### ISSUE TITLE
[feat] useMouseDistance function

### ISSUE THREAD

**Issue by Bobakanoosh** [vueuse/vueuse#1005]
I have a use-case where I need to reactively know the distance from the mouse to a given element. 

My current implementation is as follows:
```js
import { MaybeElementRef } from "@vueuse/core";
import { Ref } from "vue";

export interface UseMouseDistanceOptions {
	target: Ref<HTMLElement | undefined>;
}

const mouse = useMouse({ touch: false });

export function useMouseDistance(options: UseMouseDistanceOptions) {
	const target = computed(() => unrefElement(options.target));

	const center = computed(() => {
		if (!target.value) {
			return {
				x: 0,
				y: 0,
			};
		}

		const bounds = target.value.getBoundingClientRect();
		return {
			x: (bounds.left + bounds.right) / 2,
			y: (bounds.top + bounds.bottom) / 2,
		};
	});

	const distance = computed(() => {
		if (!target.value) {
			return { x: 0, y: 0 };
		}

		return {
			x: center.value.x - mouse.x.value,
			y: center.value.y - mouse.y.value,
		};
	});

	return { distance };
}

```

Thoughts on improvements/it being put into the library?

**Comment by okxiaoliang4** [comment]
Maybe [useMouseInElement](https://vueuse.org/core/useMouseInElement/) is what you want

**Comment by Bobakanoosh** [comment]
> Maybe [useMouseInElement](https://vueuse.org/core/useMouseInElement/) is what you want

Huh, definitely was not the place I'd think to look. Unfortunately the `elementX` and `elementY` fields are based on the top left of the element, not the center. Obviously you could absolutely position an invisible element at the center of your desired element, but that still feels hacky.

**Comment by wheatjs** [comment]
You could just use a bit of math instead to calculate to offset
Try this code below
```ts
const { elementX, elementY, elementHeight, elementWidth } = useMouseInElement(el)
const x = computed(() => elementX.value - Math.abs(elementWidth.value / 2))
const y = computed(() => elementY.value - Math.abs(elementHeight.value / 2))
```

Here is a stackblitz demo if you want to try it out https://stackblitz.com/edit/vitejs-vite-mrtvjn?file=src/App.vue
Just run `npm run dev` in the terminal

**Comment by Bobakanoosh** [comment]
Ah yeah that would do it. Thanks!
