### ISSUE TITLE
Will Rxjs be upgraded to 7.x?

### ISSUE THREAD

**Issue by rayzhao99** [vueuse/vueuse#1006]
Besides the benefits from Rxjs 7.x (such as smaller, improved typing, etc.), there are typing compatibility problems between 6.x (currently used by '@vueuse/rxjs') and 7.x (latest release of Rxjs).

There is a case for the compatibility problem. For the [Dexie.js](https://dexie.org/), a widely used IndexedDB wrapper, its `liveQuery()` API cannot be used together with the `useObservable` provided by `vueuse`, if using typescript, due to this problem. 

There might be other cases. However, since Rxjs 7.x has been released for more than half year, it might be appropriate to upgrade it now.

**Comment by antfu** [comment]
PR welcome

**Comment by rayzhao99** [comment]
We found a simple workaround, at least ok for our case. So the upgrade should be unnecessary.

The workaround is, with `from()` provided in rxjs, the incompatible Obversables defined in other modules are likely able to converted the one defined in rxjs.

An example for our case is below. As we are using [dexie](https://dexie.org/), it provided an internal `Observable` which is incompatible with rxjs, and cannot be passed to `useObservable()` directly. 
```js
import { Observable, from } from 'rxjs';
import { liveQuery as liveQueryDexie } from 'dexie';

export function liveQueryRx<T> (querier: () => T | Promise<T>): Observable<T> {
    return from(liveQueryDexie(querier));
}
```

The code above works correctly with `useObservable()`, together with rxjs v7.4.

**Comment by MatthewSH** [comment]
Can this issue be re-opened? While there is a workaround, this is still an issue with TypeScript. If I'm having to use `from` every time I was to use `useObservable` with Dexie and TypeScript it just increases code complexity for no reason.
