### ISSUE TITLE
useBreakpoints - Can we get an isActive ?

### ISSUE THREAD

**Issue by VincentVanclef** [vueuse/vueuse#1008]
Would it be possible to add an isActive(bp)/active(bp) function? Ive got a scenario where i want to render something using a list of BP's, so that would be ideal

Thanks!

**Comment by antfu** [comment]
You can have `const { sm } = useBreakpoints()` and `sm` will be `Ref<boolean>` the states it's activeness.

**Comment by VincentVanclef** [comment]
@antfu This isn't sufficient, i've made a component that renders children based on what breakpoint is active, but atm if you have 3 breakpoints (sm, md & lg), and lg is active then SM & MD is also active. Would it be possible to add an isActive?

**Comment by dheimoz** [comment]
hey @VincentVanclef , why not submit a PR so it can be evaluated by the maintainers?

**Comment by yassilah** [comment]
@VincentVanclef you're misunderstanding how breakpoints work, you can do your conditional rendering work by setting the right order for your if statements:

```vue
<script lang="ts" setup>
import { useBreakpoints, breakpointsTailwind } from '@vueuse/core'

const breakpoints = useBreakpoints(breakpointsTailwind)

const isMobile = breakpoints.smaller('md')
const isTablet = breakpoints.smaller('lg')
const isDesktop = breakpoints.smaller('xl')
</script>

<template>
<div>
  <ChildForMobile v-if="isMobile" />
  <ChildForTablet v-else-if="isTablet" />
  <ChildForDesktop v-else-if="isDesktop" />
</div>
</template>

**Comment by VincentVanclef** [comment]
> @VincentVanclef you're misunderstanding how breakpoints work, you can do your conditional rendering by setting the right order for your if statements:
> 
> ```
> <script lang="ts" setup>
> import { useBreakpoints, breakpointsTailwind } from '@vueuse/core'
> 
> const breakpoints = useBreakpoints(breakpointsTailwind)
> 
> const isMobile = breakpoints.smaller('md')
> const isTablet = breakpoints.smaller('lg')
> const isDesktop = breakpoints.smaller('xl')
> </script>
> 
> <template>
> <div>
>   <ChildForMobile v-if="isMobile" />
>   <ChildForTablet v-else-if="isTablet" />
>   <ChildForDesktop v-else-if="isDesktop" />
> </div>
> </template>
> ```

I am not misunderstanding anything, im asking for a different use-case. What if i want to render something if its in the MD and XL breakpoint, but NOT LG? Since with the above, if XL is active, LG is also active, so itll render in both, but i dont want that. I really feel this is a valid use-case.

**Comment by yassilah** [comment]
Have your tried using the existing `between` method for your specific use case:

```vue
<script setup>
const isOnlyMdOrXl = computed(() => breakpoints.between('md', 'lg').value ||  breakpoints.between('lg', 'xl').value)
</script>
```

**Comment by VincentVanclef** [comment]
> Have your tried using the existing `between` method for your specific use case:
> 
> ```
> <script setup>
> const isOnlyMdOrXl = computed(() => breakpoints.between('md', 'lg').value ||  breakpoints.between('lg', 'xl').value)
> </script>
> ```

This doesnt work as between is greater than or equals/less than or equals. Also if you have more than 2 active points, it wont suffice.

**Comment by yassilah** [comment]
`between` is `>= min` and `< max`, not `<= max`(see [this](https://github.com/vueuse/vueuse/blob/3b9a7b419fb5570d7b735159d1cc6c7e72c005c6/packages/core/useBreakpoints/index.ts#L56)).

Also, using `between` seems to work perfectly fine? You can try it out [here](https://codesandbox.io/s/quiet-dew-x3ee7?file=/pages/index.vue&resolutionWidth=1727&resolutionHeight=1080), maybe I'm misunderstanding what you're trying to achieve.

**Comment by VincentVanclef** [comment]
> `between` is `>= min` and `< max`, not `<= max`(see [this](https://github.com/vueuse/vueuse/blob/3b9a7b419fb5570d7b735159d1cc6c7e72c005c6/packages/core/useBreakpoints/index.ts#L56)).
> 
> Also, using `between` seems to work perfectly fine? You can try it out [here](https://codesandbox.io/s/quiet-dew-x3ee7?file=/pages/index.vue&resolutionWidth=1727&resolutionHeight=1080), maybe I'm misunderstanding what you're trying to achieve.

Really don't see why you favor the above implementation, itss still tedius and not really open for modification etc. Ill just stick with my 'hack' then.

Basically this is what it does:

```
import { defineComponent, computed } from 'vue';
import { breakpoints, BreakPoints, screens } from '@/styling/screens';

const breakpointsArray = Object.keys(screens) as (keyof BreakPoints)[];

const handleBreakpoints = (breakpoint: string) => {
    const bps = (breakpoint.split('-') as (keyof BreakPoints)[]);

    switch (bps.length) {
    case 1:
        return breakpoints.smaller(bps[0]).value;
    case 2:
        return breakpoints.between(bps[0], bps[1]).value;
    default:
        console.error(`Illegal breakpoint ${breakpoint}`);
        return false;
    }
};

const handleArrayOfBreakpoints = (breakpoint: string) => {
    const bps = (breakpoint.split(',') as (keyof BreakPoints)[]);

    const isBpActive = (bp: keyof BreakPoints) => {
        const index = breakpointsArray.indexOf(bp);
        const nextBp = breakpointsArray[index + 1];
        const prevBp = breakpointsArray[index - 1];

        return breakpoints[bp].value && (!nextBp || !breakpoints[nextBp].value) && (!prevBp || breakpoints[prevBp].value);
    };

    return bps.some(isBpActive);
};

export default defineComponent({
    setup(_, { slots }) {
        const activeSlots = computed(() =>
            Object
                .entries(slots)
                .filter(([breakpoint]) => {
                    const isArray = breakpoint.includes(',');
                    if (isArray) {
                        return handleArrayOfBreakpoints(breakpoint);
                    }

                    return handleBreakpoints(breakpoint);
                })
                .map(([, slot]) => slot!()));

        return () => activeSlots.value;
    },
});
```

Which allows me to use it like this:

```
<BreakPoints>
    <template v-slot:xs,sm,lg>
        <div>Visible in XS, SM & LG</div>
    </template>
    <template v-slot:md>
        <div>Visible in MD and less</div>
    </template>
</BreakPoints>
```

But its just a lot of code, and it would be nice to be able to specify exactly just 1 BP instead of greater/smaller - I really don't understand why your trying to fight this xD an isActive just seems so logical, if its because its not do-able then i completely understand (i havent looked into the implementation of this library yet)

**Comment by yassilah** [comment]
chill ya habibi, sorry for trying to help you out! 

i'm not favoring anything and really don't care how you end up doing it, I was simply trying to find a not-so-hacky way for you to achieve what you wanted with what's already implemented. Feel free to submit a PR if you think it could be useful for someone else 🙂

**Comment by VincentVanclef** [comment]
I am completely chill, just confused as to why your trying to make something work that doesnt follow the basic open/close principle - having to hard-code the individual breakpoints for functional usage is bad. But thanks for your attempt anyway :-)
