### ISSUE TITLE
useThrottle trailing = true;  leading = false; the first time cannot be executed

### ISSUE THREAD

**Issue by mangbu2017** [vueuse/vueuse#1013]

**Comment by harmyderoman** [comment]
Yeap. It's buggy in docs. Is it also buggy in your local project?

**Comment by harmyderoman** [comment]
It seems like this issue was fixed in the docs on the site.

**Comment by mangbu2017** [comment]
local 7.2.2 when i set useThrottle(search, 500, true, false); after input some letter, only input once，it won't work 
i set leading=false, but trailing is true , i thinking it should trigger once 
sorry, my english is poor

**Comment by harmyderoman** [comment]
I got you. The bug fix is on the way.
