### ISSUE TITLE
feat request: dynamic size virtual list

### ISSUE THREAD

**Issue by chu121su12** [vueuse/vueuse#1017]
Requesting #710 without the itemHeight prop.

If this feature is rarely used/heavy on resources, could anyone give some suggestion on a height callback function to achieve similar effect?

**Comment by JessicaSachs** [comment]
Hmm, `itemHeight` is also available as a function, if this is what you mean by "height callback function". The documentation only says it's a number, but that's incorrect.

```ts
// From useVirtualList/demo.vue
const { list, containerProps, wrapperProps, scrollTo } = useVirtualList(
  filteredItems,
  {
    itemHeight: i => (filteredItems.value[i].height + 8),
    overscan: 10,
  },
)
```

<img width="605" alt="Screen Shot 2021-12-23 at 12 48 20 PM" src="https://user-images.githubusercontent.com/2801156/147275721-8c5567d4-288c-4f05-8f92-8a01f809e7e6.png">

If this isn't what you want, can you send a link to an existing component lib/implementation that shows off the behavior you're looking for?

**Comment by chu121su12** [comment]
I have read the source for the types of `itemHeight` option. I think I should use the `getComputedStyle` to read the element size,

> If this isn't what you want, can you send a link to an existing component lib/implementation that shows off the behavior you're looking for?

The one I'm using right now is https://github.com/Akryum/vue-virtual-scroller#variable-size-mode.

**Comment by JessicaSachs** [comment]
Right. You want the ability to be able to do things like render an
expandable accordion or other kinds of dynamically resizing items. Kk.

**Comment by chu121su12** [comment]
My usecase mostly is for select items with styled, long wrapping text. But I'm sure this will benefit more complex cases.

**Comment by boyaboya233** [comment]
I have same situation. I tried to init useVirtualList itemHeight after async operation, e.g after Pdfjs page viewport.height. but it seems doesnot work. containerRef.value always be undefined

**Comment by reslear** [comment]
any news?
