### ISSUE TITLE
useClipboard can't work on nuxt3 ssr mode

### ISSUE THREAD

**Issue by liuqian1996** [vueuse/vueuse#1020]
useClipboard can't works on nuxt3 ssr mode

it works in local, but in linux server can't

**Comment by okxiaoliang4** [comment]
方便上一下示例代码吗

**Comment by liuqian1996** [comment]
[repo](https://github.com/liuqian1996/test-vueuse-use-clipboard)

我看到 `isSupported` 的值是 `false`，不知道为啥是 false

<img width="322" alt="image" src="https://user-images.githubusercontent.com/11707934/145342901-0e4a442e-9a57-49a2-9687-0d71d99aa139.png">

**Comment by okxiaoliang4** [comment]
![image](https://user-images.githubusercontent.com/22525904/145343887-f7fc9e70-8008-4ee6-ba15-21e75af6eec1.png)

我用你的demo看是可以的哦，你的浏览器不支持 clipboard api吧

**Comment by okxiaoliang4** [comment]
示例代码我本地run也没问题，我试下服务器上跑下看看

**Comment by liuqian1996** [comment]
百思不得其解，如果服务器上有问题，那本地也应该有问题才对

**Comment by webfansplz** [comment]
> @okxiaoliang4
> 
> [repo](https://github.com/liuqian1996/test-vueuse-use-clipboard)
> 
> 我看到 `isSupported` 的值是 `false`，不知道为啥是 false
> 
> https://github.com/vueuse/vueuse/blob/0dfae4c7d69e3c59dae3dcd3c7172b39d4a5b125/packages/core/useClipboard/index.ts#L53
> 
> <img alt="image" width="322" src="https://user-images.githubusercontent.com/11707934/145342901-0e4a442e-9a57-49a2-9687-0d71d99aa139.png">

触发`useClipboard `的时机是在服务端,`navigator `对象在服务端不存在所以不支持,可以试试在`onMounted`钩子中调用

**Comment by okxiaoliang4** [comment]
> 

如果是这样的话那我本地build完后start应该可以复现他所说的这种情况，但是我本地也无法复现

**Comment by liuqian1996** [comment]
> > @okxiaoliang4
> > [repo](https://github.com/liuqian1996/test-vueuse-use-clipboard)
> > 我看到 `isSupported` 的值是 `false`，不知道为啥是 false
> > https://github.com/vueuse/vueuse/blob/0dfae4c7d69e3c59dae3dcd3c7172b39d4a5b125/packages/core/useClipboard/index.ts#L53
> > 
> > <img alt="image" width="322" src="https://user-images.githubusercontent.com/11707934/145342901-0e4a442e-9a57-49a2-9687-0d71d99aa139.png">
> 
> 触发`useClipboard `的时机是在服务端,`navigator `对象在服务端不存在所以不支持,可以试试在`onMounted`钩子中调用

如果是这样的话，那应该不区分 Windows 和 Linux 的，但事实是我本地 Windows 可以，只是 Linux 不行

**Comment by okxiaoliang4** [comment]
@liuqian1996 我用项目内的docker跑起来看也无法复现，你试下docker下跑呢？

**Comment by liuqian1996** [comment]
@okxiaoliang4 我本地和 docker 里面都没问题，就是部署到服务器不行

**Comment by okxiaoliang4** [comment]
emmmm，你服务器能外网访问吗，可以加个`debugger`瞧一眼?我一会也试试丢我服务器上看看，现在在忙，得一会才有空

**Comment by liuqian1996** [comment]
> @okxiaoliang4
> 
> 触发`useClipboard `的时机是在服务端,`navigator `对象在服务端不存在所以不支持,可以试试在`onMounted`钩子中调用

我把 `useClipboard` 放到 `onMounted` 钩子下面，本地可以，服务器上不行

![image](https://user-images.githubusercontent.com/11707934/145360951-3dbae2a9-8d26-4b8b-8ca6-ae5a34d2dd7b.png)

**Comment by liuqian1996** [comment]
> emmmm，你服务器能外网访问吗，可以加个`debugger`瞧一眼?我一会也试试丢我服务器上看看，现在在忙，得一会才有空

加了个 debugger [go](http://47.106.14.109:8085) 你可以瞅瞅

**Comment by okxiaoliang4** [comment]
我有个想法，可能是clipboard api只能在local或者https下才能工作？我查查文档看看

**Comment by okxiaoliang4** [comment]
![image](https://user-images.githubusercontent.com/22525904/145363127-52ea8b4c-bacf-4e88-8c74-be86c50bd40c.png)
在你的链接中可以看到`navigator`确实没有`clipboard`属性

**Comment by liuqian1996** [comment]
@okxiaoliang4  确实，`localhost `可以，`192.168.x.x` 不行

**Comment by okxiaoliang4** [comment]
确实，本地dev的时候如果使用的是ip的链接，也没有`clipboard`属性,可以基本确认就是local和https才有clipboard api

**Comment by liuqian1996** [comment]
@okxiaoliang4 @webfansplz 谢谢

看来要么加 https，要么换 `clipboardjs` 了
