### ISSUE TITLE
Question about using @vueuse/integrations

### ISSUE THREAD

**Issue by mishka86** [vueuse/vueuse#1021]
When ssr:true in nuxt.js environment
I tride to install because I wanted to use the useAxios function in @vueuse/integrations
However, the message below was exposed.
Cannot find module '@vueuse/integrations/useAxios' 

npm i @vueuse/integrations
npm i axios

Is there anything else i need to do other than the above actions?

**Comment by checkwoodson** [comment]
you need import 
For example:
import {useAxios} from '@vueuse/integrations/useAxios'

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
