### ISSUE TITLE
inject() can only be used inside setup() or functional components.

### ISSUE THREAD

**Issue by ArgekarStudios** [vueuse/vueuse#1061]
**I have created a new ts file auth.ts**

import { useRouter } from 'vue-router'
const router = useRouter()
export function signInwithGoogle() {

    router.push('/user')
 
}

**I am getting errors like inject() can only be used inside setup() or functional components.**

**Comment by adlawan** [comment]
Asphalt sureface civil drainage earthwork demolition please call us for more 02246339059

**Comment by freakzlike** [comment]
`useRouter` has to be within a the `setup` method of a component, because if using multiple vue instances, then `useRouter` does not know for which vue instance you want the router.

try something like this in your auth.ts

```typescript
import { useRouter } from 'vue-router'

export const useAuth = () => {
  const router = useRouter()
  return {
    signInWithGoogle: () => {
      router.push('/user')
    }
  }
}
```

then in your components:
```vue
<template>
  <button @click="signInWithGoogle">Login<button/>
</template>

<script setup lang="ts">
import { useAuth } from './auth'

const { signInWithGoogle } = useAuth()
</script>
```

**Comment by ArgekarStudios** [comment]
@freakzlike 
Thanks a lot 
That worked perfectly thanks for the solution...
