### ISSUE TITLE
onClickOutside, events bubbles on touch devices

### ISSUE THREAD

**Issue by reinoldus** [vueuse/vueuse#1066]
If you want to use "onClickOutside" as a listener for an click outside of a modal the following issue occurs:

In the following image the green area is a backdrop and the red area is the modal content:
![image](https://user-images.githubusercontent.com/2091290/146147436-9323f068-ccdb-425c-b4db-090435fd9594.png)

On Mouse devices:

If you click on the backdrop, right over the "trigger button" area, the modal closes and stays closed.

If you do the same on touch-devices the modal closes and then reopens, because the event kind of bubbles up. Can be emulated with developer tools

I've tried it with: "pointerup" and "touchend" both events retrigger the backdrop.

Theoretically I could call "preventDefault()", but onClickOutside creates the events as "passive" and therefore you can't call that method.

I might be missing something, but one solution could be to make "passive" configurable.

Reproduction on vueuse playground: 
[Click](https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDgBdZhGOgGM1oUAAQTAYEmC3QoFSuoMEFSRAAPFRsioADrYAB8OZUKlTpQCCXM5ygQVgAF4syBK3RYHXcwB5AAKAFEAHIqAAqACUAJIAcWHHf7qeGJf68nz5iLGeIKgrVZgtfrq4AsqwqIY6ypiBQ6EZ1-dWJF98hQiH1wAvI+0xCbNCUslvgDcpWgQg47FpFBmLwODQR53z1A1FTQGo6E2EF3xDIxpDQYkyQAUnfBIwCglD0KSOgqGkXQoNfMkwE2d9dEQOh4D6F83zI9992sE861SK9mwLQsVF0OhOMnRc5y4hdM0PY9T10c9904wsrxCG86y-WB4F-fgqAA2U6jQZTEBsd9vGgYIQjQCliTA-VDWwKCIFKNgDACRB4MQRDjIw7woLJd88IIoiVBI9DKOo2i-MYkBBK4ni+OGASc347Jc2eMVpCIOhdTqaQVGAfwbm3PFGBUeQpVXFsAgNGgVAOGpfzwFQAHJnRuHk6kQGqcxSvUOHS4BmIqowqtqhZqE0FqslSjrtVYOoM1wVJKtmWrJmGGVJrMZNEBjchhpzGZsCvDKVE2PKwgq6sssQHKbm0ewcy2+RdrY9KTuY7RsFICIrtsW70rPSIVEepztGkDhyHenMCqKkr8MQAGUGkPLLt+3MMs47bbLWrx4G0OspSKQcpQAaQ7NQVBbdJewBQc1A7Ot3pkiTIhjQxVBOgBCb6Gbshyc1ZTiasQDx1RqqCar1MxUiBsBhoOEHsCMfgFQlFQG1geHgGR27ZTR1gMbrdtuxUAAhUnexbLs60YNniEZxAaZUC2rd++Igc57ADmumW5cVRWtx3QxtD5xxVfnPnJjAax+ekDQjAgV7pEutWdo1yZ0cxkABxHMd+xUTcWzUcMimprmWWYJaOCm1b1p4eNaDAJMU14dNsk42p1XXPB5FYOtONKeB1yCGjpAoFCyTcSoYDQXcOBgQe307+cjBDTZ1wAP0V2VZ8LVJNmkdduHVRAOHXlQwHXRpD9KSb9-XFTHyoWewtTZBIHMTft7rAAWTYDGbYBMstjnyoOJOR+EA8x8WAc-J8r8WDVQnmPPufQKAAE43wj0nmgfSUBDLT33HgdcA9T6hXOmkH+KgkylE8AAoBT85yxWIPFZg4hJAyGSqNTqbgnJmEQG2X8gxyqzWqjVBYm1HxBmwFwnhyBtCB0LGQzwUEASA18IwTif9yBQS7KQPA5CODKJdvYFkBwDhAA)

**Comment by reinoldus** [comment]
I rechecked the vueuse playground and it doesn't happen anymore. I'll keep investigating and reopen in case it's necessary. Sorry for the spam!

**Comment by reinoldus** [comment]
Okay, I copied the wrong playground link, reopening.

**Comment by sibbng** [comment]
First of all, the `@vueuse/core` version loaded in this Playground is v5, current latest version is v7. Also `event` option removed in v7 and this issue doesn't happen in v7.

Closing this for now since it's not an issue with current latest version. 

Playground may need to be updated /cc @wheatjs
