### ISSUE TITLE
Uncaught Error: Dynamic require of "vue-demi" is not supported

### ISSUE THREAD

**Issue by Cabbages** [vueuse/vueuse#1069]
Not sure if it's a `@vueuse` issue

# Environment

- Operating System: Windows_NT
- Node Version: v16.13.0
- Nuxt Version: 3.0.0-27324955.23397e6
- Element-Plus version: 1.2.0-beta.6
- Package Manager: pnpm@6.24.1
- Bundler: Vite
- User Config: -
- Runtime Modules: -
- Build Modules: -

# Reproduction

```shell
git clone https://github.com/element-plus/element-plus-nuxt-starter.git

cd element-plus-nuxt-starter

pnpm install

pnpm run dev

# Browser access: http://localhost:3000
```

touch `package.json`

```json
{
  "private": true,
  "scripts": {
    "build": "nuxi build",
    "dev": "nuxi dev",
    "start": "node .output/server/index.mjs",
    "generate": "export NITRO_PRESET=browser && npm run build"
  },
  "dependencies": {
    "pinia": "^2.0.5"
  },
  "devDependencies": {
    "@pinia/nuxt": "^0.1.6",
    "element-plus": "1.2.0-beta.6",
    "nuxt3": "3.0.0-27324955.23397e6",
    "sass": "^1.44.0",
    "typescript": "^4.5.4"
  },
  "pnpm": {
    "overrides": {
      "@nuxt/kit": "npm:@nuxt/kit-edge@3.0.0-27324955.23397e6",
      "@nuxt/kit-edge": "3.0.0-27324955.23397e6",
      "@vueuse/core": "7.3.0",
      "@vueuse/shared": "7.3.0"
    }
  }
}
```

# Describe the bug

```javascript
Uncaught Error: Dynamic require of "vue-demi" is not supported
    at chunk-EABY2BFN.js?v=9c4aff8c:26
    at node_modules/.pnpm/registry.npmmirror.com+@vueuse+shared@7.3.0/node_modules/@vueuse/shared/index.cjs (index.cjs:5)
    at __require2 (chunk-EABY2BFN.js?v=9c4aff8c:32)
    at node_modules/.pnpm/registry.npmmirror.com+@vueuse+core@7.3.0/node_modules/@vueuse/core/index.cjs (index.cjs:5)
    at __require2 (chunk-EABY2BFN.js?v=9c4aff8c:32)
    at node_modules/.pnpm/registry.npmmirror.com+element-plus@1.2.0-beta.6/node_modules/element-plus/lib/hooks/use-modal/index.js (aria.ts:178)
    at __require2 (chunk-EABY2BFN.js?v=9c4aff8c:32)
    at node_modules/.pnpm/registry.npmmirror.com+element-plus@1.2.0-beta.6/node_modules/element-plus/lib/hooks/index.js (index.js:12)
    at __require2 (chunk-EABY2BFN.js?v=9c4aff8c:32)
    at node_modules/.pnpm/registry.npmmirror.com+element-plus@1.2.0-beta.6/node_modules/element-plus/lib/make-installer.js (version.ts:1)
```

# Additional context

No response

# Logs

No response

**Comment by Cabbages** [comment]
When I rolled back `vite` to `2.6.14`，The problem will not arise。

**Comment by antfu** [comment]
Can't produce on https://github.com/antfu/vitesse-nuxt3

**Comment by Cabbages** [comment]
I used `Vitesse-NuxT3` and found no problems. 

I found this problem when I used  `Element-Plus`: https://stackblitz.com/github//Cabbages/element-plus-nuxt-starter

**Comment by xiaoxian521** [comment]
I guess the problem is caused by the @vueuse/core dependency installed inside element-plus？
https://github.com/element-plus/element-plus/blob/dev/package.json#L62

**Comment by michael-observerly** [comment]
I can confirm that this issue is happening as well with the latest version of Nuxt, and any composition API library built on /with @vueuse/core ...

**Comment by calebeaires** [comment]
Hope you guys find some way to overcome this issue!

**Comment by manojap** [comment]
I still have the issue

**Comment by ZuulAndRibbon** [comment]
I have the same issue,how to solve?

**Comment by mlsjla** [comment]
I have the same issue

**Comment by xiaoxian521** [comment]
Just put `@vueuse/core` as a dependency, will get the error `Dynamic require of "vue-demi" is not supported`
Is there any good solution please?
@antfu

**Comment by hzm18** [comment]
same problem. element-plus cannot be use in nuxt3 now.

**Comment by xiaoxian521** [comment]
The reason for this problem is that the dynamically calculated style is not loaded
abnormal：
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/44761321/154972840-9f6353a5-d569-4f9d-b260-1236b66fba68.png">
normal：
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/44761321/154972978-ead298c1-d733-4dcd-ab00-c8086ff204c3.png">

Specific code
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/44761321/154972609-51746d31-4520-4be8-9cc3-ef866be7d813.png">

**Comment by xiaoxian521** [comment]
> same problem. element-plus cannot be use in nuxt3 now.

Already fixed：https://github.com/element-plus/element-plus-nuxt-starter/commit/98aa178d5031359d67653e1b5f5f7611ab94ca1f
