### ISSUE TITLE
Suggestion: CachedRef

### ISSUE THREAD

**Issue by davidboom95** [vueuse/vueuse#1071]
Hi!

I love this library. I would like to suggest a utility called CachedRef().

```ts
const source = ref()
const [expired, cached] = cachedRef(source, {cache: 1000})
```

I would like to submit a PR in a few weeks, but if anyone wants to get ahead, it would be ok.

**Comment by wheatjs** [comment]
Could you give more details on how this would work?

**Comment by stefnotch** [comment]
@davidboom95 Any update regarding this?
