### ISSUE TITLE
useFetch全局实例中beforeFetch拦截options.method的问题

### ISSUE THREAD

**Issue by xiang12383** [vueuse/vueuse#1077]
V7.4.0

使用实例全局拦截`options.method`

`createFetch({ 
  options: {
     beforeFetch({ options }) {
        console.log(options.method)
      return { options }
    },
  }, 
})
`
1. 情况一，options.method 显示为 'POST'
`useFetch(url,{
method:'POST'
});`
2. 情况二，options.method显示为undefined
` useFetch(url).post()`

想问，对于情况二，可否和情况一一致显示'POST'?有时候确实需要对情况二的.post进行拦截。

再次感谢作者为大家提供很好用的vueuse

**Comment by gp3098** [comment]
import { createFetch } from '@vueuse/core'
import Coordinate from './Coordinate.vue'
const useRequest = createFetch({
  baseUrl: 'https://play.vueuse.org',
  options: {
    async beforeFetch({ options, url }) {
      if (options.params) {
        options.headers['Content-Type'] = 'application/json;charset=utf-8';
        options.body = JSON.stringify(options.params);
      }

      return { options, url };
    },
  },
  fetchOptions: {
    mode: 'cors',
  },
});

const  {execute} = useRequest('/fetch',{
method:'POST',
immediate:false
})

execute();

我发现在不加immediate的时候发出去的请求是POST
但是我加了immediate后就会变成GET请求，参数也会丢失，请问这个有解决办法吗？是我的用法不对吗？

**Comment by AllenYu0118** [comment]
#1403
