### ISSUE TITLE
useWebSocket 无限重连

### ISSUE THREAD

**Issue by KNJON** [vueuse/vueuse#1079]
当设置了自动重连后，
```
autoReconnect: true,
```
服务端校验不通过，服务端主动close，然后就触发了重连机制，
然后又不通过，又重连
...
哪怕我主动调用close(),也没法停止重连,跳转到其他页面也一直重连，必须刷新才可以停止

**Comment by StevenJPx2** [comment]
I think the latest release fixes this 
https://github.com/vueuse/vueuse/pull/1137
