### ISSUE TITLE
new function usePagination

### ISSUE THREAD

**Issue by okxiaoliang4** [vueuse/vueuse#1080]
I createing new function `usePagination`. The initial idea is this.

```typescript
const {
  currentPage,
  loading,
  maxPage,
  data,
  isLastPage,
  nextPage,
} = usePagination<User>([],
  (page: number, pageSize: number) => {  // fetch Data
    return  // any[] 
  },
  {
    total: database.value.length,
    immediate: true,
    initialPage: 1,
    pageSize: 10,
  },
)
```

**Comment by wheatjs** [comment]
Nice, also maybe we could consider adding a component version of this?

**Comment by michael-observerly** [comment]
This would be very, very useful. Would it take an array of unknown ... accepting any type `<T[]>`

**Comment by okxiaoliang4** [comment]
> Nice, also maybe we could consider adding a component version of this?

ok,Thanks for the suggestion.

**Comment by okxiaoliang4** [comment]
> This would be very, very useful. Would it take an array of unknown objects / elements to paginate ... accepting any type `<T[]>`?

Yes.

**Comment by okxiaoliang4** [comment]
#1104
