### ISSUE TITLE
New function `nextFrame`

### ISSUE THREAD

**Issue by Byloth** [vueuse/vueuse#1090]
Why don't add a simple & small function to promise the next frame update based on `requestAnimationFrame`?

You already did same sort of this with the function `promiseTimeout` here: https://github.com/vueuse/vueuse/blob/main/packages/shared/utils/index.ts#L5-L16

---

A possible example of this new function:
```typescript
export function nextFrame(
    throwOnNextFrame = false,
    reason = 'NextFrame',
): Promise<void> {
    return new Promise<void>((resolve, reject) => {
        if (throwOnNextFrame)
            requestAnimationFrame(() => reject(reason));
        else
            requestAnimationFrame(resolve);
    })
}
```

**Comment by dheimoz** [comment]
@Byloth I believe PR's are welcome here mate.

**Comment by Byloth** [comment]
Of course, they are...  
It would be great to contribute to this project and appear in the "Contributors" section! 😉
  
I just followed the [`CONTRIBUTING.md`](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md?plain=1#L31) and opened a new Issue...  
Do you think I can directly open a new PR, in this case? 🤔
