### ISSUE TITLE
Module @vueuse/core has no exported member useScroll

### ISSUE THREAD

**Issue by annndddy** [vueuse/vueuse#1118]
Version: 
"vue": "^3.2.26"
"@vueuse/core": "^7.5.1",

Code:
import { useScroll } from '@vueuse/core'
import { ref } from 'vue-demi'

const el = ref<HTMLElement | null>(null)
const { x, y, isScrolling, arrivedState, directions } = useScroll(el)

Thanks

*usable but visual studio code ts will prompt warning

**Comment by webfansplz** [comment]
I can't reproduce it, can you provide a mini repo ?

And then reopen issue if you still has this probrem .
