### ISSUE TITLE
How to use emits in typescript with useVmodel

### ISSUE THREAD

**Issue by ArgekarStudios** [vueuse/vueuse#1121]
can anyone help me with the demo of emits in typescript with useVmodel

**Comment by wheatjs** [comment]
This is too vague for us to help you with. Please provide more information about what you need help with for us to reopen. If you are wondering about the usage of useVModel, check this discussion https://github.com/vueuse/vueuse/discussions/856

**Comment by ArgekarStudios** [comment]
@wheatjs  thanks for the discussion id that solved my issue
