### ISSUE TITLE
`useStorage` doesn't work well with `localStorage.clear()`

### ISSUE THREAD

**Issue by filipsobol** [vueuse/vueuse#1129]
I have a case in which I have to remove everything from `localStorage`. The most straighforward way is to call `localStorage.clear()`, but I noticed it doesn't work well with `useStorage`.

I created a repo to reproduce this issue: https://github.com/filipsobol/repro-localStorage

Calling [clearLocalStorage](https://github.com/filipsobol/repro-localStorage/blob/main/src/App.vue#L26-L30) for the first time works as you would expect. It removes old entry from `localStorage` and adds new one with value of `SET AFTER CLEARING`.

But, when it's called the second time, entry disappears. If you call it twice fast (by clicking the button) it will add entry with correct key, but empty value.

(In my project, it doesn't even work for the first time. I'm not sure why it does here)

**Comment by filipsobol** [comment]
> that because it use vue watch the state，when state stateted same value，the watcher will not be trigger

This sounds like a sensible default, but it would be nice to be able to get around this somehow.

**Comment by harmyderoman** [comment]
Apparently, this looks like a bug. For a temporary solution, you can change your `clearLocalStorage` function like this:
```
    function clearLocalStorage() {
      localStorage.clear()
      state.value = ''
      state.value = 'SET AFTER CLEARING'
    }
```
