### ISSUE TITLE
useRefHistory: history stops reacting to changes when it was created dynamically

### ISSUE THREAD

**Issue by ga676005** [vueuse/vueuse#1131]
I want to use `useRefHistory` to keep track of a specific route, then I ran into this issue where history stops reacting to changes. 
I tried to limit the scope and made an example which is similar to the issue I have. 
I am not sure if this is a bug or I do it wrong.
Please let me know if I need to address in more details. Thank you.

testUseRefHistory.js
`useMyHistory` takes an initial value and call `setup()` to create a history using `useRefHistory` and store it into the variable `refHistory`.
```js
import { ref } from '@vue/reactivity'
import { useRefHistory } from '@vueuse/core'

const count = ref(0)
let refHistory

function setup(value) {
  count.value = value
  refHistory = useRefHistory(count)
}

export function useMyHistory(value) {
  if (!refHistory) setup(value)

  function add() {
    count.value++
  }
  return { refHistory, count, add }
}
```

TestUseRefHistory.vue
use the `useMyHistory`, 
in my real use case, the parameter `5` would be `route.path`
```vue
<script setup>
import { useMyHistory } from '@/stores/testUseRefHistory'
const { refHistory, add } = useMyHistory(5)
</script>

<template>
  <div>
    <div>
      {{ refHistory }}
    </div>
    <button @click="add">
      add
    </button>
  </div>
</template>
```

App.vue
use v-if to toggle the component to simulate when a component is created on route change. 
```vue
<script setup>
  const show = ref(true)
</script>

<template>
  <TestUseRefHistory v-if="show" />
  <button @click=" show = !show">
    toggle
  </button>
</template>
```

When toggle button is clicked and `TestUseRefHistory` is created for the first time, history is also created. the value of `refHistory` is correct.
![image](https://user-images.githubusercontent.com/51456572/148338012-f8edd25a-6d21-41bb-b2c2-d15c7b136df1.png)

and it reacts to the changes triggered by `add()`
![image](https://user-images.githubusercontent.com/51456572/148338079-ec23a4c7-a82a-456f-aec2-18a55e6cda5c.png)

but when toggling `TestUseRefHistory` off and on again, now only `refHistory.source` is reactive to `add()`, other properties of `refHistory` stops working.
![image](https://user-images.githubusercontent.com/51456572/148338558-1509e477-ad0f-4d8c-908d-f0403965e781.png)

testUseRefHistory.js 
I've found that the main issue is from I call `useRefHistory()` inside `useMyHistory`.
So I call `useRefHistory()` outside of `useMyHistory` and create an initial flag to reset the history when `useMyHistory` is called for the first time as a walkaround.
```js
import { ref } from '@vue/reactivity'
import { useRefHistory } from '@vueuse/core'

const count = ref(0)
const refHistory = useRefHistory(count) 
const init = ref(true)

export function useMyHistory(firstValue) {
  if (init.value === true) {
    count.value = firstValue
    refHistory.clear()
    init.value = false
  }

  function add() {
    count.value++
  }
  return { refHistory, count, add }
}
```

**Comment by patak-dev** [comment]
This isn't a bug. In your reproduction, you are using `useRefHistory` inside the setup of a component, so every watch and effect inside it ends up tied to the lifetime of the component. Your workaround isn't a workaround, it is correct in this case. At least for a simple app that you don't intend to be able to use as a component later. If you want the history to be tied to a particular component tree so you can use it as a component, you can make sure to call useRefHistory in the root of that tree, and you can use provide/inject (or pinia for example to manage the global state in more general way)

**Comment by ga676005** [comment]
Oh! Thanks for pointing out the difference where I call `useRefHistory`. Appreciate your help!
