### ISSUE TITLE
cant build anymore in 7.5.3 but can in 7.5.2

### ISSUE THREAD

**Issue by JonasWijne** [vueuse/vueuse#1135]
@antfu and @macheteHot  can you check if this is right, it looks like  ShallowRef should be shallowRef,

I get the error 
```
node_modules/@vueuse/core/index.d.ts:5:67 - error TS2724: '"vue-demi"' has no exported member named 'ShallowRef'. Did you mean 'shallowRef'?
```

_Originally posted by @JonasWijne in https://github.com/vueuse/vueuse/pull/1119#issuecomment-1007706055_

**Comment by JonasWijne** [comment]
see https://github.com/vueuse/vueuse/pull/1119

**Comment by JonasWijne** [comment]
tried with 7.5.2 and it builds / compiles, in 7.5.3  it gives following error.
using vue ts with vite

```
$ vue-tsc --noEmit && vite build
node_modules/@vueuse/core/index.d.ts:5:67 - error TS2724: '"vue-demi"' has no exported member named 'ShallowRef'. Did you mean 'shallowRef'?

5 import { Ref, InjectionKey, ComputedRef, ComponentPublicInstance, ShallowRef, UnwrapRef, ToRefs } from 'vue-demi';
                                                                    ~~~~~~~~~~
Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by macheteHot** [comment]
can you give a test case?

**Comment by macheteHot** [comment]
> tried with 7.5.2 and it builds / compiles, in 7.5.3 it gives following error. using vue ts with vite
> 
> ```
> $ vue-tsc --noEmit && vite build
> node_modules/@vueuse/core/index.d.ts:5:67 - error TS2724: '"vue-demi"' has no exported member named 'ShallowRef'. Did you mean 'shallowRef'?
> 
> 5 import { Ref, InjectionKey, ComputedRef, ComponentPublicInstance, ShallowRef, UnwrapRef, ToRefs } from 'vue-demi';
>                                                                     ~~~~~~~~~~
> Found 1 error.
> 
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

can you give a test case?

**Comment by JonasWijne** [comment]
sure , here is our frontend boilerplate https://github.com/jimbertools/frontend-boilerplate

**Comment by macheteHot** [comment]
> sure , here is our frontend boilerplate https://github.com/jimbertools/frontend-boilerplate
> 
> just pull, yarn install and yarn build

It is you vue-demi version old you can check yarn.lock 1912 len the version is 0.11.4 you can delete lock file and node_modules and reinstall to fix it

**Comment by JonasWijne** [comment]
works, thx
