### ISSUE TITLE
useElementBounding does not seem to be reactive

### ISSUE THREAD

**Issue by everettblakley** [vueuse/vueuse#1136]
# Summary

I am new to VueUse and the Composition API, so perhaps this is my misunderstanding, but I cannot seem to get the proper results from `useElementBounding`

Here's basically what I'm trying to create:

![NavBarExample](https://user-images.githubusercontent.com/39717736/148848779-e943e582-607d-4001-bfdb-7d5dbd67e85e.png)

I am trying to use `useElementBounding` to check for when the middle `nav` section intersects with the "logo" on the left, or with the dropdown on the right. If it intersects, it goes into collapsed mode. If it still won't fit in collapsed mode, we'll show the hamburger.

However, `useElementBounding` does not seem to update when the page size changes. 

I have an example from the VueUse Playground [here](https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxpBA6AZIhsoMhUMxur1+tbRlAqNhJsgYCFILBJu5hiGwxHaVGY6JRZJxf9eABBKFh4IhChGOi5aTagEAmoVAiROowGp1FQVHxUAxhUqkMNUXwqKDXBJ4fw3epmVIcIzQOEiHIGysgIoQVLIaT815ndOZ6AwFkAXWYTYMZrQoCrYDAkwW6FAqV1BgPZwAPLoiAQDQ9RQL+0YALwADogJEjakBENQPpspjfsgFDcOqiD1GAmwUAALCoYANs0pTwBQkS6MEaTWL+sgeLBAB80HmCo-5TsQg6IEYMEgOUEC0kUrDwKwsEzhByB8fBADsKi6BQcnkRQGx0KJFDtGSZKDuwtIgsx-7DJxLFsf+uBcdYvGweZsGsSo9kSRAUGwXhhHEQ22kQKUbAGAEaQJGAFDUs0D5GNIQXDM00gVNgyC1BwC4UNFgnIPRlD4cFKhJTFqV-hQDaZTReAYVhq4qLsc50EYDalThSQUPQ5jIFm6UUM0RgobZbH2Wg4FOVJsGsDkv6vtOAD8KgAOTKY8bVaZNKhoFNynwNYNhzWSk3MXZDlmRAxAqd+Kg7Q5KgHfFfHAHQVCMCov6lJ4t2QNIugHKY5hBNgMDIOJJ0OWgMCICEfHXV1p09fdnh8ZDBhg+DaDPbofGI793X-TMEQQIMIJ8UNOEjT42DwHD9nDCZ9mGeZ5PseZh20NxVmiBw3hUKwkTYOJMN8QAUvI2BhC+YAPjc+kgMRB5I7BADE4l9c5IB4AYFAQAEYkgGTrGGUBIE4SZ-5gExACSzh44iWOE-AS3AMApsE74BwHIZBuawb5mTKF0hW8AKjmQASvK0juzxrYO07esG14omTJI8B9F7d0iaw-sKtHal9CoofDM72D60xbsx3HKjWz7+3J4HBch47Wfh0xBDYKQqex57Rfe3XpBl0HYUZ1X2ccdkjny9RVA0BzIDU-+ACEFAUCoAByiAgvEiRgAE8RAZCQHWP29RHiED7EZw8DTtP49gAPA38RRs2NFpzH+1QYc7fr598Sta3YBtzEAOLv0xj850ZbITFnhimPLwOguo6itm9pZW6WIV6pButxaADE0hvSMMzBck0FhbSyJAjg0D4i0CFn+f2Rhbp4gAKIPjrtIAAQrpKcRMM6dlmFNZ0NweR1EQLgiBeoCFz32obI6GC2GTUmMMWeQjvzvnILg1iMxYqtnMioSCRCfykJ4toSa5lJr2AUfII8KgBJCUTqo9RJDUhkO0SYqgwlRJ6IMUotwzMwCs3ZuY78ljEDWMmlQVx7jsCOI5rYQxyjS4B3MdYFB2REDaCoTQmw9DGG+G0OZew+jQnOMjknSJajokKlifEm41DaBJIYfwJh8BtC2PsawDJTijFtzLlE4ChSPDFMQKU2hFTaSpP8SzNm2AGkhMUUY225tpxqPgX5Kg2htCOEgkxEuxAO4e3YmonJHcK4qAAD67JWdstOrYmJqOaQHTu0hMmNNbJ9b6rSjDaAwDtb210lpklujDJak0AASsweFPQlt84YC0jgvNMFQJalJPleU8N8qspR2DSEmoCl6wKvJItBYwcFbyVCNBhQ9Aw3yAAKUDahBFYCi8WaKppZzJbKOQWKcWQo6ASuFU0ZTqhQVSxGwLFEhgVKC1i157AsmYFI4gwjaCyJ4F+YhaUiD-lcLoSyfEZZizQFQA8EAKAqp4sjCW21TJnzlhfVylJ3IUApMSYxFFVLqU0tpZmlTF6pE2OFVaEAGwAA4tL9nVA1EEdBSALjdeFZAeAjWnWLhjEaNxQQTVjVjeN+5CWLTurCgw3cn7V01sMCAwDmDiHLGAkAfCoFFxnLMBBIJboJDISw0RWCcGsRucRVxzg1E0CbNgRAxKO3aGADtL5KgATRV8NitivLR3jqJpO+ySbsYsoYbKYCISDjXKyUYmGnjcmPLAB226k0YbBLbYulNmbzEzMQfMxZyyYbvkMOQDAZIRUsgdkAA)

In the script

```javascript
const nav = templateRef('nav')
const brandLogo = templateRef('brandLogo')
const dropdown = templateRef('dropdown')

const navRect = reactive(useElementBounding(nav))
const logoRect = reactive(useElementBounding(brandLogo))
const menuRect = reactive(useElementBounding(dropdown))

const overlapping = computed(() => navRect.left <= logoRect.right || navRect.right >= menuRect.left)
```

Where `overlapping` is used to determine if each link should be collapsed or not, but the `navRect` objects don't seem to be updating. Am I doing something wrong?

https://user-images.githubusercontent.com/39717736/148849538-fabba3b7-ffd1-41da-beef-971ebb9d7297.mov

**Comment by sibbng** [comment]
First of all, Playground using outdated version of VueUse, please don't use it for now. 
I built your demo on StackBlitz: https://stackblitz.com/edit/vueuse-vueuse-vite-starter-grzxmd?file=src%2FApp.vue

`useElementBounding` only listening `resize` events of [its target](https://github.com/vueuse/vueuse/blob/1ad9aaeff01ed84e202d6e27d927b18457f5128b/packages/core/useElementBounding/index.ts#L55-L58), not window. You can fix your code by updating numbers on window resize event:
```ts
import { useEventListener } from '@vueuse/core';

useEventListener('resize', () => {
  navRect.update();
  logoRect.update();
  menuRect.update();
});
```

**Comment by everettblakley** [comment]
Oh I didn't realize it was out of date, thank you for porting it! And thank you for the quick response

The new solution seems to work okay, expect there's a flickering now. I suspect it's because the resize event is firing, triggering an update, which triggers a resize event, and so on and so on... But, I think I should be in a place to solve this now! I wasn't clear on when `useElementBounding` would update, so I may rethink my approach.

https://user-images.githubusercontent.com/39717736/148977036-ff387094-b2c3-492f-a087-7d02c6aa625f.mov
