### ISSUE TITLE
any chance to include `usePrefetch`?

### ISSUE THREAD

**Issue by userquin** [vueuse/vueuse#1139]
@wheatjs @antfu https://github.com/vuejs/vitepress/blob/main/src/client/app/composables/preFetch.ts

**Comment by wheatjs** [comment]
Looks cool, maybe we want to think about how the API should work? Right now it seems like it watches for all links on any element in the document. Wondering if we want an option to specify an element to watch and default to the body? 

For example default usage would just be

```ts
const { links } = usePrefetch() // Prefetch all links in document
``` 

and for a specific element
```ts
const navigation = ref()
const { links } = usePrefetch(navigation) // Prefetch all links in navigation
```

A signature like this perhaps?
```ts
export function useFetch(target?: MaybeRef<string | HTMLElement>)
```

If you think that sounds good I'll make a PR

**Comment by userquin** [comment]
I didn't know that plugin from egoist, I think you shouldn't reinvent the wheel here.

**Comment by userquin** [comment]
closing this, seems the plugin from egoist has all we need
