### ISSUE TITLE
useAxios:How to change the data 

### ISSUE THREAD

**Issue by checkwoodson** [vueuse/vueuse#1147]
const {data} = useAxios()所吸出来的data，如何进行修改，因为看了已经被ref代理过了。
我如何操作对data数据进行改变，例如后台给的数据是个JSON格式。我也不能用JSON.prase()修改成js 在进行处理。

**Comment by webfansplz** [comment]
可以尝试: 
```ts
const parsedData = computed(()=> normalizeData(data.value))
```

**Comment by crucioo** [comment]
> const {data} = useAxios()所吸出来的data，如何进行修改，因为看了已经被ref代理过了。 我如何操作对data数据进行改变，例如后台给的数据是个JSON格式。我也不能用JSON.prase()修改成js 在进行处理。

请问，这个问题解决了吗？遇到同样的问题

**Comment by checkwoodson** [comment]
作者的意思是用计算属性来对数据进行调整了
