### ISSUE TITLE
Build error: no exported member named 'ShallowRef'

### ISSUE THREAD

**Issue by radusuciu** [vueuse/vueuse#1151]
Similar to #1135, except I've got all the latest versions of things. The full error:

```
node_modules/@vueuse/core/index.d.ts:5:67 - error TS2724: '"vue-demi"' has no exported member named 'ShallowRef'. Did you mean 'shallowRef'?

import { Ref, InjectionKey, ComputedRef, ComponentPublicInstance, ShallowRef, UnwrapRef, ToRefs } from 'vue-demi';
```

I'm using vue 2 (2.6.14) with `@vue/composition-api` (1.4.4), `@vueuse/core` (7.5.3), and `vue-demi` (0.12.1)

Pinning `@vueuse/core` to 7.5.2 is sufficient to solve the issue.

**Comment by deman777** [comment]
I have similar issue with
Vue 2.7, Pinia 2.0.33,  vueuse/core 9.13.0.
Pinia has some built in version of vue-demi and VueUse somehow uses that. And I get tons of errors.
* Module '"vue-demi"' has no exported member 'StyleValue'.
* 393:15 Cannot find name 'BluetoothLEScanFilter'.
* 401:24 Cannot find name 'BluetoothServiceUUID'.
etc...
