### ISSUE TITLE
useKeyModifier: CapsLock does not get set back to false directly

### ISSUE THREAD

**Issue by Shinigami92** [vueuse/vueuse#1153]
I use `const capsLockState = useKeyModifier('CapsLock')` to detect if the caps lock is currently active or not.

On first press it activates correctly, but on second press (turning it off again) it doesn't get set to `false` directly.
After a click on the website or pressing any key after disabling, it turns to `false`.

I can reproduce this in the Demo: https://vueuse.org/core/useKeyModifier

Using an Ubuntu 20.04 with Chrome 97.

**Comment by wheatjs** [comment]
Strange, I'm unable to reproduce on my end

**Comment by Shinigami92** [comment]
![image](https://user-images.githubusercontent.com/7195563/150101718-6bc9db2b-f98a-4458-a528-946c7501b466.png)


So if I'm correct there are two bugs in this function :eyes: 

1. The console.log I added always fires when something was press, not only of `CapsLock` :eyes:  
    So the event listener is registered wrongly and for every key and loses the reference that it tracks the exact state for the specified modifier/key.
2. If it's the `CapsLock` key, it needs to be handled differently, cause it's not a simple key-press but a toggle.  
    I'm not sure if my assumptions are wrong here, but I want specifically check whether the CapsLock key is currently active or not and show a hin below a password input field to notify the user.

**Comment by Shinigami92** [comment]
Okay, so for the first bug we could maybe use something like

```ts
events.forEach((listenerEvent) => {
  useEventListener(document, listenerEvent, (evt: KeyboardEvent) => {
    if (evt.key === modifier) {
      state.value = evt.getModifierState(modifier)
    }
  })
})
```

Not fully tested at all :warning: 
And I assume this definitely will cause bugs on different browsers/OS

**Comment by Shinigami92** [comment]
![image](https://user-images.githubusercontent.com/7195563/150106263-b4cbd077-255a-4900-bdf4-867ba201e8ed.png)

Because we register both events (`keydown` and `keyup`), the `keyup` event always overrides the `keydown` event for `CapsLock`
This is not a problem for other keys (maybe for e.g. `NumLock` :thinking:)
But for toggle-keys `keyup` always returns `true`

**Comment by Shinigami92** [comment]
A company team member tested it under **windows** and he can **NOT** reproduce it!
He has used Chrome. So it might be a linux / ubuntu / keyboard-configuration issue :thinking:

**Comment by Shinigami92** [comment]
Please note that this might not be directly relevant for VueUse, but I found out that I have the exact same "bug" on https://www.w3schools.com/howto/howto_js_detect_capslock.asp

**Comment by Shinigami92** [comment]
At least for the initial state, I overthinked the process and I came to the conclusion that the user needs to do one of three things anyways:

When page renders initially, the focus is automatically set into the `username` input field.
Then the user presses a keyboard event like a letter or the tab key, or clicks with the mouse to any location on the side like in the password field.
Then the event recognize the state of the CapsLock key and shows the hint to the user.

So only the disabling of the CapsLock key is "really" an issue as long as the user doesn't press any further key after disabling it.

**Comment by JMaylor** [comment]
Hey @Shinigami92. I wrote this useKeyModifier function and just want to let you know the reason behind 'bug 1' - why the state is updated on ANY key press. If you imagine the following situation in the case that we only updated on the modifier key being pressed:

1. User turns CAPS on while on your website. Modifier state is updated to true.
2. User tabs off your site and turns CAPS off. Your page can't detect this keypress and so doesn't update the modifier state to false.
3. User comes back to your site and continues typing. There is no CAPS press so they are now typing with CAPS off, but your app thinks CAPS is on. 

Hope that makes sense. No matter what key you press, the event exposes the current modifier state of all modifier keys via the getModifierState function.

You can add more listeners to update the state more regularly, at the cost of performance. e.g. mousemove events also provide modifier states - see https://github.com/vueuse/vueuse/pull/698#issuecomment-908241915

In terms of picking up the initial modifier state on page load, I looked into this at the time and couldn't find a way to do it. If  you simulate a key press through JS, all the modifier states are false. They are only populated on a 'real' keyboard event - [SO thread](https://stackoverflow.com/questions/31792106/how-to-detect-caps-lock-state-on-page-load-that-is-not-on-keypress-with-javas#:~:text=getModifierState%20will%20return%20true%20only%20in%20the%20case%20of%20real%20keypress.)

**Comment by Shinigami92** [comment]
I want to add that - now I have a MacBook Pro M1 - I can **not** reproduce this with my Mac
So it's an OS specific bug
