### ISSUE TITLE
Fuse not work with objects

### ISSUE THREAD

**Issue by ririen** [vueuse/vueuse#1161]
Attempting to use options and search with objects returns an empty array.

Reproduction: https://stackblitz.com/edit/vitejs-vite-fsgnzy?file=src/App.vue

**Comment by darrylnoakes** [comment]
To pass options to Fuse itself, you must put them in the `fuseOptions` property in the `options` object.

So instead of

```js
useFuse(input, dataObjects, options);
```

you would have

```js
useFuse(input, dataObjects, { fuseOptions: options });
```

or

```js
const options = {
  fuseOptions: {
    includeScore: true,
    keys: ['author', 'tags'],
  }
};
```
