### ISSUE TITLE
feat(onClickOutside): request whitelisting element

### ISSUE THREAD

**Issue by chu121su12** [vueuse/vueuse#1165]
I am integrating `onClickOutside` and `flatpickr`, and due to `flatpickr` by default attaching itself outside the `onClickOutside` container (below `body`), clicking on it will trigger the close.

**Comment by okxiaoliang4** [comment]
I will start work for this.

**Comment by okxiaoliang4** [comment]
Released https://github.com/vueuse/vueuse/releases/tag/v7.6.0
