### ISSUE TITLE
reactive RTL mode.

### ISSUE THREAD

**Issue by AtefR** [vueuse/vueuse#1168]
Yo, 
I'm trying to use vueuse to switch direction from ltr to rtl, the only way I could think of now is using [@vueuse/head](https://github.com/vueuse/head) and injecting html tag attributes.

```
useHead({
  htmlAttrs: [
    {
      dir: "rtl",
      lang: "ar-sa",
    },
  ],
})
```
I can code custom vueuse function but I thought it'll be better to open an issue to discuss it first.

**Comment by harmyderoman** [comment]
I think this is a very useful feature.
