### ISSUE TITLE
useAsyncState type error

### ISSUE THREAD

**Issue by darkxanter** [vueuse/vueuse#1188]
After update to 7.5.4 get error
```
TS2322: Type 'false' is not assignable to type 'true | undefined'.
```
```js
  const { state, isReady, execute } = useAsyncState(promise, initialState, {
    shallow: false,
  })
```

**Comment by webfansplz** [comment]
I can't reproduce it, can you provide a mini repo ?

And then reopen issue if you still has this probrem .

**Comment by darkxanter** [comment]
https://github.com/darkxanter/vueuse_useAsyncState_type_bug

**Comment by webfansplz** [comment]
> @webfansplz https://github.com/darkxanter/vueuse_useAsyncState_type_bug
> 
> Type error occurred when type of state explicit defined:
> 
> ```ts
> interface SomeData {
>   id: number;
> }
> const { state } = useAsyncState<SomeData[]>(() => Promise.resolve([]), [], {
>   shallow: false,
> });
> ```
> 
> I can't reopen issue myself.



Try :
```ts
interface SomeData {
  id: number
}
const { state } = useAsyncState<SomeData[], false>(() => Promise.resolve([]), [], {
  shallow: false,
})

```

**Comment by darkxanter** [comment]
I use this workaround, but it's not convenient.

**Comment by webfansplz** [comment]
> I use this workaround, but it's not convenient.

Can you post a screenshot of the error ? 

This workaround works for me .

**Comment by darkxanter** [comment]
If write `useAsyncState<SomeData[], false>` I have no error.

**Comment by webfansplz** [comment]
> If write `useAsyncState<SomeData[], false>` I have no error.

https://github.com/vueuse/vueuse/blob/b8a26678de12f0720f05e04082659df433682ccd/packages/core/useAsyncState/index.ts#L64

Yes,you should do that if you want to set the `shallow` option is false

**Comment by darkxanter** [comment]
But why duplicate `shallow false`? When `shallow` was simple `boolean` it's not required.

**Comment by webfansplz** [comment]
> But why duplicate `shallow false`? When `shallow` was simple `boolean` it's not required.
https://github.com/vueuse/vueuse/blob/b8a26678de12f0720f05e04082659df433682ccd/packages/core/useAsyncState/index.ts#L114

**Comment by darkxanter** [comment]
Maybe fix it somehow so that don't require explicit `false` in type parameter?

**Comment by webfansplz** [comment]
> Maybe fix it somehow so that don't require explicit `false` in type parameter?

I dont' think so, it’s designed to provide more accurate type for `state` .
