### ISSUE TITLE
Feature requests: longpress and element visibility

### ISSUE THREAD

**Issue by Blackfaded** [vueuse/vueuse#1197]
Hey there!

First I have to say, that this repo is really great! Thanks for that!

In my company we created a [repo](https://github.com/nanogiants/vue3-packages/tree/main/packages) for some vue3 directives and made them public.
As far as I have seen this repo here does not support directives yet. Am I right?

So my idea was, that I could refactor the directives to hooks and integrate them here in the library.

The[ longpress directive](https://github.com/nanogiants/vue3-packages/tree/main/packages/directive-longpress) adds a Customevent `longpress` to the element. This would also be possible if I add this functionality via a `useLongpress(elementRef)` hook.

The [visible directive](https://github.com/nanogiants/vue3-packages/tree/main/packages/directive-visible) adds support for a `v-visible` directive. It differs from `v-if` (not in the dom) and `v-show` (display none) in that its sets `visibility: hidden` on the element.

Is there any need for those two functionality in this repo?
I would love to contribute and add them as hooks.

Greetings
Blackfaded

**Comment by Blackfaded** [comment]
The demo would look like this

```ts
<script setup lang="ts">
import { ref } from 'vue-demi'
import { onLongpress } from '.'

const htmlRef = ref<HtmlElement | null>(null)
const longPressed = ref(false)

const onLongpressCallback = (e: PointerEvent) => {
  longPressed.value = true
}

const reset = () => {
  longPressed.value = false
}

onLongpress(htmlRef, onLongpressCallback)
</script>

<template>
  <p>Longpressed: {{ longPressed }}</p>

  <button ref="htmlRef" class="ml-2 button small">
    Press long
  </button>

  <button class="ml-2 button small" @click="reset">
    Reset
  </button>
</template>
```

**Comment by wheatjs** [comment]
Sounds cool, maybe follow how we did it for the components. Each function that has a directive can live under `function/directive.ts`. Then we can publish them under `@vueuse/directives`
