### ISSUE TITLE
Suggestion: Is vueuse consider to create some directives?

### ISSUE THREAD

**Issue by SnowingFox** [vueuse/vueuse#1204]
Vueuse is a hooks library, we can use it via function, but I think as a Vue lib, why not use some features of vue like `directive`?

For example about this https://github.com/vueuse/vueuse/pull/1201

If we use hook to implement this feature like the above PR, we can't make full use of the advantages of Vue, and it's very cumbersome

If we use `directive`, we can use it like this

```js
// main.js
import { lazyLoad } from '@vueuse/directives'

createApp(App).use(lazyLoad, {...some options})
```

```html
// component.vue
<img v-lazy="https://xxx.com/xxx.jpg" />
```

These are just some personal suggestions, welcome to discuss them together

**Comment by wheatjs** [comment]
This is already being worked on, see https://github.com/vueuse/vueuse/pull/1202/files

Currently there is still some more work to do before we official release something like `@vueuse/directives` but it will be coming soon
