### ISSUE TITLE
Error when creating new users

### ISSUE THREAD

**Issue by jonalxh** [vueuse/vueuse#1206]
Hi' I'm currently using `@vueuse/firebase/useAuth` in an app that allows to create several users inside a company, the problem I have is that when I create a new user with the native Firebase code, the useAuth hook reacts to that creation and sets the new account as the currently logged in account, what I need is to prevent that behavior and just allow the logged in user to create several users without being logged out.

User creation:

```
import { auth, db } from "boot/firebase";
... // code here

await auth.createUserWithEmailAndPassword(userFields.value.email, userFields.value.password)
```

User login hook in my navbar to show some user info and to know he is logged:
```
import { useAuth } from "@vueuse/firebase/useAuth";
... // code here

const { user, isAuthenticated } = useAuth(firebase.auth);

```

I repeat, when a new user is created with the `createUserWithEmailAndPassword` method, the `useAuth` hook reacts and converts the new user as the logged in user, signing out the user who created him. How do I prevent it?

Thanks a lot for your help.

**Comment by wheatjs** [comment]
This is an issue with Firebase itself. Check this thread for more info https://stackoverflow.com/questions/37517208/firebase-kicks-out-current-user/37614090#37614090

Currently I don't believe there is anything we can do on our end to fix this.

**Comment by jonalxh** [comment]
Ok, thanks for sending me the S.O tread, I'll try the solutions posted there.
