### ISSUE TITLE
[Vue warn]: Invalid watch source:  null A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types.

### ISSUE THREAD

**Issue by martinszeltins** [vueuse/vueuse#1207]
I am trying to use the `until` function but I am getting this error:

> [Vue warn]: Invalid watch source:  null A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types.

I am also using the Ref transform in my project: https://github.com/vuejs/rfcs/discussions/369

But the VueUse docs doesn't mention anything about how to use this together with Ref Transform.

https://vueuse.org/shared/until/

````
<template>
  <AppInput
    ref="nameInput"
    :block="true"
    :full-width="true"
  />
</template>

<script setup lang="ts">
    import { onMounted } from 'vue'
    import { until } from '@vueuse/core'

    const nameInput = $ref(null)

    onMounted(async () => {
        await until(nameInput).toBeTruthy()

        console.log('it is truthy!! :)')
    })
</script>
````

**Comment by AllenYu0118** [comment]
I try to change `const nameInput = $ref(null)` to `const nameInput = ref(null)` and  `import { onMounted, ref } from 'vue'`

Now, it works

**Comment by lsdsjy** [comment]
You should use `$$()` if you want to pass it to a function expecting a `ref`, [like the RFC says](https://github.com/vuejs/rfcs/discussions/369#:~:text=Retaining%20reactivity%20across%20function%20boundaries%20with).
