### ISSUE TITLE
useAxios - expose promise

### ISSUE THREAD

**Issue by volarname** [vueuse/vueuse#1210]
If its possible, Can you expose axios promise in useAxios? so we can use then() instead of watch for data change or loading change.
This way we can use this composable inside of services also.
Example: 
```
const { isLoading, response, promise } = useAxios('...', { method: 'POST' })
promise.value.then(() =>{
  console.log(isLoading.value)
}).error......finally...
```

**Comment by wheatjs** [comment]
I'd prefer if we did it this way instead https://github.com/vueuse/vueuse/pull/1056

**Comment by volarname** [comment]
> I'd prefer if we did it this way instead #1056

of course thats even better
