### ISSUE TITLE
useWindowScroll is broken

### ISSUE THREAD

**Issue by songololo** [vueuse/vueuse#1230]
Recent versions of `vueuse` seem to have broken `useWindowScroll`

Compare:
https://v5-3-0.vueuse.org/core/useWindowScroll/
with:
https://vueuse.org/core/usewindowscroll/

See the scroll counters in the bottom right corner of the window - the old version works but the current version does not.

I've tried in several browsers and the issue seems to persist. This seems related to the scroll event specifically.

**Comment by songololo** [comment]
Update: the utility only works if added specifically to the parent div / overflowable container of the scrolling content. This may be intended behaviour.

**Comment by wheatjs** [comment]
I believe this is due to an issue with SSG. If you navigate to `useWindowScroll` from another function it works
