### ISSUE TITLE
useFetch: typing json response

### ISSUE THREAD

**Issue by Ragura** [vueuse/vueuse#1234]
Question: given a normal fetch request using useFetch() like this:
```ts
const { data, isFinished, statusCode, error } = useFetch<Post>('https://jsonplaceholder.typicode.com/posts/1')
```
it will type data as ref<Post | null> which is kind of what I want. Unfortunately, it won't actually be of that type, because data will be of type string (default return value type).
If I add `.json()` at the end of the useFetch() call, data will be the object, but it will also be retyped to `Ref<any>`.

Is there a way to write this so data can hold the actual data object and be typed as `Ref<Post>`?

**Comment by Ragura** [comment]
Ah, I inspected the code and found out it's possible to also type the `.json()` chained method.

So this does work:
```ts
const { data, isFinished, statusCode, error } = useFetch('https://jsonplaceholder.typicode.com/posts/1').json<Post>()
```

Apologies for the issue, will close it now. Maybe the silver lining is it could help people searching through closed issues in the future 🙂

**Comment by System233** [comment]
Since `.json`  will erase the type information to `any`, what does `useFetch<Post>` mean? 🤔
