### ISSUE TITLE
Docs sections duplicate

### ISSUE THREAD

**Issue by unickhow** [vueuse/vueuse#1238]
Hi there,
this is a docs issue, but it just can't be reproduce when running locally, functions pages are working fine if user enter from root page, but the **Demo** section will duplicate a **false** one when user refresh the page in most function pages with it.

e.g. [useClipboard](https://vueuse.org/core/useclipboard/) *<- go directly*

| correct | incorrect |
| ------- | --------- |
| ![image](https://user-images.githubusercontent.com/22793771/153469815-f2d70912-0328-41c0-ab86-f78d42f25721.png) | ![image](https://user-images.githubusercontent.com/22793771/153469957-d287fc7c-0dbf-4764-b2df-64fc1711b7af.png) |

meanwhile, the **footer** sections will be disordered
| correct | incorrect |
| ------- | --------- |
| ![image](https://user-images.githubusercontent.com/22793771/153470033-2f14cabd-c37d-462b-8c2d-9b85e6d70730.png) | ![image](https://user-images.githubusercontent.com/22793771/153467335-342770ae-7ca4-4fc9-93b0-36651fe072c4.png) |

I've tried several browsers, like Brave, Chrome, and Safari, even in Incognito mode, **Demo** section might confuse those who enter a specific function page directly
both of two sections are defined in `markdownTransform.ts`, could it be a ssr issue ?

btw my current Chromium version is 98.0.4758.87

**Comment by darrylnoakes** [comment]
Been noticing the same issue.
Seemingly randomly either a duplicated demo or changelog or both.
Always (almost, at least) a broken source section, showing the contributors instead.

**Comment by unickowl** [comment]
@darrylnoakes In my case, it only occurs in pages with **Demo** section, both **Source** and **Changelog** are getting disordered after page refresh (or landing), besides that, everything is working fine.

e.g. [refDefault](https://vueuse.org/shared/refdefault/) is one of those pages w/o **Demo**

**Comment by unickhow** [comment]
@darrylnoakes In my case, it only occurs in pages with **Demo** section, both **Source** and **Changelog** are getting disordered after page refresh (or landing), besides that, everything is working fine.

e.g. [refDefault](https://vueuse.org/shared/refdefault/) is one of those pages w/o **Demo**
