### ISSUE TITLE
duplicate modules and broken tree shaking in Nuxt2 (webpack4)

### ISSUE THREAD

**Issue by ttkoma** [vueuse/vueuse#1239]
In a fresh Nuxt2 project, tree shaking doesn't work.
I only imported "useMouse" and my final package includes all functions from @vueuse/core (both files `index.mjs` and `index.cjs` ).
A reproduction is available here [nuxt2-vueuse-js-repro](https://github.com/ttkoma/nuxt2-vueuse-js-repro/tree/53bce1d4ba16baf898c5e18bff72675c2ad79a35)
My workaround, which reduced the package to a minimal size, is:
```js
// nuxt.config.js
export default {
 // ...
alias: {
    "@vueuse/core": resolve(__dirname, "node_modules/@vueuse/core/index.mjs"),
    "@vueuse/shared": resolve(__dirname, "node_modules/@vueuse/shared/index.mjs"),
  }
}
```

I wanted to know if there is a better solution?

_Webpack analyzer output  `yarn nuxt  -a`:_
| Before | After | 
|--------|-------|
|  ![image](https://user-images.githubusercontent.com/1864455/153517448-5713ce72-4dae-4556-8c67-bd082584862b.png)      |  ![image](https://user-images.githubusercontent.com/1864455/153517679-6f470617-f5f7-403c-9664-f591ee2151a4.png)     |

**Comment by antfu** [comment]
This is rather a project management issue rather than a bug of VueUse itself. I guess you will need to figure it out yourself.
