### ISSUE TITLE
The button is clicked and cannot be closed (onClickOutside)

### ISSUE THREAD

**Issue by yamasaan** [vueuse/vueuse#1245]
when clicked it return false then true, I a problem to click on the button and unable to close.

https://user-images.githubusercontent.com/94634392/153700331-cb2bb1b6-7849-4395-8ccc-d4d5334fbfdf.mov

https://github.com/vueuse/vueuse/blob/03929c770b74691873a724b976d9443daa64d67d/packages/core/onClickOutside/demo.vue#L33

-------------
vue version 3
-------------

**Comment by webfansplz** [comment]
I think this's just event logic conflict.If you have such a feature scenario, maybe you can do this :

```ts
const buttonRef = ref(null)
onClickOutside(
  dropdownRef,
  (event) => {
    if (event.target === buttonRef.value) {
      setTimeout(() => {
        dropdown.value = false
      })
    }
    else {
      dropdown.value = false
    }
  },
)
```

**Comment by yamasaan** [comment]
> I think it's just a event logic conflict.If you have such a feature scenario, maybe you can do this :

it worked

**Comment by anburocky3** [comment]
> I think it's just a event logic conflict.If you have such a feature scenario, maybe you can do this :
> 
> ```ts
> const buttonRef = ref(null)
> onClickOutside(
>   dropdownRef,
>   (event) => {
>     if (event.target === buttonRef.value) {
>       setTimeout(() => {
>         dropdown.value = false
>       })
>     }
>     else {
>       dropdown.value = false
>     }
>   },
> )
> ```

@webfansplz I have several menus which has the same logic. Toggle on click and hide when clicked outside, do i need to use the same logic for each and every menu item?
