### ISSUE TITLE
useColorMode not reactive when using multiple instances

### ISSUE THREAD

**Issue by toniengelhardt** [vueuse/vueuse#1268]
When I use `useColorMode()` in different places, different refs are returned, which means reactivity between them doesn't work, e.g.

```html
// ColorMode toggle component

<template>
  Some color mode toggle
</tempalte>

<script setup lang="ts">
const color = useColorMode()
// manipulate color with toggle...
</script>
```

```html
// Some other component

<template>
  <div :style="{ 'background-color': bgColor }">
    Some HTML
  </div>
</tempalte>

<script setup lang="ts">
const color = useColorMode()
const bgColor = computed(() => color === 'light' ? '#fff' : '#000')
</script>
```

Now, when I use the toggle to change the color, the second component will not react...

**Comment by okxiaoliang4** [comment]
`useColorMode` return a `Ref`,`computed` should use `color.value`
![image](https://user-images.githubusercontent.com/22525904/153969328-eea36ed2-e18d-4e84-a2b0-d895aef64bf6.png)

**Comment by okxiaoliang4** [comment]
Because the `store` event is not triggered when the value is change, the `ref` value of the other ranges is not updated.

**Comment by okxiaoliang4** [comment]
You can reuse one `ref` variable to resolve this.

```typescript
// colorMode.ts
import { useColorMode } from '@vueuse/core';
export const color = useColorMode();
```

**Comment by toniengelhardt** [comment]
It throws an error, see updated example: https://stackblitz.com/edit/nuxt3-vueuse-color-mode-reactivity-bug

**Comment by okxiaoliang4** [comment]
Sorry,I'm out you can try it in your project, I can't run stackBlitz in mobile😅

**Comment by toniengelhardt** [comment]
Amazing @webfansplz, it works. I opened a PR to add this example to the docs: https://github.com/vueuse/vueuse/pull/1293.

**Comment by okxiaoliang4** [comment]
> > It throws an error, see updated example: https://stackblitz.com/edit/nuxt3-vueuse-color-mode-reactivity-bug
> 
> Try it , https://stackblitz.com/edit/nuxt3-vueuse-color-mode-reactivity-bug-gfrbbx?file=composables%2FuseTheme.ts

Hi I'm back. I think it's a bit complicated. see this
https://stackblitz.com/edit/vitejs-vite-dfuy95?file=src%2Fuse%2FuseGlobalColorMode.ts&terminal=dev

**Comment by toniengelhardt** [comment]
Thanks @okxiaoliang4, this also works and seems be a bit less code. I'm not sure what the preferred Vue 3 way of doing it is, imports or composables.

**Comment by okxiaoliang4** [comment]
I think if you want reactive `colorMode` in multiple instance it would be a little better to export its module (less function call) or try [createGlobalState](https://vueuse.org/shared/createGlobalState).

**Comment by okxiaoliang4** [comment]
> > > It throws an error, see updated example: https://stackblitz.com/edit/nuxt3-vueuse-color-mode-reactivity-bug
> > 
> > 
> > Try it , https://stackblitz.com/edit/nuxt3-vueuse-color-mode-reactivity-bug-gfrbbx?file=composables%2FuseTheme.ts
> 
> Hi I'm back. I think it's a bit complicated. see this https://stackblitz.com/edit/vitejs-vite-dfuy95?file=src%2Fuse%2FuseGlobalColorMode.ts&terminal=dev

I update the demo with [createGlobalState](https://vueuse.org/shared/createGlobalState)
