### ISSUE TITLE
Support Deno

### ISSUE THREAD

**Issue by idanran** [vueuse/vueuse#1275]
I cannot use this module within the Deno project.

**Comment by antfu** [comment]
This is a pure client side library and I don't see any blockers to do that. Please provide more information

**Comment by idanran** [comment]
> This is a pure client side library and I don't see any blockers to do that. Please provide more information

https://esm.sh/@vueuse/core
```
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: No matching export in \"esm-build-21a8a9937be0688810d4c764f144f8f5b3ce7a76-c44ded1a/node_modules/@vueuse/core/index.mjs\" for import \"biSyncRef\"");
export default null;
```

**Comment by wheatjs** [comment]
Try setting it to bundle mode https://esm.sh/@vueuse/core?bundle

**Comment by idanran** [comment]
> Try setting it to bundle mode https://esm.sh/@vueuse/core?bundle

Ok, thank you.
