### ISSUE TITLE
useClipboard在ip地址下不能使用问题

### ISSUE THREAD

**Issue by Anm520** [vueuse/vueuse#1276]
由于新版浏览器的安全策略，clipboard只有在安全域名下才可以访问，http域名下会显示undefined，但使用https开头的域名，或localhost，就可以访问navigator.clipboard
大佬能做一下兼容吗，内网开发很多都是ip地址访问页面，功能用不了
document.execCommand('copy')

**Comment by okxiaoliang4** [comment]
Consider creating a new function or option to handle this

**Comment by Anm520** [comment]
> Consider creating a new function or option to handle this
参考一下这个博主的内容 https://www.cnblogs.com/hellxz/p/15192573.html
        function copyToClipboard(textToCopy) {
            // navigator clipboard 需要https等安全上下文
            if (navigator.clipboard && window.isSecureContext) {
                // navigator clipboard 向剪贴板写文本
                return navigator.clipboard.writeText(textToCopy);
            } else {
                // 创建text area
                let textArea = document.createElement("textarea");
                textArea.value = textToCopy;
                // 使text area不在viewport，同时设置不可见
                textArea.style.position = "absolute";
                textArea.style.opacity = 0;
                textArea.style.left = "-999999px";
                textArea.style.top = "-999999px";
                document.body.appendChild(textArea);
                textArea.focus();
                textArea.select();
                return new Promise((res, rej) => {
                    // 执行复制命令并移除文本框
                    document.execCommand('copy') ? res() : rej();
                    textArea.remove();
                });
            }
        }

**Comment by JackieCheung** [comment]
Any progress?

**Comment by JackieCheung** [comment]
I think `useClipboard` needs to provide compatibility if `navigator.clipboard` is undefined~

**Comment by WormGirl** [comment]
同样的问题
