### ISSUE TITLE
Can `useVModel` convert the value from prop to custom value?

### ISSUE THREAD

**Issue by gjccing** [vueuse/vueuse#1277]
Thanks your super cool library.

I’m looking for a function similar to `useVModel` but I want to convert the value before updating from props, Is there such a feature in Vueuse?

Example:
```
// parent
const stringValue = '1' // string
<comp v-model="stringValue" />

// child
const numberModelValue = _useVModel(props, 'modelValue', {
  update: (value) => number(value)
  emit: (value) { emit('update:modelValue', value.toString()) }
}) 
```

**Comment by okxiaoliang4** [comment]
I think maybe you should use v-model.number

**Comment by gjccing** [comment]
Oh, my use-case more complicated than the above example, 
I want to transform from one object structure to another structure or type.

**Comment by freakzlike** [comment]
`useVModel` is just a shorthand for a `computed` with `get`/`set`

You can directly use `computed` for this
```ts
const value = computed({
  get: () => fromProp(props.modelValue),
  set: value => emit('update:modelValue', toProp(value))
})
```
