### ISSUE TITLE
useEventBus payload

### ISSUE THREAD

**Issue by Idered** [vueuse/vueuse#1278]
```
const modalBus = useEventBus<'show' | 'hide'>('modal')

modaBus.emit('show', {name: 'login-modal')
```

**Comment by webfansplz** [comment]
I'll support it.

**Comment by Idered** [comment]
[mitt](https://www.npmjs.com/package/mitt) package api is really good. Being able to define payload type for each event type is easy
```ts
type Events = {
  foo: string;
  bar?: number;
};

const emitter = mitt<Events>(); // inferred as Emitter<Events>

emitter.on('foo', (e) => {}); // 'e' has inferred type 'string'
emitter.on('bar', (e) => {}); // 'e' has inferred type number | undefined

emitter.emit('foo', 42); // Error: Argument of type 'number' is not assignable to parameter of type 'string'. (2345)
```

**Comment by okxiaoliang4** [comment]
Looks good

**Comment by webfansplz** [comment]
> [mitt](https://www.npmjs.com/package/mitt) package api is really good. Being able to define payload type for each event type is easy
> 
> ```ts
> type Events = {
>   foo: string;
>   bar?: number;
> };
> 
> const emitter = mitt<Events>(); // inferred as Emitter<Events>
> 
> emitter.on('foo', (e) => {}); // 'e' has inferred type 'string'
> emitter.on('bar', (e) => {}); // 'e' has inferred type number | undefined
> 
> emitter.emit('foo', 42); // Error: Argument of type 'number' is not assignable to parameter of type 'string'. (2345)
> ```

Thank you for your suggestion.

`UseEventBus` has some implementation differences from `mitt`,if we want to made the same behavior with mitt, it will be caused breaking change.

I try with mini modification for payload support, hope it can help you.

PR always welcome if you want to improve it .

**Comment by Idered** [comment]
I can create PR with `useEventEmitter` which would have mitt api. `useEventBus` could be marked as deprecated and link to useEventEmitter.  @webfansplz what do you think?

**Comment by Idered** [comment]
Actually, `useEventBus` can be used to recreate mitt api:

```ts
const busMap = new Map()

busMap.set('foo', useEventBus<string>('foo'))
busMap.set('bar', useEventBus<number | undefined>('bar'))

function emit<P>(name: string, payload: P) {
  return busMap.get(name).emit(payload)
}
```

**Comment by webfansplz** [comment]
We usually use the Mitt with Provide/Inject API .  (mitt  function only triggered once time)

You can use `mitt` directly like this :

```ts
import { inject, App, InjectionKey } from 'vue'
import mitt, { Emitter } from 'mitt'

const MittKey: InjectionKey<Emitter> = Symbol()

export function initMitt(app: App<Element>) {
    const emitter = mitt()
    app.provide(MittKey, emitter)
}

export function useEmitter() {
    return inject(MittKey)
}
```
But we usually use composable API in in anywhere and call it multi times , I guess that's what `useEventBus` was designed for. 

https://github.com/vueuse/vueuse/blob/aef8a2b2459b064ea4d92c843db2f88ef3c0eb2c/packages/core/useEventBus/internal.ts#L4

```ts
// a.vue
 const { on, emit } = useEventBus<'inc'|'dec', number>('counter')
 const { on, emit } = useEventBus<'show'|'hide', {name:string}>('modal')
// b.vue
 const { on, emit } = useEventBus<'inc'|'dec', number>('counter')
 const { on, emit } = useEventBus<'show'|'hide', {name:string}>('modal')
```
