### ISSUE TITLE
useLocalStorage 在vite-ssg中build后无法正常使用

### ISSUE THREAD

**Issue by LuckLin520** [vueuse/vueuse#1283]
![image](https://user-images.githubusercontent.com/33896086/154388843-ac05ac35-e3c6-4b57-b3e6-dbfaffb8e3a4.png)
build后启动服务预览项目，并没有获取到存储的值，并且localstorage中也没有
![image](https://user-images.githubusercontent.com/33896086/154388933-772e9fc8-a788-4a8e-a668-8c1d223a9b2e.png)

可能相关的依赖版本：
"vite-ssg": "^0.17.10",
"pinia": "^2.0.11",
"vue": "^3.2.25",

**Comment by webfansplz** [comment]
你可以提供一个最小可以复现的`Demo`吗 ?

**Comment by LuckLin520** [comment]
> 你可以提供一个最小可以复现的`Demo`吗 ?

抱歉我不能提供一个在线沙箱Demo，我把本地项目最小化并通过在线地址分享出来了，[userLocalStorage_issuses](https://wx.mail.qq.com/ftn/download?func=3&key=9aca53395ef4c078a8b9163964643765ceb6383966643765401a590d5250005d045415585402074851005e0d4b5c070603180a0b5f5406035450090105542d6510465d75090756093641574b0703523a0c464b4c0317191f0c452c4f44b232597b2e26f90c780a0aba196010a6f71d&code=e589fd7e&k=9aca53395ef4c078a8b9163964643765ceb6383966643765401a590d5250005d045415585402074851005e0d4b5c070603180a0b5f5406035450090105542d6510465d75090756093641574b0703523a0c464b4c0317191f0c452c4f44b232597b2e26f90c780a0aba196010a6f71d&fweb=1&cl=1)
麻烦您可以下载下来启动帮我看看？
目前我所得到的结果就是启用vite-ssg和vite-plugin-pages插件后，只要创建了pages目录（生成路由的目录）和.vue页面文件并build后，启动preview预览项目useLocalStorage不能正常工作。

**Comment by LuckLin520** [comment]
删除pages目录或者改个名字重新构建是可以达到预期的，所以我觉得可能是vite-ssg或者vite-plugin-pages和useLocalStorage哪里不兼容。。。

**Comment by LuckLin520** [comment]
应该是vite-ssg无法使用storage
