### ISSUE TITLE
make `not(ref)` writeable

### ISSUE THREAD

**Issue by QiroNT** [vueuse/vueuse#1285]
```typescript
const a = ref(true)
const b = not(a) // WritableComputedRef<boolean>
b.value = true
console.log(a.value) // false

not(false) // ComputedRef<boolean>
not(computed(() => false)) // ComputedRef<boolean>
```

I'm not sure if it should be a feature of `not` or a standalone `writeableNot`

**Comment by webfansplz** [comment]
The `not` just a computed wrapper.

I don’t think it’s necessary , because it may lead to unexpected result, and semantically,`not` also should provide a readonly inverse value .

Why not just change `a` ? it can get the same result . can you share why you need it ?

**Comment by antfu** [comment]
Use useToggle instead. `not` is designed to be one directional since the input is not neccessary boolean nor writeable ref
