### ISSUE TITLE
proposal: useBluetooth()

### ISSUE THREAD

**Issue by michealroberts** [vueuse/vueuse#1286]
Although this API is not well supported, I feel like providing some sort of support for it out of the box for "future generations" would be really, really beneficial for bridging the gap between PWAs and native app experiences ...

https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API

Thoughts are very much welcome!

**Comment by michael-observerly** [comment]
@okxiaoliang4 This proposal would introduce the developer dependency "@types/web-bluetooth", is that ok?

**Comment by okxiaoliang4** [comment]
> @okxiaoliang4 This proposal would introduce the developer dependency "@types/web-bluetooth", is that ok?

I think is ok.

**Comment by michael-observerly** [comment]
@okxiaoliang4 Question: to get those types working within the library I had to add `"@types/web-bluetooth"` to the tsconfig.json under the types field ... this doesn't feel quite right.

**Comment by michael-observerly** [comment]
@okxiaoliang4 PR for this has now been submitted.
