### ISSUE TITLE
Feature request useCaptcha

### ISSUE THREAD

**Issue by joshauh46** [vueuse/vueuse#1289]
Hi,

Would you consider adding a useCaptcha function like this one for React? https://github.com/sakalx/useCaptcha 

vue-recaptcha-v3 exists for Vue 3 composition API but you need to make a global import and mount it to App instance.

This causes the library to load on all pages even when it's not needed.

Recaptcha bundle size is huge at 600kb and it slows down the site in fact 60% of total JS size in one of my projects is Recaptcha alone.

**Comment by stefnotch** [comment]
You could consider using a different captcha service with a smaller bundle size https://github.com/FriendlyCaptcha/friendly-challenge
