### ISSUE TITLE
bug(useEyeDropper): "open" button is disabled when loading the page directly

### ISSUE THREAD

**Issue by darrylnoakes** [vueuse/vueuse#1301]
When loading the `useEyeDropper` page directly, the "open" button momentarily shows the "not supported" message, and then the demo finishes loading (the output text appears above the button) and the button text switches to "Open Eye Dropper", but the button remains disabled.

Navigating to the page from another page on the site is fine, with no loading period at all.

**Comment by ryanmoyo** [comment]
I tried some methods to slove this, the only way is put it in onMounted, but it will be wired that it first showed `not sppport ...` and then became normal and available.

**Comment by darrylnoakes** [comment]
It seems to be something to do with `isSupported` not being a ref. The button for some reason starts as disabled with the disabled text, and then the text changes but not the disabled state.

I couldn't replicate it in [an SFC playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuZnVuY3Rpb24gdXNlRm9vKCkge1xuICBjb25zdCBpc1N1cHBvcnRlZCA9IEJvb2xlYW4odHlwZW9mIHdpbmRvdyAhPT0gJ3VuZGVmaW5lZCcgJiYgJ0V5ZURyb3BwZXInIGluIHdpbmRvdylcbiAgY29uc3QgdmFsID0gcmVmKDApXG5cbiAgZnVuY3Rpb24gaW5jcmVtZW50KCkge1xuICAgIHZhbC52YWx1ZSArPSAxO1xuICB9XG5cbiAgcmV0dXJuIHsgaXNTdXBwb3J0ZWQsIHZhbCwgaW5jcmVtZW50IH1cbn1cblxuY29uc3QgeyBpc1N1cHBvcnRlZCwgdmFsLCBpbmNyZW1lbnQgfSA9IHVzZUZvbygpOyBcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxidXR0b25cbiAgICA6ZGlzYWJsZWQ9XCIhaXNTdXBwb3J0ZWRcIlxuICAgIEBjbGljaz1cIigpID0+IGluY3JlbWVudCgpXCJcbiAgPlxuICAgIHt7IGlzU3VwcG9ydGVkID8gJ0luY3JlbWVudCcgOiAnTm90IFN1cHBvcnRlZCBieSBZb3VyIEJyb3dzZXInIH19XG4gIDwvYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuYnV0dG9uIHtcbiAgcGFkZGluZzogM3B4IDE1cHg7XG4gIGJhY2tncm91bmQtY29sb3I6ICM0MmI4ODM7XG4gIGJvcmRlcjogbm9uZTtcbiAgb3V0bGluZTogbm9uZTtcbiAgY29sb3I6ICNmZmY7XG4gIG1hcmdpbjogMC41cmVtIDA7XG4gIGJvcmRlci1ib3R0b206IDJweCBzb2xpZCAjMzNhMDZmO1xuICB0ZXh0LXNoYWRvdzogMXB4IDFweCAxcHggIzMzYTA2ZjtcbiAgYm9yZGVyLXJhZGl1czogNHB4O1xuICBmb250LXNpemU6IDFyZW07XG4gIGJveC1zaXppbmc6IGJvcmRlci1ib3g7XG4gIHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7XG59XG4gIFxuYnV0dG9uOmFjdGl2ZSB7XG4gIGJvcmRlci1ib3R0b206IDA7XG4gIGJvcmRlci10b3A6IDJweCBzb2xpZCAjMzNhMDZmO1xufVxuXG5idXR0b25bZGlzYWJsZWRdIHtcbiAgY3Vyc29yOiBkZWZhdWx0O1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjODg4ODg4NTA7XG4gIGNvbG9yOiBpbmhlcml0O1xuICBib3JkZXItYm90dG9tOiAycHggc29saWQgIzg4ODg4ODUwO1xuICBwb2ludGVyLWV2ZW50czogbm9uZTtcbiAgdGV4dC1zaGFkb3c6IG5vbmU7XG4gIGJvcmRlci10b3A6IDA7XG4gIG9wYWNpdHk6IC44O1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=).

I'm guessing it's due to SSR/SSG initializing the button like that and then it failing to update correctly.
