### ISSUE TITLE
Height transition

### ISSUE THREAD

**Issue by kostyfisik** [vueuse/vueuse#1316]
### Clear and concise description of the problem

Performant height transition is an old and popular topic, see [SO link](https://stackoverflow.com/questions/3508605/how-can-i-transition-height-0-to-height-auto-using-css?rq=1) with >2500 votes. It can be useful for animation of Menu items, showing\hiding form fields, in some vertical accordion, etc. JS nature of Vue makes it easier to solve this problem. However, I am not aware of any free and open-source solution for this in Vue. 

### Suggested solution

I have created a Vue component to solve this issue. It is in a very early stage of development, but rather usable. See the [demo](https://height-transition-vue3-web-animation-api.netlify.app/) and related [GitHub](https://github.com/kostyfisik/transition-height-vue3-ts) It is based on Web Animation API to ensure GPU usage (no polyfill in demo, so use only modern browser to take a look), so there is no need to use any 3rd party animation lib, and thus it can be included to the core module. Note, that there is also Popmotion based Motion module, which can be another place to host this. Still, the main question is whether this kind of stuff is needed in VueUse at all?

```js
<script setup lang="ts">
interface Props {
  duration?: number;
  easingEnter?: string;
  easingLeave?: string;
  opacityClosed?: number;
  opacityOpened?: number;
}

const props = withDefaults(defineProps<Props>(), {
  duration: 250,
  easingEnter: "ease-in-out",
  easingLeave: "ease-in-out",
  opacityClosed: 0,
  opacityOpened: 1,
});

const closed = "0px";

interface initialStyle {
  height: string;
  width: string;
  position: string;
  visibility: string;
  overflow: string;
  paddingTop: string;
  paddingBottom: string;
  borderTopWidth: string;
  borderBottomWidth: string;
  marginTop: string;
  marginBottom: string;
}

function getElementStyle(element: HTMLElement) {
  return {
    height: element.style.height,
    width: element.style.width,
    position: element.style.position,
    visibility: element.style.visibility,
    overflow: element.style.overflow,
    paddingTop: element.style.paddingTop,
    paddingBottom: element.style.paddingBottom,
    borderTopWidth: element.style.borderTopWidth,
    borderBottomWidth: element.style.borderBottomWidth,
    marginTop: element.style.marginTop,
    marginBottom: element.style.marginBottom,
  };
}

function prepareElement(element: HTMLElement, initialStyle: initialStyle) {
  const { width } = getComputedStyle(element);
  element.style.width = width;
  element.style.position = "absolute";
  element.style.visibility = "hidden";
  element.style.height = "";
  let { height } = getComputedStyle(element);
  element.style.width = initialStyle.width;
  element.style.position = initialStyle.position;
  element.style.visibility = initialStyle.visibility;
  element.style.height = closed;
  element.style.overflow = "hidden";
  return initialStyle.height && initialStyle.height != closed
    ? initialStyle.height
    : height;
}

function animateTransition(
  element: HTMLElement,
  initialStyle: initialStyle,
  done: () => void,
  keyframes: Keyframe[] | PropertyIndexedKeyframes | null,
  options?: number | KeyframeAnimationOptions
) {
  const animation = element.animate(keyframes, options);
  // Set height to 'auto' to restore it after animation
  element.style.height = initialStyle.height;
  animation.onfinish = () => {
    element.style.overflow = initialStyle.overflow;
    done();
  };
}

function getEnterKeyframes(height: string, initialStyle: initialStyle) {
  return [
    {
      height: closed,
      opacity: props.opacityClosed,
      paddingTop: closed,
      paddingBottom: closed,
      borderTopWidth: closed,
      borderBottomWidth: closed,
      marginTop: closed,
      marginBottom: closed,
    },
    {
      height,
      opacity: props.opacityOpened,
      paddingTop: initialStyle.paddingTop,
      paddingBottom: initialStyle.paddingBottom,
      borderTopWidth: initialStyle.borderTopWidth,
      borderBottomWidth: initialStyle.borderBottomWidth,
      marginTop: initialStyle.marginTop,
      marginBottom: initialStyle.marginBottom,
    },
  ];
}

function enterTransition(element: Element, done: () => void) {
  const HTMLElement = element as HTMLElement;
  const initialStyle = getElementStyle(HTMLElement);
  const height = prepareElement(HTMLElement, initialStyle);
  const keyframes = getEnterKeyframes(height, initialStyle);
  const options = { duration: props.duration, easing: props.easingEnter };
  animateTransition(HTMLElement, initialStyle, done, keyframes, options);
}

function leaveTransition(element: Element, done: () => void) {
  const HTMLElement = element as HTMLElement;
  const initialStyle = getElementStyle(HTMLElement);
  const { height } = getComputedStyle(HTMLElement);
  HTMLElement.style.height = height;
  HTMLElement.style.overflow = "hidden";
  const keyframes = getEnterKeyframes(height, initialStyle).reverse();
  const options = { duration: props.duration, easing: props.easingLeave };
  animateTransition(HTMLElement, initialStyle, done, keyframes, options);
}
</script>

<template>
  <Transition :css="false" @enter="enterTransition" @leave="leaveTransition">
    <slot />
  </Transition>
</template>
```

### Alternative

Simple CSS max-height solution is OK, however, has unpredictable (based on contend rendering result) visual animation duration. ScaleY solution can be a bit messy for some users. Clip solution is good, but it can't be used when the element is incorporated into the main layout (e.g. for some additional form field to apper on checkbox click), etc.

I started with this [blog post](https://markus.oberlehner.net/blog/transition-to-height-auto-with-vue/) and somehow improved it (mostly to keep the initial style of the content block after the end of the transition). The main change is the switch to Web Animation API, which seems as performant as pure CSS animation and provides much more control.  This also had eliminated all performance optimization hack from the original solution. 

### Additional context

If it seems to be a useful addition to VueUse I will be happy to rewrite this code to comply to the project coding style. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jd-0001** [comment]
why don't you make a PR? I am not an expert at animation but it looks good. 👍🏻

**Comment by antfu** [comment]
Did you know this? https://vueuse.org/core/usetransition/

**Comment by jd-0001** [comment]
If you are asking me. Yes, I follow every update of vueuse.

I don't have any idea regarding height transition.

**Comment by kostyfisik** [comment]
> Did you know this? https://vueuse.org/core/usetransition/

I read this before, but there is still some non-trivial code to make it work for height transition. 

Two main points to address with a proper height transition:
1) It should work fine for any content. The rendered block height is not known at advance, so it should be evaluated just before showing it with `v-if` or `v-show`. Thus, you need to evaluate the content height in a correct way just before `useTransition()` call
2) Height transition leads to a relayout of the whole page, not just `<div>` to be toggled, so performance is important. As far as I understand, `useTransition()` is based on Vue reactivity, so it is pure JS approach to animation and it might not be very performant.

However, if it makes sense to have `useTransitionHeight` component, I can try to make a prototype based on `useTransition()` and compare the performance of `useTransition` vs Web Animation API directly. @antfu Just let me know that is makes sense.

**Comment by kostyfisik** [comment]
3. I suppose that CSS or Web Animation API are the most energy-efficient ways of animation, so it is a way to make UI eye candy and more intuitive, while taking care of the user's phone\laptop battery...

**Comment by antfu** [comment]
Ok sounds good. But how do you expect it to be implemented with composition apis? If it works only as a component I would suggest to publish it in another lib or framework, instead of VueUse tbh.

**Comment by kostyfisik** [comment]
As soon as it may be useful for VueUse, I took a look to some other VueUse functions. To make this new feature to look and feel native, I propose the following API draft usage example:
```javascript
import { useHeightTransition } from '@vueuse/core'
const element = ref<HTMLDivElement>()
const { shrinkHeight, expandHeight } = useHeightTransition()

//later...
shrinkHeight(element)
//or
expandHeight(element)
//or using standard Vue transition
<template>
  <Transition :css="false" @enter="expandHeight" @leave="shrinkHeight">
    <SomeCustomComponent />
  </Transition>
</template>
``` 
There are many details, which I omitted in this draft, e.g. `useHeightTransition()` should have some optional parameters, like `transitionDuration`, `shrinkEasing`, `expandEasing`, etc. send as a configuration object. At the moment, the only requirement, is that it should work nicely with Vue's `Transition` (and if it is possible to manage to make it work with `TransitionGroup` it would be my ideal). However, what is a reasonable default behavior for expandHeight() when applied to a random HTMLDivElement - I simply don't have an answer for this right now.

If it looks reasonable for you - just let me know and I will try to find some time to work on this. I don't think it should go to some UI framework, this is a very basic and common demand. On the other hand, it should be 100% compatible with Vue native `Transition`, so VueUse seems to be a right place IMHO (but I can obviously be wrong with this).  VueUse for Vue.js looks to be like a standard library for C++, so any other generic lib (like lodash) doesn't fit my demand for good integration with Vue.js.

**Comment by antfu** [comment]
Sure! Let's see the implementation and discuss it then. Thanks!

**Comment by kostyfisik** [comment]
Good. I think it will take several weeks for me to prepare a draft of the merge request.

**Comment by kostyfisik** [comment]
@antfu @jd-solanki  I have prepared an early implementation example, it works, but it still needs to be refactored to become cleaner and to cover all known corner cases. However, you are welcome to provide some early feedback on this, especially on Demo section.

**Comment by kostyfisik** [comment]
Sorry, I've changed the company where I work and got immediately overloaded... I will reopen the issue as soon as I have any updates on this...
