### ISSUE TITLE
useFetch doesn't play nice with async/await (await-thenable)

### ISSUE THREAD

**Issue by francoism90** [vueuse/vueuse#1321]
### Describe the bug

```
// Valid
const { data } = await api(`books/${id}`);

// Not valid
const { data } = await api(`books/${id}`).get().json<BookResponse>();
```

Note: This is TS/eslint ruling, bit difficult to reproduce this using a link.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rptfks/

### System Info

```Shell
$ npx envinfo --system --npmPackages '{vue,@vueuse/*}' --binaries --browsers

  System:
    OS: Linux 5.16 Arch Linux
    Container: Yes
  Binaries:
    Node: 17.6.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.5.2 - /usr/bin/npm
  npmPackages:
    @vueuse/core: ^7.6.2 => 7.7.0 
    vue: ^3.2.31 => 3.2.31
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by webfansplz** [comment]
Can you provide a correctly mini repo ?

**Comment by francoism90** [comment]
@webfansplz https://github.com/francoism90/mediadb-app/blob/a37cb876dabe786166b9e9ea533ec6e26c95f587/src/composables/useVideo.ts#L14

Also it seems to return a JSON parse error (500, 404, 403, etc.), instead of the actual error.

**Comment by webfansplz** [comment]
> @webfansplz https://github.com/francoism90/mediadb-app/blob/a37cb876dabe786166b9e9ea533ec6e26c95f587/src/composables/useVideo.ts#L14
> 
> Also it seems to return a JSON parse error (500, 404, 403, etc.), instead of the actual error.

This repo seems too big 😂 , you should provide a mini repo so that we can reproduction it quickly .

P.S.  It's worked fine in our test case .

**Comment by francoism90** [comment]
@webfansplz Do you use any eslint/linting rules? It could be a mistake by the linter/checker.

What happens if you fetch an incorrect URL with the json parse method?

Also another question, when using await you cannot use isFetching right? Because I would expect it to wait.

For me skipping the await part doesn't always play nicely, for some reason it doesn't seem to populate data ({ data } = UseFetch(..))

**Comment by wheatjs** [comment]
If you are using `await` you need to use the Vue `Suspense` API as well. `isFetching` will also be useless when using await. If you don't use await you can instead just watch the data and you won't have to use the Suspense api, like this

```ts
const { data } = useFetch(url)

watch(data, () => {
  console.log(data.value)
})
```

**Comment by francoism90** [comment]
@kyranet Thanks for the fix! :)

**Comment by kyranet** [comment]
Glad to help :)

The fix has also been released quite quickly 🎉
