### ISSUE TITLE
'usePreferredDark' is also true for the light theme

### ISSUE THREAD

**Issue by jannikbuscha** [vueuse/vueuse#1326]
### Describe the bug

[usePreferredDark](https://vueuse.org/core/usePreferredDark/) remains true even if you set the page to light theme. It only looks at what the browser has set to theme, shouldn't it do this? isn't that what [usePreferredColorScheme](https://vueuse.org/core/usePreferredColorScheme/) is for?

![image](https://user-images.githubusercontent.com/74017697/155898183-f6a40ee0-a8df-4631-b74e-89b12ec4ba1a.png)

### Reproduction

https://vueuse.org/core/usePreferredDark/

### System Info

```Shell
/
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It is the preference of your system, not the site. `useDark` might be what you want.

**Comment by jannikbuscha** [comment]
> 

All right, then I misunderstood. But then I would have another question. Why is this element not reactive when I change the theme via the theme selector in the navbar? 
![image](https://user-images.githubusercontent.com/74017697/155898451-b3be3525-7314-472a-8db8-2100f6876b73.png)

I have a similar usecase. I would like to get the current theme as text in a component and this text should always update itself as soon as the theme changes via the theme selector. What possibilities do I have there?

**Comment by antfu** [comment]
It works for me tho

**Comment by jannikbuscha** [comment]
> It works for me tho

https://user-images.githubusercontent.com/74017697/155899546-f2ab62d8-d06f-4728-9dee-7d84120686a9.mp4

I tested it in chrome, edge, firefox and brave, everywhere the button text updates only when i reload the page.
