### ISSUE TITLE
useDocumentVisibility: VisibilityState not found in TypeScript 4.6

### ISSUE THREAD

**Issue by Shinigami92** [vueuse/vueuse#1334]
### Describe the bug

```node
❯ npx vue-tsc --noEmit
node_modules/@vueuse/core/index.d.ts:1153:82 - error TS2304: Cannot find name 'VisibilityState'.

1153 declare function useDocumentVisibility({ document }?: ConfigurableDocument): Ref<VisibilityState>;
                                                                                      ~~~~~~~~~~~~~~~


Found 1 error in node_modules/@vueuse/core/index.d.ts:1153
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-enmwba?devtoolsheight=33

### System Info

```Shell
System:
    OS: Linux 5.14 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 48.76 GB / 62.44 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 97.0
  npmPackages:
    @vueuse/core: ~7.7.0 => 7.7.0 
    vue: ~3.2.31 => 3.2.31
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by webfansplz** [comment]
Be related to https://github.com/vueuse/vueuse/pull/1232, I found this problem before `TS 4.6` release.

`TS 4.6` use `DocumentVisibilityState` instead of `VisibilityState` , but i don't sure how we can be compatible with below  `TS 4.6` if we update it . 😂
