### ISSUE TITLE
Allow useAxios without an url

### ISSUE THREAD

**Issue by aalsamoht** [vueuse/vueuse#1347]
### Clear and concise description of the problem

I would like to be able to call `useAxios` without an url, it would be great if the following method signatures could be supported:

```ts
useAxios() // implicit immediate=false or pass the option { immediate: false }
useAxios(AxiosInstance) // also immediate=false
useAxios(AxiosRequestConfig)
useAxios(AxiosRequestConfig, AxiosInstance)
```

With `useAxios(AxiosInstance)` it would be easier to extend `useAxios` with a shared config:

```ts
export const axiosWithToken = axios.create({
  baseURL: config.baseURL,
  timeout: config.timeout,
});

axiosWithToken.interceptors.request.use(async (axiosConfig) => {
  // ....

  axiosConfig.headers.Authorization = `Bearer ${response.accessToken}`;

  return axiosConfig;
});

// Import and use this version of useAxios for protected APIs
export function useTokenAxios(config?: AxiosRequestConfig) {
  return useAxios(config, axiosWithToken);
}
```

I would like to keep all my endpoint configuration in the same place:
```ts
export const bookEndpoints = {
  getAll(): AxiosRequestConfig {
    return { url: 'books' };
  },
  getPaged(pageSize: number, pagenumber: number): AxiosRequestConfig {
    return { url: 'books', params: { pageSize, pagenumber } };
  },
  getSingle(id: string): AxiosRequestConfig {
    return { url: `books/${encodeURIComponent(id)}`, transformResponse: transformData };
  },
  create(objData: unknown): AxiosRequestConfig {
    return { url: 'books', method: 'POST', data: objData };
  },
  update(id: string, objData: unknown): AxiosRequestConfig {
    return { url: `books/${encodeURIComponent(id)}`, method: 'PUT', data: objData };
  },
  delete(id: string): AxiosRequestConfig {
    return { url: `books/${encodeURIComponent(id)}`, method: 'DELETE' };
  },
};
```

API usage:
```ts
// create, update, delete or something else that is not going to be executed in setup
const { execute } = useAxios() // implicit immediate=false or pass the option { immediate: false }

// execute the request some time in the future when the user has updated the data
execute(bookEndpoints.update('aBzw', myUpdatedBook))

// others executed immediately
useAxios(bookEndpoints.getAll())
// or
useAxios(bookEndpoints.getAll(), axiosWithToken)
// or 
useTokenAxios(bookEndpoints.getAll())
```

### Suggested solution

`useAxios` could allow the new method signatures or a new method could be exposed without the url. E.g.
```ts
useAxios(url : string) {
  return useAxiosWithoutUrl( { url: url } );
}
```

### Additional context

Since `useAxios` uses `axios(url, config)` it is not possible to override the url using the config.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hengshanMWC** [comment]
Judge that the first parameter is not a string. The default is {immediate: false}, and then execute (executeurl: String = URL, config: axiosrequestconfig = {}). The change is small. I've just made changes to useaxios. When it's passed, I'll be happy to modify it

**Comment by femaimi9527** [comment]
do we have any methods to do useAxios requests with formdata like upload a file to some url or some server address ？

**Comment by aalsamoht** [comment]
Sounds great @hengshanMWC. Just for claification. 

It would be nice if `instance` in the `execute` function was not called with the parameter `url`.

I.e. change from ` instance(url, { ...defaultConfig, ...config, cancelToken: cancelToken.token })` to ` instance({ ...defaultConfig, ...config, cancelToken: cancelToken.token })`.

So when `useAxios` is called with a `url: string` set the defaultConfig to `{ url }`.

```ts
// Not possible today since axios does not overwrite the url set on its instance
// axios(url, { url: otherUrl }) will use the first url
const { execute } = useAxios('https://demo.com/profile/1'`);

execute({ url: 'https://demo.com/profile/999' } ) // uses https://demo.com/profile/1
```

```ts
useAxios('https://demo.com/profile/1');
useAxios({ url: 'https://demo.com/profile/1' });

// Current implementation always uses the first url, maybe the new one should always use the second one?
// defaultConfig = { url } // profile/1
// mergedConfig = { ..defaultConfig, ..parameterConfig } // result: profile/999
useAxios('https://demo.com/profile/1', { url: 'https://demo.com/profile/999' });
```

**Comment by hengshanMWC** [comment]
Now I don't understand the goal of the module 'useaxios'. In fact, I have written a set of solutions for the scheme I mentioned above, but I don't know if it is what you want

**Comment by aalsamoht** [comment]
I'll try to explain with some code.


```ts
useAxios() // options = { immediate: false }
useAxios(instance: AxiosInstance) // options = { immediate=false }
useAxios(config: AxiosRequestConfig, options?: UseAxiosOptions)
useAxios(config: AxiosRequestConfig, instance: AxiosInstance, options?: UseAxiosOptions)

// Changes to existing api
useAxios(url: string, config?: AxiosRequestConfig, options?: UseAxiosOptions) // defaultConfig = { url: url, ...args[0] }
useAxios(url: string, instance?: AxiosInstance, options?: UseAxiosOptions) // if ('request' in args[0]) { instance = args[0]; defaultConfig = { url };  }      
useAxios(url: string, config: AxiosRequestConfig, instance: AxiosInstance, options?: UseAxiosOptions) // defaultConfig = { url: url, ...args[0] }
```

```ts
 const execute = (config: AxiosRequestConfig = {}) => {
    loading(true)
    // Remove url from instance function call
    instance({ ...defaultConfig, ...config, cancelToken: cancelToken.token })
   // ...
```

```ts
axios(urlUsedByAxios);
axios(urlUsedByAxios, { url : 'https://url.ignored.by.axios' } );
axios({ url : 'https://url.used.by.axios' });
```

**Comment by hengshanMWC** [comment]
@aalsamoht `execute` inferred by `typescript` type
- When `useAxios' passes the `url`, the `url` of 'execute' can choose not to pass it
- `useAxios` does not pass the `url`, but the `url` of 'execute' is mandatory.
I think it can replace `{url}` this scheme
```ts
const { execute } = useAxios()
// When you don't pass the url, typescript will prompt you to pass the url
execute(url)
```
```ts
const { execute } = useAxios(url, {}, {  immediate: false })
// The url here is optional, and url2 will replace the url. I want to replace {url} in this way
execute(url2)
```
But if you use `{url}` this scheme, the code will become more complex than the one above.Of course, it depends on how managers feel about this scheme and whether it is worth doing

**Comment by hengshanMWC** [comment]
[The above scheme is implemented](https://github.com/hengshanMWC/vueuse/blob/useAxios-url-handle/packages/integrations/useAxios/index.test.ts)

**Comment by aalsamoht** [comment]
Ah I see @hengshanMWC. All these changes do increase the complexity of `useAxios', it would be nice get an answer to #1374.

**Comment by hengshanMWC** [comment]
@aalsamoht Maybe I can try sending a pr

**Comment by hengshanMWC** [comment]
@aalsamoht Functions have been merged
