### ISSUE TITLE
useFetch

### ISSUE THREAD

**Issue by hmendes00** [vueuse/vueuse#1349]
### Describe the bug

**PATCH** is not working (or at least it seems to not work)
The reason seems to be behind the **METHOD** being added in **lowercase** when doing the call.

The following won't work:
`import { useFetch } from '@vueuse/core';

const response = await useFetch('https://jsonplaceholder.typicode.com/posts/1')
  .patch(JSON.stringify({ a: 'sss' }), 'application/json')
  .json();` 
  
  While the one bellow will:
  `const { data } = await useFetch(
  'https://jsonplaceholder.typicode.com/posts/1',
  {
    body: JSON.stringify({ a: 'asdad' }),
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
  },
  {}
).json();`

It looks like in the specs it's not specified that patch should be uppercased, but unless there's a workaround or something that I am missing it should be.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-i7csp1/?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.35 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Safari: 13.1.2
  npmPackages:
    @vueuse/core: ^7.5.5 => 7.6.1 
    vue: ^3.2.2 => 3.2.29
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by okxiaoliang4** [comment]
Fixed: #1336
