### ISSUE TITLE
useMagicKeys: Alt is left after switching windows using Alt + Tab

### ISSUE THREAD

**Issue by weakfi** [vueuse/vueuse#1350]
### Describe the bug

Open page in browser, then switch windows using Alt + Tab and then again Alt + Tab to switch back to the page,
the Alt key is still there, which should be disappear

This bug can be recreate on demo page:
https://vueuse.org/core/usemagickeys/
![chrome-capture-2022-2-4 (1)](https://user-images.githubusercontent.com/37606164/156733613-29e2a7a7-00fe-4829-83f6-1cc8aa721e04.gif)

### Reproduction

https://vueuse.org/core/usemagickeys/

### System Info

```Shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 2.83 GB / 15.72 GB
  Binaries:
    Node: 16.13.2 - D:\software\nodejs_16.13.2\node.EXE
    npm: 8.1.2 - D:\software\nodejs_16.13.2\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.62)
    Internet Explorer: 11.0.19041.1202
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by weakfi** [comment]
@antfu 麻烦看看这个问题，用Alt + Tab从页面切换到其他窗口的时候，Alt被按下状态没有消失

**Comment by CapitaineToinon** [comment]
This seems to be caused by combinations of keys where after being pressed, the window loses focus and therefore the key up event for modifier keys is never fired. Not really a solution but as a fix for my project, I've been just cleaning all inputs after blur and focus as my key shortcuts makes no sense when the user leaves the page anyway. 

```js
const { ControlLeft, Enter } = useMagicKeys();

const clear = () => {
  ControlLeft.value = false;
  Enter.value = false;
};

// Fix for https://github.com/vueuse/vueuse/issues/1350
useEventListener('blur', clear);
useEventListener('focus', clear);

whenever(and(ControlLeft, Enter), () => {
  // do whatever
});
```
