### ISSUE TITLE
useVirtualList with Vue2 - list is not reactive

### ISSUE THREAD

**Issue by johannes-z** [vueuse/vueuse#1364]
### Describe the bug

I'm using Vue2 and `useVirtualList` does not render anything. `list` stays empty.

Ref #1078 (#951 Vue3)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-uuio2f

### System Info

```Shell
Stackblitz template; 


{
  "name": "vite-starter",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "postinstall": "vue-demi-fix"
  },
  "dependencies": {
    "@vue/composition-api": "^1.4.9",
    "@vueuse/components": "^7.7.1",
    "@vueuse/core": "^7.7.1",
    "vue": "^2.6.14",
    "vue-demi": "^0.12.1"
  },
  "devDependencies": {
    "vite": "^2.8.6",
    "vite-plugin-vue2": "^1.9.3",
    "vue-template-compiler": "^2.6.14"
  }
}
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by johannes-z** [comment]
In `@vue/composition-api` the template refs work differently, so I had to explicetly add the ref attribute to the container, and return the ref from the setup like so:

```html
    <div
      v-bind="containerProps"
      ref="containerRef"
      class="h-300px overflow-auto p-2 bg-gray-500/5 rounded"
    >
   ...
   </div>
```

```ts
    return {
      list,
      containerProps,
      containerRef: containerProps.ref,
      wrapperProps,
    };
```

It then shows the data. I don't think this is fixable by vueuse, but maybe it could be mentioned in the docs?

**Comment by xinlei3166** [comment]
mark

**Comment by johanneslo1** [comment]
I had to add the scroll event manually too:


`const { list, containerProps, wrapperProps } = useVirtualList(filteredList, {
  itemHeight: 22,
});

const containerRef = containerProps.ref;`

`<div
      ref="containerRef"
      style="height: 300px; overflow-y: auto;"
      @scroll="containerProps.onScroll"
    >
      <div v-bind="wrapperProps">
        <div v-for="item in list" :key="item.index" style="height: 22px">
          Row: {{ item.data }}
        </div>
      </div>
    </div>`

**Comment by johannes-z** [comment]
bump

**Comment by johannes-z** [comment]
not completed
