### ISSUE TITLE
useAxios: waitUntilFinished Is there a better solution

### ISSUE THREAD

**Issue by hengshanMWC** [vueuse/vueuse#1368]
### Clear and concise description of the problem

Now in order to complete the asynchronous wait，
```js
const { execute, then } = useAxios(url,{}, { immediate: false})
execute()
then((result) => {
      // logical processing
})
```

### Suggested solution

Should it be optimized into
```js
const { execute } = useAxios(url,{}, { immediate: false})
execute()
  .then((result) => {
      // logical processing
  })
```

### Alternative

# benefit
`execute` has the risk of being called many times. `execute` uses a `promise` as a lock internally. When calling `execute`, judge whether there is a lock. If there is a lock, return `lockPromise`. If not, call instance to initiate a request and generate a `new promise` as a lock. In that case
- keep the consistency of function use and reduce the mental burden. Only operate `execute`
- return data consistency
- reduce potential HTTP duplicate requests

# doubt
In the current usage scenario of `useAxios`, do you need to call `useAxios` again for each new request

### Additional context

#Feeling after reading
- [Relevant pr-1228](https://github.com/vueuse/vueuse/pull/1228)
- [Relevant issue-1264](https://github.com/vueuse/vueuse/issues/1264)
- [Relevant issue-1347](https://github.com/vueuse/vueuse/issues/1347)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
The current implementation is for the `useAxios` to be awaited directly. In the case of using `execute` we could probably return a promise like we do in `useFetch` https://github.com/vueuse/vueuse/blob/main/packages/core/useFetch/index.ts#L322
