### ISSUE TITLE
useDark not Reactive

### ISSUE THREAD

**Issue by jannikbuscha** [vueuse/vueuse#1369]
### Describe the bug

I would like to get the current theme as text in a component and this text should always update itself as soon as the theme changes via the theme selector. What possibilities do I have there?

I tested it in chrome, edge, firefox and brave, everywhere the button text updates only when i reload the page.

https://user-images.githubusercontent.com/74017697/156927958-d0f32894-81fa-44bd-8454-7d14e6a2d67f.mp4

### Reproduction

<span>{{ useDark() ? 'Dark' : 'Light' }}</span>

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 17.09 GB / 31.95 GB
Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.30)
    Internet Explorer: 11.0.19041.1202
npmPackages:
    @vueuse/core: ^7.7.0 => 7.7.0
    @vueuse/shared: ^7.7.0 => 7.7.0
    vue: ^3.2.29 => 3.2.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
You can export the `useDark` function from a file and use that across you components. See here for how it is done in a vue 3 template https://github.com/antfu/vitesse/blob/main/src/composables/dark.ts
