### ISSUE TITLE
useEventListener not remove event when onUnmounted, Even though page Unmounted the event  also trigger.Why?

### ISSUE THREAD

**Issue by WormGirl** [vueuse/vueuse#1370]
### Describe the bug

I use useEventListener bind doucument click event at page, when the page is unMounted, the event also trigger, actualy not removeed when page unMounted.

### Reproduction

no

### System Info

```Shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 4.26 GB / 15.79 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - D:\project\USTA-vm\vm-front\manage\node_modules\.bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (99.0.1150.30)
    Internet Explorer: 11.0.19041.906
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by okxiaoliang4** [comment]
Can you provide a mini repo?
I think we've handled it.
https://github.com/vueuse/vueuse/blob/6cc8d1f4512f8ded294a2556cecad590c6435acd/packages/core/useEventListener/index.ts#L123

**Comment by WormGirl** [comment]
this is work fine now at version 8.2.2.

**Comment by WormGirl** [comment]
this may not at version `"@vueuse/core": "^7.4.1"`
