### ISSUE TITLE
useColorMode not working properly during SSR

### ISSUE THREAD

**Issue by p1atdev** [vueuse/vueuse#1378]
### Describe the bug

I encountered this unnatural behavior when using useColorMode in SSR mode.
This bug did not occur when `ssrHandlers` was not set to true.

https://user-images.githubusercontent.com/60182057/157280696-3e2f0271-22e1-4db1-882f-21a54685825e.mov

(Safari 15.4)

When using useColorMode and switching CSS by theme, colors are not reflected correctly when reloading the page.
For a moment I see the correct colors on the screen, but somehow it returns to the default colors.

### Reproduction

https://github.com/p1atdev/vueuse_useColorMode

### System Info

```Shell
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 72.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.anyenv/envs/nodenv/versions/16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.anyenv/envs/nodenv/versions/16.13.1/bin/npm
  Browsers:
    Firefox: 97.0.1
  npmPackages:
    @vueuse/core: ^7.7.1 => 7.7.1 
    @vueuse/nuxt: ^7.7.1 => 7.7.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hengshanMWC** [comment]
put to onMounted?

**Comment by hengshanMWC** [comment]
put onMounted?
