### ISSUE TITLE
Whether the document supports Chinese

### ISSUE THREAD

**Issue by gastrodia** [vueuse/vueuse#1379]
### Clear and concise description of the problem

Can create a Chinese document project to support Chinese

### Suggested solution

document  supports Chinese

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by okxiaoliang4** [comment]
No such plan for now
