### ISSUE TITLE
new function animateHeight

### ISSUE THREAD

**Issue by jd-0001** [vueuse/vueuse#1382]
### Clear and concise description of the problem

I use unocss & vueuse for my small projects and I build a few components myself. Things get interesting when it comes to animating height.

As vueuse 8 is providing directive support it will also provide support for function/directive like animate height which is better created by an experienced developer for smooth (almost smooth) animation. It is useful in various cases:
* collapse component
* expandable data in the table component

### Suggested solution

BootstrapVue provide [collapse directive](https://bootstrap-vue.org/docs/components/collapse).

### Alternative

None

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kostyfisik** [comment]
@jd-0001 FYI, see my #1316, which is a similar proposal, so these one can be considered as a duplicate.  Note, that Boostrap solution is not smooth for [two elements](https://bootstrap-vue.org/docs/components/collapse#trigger-multiple-collapse-elements)  (at least for me, tested Chrome and Firefox) when closing. I would be great, if you can test my solution [demo](https://height-transition-vue3-web-animation-api.netlify.app/), feel free to report any problems on it, I will try to check it out and fix it.
