### ISSUE TITLE
POST 请求在createFetch后不立即执行会变成GET请求

### ISSUE THREAD

**Issue by gp3098** [vueuse/vueuse#1403]
### Describe the bug

```javascript
import { createFetch } from '@vueuse/core'
const useRequest = createFetch({
  baseUrl: 'https://play.vueuse.org',
  options: {
    async beforeFetch({ options, url }) {
      if (options.params) {
        options.headers['Content-Type'] = 'application/json;charset=utf-8';
        options.body = JSON.stringify(options.params);
      }

      return { options, url };
    },
  },
  fetchOptions: {
    mode: 'cors',
  },
});

const  {execute} = useRequest('/fetch',{
method:'POST',
immediate:false
})

execute();
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-fyd31u?file=src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 153.23 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Edge: 98.0.1108.56
    Safari: 15.3
  npmPackages:
    @vueuse/core: ^8.0.0 => 8.0.0 
    vue: ^3.2.25 => 3.2.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by okxiaoliang4** [comment]
使用方法是这样的哦

```typescript
import { createFetch } from '@vueuse/core'

const useRequest = createFetch({
  // baseUrl: '/',
  fetchOptions: {
    mode: 'cors',
  },
})

const { execute } = useRequest('/fetch', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json;charset=utf-8',
  },
  body: JSON.stringify({ id: 1 }),
}, {
  immediate: false,
})

execute()
```
