### ISSUE TITLE
Can't toggle by using '@click' with onClickOutside

### ISSUE THREAD

**Issue by onurusluca** [vueuse/vueuse#1405]
### Describe the bug

onClickOutside doesn't let me toggle the menu item on click. It opens it, onClickOutside works fine but can't close the menu by clicking the button again.
There is a workaround but maybe this should be corrected?: https://github.com/vueuse/vueuse/issues/1245

### Reproduction

https://stackblitz.com/edit/vitejs-vite-7v9ofd/?file=src%2Fmain.js

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 19.21 GB / 31.77 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.39)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
There is no single solution for all use cases. 

I sent a PR at https://github.com/vueuse/vueuse/pull/1406. It does add a new option to let you pick the event phase of internal event listener.

When it's released you chould pass it as third argument:

```ts
onClickOutside(dropdownRef, () => {
  dropdownOpen.value = false;
}, { capture: false });
```

Kindly note that, when using bubbling phase, our event listener will take priority from your in-template click listener. That means, even if you click the open menu button it won't work. Because the click event will bubble all the way up until `window` and your `onClickOutside` callback will run and set `dropdownOpen.value` to `false`. To prevent this add `.stop` modifier to your click listener:

```html
<button @click.stop="dropdownOpen = !dropdownOpen">OPEN MENU /></button>
```

For now, as a workaround I would suggest doing that:
```ts
onClickOutside(dropdownRef, (e) => {
  dropdownOpen.value = e.target.dropdown ?? false;
});
```
```html
<button .dropdown="!dropdownOpen">OPEN MENU /></button>
```

**Comment by onurusluca** [comment]
@sibbng Thank you for the quick reply and the PR.

Uh, yeah. I forgot to add .stop to reproduction.

`e.target.dropdown` gives "Object is possibly null" and "Property dropdown does not exist on type 'EventTarget'.
Works only with button element I guess. It didn't work on my 'span'.

It works for now and you kindly made a PR so I am closing this and accepting you reply as solution.

Thanks! Teşekkürkler!

**Comment by sibbng** [comment]
> Uh, yeah. I forgot to add .stop to reproduction.

I meant to say, you will need `.stop` if you disable capture phase by adding `, { capture: false }`.

> `e.target.dropdown` gives "Object is possibly null" and "Property dropdown does not exist on type 'EventTarget'.

```ts
onClickOutside(dropdownRef, (e) => {
  type DropdownButton = EventTarget & HTMLButtonElement & { dropdown: boolean } | null
  dropdownOpen.value = (e.target as DropdownButton)?.dropdown ?? false;
});
```

**Comment by onurusluca** [comment]
@sibbng Thanks a lot for the solution. 

I am being too much but is there a possibility that this code doesn't work with multiple instances?
I have another dropdown menu but onClickOutside won't work on that with this code.

Reproduction: https://stackblitz.com/edit/vitejs-vite-7v9ofd?file=src/App.vue

```
// Menu Dropdown
const dropdownOpen = ref(false);
const dropdownRef = ref(null);
// https://vueuse.org/core/onclickoutside/
onClickOutside(dropdownRef, (e) => {
  type DropdownButton = (HTMLButtonElement & { dropdown: boolean }) | null;
  dropdownOpen.value = (e.target as DropdownButton)?.dropdown ?? false;
});

// User Menu Dropwdown
const userMenuDropdownOpen = ref(false);
const userMenuDropdownRef = ref(null);
onClickOutside(userMenuDropdownRef.value, (e) => {
  type DropdownButton =
    | (HTMLButtonElement & { userMenuDropdown: boolean })
    | null;
  userMenuDropdownOpen.value =
    (e.target as DropdownButton)?.userMenuDropdown ?? false;
});
```

**Comment by sibbng** [comment]
Create another onClickOutside instance for it.

**Comment by onurusluca** [comment]
@sibbng Isn't that what I did here?

**Comment by sibbng** [comment]
> @sibbng Isn't that what I did here?

Sorry, I didn't look at your code carefully. You need to pass `userMenuDropdownRef` as **Ref**, not it's value.
```diff
- onClickOutside(userMenuDropdownRef.value, (e) => {
+ onClickOutside(userMenuDropdownRef, (e) => {
```

**Comment by onurusluca** [comment]
@sibbng Hi again!

I was wondering if the solution to this problem changed after the [PR](https://github.com/vueuse/vueuse/pull/1406) because I couldn't find it in the docs.

Also I can't use it with 'v-for'. Say we have different elements with menus and I want to toggle every menu but with this solution toggling affects all menus, not only the clicked one.

**Comment by sibbng** [comment]
It's documented in the Type Declarations section. https://vueuse.org/core/onClickOutside/#type-declarations

The `ignore` option might be what you are looking for or you need to craft your solution by combining multiple composition APIs. If you could post your questions on [Discussions](https://github.com/vueuse/vueuse/discussions) page with some code samples you might get an answer from other people too.

**Comment by anburocky3** [comment]
@sibbng How to work it with directives?

below is my code, `modal` is my vue's `ref()`
```js
  <button @click="modal = !modal">
    Toggle Modal
  </button>
  
  <div v-if="modal" v-on-click-outside="() => modal = false">
    Hello World
  </div>
```
