### ISSUE TITLE
useDraggable Initial Positioning not reactive

### ISSUE THREAD

**Issue by alexrafuse** [vueuse/vueuse#1418]
### Describe the bug

I am trying to create a draggable component. The draggable element should appear in the center of the parent:

Example here: https://stackblitz.com/edit/vitejs-vite-cbnyar?file=src%2FApp.vue

```
const { left, right, top, bottom } = useElementBounding(container);
const { width, height } = useElementBounding(draggable);

const { x, y } = useDraggable(draggable, {
  initialValue: { x: (right - left) / 2, y: (bottom - top) / 2 },
  preventDefault: true,
});
```

I have tried making the initialValue a computed field but that doesn't work either:
```
const { left, right, top, bottom} = useElementBounding(canvas);
const initialValue = computed(() => {
    return {
        x: (right.value - left.value),
        y: (bottom.value - top.value)
    }
})
const { x, y } = useDraggable(draggable, {
    initialValue: initialValue.value,
    preventDefault: true,
})
```
Any suggestions? Am I doing this incorrectly or is there a bug in the package?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-cbnyar?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 82.55 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - /opt/homebrew/bin/node
    npm: 8.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 98.0.1
    Safari: 15.1
  npmPackages:
    @vueuse/core: ^8.0.1 => 8.0.1 
    vue: ^3.2.30 => 3.2.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alexrafuse** [comment]
> Try this https://stackblitz.com/edit/vitejs-vite-e2rk8f?file=src%2FApp.vue

Great, thank you. I'm doing this in a modal so now I'm having issues with absolute positioning, but there is another issue opened on that topic. 

Much appreciated.

**Comment by wheatjs** [comment]
> > Try this https://stackblitz.com/edit/vitejs-vite-e2rk8f?file=src%2FApp.vue
> 
> Great, thank you. I'm doing this in a modal so now I'm having issues with absolute positioning, but there is another issue opened on that topic. #1288
> 
> Much appreciated.

If it helps that demo uses absolute positioning
