### ISSUE TITLE
When `useClipboard` calls the `copy` method without passing parameters, the value is `Event`.

### ISSUE THREAD

**Issue by Hongbusi** [vueuse/vueuse#1427]
### Describe the bug

When calling the `copy` method without passing parameters, the value is `Event`, and it cannot be successfully assigned to `unref(source)` in [vueuse/useClipboard](https://github.com/vueuse/vueuse/blob/main/packages/core/useClipboard/index.ts#L74).

Although I tried to solve it, I didn't find a solution that satisfied me.

### Reproduction

https://github.com/Hongbusi/learn-vueuse/blob/main/src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 51.89 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 97.0.1
    Safari: 15.1
  npmPackages:
    vue: ^3.2.25 => 3.2.31
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AllenYu0118** [comment]
You can try：`<button @click="copy">` = > `<button @click="copy()">`

**Comment by Hongbusi** [comment]
I know it works, but it doesn't seem perfect.

**Comment by antfu** [comment]
https://github.com/vueuse/vueuse/pull/1428#issuecomment-1069236193
