### ISSUE TITLE
LogicAnd - all elements of type boolean and false the function returns true

### ISSUE THREAD

**Issue by Xenoha** [vueuse/vueuse#1434]
### Describe the bug

When using the logicAnd function, the function uses the .every method. This will return true if all elements are of type boolean and are false.

When using logicAnd, the function should return truthy only if all params are true.

Moreover, as a side note. Your Reproduction link should provide an updated version of the package. The provided reproduction link doesn't have the logicAnd function in the package.

Please let me know if you have any further questions.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tfyfnr?file=src/App.vue

### System Info

```Shell
System:
    OS: Linux 5.13 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 6.10 GB / 31.20 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  npmPackages:
    @vueuse/core: ^8.0.1 => 8.0.1 
    @vueuse/integrations: ^7.6.2 => 7.6.2 
    vue: ^3.0.11 => 3.2.11
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
`logicAnd` returns a computed ref, so you would need to check `logicAnd(false, false).value` instead. Here is an example of it working as expected https://stackblitz.com/edit/vitejs-vite-cc4yip?file=src%2FApp.vue

**Comment by AllenYu0118** [comment]
First,the reproduction is not work 🤣

And, The `logicAnd` function return `ComputedRef` Proxy object.

so,you need to get value of the proxy object 😃

> The guys upstairs is so fast 😂

**Comment by Xenoha** [comment]
Blah, stupid error on my part. But, yes the linked example doesn't work because logicAnd isn't available in the playground to link issues.

Thanks Guys!

**Comment by AllenYu0118** [comment]
Yes, same question for me. 
you can try the following code in the example
 ```
import { and } from '@vueuse/core'
```
