### ISSUE TITLE
开多个窗口并修改使用 useStorage 创建的值, 有时另一个窗口的值不会更新

### ISSUE THREAD

**Issue by Zhang-Wei-666** [vueuse/vueuse#1444]
### Describe the bug

![](https://github.com/Zhang-Wei-666/Issues/raw/master/vueuse/vueuse/1/useStorage.gif)

### Reproduction

https://vueuse.org/core/usestorage/#demo

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz 
    Memory: 2.54 GB / 15.87 GB
  Binaries:
    Node: 16.13.2 - D:\Program Files\nodejs\node.EXE        
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.36)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by manchixue** [comment]
may be variable `synced` problem.
When type a char, will invoke `watchWithFilter` callback, change `synced` to `true`.
and type again, when executing `storage` callback, `synced` is `true` and will not trigger `read`
