### ISSUE TITLE
useWindowLocation does not update on vue router changes, or anchor clicks

### ISSUE THREAD

**Issue by Bobakanoosh** [vueuse/vueuse#1445]
### Describe the bug

The returned value of `useWindowLocation` doesn't update when using `createWebHistory` mode for the router, and when they navigate via an `<a>`.

This makes since based off the source, as `popstate` is triggered when using the browsers navigation, and then `hashchange` is only triggered (I assume) when using `createHashHistory` mode.

Locally I have made a copy of `useWindowLocation` and added the following:
```ts
let lastPath = location.pathname;
useEventListener(
	window,
	"click",
	() => {
		if (location.pathname != lastPath) {
			lastPath = location.pathname;
			state.value = buildState("routechange");
		}
	},
	{ passive: true },
);
```

It works, however, I'm not sure if this is the best solution or the solution that the library would want.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-xzhoad/?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19043
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 17.15 GB / 31.94 GB
  Binaries:
    Node: 16.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.46)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/components: ^7.3.0 => 7.4.0
    @vueuse/core: ^8.1.1 => 8.1.1
    @vueuse/head: ^0.7.4 => 0.7.4
    vue: ^3.2.29 => 3.2.29
```
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by manchixue** [comment]
I think i have found the problem why happened.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/31590999/160137208-09dadc3d-338f-4055-94c8-ecad61166b35.png">

When invoke by `<router-link>` , actually will go this function logic and cause event stop propogation.

**Comment by manchixue** [comment]
i think i have found the problem why it cause the problem..

<img width="468" alt="image" src="https://user-images.githubusercontent.com/31590999/160226358-8d0bb6fd-b508-46ec-89b7-eb94914277e4.png">

**Comment by ryanmoyo** [comment]
Maybe we should give a tip: using the api provided by vue-router when you use vue-router.
