### ISSUE TITLE
Function proposal: `useTypeAhead()`

### ISSUE THREAD

**Issue by 0x009922** [vueuse/vueuse#1450]
### Clear and concise description of the problem

In native UIs as well as in native `<select>` element there is a very useful a11y feature - "type ahead". It is easy to understand how it works from this demo:

https://user-images.githubusercontent.com/43530070/159703763-af3bc9e2-1852-4bfd-aa13-8539e82a7e0f.mov

In WAI-ARIA it is [described](https://www.w3.org/TR/wai-aria-practices-1.1/#listbox_kbd_interaction) as following:

> Type-ahead is recommended for all listboxes, especially those with more than seven options:
> - Type a character: focus moves to the next item with a name that starts with the typed character.
> - Type multiple characters in rapid succession: focus moves to the next item with a name that starts with the string of characters typed.

So, it would be great to have an easy-to-use composable that brings that so much useful feature! This feature is not so easy to implement, and it can greatly increase quality of an application and UX.

### Suggested solution

I've found an implementation of it in Material Components (in MDCList component): [typeahead.ts
](https://github.com/material-components/material-components-web/blob/f31a833fae6f132318068f30a24a12c6c0cc192f/packages/mdc-list/typeahead.ts). I think it can be ported.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by czh740132583** [comment]
That's a cool idea

**Comment by michealroberts** [comment]
I’m going to tackle this tomorrow unless anybody else is working on it? :)

**Comment by OrbisK** [comment]
a pr was closed with this comment: https://github.com/vueuse/vueuse/pull/1476#issuecomment-1116307947

closing this issue for now
