### ISSUE TITLE
until() doesn't expose all methods provided in the docs

### ISSUE THREAD

**Issue by bpolaszek** [vueuse/vueuse#1452]
### Describe the bug

Hello there,

I attempted to use for the 1st time `until()` but as opposed to what [the docs](https://vueuse.org/shared/until/#more-examples) say, `toBe` and `not.toBe` (that is the question) aren't exposed:

```js
import { until } from '@vueuse/core';

// ...
await until(someVar).not.toBe(undefined);
```

produces:

> Uncaught (in promise) TypeError: until(...).not.toBe is not a function

It works with `toMatch` tho:

```js
import { until } from '@vueuse/core';

// ...
await until(someVar).not.toMatch(v => undefined === v);
```

### Reproduction

See above

### System Info

```Shell
@vueuse/core@8.1.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by okxiaoliang4** [comment]
`someVar` is an array?

https://github.com/vueuse/vueuse/blob/13fde886b1b31fca74867e46768c7c6316b95212/packages/shared/until/index.ts#L156-L168

**Comment by bpolaszek** [comment]
Oh, yes indeed. 
I didn't notice there was such a difference.

My use case is to wait until an `undefined` ref becomes an array (which is fine to be empty).

```javascript
import { until } from '@vueuse/core';
import { useStore } from 'vuex`;

const store = useStore();
const items = computed(() => store.state.items); // Initialized as `ref()` e.g. `undefined`

await until(someVar).not.toBe(undefined); // store.state.items is no longer undefined, let's get started
```



IDK if this could / should be fixed.

**Comment by lsdsjy** [comment]
I think it's a design flaw of `until` API. This API has two modes: `Value` mode and `Array` mode, which have different API exposed. In your case, `items` should be considered as `Value` not `Array`(the return type of `until()` can confirm that). But on run-time, `until` un-refs the argument to check if it's an array. So if your ref is of type `ComputedRef<undefined | Item[]>` and is currently in fulfilled status(i.e. `Item[]`), `until` will work in `Array` mode.
A possible solution is to split `until` into two different APIs for `Value` mode and `Array` mode separately, like `until` and `untilArray`. @antfu Any idea?

**Comment by StevenJPx2** [comment]
I still have an issue with this.

**Comment by illegalnumbers** [comment]
I have an issue with this
