### ISSUE TITLE
需要中文文档

### ISSUE THREAD

**Issue by CFMJ** [vueuse/vueuse#1457]
### Clear and concise description of the problem

需要中文文档

### Suggested solution

需要中文文档

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by okxiaoliang4** [comment]
建议使用翻译软件翻译一下，暂时没有做中文文档的打算哦

**Comment by CFMJ** [comment]
好的 感谢回复
