### ISSUE TITLE
Add directories to the useFileSystemAccess function

### ISSUE THREAD

**Issue by josh-hemphill** [vueuse/vueuse#1466]
### Clear and concise description of the problem

According to the docs of the [File_System_Access_API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API), the browsers that support it also support [directories](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle).

Managing directories or having access to a whole directory can be huge for web apps that need to manage lots of data or perform administrative tasks on the filesystem.

### Suggested solution

There's enough shared functionality between creating and managing, files and directories, that for the most part the existing `useFileSystemAccess` api could be extended to support directories. 

Because the possible recursive nature of directories, it could get pretty complicated, and that may require parts of it to be broken out separately.

### Alternative

It could probably be implemented in userspace, but because the datatypes are set within `useFileSystemAccess` it would be hard to use both `useFileSystemAccess` and the direct native api at the same time.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tdoan2010** [comment]
Hi, is this feature implemented? How can I get a `FileSystemDirectoryHandle` from `useFileSystemAccess`?

**Comment by josh-hemphill** [comment]
It's been submitted in PR #3122 , just waiting on review and to find out whether it's eligible to be added.
