### ISSUE TITLE
proposal: Maybe, the documentation about `useWebNotification` can be more accurate

### ISSUE THREAD

**Issue by lazy59** [vueuse/vueuse#1469]
### Describe the bug

![image](https://user-images.githubusercontent.com/27847851/160762755-f881146c-0a75-4a20-abea-239fb5bee0a6.png)
As shown, `onClick` is considered as a function, but it is an instance of `EventHook`.

And as shown below, I think it might be more convenient for `onClick` to return as a function. 

```typescript
return {
    isSupported,
    notification,
    show,
    close,
    onClick: onClick.on,
    onShow: onShow.on,
    onError: onError.on,
    onClose: onClose.on,
  }
```

### Reproduction

https://github.com/vueuse/vueuse/blob/main/packages/core/useWebNotification/index.ts

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 1.42 GB / 7.76 GB
  Binaries:
    Node: 14.17.0 - C:\dev\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\dev\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.84
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by michael-observerly** [comment]
Thank you @lazy59 for this, I will update the documentation accordingly.
