### ISSUE TITLE
Module '"@vueuse/core"' has no exported member 'logicAnd'

### ISSUE THREAD

**Issue by aegorx** [vueuse/vueuse#1470]
### Describe the bug

![image](https://user-images.githubusercontent.com/13310883/160900951-a09cf87e-b1a9-411d-8a56-f60c39378988.png)

change

import { and } from '@vueuse/core';

### Reproduction

-

### System Info

```Shell
 v 7.4.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
What version are you using? `logicAnd` was introduced in v8.0 as an alias of `and`

**Comment by aegorx** [comment]
@wheatjs 

version 7.4.1
