### ISSUE TITLE
useVModel work isn't correct?

### ISSUE THREAD

**Issue by Luferov** [vueuse/vueuse#1477]
### Describe the bug

useVModel work isn't correct? Values ​​​​on the used component are not updated.

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDgBdZhGOgGM1oUAAQTAYEmC3QoFSuoMEFSRAAPFRsgA+AA62FTMrqGdwqRUxAoeFYNAMAF5syBpHXhjm82BrJngMB4ioDgdU8NW4hm32M8RM88xdIiHRdXVpCpO9YTAcahxZioAOQLde56d6jhzgscIvJtJGVd4DeTYaH4+pGPkbfYXMzbDIOdz6sqRfadcAFUQmzSOu9gsswN5mCe948PGtBgEmKa8KmZhgAE8QhGAiC1vWAENiApblpWnhYV4UCGP+gF1mOzDiJIMhTjO+7zm4iBBtgiAAAqroMjDMaxiAAKL0HOy5nmum4PjuDFzp2eKKAAsoRBjdiuYnOjcPJ1Igj7PvIb4qK23jOJ+NB8ZxhnaMAuYqKWhjkGgKgAHKkHgpSIBwjC5gc9i5jpr5zpoH68WYAlCdoGDrvI6RgFQJ5oMQtlaX63lPrYulziRZE4Son6yQpVbaAZ3EbvFBgPjxAXJSyPZAA

### System Info

```Shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
    Memory: 16.33 GB / 31.29 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 17.8.0 - /usr/bin/node
    Yarn: 1.22.18 - ~/PycharmProjects/dcis/client/node_modules/.bin/yarn
    npm: 8.5.5 - /usr/bin/npm
  npmPackages:
    @vueuse/core: ^8.2.3 => 8.2.4 
    @vueuse/integrations: ^8.2.4 => 8.2.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by darrylnoakes** [comment]
You have some naming and typing issues.

Firstly, the event name should be `update:xxx`, not `onUpdate:xxx`.
Secondly, to use the default `v-model` without an argument (just `v-model` instead of `v-model:name`), the prop must be named `modelValue`. If it is not named `modelValue`, you must provide an argument to `v-model` (e.g. `v-model:myCoolName`).

Also, you are providing a string to a `v-model` that is expecting a number.

(Hope this doesn't sound snarky, wrote it in a hurry.)

So, to fix:

```ts
const props = defineProps({
  modelValue: String, // A
})

const emit = defineEmit(['update:modelValue']) // B

const localText = useVModel(props, 'modelValue', emit) // C
```

The names used in A, B, and C must all be the same.
If you use `modelValue`, use this:

```html
<Coordinate v-model="t"/>
```

If you name it anything other than `modelValue`, use this, where `xxx` is the name you used:

```html
<Coordinate v-model:xxx="t"/>
```
