### ISSUE TITLE
Support for days of week format string in `useDateFormat()`

### ISSUE THREAD

**Issue by andrewspy** [vueuse/vueuse#1478]
### Clear and concise description of the problem

It's nice to have the day of week format string in `useDateFormat()` as per `dayjs`.

Reference: https://day.js.org/docs/en/display/format

### Suggested solution

- Support `d`, `dd`, `ddd`, `dddd` format.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by webfansplz** [comment]
PR Welcome to add `d`,the others involved `locale`, which I don't think we'll add yet.

**Comment by andrewspy** [comment]
I think adding `d` variant and `a` variant would suffice for simplicity. Support for `locale` may be over-complicated.
