### ISSUE TITLE
useFetch: headers are ignored when other options are set

### ISSUE THREAD

**Issue by pierres** [vueuse/vueuse#1486]
### Describe the bug

The headers option is ignored when other options are set in useFetch(, url, options)

Example:
```
useFetch('https:/example.com/', {
  refetch: true,
  headers: { Accept: 'application/json' }
}).json()
```
This will send a request where the Accept-Header is set to "*/*". Removing the "refetch" option results in the correct header being set. This is not specific to "refetch" though. The same it true for e.g. "initialData" and other options.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zhwckh/?file=src%2FApp.vue

### System Info

```Shell
not relevant
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
Take a look at the last line of code in this section of the docs https://vueuse.org/core/usefetch/#setting-the-request-method-and-return-type

When setting both fetch request options and options for useFetch the second parameter is for fetch and the third parameter is `useFetch` specific
 
```ts
useFetch('https:/example.com/', { 
  headers: { Accept: 'application/json' } 
}, { refetch: true }).json()
```

**Comment by pierres** [comment]
Thanks a lot for the hint. I got it working now. I starred at the source and then documentation but did not see it.
