### ISSUE TITLE
useFetch: headers object missing in BeforeFetch context

### ISSUE THREAD

**Issue by mirorac** [vueuse/vueuse#1495]
### Describe the bug

The `beforeFetch` hook's context does not contain `headers` object, and therefore, one is forced to check for its presence.

For example, following code from the docs throws an error because we are trying to set `Authorization` property on an undefined `options.headers` object:
```typescript
const useMyFetch = createFetch({
  baseUrl: 'https://my-api.com',
  options: {
    async beforeFetch({ options }) {
      const myToken = await getMyToken()
      options.headers.Authorization = `Bearer ${myToken}`

      return { options }
    },
  },
  fetchOptions: {
    mode: 'cors',
  },
})

const { isFetching, error, data } = useMyFetch('users')
```

The following code works:
```typescript
const useMyFetch = createFetch({
  baseUrl: 'https://my-api.com',
  options: {
    async beforeFetch({ options }) {
      const myToken = await getMyToken()
      if (!('headers' in options)) {
        options.headers = {}
      }
      options.headers.Authorization = `Bearer ${myToken}`

      return { options }
    },
  },
  fetchOptions: {
    mode: 'cors',
  },
})

const { isFetching, error, data } = useMyFetch('users')
```

The code above works but it does not feel right to initialize library's object instances.
I think that [initialization of the beforeFetch context](https://github.com/vueuse/vueuse/blob/50de864cbe412c24279e1ee6b52cc4ed335c80ab/packages/core/useFetch/index.ts#L352) could use the existing [defaultFetchOptions](https://github.com/vueuse/vueuse/blob/50de864cbe412c24279e1ee6b52cc4ed335c80ab/packages/core/useFetch/index.ts#L338) object, which already contains an empty `headers` object.

For example:
```typescript
const context: BeforeFetchContext = { url: unref(url), options: {...defaultFetchOptions, ...fetchOptions}, cancel: () => { isCanceled = true } }
```
If this code was used, then the initialization of fetch object would not need [to spread `defaultFetchOptions` object](https://github.com/vueuse/vueuse/blob/50de864cbe412c24279e1ee6b52cc4ed335c80ab/packages/core/useFetch/index.ts#L371) anymore.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-e2xqwr/?file=src%2FApp.vue

### System Info

```Shell
npmPackages:
    @vueuse/core: ^8.2.6 => 8.2.6 
    vue: ^3.2.29 => 3.2.31
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hbshvn** [comment]
Hello folks,
after some google search I found this closed issue here.

The same problem is present in my current project:
<img width="703" alt="Screenshot 2022-12-20 at 12 39 39" src="https://user-images.githubusercontent.com/69720211/208658597-645a7a9a-a647-49c6-9769-a3346f583c8a.png">

I'm currently using 
 _
  "@vueuse/core": "^9.7.0"
"vue": "^3.2.41"
 _
  
Being TS newbie I would be really appreciated for a tip of how to fix it.

**Comment by manuelsidler** [comment]
@hbshvn I had the same issue and found another way in the docs using the spread operator:
```
options.headers = {
  ...options.headers,
  Authorization: `Bearer ${myToken}`,
  }
```
https://vueuse.org/core/useFetch/#intercepting-a-request
