### ISSUE TITLE
Problems using useLocalStorage with pinia and typescript

### ISSUE THREAD

**Issue by StefanGhiban** [vueuse/vueuse#1496]
### Describe the bug

I am not able to get useLocalStorage in pinia with typescript to work.
This is the code that I have inside an auth.ts file: 
<img width="364" alt="image" src="https://user-images.githubusercontent.com/47953165/163531176-6a387227-e4c5-4098-91be-51b21288990f.png">

And this is the error that I am getting: 
<img width="928" alt="image" src="https://user-images.githubusercontent.com/47953165/163531364-1a6c365f-1817-4665-a299-25fa2434050c.png">

I get a different error when a type the ref as follows:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/47953165/163531451-b4e4038c-f74b-4901-982c-32bee8296db9.png">

### Reproduction

-

### System Info

```Shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 103.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.88
    Firefox: 97.0.1
    Safari: 15.4
  npmPackages:
    @vueuse/core: ^8.2.5 => 8.2.5 
    @vueuse/integrations: ^8.2.5 => 8.2.5 
    vue: ^3.2.31 => 3.2.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cadillaclizard** [comment]
Got the same problem, kinda solved it by adding:
![image](https://user-images.githubusercontent.com/6390981/163586819-16e958ac-8028-473c-ab4a-9af7b70d089e.png)
But my linters does not understand it...

**Comment by StefanGhiban** [comment]
Yea, I figured that part out myself too, by importing the type, the error goes away. I dont understand the reason behind this though.

**Comment by okxiaoliang4** [comment]
Can you provide a minimal reproduction demo? I don't have this problem in my project

**Comment by StefanGhiban** [comment]
> Can you provide a minimal reproduction demo? I don't have this problem in my project

I will try to make a repo for this issue after the weekend. I will tag you when I have it. Thanks.

**Comment by wheatjs** [comment]
I also am unable to reproduce this, but just as a note you don't need to wrap `useLocalStorage` in a ref as it is already a ref.

**Comment by StefanGhiban** [comment]
Thanks for the note @wheatjs . Regarding the reproduction repo, I could not reproduce it on a fresh configuration. I will link here the repo where I found the issue, maybe it is something I have that is clashing with pinia and vue use. This is the link to that repo. The issue is in the auth.ts store in the stores folder. After an npm install, everything should work and the error should pop up. Thanks for the help @wheatjs , @okxiaoliang4 .

**Comment by WORMSS** [comment]
Just to put my 2 cents in.. I too was getting this issue.. 
My solution was 

```ts
import { useLocalStorage } from '@vueuse/core';
import { defineStore } from 'pinia';
import type { Ref } from 'vue';

const ls = <T>(id: string, defaultValue: T): Ref<T> => // note the Ref<T> not RemovalRef<T>
  useLocalStorage(id, defaultValue);

export const useFigureStore = defineStore({
  id: 'figure',
  state: () => ({
    sholderWidth: ls('sholderWidth', 20),
    waistWidth: ls('waistWidth', 15),
    hipWidth: ls('hipWidth', 20),
    torsoHeight: ls('torsoHeight', 40),
    headSize: ls('headSize', 20),
    neckDip: ls('neckDip', 2),
    neckLength: ls('neckLength', 2),
    waistPosition: ls('waistPosition', 0.5),
    armPosition: ls('armPosition', 0.1),
  }),
  getters: {},
  actions: {},
});
```

And this worked beautifully for me. 

I didn't do anything special. 

```sh
npm init vue@latest
project-name
typescript yes, pinia yes, eslint yes, prettier yes,

cd project-name
npm i @vueuse/core

and then the TS file above.
```

**Comment by StefanGhiban** [comment]
> Just to put my 2 cents in.. I too was getting this issue.. 
> 
> My solution was 
> 
> 
> 
> ```ts
> 
> import { useLocalStorage } from '@vueuse/core';
> 
> import { defineStore } from 'pinia';
> 
> import type { Ref } from 'vue';
> 
> 
> 
> const ls = <T>(id: string, defaultValue: T): Ref<T> => // note the Ref<T> not RemovalRef<T>
> 
>   useLocalStorage(id, defaultValue);
> 
> 
> 
> export const useFigureStore = defineStore({
> 
>   id: 'figure',
> 
>   state: () => ({
> 
>     sholderWidth: ls('sholderWidth', 20),
> 
>     waistWidth: ls('waistWidth', 15),
> 
>     hipWidth: ls('hipWidth', 20),
> 
>     torsoHeight: ls('torsoHeight', 40),
> 
>     headSize: ls('headSize', 20),
> 
>     neckDip: ls('neckDip', 2),
> 
>     neckLength: ls('neckLength', 2),
> 
>     waistPosition: ls('waistPosition', 0.5),
> 
>     armPosition: ls('armPosition', 0.1),
> 
>   }),
> 
>   getters: {},
> 
>   actions: {},
> 
> });
> 
> ```
> 
> 
> 
> And this worked beautifully for me. 
> 
> 
> 
> I didn't do anything special. 
> 
> 
> 
> ```sh
> 
> npm init vue@latest
> 
> project-name
> 
> typescript yes, pinia yes, eslint yes, prettier yes,
> 
> 
> 
> cd project-name
> 
> npm i @vueuse/core
> 
> 
> 
> and then the TS file above.
> 
> ```

Hi! I have managed to solve this issues as well by importing a type from vue use. But I thought maybe I would find a better solution here. Thank for you opinion! @WORMSS .

**Comment by StefanGhiban** [comment]
> Does this mean the problem is fixed? or you are just closing to ignore it?

It's somewhat fixed that I have found a tweak, but I have opened a new one by mistake and left that as it is newer and maybe will get more responses there. I also saw that I forgot to add a reproduction url here so I will add a reproduction repo over that issue.
