### ISSUE TITLE
syncRefComputed

### ISSUE THREAD

**Issue by envatic** [vueuse/vueuse#1499]
### Clear and concise description of the problem

SyncRef for its part simply syncs the value of two refs Making ref B == Ref A and vice-versa as specified.  sometimes we are faced with situations where there is logic determining the relationship between the value of A and B, eg a translation Ui with two inputs and a user can type any language in any of the two inputs and geta transaltion in the other, But for now lets take an example of two currencies
````
cont btc = ref(0);
const usd = ref(0):
const rate = 40000;
syncRefs(usd,btc,{});
//there is no way to add the logic betwen the two currencies
// we need to able to sync these refs with logic between them. so that changing one modifies the other , a simple modification to syncrefs could actually work
````

### Suggested solution

We could simply modify  [https://github.com/vueuse/vueuse/blob/main/packages/shared/syncRef/index.ts](url) to accomodate a case where we need to control the relation of the refs.
````
import type { Ref } from 'vue-demi'
import { watch } from 'vue-demi'
import type { ConfigurableFlushSync } from '../utils'

export interface SyncRefComputedOptions extends ConfigurableFlushSync {
  /**
   * Watch deeply
   *
   * @default false
   */
  deep?: boolean
  /**
   * Sync values immediately
   *
   * @default true
   */
  immediate?: boolean

  /**
   * ltr
   *
   * @default true
   */
   ltr?: boolean|Function

  /**
   * rtl
   *
   * @default true
   */
   rtl?: boolean|Function

}

/**
 * Two-way refs synchronization.
 *
 * @param left
 * @param right
 */
export function syncRefComputed<R extends Ref<any>>(left: R, right: R, options: SyncRefComputedOptions = {}) {
  const {
    flush = 'sync',
    deep = false,
    immediate = true,
    ltr = true,
    rtl = true,
  } = options

  let stop1: Function, stop2: Function

  if (ltr) {
    stop1 = watch(
      left,
      async newValue => ltr instanceof Function? right.value = await ltr(newValue):right.value = newValue,
      { flush, deep, immediate },
    )
  }

  if (rtl) {
    stop2 = watch(
      right,
      async newValue => rtl instanceof Function?left.value = await rtl(newValue):left.value = newValue,
      { flush, deep, immediate },
    )
  }

  return () => {
    stop1?.()
    stop2?.()
  }
}

````

in this case the  the example above could be called
as 
````
cont btc = ref(0);
const usd = ref(0):
const rate = 40000;
syncRefComputed(usd,btc,{
  ltr:(usd)=>rate*usd,
  rtl:(btc)=>btc/rate,
});
````

### Alternative

I think we we could use computed values with getters and setters, Although this suffers from the effect of a mutation loop when one value is adjusted

### Additional context

since the function accepts booleans for ltr, and rtl, the same function can server as syncRefs  and in that case to set the direction as both, ltr and rtl must both be true
````
\\ direction = ltr;
syncRefComputed(usd,btc,{
  ltr:true,
  rtl:false,
});
````
is still valid

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Make sense, we could add options to `syncRef` directly
