### ISSUE TITLE
feat(watchPromise): watch callback with async

### ISSUE THREAD

**Issue by xizher** [vueuse/vueuse#1501]
### Clear and concise description of the problem

sth. liks this:
```js
watch(xxx, async () => {
  await awaitFn()
})
```
if the callback toggles twice and the first one takes longer to execute than the second one, it will overwrite the sceond callback's result.

### Suggested solution

how to solve it?
it can?
```typescript

function watchPromise(...args: Parameters<typeof watch>) {
  const [source, cb, options] = args
  let promiseLink : Promise<unknown> = Promise.resolve()
  watch(source, (..._args) => {
    promiseLink = promiseLink.then(() => cb(..._args))
  }, options)
}

watchPromise(xxx, async () => {
  await awaitFn()
})
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chaii3** [comment]
Any progress ?
