### ISSUE TITLE
`useLocalStorage` should sync with localStorage

### ISSUE THREAD

**Issue by jd-solanki** [vueuse/vueuse#1504]
### Clear and concise description of the problem

I am using the card code component which lets you change the code language `ts` or `js`. I use `useLocalStorage` in my card component to get and set language to show in the card.

However, If I change the language from one card then it doesn't get reflected in other cards until I refresh or come back from another route.

[Playground](https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDgBdZhGOgGM1oUAAQTAYEmC3QoFSuoMEFSRAAPFRsgAdcwqeCSKgAXkzIAAfjUohQOKxIrmIGAKAAWYvZlQqMBJ7hFkAzdU2aQUbi9+rBWjIAd9xAcZs53Rd8TWGzT1u1dVdvDyVhLlQAPhbKlTUsqoOGu5zqd09SgSeQyC7pTqNHq944j4obCCoOfr7zEBCjbJZJJBQABsTYgCoJ57geR4QaeqbDBmxDbs8YrSEQdC6nU0jajBRhVngKjFpMwyHi+MbkNOLLMKRVDkTw8a0O2yZnOm2QqFeEA3l2Rghps5aIJsA6ysWp6tuelLbjRKgACrBCG8G6BJUFgJJrA0CoRQQNg8CkAgiBoCowDAG21hGJOjwyjQmnabpSAqAcBzwSpUGIex163sWPECbW9aCQ2Kh4P2YGia2+6lAECTmBxXHFqU8AUBsdDwKwFDEgB8QCf2kS6CObYUM0Vb8DQVAUAY8DFio5xXnQsBdmApnmSClmINZOl6QWADk0jIB1InSSEYCIACqHweF-TyCFYljZFbmcR5IBxQltJJSlaWAakmxZTlqR5QV7C0iCpXleBVVBLVxb1YgZkcBZaktVpbVIJ1+y9SA24AFIQMQEDDZIMijRFE1QQh2RwSDSEoX9aG8BheocNhxl4gCCQVHZBw1PhKgdc6Nw8nUiC9dg2Y9sg2GXddt1WQ9tlpAW-g3MjdR6doHXk41VDNa1NMdYwWPdR19gsg5QA)

### Suggested solution

`useLocalStorage` can accept a arg to allow sync between instances.

### Alternative

None

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by climba03003** [comment]
I am facing the similar issue. The problem should be the `localStorage` do not update instantly or it wait too long to update. I assume it is the problem of using `watchPausable`.

**Comment by gehringf** [comment]
If possible should share the ref in a separate composable in this case (e.g.
```ts
export function usePreferredLanguage() {
  return {
    lang: useStorage('preferredCodeLanguage', 'ts')
  }
}
```

then in your component
```ts
const { lang } = usePreferredLanguage();
```

**Comment by robokozo** [comment]
Ran into this myself today. Glad to see it's already on github!

**Comment by dajpes** [comment]
Do we have a solution for this?

**Comment by jd-solanki** [comment]
👀

**Comment by nolde** [comment]
I have been experiencing this with vue3 as well... if you reload the page, value loads correctly, but never seems to track value until next reload.

**Comment by harmyderoman** [comment]
I'm not sure if this is possible. The problem is in the storage listeners, as it is written in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event), they will not work on the same page, only on different tabs. I think this is done on purpose to avoid an endless loop.

**Comment by nolde** [comment]
@harmyderoman You're correct. I was not aware of that.

Probably would be good to add a disclaimer to the doc. I totally expected it to be fully reactive within the context of the same page. Guess I am out of luck.

**Comment by harmyderoman** [comment]
@nolde don't be upset. Vueuse already has a solution for you. Just use [createGlobalState](https://vueuse.org/shared/createGlobalState/). Like this

```
// store.js
import { createGlobalState, useStorage } from '@vueuse/core'

export const useGlobalState = createGlobalState(
  () => useStorage('vueuse-local-storage', 'initialValue'),
)
```

**Comment by nolde** [comment]
@harmyderoman Ooooh that's interesting. I'll take a look into that! Thanks a lot mate!

**Comment by harmyderoman** [comment]
https://github.com/vueuse/vueuse/issues/1595

**Comment by pionxzh** [comment]
Personally, I do monkey patching on `storage.setItem` and `storage.removeItem`.
**BUT**, you need to do the dedup by yourself to stop the infinity updating.
In the end, I wrote one `useLocalStorage` by myself :/

For people who want to try this method:
> It's definitely not an ideal solution
```js
function hookBefore(target: any, methodName: string, hookFn: Function) {
    const original = target[methodName]
    target[methodName] = function (...args: any[]) {
        hookFn(...args)
        return original.apply(this, args)
    }
}

function tryPatchLocalStorage() {
    // @ts-expect-error mark it as patched
    if (localStorage.setItem.__patched__) return
    // @ts-expect-error mark it as patched
    localStorage.setItem.__patched__ = true

    hookBefore(localStorage, 'setItem', (key: string, newValue: string) => {
        const oldValue = localStorage.getItem(key)
        const event = new StorageEvent('storage', {
            key,
            newValue,
            oldValue,
            storageArea: localStorage,
        })
        nextTick(() => window.dispatchEvent(event))
    })

    hookBefore(localStorage, 'removeItem', (key: string) => {
        const oldValue = localStorage.getItem(key)
        const event = new StorageEvent('storage', {
            key,
            newValue: undefined,
            oldValue,
            storageArea: localStorage,
        })
        nextTick(() => window.dispatchEvent(event))
    })
}
```

**Comment by nolde** [comment]
I think this could be worked around with a normal ref for local usage, and a `useStorage` ref for external syncing, and then use [`syncRef`](https://vueuse.org/shared/syncRef) to keep them synchronised.

This works, if you can use the same ref everywhere, locally.
Here is an example: https://codesandbox.io/s/vueuse-localstorage-sync-ugmbp5
Use the "Open in New Window" button in the browser panel for an actual working app.

**Comment by smallnine9** [comment]
Fixed by https://github.com/vueuse/vueuse/commit/800f74f49197b11ee5691ac8f4061eb2459ad07e
Maybe we can close it.

**Comment by meshbor** [comment]
Seems problem is not solved yet
