### ISSUE TITLE
`useWindowSize` Resize detection on mobile devices

### ISSUE THREAD

**Issue by ryoji-sagara** [vueuse/vueuse#1505]
### Prerequisite :
In index.html
````
<meta name="apple-mobile-web-app-capable" content="yes" />
````
Set and "Add to Home" state.

### Issue
I used useWindowSize for reactive window size detection.
```
import { watch } from 'vue'
import { useWindowSize } from '@vueuse/core'

const { height } = useWindowSize()
watch(height, () => {
  console.log('Change WindowSize!', height.value)
})
```

I used useWindowSize to detect not only the `resize` event, but also the
I think we should add an `orientationchange` event as well, since it is possible to detect changes by binding an `orientationchange` event as well.

I'm not sure I've covered all the features of Vueuse, so if there is another way to do it, I'd appreciate it if you could let me know.

### Reproduction

none

### System Info

```Shell
iPhone safari
```

### Used Package Manager

yarn

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JMaylor** [comment]
Could you combine with `useScreenOrientation`?

e.g.

```js
import { watch } from 'vue'
import { useWindowSize, useScreenOrientation } from '@vueuse/core'

const { height } = useWindowSize()
const { orientation } = useScreenOrientation()
watch([height, orientation], () => {
  if (window) console.log(window.innerHeight)
})
```

**Comment by ryoji-sagara** [comment]
@JMaylor 
Thanks.
In my case, I can use useScreenOrientation and it will be fine.

However, I am concerned that the `height` of useWindowSize does not change reactively when the device is rotated, which may be a bug for development users.

**Comment by CodyBontecou** [comment]
> @JMaylor Thanks. In my case, I can use useScreenOrientation and it will be fine.
> 
> However, I am concerned that the `height` of useWindowSize does not change reactively when the device is rotated, which may be a bug for development users.

I'm running into this.

```js

watch(orientation, () => {
  console.log("width: ", windowWidth.value, "height: ", windowHeight.value);
});

watch(windowWidth, () => {
  console.log(
    "windowWidth: ",
    windowWidth.value,
    "height: ",
    windowHeight.value,
  );
});```

These are outputting different amounts.
