### ISSUE TITLE
axios use POST模式下如何默认不执行。

### ISSUE THREAD

**Issue by huzedong2015** [vueuse/vueuse#1516]
### Clear and concise description of the problem

```javascript
const { execute } = useAxios(url1, { method: "Post" }, instance)
```
这种需要默认不执行，我要怎么解决？

### Suggested solution

const { execute } = useAxios(url1, { method: "Post" },  {
  instance,
  immediate: false,
})

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by okxiaoliang4** [comment]
try this
```ts
const { execute } = useAxios(url1, { method: 'POST' }, instance, { immediate: false })
```

**Comment by huzedong2015** [comment]
我看文档上面没有4个参数的。我等下试试哈

**Comment by okxiaoliang4** [comment]
ok

**Comment by huzedong2015** [comment]
确实可以，一般都会自己封装axios处理一些拦截器，token啥的。所以大概率会使用instance，麻烦文档上补充一下吧。这种4个参数的。

**Comment by okxiaoliang4** [comment]
OK，那我先关闭了
