### ISSUE TITLE
Proposal: `useToggle` new options

### ISSUE THREAD

**Issue by okxiaoliang4** [vueuse/vueuse#1517]
### Clear and concise description of the problem

Sometimes we need to toggle `0` or `1`. `useToggle` does not do this very well.

### Suggested solution

```ts
export interface UseToggleOptions<Truly, Falsely> {
  trulyValue?: MaybeRef<Truly>
  falselyValue?: MaybeRef<Falsely>
}

export function useToggle<Truly, Falsely, T = Truly | Falsely>(initialValue: Ref<T>, options?: UseToggleOptions<Truly, Falsely>): (value?: T) => T
export function useToggle<Truly = true, Falsely = false, T = Truly | Falsely>(initialValue?: T, options?: UseToggleOptions<Truly, Falsely>): [Ref<T>, (value?: T) => T]

/**
 * A boolean ref with a toggler
 *
 * @see https://vueuse.org/useToggle
 * @param [initialValue=false]
 */
export function useToggle(initialValue: MaybeRef<unknown> = false, options: UseToggleOptions<true, false> = {}) {
  const {
    trulyValue = true,
    falselyValue = false,
  } = options

  const valueIsRef = isRef(initialValue)
  const innerValue = ref(initialValue) as Ref<boolean>

  function toggle(value?: boolean) {
    // has arguments
    if (arguments.length) {
      innerValue.value = value!
      return innerValue.value
    }
    else {
      innerValue.value = innerValue.value === unref(trulyValue) ? unref(falselyValue) : unref(trulyValue)
      return innerValue.value
    }
  }

  if (valueIsRef)
    return toggle
  else
    return [innerValue, toggle]
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Maybe use this https://vueuse.org/core/useCycleList ?

**Comment by okxiaoliang4** [comment]
> Maybe use this https://vueuse.org/core/useCycleList ?

I think `useToggle` is more appropriate.

we can reduce judgment conditions like this
https://github.com/vueuse/vueuse/blob/af3e87785760477aff294c4dd9230dec91bfa2af/packages/shared/useToggle/demo.vue#L1-L20

```vue
<script lang="ts">
const [value, toggle] = useToggle('ON', {
  trulyValue: 'ON',
  falselyValue: 'OFF',
})

watchEffect(() => {
  request('xxx', {
    body: {
      lightStatus: value
    }
  })
})
</script>

<template>
  value: {{ value }}
</template>
```

**Comment by antfu** [comment]
Sure, pr welcome

**Comment by zojize** [comment]
Perhaps the options fields should be named [truthyValue](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) and [falsyValue](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) as this aligns with the mdn glossary.

**Comment by okxiaoliang4** [comment]
> Perhaps the options fields should be named [truthyValue](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) and [falsyValue](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) as this aligns with the mdn glossary.

ok
