### ISSUE TITLE
Calculate `itemHeight` for `useVirtualList` from item properties

### ISSUE THREAD

**Issue by equt** [vueuse/vueuse#1521]
### Clear and concise description of the problem

The [current `useVirtualList`](https://github.com/vueuse/vueuse/blob/main/packages/core/useVirtualList/index.ts) requires `itemHeight` to be provided as a constant, or as a function accepting an index. This proposal suggests extending the function to allow the `itemHeight` to be calculated according to the item itself, not only the index, making the `itemHeight` more usable & reasonable. I'll later try to submit a PR.

### Suggested solution

In the current `useVirtualList` function, instead of having the the `itemHeight` like

```ts
{
  itemHeight: number | ((index: number) => number),

  // ...
}
```

we could have something like

```ts
{
  itemHeight: number | ((item: T, index: number) => number),

  // ...
}
```

or if we might worry about the breaking change

```ts
{
  itemHeight: number | ((index: number, item: T) => number),

  // ...
}
```

which is slightly unintuitive in the JS world.

### Alternative

Even if the item height could be calculated against itself, this should still be considered static, i.e., the function has to be idempotent. Another solution is to wrap around items to allow dynamic content, which is more general but complicated.

### Additional context

Might be related issues / PRs

- https://github.com/vueuse/vueuse/issues/1017
- https://github.com/vueuse/vueuse/issues/954

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by equt** [comment]
Wait, i miss the part that item could be indexed. Closed since not necessary anymore.

**Comment by danCMedicus** [comment]
Did this feature ever get added? ie a list with items of variable height?
