### ISSUE TITLE
Docs: Filter by "most used" or "most liked"

### ISSUE THREAD

**Issue by dosstx** [vueuse/vueuse#1528]
### Clear and concise description of the problem

As a developer using VueUse, I want to see a sorted list of the top used VueUse packages. There are so many functions available  and it would be nice to know which functions are top-rated/most-used. 

### Suggested solution

Have a sorting filter on the VueUse website to show what functions are "most-used" or "most liked", etc. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I have no idea how we could collect the data of "used" and "liked"
