### ISSUE TITLE
Correct useObservable type signature and provide means of creating a non-undefined Ref

### ISSUE THREAD

**Issue by scvnc** [vueuse/vueuse#1544]
### Clear and concise description of the problem

Current behavior: `useObservable` has a return type signature of `Ref<H>` when in practice it returns `Ref<H | undefined>` because there exists a moment where the ref could contain `undefined` since the observable may not have emitted yet.

### Suggested solution

1. Correct the return type signature
2. Provide a way to allow the composable to always return `Ref<H>` by providing an `initialValue`

### Alternative

At a minimum, the type signature should be corrected such that it returns a `Ref<H | undefined>` because in practice it *does* return `Ref<H | undefined>` when the Observable has not emitted.

### Additional context

https://github.com/vueuse/vueuse/discussions/1416

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by scvnc** [comment]
[Draft PR](https://github.com/scvnc/vueuse/commit/69b6f3091d2dfe0fc5514803b1ebabb4d7372813) - Includes demonstrative unit tests.

I'm still stewing on it a little.

**Comment by okxiaoliang4** [comment]
merged
