### ISSUE TITLE
get user's device info like operational system, platform, browser

### ISSUE THREAD

**Issue by maico910** [vueuse/vueuse#1570]
### Clear and concise description of the problem

Function to get user device info like browser user agent, platform, etc

### Suggested solution

Maybe can create soluction like this one? [Quasar Platform Detection](https://quasar.dev/options/platform-detection#introduction)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by webfansplz** [comment]
Any case it needs to be Vue specific ?  If not I would recommend directly use [ua-parser-js](https://github.com/faisalman/ua-parser-js) instead.

**Comment by tobiasdiez** [comment]
Mr stale, this feature is still missing ;-)

**Comment by maico910** [comment]
> Any case it needs to be Vue specific ? If not I would recommend directly use [ua-parser-js](https://github.com/faisalman/ua-parser-js) instead.

@webfansplz sorry, I forgot to answer, in my case it's not necessary to be Vue, so ua-parser-js is useful for me, thanks for the reply!

**Comment by maico910** [comment]
@tobiasdiez do you need this feature?

**Comment by tobiasdiez** [comment]
I guess ua-parser-js indeed fits the bill. How does it through work with ssr?

**Comment by maico910** [comment]
@tobiasdiez I don't know about this, maybe is better you check it on the repo? 

I will close this issue because I get my solution, if you need something else is better you create another issue, thanks
