### ISSUE TITLE
can not start production build of nuxt 3

### ISSUE THREAD

**Issue by mihail727** [vueuse/vueuse#1576]
### Describe the bug

can not start production build of nuxt 3....
in dev mode all works fine
Nuxt: `Nuxt CLI v3.0.0-rc.2-27530889.9e5a3cd`
@VueUse/Nuxt: `8.4.2`

error: ![](https://i.imgur.com/8PghOaf.png)

### Reproduction

I can’t provide a reproduction because you can’t start production mode there

### System Info

```Shell
System:
    OS: Linux 5.17 Fedora Linux 35 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Memory: 10.91 GB / 15.59 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
  npmPackages:
    @vueuse/nuxt: ^8.4.2 => 8.4.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by webfansplz** [comment]
Seems not be `Vueuse`‘s issue, it's work fine in my probject.

I cloned [vitesse-nuxt3](https://github.com/antfu/vitesse-nuxt3.git) and upgrade `@vueuse/nuxt` to `8.4.2` , it's also work fine.

**Comment by mihail727** [comment]
> Seems not be `Vueuse`‘s issue, it's work fine in my probject.
> 
> I cloned [vitesse-nuxt3](https://github.com/antfu/vitesse-nuxt3.git) and upgrade `@vueuse/nuxt` to `8.4.2` , it's also work fine.

yeah ... u right my bad ... seems like problem with nuxt 3
