### ISSUE TITLE
I can't get the real breakpoint immediately

### ISSUE THREAD

**Issue by ByeWord** [vueuse/vueuse#1596]
### Describe the bug

```javascript
const breakpoints = useBreakpoints(breakpointsAntDesign)
const resizeHandler = () => {
  console.log(unref(breakpoints.smaller("md")))
  mediaStore.isMobile = unref(breakpoints.smaller("md"))
}
useEventListener(window, 'resize', resizeHandler)
// I have to call nextTick to get real breakopint value
nextTick(() => {
  resizeHandler()
})
```

### Reproduction

none

### System Info

```Shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 4.55 GB / 15.86 GB
  Binaries:
    Node: 14.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - E:\npm\npm_global\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.39)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Archetipo95** [comment]
I think that my problem is linked to this issue.
I'm using the code from docs.
```
const breakpoints = useBreakpoints(breakpointsTailwind)
const lg = breakpoints.isGreater("lg")
```
And on the template:
`<span>{{ lg }}</span>`

I'm getting this warning in the console:

```
runtime-core.esm-bundler.js:38 [Vue warn]: Hydration text content mismatch in <span>:
- Client: false
- Server: true 
```

**Comment by xunmi1** [comment]
1. If you use `greater`, `smaller`, `between`, then you don't need to bind the `resize` event, the return value is a `ref`.
```js
const breakpoints = useBreakpoints(breakpointsAntDesign);
const isMobile = breakpoints.smaller('md');
watchEffect(() => (mediaStore.isMobile = isMobile));
```
2. The issue is that the initial value of ` useMediaQuery` is `false`, and `tryOnBeforeMount` can't be safely executed in some cases.

**Comment by ideafm** [comment]
Any result to avoid hydration mismatch?
