### ISSUE TITLE
`useFetch` ignores `fetch` option

### ISSUE THREAD

**Issue by Kylyi** [vueuse/vueuse#1602]
### Describe the bug

`useFetch` does not take some (tried only `fetch`) options into account.

This doesn't work:
```typescript
import _fetch from 'cross-fetch'

const { data } = await useFetch('https://httpbin.org/get', { fetch: _fetch }).get().json() // _fetch is not taken into account
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-z5eyel?file=src/App.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
    Memory: 4.54 GB / 15.87 GB
  Binaries:
    Node: 18.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^8.4.2 => 8.4.2
    vue: ^3.2.33 => 3.2.33
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Grawl** [comment]
Just got "Headers is not defined" with 'cross-fetch'.

'isomorphic-fetch' is working for me.
