### ISSUE TITLE
useAxios: awaitable execute function

### ISSUE THREAD

**Issue by blooddrunk** [vueuse/vueuse#1607]
### Clear and concise description of the problem

currently, only the result of  `useAxios` is a promise-like object, it would help if the `execute` function also return the promise result of  `axios` .

### Suggested solution

I've seen it's mentioned here https://github.com/vueuse/vueuse/issues/1368#issuecomment-1059918145, hopefully it will be implemented.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Eating-Eating** [comment]
need a pr?I guess I can do this,need to implement a promisify return in `execute` like what `useFetch` do.
