### ISSUE TITLE
useStorage does not work in HTML files

### ISSUE THREAD

**Issue by oldshensheep** [vueuse/vueuse#1611]
### Describe the bug

No persistence

### Reproduction

https://github.com/oldshensheep/toyweb/blob/main/demo.html

https://blog.oldshensheep.com/toyweb/demo.html

### System Info

```Shell
unnecessary
```

### Used Package Manager

No.  Just HTML files

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by syy11cn** [comment]
@oldshensheep You just need to add a `script` tag before `@vueuse/core`, importing the `@vueuse/shared` package. It will register a method called `pausableWatch` on `VueUse` obj, which is depended by `useStorage`.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/57290456/169435984-139873bd-1f3c-44ec-b4f9-7b3af8f93004.png">

Here is the demo link: https://codesandbox.io/s/usestorage-does-not-work-in-html-files-1611-ci526c?file=/index.html .

**Comment by oldshensheep** [comment]
@syy11cn  thanks, now it works.
