### ISSUE TITLE
useStorage appear in Cookies

### ISSUE THREAD

**Issue by sikeat7** [vueuse/vueuse#1616]
### Describe the bug

I have a problem when using useStorage not set to local storage but it appear in cookies.

`useStorage("test", 123123);`

<img width="1048" alt="Screen Shot 2022-05-19 at 7 23 59 PM" src="https://user-images.githubusercontent.com/12691222/169293078-f089a85c-5272-4aa4-ac44-de577fa0cc59.png">

### Reproduction

localhost

### System Info

```Shell
System:
    OS: macOS 11.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 393.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 15.3
  npmPackages:
    @vueuse/core: ^8.5.0 => 8.5.0 
    @vueuse/nuxt: ^8.5.0 => 8.5.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ablipan** [comment]
I've met the problem too. 

`useStorage` will write value into Cookie. So i changed the code to `useLocalStorage`, it works but will insert an empty record into Cookie.

```
  System:
    OS: macOS 11.6.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 154.86 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Edge: 84.0.522.40
    Firefox: 73.0.1
    Safari: 15.4
  npmPackages:
    @vueuse/components: ^8.2.5 => 8.5.0
    @vueuse/core: ^8.2.5 => 8.5.0
    @vueuse/nuxt: ^8.2.5 => 8.5.0
    vue: ^3.2.0 => 3.2.36
```

**Comment by antfu** [comment]
`useStorage` will use Cookie when you enable `ssrHandlers`. Use `useLocalStorage` if you want to be explict.

**Comment by newbill** [comment]
> I've met the problem too.
> 
> `useStorage` will write value into Cookie. So i changed the code to `useLocalStorage`, it works but will insert an empty record into Cookie.
> 
> ```
>   System:
>     OS: macOS 11.6.5
>     CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
>     Memory: 154.86 MB / 16.00 GB
>     Shell: 5.8 - /bin/zsh
>   Binaries:
>     Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
>     Yarn: 1.22.4 - ~/.yarn/bin/yarn
>     npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
>   Browsers:
>     Chrome: 101.0.4951.54
>     Edge: 84.0.522.40
>     Firefox: 73.0.1
>     Safari: 15.4
>   npmPackages:
>     @vueuse/components: ^8.2.5 => 8.5.0
>     @vueuse/core: ^8.2.5 => 8.5.0
>     @vueuse/nuxt: ^8.2.5 => 8.5.0
>     vue: ^3.2.0 => 3.2.36
> ```

I have met the same problem too. `useLocalStorage` works but will insert an empty record into Cookie. So how to deal with it?
