### ISSUE TITLE
whenever: does not observe the computed value

### ISSUE THREAD

**Issue by Scrum** [vueuse/vueuse#1617]
### Describe the bug

Whenever does not observe the computed value

```js
  const a = ref(null);
  const b = computed(() => a);

  setTimeout(() => {
    a.value = 'test';
    setTimeout(() => {
      a.value = null;
    }, 2000);
  }, 2000);

  whenever(b, () => {
    console.log('whenever', b);
  });
```
### Reproduction

https://vueuse.org/shared/whenever/

### System Info

```Shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 29.98 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome Canary: 104.0.5071.0
    Firefox Developer Edition: 101.0
    Safari: 15.4
    Safari Technology Preview: 15.4
  npmPackages:
    @vueuse/components: 7.5.5 => 7.5.5 
    @vueuse/core: 7.7.0 => 7.7.0 
    @vueuse/integrations: 7.5.4 => 7.5.4 
    @vueuse/router: 7.5.5 => 7.5.5 
    vue: 3.2.33 => 3.2.33
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
You need to access `a`'s value.

```diff
-- const b = computed(() => a);
++ const b = computed(() => a.value);
```

**Comment by Scrum** [comment]
> You need to access `a`'s value.
> 
> ```diff
> -- const b = computed(() => a);
> ++ const b = computed(() => a.value);
> ```

Thank you so much buddy you made my day
