### ISSUE TITLE
我想知道useVModel可以用来绑定父组件传入的数组吗？

### ISSUE THREAD

**Issue by CNlitai** [vueuse/vueuse#1618]
### Clear and concise description of the problem

`
interface Props {
	questionMarkList: number[]
}

const props = withDefaults(defineProps<Props>(), {
	questionMarkList: [],
})
const emits = defineEmits(['update:questionMarkList'])
const _questionMarkList = useVModel(props, 'questionMarkList', emits, { deep: true })

`

### Suggested solution

这样我在子组件中修改_questionMarkList时并没有起作用，我哪里写错了吗？

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by xunmi1** [comment]
1. `defineProps()` -> `defineProps<Props>()`, 或者为 `useVModel` 加上 `defaultValue` 参数
2. `useVModel` 的 `deep: true` 仅在 `passive: true` 模式下有效

**Comment by CNlitai** [comment]
> 1. `defineProps()`-> `defineProps<Props>()`, 或者为`useVModel`附加`defaultValue`参数
> 2. `useVModel`的`deep: true`仅在`passive: true`模式下有效

非常感谢，这部分的内容可以添加在文档中吗？

**Comment by CNlitai** [comment]
我这边有一个新的问题 我有一需要使用deep监听的数据结构 但是在子组件关闭dialog的时候我需要emits这个事件出去 告诉父组件重新组装一下数据（因为子组件内使用useVModel绑定的数据是在父组件内组装好传入的 传入整个数据结构太臃肿， 而且dialog内的内容可能被反复编辑 不保存到数据库中）但是passive: true和这种情况明显冲突了，我除了把父组件的那个复杂结构传入之外还有其他的方法吗？可以支持deep: true passive: false这种情况吗
