### ISSUE TITLE
unplugin-auto-import

### ISSUE THREAD

**Issue by kknono** [vueuse/vueuse#1635]
### Describe the bug

使用unplugin-auto-import 后，生成的auto-imports.d.ts里面报错
  类似于const controlledRef: typeof import('@vueuse/core')['controlledRef']，找不到controlledRef
 AutoImport({
imports:[ '@vueuse/core']
    
})

### Reproduction

no

### System Info

```Shell
使用unplugin-auto-import 后，生成的auto-imports.d.ts里面报错
  类似于const controlledRef: typeof import('@vueuse/core')['controlledRef']，找不到controlledRef
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by kknono** [comment]
sorry, it's already correct. Maybe some conflict  within vetur format and eslint.
thx
