### ISSUE TITLE
Support for missing format string in `useDateFormat()` from `dayjs`

### ISSUE THREAD

**Issue by andrewspy** [vueuse/vueuse#1641]
### Clear and concise description of the problem

It's nice to have some of the missing format string in `useDateFormat()` as per `dayjs` for common use case, such as:

```
MMM | Jan-Dec | The abbreviated month name
MMMM | January-December | The full month name
dd | Su-Sa | The min name of the day of the week
ddd | Sun-Sat | The short name of the day of the week
dddd | Sunday-Saturday | The name of the day of the week
A | AM PM |  
a | am pm
```

Reference: https://day.js.org/docs/en/display/format

Also, with the missing format, we could potentially reduce overall bundle size by not bundling `dayjs` for common formatting use case.

### Suggested solution

Support the proposed missing format string.

### Additional context

https://day.js.org/docs/en/display/format

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by webfansplz** [comment]
Same issue #1478 .

Perhaps you should use `dayjs` directly or fork `useDateFormat` implementation it in your probject if you need it.

**Comment by andrewspy** [comment]
@webfansplz I think a human-readable date format should be included for general UI use case. For date manipulation, I would surely go with `dayjs` instead.

**Comment by webfansplz** [comment]
> @webfansplz I think a human-readable date format should be included for general UI use case. For date manipulation, I would surely go with `dayjs` instead.

These options involves `locale`,Users come from all over the world,and supporting it is too much for a `composable API`.

I feel it's outside the scope of `VueUse` , so I suggestion you add it in your pobject.

**Comment by andrewspy** [comment]
There is some misunderstanding here, I don't see how "Jan-Dec", "Sun-Mon" or "am/pm" involve any locale here. It's a purely formatting option as opposed to presenting it as numbers such as 1-12 (month), 0-6 (weekday), and 0-23 (hours in am/pm). it's simply a mapping of objects/arrays.

If you mean translating the date format into another locale/language, I do agree that would certainly be out of scope for `VueUse`.

**Comment by webfansplz** [comment]
> There is some misunderstanding here, I don't see how "Jan-Dec", "Sun-Mon" or "am/pm" involve any locale here. It's a purely formatting option as opposed to presenting it as numbers such as 1-12 (month), 0-6 (weekday), and 0-23 (hours in am/pm). it's simply a mapping of objects/arrays.
> 
> If you mean translating the date format into another locale/language, I do agree that would certainly be out of scope for `VueUse`.

Take  the  `ddd` option as an example:

![image](https://user-images.githubusercontent.com/22515951/173006425-7b7b1c3a-c237-4031-920e-d021679f24be.png)

https://github.com/iamkun/dayjs/blob/fff66d191afb17ebe85c2eb96d95753786f87b3e/src/index.js#L292

Chinese : [https://github.com/iamkun/dayjs/blob/dev/src/locale/en-ca.js#L8](https://github.com/iamkun/dayjs/blob/dev/src/locale/en-ca.js#L8)
![image](https://user-images.githubusercontent.com/22515951/173006464-a6168be5-b5d3-44cb-b13b-1e29f1c0f451.png)

English : [https://github.com/iamkun/dayjs/blob/dev/src/locale/zh-cn.js#L8](https://github.com/iamkun/dayjs/blob/dev/src/locale/zh-cn.js#L8)

![image](https://user-images.githubusercontent.com/22515951/173006487-f4b3d2b5-f9f4-4e56-a953-d28d56ba0584.png)

For other unrelated options to `locale` , PR always welcome.

**Comment by andrewspy** [comment]
@webfansplz I do understand where you are coming from, what I meant was only supporting it as an "international" date for common use case, which means Monday will simply just display as "Mon" regardless of locale (english/chinese).

If a user wishes to have full locale support, they can simply use dayjs instead.
