### ISSUE TITLE
Make `useElementBounding` react to parent container scroll

### ISSUE THREAD

**Issue by ChrisGV04** [vueuse/vueuse#1645]
### Clear and concise description of the problem

I have a sidebar on my app that contains a list of elements in it but the sidebar is fixed, so it doesn't scroll with the window. However, it could happen that that list gets very long, so I need to scroll the elements in the parent, and so the boundaries of each element change when I scroll inside the parent container.

For some reason, the `useElementBounding` composable doesn't update the `x` and `y` refs when I do that. I will try to make an example:
```
<ul class="fixed h-screen overflow-y-auto">
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
  <li>Item 4</li>
  <li>Item 5</li>
  ...
</ul>
```
If I do scrolling inside of that list, the `useElementBounding` composable still returns the initial values, not the ones after performing the scroll.

I've uploaded a video showing my example: [This video](https://youtu.be/Fy-VmSlKJno) shows that the toolbar is appearing at the initial location of the navigation item instead of its position after scrolling.

### Suggested solution

In my case, I am using this for tooltip functionality and I was able to solve it by using a direct ref to the element inside a computed property and then getting the bounding rect:
```
const tooltip = ref<HTMLElement | undefined>();
const wrapper = ref<HTMLElement | undefined>();

const tooltipPosition = computed<HTMLAttributes['style']>(() => {
  if (!wrapper.value || !tooltip.value) return { top: '0', left: '0' };

  const { x: wX, y: wY, width: wW, height: wH } = wrapper.value!.getBoundingClientRect();
  const { height: tH, width: tW } = tooltip.value!.getBoundingClientRect();
  ...
)}
```
The above solution always returned the correct position of the wrapper of the tooltip

### Additional context

[Video where I show what happens](https://youtu.be/Fy-VmSlKJno)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JMaylor** [comment]
`useElementBounding` is currently set up to listen to the target element being resized, and optionally (enabled by default) window scroll and window resize events.

`useElementBounding` does return an `update()` function, which you could invoke manually if there is a custom event listener that you would need to listen to - in your case, scrolling on the parent wrapper. I don't see a link to any reproduction so hopefully the below is adaptable to your use case:

```vue
<script setup>
import { useElementBounding, useScroll } from '@vueuse/core'
import { watch } from 'vue'

// nav is the wrapper element (which is scrollable)
const nav = ref<HTMLElement | null>(null)
// target is the link that is not currently being tracked.
const target = ref<HTMLElement | null>(null)

// useElementBounding composable used as normal
const { x, y, top, right, bottom, left, width, height, update } = useElementBounding(target)

// watch for any changes in the scroll of the wrapper element
const { x: navScrollX, y: navScrollY } = useScroll(nav)
watch([navScrollX, navScrollY], update)
</script>

<template>
  <nav ref="nav">
    <router-link ...>Home</router-link>
    <router-link ...>About</router-link>
    <router-link to="/new" ref="target">New Post</router-link>
    <router-link ...>Settings</router-link>
    <router-link ...>Profile</router-link>
  </nav>
<template>
```

I would do this in play.vueuse.org but I am having [some issue with useScroll there](https://github.com/wheatjs/vueuse-playground/issues/12)

**Comment by ChrisGV04** [comment]
@JMaylor Oh I completely forgot about the update function! I was checking out the source code and I could see what you said, it only listens for element resize and window scroll.

Your proposed solution worked perfectly fine for my Tooltip use case. Thank you very much!
