### ISSUE TITLE
useMagicKeys 在使用某些组合键时不生效

### ISSUE THREAD

**Issue by Zhang-Wei-666** [vueuse/vueuse#1646]
### Describe the bug

比如: 
D_E_L
I_O_L
O_P_L
...

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDgBdZhGOgGM1oUAAQTAYEmC3QoFSuoMEFSRAAPFRsgA+AA65hUUE41nVaBUwGAKhgiBCyGmhZs0hUBwOudTwwzxBz2Bb7ZUxAodCMAF5syBK9WMAByNQUACiFCKE79I87KnUM6KLbbWdz3eyvf7Q5HY+Qk4A8hQAArzxfL3Or08XjfYVvtzPPMXSIh0XV1BvlvEALIIHQUAANJVs4Bw1BwswqBOzo3DydSIBOubfnqHANjKdQZrgqTQbBE6TMM2EcLhyaIDG5CoV2tjyMgDbHiog7+DcQHwCB4HVtowB3io1jQLIHgltIHDkLmBz2AA3CyzCkeRqRUTw8a0GASYprw6bZHxtTqsOIB4PIrAjnxpTwPpQTwH0FDEmSZJuJUMBoFQjk2XZJl5kYIabPpAB++ayh5q6pJs0j6dw6qIBwQUqGA+mNDFpQ4VF+kwfwNBUB5K4qKmyCQOYIVhSOAAsmwGMuZa9oYqhNq2eUQNg2W5fl8SIKF+nIHgDkcE5lnWQAnHZ3VOd40DBCEbkjioeD6dIFAJSAmYAewkKVUmpSeI2Bx1flnYvlm76SDIX4-phpZuIgQbYIgF4wYMjYEV1E4LDRuY0FdN13cgPF8etnglgCom+IwfHENViAlgAcqQeAbRwIPYJJLJNkAA

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz  
    Memory: 3.77 GB / 15.87 GB
  Binaries:
    Node: 16.13.2 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by okxiaoliang4** [comment]
我试了是可以的喔

![image](https://user-images.githubusercontent.com/22525904/170944828-84be7654-5cae-4b64-88df-81ffd1bab0f4.png)

**Comment by Zhang-Wei-666** [comment]
> 我试了是可以的喔
> 
> ![图片](https://user-images.githubusercontent.com/22525904/170944828-84be7654-5cae-4b64-88df-81ffd1bab0f4.png)

这 ....
那看来是我的问题
