### ISSUE TITLE
feat(useSortable): Sortable JS integration

### ISSUE THREAD

**Issue by parafeu** [vueuse/vueuse#1648]
### Clear and concise description of the problem

I am using VueUse for a big SPA in my company. I was using [https://github.com/SortableJS/Vue.Draggable](url) for my Vue 2 projects and tried to use it too on this Vue 3 project. 

Unfortunately, the project looks abandoned and seems to support only the Option API.

I'm opening this issue to share with you the solution I coded and discuss if this feature is desired. 

### Suggested solution

So I coded a composable based on the SortableJS library. Here it is : 

```ts
import { MaybeElementRef, MaybeRef } from "@vueuse/core";
import SortableJS from 'sortablejs';
import { Ref } from "vue";

export function useSortable<T extends Record<string, unknown>>(
    el: MaybeElementRef, 
    vmodel: Ref<T[]>,
    options?: MaybeRef<SortableJS.SortableOptions>
) {
    const instance = ref<SortableJS>();
    const internalVmodel = toReactive(vmodel);

    function onMove(event: SortableJS.MoveEvent) {
        const _options = unref(options);
        return _options?.onMove ? _options.onMove.call(event, event, event) : true &&  event.related.dataset.sortableFooter === undefined;
    }

    function onEnd(event: SortableJS.SortableEvent) {
        const _options = unref(options);
        if(_options?.onEnd)
            _options.onEnd.call(event, event);

        if(event.newDraggableIndex !== undefined && event.oldDraggableIndex !== undefined) {
            [internalVmodel[event.oldDraggableIndex], internalVmodel[event.newDraggableIndex]] = [internalVmodel[event.newDraggableIndex], internalVmodel[event.oldDraggableIndex]];
        }
    }

    function init() {
        if(instance.value)
            instance.value.destroy();

        const _el = unrefElement(el);
        const _options = unref(options);

        if(_el instanceof HTMLElement) {
            instance.value = new SortableJS(_el, {
                ...(_options ?? {}),
                filter: "[data-sortable-footer]",
                onMove,
                onEnd
            });
        }
    }

    const stopWatch = [
        watch(() => unref(el), init),
        watch(() => unref(options), init)
    ];

    tryOnBeforeUnmount(() => stopWatch.forEach(watch => watch()));

    return instance;
}
```

As you can see, it's really scoped for my project, and probablyneed some changes to be more universal

### Additional context

This is my first issue here, so feel free to correct me if I made mistakes. (And english is not my native language, so I probably made some grammatical errors)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by parafeu** [comment]
I am just following contribution guide

`Before you start working, it's better to open an issue to discuss first.`

**Comment by messenjer** [comment]
Hello,

I face the same problem when migrating a project from vue2 to vue3. 

This is something missing in the vue ecosystem, a composable library that wraps around Sortable.js

Why not use <other library>?

- Vue.Draggable only supports Vue 2
- vue.draggable.next uses the Options API, has multiple open pull requests, and had weird bugs/side-effects when we tried and used it
- shopify/draggable and [vue-shopify-dragable](https://github.com/zjffun/vue-shopify-draggable) seemed promising but they don't supported nested components
- https://github.com/MaxLeiter/sortablejs-vue3 - it could be a source of inspiration, a smaller solution as close to Sortable as possible

Can we start to work on it?

Regards

Mathieu

**Comment by messenjer** [comment]
Ok, there is already work in progress for this feature: https://github.com/vueuse/vueuse/issues/2766

**Comment by Alfred-Skyblue** [comment]
PR #2763
