### ISSUE TITLE
 can not recognized useIntervalFn

### ISSUE THREAD

**Issue by yzj-again** [vueuse/vueuse#1650]
### Describe the bug

when I use useIntervalFn from @vueuse/core in my vue project，but now, my IDE says "cannot resolve symbol 'useIntervalFn'" and it is red as on image below.
![Snipaste_2022-05-31_01-22-59](https://user-images.githubusercontent.com/28704447/171038093-da4b1e4e-da72-443b-8546-2287d9b688c0.png)
At the same time，when I check`node_modules`，it looks very strange,and It does not jump to where the function is declared.

![Snipaste_2022-05-31_01-18-55](https://user-images.githubusercontent.com/28704447/171038343-c7b901a9-1934-4cc3-be2f-d2b0e208e6d3.png)
I tried to reinstall packages, nothing helped. 
I use `npm i @vueuse/core` to install it.
App still compiles without problems.

### Reproduction

null

### System Info

```Shell
IDE: WebStorm 2022,
OS: Win 10,
"@vueuse/core": "^8.5.0",
"vue": "^3.2.13",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzj-again** [comment]
It seems that this problem has no impact on the program

**Comment by jodyhoonstarr** [comment]
I believe this is the workaround for intellij editors and vueuse: https://github.com/vueuse/vueuse/issues/896#issuecomment-1190359361

**Comment by antfu** [comment]
Duplicated #896
