### ISSUE TITLE
Bug using useLocalStorage in pinia store

### ISSUE THREAD

**Issue by StefanGhiban** [vueuse/vueuse#1667]
### Describe the bug

I am trying to use the useLocalStorage composable in a Pinia store, but I get a typescript error out of it.
This is the store.
<img width="329" alt="Screenshot 2022-06-06 at 11 34 30" src="https://user-images.githubusercontent.com/47953165/172126379-913d6d0b-3dac-4ea7-9baa-6415a319d2de.png">

And this is the error that I am geeting.
<img width="889" alt="Screenshot 2022-06-06 at 11 35 38" src="https://user-images.githubusercontent.com/47953165/172126702-988a3c9f-85f8-4f5f-870a-e37cb14cfdfe.png">

If I type the state, the error goes away, but the thing is, if I remove useLocalStorage and have a normal state object, the error does not show up.

I could not reproduce this on a fresh repo so I have linked the repo where I have encountered the error. If you clone and run npm install then you install the required extensions so that vs code will understand the code, you will see in the stores folder to ts files that have that error. If I use removable ref to type each variable, the errors goes await, but it doesnt make sense to me to be this way.

### Reproduction

https://github.com/genuineq/template-frontend

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 1.04 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    @vueuse/core: ^8.2.5 => 8.2.5 
    @vueuse/integrations: ^8.2.5 => 8.2.5 
    vue: ^3.2.31 => 3.2.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by thijsw** [comment]
Same as #1496 ?

**Comment by StefanGhiban** [comment]
> Same as #1496 ?

Yea, just a better explanation this time.
