### ISSUE TITLE
usePanToScroll

### ISSUE THREAD

**Issue by emersonbottero** [vueuse/vueuse#1681]
### Clear and concise description of the problem

scroll grabbing  the background of any overflowed element with scroll.

### Suggested solution

use directive to add the feature to an html element

- the point change to grab onmousedown
- you can drag in both direction to scroll horizontally and vertically
- the point change to standard after onmouseup

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by stefnotch** [comment]
So, the feature request is to add a scrolling mechanism that works like it does on mobile:
Mouse down on the background, then drag it, and the page ends up scrolling.

**Comment by emersonbottero** [comment]
yes! I did a dynamic tree chart and it can get really big.. 
pan is more user friendly is those cases

**Comment by wheatjs** [comment]
PR here #2733
