### ISSUE TITLE
useEdgeResizer

### ISSUE THREAD

**Issue by emersonbottero** [vueuse/vueuse#1682]
### Clear and concise description of the problem

I want an entire edge of an element to be draggable and while dragging it resize the element

### Suggested solution

add an directive to add resize on drag.

- we can pass the edge to be sizeable (top, down, left, right)
- on mouse over change the pointer to col-resize, row-resize
- while grabbing the element is resized and the point change to grab

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
Have you seen https://github.com/vueuse/vueuse/pull/708? Seems to cover this, hopefully we can get this PR merged soon
