### ISSUE TITLE
useThrottleFn 快速点击会触发两次

### ISSUE THREAD

**Issue by Mascot1** [vueuse/vueuse#1684]
### Describe the bug

如果在设定时间内，快速点击多次，useThrottleFn 内的方法会触发两次，第一次在点击的时候触发，第二次触发是在 useThrottleFn 定时结束后触发。不知是原先就如此设计，还是因为 bug。如果设计如此是否有违 throttle 方法在短时间内只触发一次的原则。希望官方可以给个解答。

### Reproduction

https://github.com/vueuse/vueuse/blob/main/packages/shared/useThrottleFn/demo.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 7.20 GB / 15.92 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.33)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^5.3.0 => 5.3.0
    vue: ^3.2.33 => 3.2.33
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by webfansplz** [comment]
`useThrottleFn`提供了`trailing`参数用于在时间结束后再次调用fn. 

现在`trailing`默认是启用的,我个人也认为这不太符合节流函数的设计.我将提`PR`讨论这个问题,因为这将造成破坏性改动,我想我们可能需要讨论权衡.

可以先将`trailing`参数设置为`false`来避免: 

```ts
const throttledFn = useThrottleFn(() => {
  updated.value += 1
}, 1000,false)

```

**Comment by Mascot1** [comment]
> `useThrottleFn`提供了`trailing`参数用于在时间结束后再次调用fn.
> 
> 现在`trailing`默认是启用的,我个人也认为这不太符合节流函数的设计.我将提`PR`讨论这个问题,因为这将造成破坏性改动,我想我们可能需要讨论权衡.
> 
> 可以先将`trailing`参数设置为`false`来避免:
> 
> ```ts
> const throttledFn = useThrottleFn(() => {
>   updated.value += 1
> }, 1000,false)
> ```

谢谢你的回答

**Comment by t-shangwei** [comment]
為什麼要跟慣例唱反調 😭 
從 jQuery 時代自家實作 -> underscore -> lodash -> react 的 useHook 的 default trailing 都是 true

**Comment by ilyaliao** [comment]
> 為什麼要跟慣例唱反調 😭 從 jQuery 時代自家實作 -> underscore -> lodash -> react 的 useHook 的 default trailing 都是 true

在 PR 中有提到，是歡迎改回 `true` 的，不過距離當時已經有一段時間，或許許多用戶已經習慣這個改變。

如果你願意的話，可以在討論串中收集大家對此的看法！
