### ISSUE TITLE
can not use screen orientation

### ISSUE THREAD

**Issue by hamedg68** [vueuse/vueuse#1686]
### Describe the bug

I use vuejs + vite and when I use screen orientaion I get this error in browser

SyntaxError: The requested module '/node_modules/.vite/deps/@vueuse_core.js?v=3f804fbc' does not provide an export named 'useScreenOrientation' 

### Reproduction

https://vueuse.org/core/usescreenorientation/#demo

### System Info

```Shell
Browsers
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by murongg** [comment]
I created a new project to try this function, but I didn't find any problems! Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by hamedg68** [comment]
> I created a new project to try this function, but I didn't find any problems! Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

I found the problem. remove node-modules and install again
