### ISSUE TITLE
useToggle/useDebounceFn not found

### ISSUE THREAD

**Issue by theolavaux** [vueuse/vueuse#1688]
### Describe the bug

I have a Nuxt 2 project where I'm trying to use the vueuse library.
It runs fine when I install my dependencies normally, but after doing `pnpm i --frozen-lockfile`, I get those two errors at the lint stage in my CI.

You can reproduce with the link provided and just run `pnpm lint`.

`useDebounceFn` not found in `'@vueuse/core'` eslint [import/named](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/named.md)
`useToggle` not found in `'@vueuse/core` eslint [import/named](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/named.md)

### Reproduction

https://stackblitz.com/edit/nuxt-typescript-starter-fhvkaw?file=pages/index.vue

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 26.33 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.12.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 98.1.35.101
    Chrome: 102.0.5005.115
    Firefox Developer Edition: 102.0
    Safari: 15.1
  npmPackages:
    @vueuse/core: 8.6.0 => 8.6.0 
    @vueuse/nuxt: 8.6.0 => 8.6.0 
    vue: 2.6.14 => 2.6.14
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by theolavaux** [comment]
I managed to debug the issue, these functions live in `@vueuse/shared` and not `@vueuse/core` anymore, just by installing the package and updating my dependencies I was able to get rid of the error. Is the doc not up to date?

**Comment by calebwaldner** [comment]
I found the same issue. I had to import from `@vueuse/shared` rather than `@vueuse/core`.
