### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by Mistrain-y-y** [vueuse/vueuse#1689]
### Describe the bug

服务端渲染，引入 index.cjs， 其中有一个 instanceof Headers 的判断， 会报错。 Headers 只有在浏览器端才有。
function headersToObject(headers) {
  if (headers instanceof **Headers**)
    return Object.fromEntries([...headers.entries()]);
  return headers;
}

### Reproduction

null

### System Info

```Shell
latest package
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Fixed in 8f541b0aced9168e88201e268b253d7c5a42747b
