### ISSUE TITLE
#1657 breaks `unrefElement(exposedComponent)`

### ISSUE THREAD

**Issue by CarterLi** [vueuse/vueuse#1702]
### Describe the bug

[exposed component](https://github.com/vuejs/core/blob/9734b31c312244a2b5c5cf83c75d7b34076a0c4b/packages/runtime-core/src/component.ts#L938) is a proxy object which only contains exposed properties.  [You can get values of public properties like`$el`](https://github.com/vuejs/core/blob/9734b31c312244a2b5c5cf83c75d7b34076a0c4b/packages/runtime-core/src/component.ts#L942) but [testing their existence](https://github.com/vueuse/vueuse/pull/1657/files#diff-bb3ba900e16f30e9d1330cd380fc0d6388b0931d7759d8d3ec1b8f902dc00c25R19) will fail if users didn't expose them manually.

> '$el' in (plain as VueInstance)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-amsrj4/

### System Info

```Shell
With minimal reproduction is provided, this section is meaningless
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CarterLi** [comment]
Ref: https://github.com/element-plus/element-plus/pull/8338#issuecomment-1159404310

@DrJume Ideas?

**Comment by DrJume** [comment]
I'm sorry for causing this trouble! This issue seems to happen only with Vue components which use `expose`/`defineExpose` and don't expose a custom `$el` property.

It's very likely to be caused by a bug in Vue.js:
- https://github.com/vuejs/core/issues/6137

**Comment by DrJume** [comment]
Thank you for your insight! I submitted a PR in `vuejs/core` to fix the underlying? issue. 

- https://github.com/vuejs/core/pull/6138
