### ISSUE TITLE
useWebSocket: WebSocket initial status

### ISSUE THREAD

**Issue by apm29** [vueuse/vueuse#1726]
### Describe the bug

# useWebSocket
when `immediate` is set to be `false`, the status init value is `'CONNECTING'`,  it should be `'CLOSED'` or something else like `'INITIAL'`,`'CREATED'`...

### Reproduction

https://stackblitz.com/edit/vitejs-vite-sjcwba?file=src/App.vue

### System Info

```Shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
    Memory: 805.50 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.19.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Safari: 15.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chaii3** [comment]
What's your suggestion ? Current version is relevant with native statuses. (https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState)
