### ISSUE TITLE
useFetch cannot use formData 

### ISSUE THREAD

**Issue by PoliWen** [vueuse/vueuse#1734]
### Describe the bug
``` javascript
const {
    data,
    onFetchError,
} = await useFetch(url).post(formData, 'formData').json()
```
when I use formData, how can I set multipart/form-data?

The error info is: The body of your POST request is not well-formed multipart/form-data.

### Reproduction

dev

### System Info

```Shell
browsers
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by PoliWen** [comment]
If I use like this,can get the correct answer.
useFetch(action, { method: 'POST', body: formData }).json()

**Comment by PoliWen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件已收到。记得常联系哦

**Comment by abitwhy** [comment]
Workaround: Sets the payload type to `null`.

``` diff
- .post(formData, 'formData')
+ .post(formData, null)
```

**Comment by PoliWen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件已收到。记得常联系哦
