### ISSUE TITLE
New feature: Get microphone level

### ISSUE THREAD

**Issue by themarcba** [vueuse/vueuse#1735]
### Clear and concise description of the problem

As a developer using VueUse, I want to read the audio levels of the microphone, so I can display it in a web application.

### Suggested solution

In the module "sensors", ww could provide an implementation that reads the microphone level data via getUserMedia.
The solution would take care of the browser permissions to access the microphone.

The exposed values would be
- The microphone level indication (e.g. `audioLevel`)
- The browser permission (`isAllowed`)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by themarcba** [comment]
I'd love to implement this 😁

**Comment by antfu** [comment]
This seems to be a bit complex to get right (permission, multiple devices, hot-plug, etc.). I would suggest not being blocked by us but start implementing in your codebase (get the work done first!). And maybe after some iterations, if you feel good about the design, you can share the code and we would discuss if the usage makes sense in VueUse. Thanks :)

**Comment by themarcba** [comment]
Ok Anthony. Now that I actually think of it, the permissions should be an own composable. I will do like you said - show my work when I feel good about it.

**Comment by wheatjs** [comment]
> Ok Anthony. Now that I actually think of it, the permissions should be an own composable. I will do like you said - show my work when I feel good about it.

We do have a composable for permissions if that helps https://vueuse.org/core/usePermission/

**Comment by themarcba** [comment]
Oh how did I miss this? I was searching for microphone and getUserMedia. Anyways this will help a lot.

Thank you @wheatjs 🔥
