### ISSUE TITLE
Image might be loaded before adding listener

### ISSUE THREAD

**Issue by shtse8** [vueuse/vueuse#1737]
### Describe the bug

https://github.com/vueuse/vueuse/blob/ef6cf56cfde1e41cead37ccda48cde68f89ec931/packages/core/useImage/index.ts#L22-L29

we are adding listeners after setting `iamge.src` on the image object.
it might cause the image being loaded and triggered `onloaded` and `onerror` before listening it.

another issue is that, the listeners haven't removed after component unmounted?

### Reproduction

NA

### System Info

```Shell
NA
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by radusuciu** [comment]
This might not be 100% related, but I'm also finding that images are loaded before the component is even rendered. Possibly related: https://github.com/vuejs/vue/issues/1646

**Comment by TwT-L** [comment]
why ?
syntaxError: The requested module '/node_modules/.vite/@vueuse_core.js?v=841ba7da' does not provide an export named 'useImage'
