### ISSUE TITLE
v9.0 Plan

### ISSUE THREAD

**Issue by antfu** [vueuse/vueuse#1744]
Working branch: https://github.com/vueuse/vueuse/tree/next
Milestone: https://github.com/vueuse/vueuse/milestone/2

## Main Focus

- [x] Refactor all `isSupport` to be ref, for SSR
  - #1800
- [x] #1743
- [x] #1768
- [ ] New @vueuse/math package, and move some functions over
  - #1224 
  - #1794
  - #1810
  - #1223
  - #1812
- [ ] Tests for Vue 2.7

## Breaking Changes

- [ ] #1687 
- [ ] #1605
- [ ] #1506

**Comment by userquin** [comment]
@antfu is there any change to include this https://github.com/vueuse/vueuse/issues/1697?

**Comment by antfu** [comment]
@userquin sure if you could make a PR

**Comment by francoism90** [comment]
```
runtime-core.esm-bundler.js:221 SyntaxError: The requested module '/node_modules/.vite/deps/@vueuse_core.js?v=16ed7cb0' does not provide an export named 'and'
```
Is `and` removed or moved?

**Comment by antfu** [comment]
Moved to `@vueuse/math`. Please check the release note.
