### ISSUE TITLE
`useVModel` break with vue 2.7 and vue-demi

### ISSUE THREAD

**Issue by b4n92uid** [vueuse/vueuse#1745]
### Describe the bug

Hello everyone, first thanks for the incredible toolset of composables function

So useVModel is trying to get the emit function directly from the VM :

https://github.com/vueuse/vueuse/blob/ef6cf56cfde1e41cead37ccda48cde68f89ec931/packages/core/useVModel/index.ts#L57
` const _emit = emit || vm?.emit || vm?.$emit?.bind(vm)`

And as stated here by the vue author we should not rely on other than proxy to use the current instance:
https://github.com/vuejs/vue/issues/12596#issuecomment-1173269807

So this can be refactored as (in backward compatible manner):
` const _emit = emit || vm?.emit || vm?.$emit?.bind(vm) || vm?.proxy?.emit`

### Reproduction

N/A

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 6.45 GB / 15.97 GB
  Binaries:
    Node: 16.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.44)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Looks good, PR welcome

**Comment by 1084350607** [comment]
I create a PR #1798

**Comment by Staremang** [comment]
Problem not resolved

Error:
```js
console.log(vm?.proxy?.emit) // undefined
```
Fixed:
```js
console.log(vm?.proxy?.$emit)
```

**Comment by Shimada666** [comment]
> I create a PR #1798

I used the latest version(v8.9.2) but it still doesn't work. Maybe @Staremang's PR can fix that. Could you please review and merge it? Thanks! @antfu
