### ISSUE TITLE
useNetwork return type value is undefined

### ISSUE THREAD

**Issue by freezepluto** [vueuse/vueuse#1747]
### Describe the bug

the value field returned by this hook is undefined , becouse this filed is only supported in chrome os 

### Reproduction

just use this hook and log returned value

### System Info

```Shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 111.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Safari: 15.3
  npmPackages:
    vue: ^2.6.12 => 2.6.14
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by freezepluto** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/type

**Comment by antfu** [comment]
What do you expect that we could do better? We have `isSupported` to indicate of the hook functions normallyl.
