### ISSUE TITLE
`templateRef` type argument does not support vue copmponent

### ISSUE THREAD

**Issue by Holi0317** [vueuse/vueuse#1757]
### Describe the bug

Currently the type argument for [`templateRef`](https://vueuse.org/core/templateref/#templateref) is `<T extends HTMLElement | SVGElement | null>`. If I pass in a vue component type in the type argument, typescript will fail as the type does not extend `HTMLElement` or `SVGElement`.

(Run `npm run build` in the given stackblitz below)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-sthn2a?file=src/App.vue

### System Info

```Shell
❯ npx envinfo --system --npmPackages '{vue,@vueuse/*}' --binaries --browsers
success Install finished in 1.656s


  System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @vueuse/core: ^7.6.2 => 7.7.1 
    vue: ^3.2.25 => 3.2.37
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Holi0317** [comment]
Side comment/suggestion: I think providing a stackblitz link in the issue template that contains vite+vue2/3+vueuse would make reproducing issues easier.

**Comment by Holi0317** [comment]
There is still activity in this issue/PR.

@antfu can you add no stale tag to this issue? Thanks.

**Comment by hfhchan** [comment]
templateRef can also be []
