### ISSUE TITLE
需要中文文档，谷歌翻译有问题，不是说组织社区翻译吗？

### ISSUE THREAD

**Issue by godingchen** [vueuse/vueuse#1759]
### Clear and concise description of the problem

请组织社区翻译，毕竟中国人占了多数开发者

### Suggested solution

建议提上议程

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
It's ready been discussed, we are not going to maintain the official Chinese documentation. Feel free to fork.
