### ISSUE TITLE
useObjectUrl

### ISSUE THREAD

**Issue by michaelhue** [vueuse/vueuse#1761]
### Clear and concise description of the problem

I'm developing apps that store files inside the browser (e.g. via Dexie/IndexedDB) and I need to provide a download link and/or preview image for those files. I'm using [`URL.createObjectUrl()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to create these links.

URLs created with `URL.createObjectURL()` should be released via [`URL.revokeObjectURL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL) when no longer needed.

I created a composable for my projects (see below) what watches a given `File`/`Blob` and automatically creates and revokes an object URL.

I think this composable could be useful for others and I would be happy to implent it and create a pull request if desired.

Thanks!

### Suggested solution

This is the code I'm currently using in my projects:

```ts
import { ref, watch } from "vue";
import { type MaybeRef, tryOnScopeDispose } from "@vueuse/core";

/**
 * Create a temporary object url for a blob which is automatically released
 * when the input changes or the scope is disposed.
 *
 * @param blob Source blob for object url.
 */
export function useObjectUrl(blob: MaybeRef<Blob | MediaSource | undefined>) {
  const blobRef = ref(blob);

  const objectUrl = ref<string | undefined>();

  const release = () => {
    if (objectUrl.value) {
      URL.revokeObjectURL(objectUrl.value);
      objectUrl.value = undefined;
    }
  };

  watch(
    blobRef,
    (blob) => {
      release();

      if (blob) {
        objectUrl.value = URL.createObjectURL(blob);
      }
    },
    { immediate: true }
  );

  tryOnScopeDispose(release);

  return objectUrl;
}

```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sounds good, PR welcome
