### ISSUE TITLE
useMediaQuery broke after latest update

### ISSUE THREAD

**Issue by wc-matteo** [vueuse/vueuse#1764]
### Describe the bug

the check introduced [here](https://github.com/vueuse/vueuse/commit/5a64cb53) is wrong:

`typeof 'matchMedia' === 'function'` will always return false since 'matchMedia' is a string

### Reproduction

https://github.com/vueuse/vueuse/commit/5a64cb53

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 4.62 GB / 15.80 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD      
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.66
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.44)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^8.8.0 => 8.8.0
    @vueuse/head: ^0.7.6 => 0.7.6
    vue: ^3.2.37 => 3.2.37
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dfreier** [comment]
Submitted a PR: https://github.com/vueuse/vueuse/pull/1765
