### ISSUE TITLE
onClickOutside: support iframe detection option

### ISSUE THREAD

**Issue by renatodeleao** [vueuse/vueuse#1777]
### Clear and concise description of the problem

If you're using `onClickOutside` to close poppers/dropdown menus and happen to have an `iframe` on the page — like an embed widget — clicking on it won't trigger the handler and, consequently, the menu won't close

=> [Sandbox of the "issue"](https://codesandbox.io/s/vueuse-core-onoutsideclick-iframe-test-mwu8wj) 

### Suggested solution

```vue
<script setup>
const onClickOutside(target, handler, { detectIframe: true }) // or being on by default and have the possibility to opt-out
</script>
```

```js
// ... onOutsideClick.js
const onFauxIframeClick = () => {
  // Note: on firefox clicking on iframe triggers blur, but only on
  //       next event loop it becomes document.activeElement
  // https://stackoverflow.com/q/2381336#comment61192398_23231136
  setTimeout(() => {
    const el = unrefElement(target)
    const { activeElement } = document
    if (
      activeElement &&
      activeElement.tagName === 'IFRAME' &&
      !el.contains(activeElement)
    ) {
      handler(event)
    }
  }, 0)
}

const cleanup = [
  // ...
  detectIframe && useEventListener(window, 'blur', onFauxIframeClick, { passive: true, capture }),
].filter(Boolean)
// ...
```

### Alternative

🤷 

### Additional context

Hey 👋 
i've been using and collaborating on the maintenance [`v-click-outside`](https://github.com/ndelvalle/v-click-outside) package for vue2. That's where I got the problem in the first place, [written the code that fixed it](https://github.com/ndelvalle/v-click-outside/pull/222) and that i'm now sharing here.

As mentioned in the package [README](https://github.com/ndelvalle/v-click-outside#detecting-iframe-clicks), detecting an iframe click is not as linear as a regular outside click and **has some caveats** that's why this is reported as an improvement `option`, instead of a default, since it might have some [unexpected side-effects](https://github.com/ndelvalle/v-click-outside/issues?q=iframe)  — at least from our research, would be more than happy if you have better solutions.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sibbng** [comment]
@renatodeleao Thanks for the detailed explanation. I added this feature in #1795.
