### ISSUE TITLE
bug(useStepper): using object steps relies on object key order being maintained

### ISSUE THREAD

**Issue by darrylnoakes** [vueuse/vueuse#1780]
### Describe the bug

Using objects for the steps relies on the key order of the wrapper object being maintained.

While there are possibilities that the order is entirely random, in general engines have followed certain rules rules for quite a while, with the spec being updated afterward.
The order for non-inherited properties is:

- Integer-like keys in ascending order
- String keys in insertion order
- Symbols in insertion order

<details>
<summary>
Expand for more detail on specs and such
</summary>

There was almost no spec for this prior to ES2015, and it was only properly specced in ES2020.
From [an SO answer](https://stackoverflow.com/a/5525820/15261914): "The iteration order for objects follows [a certain set of rules](https://stackoverflow.com/a/38218582/292500) since ES2015, but it does not (always) follow the insertion order."

From that second link:

> The order for "own" (non-inherited) properties is:
> 
> - Integer-like keys in ascending order
> - String keys in insertion order
> - Symbols in insertion order
> 
> Thus, there are three segments, which may alter the insertion order (as happened in the example). And integer-like keys don't stick to the insertion order at all.
> 
> In ES2015, only certain methods followed the order:
> 
> - `Object.assign`
> - `Object.defineProperties`
> - `Object.getOwnPropertyNames`
> - `Object.getOwnPropertySymbols`
> - `Reflect.ownKeys`
> - `JSON.parse`
> - `JSON.stringify`
> 
> As of ES2020, all others do (some in specs between ES2015 and ES2020, others in ES2020), which includes:
> 
> - `Object.keys, Object.entries, Object.values, ...`
> - `for..in`

</details>

While there is the possibility that this doesn't work in older browsers, I don't believe this is an issue, especially moving forward.

However, if this composable is used with a combination of integer keys and non-integer keys, the order will not be maintained, as stated in the rules given above, _which is an actual issue_.
E.g. "Intro, 1, 2, 3, End" would be changed to "1, 2, 3, Intro, End".

~~A potential fix is to rather pass an array of objects, with each an extra property in each object to specify the name.~~ Rejected, as it requires a special property in each step object.

A potential solution is to pass an array as usual, but each item is a tuple of the key and object.
For example:

```js
const stepper = useStepper([
  ['user-information', {
    title: 'User information',
    isValid: () => form.firstName && form.lastName,
  }],
  ['billing-address', {
    title: 'Billing address',
    isValid: () => !!form.billingAddress,
  }],
  ['terms', {
    title: 'Terms',
    isValid: () => form.contractAccepted === true,
  }],
  ['payment', {
    title: 'Payment',
    isValid: () => ['credit-card', 'paypal'].includes(form.payment),
  }],
])
```

This is not that different in style to the original: the top-level object is changed to an array, and for each item the key-value pair is changed to an array.

### Reproduction

[VueUse `useStepper` key-order issue repro on StackBlitz](https://stackblitz.com/edit/vitejs-vite-hnxybv)

### System Info

(Taken from the StackBlitz repro.)

```Shell
System:
  OS: Linux 5.0 undefined
  CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 0 Bytes / 0 Bytes
  Shell: 1.0 - /bin/jsh
Binaries:
  Node: 16.14.2 - /usr/local/bin/node
  Yarn: 1.22.10 - /bin/yarn
  npm: 7.17.0 - /bin/npm
npmPackages:
  @vueuse/core: ^8.9.0 => 8.9.0 
  vue: ^3.2.25 => 3.2.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lbineau** [comment]
I agree this is an issue. Could we maybe use `Map()` to ensure the order or an `order` field inside the object?

**Comment by darrylnoakes** [comment]
I personally like the method I suggested because of its simplicity and wide compatibility. `Map`s do not serialize well, and maintaining the order separately would be confusing and a pain. If you do not have the issue of numeric keys, you could use `Object.entries()` to construct it from an object in the original format.

Hence, I propose it be an overload: it accepts an object as before, and this new structure, but internally uses the array structure and converts an object argument to it using `Object.entries()`.
