### ISSUE TITLE
useVibrate doest not play onMounted

### ISSUE THREAD

**Issue by RemixJazzCode** [vueuse/vueuse#1789]
### Describe the bug

Im tryin to use this component when timer is to zero. But it component does not play until zero count. also as i mentioned title, it does not play in onMounted func too. i think this component equal to useAudio play. It means user action required like button click( broswer policy). Check plz.

### Reproduction

https://vueuse.org/core/usevibrate/#usevibrate

### System Info

```Shell
Broswer: chrome,samsung broswer.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by darrylnoakes** [comment]
As per [the support table on the MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate#browser_compatibility):

> Beginning in Chrome 60, this method requires a user gesture. Otherwise it returns false.

> Beginning in Samsung Internet 8.0, this method requires a user gesture. Otherwise it returns false.

**Comment by Avaray** [comment]
I think it should work if user installed PWA.

**Comment by wheatjs** [comment]
Per @darrylnoakes comment, this is default browser behavior and cannot be changed via the VueUse library, so I'm going to close this issue.
