### ISSUE TITLE
Using useMagicKeys(), the console reports an error after pressing an undefined key combination

### ISSUE THREAD

**Issue by lainbo** [vueuse/vueuse#1805]
### Describe the bug

Pressing an undefined key combination in a web page and then letting the page lose focus will result in an error being reported in the console

VueUse 8.9.1

![demo](https://user-images.githubusercontent.com/46062895/178107001-e11bd300-a86f-4f29-8c4c-664463446c3a.gif)

### Reproduction

https://codesandbox.io/s/trusting-swirles-367cg7?file=/src/App.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700KF
    Memory: 8.57 GB / 15.86 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by craigrileyuk** [comment]
Can confirm I'm getting this too. `useMagicKeys` is spewing errors onto my console. First it was stuff like `error trying to set value on readonly computed`, now it's `Uncaught TypeError: refs[key] is undefined` from `function reset()`.

**Comment by antfu** [comment]
Fixed in https://github.com/vueuse/vueuse/pull/1856
