### ISSUE TITLE
Vue Demi issue with Nuxt Bridge

### ISSUE THREAD

**Issue by LynxTR** [vueuse/vueuse#1806]
### Describe the bug

Yesterday (7/8/2022) i was trying to implement another module to my project and removed package lock & node modules, then i reinstalled npm. Afterwards importing and using any composable, for instance useDark() or useToggle(), from vueuse causes an error. I have tried @vueuse/core versions 7.6.2 and 8.9.1, and later on i cloned the vitesse-nuxt-bridge repo and tried to run it, but i am still getting same error on both of my macos and windows machines:

`SyntaxError: The requested module 'vue-demi' does not provide an export named 'onBeforeUnmount'`

![Screenshot](https://user-images.githubusercontent.com/64704879/178113208-15e2ad78-09aa-4f0b-a646-7f98d24b3064.png)

### Reproduction

[https://github.com/antfu/vitesse-nuxt-bridge](https://github.com/antfu/vitesse-nuxt-bridge)

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Suniron** [comment]
Same error today !
