### ISSUE TITLE
Team members page

### ISSUE THREAD

**Issue by antfu** [vueuse/vueuse#1808]
Hey @wheatjs @okxiaoliang4 @sibbng @anteriovieira @scottbedard @cawa-93 @lstoeferle @harlan-zw @Tahul @egoist - sorry for directly pinging, but in case you are not aware of, we now have a new team section on the front page of our docs https://vueuse.org. You have a chance to introduce yourself a bit.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/11247099/178132075-34219b3a-e870-48e7-9b1d-9b2d85e07652.png">

When you got some time, please review your info, and fulfill them out if anything is missing by sending a PR to https://github.com/vueuse/vueuse/blob/main/packages/contributors.ts#L29. Thank you!

**Comment by antfu** [comment]
And in the meantime, for team members, if you are not in our Discord already, please join by https://chat.antfu.me and then ping me so I can set your role to access our team's private channel. 🙌

**Comment by scottbedard** [comment]
That looks great, thank you. One thing though, the Twitter profile you linked for me is actually a different person of the same name. I'm not active on Twitter, so just linking to GitHub would be great.

**Comment by antfu** [comment]
@scottbedard Sure, you can remove the entry with the PR :)

**Comment by harlan-zw** [comment]
Looks great, thanks for the ping :+1:
