### ISSUE TITLE
New `@vueuse/math` package

### ISSUE THREAD

**Issue by antfu** [vueuse/vueuse#1812]
We plan to ship a new `@vueuse/math` package in v9.0, where you can see it in the `next` branch already.

We planned to adding those new functions:

- [ ] `useMax`
- [ ] `useMin`
- [x] [`useRound`](https://github.com/vueuse/vueuse/pull/1820)
- [x] [`useFloor`](https://github.com/vueuse/vueuse/pull/1817)
- [x] [`useCeil`](https://github.com/vueuse/vueuse/pull/1818)
- [ ] `useSum`
- ...

Open for contributions

**Comment by LittleSound** [comment]
For some of the single parameter `Composables` maybe we can support `setter` ? 
For example `useRound`:
```ts
const round = useRound(0.5)

watchSyncEffect(() => console.log(value)) // log: 1

round.value = 0.1 // log: 0

round.value = 2.5 // log: 3
```

**Comment by antfu** [comment]
@LittleSound Yes we could. But how should we handle this case?:

```ts
const round = useRound(0.5)

watchSyncEffect(() => console.log(value)) // log: 1

round.value = 0.1 // log: 0

round.value = 2.5 // log: 3

**Comment by LittleSound** [comment]
@antfu  😂 I made a typo, it should be `watchSyncEffect(() => console.log(round.value))`

**Comment by antfu** [comment]
No problem with the typo. My question is, how should we handle the write back if the value is provided as a ref?

**Comment by LittleSound** [comment]
> @LittleSound是的，我们可以。但是我们应该如何处理这种情况呢？：
> 
> ```ts
> const value = ref(0.5)
> const round = useRound(value)
> 
> watchSyncEffect(() => console.log(value)) // log: 1
> 
> round.value = 0.1 // log: 0 // value?
> 
> round.value = 2.5 // log: 3
> ```

It seems to me that "write-back" should probably be disabled, or needs to be turned on via options

**Comment by zojize** [comment]
For associative binary operations (i.e. `Math.min, Math.max, +, *` etc.), I'm wondering if we could provide overloads for both array input and multiple arguments input?

e.g.
```ts
function min(arr: MaybeComputedRef<MaybeComputedRef<number>[]>): ComputedRef<number>
function min(...args: MaybeComputedRef<number>[]): ComputedRef<number>
function min(...args: [MaybeComputedRef<MaybeComputedRef<number>[]>] | MaybeComputedRef<number>[]): ComputedRef<number> {
  let xs: Ref<MaybeComputedRef<number>[]>
  if (args.length === 1 && Array.isArray(resolveUnref(args[0])))
    xs = resolveRef(args[0]) as typeof xs
  else
    xs = resolveRef(args) as typeof xs
  return computed(() => xs.value.reduce<number>((a, b) => Math.min(resolveUnref(a), resolveUnref(b)), Infinity))
}

min(ref(1), ref(2), 3) // works
min([1, 2, 3]) // works
min([ref(1), ref(2), 3]) // works
min(ref([1, 2, 3])) // works
```

**Comment by LittleSound** [comment]
@zojize I'm trying to achieve a similar effect in [`useSum`](https://github.com/vueuse/vueuse/pull/1831)
[packages/math/useSum/index.test.ts](https://github.com/vueuse/vueuse/pull/1831/files#diff-335c3ac1be1cc1f0344db1a781fd1357561cbab78cd37d0608da61056b4ae027)

**Comment by yjl9903** [comment]
@LittleSound I saw your implementation of useSum

https://github.com/vueuse/vueuse/blob/fe25afed57f80591f674101e79944f387c7063b4/packages/math/useSum/index.ts#L19-L35

Maybe we can have some more general array utilities, like `useReduce`, `useFilter`, `useMap`, `useFind` , `useFindIndex`, and so on ?

And then implement `useMax`, `useMin`, and `useSum` with `useReduce` ?

------

Another question is should we optimize `useSum` in advance, for the scenes that the input array is a long array of `Ref<number>`. We can store the sum, and modify the the sum when the value of a ref is changed. So it will not re-compute the full result at each time.

**Comment by LittleSound** [comment]
> Another question is should we optimize useSum in advance, for the scenes that the input array is a long array of Ref<number>.

@yjl9903 Do you have any ideas about how to implement this kind of optimization?

**Comment by yjl9903** [comment]
> > Another question is should we optimize useSum in advance, for the scenes that the input array is a long array of Ref.
> 
> @yjl9903 Do you have any ideas about how to implement this kind of optimization?

Maybe something like this

```ts
export function useSum(nums: Array<MaybeComputedRef<number>>) {
  const sum = ref(0)
  for (const num of nums) {
    sum.value += resolveUnref(num)
    watch(() => resolveUnref(num), (newNum, prevNum) => {
      sum.value += newNum - prevNum
    })
  }
  return sum
}
```

And I am not sure how to implement when wrapper array is also a ref.

Another problem is that the optimized one has different semantic from the origin. Counter example is

```ts
const r1 = ref(Number.MAX_VALUE)
const r2 = ref(Number.MAX_VALUE)
const sum = useSum([r1, r2]) // Inf
r1.value = 0
r2.value = 0
// NaN (Inf - Inf = NaN)
```

**Comment by LittleSound** [comment]
1. If the array itself is also responsive, perhaps add a `watch(() => resolveUnref(nums).length, () => {})` as an iterator side effect to reinitialize when the length changes.
2. Is `Infinity` a special edge case, and if so, can it be recognized and handled specially?
