### ISSUE TITLE
Externalize `@vueuse/firebase` `@vueuse/rxjs` `@vueuse/electron` 

### ISSUE THREAD

**Issue by antfu** [vueuse/vueuse#1813]
Since those packages are bound to specific integrations, where the major version of VueUse doesn't normally affect them, I propose we move those tree packages as three standalone repo under the org so they could be iterated and released independently from the core.

**Comment by antfu** [comment]
Yeah gave it a try but decided not to do it due to the complexity and documentation.

**Comment by wheatjs** [comment]
Ah yeah, also feel like it would kind of make it feel too isolated from everything else and then not get as much attention. Out of sight out of mind kinda thing
