### ISSUE TITLE
useMagicKeys internal throw `TypeError : Cannot set properties of undefined value`

### ISSUE THREAD

**Issue by Matrixbirds** [vueuse/vueuse#1855]
### Describe the bug

I m using tiptap and useMagicKeys. I trigger editor element blur event would random throw this error.

I m also breakpoint in the error stack.

I find the `usedKeys` is not matched with refs in my runtime context.
<img width="292" alt="arrowdown RefImpl {__v_isShallow fals" src="https://user-images.githubusercontent.com/9990676/178300769-5c8439af-2977-46f1-93e3-ef7bc8f24300.png">

### Reproduction

use tiptap offical demo with useMagicKeys.

### System Info

```Shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 75.53 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.5.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 99.0.1
    Safari: 15.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
fixed in https://github.com/vueuse/vueuse/pull/1856
