### ISSUE TITLE
new composable: `usePropClone`

### ISSUE THREAD

**Issue by jd-solanki** [vueuse/vueuse#1859]
### Clear and concise description of the problem

When creating a dialog with form inside, we need to clone the passed form data to the dialog component and emit that data on submit and reset data on cancel

### Suggested solution

We can create a new function `usePropClone` which will clone the prop value.

```ts
const { data, reset } = usePropClone(toRef(props.formData))
```

### Alternative

Building components without this composable, writing reset and cloning in each dialog.

### Additional context

I am happy to make PR _(if this function should be allowed to be added in vueuse)_ but I would like to know should I clone the prop data using:
```js
JSON.stringify(JSON.parse(propToClone))
```

Thanks.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chaii3** [comment]
I'm not sure that it only about props. Making templates for forms in my opinion it might be useful.

**Comment by antfu** [comment]
https://github.com/vueuse/vueuse/pull/2017#issuecomment-1204778668

**Comment by chaii3** [comment]
> #2017 (comment)

I can do it

**Comment by chaii3** [comment]
Made a new pr. Can you check it please. Is that what you expected ?
