### ISSUE TITLE
Add `total` to `UseOffsetPaginationReturn` of `useOffsetPagination`

### ISSUE THREAD

**Issue by DamianGlowala** [vueuse/vueuse#1903]
### Clear and concise description of the problem

For backend-based pagination, every data fetch may return a total number of items alongside the items chunk for a given page. Currently, there is no way to update the `total` variable directly within a function called by either `onPageChange`, `onPageSizeChange` or `onPageCountChange`.

### Suggested solution

Extend the `UseOffsetPaginationReturn` interface with the presence of the `total` key:
```
export interface UseOffsetPaginationReturn {
  total: Ref<number>
  currentPage: Ref<number>
  currentPageSize: Ref<number>
  pageCount: ComputedRef<number>
  isFirstPage: ComputedRef<boolean>
  isLastPage: ComputedRef<boolean>
  prev: () => void
  next: () => void
}
```

### Alternative

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jiankafei** [comment]
@DamianGlowala Why did you close the issue? Do you have a solution?
