### ISSUE TITLE
peerDependencies on vue missing for vueuse/router

### ISSUE THREAD

**Issue by vincentbernat** [vueuse/vueuse#1912]
### Describe the bug

When requesting `@vueuse/router` with Yarn, it complains about a missing dependency on `vue` due to using `vue-demi`:

```
➤ YN0002: │ @vueuse/router@npm:8.6.0 [d54e3] doesn't provide vue (p9ce65), requested by vue-demi
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
```

Unlike `@vueuse/core`, `@vueuse/router` is missing this part in `package.json`:

```json
  "peerDependencies": {
    "@vue/composition-api": "^1.1.0",
    "vue": "^2.6.0 || ^3.2.0"
  },
  "peerDependenciesMeta": {
    "vue": {
      "optional": true
    },
    "@vue/composition-api": {
      "optional": true
    }
  },
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-bc8aw8/?file=package.json (dunno how to switch to Yarn here)

### System Info

```Shell
System:
    OS: Linux 5.18 Debian GNU/Linux bookworm/sid
    CPU: (4) x64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
    Memory: 2.79 GB / 7.68 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /tmp/xfs-e4e7a53a/node
    Yarn: 3.2.1 - /tmp/xfs-e4e7a53a/yarn
  Browsers:
    Firefox: 102.0.1
  npmPackages:
    @vueuse/core: ^8.6.0 => 8.6.0
    @vueuse/router: ^8.6.0 => 8.6.0
    vue: ^3.2.37 => 3.2.37
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by l3d00m** [comment]
Can this be reopened?
