### ISSUE TITLE
Webstorm Error: Cannot resolve symbol 'useDebounceFn' 

### ISSUE THREAD

**Issue by Cowjiang** [vueuse/vueuse#1913]
### Describe the bug

use: 
`import {useScreenOrientation, useWindowSize, useDebounceFn} from '@vueuse/core'`

### Reproduction

webstorm error

### System Info

```Shell
{
  "name": "scroll_demo",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@vueuse/core": "^8.9.2",
    "alloytouch": "^0.3.0",
    "pinia": "^2.0.16",
    "pixi.js": "^6.4.2",
    "sass": "^1.53.0",
    "sass-loader": "^13.0.2",
    "vite-plugin-windicss": "^1.8.6",
    "vue": "^3.2.25"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^2.3.3",
    "typescript": "^4.5.4",
    "unplugin-auto-import": "^0.9.2",
    "vite": "^2.9.9",
    "vue-tsc": "^0.34.7"
  }
}
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jodyhoonstarr** [comment]
I believe this is the workaround for intellij editors and vueuse: https://github.com/vueuse/vueuse/issues/896#issuecomment-1190359361

**Comment by Cowjiang** [comment]
> I believe this is the workaround for intellij editors and vueuse: [#896 (comment)](https://github.com/vueuse/vueuse/issues/896#issuecomment-1190359361)

Thanks, I marked the directory as not exclude and it works XD

**Comment by antfu** [comment]
Duplicated #896
