### ISSUE TITLE
useAxios 如何使用防止重复请求

### ISSUE THREAD

**Issue by iizhangchao** [vueuse/vueuse#1924]
### Describe the bug

如何防止重复请求

### Reproduction

useAxios

### System Info

```Shell
任何
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by murongg** [comment]
提供一个思路：搞一个 Map 数据结构，在请求拦截器里将请求的 URL 存起来，在这之前判断一下 map 里有没有这条数据，如果有，中断这次请求，如果没有则存起来。在响应拦截器里将这条 URL 再清除掉。

**Comment by sbq17** [comment]
防抖？

**Comment by BigBroFinch** [comment]
搞个useSWR
