### ISSUE TITLE
Using useFullscreen() will prompt an error in the console

### ISSUE THREAD

**Issue by lainbo** [vueuse/vueuse#1926]
### Describe the bug

Using useFullscreen()'s toggle() will prompt a warning "`Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.`" and error "`Uncaught (in promise) TypeError: fullscreen error at enter (index.mjs:2663:21) at async toggle (index.mjs:2671:7)`" in the console

### Reproduction

https://codesandbox.io/s/flamboyant-diffie-d0u801?file=/src/App.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700KF
    Memory: 7.64 GB / 15.86 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by okxiaoliang4** [comment]
It must either be located within the top-level document or in an `<iframe>` which has the [allowfullscreen](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-allowfullscreen) attribute applied to it.

see https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen#usage_notes
