### ISSUE TITLE
SpeechSynthesis Demo - changing Language reverts to first selection on Speak

### ISSUE THREAD

**Issue by saschwarz** [vueuse/vueuse#1928]
### Describe the bug

I was looking at: https://vueuse.org/core/usespeechsynthesis/#demo
and noticed if I change the Language input from the default (first) selection in the select list as soon as I press the Speak button the selection changes back to the first selection and the voice used is also the first selection.

I have tested it on my OSX machine using Safari and Chrome with the same result.

### Reproduction

https://vueuse.org/core/usespeechsynthesis/#demo

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 31.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.3.0 - ~/.nvm/versions/node/v18.3.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v18.3.0/bin/npm
    Watchman: 2022.06.27.00 - /usr/local/bin/watchman
  npmPackages:
    @vueuse/core: ^8.9.3 => 8.9.3 
    vue: ^3.2.21 => 3.2.37
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by saschwarz** [comment]
Clarifying: if you select a different voice *and* that voice has the same `lang` as the already selected voice then the language select list reverts to the initial voice in that language and the voice used is the first one with the matching `lang`.

**Comment by sibbng** [comment]
I fixed this in https://github.com/vueuse/vueuse/pull/1882 but it's on [next](https://github.com/vueuse/vueuse/commits/next) branch and will be released as part of v9. I just made another PR (#1930) to fix v8 demo.
