### ISSUE TITLE
CreateGlobalState: does not support Set() when using UseStorage

### ISSUE THREAD

**Issue by LoganTann** [vueuse/vueuse#1939]
### Describe the bug

Hello, 
I implemented in my project the example code for CreateGlobalState (https://vueuse.org/shared/createGlobalState/)

However, one of my objects stored is initialized as a `new Set()`. Using a set instead of an array is better in my use case.

When trying to mutate a set using the methods `.add()` or `.delete()`, the set is not edited.

When reloading my browser tab, I can no longer use the methods (will result into a `state.mySet.has` is not a function)

I suspect the UseStorage function not properly serializing and deserializing the set. We can see in the local storage that it is stingified as an empty object (`{}`)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-b3qc2h?file=src/Item.vue

### System Info

```Shell
-- my real config

NuxtJS v3.0.0-rc.5 and Firefox 102.0.1

-- nxp envinfo
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 4.61 GB / 15.74 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^8.9.2 => 8.9.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by LoganTann** [comment]
I made a very small edit in the stackblitz : https://stackblitz.com/edit/vitejs-vite-b3qc2h?file=src/Item.vue

To reproduce :  
- Clear your localstorage
- Interact with buttons. Notice it now works, but the JSON.stringify call says the set remains empty
- Reload page. As expected, the component don't work.

Dirty quickfix (works only if numbers are stored): As my ids are just numbers, I use a string instead of a set. Adding a number into the set means concatenating the string `[${id}]`, delete means replace `[${id}]` by empty string, etc.

**Comment by sibbng** [comment]
Alternatively, you can use [superjson](https://github.com/blitz-js/superjson) as a custom serializer.

```ts
import { createGlobalState, useStorage } from '@vueuse/core';
import superjson from 'superjson';

export const useGlobalState = createGlobalState(() =>
  useStorage('state-trsEditorFiles', {
    openedIds: new Set<number>(),
    allFiles: [],
  }, undefined, {
    serializer: {
      read: (raw) => superjson.parse(raw),
      write: (val) => superjson.stringify(val),
    }
  })
);

```

**Comment by antfu** [comment]
See https://github.com/vueuse/vueuse/pull/1948

**Comment by LoganTann** [comment]
Debatable, but I'd suggest editing the docs in https://vueuse.org/core/useStorage/#custom-serialization. It is not very clear for me (it does not explain well why would I need a custom serializer). Maybe mentioning superjson as custom serializer would solve the problem.
