### ISSUE TITLE
useStorage: difference between Object.keys(rawValue) and Object.keys(rawInit)

### ISSUE THREAD

**Issue by haoval** [vueuse/vueuse#1954]
### Describe the bug

if an object exists in localStorage with given key:
```javascript
test: {
  a:1
}
```

oops:
```javascript
const testState = useLocalStorage('test', {
  a: 1,
  b: 2,
})
console.log(testState.value.b) // returns undefined
```

### Reproduction

dev

### System Info

```Shell
--npmPackages {
  "@vueuse/core": "^8.9.3"
}
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Yeah, currently initValue only applies when the stored value is undefined. I think we could introduce an option to deep merge the default. PR welcome

**Comment by lumdzeehol** [comment]
> Yeah, currently initValue only applies when the stored value is undefined. I think we could introduce an option to deep merge the initialValue. PR welcome

`useStorage` locates in `@vueuse/core`, so I think it's better to implement a lite deepmerge function internally instead of introducing lib likes `deepmerge`？

**Comment by antfu** [comment]
Yes https://github.com/vueuse/vueuse/pull/1957 allows it to be a function to provide custom merge logic
