### ISSUE TITLE
computedAsync with lazy does not always update when current updates

### ISSUE THREAD

**Issue by Evertt** [vueuse/vueuse#1956]
### Describe the bug

Currently I'm on @vueuse/core version 8.9.4.

I've been so frustrated that I didn't see my UI update when it was supposed to. So I've been debugging computedAsync by copying it to my own `src` directory and placing a whole bunch of `console.log()` statements everywhere. And here's what I found:

When `current.value` is updated on [line 94](https://github.com/vueuse/vueuse/blob/main/packages/core/computedAsync/index.ts#L94), then [the computed return on line 108](https://github.com/vueuse/vueuse/blob/main/packages/core/computedAsync/index.ts#L108-L111) (since I'm using `lazy`) does not always recompute.

I honestly have no idea why it wouldn't.

One experiment that I did was adding the following code just above the [`return computed`](https://github.com/vueuse/vueuse/blob/main/packages/core/computedAsync/index.ts#L108):

```ts
watch(() => current, () => console.log("current change detected", { current })
```

And that `console.log` *always* ran at the right time, so for some reason `watch` is better at tracking `current` than `computed` is.

### PS

I'm sorry, the reproduction link I shared is a lie. I don't know how to reproduce the problem exactly, except maybe by giving you guys access to my entire project. But of course that'd be too big for you guys to delve into and also I have an NDA on that project. And even on my own project, the bug doesn't happen *all* the time. But still too often to be acceptable.

The best I could offer you for now is [a screencast that demonstrates the problem](https://youtu.be/r7fV0U20z9U). I don't know if that helps, but it's the best I could do.

I hope that maybe you guys are willing think with me. I'm curious to understand why `computed` wouldn't recompute when `current.value` clearly changes. I'm wondering if it's possible to find out at runtime what that particular `compute` has been able to identify as its dependencies that it will try to track.

But most of all I'd appreciate some help with finding a workaround for now. I'm trying to fix this right now by writing my own `customRef`, but this is the first time I'm doing that,, so I'm not 100% sure I'm gonna do that right.

### edit

Okay the `customRef` thing didn't work out as I was hoping. One thing I'm trying at the moment is replace [`computed` at line 108](https://github.com/vueuse/vueuse/blob/main/packages/core/computedAsync/index.ts#L108) with this:

```ts
return computedWithControl(current, () => {
  started.value = true
  return current.value
})
```

And that *seems* to be working, as in everything gets recomputed when it should, except that now I get loads of these errors:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/1267282/179739825-acf10ffd-851a-4d2a-bc6a-361a5aa77a3d.png">

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zruu1f?file=src/api.js

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 90.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Brave Browser: 89.1.22.71
    Chrome: 103.0.5060.114
    Safari: 15.5
  npmPackages:
    @vueuse/core: ^8.9.4 => 8.9.4 
    vue: ^3.2.31 => 3.2.31 
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Evertt** [comment]
For now I fixed it like so:

```ts
// computedWithTrigger.ts

import type { ComputedGetter, ComputedRef, WritableComputedOptions, WritableComputedRef } from 'vue'
import { customRef, ref } from 'vue'
import { Fn, isFunction } from "."

export interface ComputedWithTriggerRefExtra {
  /**
   * Force update the computed value.
   */
  trigger(): void
}

export interface ComputedWithTrigger<T> extends ComputedRef<T>, ComputedWithTriggerRefExtra {}
export interface WritableComputedWithTriggerl<T> extends WritableComputedRef<T>, ComputedWithTriggerRefExtra {}

export function computedWithTrigger<T>(
  fn: ComputedGetter<T>
): ComputedWithTrigger<T>

export function computedWithTrigger<T>(
  fn: WritableComputedOptions<T>
): WritableComputedWithTriggerl<T>

export function computedWithTrigger<T>(fn: ComputedGetter<T> | WritableComputedOptions<T>) {
  let value: T
  const get = isFunction(fn) ? fn : fn.get
  const set = isFunction(fn) ? undefined : fn.set
  const dirty = ref(true)
  let trigger: Fn
  
  const update = () => {
    dirty.value = true
    trigger()
  }
  
  const result = customRef((track, _trigger) => {    
    trigger = _trigger
    
    return {
      get() {
        if (dirty.value) {
          value = get()
          dirty.value = false
          track()
        }
        return value
      },
      set(newValue) {
        if (!set) throw "No set function was provided"
        set(newValue)
        dirty.value = true
        trigger()
      }
    }
  })
  
  if (Object.isExtensible(result))
    (result as any).trigger = update
  
  return result
}
```

This code is similar to `computedWithControl`, except that it's not watching a `WatchSource`, it will simply only recompute when `.trigger()` is called.

And now I adapted my `computedAsync` to look like this:

```ts
// computedAsync.ts

import { noop } from 'lodash-es'
import { isRef, Ref, ref, unref, watchEffect } from 'vue'
import { computedWithTrigger } from "./computedWithTrigger"

type AsyncComputedOnCancel = (cancelCallback: () => void) => void

interface AsyncComputedOptions {
  /**
   * Should value be evaluated lazily
   *
   * @default false
   */
  lazy?: Boolean
  /**
   * Ref passed to receive the updated of async evaluation
   */
  evaluating?: Ref<boolean>
  /**
   * Callback when error is caught.
   */
  onError?: (e: unknown) => void
}

type NoRef<T> = T extends Ref ? never : T

function computedAsync<U, T extends NoRef<U>>(evaluationCallback: (onCancel: AsyncComputedOnCancel) => T | Promise<T>, initialState?: T, optionsOrRef?: Ref<boolean> | AsyncComputedOptions): Ref<T> {
  let options: AsyncComputedOptions
  if (isRef(optionsOrRef)) {
    options = {
      evaluating: optionsOrRef
    }
  } else {
    options = optionsOrRef || {}
  }
  const {
    lazy = false,
    evaluating = void 0,
    onError = noop
  } = options
  const started = ref(!lazy)
  const current = ref(initialState) as Ref<T>
  let counter = 0

  const toReturn = !lazy ? current :
    computedWithTrigger(() => {
      started.value = true
      return current.value
    })
  
  watchEffect(async (onInvalidate) => {
    if (!started.value) return

    counter++
    const counterAtBeginning = counter
    let hasFinished = false
    if (evaluating) {
      Promise.resolve().then(() => {
        evaluating.value = true
      })
    }
    try {
      const result: T = await evaluationCallback((cancelCallback) => {
        onInvalidate(() => {
          if (evaluating)
            evaluating.value = false
          if (!hasFinished)
            cancelCallback()
        })
      })
      if (counterAtBeginning === counter) {
        current.value = unref(result)
        if (lazy) (toReturn as any).trigger()
      }

    } catch (e) {
      onError(e)
    } finally {
      if (evaluating && counterAtBeginning === counter)
        evaluating.value = false
      hasFinished = true
    }
  })

  return toReturn
}

export { computedAsync, computedAsync as asyncComputed }
```

The main difference from your official `computedAsync` implementation is that I wrote this:

```ts
  const toReturn = !lazy ? current :
    computedWithTrigger(() => {
      started.value = true
      return current.value
    })

      // And then a little later, after result has been computed

      if (counterAtBeginning === counter) {
        current.value = unref(result)
        if (lazy) (toReturn as any).trigger() // Here I make absolutely sure that the computed will recompute
      }
```

**Comment by haydenbr** [comment]
FWIW, I'm seeing kind of a similar issue with `asyncComputed`, but in unit tests (vitest) and I'm not using `lazy`

```ts
const userId = ref<string>('')

// ...

const customers = asyncComputed<Customer[]>(
  () => {
    if (!userId.value) {
      return [];
    }

    return CustomersApi.fetchAllCustomers();
  },
  []
);
```

Just doing a watch and console.log on userId, I see the initial value and then the actual value whenever userId is populated. But the function passed to asyncComputed only ever runs once. However, it works as expected when actually running in the browser.
