### ISSUE TITLE
Enable default color scheme value in `useDark`

### ISSUE THREAD

**Issue by MCYouks** [vueuse/vueuse#1967]
### Clear and concise description of the problem

By default, `useDark` uses `usePreferredDark` to set up the color scheme value by default. As a result, we cannot force  `light` as the default value.

### Suggested solution

This problem could be solved by implementing a `defaultValue` parameter in the `UseDarkOptions` payload, as follow:

```
import { useDark, useToggle } from '@vueuse/core'

const isDark = useDark({ defaultValue: "light" })
const toggleDark = useToggle(isDark)
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Does that mean you don't want the auto mode by `usePreferredDark` at all?

**Comment by MCYouks** [comment]
That's absolutely correct!

**Comment by MCYouks** [comment]
Hey there, any update about the implementation in production? Thanks :)

**Comment by tripflex** [comment]
Yes i'm surprised this isn't possible either

**Comment by tripflex** [comment]
```javascript
import { useColorMode, useToggle, useDark } from '@vueuse/core'

useColorMode({initialValue: 'dark'})

export const isDark = useDark()

export const toggleDark = useToggle(isDark)
```
