### ISSUE TITLE
add useIndexedDB function

### ISSUE THREAD

**Issue by westhide** [vueuse/vueuse#1972]
### Clear and concise description of the problem

# useIndexedDB
I want to add useIndexedDB function , so that we can use browser indexedDB convenient.And I intend to submit  PR to implement this.

> #### Plan
> 1. wrap CRUD operate in indexedDB with reactive data as useStorage() have done.
> 2. able to auto cache data`(such as axios response)` in indexedDB , refetch api  only when outdated or force call. let web app can store data in a long term.
> 3. add features bind to indexedDB , reference other useRequest library have done.

### Inspired by 
* [`dexie`](https://github.com/dexie/Dexie.js/blob/master/src/classes/dexie/dexie.ts)
* [`rx-database`](https://github.com/pubkey/rxdb/blob/master/src/rx-database.ts)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by westhide** [comment]
Is that meaningful to work on it?

**Comment by darrylnoakes** [comment]
FWIW, [Jake Archibald's `idb` library](https://github.com/jakearchibald/idb) is a nice thin wrapper around IndexedDB.
