### ISSUE TITLE
How to use the execute method in useAxios to handle request exceptions？

### ISSUE THREAD

**Issue by Mintnoii** [vueuse/vueuse#1979]
### Describe the bug

I looked at the [execute](https://github.com/vueuse/vueuse/blob/dc3ebe80bc61ee56004fdcd417cb234ee749e41e/packages/integrations/useAxios/index.ts#L171) code, and I saw that it finally returned this then method.
```typescript
  const then = (onFulfilled, onRejected) => waitUntilFinished().then(onFulfilled, onRejected);
```
So I use the following method to capture the data for the request exception. 👇
```typescript
const { data, execute, error } = useAxios('login url',{method:'POST', data: formData},{immediate:false});

execute().then(() => {
  //  Whether the request is successful or not is always executed here.🤔
  console.log(data, error)
},err => {
  // After the Axios request fails, I want to get the exact error message here.
  console.log(err)
})
```
I don't know if there is a problem with my understanding or incorrect usage, please help me to have a look.

### Reproduction

https://github.com/vueuse/vueuse/blob/dc3ebe80bc61ee56004fdcd417cb234ee749e41e/packages/integrations/useAxios/index.ts#L185

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
    Memory: 13.35 GB / 31.88 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^8.7.5 => 8.9.4
    @vueuse/integrations: ^8.9.4 => 8.9.4
    vue: ^3.2.25 => 3.2.37
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jwrycza-tl** [comment]
@Mintnoii I have the same problem. Did you find any solution or do you know how to handle request expectation?
