### ISSUE TITLE
createGlobalState - use without localstorage should be documented

### ISSUE THREAD

**Issue by LoganTann** [vueuse/vueuse#1991]
### Clear and concise description of the problem

The only code example of createGlobalState documentation (https://vueuse.org/shared/createglobalstate/) is the following : 

```ts
import { createGlobalState, useStorage } from '@vueuse/core'

export const useGlobalState = createGlobalState(
  () => useStorage('vueuse-local-storage', 'initialValue'),
)
```

There are cases when the developer don't want to persist the global state in the local storage.
However, this doc page is not enough documented. The argument's doc is "A factory function to create the state", but for a beginner, we can't know to what a "factory function" refers.

This may lead to asking questions (Like I did in https://github.com/vueuse/vueuse/discussions/1952) that could be avoided if documentation were more complete.

### Suggested solution

In the docs, add an exemple where useLocalStorage is not required.

```ts
import {ref} from "vue";
import {createGlobalState} from "vueuse";

export const useReactiveGlobalState = createGlobalState(() => {
    const name = ref('banana');
    const color = ref('yellow');
    const size = ref('medium');
    return { name, color, size };
});
```

### Alternative

Consider the reader haves a good knowledge of vueuse and there is no need to add such indication in the docs

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, PR welcome to improve the docs

**Comment by HERBOD7** [comment]
@antfu can I do it?

**Comment by stefnotch** [comment]
@HERBOD7 Yes, you're definitely welcome to open a PR. Do read through the contributing guide https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md and go from there :)
