### ISSUE TITLE
createInjectionState provide should return composable result

### ISSUE THREAD

**Issue by johannes-z** [vueuse/vueuse#1997]
### Clear and concise description of the problem

When using `createInjectionState`, there is no way of using the provided data within the provider. If `useProvidingState` would return the state it provides, it can be used in the provider as well.

```ts
const [useProvideState, useState] = createInjectionState(() => {
  const myState = {}
  return myState
})

// App.vue
defineComponent({
  setup () {
    useProvideState() // I want to use myState now...
  }
})

```

### Suggested solution

In [this file](https://github.com/vueuse/vueuse/blob/main/packages/shared/createInjectionState/index.ts#L14) the code could look as follows:

```ts
  const useProvidingState = (...args: Arguments) => {
    const result = composable(...args)
    provide(key, result)
    return result
  }
```

### Alternative

My workaround for now is (my code includes automatically asserted injections):

```ts
import { createInjectionState } from '@vueuse/core'

export function assertInjection<Return> (injection: () => Return): NonNullable<Return> {
  const value = injection()
  if (value == null) {
    throw new Error('Injection was called before the value was provided by a parent.')
  }
  return value!
}

export function assertCreateInjectionState<Arguments extends Array<any>, Return> (
  composable: (...args: Arguments) => Return,
): readonly [
  useProvidingState: (...args: Arguments) => Return,
  useInjectedState: () => Return
  ] {
  let context: Return
  const [provide, inject] = createInjectionState((...args: Arguments) => {
    context = composable(...args)
    return context
  })
  return [
    (...args) => {
      provide(...args)
      return context
    },
    () => assertInjection(inject),
  ]
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Tanimodori** [comment]
Yeah I found it pretty inconvenience to use `createInjectionState` with those limitations. This issue is not completed yet.

**Comment by lsdsjy** [comment]
@xiaoxiangmoe What do you think, considering that Vue 2.7 doesn't support inject the provided state in the same component(https://github.com/vuejs/vue/issues/12678)?
