### ISSUE TITLE
Is playground broken?

### ISSUE THREAD

**Issue by jd-solanki** [vueuse/vueuse#2000]
### Describe the bug

Unable to use `useOffsetPagination` in playground for reproduction

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDgBdZhGOgGM1oUAAQTAYEmC3QoFSuoMEFSRAAPFRsgAdcwqeCSKgAXkzIAAfjUohQZgZcxAwBQACzF7MqFRgJPcIsgGbqmzSSu9xD1YK0ZD9nscJs53Sd8TWGyTlu1dWdvDyVgLlQAPmbKlTYGsm-DkRQs0QqeG+8Q2+w54zxE3zzF0iIdF1dWkKmA-huAHkjEYbmkAAFBAzGTCUVAOGoOFmFQAHJnRuHk6kQODs2zbtkA-axpE4bBFEMVQC2-RA-wAxBgNA3BFW0YAdwSaRDDQFQMADHdICQZjKUYdiEEQAE6AAL0QLiyR47ADnsFkDgOIA

### System Info

```Shell
N/A
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by curtgrimes** [comment]
I believe this is due to vueuse-playground using an older version of VueUse ([currently using 5.0.1](https://github.com/wheatjs/vueuse-playground/blob/f2f0a0bcccb57319ecb6ba07d793437dedd8f924/src/orchestrator.ts#L255)) and [`useOffsetPagination` was introduced in 7.6.0](https://github.com/vueuse/vueuse/releases/tag/v7.6.0).

I opened https://github.com/wheatjs/vueuse-playground/pull/14 for updating vueuse-playground to use the latest version of VueUse, which appears to fix the problem.
