### ISSUE TITLE
useURLSearchParams is not safe when used concurrently

### ISSUE THREAD

**Issue by mskr** [vueuse/vueuse#2006]
### Describe the bug

Two different parameters kick each other out.

```
const useA = defineStore({
  state: {
    params: useURLSearchParams()
  },
  actions: {
    test() {
      this.params.a = 'test';
    }
  }
})
```

```
const useB = defineStore({
  state: {
    params: useURLSearchParams()
  },
  actions: {
    test() {
      this.params.b = 'test';
    }
  }
})
```

```
useA().test();
useB().test();
```

Param `b` kicks out param `a` from URL!

Expected:
```
?a=test&b=test
```
i.e. the same behavior as [URLSearchParams.set](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set).

Got:
```
?b=test
```

### Reproduction

https://github.com/mskr/useUrlSearchParamsTest

### System Info

```Shell
"@vueuse/core": "^8.5.0",
"pinia": "^2.0.12",
"vue": "^3.2.31"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chaii3** [comment]
What do you expect in this case ?

**Comment by mskr** [comment]
Updated issue description with expected outcome.

**Comment by mskr** [comment]
Updated issue description with example repo

**Comment by huynl-96** [comment]
It looks like you want to control the `params` throughout all the pages for the entire app. For that case, you should only use 1 store to manage the `params` for the whole app

Dividing `params` into 2 stores means you want to treat your `params` as 2 different states, i.e. each page will have its own search params so it does not make sense to merge the `params` from page `A` to the one from page `B`

**Comment by huynl-96** [comment]
It looks like you want to control the `params` throughout all the pages for the entire app. For that case, you should only use 1 store to manage the `params` for the whole app

Dividing `params` into 2 stores means you want to treat your `params` as 2 different states, i.e. each page will have its own search params. Hence, it does not make sense to merge the `params` from page `A` to the one from page `B`

**Comment by mskr** [comment]
Thanks for looking into it. I am not sure if 2 stores means 2 different states, but that would be a pinia question and hence off topic. Actually I use multiple stores for a single page app and therefore want all `params` present at the same time. There is the danger of name collisions though. The "1 store for params" solution you proposed could be the solution. I think the the vueuse docs should mention that.

**Comment by BenJackGill** [comment]
This is a pain. I too believe setting a param `b` should not kick out param `a`.
