### ISSUE TITLE
useToFixed() return type and required digits parameter does not match native toFixed()

### ISSUE THREAD

**Issue by curtgrimes** [vueuse/vueuse#2015]
### Describe the bug

`useToFixed()`, by default, returns a `number`. However, the native `Number.prototype.toFixed()` instead [returns a type `string`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#return_value)  by default.

The native `toFixed()` also [has its digits parameter optional](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#parameters), and when it is omitted it is treated as 0. `useToFixed()` instead requires the digits parameter and will return `NaN` if it is not provided.

Should the behavior of `useToFixed()` match `Number.prototype.toFixed()` in both of these situations to make its behavior more predictable? If so I am happy to submit a PR.

### Reproduction

https://stackblitz.com/edit/vue3-script-setup-with-vite-ndx5se?file=src%2FApp.vue

### System Info

```Shell
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v17.4.0/bin/npm
  npmPackages:
    @vueuse/core: link:packages/core => 9.0.2 
    @vueuse/integrations: link:packages/integrations => 9.0.2 
    @vueuse/math: link:packages/math => 9.0.2 
    @vueuse/shared: link:packages/shared => 9.0.2 
    vue: ^3.2.37 => 3.2.37
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 1084350607** [comment]
Now, the digits param is required in useToFixed.

**Comment by 1084350607** [comment]
If don't have the digits, maybe return itself ? It looks wired if that.

**Comment by chaii3** [comment]
As I see you can get string with type: string in options. I think it's better to return 0 instead of NaN.

**Comment by chaii3** [comment]
@antfu sorry for directly pinging but can you explain please why do you think that NaN is better ?
