### ISSUE TITLE
useDark: make it possible to switch back to "auto"

### ISSUE THREAD

**Issue by denjaland** [vueuse/vueuse#2016]
### Clear and concise description of the problem

At this point, it seem we can only set isDark to true or false.  I'd like to be able to set the mode to either 'dark', 'light' or 'auto' instead, using system preferred setting, so that when I set it back to 'auto', the theme would switch automatically again.

Now, once a mode is chosen, there is no way to go back to auto.

### Suggested solution

Change the isDark implementetion would be a breaking change to active users, so either we need to break it an release it in a major, or we can add a new module useDarkMode for instance which does the same as useDark, but allows you to switch.

### Alternative

I can always remove the key from storage myself, but I'd prefer to have it built into this feature though.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
Maybe https://vueuse.org/core/useColorMode/ is what you are looking for

**Comment by denjaland** [comment]
Wow!  Completely missed it - will have a look at that one!
