### ISSUE TITLE
About Chinese translations

### ISSUE THREAD

**Issue by fonghehe** [vueuse/vueuse#2020]
### Clear and concise description of the problem

Want to provide Chinese translations of documents for easy reading by Chinese developers

### Suggested solution

want to know the author's vision and implementation of this suggestion

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
We don't have a plan to do it officially.

**Comment by fonghehe** [comment]
If there is a official plan in the later stage, you can notify me, and I intend to participate in the contribution.
