### ISSUE TITLE
`useScriptTag` child component `unload` removes parent component tag when same `src`.

### ISSUE THREAD

**Issue by shtse8** [vueuse/vueuse#2027]
### Describe the bug

`load` get the existing element
https://github.com/vueuse/vueuse/blob/8b21ca203adcc7e3bbc6e31e49d07803cb0b19b7/packages/core/useScriptTag/index.ts#L101

`unload` deletes the element
https://github.com/vueuse/vueuse/blob/8b21ca203adcc7e3bbc6e31e49d07803cb0b19b7/packages/core/useScriptTag/index.ts#L174-L176

If there is two component using the same script, the child component will remove the parent script.
if the component is self referencing, on child component unmounted, the parent script will be removed.

It can be addressed by managing a list of usages, the last unmounted removes the tag.

### Reproduction

as above.

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
    Memory: 1.58 GB / 3.83 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.1 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Firefox: 103.0
  npmPackages:
    @vueuse/components: ^9.0.2 => 9.0.2
    @vueuse/core: ^9.0.2 => 9.0.2
    @vueuse/motion: ^2.0.0-beta.12 => 2.0.0-beta.12
    @vueuse/nuxt: ^9.0.2 => 9.0.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I general I think this is something you should avoid doing. Consider wrapping it with https://vueuse.org/shared/createSharedComposable/

**Comment by shtse8** [comment]
I think it's hard to avoid. For example, consider making a `useFacebookSdk` which has `useScriptTag` inside
`App.vue` uses `logPageView()`
and there is a component like `Sharer.vue` also use `useFacebookSdk`, `send()`. They are using same script tag.

I will try to use `createdSharedComponsable`. Thanks.
