### ISSUE TITLE
[useDebounceFn]: add leading and trailing option

### ISSUE THREAD

**Issue by tiamed** [vueuse/vueuse#2029]
### Clear and concise description of the problem

Support specifying invoking on the leading/trailing edge of the timeout like [lodash](https://lodash.com/docs/#debounce)

### Suggested solution

https://github.com/xnimorz/use-debounce/blob/bb6931ceaa44f3749305d4fe6aa97a89e5430bf1/src/useDebouncedCallback.ts#L231

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Edge00** [comment]
Can someone reopen this issue ?

**Comment by VincEnterprise** [comment]
bump someone reopen this issue
