### ISSUE TITLE
useFirestore: how to retrieve Id's of documents as well?

### ISSUE THREAD

**Issue by abbjetmus** [vueuse/vueuse#2033]
### Clear and concise description of the problem

`const roles = useFirestore(collection(db, 'default-roles'));`

1. When retrieving docs from a collection that doesn't have id stored in the document can I retrieve the Id's as well?

This is how I do it without useFirestore:
```
const roles = ref<Array<Role>>([]);

const roleSubscription = onSnapshot(
  query(rolesRef, orderBy('name')),
  (snapshot) => {
    snapshot.forEach((doc) => {
      roles.value.push({
        ...doc.data(),
        id: doc.id,
      } as Role);
    });
  }
);
```

2. How to I cast the document-data to a local type?
This doesn't work.
`const roles = useFirestore(collection(db, 'default-roles')) as Array<Roles>;`

### Suggested solution

Dont have suggestion!

### Alternative

Dont have alternative!

### Additional context

Dont have context!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kiyopikko** [comment]
1. `useFirestore` also includes  `id`, the data mapping implementation is below. please re-check.

https://github.com/vueuse/vueuse/blob/main/packages/firebase/useFirestore/index.ts#L17-L30

2. `useFirestore` returns `Ref`.

```typescript
const roles = useFirestore(collection(db, 'default-roles')) as Array<Roles>; // ❌
const roles = useFirestore(collection(db, 'default-roles')) as Ref<Roles[]>; // ✅
```

or you can use `withConverter` to cast firestore data to local type like below. 

```typescript
interface User {
  id: string
  name: string
  age: number
}

const userDocRef = doc(db, 'users/userId').withConverter(getFirestoreConverter<User>())
const user = useFirestore(userDocRef) // Ref<User>

const userCollectionRef = collection(db, 'users').withConverter(getFirestoreConverter<User>())
const users = useFirestore(userCollectionRef) // Ref<User[]>

function getFirestoreConverter<T>() {
  const firestoreConverter: FirestoreDataConverter<T> = {
    fromFirestore(snapshot, options) {
      return snapshot.data(options) as T
    },
    toFirestore(model: T) {
      return model
    },
  }

  return firestoreConverter
}
```

**Comment by fcamblor** [comment]
> `useFirestore` also includes id, the data mapping implementation is below. please re-check.
> https://github.com/vueuse/vueuse/blob/main/packages/firebase/useFirestore/index.ts#L17-L30

Would it be possible to make this behaviour customizable (at least, for `id` field name)

I'm currently working with a firestore document which has an `id` field which has a different value than document's key, and this behaviour overrides my document's `id` field :(
