### ISSUE TITLE
usePreferredReducedMotion

### ISSUE THREAD

**Issue by Zhaocl1997** [vueuse/vueuse#2037]
### Clear and concise description of the problem

`prefers-reduced-motion` media query, same like `usePreferredColorScheme`

### Suggested solution

I'll try make a pr

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
PR welcome

**Comment by Zhaocl1997** [comment]
I think i can try to do the rest like `prefers-contrast` and `prefers-reduced-transparency`

**Comment by Zhaocl1997** [comment]
oh, `prefers-reduced-transparency` has no media query yet.
