### ISSUE TITLE
computedDebounced

### ISSUE THREAD

**Issue by ropez** [vueuse/vueuse#2043]
### Clear and concise description of the problem

There are `refDebounced` and `watchDebounced`, but why not `computedDebounced`?

A computed that depends on other reactive state, but only updates after that other state has stopped changing for a certain time.

Maybe there is some way to use the existing function to achieve this, but I have trouble seeing it.

Note: In my current use-case, I actually only need the computed to fire on the next update, like watch with the option `{ flush: 'post' }`.

### Suggested solution

```
const preview = computedDebounced(() => generatePreview(props.inputText), 1000);
```

Essentially the same as:

```
const preview = ref('');

watchDebounced(() => props.inputText, () => {
  preview.value = generatePreview(props.inputText);
}, { debounce: 1000 });
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tripflex** [comment]
I agree with this, not sure why it was closed as stale there's 6 others who thumbed up for this

**Comment by vad1ym** [comment]
+1, it would be nice to have this

**Comment by chriscdn** [comment]
I think `refDebounced` can be used with computed properties.

**Comment by AQS-DTheuke** [comment]
Can anyone reopen this?
