### ISSUE TITLE
useVirtualList sometimes missing elements

### ISSUE THREAD

**Issue by stefnotch** [vueuse/vueuse#2065]
### Describe the bug

With certain combinations of overscan and low element counts, it can happen that the virtual list is simply missing a few elements.

For example, I tweaked the demo to have an overscan of 1, and the demo list to have 3 elements. 
However, it only ends up displaying 2 elements, with no way of seeing the 3rd one.

### Reproduction

https://github.com/stefnotch/vueuse/blob/bug-virtual-list/packages/core/useVirtualList/demo.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 23.74 GB / 31.86 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stefnotch** [comment]
The code doesn't seem to have been changed since then, so I'd assume this bug is still present
https://github.com/vueuse/vueuse/commits/main/packages/core/useVirtualList/index.ts

**Comment by stefnotch** [comment]
Could this issue be reopened? I can't use the Vueuse virtual list due to this.

**Comment by begedin** [comment]
I can confirm this is definitely not fixed yet. I think I also see where the bug is, so I will try to submit a PR.
