### ISSUE TITLE
Bundle size impact

### ISSUE THREAD

**Issue by stephenjason89** [vueuse/vueuse#2067]
### Clear and concise description of the problem

On the docs, there are no details about the impact it has on the bundle size

### Suggested solution

Please provide a size in the docs
Preferably compressed and uncompressed
Per composable

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by darrylnoakes** [comment]
See [VueUse - Export Size](https://vueuse.org/export-size.html) for a start.

**Comment by stephenjason89** [comment]
@darrylnoakes I think it would be better if it is placed inside the composables doc instead of a separate page.
For example, I am looking at
https://vueuse.org/core/usedropzone/
But that page doesn't have the export size.

I have to go to the link you provided. And btw, there's no useDropzone there as well.

**Comment by antfu** [comment]
Pr welcome

**Comment by stephenjason89** [comment]
Thanks @antfu will try it over the weekends.

**Comment by stephenjason89** [comment]
@wheatjs Thank you for this

**Comment by antfu** [comment]
https://github.com/vueuse/vueuse/commit/42dd9015f8fe31a15c28ce721be33207b16938d7

**Comment by stephenjason89** [comment]
Hello @antfu here's my PR https://github.com/vueuse/vueuse/pull/2082
