### ISSUE TITLE
useDrauu integration not working on touchscreens

### ISSUE THREAD

**Issue by oefeningen** [vueuse/vueuse#2068]
### Describe the bug

When I try to draw with the mouse, everything is working as it should.
But when i use a touchscreen, only the first little part of my line is showing.
It even happens on the demo-page:  (https://vueuse.org/integrations/usedrauu/#demo)

As I understand, Drauu is also used in Slidev, and there the drawing on touchscreen works.  
So it's a vueuse issue?

### Reproduction

https://github.com/vueuse/vueuse/blob/main/packages/integrations/useDrauu/demo.vue

### System Info

```Shell
I've tested the issue on different systems:
Microsoft Surface, Acer chromebooks,School touchscreens, ...
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vsme** [comment]
did you solve the problem? I also encountered this problem.

**Comment by oefeningen** [comment]
It works for me when I wrap it in a div and add 'touch-action:none' to the css of that div.

**Comment by vsme** [comment]
> It works for me when I wrap it in a div and add 'touch-action:none' to the css of that div.

Thanks a lot，I set 'touch-action: none' on SVG, the program also runs.
