### ISSUE TITLE
Search missing useObjectUrl

### ISSUE THREAD

**Issue by stefnotch** [vueuse/vueuse#2070]
### Describe the bug

The search seems to be bugged, if I go to https://vueuse.org/functions.html#category=Browser and and search for `useObjectUrl` in the search bar at the very top, it does not find any results.

However, [useObjectUrl](https://vueuse.org/core/useObjectUrl/) is very much a thing that Vueuse provides.

![image](https://user-images.githubusercontent.com/10220080/183747630-2d1c1fe6-622b-4b1d-a4d5-76d7947e8eac.png)

This seems to happen to multiple results, for example I can also reproduce this with `usePreferredReducedMotion`.

![image](https://user-images.githubusercontent.com/10220080/183747515-6fdb5a56-d7a2-441e-b3ab-eb175bd8b70a.png)

If I search for something like `useMemory`, I can find the result.

![image](https://user-images.githubusercontent.com/10220080/183747057-f14fe399-516a-4c8c-866f-e159e9c0f5c4.png)

### Reproduction

https://vueuse.org/core/useMemory/

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 23.74 GB / 31.86 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stefnotch** [comment]
Still an issue, though I'll leave it up to the maintainers whether to keep this one or https://github.com/vueuse/vueuse/issues/2121 open.

**Comment by dpschen** [comment]
I searched for `useTextareaAutosize` and thought it was deleted…

**Comment by stefnotch** [comment]
@antfu I really do apologise for the ping, but any chance this issue could be put on the team's radar? It's really easy to reproduce, and makes the documentation significantly harder to use than one would like.

**Comment by stefnotch** [comment]
@antfu Pinging again, since I do think that a properly searchable documentation would be quite important.

As it stands, I'd argue that the search-bar with missing entries at the top is *counterproductive*, since it finds less than a simple `Ctrl`+`F` does. I also think that this might be a bad look for algolia as well, since their name is featured prominently on the search bar.

**Comment by luckylooke** [comment]
As fallback I am using google search to search inside vueuse docs by providing site parameter:
```
useIntersectionObserver site:vueuse.org
```

But, yes functional search should be priority as it may leads lot of users out of the trace. I have feeling that it is some bug of VuePress/VitePress because I have experienced this in several vue related documentations.

<img width="948" alt="Screenshot 2023-02-05 at 14 15 37" src="https://user-images.githubusercontent.com/3660030/216821126-a111db71-4018-4604-8536-8b7f46d6a861.png">

**Comment by stefnotch** [comment]
Woah, this issue has finally been fixed
