### ISSUE TITLE
feat(useTimeAgo): allow `requestAnimationFrame` as an update interval

### ISSUE THREAD

**Issue by darrylnoakes** [vueuse/vueuse#2072]
### Clear and concise description of the problem

I was wondering about using `requestAnimationFrame` as an interval for `useTimeAgo`. Is there any specific reason that it is not allowed (the interval is typed as `number`) despite `useNow` supporting it?
I doubt it would be any use, but I would like to know the reasoning behind it.

### Suggested solution

Allow specifying `requestAnimationFrame` as an update interval for `useTimeAgo`.

### Alternative

Do nothing. Such a rapid update period will rarely be needed.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
`useTimeAgo` only needs very low accuracy of the time, using `requestAnimationFrame` would be too costly and would increase the bundle size.

**Comment by darrylnoakes** [comment]
That's what I thought, but wanted to be clear 👍
