### ISSUE TITLE
Add a new Function `useElement`

### ISSUE THREAD

**Issue by Cheng-DX** [vueuse/vueuse#2078]
### Clear and concise description of the problem

`useElement` should able to get an element ref by CSS selector

### Suggested solution

useage: 
```ts
const { element } = useElement('#test')
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chaii3** [comment]
Can you use ref templates for it ?

**Comment by Cheng-DX** [comment]
> Can you use ref templates for it ?

Thanks for your repley. 
In `useElement`, what I want is a common tool to get any element ref in the document, but template ref can only get those in this component. 
I need this functionality because sometimes I need to get elements that are outside the component, for example I need to get the position of some dom.
I don't know if such a function is necessary, it is just I used it when writing a component  so that I opened such an issue.

**Comment by 1084350607** [comment]
Why not use querySelector,  if you use like this : useElement('#test')

**Comment by Cheng-DX** [comment]
> Why not use querySelector, if you use like this : useElement('#test')

I wanna got a `null` when element has been removed, a hook will be better.

**Comment by chaii3** [comment]
> > Why not use querySelector, if you use like this : useElement('#test')
> 
> 
> 
> I wanna got a `null` when element has been removed, a hook will be better.

I'm not sure that selecting element from other component is vue way. It might create some problems. I might be wrong.
