### ISSUE TITLE
`useElementSize` returns wrong size for SVG element

### ISSUE THREAD

**Issue by UnluckyNinja** [vueuse/vueuse#2084]
### Describe the bug

I encountered this bug when trying to achieve panning effect on SVG element (like a draggable map).
Then I notice `useElementSize` returns its content size rather than the element's own size.

`useElementBounding` works as expected.

https://vueuse.org/core/useElementSize/ (for convenience)

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAnJMAAzk9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKnFeDArGQMPkGWhshQCKRIBRgxGYwEQmms2GLLZHMQJPJlI2iG2e0OAF1mEY6AZDWhQABBMBgSYLdCgVIagwQVKAxQAcRUnloNmkLmc0kqSAzcv8NwAov6CEqAXQAF6INAAHWwAB4qNkVNYjABeGssYjwADqFVDiA4nZUyFC-o7IEidCo0l0aBqwQoMyV6c7AD46yoVPXkN2W4h253d-Bh1OZ7oJwBGMlksCbYcXzvX2-3kAqYiwyIAIVYmwnZJUADnxUZ9103LcIPrOg8AQNJWwnY8AEkYKQU9p1nCdGhvO9h02IJsBgNBdHgztTTReY6AgSYwFjbhdAlGgOGtOYsLJTZWOo7ATzfYYN3Mbc7m7Pj62GJtiGE8phLEvit2Q2CdFqepW0HGxuHsWt+KgvA-GQLgJzI80PyomjoEQeiDEY5jhlY9ib047jhNE7IpOc8DjxHStqxUYBgGPcsqwOA46xE6SVGC6TwOg+SzBHPdtSrecfKQlDEH8xBAuCpzxPC1z+OSCAB3qeKvJ8-LCrSjKGyyiSOBc7L+OPH9+CbLjEt87smupXxJjPWdAsYbz2vgTqWqmXREDoeA+kqkLnJUZ5BWkIhoM1DgM2AVsDhqDhZhUAByBY9rrFa6nWgtEGLNMy08ga8Uu0tpBG3wVC2owdrwfa7Rudk6kQI7sDrZdR1ivw233IxtHsQH5GB5L5LB1tIeh7BYe7PsCrAQcVARg8kYB2wYYzPzPOx877vTNLtGPKGCZRonuzkpA0tJu6SwpzyqYZlKaaBjMysxjhmbB1mrukSnj3RwqaeR1HhvYLquJZos2aVJ6uM5+B7HpQKgA

### System Info

```Shell
VueUse playground, browser MS Edge 104.0.1293.47
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JayMeDotDot** [comment]
Maybe the `height` or the `width` attribute applied to the <svg> tag only means the size of an SVG viewport, not the size of an element.
And the [Element.getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) method returns a [DOMRect](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect) object providing information about the size of an element and its position relative to the [viewport](https://developer.mozilla.org/en-US/docs/Glossary/Viewport). 

So the `useElementBounding` gets the size of an SVG viewport, while the `useElementSize` gets the real size of an SVG. 

Maybe this is why we get different values.
