### ISSUE TITLE
Left scroll bar not working in top 

### ISSUE THREAD

**Issue by Saeed-Paris** [vueuse/vueuse#2086]
### Describe the bug

in all functions page u cant select the left scroll bar. i edit it with z-index and it worked.

### Reproduction

https://vueuse.org/functions.html

### System Info

```Shell
.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by curtgrimes** [comment]
This looks like an issue with VitePress instead of VueUse. This should fix it: https://github.com/vuejs/vitepress/pull/1168
