### ISSUE TITLE
ssr-plugin.js causing plugin not wrapped warning with nuxt3

### ISSUE THREAD

**Issue by v-limc** [vueuse/vueuse#2094]
### Describe the bug

Using `@vueuse/nuxt` with `nuxt@3.0.0-rc.7` will get an warning like this:

```
[warn] [nuxt] You are using a plugin that has not been wrapped in `defineNuxtPlugin`. It is advised to wrap your plugins 
as in the future this may enable enhancements: () => { }
```

I think it's because the [ssr-plugin.js](https://github.com/vueuse/vueuse/blob/main/packages/nuxt/ssr-plugin.mjs#L40) is not constructed with `defineNuxtModule`, thus not being exported as a module with the essential information passing the check here in `nuxt.mjs`:

```javascript
export function normalizePlugins(_plugins) {
  // ...
    if (!isNuxtPlugin(plugin)) {
      unwrappedPlugins.push(plugin);
    }
    return plugin;
  // ...
  if (process.dev && unwrappedPlugins.length) {
    console.warn("[warn] [nuxt] You are using a plugin that has not been wrapped in `defineNuxtPlugin`. It is advised to wrap your plugins as in the future this may enable enhancements:", unwrappedPlugins.map((p) => p.name || p).join(","));
  }
  return plugins;
}
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-nbhqcu

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 2.56 GB / 15.75 GB
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.17.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vueuse/nuxt: ^9.1.0 => 9.1.0
    nuxt: ^3.0.0-rc.7 => 3.0.0-rc.7
    vue: ^3.2.37 => 3.2.37
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by itsmnthn** [comment]
I get the same warning

**Comment by itpropro** [comment]
Same here

**Comment by NoahCardoza** [comment]
Third this

**Comment by wangrongding** [comment]
Same here😿

**Comment by Developer27149** [comment]
Same here

**Comment by Foddie2** [comment]
Any soluions to this issue?

**Comment by quartzar** [comment]
Same here

**Comment by Foddie2** [comment]
Any solution to this issue

**Comment by SouleyCat** [comment]
same issue here
