### ISSUE TITLE
WebSocket: Wrong implementation of heartbeat

### ISSUE THREAD

**Issue by miili** [vueuse/vueuse#2096]
### Describe the bug

The heartbeat is currently sending a `'ping'`, this ought to be `0x9` and pong is `0xA`.

Also I do not see the acknowledgement of the Pong. I can work on this if required.

See the reference on MDN:
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#pings_and_pongs_the_heartbeat_of_websockets

### Reproduction

https://github.com/vueuse/vueuse/blob/dc3ebe80bc61ee56004fdcd417cb234ee749e41e/packages/core/useWebSocket/index.ts#L235

### System Info

```Shell
generic
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by miili** [comment]
@antfu ping, I think this should be high prio.

**Comment by ilyaliao** [comment]
Closed via #2170
