### ISSUE TITLE
usedraggable is not smooth when cursor loses element

### ISSUE THREAD

**Issue by tcampbPPU** [vueuse/vueuse#2102]
### Describe the bug

The issue I am facing is kind of difficult to explain but if/when the cursor loses the element you are trying to drag it become impossible to drag it. You need to make sure the cursor is always over the element when you are moving, which sometimes means you must move this element pretty slow. 

I only see this issue when I use it when it has a parent element boundary (which I found from [here](https://github.com/vueuse/vueuse/issues/1014)).

In my use case I need drag an element over a iframe (like in the example I provided). In that example you will notice it more when you click `"Open in New Tab"` for some reason I was able to replicate this more on a larger screen.

![image](https://user-images.githubusercontent.com/25044744/185505043-7b47661f-447f-4185-b43b-ffe3e629d5ca.png)

https://user-images.githubusercontent.com/25044744/185505147-f7aa7363-816b-472f-8ab1-1a803235880c.mp4

Any suggestions on what I need to do in order to get a smoother dragging effect?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-kndiip?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 5.18 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 17.91 GB / 23.35 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.16.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 104.1.42.88
    Firefox: 103.0.2
  npmPackages:
    @vueuse/core: ^9.1.0 => 9.1.0 
    vue: ^3.2.31 => 3.2.37
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stefnotch** [comment]
I can't seem to reproduce this. (Firefox and Microsoft Edge on Windows 10)

This might be a stupid question, but does your mouse button definitely stay held down?

**Comment by tcampbPPU** [comment]
Yup my mouse button is still for sure held down.

When you where trying to replicate this did you open the  stack blitz example I posted in full screen?

**Comment by stefnotch** [comment]
I see, maybe Linux handles mouse events differently? That's one of the few explanations that I could think of at the moment.

Here is me trying it out, notice how I can drag it as fast as I like, and the element will keep following the mouse. If I drag it very quickly, it will trail behind the mouse (and the cursor will look different). But, the element does catch up and can continuously be dragged.
![video](https://user-images.githubusercontent.com/10220080/185736141-8f979e2e-1ce9-48c4-bb25-5222fcb99759.mp4)

**Comment by tcampbPPU** [comment]
I don't think it's OS specific. I also have a Mac and can repeat the issue.

**Comment by azaleta** [comment]
the problem isiframe is listening to point events

I think you can avoid this by using css setting to get smooth move.
But this will make scrolling of ifarme disabled as well.

```
<style scoped>
// add this
iframe {
  pointer-events: none;
}
</style>
```
further complex setting is needed according to your usecase

**Comment by tcampbPPU** [comment]
> the problem is iframe is listening to point events

Thanks! Yea I ended up needing to add this and also set dragging classes to work abound that scroll issue too.
