### ISSUE TITLE
ESLint error `@typescript-eslint/unbound-method` on `useRefHistory`

### ISSUE THREAD

**Issue by seahindeniz** [vueuse/vueuse#2110]
### Describe the bug

When I destruct the returned object from `useRefHistory()`, ESLint gives an error 
![image](https://user-images.githubusercontent.com/5789670/185799770-5ea2a91a-ed36-428f-af78-2855fd41ae66.png)

I believe this issue can be solved by changing following lines
https://github.com/vueuse/vueuse/blob/1eb83c41bb1ca6e6c8ee61c46ce9dbca7ab1613f/packages/core/useManualRefHistory/index.ts#L79-L99

into this, for example:
```ts
undo: () => void;
```

As it is explained in the [TypeScript ESLint docs](https://typescript-eslint.io/rules/unbound-method/), the rule considers destructing a method could potentially cause `this` related issues. Since methods don't preserve `this` bound and the clear solution is to use properties with arrow expression instead.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-9fi1xu?file=src/main.ts

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 109.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Chrome Canary: 107.0.5252.0
    Safari: 15.5
  npmPackages:
    @vueuse/core: ^9.1.0 => 9.1.0 
    vue: ^3.2.37 => 3.2.37
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
PR welcome!
