### ISSUE TITLE
useAxios 如何取消请求

### ISSUE THREAD

**Issue by jahnli** [vueuse/vueuse#2116]
### Clear and concise description of the problem

useAxios 如何取消请求

### Suggested solution

useAxios 如何取消请求

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by azaleta** [comment]
https://github.com/vueuse/vueuse/blob/main/packages/integrations/useAxios/index.ts#L41
