### ISSUE TITLE
Vueuse.org Algolia CMD+K search has old data. 

### ISSUE THREAD

**Issue by andreylysenko** [vueuse/vueuse#2121]
### Describe the bug

Vueuse.org Algolia search does not find new functions. Try search "useArrayMap"  no results.

### Reproduction

vueuse.org

### System Info

```Shell
Vueuse.org / Web
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by orionna319** [comment]
Do you need to re-crawl the page information in the DocSearch administration backend?

**Comment by stefnotch** [comment]
That would explain https://github.com/vueuse/vueuse/issues/2070

**Comment by dpschen** [comment]
This is still true. I was searching for `useTextareaAutosize`

**Comment by stefnotch** [comment]
Seems to have been fixed
