### ISSUE TITLE
Unoicon dynamic assignment in TS cannot be displayed

### ISSUE THREAD

**Issue by muchenfine** [vueuse/vueuse#2126]
### Describe the bug

Unoicon dynamic assignment in TS cannot be displayed，Color also fails to take effect

```js
const renderIcon = (icon: string,color:string) => {
  return () => {
    return h('i', { class: `i-carbon:${icon} text-20px text-${color}` });
  };
};

renderIcon('logout','red')
```

### Reproduction

*

### System Info

```Shell
vue3 ts vite3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
https://github.com/unocss/unocss#scanning
