### ISSUE TITLE
[Feature] useConcatenate

### ISSUE THREAD

**Issue by Zehir** [vueuse/vueuse#2134]
### Clear and concise description of the problem

In my project I found myself to concatenate a quite large amount of string and found myself doing this multiple times;
```typescript
const path = computed(() => corsProxy.value + gameURL.value)
```

### Suggested solution

Like the `useSum` we could have a `useConcatenate` or allow `useToString` to have multiple params.

### Alternative

There is really other alternative than the one I wrote at the start of this feature request.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Bobakanoosh** [comment]
I'd imagine usage for this would support all of the following
```ts
useConcatenate("string1", refString.value, refString);

const someRefArray = ref(["string1", refString.value, refString]);
useConcatenate(someRefArray)
```

I'd be willing to add this if the above API is approved

**Comment by Zehir** [comment]
Does he would / should only accept strings and you need to use `useToString` for the other ones or cast anything to string ?

**Comment by Bobakanoosh** [comment]
It could use the same thing that `useToString` does internally, so that you can do:
```ts
useConcatenate([[1,2,3], () => 'myFunctionResult']);
```
or anything else that `useToString` supports.

**Comment by Zehir** [comment]
Something like this ?
```typescript
export function useToString(
  ...values: MaybeComputedRef<unknown>[],
): ComputedRef<string> {
  return useArrayReduce(values, (fullStr = '', str) => fullStr += `/${resolveUnref(str)}`)
}
```
