### ISSUE TITLE
useBreakpoints - new methods?

### ISSUE THREAD

**Issue by Kcko** [vueuse/vueuse#2144]
### Clear and concise description of the problem

I see list of available methods - https://vueuse.org/core/usebreakpoints , its OK. 
But from my logic in my code, i need methods like greaterOrEqual(someBreakpoint) or smallerOrEqual(someBreakpoint)

Because when i have this code 
```      <responsive-teleport to="#TransportList__BuyMobile-{$transport->id}" breakpoint="lg">```
Nobody knows what this means <= lg or < lg 

in my TW css file i have 
```
.some-element {  
@apply hidden lg:block
}
```

And logic for first look is not the same.

It makes sense? Or another solution or procedure?
Thx

PS. My temp solution 
```
     <responsive-teleport 
                        to="#TransportList__BuyMobile-{$transport->id}" 
                        :breakpoint-rule="{
                            rule: 'smaller',
                            breakpoint: 'lg'
                        }">
```

### Suggested solution

Add two new methods 
- greaterOrEqual
- smallerOrEqual

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JessicaSachs** [comment]
Should this be closed?

**Comment by Kcko** [comment]
Great! Thx a lot.
