### ISSUE TITLE
new useSuspense

### ISSUE THREAD

**Issue by onmax** [vueuse/vueuse#2145]
### Clear and concise description of the problem

Vue 3 has a Suspense component that allows developers to divide the success and error screen  better in the templates. I would like to have something similar in a composable.

### Suggested solution

The composable will have the following arguments:
1. The function to execute. Lets call it `fn`
2. `onSuccess` callback. It will be triggered, if `fn` worked successfully
3. `onError` callback. It will be triggered, if `fn` didn't work
4. Other params like `delayBeforeCb` before running the callbacks. 

The composable would work as follows:
1. Declare `executing` ref
2. Declare `executeFn` function
3. Return both variables
4. Developer can trigger `executeFn` and check the status with `executing` flag

This is my current composable:

```ts
import { sleep } from "@/lib/util" // This should be replaced I guess
import { ref } from "vue"

export interface UseSuspenseOptions {
    fn: Function,
    onSuccess: () => void,
    onError?: (params: { error: string }) => void,
    delayBeforeCb?: number
}

export function useSuspense({ onSuccess, onError, fn, delayBeforeCb }: UseSuspenseOptions) {
    const executing = ref(false)

    async function executeFn() {
        executing.value = true
        const error = await fn()
        executing.value = false

        if (delayBeforeCb) {
            await sleep(delayBeforeCb)
        }

       // I know this is ugly, the way I handle errors, but it works
        if (!error) {
            onSuccess()
        } else if (onError) {
            onError({ error })
        }
    }

    return {
        executeFn,
        executing
    }
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
https://vueuse.org/core/useasyncstate ?

**Comment by onmax** [comment]
Oh sorry, I miss it. I will use it then. When I read it the first time I don't know why I thought it could not solve the problem.
