### ISSUE TITLE
Failed to generate the QR code asynchronously

### ISSUE THREAD

**Issue by quanzaiyu** [vueuse/vueuse#2147]
### Describe the bug

I need to get the data from the request. Simulate the request using setTimeout:

```vue
<script setup>
import { useQRCode } from '@vueuse/integrations/useQRCode'
let text = ref('123456')
let qrcode = ref('')
setTimeout(() => {
  qrcode.value = useQRCode(text)
}, 200)
</script>

<template>
  <div v-if="qrcode">
    <img :src="qrcode" alt="QR Code" class="w-full h-full p-0" />
    <div>{{ text }}</div>
  </div>
</template>
```

![image](https://user-images.githubusercontent.com/13745132/187574036-0af9143b-fa43-4a34-9e6a-c9e399827c27.png)

But generate failure:

![image](https://user-images.githubusercontent.com/13745132/187574397-5aa31fae-bc77-458e-9a0b-0883f694ba0a.png)

How should I use it.

### Reproduction

https://qiniu.shidiankeji.com/frontend/vue/vueuse.vue

### System Info

```Shell
❯ npx envinfo --system --npmPackages '{vue,@vueuse/*}' --binaries --browsers
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: Windows 10 10.0.22622
    CPU: (16) x64 Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
    Memory: 5.96 GB / 15.94 GB
  Binaries:
    Node: 16.17.0 - D:\Software\Scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Software\Scoop\apps\nvm\current\nodejs\nodejs\yarn.CMD
    npm: 8.15.0 - D:\Software\Scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.586.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/components: ^8.9.4 => 8.9.4
    @vueuse/core: ^8.9.4 => 8.9.4
    @vueuse/integrations: ^9.0.0 => 9.0.0
    vue: ^3.2.33 => 3.2.37
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
https://vueuse.org/integrations/useqrcode/#usage
QRCode support ref, so when the ref change image will change as well.
like
```
const text = ref('')
const qrcode = useQRCode(text)
setTimeout(() => {
  text.value = 'from other request'
}, 2000)
```
