### ISSUE TITLE
useAxios Query parameters cannot be changed dynamically

### ISSUE THREAD

**Issue by muchenfine** [vueuse/vueuse#2149]
### Describe the bug

```

const form = ref({
  module: null
});

const {
  data:,
  isLoading,
  execute:
} = useAxios(api, {
  size: 10,
  page: 1,
  ...form.value
});
execute();

<template>
  <div id="button">
    {{ form }}
    <button @click="execute()">sd</button>
  </div>
</template>
```

When I call execute again, the request parameters are still {size: 10,page: 1}，
How should I get {size: 10,page: 1,module:' XXXX '}

### Reproduction

https://github.com/vueuse/vueuse/blob/main/packages/integrations/useAxios/demo.vue

### System Info

```Shell
win10,vueuse last
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
https://github.com/vueuse/vueuse/blob/main/packages/integrations/useAxios/index.ts#L171
add config to the execute should be ok

**Comment by azaleta** [comment]
this is not same config, I think
config is changed if your  form.value is changed. (and also config can't automatic updated when you change form.)

A ref here:
https://github.com/vueuse/vueuse/issues/1347

**Comment by azaleta** [comment]
As I said, config can't automatic updated when you change form
There is no reactive here.
UseAxios instance is created with config and then freeze.

Only way to refresh this is passing config(just the part you need) again.
```
<button @click="execute(undefined, {params: { module: query.module }})">get</button>
```

Also,this `undifined` thing should be removed. 
I prefer `execute({params: { module: query.module }})`

**Comment by azaleta** [comment]
umm...
`There is no reactive here.` -> This is not your problem.This is the design thing.
`config` is not ref, so it will not be automaticly changed like reactive. (even through you want to use a ref obj as config)
You must trigger update manually by passing config in excute.
![image](https://user-images.githubusercontent.com/22554452/187871706-71c6d35a-9ea1-4b4f-a3ce-822c866e906b.png)

**Comment by jahnli** [comment]
Instead of relying on reactive or re-passed configurations, why not re-read its own configuration as a function when executing execute, which is mostly built-in in real scenarios
