### ISSUE TITLE
How about adding a method to dispose useInfiniteScroll

### ISSUE THREAD

**Issue by MeFelixWang** [vueuse/vueuse#2153]
### Clear and concise description of the problem

When using `<keep-alive>` to cache the component, useInfiniteScroll will keep calling even though the component is diactivated.

This may cause some error.

So, how about adding a method to dispose?

### Suggested solution

Add a method to dispose useInfiniteScroll.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Lehakos** [comment]
I would to see such method too!
