### ISSUE TITLE
useFetch.execute is not the same as bare useFetch

### ISSUE THREAD

**Issue by Glandos** [vueuse/vueuse#2154]
### Describe the bug

When awaiting from `useFetch`, the result is always fully finished.
If we await for `useFetch("/path", {immediate:false}).execute()`, the result is not fully finished.

This is probably caused by the `waitUntilFinished` in the `then()` implementation, that is not available in the `execute()`.

But for now, it's seems not possible to have a deferred `useFetch` and wait for its completion (e.g. in a store).

### Reproduction

https://codepen.io/glandos/pen/xxjxxWE

### System Info

```Shell
N/A
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
https://github.com/vueuse/vueuse/blob/main/packages/core/useFetch/index.ts#L392

https://github.com/vueuse/vueuse/blob/main/packages/integrations/useAxios/index.ts#L186

These 2 execute have different return type.
Is it intended to design like this? @antfu

Change execute func of useFetch should resolve this.

**Comment by Glandos** [comment]
This is still waiting for a fix

**Comment by Glandos** [comment]
This is still waiting for a fix
