### ISSUE TITLE
useElementSize returns wrong size when using { box: 'border-box' }

### ISSUE THREAD

**Issue by fmgrafikdesign** [vueuse/vueuse#2158]
### Describe the bug

`useElementSize` seems to ignore the provided option` { box: 'border-box' }` and instead still uses the content-box of the element.

The example shows how the lower box reports the same size as the upper one, even though it should be reporting the border-box sizing, which would be 250 x 200 (checked via chrome inspector).

### Reproduction

https://stackblitz.com/edit/vitejs-vite-fxnszl/?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 14.48 GB / 31.93 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.25)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Agility6** [comment]
This PR seems to solve your problem?🤔 #2143

**Comment by fmgrafikdesign** [comment]
Very nice, thank you! Hope it gets merged soon. 👍 Kinda confusing the documentation advertises a feature that is not actually implemented yet. :/
