### ISSUE TITLE
error when use ref in Vue component instance(should use unrefElement)

### ISSUE THREAD

**Issue by mymx2** [vueuse/vueuse#2160]
### Describe the bug

error when use ref in Vue component instance. same error in
// 1. useElementSize
// 2. useVirtualList
// 3. useScrollLock
// 4. usePointerSwipe
// 5. useInfiniteScroll
// 6. useElementVisibility
// 7. useDraggable
fix: use unrefElement rather than resolveUnref
![image](https://user-images.githubusercontent.com/32814920/188263067-f37ab029-9b9b-4b22-add2-4760bd5b2192.png)

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAnJMAAzk9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKnFeDArGQMPkGWhshQCKRIBRgxGYwEQmms2GLLZHMQJPJlI2iG2e0OAF1mEY6AZDWhQABBMBgSYLdCgVIagwQVJEAA8VGyAB1zCp4JIqABeFMgAB+NSiFBmBgzEDAFAALHm0yoVGBY9xcyAZkqbNISx3EPVgrRkF32xxa+ndC3xNYbCP67UlS28PJWNOVAA+OsqBPiurJ3CpFTWIwt6SVJDSPMqWOlTwtgAa57QxEM5Bbm3PwzX6c3rG3ZjjaUv155gAmvej4GM+eYhG+H4JsMybECuzyCtIRB0BqdTSCowD7ogJgHDUHCzCoADkCzEWmaGahwmHYXiACy7A3Iw-g3AAov6BBKoodDaqUfrBGE+FGIReAkXaNzsnUiDkVk6HUWq34cDuf4EURxGTMMW5Kb+qThuQMlpm2yA0SomzMYJKjZixiAMXi2j2GmaajCoPaEfUkS6DY1k4SYZhgioWKatgHamNgxkQLYiCTCoeQEC5HBuaFTnDCoACM0V4uxtAdgCdAAF6IMlKiNBlNzcdRpCGCUxlFe0pWIACEgSgYRSsLARVVvVAAKrBmKkHAApEUiFdgzkAKz1QAktgvpZKkjWERERUAGz1VlnHSNxvH8aERUAOz1WoFTwPAEClP6RW+psaDefwB7rSFFTSJ59TPRFOFsAYHiZAejm2PIxnxCeiCYVZB7aNgpARA5-1hZhx4cKek3IFtZT+pZ1kPVxPFlDtITaAjp72PSzBacpukRoGIDRo2f6JvB66ztI86LsupTwC2QTwH0FBjWSZJuJUMBoFQQu8-zy5GP6mwtoWpbLqkmzM3m3BDsuYAto0bPbj2LaEfwNBUCOH71gmyCQOYivKyAVabAYeYrsA2FgaoBwHLB5sRSbG6e5bbrW8gomixwwtczzxL84LIdoN40ACeL554EeFBayAK62ZCTsXmdngqG7HsWzBcHZIhzATr8RA0LNiBdYRgzaMA64AQYN0AtIkjYPAjDri7iA3QAcqQeBXhw3fYAcxNuwcQA

### System Info

```Shell
Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
  npmPackages:
    @vueuse/core: workspace:* => 9.1.1
    @vueuse/integrations: workspace:* => 9.1.1
    @vueuse/math: workspace:* => 9.1.1
    @vueuse/shared: workspace:* => 9.1.1
    vue: ^3.2.37 => 3.2.37
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Reproduced in `useElementVisibility`, could you please provide more cases about the functions you mentioned.
