### ISSUE TITLE
[vueuse/rxjs] Add 'fromWatcher' to create an observable from a Vue watcher

### ISSUE THREAD

**Issue by JasonLandbridge** [vueuse/vueuse#2162]
### Clear and concise description of the problem

Hi there,

I'm currently migrating from [vuejs/vue-rx](https://github.com/vuejs/vue-rx/) to [vueuse/rxjs](https://github.com/vueuse/vueuse/tree/main/packages/rxjs) and I'm looking for something similair to [$watchAsObservable](https://github.com/vuejs/vue-rx/blob/638e555addb67deaa18343b6e1d18328296d7d23/src/methods/watchAsObservable.js). I can't seem to make it work with [from/fromEvent](https://vueuse.org/rxjs/from/#from-fromevent)

### Suggested solution

We could add a new `fromWatcher` [here](https://github.com/vueuse/vueuse/blob/main/packages/rxjs/from/index.ts) which would take the name of a watchable field/prop and create an observable from it that fires on each value change.

```javascript
const vm = new Vue({
  data: {
    someValue: 1
  },
  subscriptions () {
    useSubscription(fromWatcher('someValue')
       .subscribe(({ newValue, oldValue }) => console.log('stream value', newValue, oldValue)));
  }
})





```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JasonLandbridge** [comment]
Bump

**Comment by Voltra** [comment]
I think #3453 addresses this in a way, and it has been merged
