### ISSUE TITLE
nuxt v3.0.0-rc.9 autoImports hook was deprecated.

### ISSUE THREAD

**Issue by keymasroy** [vueuse/vueuse#2173]
### Clear and concise description of the problem

In nuxt v3.0.0-rc.9, autoImports option and hooks is deprecated and renamed to imports.
https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.9

but @vueuse/nuxt/index.mjs (version 9.1.1), use autoImports:sources yet.

### Suggested solution

plase change hook name to autoImports:sources  to imports:sources..
Thanks..

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
https://github.com/vueuse/vueuse/pull/2166
