### ISSUE TITLE
[useScroll]: arrivedState should update if the container dimensions change

### ISSUE THREAD

**Issue by onmax** [vueuse/vueuse#2174]
### Describe the bug

Lets say you scroll a container and stop reach the bottom. 
Using `useScroll` you would have this values in `arrivedState`

```ts
arrivedState = {
   left: false,
   right: false,
   top: false,
   bottom: true,
}
```

Note that `arrivedState.bottom` is `true` because we reached the end of the container.

But, now you add more items in the container, making the container bigger and therefore `arrivedState.bottom` should update.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-lwa9ge?file=src/App.vue

### System Info

```Shell
Not relevant
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jiblett1000** [comment]
I believe this is related to my issue as well. I am using `arrivedState.bottom` on Window to show my navigation on page bottom. However, the problem is that the Window height is being calculated when the Chrome address bar is visible but when I reach page bottom, the address bar is hidden and this causes a discrepancy somehow. If I offset the bottom of useScroll by the address bar height (56px), it works as intended and shows my navigation.

**Comment by Amaurgit** [comment]
Same here, on client resizing, the arrivedState doesn't update. I have arrivedState = true with no available scroll on the container :)

**Comment by robbieaverill** [comment]
This issue would possibly be fixed by https://github.com/vueuse/vueuse/pull/4655

**Comment by robbieaverill** [comment]
A workaround is to call `measure()` whenever your content changes, e.g.

```vue
const { arrivedState, measure } = useScroll(myRef)

watch(isContainerExpanded, () => {
  // await nextTick() <-- may be required
  measure()
})
```
