### ISSUE TITLE
Can't use vueuse/nuxt@9.2.0 in nuxt@2.15.8

### ISSUE THREAD

**Issue by vahid-bagh3ri** [vueuse/vueuse#2176]
### Describe the bug

Can't use in production:
peer nuxt@"^3.0.0-rc.9" from @vueuse/nuxt@9.2.0

### Reproduction

didnt provide Reproduction

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 3.72 GB / 15.78 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.23.0-20220130.1630 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by danielroe** [comment]
Yes, I think we should do that 👍

**Comment by AndrewBogdanovTSS** [comment]
@antfu Is this what's causing autoImport to fail from vueuse/core at the moment when using with rc.9 ?

**Comment by danielroe** [comment]
This should now work with latest Bridge: https://stackblitz.com/edit/github-8bqrdc?file=nuxt.config.ts,pages%2Findex.vue

**Comment by AndrewBogdanovTSS** [comment]
It works, thank you
