### ISSUE TITLE
Mention «close» function in the «Usage» section of «onClickOutside» documentation

### ISSUE THREAD

**Issue by gssvv** [vueuse/vueuse#2188]
### Clear and concise description of the problem

Right now `onClickOutside` function returns [`close`](https://github.com/vueuse/vueuse/blob/main/packages/core/onClickOutside/index.ts#L91) that seems to remove all related listeners, but documentation does not mention it. 
Therefore, It's not evident that there's such functionality.

### Suggested solution

Show functionality in the [usage example](https://vueuse.org/core/onclickoutside/#usage).

For example, instead of:
```js
  setup() {
    const target = ref(null)

    onClickOutside(target, (event) => console.log(event))

    return { target }
  }
```
Describe it as:
```js
  setup() {
    const target = ref(null)

    const stop = onClickOutside(target, (event) => console.log(event))

    return { target, stop }
  }
```

It might also be a good idea to describe it more, but I think it should be mentioned at least in the way I showed it above.

### Additional context

I would like to make this change if one of the members confirms it's needed.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
56ce7e63b00c5b2375890f2aee924cd090d2f1e2
