### ISSUE TITLE
onClickOutside: listen only to mousedown event for ignore elements 

### ISSUE THREAD

**Issue by kduvignau** [vueuse/vueuse#2196]
### Describe the bug

Hi! 👋

If I click inside an ignore element  then release my mouse outside of it and the target, the handler function is called.

In a previous version of vueUse, it was possible to specifiy which events should trigger the handler ( see https://github.com/vueuse/vueuse/pull/508/commits/e080ec61f8b99527f45458b4d7d9de3ee378f3b8)

I'm not sure if this was also applied to ignore elements, but the option was then removed in this commit https://github.com/vueuse/vueuse/commit/2ff6ca9b0b1cf3f3ea885c9130d3b417f680b5cd

Why the option has been removed? Could it be possible to bring it back? How can I do to not trigger the handler function?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jkw1v5/?file=src%2FApp.vue

### System Info

```Shell
vueuse stackblitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kduvignau** [comment]
@sibbng It looks like you are the expert of the onClickOutside function 😁

**Comment by sibbng** [comment]
Relying only on the `click` event was fixing a bunch of issues and consistency problems for us. The issue you mention could be resolved easily by moving this part 👇

https://github.com/vueuse/vueuse/blob/56ce7e63b00c5b2375890f2aee924cd090d2f1e2/packages/core/onClickOutside/index.ts#L57-L63

inside here 👇
https://github.com/vueuse/vueuse/blob/56ce7e63b00c5b2375890f2aee924cd090d2f1e2/packages/core/onClickOutside/index.ts#L70-L73

`shouldListen.value` should be set to `false` if it matches any ignored elements.

PRs welcome 🤞
