### ISSUE TITLE
关于 useAxios, 强制类型 AxiosRequestConfig<D> 而不是 <any>

### ISSUE THREAD

**Issue by KeJunMao** [vueuse/vueuse#2204]
### Clear and concise description of the problem

useAxios 目前仅支持一个泛型参数作为response类型，希望可以为AxiosRequestConfig也新增一个类型参数来定义data属性的类型

### Suggested solution

```ts
interface StrictUseAxiosReturn<T, D> extends UseAxiosReturn<T> {
  /**
   * Manually call the axios request
   */
  execute: (
    url?: string | AxiosRequestConfig<D>,
    config?: AxiosRequestConfig<D>
  ) => PromiseLike<StrictUseAxiosReturn<T, D>>;
}
declare function useAxios<T = any, D = any>(
  url: string,
  config?: AxiosRequestConfig,
  options?: UseAxiosOptions
): StrictUseAxiosReturn<T, D> & PromiseLike<StrictUseAxiosReturn<T, D>>;
```
我是ts菜鸟，也许可以解决？

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by KeJunMao** [comment]
@azaleta 谢谢你，可以的话，都加了个 D 了，能再加个范型 E 用于给error指定类型吗

**Comment by azaleta** [comment]
#2248 
I don't think it is E
it shoud be D

**Comment by sxzz** [comment]
Fixed via #2248
