### ISSUE TITLE
useFocusWithin gives incorrect values

### ISSUE THREAD

**Issue by 94726** [vueuse/vueuse#2214]
### Describe the bug

When changing focus between children of the referenced element, `focused` will always be set to `false` before being set back to `true`. This is not what I expect to happen, as the focus within the referenced element never gets lost. 

 Because of this behavior, following statement from the docs is incorrect:
>  It is meant to match the behavior of the :focus-within CSS pseudo-class.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ifsyhn/?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 4.61 GB / 7.74 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
 Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
 npmPackages:
    @vueuse/core: ^8.7.5 => 8.9.4 
    vue: ^3.2.25 => 3.2.37
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MorevM** [comment]
Just ran into this yesterday, but decided not to bump because it annoys everyone who subscribes. 
Writing now since it still an issue and shouldn't be closed.
