### ISSUE TITLE
useDraggable在网页缩放中拖动位置偏差

### ISSUE THREAD

**Issue by enjoy-wind** [vueuse/vueuse#2220]
### Describe the bug

有时候我们网站需要根据不同屏幕做自适应，可能会采用不同分辨率等比缩放，但是和等比缩放功能一起用时，拖动元素位置就发生了偏差。
具体表现：光标的位置和元素的位置就分离了。
缩放代码：
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/39360554/190904264-7de8f419-165c-474a-9197-6bc44b57ad29.png">

### Reproduction

prod

### System Info

```Shell
chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ZedCoding** [comment]
@enjoy-wind 我也遇到这个问题，请问你解决了嘛
