### ISSUE TITLE
`breakpoints.md` doesn't work in template when prefixing `!`

### ISSUE THREAD

**Issue by mesqueeb** [vueuse/vueuse#2222]
### Describe the bug

bugs:
1. `.md`
`breakpoints.md` in the template works, but doesn't work when you flip it around with `!breakpoints.md`

2. `.greater('md')`
this might be a misunderstanding on my part, but `.greater('md')` doesn't work at all in the template

3. `.isGreater('md')`
this is the only one that works in the template with and without flipping

See video:

![](https://user-images.githubusercontent.com/3253920/190970471-c73351d2-17bd-4cf9-85d4-9999c93a80e9.mp4)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-5ns2ju?file=src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 144.72 MB / 24.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 102.0.1
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by haiya6** [comment]
This seems to be related to Vue templates([Ref Unwrapping in Templates](https://vuejs.org/guide/essentials/reactivity-fundamentals.html#ref-unwrapping-in-templates)).

`breakpoints.md` will not be unwrapped as `breakpoints.md.value`, so `!breakpoints.md` is like `!{}` always returns false.

Maybe you can use `!breakpoints.md.value` to get it working

**Comment by antfu** [comment]
You can use `logicNot` for reactive "not" operation.

**Comment by mesqueeb** [comment]
@haiya6 @antfu ok, maybe we can change this ticket to be a documentation ticket? It's best to write something on this so newer devs don't get confused. Perhaps with a link to the vue docs.

Also, currently, `.greater('md')` doesn't work but `.isGreater('md')` does work. While the docs don't even mention `.isGreater` 🤔  I wonder what I'm misunderstanding about `.greater` in my stackblitz.

https://vueuse.org/core/usebreakpoints/#usage

I can imagine these are good improvement tasks for the docs for completing this ticket:
- [ ] add docs on `.md` `.lg` etc. methods of `useBreakpoints`
- [ ] add mention that flipping `.md` with a `!` will break reactivity inside the template. (not when added variable from setup) with link to https://vuejs.org/guide/essentials/reactivity-fundamentals.html#ref-unwrapping-in-templates
- [ ] add docs on the difference between `.greater()` and `.isGreater`, when which one should be used
- [ ] mention that `.isGreater` works best when used directly in the template, it will not loose reactivity (with possible comparison as per my stackblitz)

**Comment by mesqueeb** [comment]
@antfu @haiya6 should I open a new ticket for the documentation recommendations above?
