### ISSUE TITLE
Type checking failed with vue@2.7: Property 'flush' does not exist on type 'WatchOptions'

### ISSUE THREAD

**Issue by lsdsjy** [vueuse/vueuse#2232]
### Describe the bug

Running `vue-tsc` in a project with `vue` of version 2.7 would report errors like this:
```
node_modules/@vueuse/shared/index.d.ts:200:26 - error TS2339: Property 'flush' does not exist on type 'WatchOptions'.

200     flush?: WatchOptions['flush'];
```

It seems that vue 2.7 exports `WatchOptions` for Options API, not for Composition API:
```ts
// node_modules/vue/types/index.d.ts
export {
  ...
  WatchOptions,
  WatchOptionsWithHandler,
  DirectiveFunction,
  DirectiveOptions
} from './options'
```
which has no `flush` property.
A possible fix is to re-export `WatchOptions` from `vue/types/v3-generated` in `vue-demi` for v2.7 like:
```ts
// vue-demi/lib/v2.7/index.d.ts
export * from 'vue'
export type { WatchOptions } from 'vue/types/v3-generated'
```
@antfu Any thoughts?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-z2pxyv?file=src/a.ts

Run `npx vue-tsc`

### System Info

```Shell
@vueuse/core: ^9.2.0 => 9.2.0 
    vue: ^2.7.3 => 2.7.10 

on StackBlitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Holi0317** [comment]
Got same issue with vue 2.7.13.

I think this is issue with vue instead of demi coz the type exported in vue 2.7 is (somehow magically?) compatible with both v3 and v2. Should we open issue on vue repo?

**Comment by vuthanhbayit** [comment]
same issue!

**Comment by lsdsjy** [comment]
Still got this issue

**Comment by Dmitry-zh** [comment]
Have same issue.
@lsdsjy thank you for solution

Temporary added patch:
```
diff --git a/node_modules/vue-demi/lib/index.d.ts b/node_modules/vue-demi/lib/index.d.ts
index 897b4c5..6cdfb78 100644
--- a/node_modules/vue-demi/lib/index.d.ts
+++ b/node_modules/vue-demi/lib/index.d.ts
@@ -18,6 +18,7 @@ declare const V: typeof Vue
 export declare type Plugin = PluginObject<any> | PluginFunction<any>
 export type { VNode } from 'vue'
 export * from 'vue'
+export type { WatchOptions } from 'vue/types/v3-generated'
 export { V as Vue, Vue2, isVue2, isVue3, version, install }

 // #region createApp polyfill
```


and added resolution in my` package.json` to freeze version:
```
"resolutions": {
        "vue-demi": "0.13.11"
    }
```

Hope this problem going to be solved asap

**Comment by lsdsjy** [comment]
keep
