### ISSUE TITLE
pnpm dev:Dependency error

### ISSUE THREAD

**Issue by Thunder7991** [vueuse/vueuse#2235]
### Describe the bug

The error message is as follows :
[vite] Internal server error: plugin.load.call is not a function
at Object.load (E:\myCode\vueuse\node_modules\.pnpm\vite@2.9.15\node_modules\vite\dist\node\chunks\dep-689425f3.js:39293:50)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async doTransform (E:\myCode\vueuse\node_modules\.pnpm\vite@2.9.15\node_modules\vite\dist\node\chunks\dep-689425f3.js:49982:24)

### Reproduction

https://vueuse.org/

### System Info

```Shell
win10 ,node 16.17.9,pnpm 7.12.1,vite 3.1.1,pnpm dev
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cainiaodjm** [comment]
I also encountered this problem

**Comment by Thunder7991** [comment]
> I also encountered this problem

Have you solved it?

**Comment by Bustuk** [comment]
Same on `macos 12.6, node 16.17.0, pnpm 7.5.0` and `node 18.9.0` and `pnpm 7.12.1`
