### ISSUE TITLE
什么时候可以有中文的文档

### ISSUE THREAD

**Issue by renjiali666** [vueuse/vueuse#2238]
### Clear and concise description of the problem

希望可以有一个中文文档

### Suggested solution

比如cn.https://vueuse.org  是中文版的

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by vaakian** [comment]
我愿意帮忙翻译，如果有其他的朋友愿意一起，咱们就开个discord群开干。

**Comment by antfu** [comment]
官方不会有 https://github.com/vueuse/vueuse/discussions/2081
