### ISSUE TITLE
[useLocalStorage] When mergeDefaults uses functions, sometimes localStorage does not update

### ISSUE THREAD

**Issue by hipi** [vueuse/vueuse#2244]
### Describe the bug

https://user-images.githubusercontent.com/22478003/192033352-4b5565fa-9c92-4b1d-b8cd-3c6219043e7f.mp4

The first time into the page no problem, the second time into the problem

### Reproduction

https://stackblitz.com/edit/vitejs-vite-qckkmi?file=src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 31.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Firefox: 104.0.2
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vaakian** [comment]
`mergeDefaults` should be returning a different `object`, your `assign` varible is always the same reference of the `defaults`, which is the initial value of the internal ref. It might be a bug, or a feature.

a quick solution:
```js
mergeDefaults: (storageValue, defaults) => {
      const assign = mergeWith(defaults, storageValue, customizer);
      // create a new object
      return {...assign};
    },
```
