### ISSUE TITLE
useAxios Data returns ShallowRef, can be changed to configurable, ref or ShallowRef, sometimes you need to operate on the data nested property

### ISSUE THREAD

**Issue by laterdays** [vueuse/vueuse#2249]
### Describe the bug

Data returns ShallowRef, can be changed to configurable, ref or ShallowRef, sometimes you need to operate on the data nested property

### Reproduction

*

### System Info

```Shell
useAxios Data returns ShallowRef, can be changed to configurable, ref or ShallowRef, sometimes you need to operate on the data nested property
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by laterdays** [comment]
I will return the data data, used in the table, I tried to modify the nested property of data, he failed

**Comment by laterdays** [comment]
const {data } = useAxios(****)

If the data =  ([
  { status: 1, id: 1 },
  { id: 2, status: 0 }
]);

data.value[0].status  = false
 
He was a failure

**Comment by laterdays** [comment]
![image](https://user-images.githubusercontent.com/112848218/192104322-6aa6000c-16e0-48b3-a62c-22a42a9ae155.png)
I see ShallowRef in the source code, can you provide a configuration item to choose whether to use ShallowRef or ref

**Comment by GODLiangCY** [comment]
It's not a good practice to directly change the data returned from the request, IMHO

**Comment by laterdays** [comment]
@GODLiangCY   So how do you use the returned shallowRef data, or how do you change shallowRef back to Ref

**Comment by laterdays** [comment]
In the current scenario, the data is given to the table, but there is a switch that needs to modify the data of the table, because it is shallowRef, so the table view is not updated

@GODLiangCY
