### ISSUE TITLE
Delay before disconnecting useFirestore

### ISSUE THREAD

**Issue by Zehir** [vueuse/vueuse#2252]
### Clear and concise description of the problem

In the case you are using vue-plugin-pages you can have a case that you load the same documents multiple times in case you came back to a page you already loaded once.
But when you change the page the connection is closed at the moment you left the page thanks to:
```javascript
    tryOnScopeDispose(() => {
      close()
    })
```
So you will be charged by one read each time.

### Suggested solution

Using a little delay could alow you to use the cached document instead of get one new.
```javascript
    tryOnScopeDispose(() => {
      useTimeoutFn(() => {
        close()
      }, 30000)
    })
```
You don't need more code because the firestore sdk handle it by default. Even if the first `useFirestore` is closed I still get updates on the new `useFirestore`

### Alternative

An alternative is to store your `useFirestore` in a pinia store but it's lead to many tracks of what you put there.

### Additional context

I can make a PR for that but I don't know about the delay, should it's be lower ? configurable ?
Maybe a force close option ?
Maybe a close if I get an update during the timeout ?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kiyopikko** [comment]
I think it's the simplest way `autoDispose` option also accept milliseconds of timeout (`number`)  not only `false`. 

> Maybe a close if I get an update during the timeout ?

Can you do this? I want to know how it is implemented.

**Comment by Zehir** [comment]
I will make a PR to have some code to discuss on. But yes you can do that with a watchOnce and call the close method when data is updated. If it's an other listener on the same document it's won't be an issue because it's will just close the old one.

**Comment by Zehir** [comment]
This is my current implementation using a custom composable;
https://gist.github.com/Zehir/be3b229e36963b1e4d6869207b231ac0

**Comment by kiyopikko** [comment]
Thanks, let's discuss on your PR 👍

**Comment by Zehir** [comment]
> Thanks, let's discuss on your PR 👍

It's may take a few days, I have some issues to setup a dev env #2268

**Comment by Zehir** [comment]
@kiyopikko why did you limit close to query only ? Documents read need to be closed too.
https://github.com/vueuse/vueuse/blob/2419803235e55e5e19057c4225c30edc571ee4b1/packages/firebase/useFirestore/index.ts#L99-L103

**Comment by kiyopikko** [comment]
@Zehir oh, that's a mistake and thanks for making PR!

I cared about compatibility, I wanted to write

```
if (autoDispose || isDocumentReference<T>(refOfDocRef.value)) { 
  tryOnScopeDispose(() => {})
}
```

because documents always close regardless `autoDispose` option in [previous code](https://github.com/vueuse/vueuse/blob/ffb24e77b62ac68def6f935f9114cd1a761d228f/packages/firebase/useFirestore/index.ts#L88-L90).

but almost users will expect to be able to use `autoDispose` to documents so

```
if (autoDispose) { 
  tryOnScopeDispose(() => {})
}
```

is good like your PR.

**Comment by Zehir** [comment]
Up

**Comment by Zehir** [comment]
#2276 is updated
