### ISSUE TITLE
feat: allow `history.pushState` instead of `history.replaceState` in `useUrlSearchParams`

### ISSUE THREAD

**Issue by yassilah** [vueuse/vueuse#2260]
### Clear and concise description of the problem

Currently, when using `useUrlSearchParams`, the state is being replaced and there is no way to push it instead. My use case is that I'm building a small app within a larger one, so we agreed to use "scoped" hash params to navigate and make sure they don't clash with existing ones. However, with the current implementation, I cannot go back/forward as the initial state is being replaced in the history.

### Suggested solution

Simply add an option to allow for pushing state.

```ts
export interface UseUrlSearchParamsOptions<T> extends ConfigurableWindow {
  /**
   * Action performed on state change
   *
   * @default "replace"
   */
   action?: 'replace' | 'push' 
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jelledruut** [comment]
Would be great! Is there a reason your PR wasn't merged?

**Comment by vincerubinetti** [comment]
It just got marked as stale and closed, along with this issue. Really bad practice. If they're still issues, they should be left open, even if you don't have the resources to get to them.

This option is such a slam dunk and obvious addition. `vueuse` is a great library, but I'm surprised this wasn't in there from the beginning. Every router for any framework -- or even any library I've seen that deals with the URL or history -- has this option. Definitely not an "enhancement".
