### ISSUE TITLE
Repo playground not working

### ISSUE THREAD

**Issue by Zehir** [vueuse/vueuse#2268]
### Describe the bug

Hello, I tried to use the playground folder from the repo to try functions in a blank setup but for some reason reactivity don't seems to work.
It's look that the "reactivity tree" stop at the page render.
I also tried to install vitesse in a new folder, but I get the same result.
For example if I load the useMouse I get value 0,0 but if I type something in the input field the x,y values get updated.

I have no idea what is happening here

### Reproduction

https://github.com/Zehir/vueuse/tree/dev

### System Info

```Shell
System:
    OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 4.31 GB / 7.77 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  npmPackages:
    vue: ^3.2.39 => 3.2.39
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Zehir** [comment]
I copied the settings from
/vitest.config.ts
to
/playgrounds/vite/vite.config.ts
and now it's working fine.
I don't know what the option `resolve.dedupe` do but it's solve the issue.

Do we should make a PR to update the playground config ?

**Comment by Zehir** [comment]
Well it's not working that good, I can use functions like `useMouse` but have no success with the firebase package. I tried many variation to import the package. Did anybody was able to make it work ?

**Comment by jiang-24-gdufs** [comment]
I just cloned the repository from github, and found that the example repo in the playgrounds can not start
