### ISSUE TITLE
Assert version of isDefined

### ISSUE THREAD

**Issue by Tsuyoshi84** [vueuse/vueuse#2269]
### Clear and concise description of the problem

There is [isDefined](https://vueuse.org/shared/isdefined/) composable that checks if a given value is defined or not. I thought it would be helpful if there were also an "assert" version of `isDefined` composable.

### Suggested solution

The implementation would be:

```ts
interface AssertDefinedOptions {
  message?: string
}

export function assertDefined<T>(v: Ref<T>, options?: AssertDefinedOptions): asserts v is Ref<Exclude<T, null | undefined>>
export function assertDefined<T>(v: ComputedRef<T>, options?: AssertDefinedOptions): asserts v is ComputedRef<Exclude<T, null | undefined>>
export function assertDefined<T>(v: T, options?: AssertDefinedOptions): asserts v is Exclude<T, null | undefined>
export function assertDefined<T>(v: Ref<T>, options: AssertDefinedOptions = {}): void {
  const { message = 'Value is undefined or null' } = options

  if (unref(v) == null) {
    throw new Error(message)
  }
}
```

Usage:

```ts
const video = ref<HTMLVideoElement | null>(null)

function playVideo() {
  assertDefined(video, { message: 'video element is missing!' })

  video.value.play()
}
```

If it looks good, I'll make a PR.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks but this is out-of-scope of VueUse.
