### ISSUE TITLE
RemovableRef<T> should have a getter of <T | null>

### ISSUE THREAD

**Issue by Glandos** [vueuse/vueuse#2271]
### Describe the bug

In https://github.com/vueuse/vueuse/issues/452 the solution was to add RemovableRef<T> that accept null as a set value.
But after setting the value, the get will return null! So the typing of `get()` is incorrect, it should return `<T | null | undefined>` since the value will be set as-is, at least by useStorage.

(Sorry, Stackblitz doesn't work in my browser for a minimal repro)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rptfks/

### System Info

```Shell
System:
    OS: Linux 5.19 Debian GNU/Linux bookworm/sid
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 12.27 GB / 31.22 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chromium: 105.0.5195.125
    Firefox: 104.0.2
  npmPackages:
    @vueuse/core: ^9.2.0 => 9.2.0 
    vue: ^2.7.10 => 2.7.10
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
When you delete the value, it should fallback to the initial value you provided, thus it shouldn't be nullable.

**Comment by Glandos** [comment]
That's right. It is not clearly stated in the docs, but I should have been more careful in my tests. Sorry about the noise.

**Comment by Glandos** [comment]
Before opening a new issue, can you confirm that [setting null doesn't fallback to the initial value?](https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAnJMAAzk9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKnFeDArGQMPkGWhshQCKRIBRgxGYwEQmms2GLLZHMQJPJlI2iG2e0OAF1mEY6AZDWhQABBMBgSYLdCgVIagwQVJEAA8VGyAB1zDV-ZsALwpkAzAykPDYXNplQ1eTSHMgPDyVgl9MAPlLKiT2Qbos41iVKmIhlUyASjzQKmAwBUAOkkmw8G0A7qIMcBwOOlH8RCYEQcpUc8eKiX9kmCeGyeITfTCdKAQS5nOUCCsCrN2k2mwpAi9lzKjwHCrjU-YCrABGT9SjqGgf1zdowE2XMGwBRBpBUV8IiPS9+nkM8ywvK9dVve8YEfBDtAAcl0TwvGIj8QBUADc2A6jQI4cCqygmCQDghCVDIiJWFQnDsDPI8TwbZ5BWkIg6A1OpELHPEAFl2BuRh-BuCc6gQNJlyMDhZhUYi7Rudl52ItM0xmbAB23QcQRULMVMQNSKiQbRm2IqBrgSPAAH0YEQEJiMYVzuIowL00iDZWEiSYvCgQxHI00KyzHIIBxsAAVVh4qQUV9GnFBhyMQxIQONMP2LbAjH4aVhW3IjewLRBHGAZsdxBcM+zSOz6vINMSoUJcDiAA)
I had to set `listenToStorageChanges` to false, since in the playground, storage is set in a subdocument, and that triggers the event listener. Which is not the case in a SPA.

I see no test about setting value to null **and** testing that the value was set to the fallback value. The following test initializes with a `null` fallback, so it's not the same: https://github.com/vueuse/vueuse/blob/c20bfdb59873b4a1c2119a5f5e148df90357f75f/packages/core/useStorage/index.test.ts#L104-L114
