### ISSUE TITLE
useTimer

### ISSUE THREAD

**Issue by franciscoemanuel** [vueuse/vueuse#2274]
### Clear and concise description of the problem

It would be helpful to have a timer composable that would execute a callback after it's finished, something like [useTimer](https://www.npmjs.com/package/use-timer) from React, and if it sounds cool I could work on a PR asap.

### Suggested solution

Usage would be like:

```js
  const { timer, start } = useTimer(5, () => {
    isButtonDisabled.value = false;
  });
```

I've created a [stackblitz](https://stackblitz.com/edit/vue-6z9exj?file=src%2FApp.vue,src%2Fcomposables%2FuseTimer.js) initial implementation with some controls, but the API could be simpler.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Zehir** [comment]
You mean like [useTimeoutFn](https://vueuse.org/shared/useTimeoutFn/) ?

**Comment by franciscoemanuel** [comment]
@Zehir The purpose of what I was proposing was indeed something like `useTimeoutFn`, but that could also return a reactive timer value corresponding to the time left for the function to be executed and that would be helpful in cases where the remaining minutes and seconds must be displayed, such as:

![CPT2210031114-582x259](https://user-images.githubusercontent.com/15387723/193599561-47ad9fea-fdec-4115-a137-455b15d0a24c.gif)

**Comment by Zehir** [comment]
So with coundown and countup option ?

**Comment by Zehir** [comment]
Or maybe add a reactive value on the timeout function to have the time left

**Comment by chaii3** [comment]
@franciscoemanuel do you want to make a PR ?

**Comment by franciscoemanuel** [comment]
@chaii3 for sure, I will draft something as soon as I can
