### ISSUE TITLE
useBase64 returns empty string when unwrapped in script

### ISSUE THREAD

**Issue by marssantoso** [vueuse/vueuse#2277]
### Describe the bug

Title.

Example code:

```ts
const { base64 } = useBase64('some text')
console.log(base64)       // { value: 'data:text/plain;base64,c29tZSB0ZXh0' }
console.log(base64.value) // empty string
```

This way, we can't use the encoded base64 value in `script`, only in `template`. Or is there something missing?

Edit:

Also tried using `reactive` like [mentioned in the doc here](https://vueuse.org/guide/best-practice.html#destructuring), still doesn't work:

```ts
const b = reactive(useBase64('some text'))
console.log(b.base64) // still empty string
```

More tries, using `watch` works but it doesn't quite fit our use case:

```ts
const { base64 } = useBase64('some text')
watch(base64, (v) => {
  console.log(v)
})
```

Computed would be better, however it still doesn't work either:

```ts
const { base64 } = useBase64('some text')
const computedBase64 = computed(() => base64.value)
console.log(computedBase64.value)
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-sunpbu?file=app.vue

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 113.66 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.6.1
  npmPackages:
    @vueuse/nuxt: ^9.3.0 => 9.3.0
    vue: ^3.2.39 => 3.2.39
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
https://github.com/vueuse/vueuse/blob/main/packages/core/useBase64/index.ts#L97-L100

if input is not a ref or function, it will be a promise.

So I think it should be
```
const { promise, base64 } = useBase64('some text')
await promise.value
console.log(base64.value)
```
