### ISSUE TITLE
`useVirtualList` receive events from mounting shown indexes

### ISSUE THREAD

**Issue by mesqueeb** [vueuse/vueuse#2286]
### Clear and concise description of the problem

We need a virtual list combined with
1. an api call to fetch extra rows when we get close to reaching the bottom
2. an api call to fetch extra data on shown rows

### Suggested solution

I imagine the API could look something like this

```ts
const rows = ref<{ id: string }[]>([])

const extraData = ref<{ [id in string]: unknown }>({  })

const filteredItems = computed(() => rows.value.map(r => ({ ...r, extraData: extraData[r.id] })))

async function fetchRowData (id: string) {
  const data = await api.fetchExtraData(id)
  extraData[id] = data
}

async function fetchExtraRows (index: number) {
  if (index + 20 > rows.value.length) {
    const rows = await api.fetchRows({ after: rows.value.length, limit: 20 })
    rows.value.push(...rows)
  }
}

async function onRowBecameVisible (index: number) {
  const rowId = filteredItems.value[index].id
  fetchRowData(rowId)
  fetchExtraRows(index)
}

const { ... } = useVirtualList(
  filteredItems,
  {
    visible: i => onRowBecameVisible(i),
    itemHeight: i => (filteredItems.value[i].height + 8),
    overscan: 10,
  },
)
```

### Alternative

```ts
const { list, containerProps, wrapperProps, scrollTo } = useVirtualList(
  filteredItems,
  {
    itemHeight: i => {
      // async side effect in here seems... wrong
      onRowBecameVisible(i)
      return filteredItems.value[i].height + 8
    },
    overscan: 10,
  },
)
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
We are deprecating `useVirtualScroll` in favor of https://github.com/Akryum/vue-virtual-scroller

See https://github.com/vueuse/vueuse/pull/2658
