### ISSUE TITLE
onClickOutside with teleport

### ISSUE THREAD

**Issue by mokone91** [vueuse/vueuse#2287]
### Clear and concise description of the problem

Hi!
I have a Modal with onClickOutside, I render select control which uses teleport to show dropdown content(to allow dropdown to overflow modal/any other overflow hidden wrapper) but when i click to dropdown content click outside it triggered as content rendered in body

Is there any solution exept to filter teleports on each onClickOutside usage? 

### Suggested solution

looking for solution 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by carl1498** [comment]
same here, there's currently an ignore option for onClickOutside but it's only for the core and is not yet available for the components. Hope we could have it there too.

https://github.com/vueuse/vueuse/pull/1205

**Comment by jd-solanki** [comment]
You can use ignore as we did in the Anu framework [here](https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/components/select/ASelect.tsx#L101).

In your case, you can assign template ref to the dropdown and add it to ignore list.

I hope this will resolve your issue.

**Comment by sibbng** [comment]
@mokone91 I would suggest you create a wrapping function in this situation. When #2439 is merged, you can also add selector strings in `ignore` option.

@carl1498 We've added support passing options in OnClickOutside component. But at the moment `ignore` option only accepts HTMLElement. It may be tricky to pass ignored elements through the component if you are working in SSR environment. #2439 will make this easier by adding selector string support for `ignore` option.
