### ISSUE TITLE
useIndexedDb / useIDB

### ISSUE THREAD

**Issue by Fanna1119** [vueuse/vueuse#230]
Any plans for adding a IndexedDb utility ?

**Comment by antfu** [comment]
This is definitely good to have. However, I am not that familiar with IndexedDB, PR welcome. Another option is that we could have a wrapper for https://dexie.org/

**Comment by brokolosov** [comment]
I found a local DB [comparison](http://nolanlawson.github.io/database-comparison/) (localStorage, localForage, Dexie, LokiJS etc.)  Based on this comparison, a better choice would be LokiJS. Dexie is to slowly... IMHO

**Comment by Fanna1119** [comment]
LokiJS looks really decent, i have never heard of it before, thanks for the share!

**Comment by jssullivan** [comment]
I am working to make a composition wrapper around [idb-keyval](https://www.npmjs.com/package/idb-keyval). Which is a key value store api on top of Indexed DB. It will have a similar type signature to [useStorageAsync](https://vueuse.org/core/useStorageAsync/) 

This won't add full support for Indexed DB. However it will give you typed keys and values without the need of a serializer, adds web worker support, and lets you use more storage space when compared to using the local storage variant.

It won't reactively update if another source updates the KV store. There isn't an event that fires when the Indexed DB is changed, unlike the Storage Api's (https://github.com/vueuse/vueuse/blob/main/packages/core/useStorage/index.ts#L164).

Can I open a PR adding it to `vue-use`?  I was thinking the name would be `useKVIndexedDB`.
