### ISSUE TITLE
useAxios Support custom ResponseType 

### ISSUE THREAD

**Issue by laterdays** [vueuse/vueuse#2303]
### Clear and concise description of the problem

Now that axios supports custom responseType, I want useAxios to update

```
get<T = any, R = AxiosResponse<T>, D = any>(url: string, config?: AxiosRequestConfig<D>): Promise<R>;
delete<T = any, R = AxiosResponse<T>, D = any>(url: string, config?: AxiosRequestConfig<D>): Promise<R>;
```

### Suggested solution

UseAxios<T, R,D>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by laterdays** [comment]
![图片](https://user-images.githubusercontent.com/112848218/194703183-dc3d2d16-4749-49c6-b602-8ff7a95c7346.png)

**Comment by Surof1n** [comment]
Tell me what do you want to do?

It seems that this has already been implemented.

<img width="1017" alt="Снимок экрана 2022-10-09 в 00 37 43" src="https://user-images.githubusercontent.com/75340792/194728594-3ad31315-1ecd-40b1-983e-445626c75fa2.png">

**Comment by laterdays** [comment]
There's already a PR for that

**Comment by laterdays** [comment]
@Surof1n https://github.com/vueuse/vueuse/pull/2304
