### ISSUE TITLE
Support more media session features

### ISSUE THREAD

**Issue by septatrix** [vueuse/vueuse#2308]
### Clear and concise description of the problem

`useMediaControls` is not sufficient for my use case.
I also want to have handlers for skipping/seeking and provide metadata like title and artwork for a video/song.
This is possible using the [`MediaSession` API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API)

### Suggested solution

Add a new `useMediaSession` function which covers all these features.

### Alternative

It would also be possible to expand the existing `useMediaControls` function though I am not sure if e.g. providing metadata fits into its scope. Therefore a new functions seems fitting. It might, however, be fitting to deprecate `useMediaControls` in favor of the newer proposed function if is implemented in such a way that it provides a superset of the existing features though I am not sure if the media session API also covers stuff like volume so it might be a good idea to just keep them separate.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by septatrix** [comment]
Does this fit within the project or is this out of scope?

**Comment by ferferga** [comment]
I agree a new useMediaSession function would be nice. However, what exactly prevents you from using this composable and provide your own MediaSession handlers yourself?

**Comment by septatrix** [comment]
Nothing and that is what I am currently doing as a workaround though that is definitely not as pretty as using composables from this library

**Comment by ferferga** [comment]
@septatrix I'm thinking I might take this one
