### ISSUE TITLE
Warning 'Vue 2 does not support reactive collection types such as Map or Set' in useMagicKeys on Vue 2.7

### ISSUE THREAD

**Issue by MrCube42** [vueuse/vueuse#2311]
### Describe the bug

As stated in https://blog.vuejs.org/posts/vue-2-7-naruto.html even though Vue 2.7 fully includes the composition API there are a few caveats as e.g. `Map` and `Set` are not reactive. I am using `useMagicKeys` to listen for global _Ctrl+S_ in order to save some changes. The feature itself is working properly, however in my tests there appears a warning from inside `useMagicKeys` saying that  'Vue 2 does not support reactive collection types such as Map or Set'. In our setup we fail on warnings in our tests.

Having a look at the sources shows that `current` is defined as a reactive `Set` (https://github.com/vueuse/vueuse/blob/main/packages/core/useMagicKeys/index.ts#L83). This line of code produces the warning described above.

As _vueuse_ states to support both Vue 3 and 2(.7) (with the use of vue-demi and so one) I would not expect a warning like this.

---

For a minimal reproduction, use the repo from https://github.com/MrCube42/magickeys-warning and simply `npm run dev`. The browser will also log the warning. The code using `useMagicKeys` itself is located in the `App.vue`.

### Reproduction

https://github.com/MrCube42/magickeys-warning

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 14.27 GB / 23.48 GB
    Container: Yes
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 16.16.0 - /mnt/wslg/runtime-dir/fnm_multishells/709_1665480869441/bin/node
    npm: 8.11.0 - /mnt/wslg/runtime-dir/fnm_multishells/709_1665480869441/bin/npm
  npmPackages:
    @vueuse/core: ^9.3.0 => 9.3.0 
    vue: ^2.7.10 => 2.7.10
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ElYaiko** [comment]
I'm having the same issue with `useMagicKeys()` in Vue 2.7.0

**Comment by ethanhalko** [comment]
Also having this issue. Has anyone found a solution?

**Comment by luvsic3** [comment]
Hi, I created a pull request to solve this problem  
#2503

**Comment by valh1996** [comment]
Hi, any update on this please?

**Comment by Glandos** [comment]
In order to avoid `useReactiveSet`, it's also possible to use [`useArrayUnique`](https://vueuse.org/shared/useArrayUnique/) (which was created after #2503), but it returns a `ref` and not a `reactive`. Is it possible to *unref* it?

**Comment by Lurrik** [comment]
Hi, any update on this please? I'm having the same error on Vue 2.7

**Comment by luvsic3** [comment]
#2503   
I created a pr to solve this issue, but I haven't gotten approved

@valh1996 @Lurrik
