### ISSUE TITLE
useScroll on nuxt 3

### ISSUE THREAD

**Issue by Seyid-cmd** [vueuse/vueuse#2324]
### Describe the bug

Is there anyway to use useScroll on the body tag ?

**Comment by Seyid-cmd** [comment]
Sorry , It was not working because I failed to make referenced element scrollable .can i use useScroll on the body tag

**Comment by Seyid-cmd** [comment]
Closed, to ask question on Stackoverflow

**Comment by ngekoding** [comment]
Hi, have you make it works?

**Comment by kespaldon** [comment]
@ngekoding https://stackoverflow.com/questions/74070972/how-to-use-usescroll-on-nuxt-3
