### ISSUE TITLE
useContainerQuery function

### ISSUE THREAD

**Issue by sykes10** [vueuse/vueuse#2329]
### Clear and concise description of the problem

I found myself using a lot of the composable useElementSize to have a different layout based on the width of the element to do conditional rendering and I think that we can create a new method to have this logic together.

### Suggested solution

I think it would be a good idea to have a function called useContainerQuery that would be similar to useBreakpoint where you provide the breakpoints for the element you want to track and the container and it will return those breakpoints and if they are met or not.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by michealroberts** [comment]
I did have a PR open on this, but I believe it has been closed. #1297
