### ISSUE TITLE
Support `extendRef()` with Vue 2.7

### ISSUE THREAD

**Issue by posva** [vueuse/vueuse#2340]
### Clear and concise description of the problem

`@vue/composition-api` has a limitation that prevents `extendRef()` to be used but this is not the case for Vue 2.7

### Suggested solution

I think vue-demi could expose a variable `isNativeCompositionAPI` or similar.

Even without that, using `import { version } from 'vue'` should work in most cases to check if it's vue >= 2.7 and allow using `extendRef()`.

### Additional context

- https://github.com/vueuse/vueuse/issues/280

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by posva** [comment]
up

**Comment by antfu** [comment]
Making sense, implemented. `isNativeCompositionAPI` might be a good idea, but I feel `vue-demi` is already a bit overwhelming. Since we can have the info via `version`, let's use it for now.
