### ISSUE TITLE
OnClickOutside: Option to trigger on escape key

### ISSUE THREAD

**Issue by gregg-cbs** [vueuse/vueuse#2342]
### Clear and concise description of the problem

On clicking outside of things is a common practice to close things..  this is usually paired with the ability to close things by pressing the escape key on the keyboard.

It would be nice to have a prop to allow this functionality:
`closeOnEscapeKey: true`

### Suggested solution

Add suggested prop

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by webfansplz** [comment]
IMHO, It's out of scope the `onClickOutside`,I recommend use 'onKeyStroke' to combine it :

```ts
onKeyStroke('Esc', () => {
  // ...
})

```
