### ISSUE TITLE
computedRef

### ISSUE THREAD

**Issue by jackZmym** [vueuse/vueuse#2344]
### Clear and concise description of the problem

      <template #default="scope">
                        {{ useDateFormat(scope.row.createDate, 'YYYY-MM-DD').value }}
      </template>

### Suggested solution

Can you give a configuration so that the utility class does not form computedRef? I just want the result to be displayed

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
`formatDate` is exposed for that.
