### ISSUE TITLE
Adding v-visible directive (and component/hook)

### ISSUE THREAD

**Issue by Blackfaded** [vueuse/vueuse#2345]
### Clear and concise description of the problem

Hey there!

Sometimes v-if and v-show are not enough. The v-if directive removes an element from the DOM and the v-show directive sets the `display` value to `none`. Both of them come with the caveat that the element does not take any space in the DOM anymore.
As a developer I often need the flexibility to hide an element, but keep their space in the DOM.

### Suggested solution

In module useVisible we could provide the following implementation:

As a hook
```ts
useVisible(elementRef, flag)
```

As a directive
```vue
<div v-visible="flag">Hello World!</div>
```

As a component
```vue
<Visible :show="flag">Hello World!</Visible>
```

### Alternative

The only alternative to implement this so far is to give the DOM element a class and set the css to `visibility: hidden`

### Additional context

![Bildschirmfoto 2022-10-21 um 09 09 33](https://user-images.githubusercontent.com/19570581/197134752-b2b86528-0e4e-4ec1-8f91-ecc83a474ec6.png)

I would love to open a PR if this feature is needed in this library

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ywenhao** [comment]
I think this is great!
