### ISSUE TITLE
Pass options to useFetch execute()

### ISSUE THREAD

**Issue by fvanwijk** [vueuse/vueuse#2348]
### Clear and concise description of the problem

Suppose I want to save a User.

```html
<input v-model="user.id" />
<button @click="onSave(user)">
```
```ts
const user = ref({ firstname: '', lastName: '', id: '1' });

const useSaveUser = (user: Ref<User>) => {
  return useFetch(computed(() => `/api/user/${user.id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(user.value) // this is not reactive :(
  }));
}

const { data, isFetching error, execute: onSave } = useSaveUser(user);
```

The URL is reactive, so when I call `execute()` it will call the endpoint `/api/user/2` after I change the id into 2 with the input field.
However the options are not reactive so I cannot PUT the updated user.

Am I missing something or is it pretty hard to use `usefetch` except for when you are fetching things?

### Suggested solution

It would be nice if you can pass `options` to the `execute` method. These will be merged with the options that you already passed when calling `useFetch`.

```ts
const useSaveUser = (user: Ref<User>) => {
  return useFetch(computed(() => `/api/user/${user.id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
  }));
}

const { data, isFetching error, execute } = useSaveUser(user);

const onSave = (user) => {
  execute(undefined, {
    url: `/api/user/${user.id}`,
    body: JSON.stringify(user)
  });
}
```

### Alternative

As a workaround I can do something like this:
```ts
const isFetching = ref(false);
const showError = ref(false);
const onSave = (user) =>
  isFetching.value = true;
  showError.value = false;

  const { data, error } = await useFetch(`/api/user/${user.id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(user)
  }));

  isFetching.value = false;
  showError = !!error.value;
}
```
However then I don't make use of hooks and I need to keep redundant state. Then I can also use `fetch` or one of the available vanilla JS API clients.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by emavitta** [comment]
Have you tried removing the body from the initialization and then pass to the execute function this way?
 'execute().post(JSON.stringify(user)).json()'

**Comment by fvanwijk** [comment]
Thanks for the suggestion. The problem is that you want to use `useFetch` to create all the reactive state once, but at that moment in time you don't know the body to POST yet. So with a single `execute` call you want to set the body just in time.

If I'm correct you are suggesting to split the `useFetch` and the `post` calls. `.post()` creates a new `UseFetchResult` instance, but I won't use it.

```ts
const useSaveUser = (user: Ref<User>) => {
  return useFetch(computed(() => `/api/user/${user.id}`, {
    headers: { 'Content-Type': 'application/json' },
  }, { immediate: false ));
}

const useSaveResult = useSaveUser(user);
const { data, isFetching error, execute } = useSaveResult;

const onSave = (user) => {
  const newUseSaveResult = useSaveResult.put(JSON.stringify(user)).json();
  execute();
}
```

My original problem is that I want to POST `/api/user/` or PUT `/api/user/${user.id}`. So the method and URL also should update when I call `execute`.

```ts
const onSave = (user) => {
  const newUseSaveResult = user.id ?
    useSaveResult.put(JSON.stringify(user)).json() : // How to update URL?
    useSaveResult.post(JSON.stringify(user)).json();
  execute();
}
```

The reactive URL and method still depend on `user` passed into `useSaveUser`, so that still leads to issues.
I think I have to separately call `useFetch` for PUT and POST and execute either one of them...

**Comment by emavitta** [comment]
Sorry i replied on my mobile so i was too quick, i made a little confusion, you were not talking about post but put.
Anyway her's the solution i'd implement by your first post using put:

```javascript
const user = ref({ firstname: '', lastName: '', id: '1' });

const useSaveUser = () => {
  return useFetch(`/api/user/${user.value.id}`, {
    headers: { 'Content-Type': 'application/json' },
  }).put(JSON.stringify(user.value)).json();
}

const { data, isFetching, execute: onSave } = useSaveUser(user);
```

No need to use a computed, since you're calling the execute on @click. 
I just stumbled on the same thing and this was my way of solving it, only using reactive in the post() (hence my error on my first reply) cause i had to build a more complex object.
hope it helps.

**Comment by fvanwijk** [comment]
[Here is a sandbox](https://stackblitz.com/edit/vue-cssrbp?file=src%2FApp.vue) to demonstrate that your example doesn't work.

Some small changes:
- I added `{ immediate: false }` because it should only fire on execute
- You cannot use `user` from closure because you want a hook to be a pure function that is eventually moved into a different file. However with a closure it also doesn't work, see [example](https://stackblitz.com/edit/vue-5jmqsm?file=src/App.vue)

When you type 2 in the input field, after clicking Save the called url is still `/api/user/1` and the `id` in the body is also still 1 ❌.

**Comment by emavitta** [comment]
Doing this way you can update the body of your payload.

```javascript
export default defineComponent({
  setup() {
    const userRef = ref({ firstname: '', lastName: '', id: '1' });

    const useSaveUser = (user) => {
      return useFetch(
        `/api/user/${user.value.id}`,
        {
          headers: { 'Content-Type': 'application/json' },
        },
        { immediate: false }
      )
        .put(user)
        .json();
    };

    const { data, isFetching, execute: onSave } = useSaveUser(userRef);

    return { onSave, userRef };
  },
});
```

Changing the input for the id (or adding more input for the other values as the username) change the body of the payload. It doesn't change the id in the url, but you can try to add `{refetch:true}` and add the url as a ref, as described in the [docs](https://vueuse.org/core/usefetch/#refetching-on-url-change).

**Comment by fvanwijk** [comment]
Thanks. By passing a `Ref` to `.put` the value is reactive and it is automatically stringified 👍🏻 
But how to update the `id` in the url when calling `execute`?

**Comment by emavitta** [comment]
Check this out, it's just a quick implementation. No need for refetch true cause you don't want to update automatically on the change of the input. I hope that's the way you intended to use the composable, still it's an idea of how you can implement it.

https://stackblitz.com/edit/vue-vsm2pj?file=src%2FApp.vue

Hope it helps

**Comment by fvanwijk** [comment]
In the mean time I created this full example, including error handling.

So the main differences with your example are:
1. Supports PUT and POST depending on which button you click
2. The `userRef` should not be updated when we click Save as. It should create a copy that is POSTed. Hence the need for passing a different payload to `execute` :) 

https://stackblitz.com/edit/vue-hbnfxy?file=src/App.vue

**Comment by emavitta** [comment]
I would have create two different method, SaveAs and Save instead of onSave with an option, just so i can have a better api interface of the methods to call, leaving the method to call to the component; a little bit more elastic. Stil it works. Nice!

**Comment by fvanwijk** [comment]
I think you are right. So it looks like the url and body can be made reactive when you execute the call via `useFetch(urlRef).post(bodyRef)`.
All the other options aren't. If you want to be flexible, you need to create multiple `UseFetchResult`s upfront.

I'd like to see the authors view on this matter before closing the issue myself.

**Comment by emavitta** [comment]
What do you mean with all the other options?

**Comment by fvanwijk** [comment]
I mean options like `headers` and `method`
