### ISSUE TITLE
Types incompatibility when assigning `useClipboard` to `ref<UseClipboardReturn<true>>` 

### ISSUE THREAD

**Issue by DamianGlowala** [vueuse/vueuse#2352]
### Describe the bug
What is the correct type to specify when declaring a `ref`, so that the error is gone?
```
const clipboard = ref<UseClipboardReturn<true>>(null)

onMounted(() => {
    clipboard.value = useClipboard({
        source: '...'
    })
})
```
![image](https://user-images.githubusercontent.com/48835293/197282782-33d80ddd-6a02-473c-8543-2cc4f3bd9948.png)

### Reproduction

n/a

### System Info

```Shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by darrylnoakes** [comment]
You are nesting the refs returned by `useClipboard` within another ref.
They way the `Ref` type is defined in Vue means that that the info that the object properties are refs is stripped away.

**Comment by darrylnoakes** [comment]
Vue unwraps these nested refs, which means that they values (and therefore their types) are incompatible.

**Comment by DamianGlowala** [comment]
Appreciate the explanation of what is happening here :) What would be the correct way to solve this issue though? Have you got an idea?

**Comment by darrylnoakes** [comment]
Relevant code (stripped down):

```ts
export function ref(value?: unknown) {
  return createRef(value, false) // A
}

function createRef(rawValue: unknown, shallow: boolean) {
  ...
  return new RefImpl(rawValue, shallow) // B
}

class RefImpl<T> {
  ...

  constructor(value: T, public readonly __v_isShallow: boolean) {
    this._rawValue = __v_isShallow ? value : toRaw(value)
    this._value = __v_isShallow ? value : toReactive(value) // C
  }

  get value() {
    trackRefValue(this)
    return this._value // D
  }

  ...
}
```

Flow:
- `A`: The `ref` function calls `createRef`.
- `B`: `createRef` creates a new `RefImpl`.
- `C`: The constructor of `RefImpl` passes the value through `toReactive` if it is not creating a shallow ref. 
- `D`: The value that has been passed through `toReactive` is used as the developer-facing `value` property.

**Comment by darrylnoakes** [comment]
As to solving the issue, this looks like it could be a case of the XY problem.
What are you actually trying to achieve?
Why do you need to call `useClipboard` on mount? Could you not do it at the top-level of the setup?

**Comment by darrylnoakes** [comment]
If you _have_ to do it as you currently have it, you can wrap the `useClipboard` call in `reactive`.

**Comment by DamianGlowala** [comment]
Good point about declaring it at the top-level - there was an error and I thought it is about using this particular composable, but it turns out isn't related to `useClipboard` so closing! :) Again, thank you for the advice you shared on this issue.
