### ISSUE TITLE
useAxios，execute After the request is sent, the returned data is printed as old data （probabilistic）

### ISSUE THREAD

**Issue by laterdays** [vueuse/vueuse#2392]
### Describe the bug

After the request is sent, the data returned is up-to-date when viewed by network, but the data printed as data.value is old
（probabilistic）

```
const { excute } = useAxios('api');

const test = async () => {
  const { data } = await excute(__, {}, { params: { id: 1 } });
  console.log(data);
};
```

### Reproduction

*

### System Info

```Shell
windows
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ethansnow2012** [comment]
I got the issue too.  In vueuse ^9.1.0, axios ^0.27.2.

**Comment by laterdays** [comment]
@antfu

**Comment by laterdays** [comment]
@antfu  Looking forward to resolution

**Comment by ethansnow2012** [comment]
After I have deeper understanding, I figured out in my case it may not be a bug. It's just that I sent two requests 
in order but the first one was received later than the second one. Thus the first one request overwrite the second.

To properly receive the second without being overwrite, I would like to abort to first one. But if I understand "useAxios" properly, there is no straightforward way to do it.(?

Here is how I tried to abort it(with no success).
```
let { data, execute, abort } = useAxios(
        'xxxxx',
        {
            method: 'POST',
            data: xxxxx1
        },
        { immediate: false }
    )
    watchThrottled(
        () => xxxxxx, //some trigger
        () => {
            abort() // this will abort all future execution
            execute('xxxx', { data: xxx_some_condition_xxxx })
        },
        { throttle: 600 },
    )
 ```
 
 Thanks for any help in advance.

**Comment by laterdays** [comment]
@antfu   Can it be solved?

**Comment by Alfred-Skyblue** [comment]
I hope this issue can be reopened, I proposed a solution in #2728
