### ISSUE TITLE
export function `clean` in fn `useIntervalFn`

### ISSUE THREAD

**Issue by tachibana-shin** [vueuse/vueuse#2399]
### Clear and concise description of the problem

i am using `useIntervalFn` there are some cases where i want to completely cancel this function so this is necessary

### Suggested solution

add return `clean` in fn `useIntervalFn`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wumaorg** [comment]
In fact,  the timer is completely cleared when you use pause

**Comment by tachibana-shin** [comment]
> In fact, the timer is completely cleared when you use pause

OH that's right thanks for replying me
