### ISSUE TITLE
expiring async ref

### ISSUE THREAD

**Issue by silberGuy** [vueuse/vueuse#2410]
### Clear and concise description of the problem

Hello :)
I could not find an existing feature for my need, please correct me if I missed it.
My app is using a server generated JWT, that expires after 15 minutes. I use this token for certain requests to a different service, and I want to reuse the same token as long as it is alive. After expiration, I want to automatically regenerate a JWT **only** on the next usage.
More generically - I need a ref to automatically clear its value, and that an expiring value could be asynchronously generated  on demand.

### Suggested solution

I implemented for myself something similar to the following:

## Generic Composables

```ts
function useExpiringRef<T>(timeout: number) {
  const value = ref<T>()

  return computed({
    get() {
      return value.value
    },
    set(newVal: T | undefined) {
      value.value = newVal
      setTimeout(() => {
        value.value = undefined
      }, timeout)
    },
  })
}

function useAsyncExpiringRef<T>(fn: () => Promise<T>, timeout: number) {
  const value = useExpiringRef<T | Promise<T>>(timeout)

  return computed(() => {
    if (!value.value) {
      value.value = fn()
    }

    return value.value
  })
}
```

## Using in App Logic
```ts
async function createJWT(): Promise<string> {
  return await fetch('/generate-jwt').then(res => res.text())
}

const tokenAsyncRef = useAsyncExpiringRef(createJWT, 1000 * 60 * 15 // 15min)

// The function I use in the app
function doStuffWithAnotherService() {
  const token = await tokenAsyncRef.value
  doStuffWithToken(token)
}

```

### Alternative

A `setInterval` of 15 minutes that refetches the token

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by climba03003** [comment]
Feature look good, the use-case is a bit prone to error.

```ts
function checkExpire(timeout: number): boolean {
  const last = new Date()
  return {
    check() {
      return (last + timeout) > Date.now()
    },
    reset() {
      last = new Date()
    }
  }
}

function useExpiringRef<T>(timeout: number | Function) {
  const value = ref()
  const { check, reset } = typeof timeout === 'function' ? { check: timeout, reset() {} } : checkExpire(timeout)
  
  return computed({
    get() {
      // when true, it is expire. Return undefined
      if(check()) return undefined
      return value.value
    },
    set(newVal: T | undefined) {
      value.value = newVal
      // reset timer
      reset()
    },
  })
}
```

**Comment by silberGuy** [comment]
@climba03003 thanks for your response

I agree, using a function would make the usage better, but I do wonder - we lose the "active" update of the expired ref, that the `setTimeout` would have triggered, meaning that a template wouldn't rerender on expiration.

we can maybe export a function to update the timeout ms, that would also cover for reseting:
```ts
function useExpiringRef<T>(initialMs?: number): [Ref, (ms?: number) => void] {
  const valueRef = ref<T>()
  let ms = initialMs
  let timeout: ReturnType<typeof setTimeout> | undefined

  const setValTimeout = () => {
    if (ms) {
      timeout = setTimeout(() => {
        valueRef.value = undefined
        timeout = undefined
      }, ms)
    }
  }

  const compValue = computed({
    get() {
      return valueRef.value
    },
    set(newVal: T | undefined) {
      valueRef.value = newVal
      setValTimeout()
    },
  })
  
  const setMs = (newMs = ms) => {
    ms = newMs
    if (timeout) clearTimeout(timeout)
    setValTimeout()
  }

  return [compValue, setMs]
}
```

and for the async ref:
```ts
function useAsyncExpiringRef<T>(fn: () => Promise<[T, number]>) {
  const [value, setMs] = useExpiringRef<T | Promise<T>>()

  const generateValue = async () => {
    const [val, ms] = await fn()
    setMs(ms)
    return val
  }

  return computed(() => {
    if (!value.value) {
      value.value = generateValue()
    }

    return value.value
  })
}

const tokenAsyncRef = useAsyncExpiringRef(async () => {
  const { token, expiry } = await createJWT()
  return [token, expiry]
})
```

**Comment by climba03003** [comment]
Your usage of timeout will setup brunch of floating function.
You need to keep checking in set and remove the previous one. Otherwise, it will clear in an unintended way.

I use lazy removal as intended to reduce the work.

**Comment by climba03003** [comment]
> I do wonder - what kind of floating function will we have?

You need to use `clearTimeout` whenever you call the `computed.set`.
Proper cleanup are necessary, otherwise when multiple call to update the `value`. You will stack up unwanted `timeout` that clear the value.

**Comment by silberGuy** [comment]
seems solvable:
```ts
function useExpiringRef<T>(initialMs?: number): [Ref, (ms?: number) => void] {
  const valueRef = ref<T>()
  let ms = initialMs
  let timeout: ReturnType<typeof setTimeout> | undefined

  const setValTimeout = (newMs?: number) => {
    if (newMs !== undefined) ms = newMs
    if (timeout) clearTimeout(timeout)
    if (ms) {
      timeout = setTimeout(() => {
        valueRef.value = undefined
        timeout = undefined
      }, ms)
    }
  }

  const compValue = computed({
    get() {
      return valueRef.value
    },
    set(newVal: T | undefined) {
      valueRef.value = newVal
      setValTimeout()
    },
  })

  return [compValue, setValTimeout]
}
```
