### ISSUE TITLE
functions piping hook

### ISSUE THREAD

**Issue by OMARIZEM** [vueuse/vueuse#2411]
### Clear and concise description of the problem

As Vueuse user i want to be able to call a series of functions in which each takes the previous function result as an argument  (especially non-async functions because we can solve issue for async functions using promise chaining).

please check: https://dev.to/rajnishkatharotiya/how-to-execute-functions-via-pipeline-38g8

**i would like to submit a PR for this issue.**

### Suggested solution

Add a composable hook with the following features:

1. call list of functions using pipeline pattern
2. accept an error callback
3. enable/disable async mode ( if the async mode is enabled the pipeline will return a promise )

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by climba03003** [comment]
Are you proposing `pipeline` operator?
https://github.com/tc39/proposal-pipeline-operator

**Comment by sun0day** [comment]
Interesting idea!

Can you add some js code to show how to use function pipeline in vueuse.

**Comment by sun0day** [comment]
Some use-cases demo.

**Comment by OMARIZEM** [comment]
Here's one of the use cases that i was working on this week which inspires me to suggest this composable, we have a POS system where i had to make some orders, to create a new order we have to do the following:

1. build request ( a factory that creates data from our store )
2. apply some discounts and calculations based on the created request object
4. send a request to the terminal if it required ( again based on the created request)
5. create order/sale
6. we passe created order through another process which will need pipelines too but i'll explain how we can use it in the previous steps.


**we can do this process using a pipeline easily**

```
// order.request.factory.ts`
export function createRequest(): TCreateOrderRequest {
 // our logic
}
```

```
// finance.ts`
export function applyFiscalisation(request: TCreateOrderRequest): TCreateOrderRequest {
 // our logic
}
```

```
// payment.service.ts`
export function checkTerminal(request: TCreateOrderRequest): TCreateOrderRequest {
 // here we can decide if we'll need to pay with the terminal or just ignore this request 

return {...request};
}
```

```
// use.order.service.ts
export function createOrder(request: TCreateOrderRequest): TOrder {
}
```

------------------------------------------------------------------------------------------
```
// TheCheckout.vue

<script setup lang="ts">
// let's assume that all functions are imported
import {usePipe} from "@vueuse/core";

const {onError , onSuccess , pipe , addFunction, success} = usePipe();

// add functions to pipe ( we can add directly with constructor usePipe([createRequest, applyFiscalisation, checkTerminal]); )
addFunction(createRequest);
addFunction(applyFiscalisation);
addFunction(checkTerminal);

// execute
pipe();

onError((e) => {
// handle error
})

onSuccess(async (request: TCreateOrderRequest) => {
 const response =  await createOrder();
   // more logic
})


</script>
```

i hope this example helps to understand the purpose of the suggested composable.

**Comment by sun0day** [comment]
See https://rxjs.dev/api/index/function/pipe,  maybe `@vueuse/rxjs` can help you.

**Comment by OMARIZEM** [comment]
@sun0day i'm trying to add something like pipe from "rxjs" to "vueuse"
