### ISSUE TITLE
这么优秀的库，为什么没有中文文档？

### ISSUE THREAD

**Issue by whyfail** [vueuse/vueuse#2415]
### Clear and concise description of the problem

Vue也好，VueUser也好，都是非常优秀的框架或者库，Vue的初衷也是为了让前端开发更加简单，对于新入门的人来说，一份好的文档更是不可或缺的，每次我给一些新人介绍这个库多么优秀时，他们往往因为这个库没有中文文档而选择放弃使用，我感到非常可惜。

### Suggested solution

如果能在开发之余添加一份中文文档，那或许会收获更多的粉丝和Star^_^

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
https://vueuse.org/why-no-translations.html
