### ISSUE TITLE
Default values in URL search params.

### ISSUE THREAD

**Issue by dm1tr** [vueuse/vueuse#2420]
### Clear and concise description of the problem

Hi Guys.

I ran into a problem setting the initial value of the filter, for example, today's date using `useRouteQuery`.

If it's necessary to set the initial value for `useRouteQuery` as today, the date doesn't display in the URL query string, which in turn breaks the constancy of the link. If i set `useRouteQuery` default value as something empty ("", null, etc.), and then change the value to the necessary value, then this leads to sending an additional request with an empty value, if reactive value is used in the request.

Thanks.

### Suggested solution

I suggest extending `useRouteQuery`, with a flag that will be responsible for displaying the default value in the URL or not. What do you think about it?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by GabriMcNab** [comment]
Hi! Out of curiosity, why was this closed? I also think that the default value should be displayed in the URL

**Comment by dm1tr** [comment]
Hello @GabriMcNab,
Sorry for the long answer. In fact, after default values I also needed transformation functions for arrays and other data types besides strings from URL query, so I decided to use another package, and then wrote a solution for myself. 

I probably shouldn't have closed the issue, but i closed it so as not to distract the authors of the package. I think it's possible to open it again.

**Comment by yakobe** [comment]
@demershov and @GabriMcNab did you find a work around for this? It really feels like the default value should show in the url immediately.

**Comment by BenJackGill** [comment]
Yes this should be re-opened. I was baffled why the default it did not appear in the URL.

@demershov in the mean time can you share your work around?
