### ISSUE TITLE
useWebWorker not working  

### ISSUE THREAD

**Issue by CatsAndMice** [vueuse/vueuse#2421]
### Describe the bug

使用`useWebWorker`方法与使用原生`Worker`执行结果不一致。
<img width="804" alt="image" src="https://user-images.githubusercontent.com/58327088/201109816-2aba6acf-6b6e-4241-8e3a-848c66aa8c86.png">
问题出在：`window`为`undefined`,判断`window`这个`if`条件失败;  `const {window = defaultWindow} = options ?? {}`这行代码，打包被转化成`const {window = defaultWindow} = options!=null?options:{}`,没有判断options为`undefined`的情况。

这个bug我已经提交过PR https://github.com/vueuse/vueuse/pull/2408 ,但现在被关闭了，希望作者能看下是否能给我合并下，解决这个bug

### Reproduction

https://codepen.io/lihai-boop/pen/rNKyeMg

### System Info

```Shell
browsers
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by climba03003** [comment]
`options!=null` is identical to `options !== undefined && options !== null`.
Please note that there are only one `=` in the code. It will coerce the types and do loose checking.

**Comment by CatsAndMice** [comment]
Learned

**Comment by CatsAndMice** [comment]
@climba03003 重新补了个PR

**Comment by CatsAndMice** [comment]
@antfu
