### ISSUE TITLE
useRefHistory serialize 

### ISSUE THREAD

**Issue by AndrewMeleka** [vueuse/vueuse#2425]
### Describe the bug

Hi, 
I was working in redo, undo 
But i found a series problem after undo or redo in the class object i lost the functions of object example:

const formLayout = ref(new FormLayout())
const {undo} = useRefHistory(formLayout, {
deep: true
})

After undo the formLayout becomes an pure object without be an Instance of  class so i lose functions

any help, 
thank u

### Reproduction

Soom

### System Info

```Shell
System
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AndrewMeleka** [comment]
let's add to your following example function called "sayHi"
and console.log after undo() or redo() function
**it will say dum.value.sayHi is not a function**

here is an example:
https://playcode.io/1008690

**Comment by azaleta** [comment]
https://github.com/vueuse/vueuse/blob/main/packages/core/useManualRefHistory/index.md

use `klona` as recommend

**Comment by AndrewMeleka** [comment]
Thank you for your response,
my case was too complex in OOP but finally solved 
and here is my solution

```
const formLayoutStore = ref(new FormLayout());
const formRefHistory = useManualRefHistory(formLayoutStore, {
  capacity: 15,
  clone: klona
});
```
