### ISSUE TITLE
New Feature: `useEventListenerOnce`

### ISSUE THREAD

**Issue by lsdsjy** [vueuse/vueuse#2429]
### Clear and concise description of the problem

Add a new composable for one-shot event listeners, which behaves like `watchOnce`. It can be useful in scenes like:
```js
function onClick() {
    elStyle.value = { height: '100px' };
    useEventListener(el, 'transitionend', () => {
       // ...
    })
}
```

### Suggested solution

Add a new composable called `useEventListenerOnce`, which has the same signature as `useEventListener`, and can be simply implemented as:
```ts
let stop
fn = (...args) => {
  fn(...args)
  stop()
}
stop = useEventListener(..., fn, ...);
return stop
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You may use `useEventListener('foo', fn, { once: true })`. I don't feel it's worth it to bring yet another new function.

**Comment by lsdsjy** [comment]
Nice! Didn't notice that option before.
