### ISSUE TITLE
Incorrect type definition for `formatDate`

### ISSUE THREAD

**Issue by dream2023** [vueuse/vueuse#2435]
### Describe the bug

```ts
// formatDate type 
//  `options`  is a required parameter
declare const formatDate: (date: Date, formatStr: string, options: UseDateFormatOptions) => string;
```

```ts
// source code
//  `options`  is an optional parameter
export const formatDate = (date: Date, formatStr: string, options: UseDateFormatOptions = {}) => {
 // ...
}
```

### Reproduction

no need

### System Info

```Shell
no need
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by huynl-96** [comment]
You could try to re-run `pnpm run build:types`
I've just had a quick check on `v9.6.0`

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/15758406/203885881-0c07d383-e2b9-4526-b849-9b2a0588a4d4.png">
