### ISSUE TITLE
Question: What is the proper way to use useVirtualList in a table with a static header?

### ISSUE THREAD

**Issue by nockstarr** [vueuse/vueuse#2437]
### Clear and concise description of the problem

What is the proper way to use `useVirtualList` in a table with a static header?
I'v been trying to get this for weeks now with no success... I have attempted with normal `table`, tables of `div`s and two tables (one for the head and one for the body). Any suggestions?

### Suggested solution

Im stuck

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by begedin** [comment]
I'm not sure it can be done cleanly, as tables use `display: table` as a layout, meaning stuff like height and width are more suggestions than rules to follow.

You could set the table to display block, or you can have one table, wrapped in a div (which scrolls) as the items, and a separate as a header, while trying to sync cell dimensions between the two.

**Comment by nockstarr** [comment]
`position: sticky;` and `top: 0;` did the trick. Good enough for my use case.
```
<template>
	<div v-bind="containerProps" class="" style="height: 50vh; overflow-x: auto; white-space: nowrap;">
	  <div v-bind="wrapperProps">
		<table>
		  <thead>
		  <tr>
			<th>#</th>
		  </tr>
		  </thead>
		  <tbody>
		  <tr v-for="{ index, data } in list" :key="index">
			<td>{{index}}</td>
		  </tr>
		  </tbody>
		</table>
	  </div>
	</div>
</template>

<style scoped>
th {
  position: sticky;
  top: 0;
}
table {
  width: 100%;
}
th:last-of-type {
  width: 100%;
}
</style>
```

**Comment by begedin** [comment]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/1925540/204052712-2c9e6775-f206-42e7-ac05-09950a74c443.png">

That's a cool approach!

I tried a minimal example with my proposed solution, but yours seems cleaner. Here's mine if someone finds it useful.

```vue
<template>
  <table>
    <thead>
      <tr>
        <th>Foo</th>
        <th>Bar</th>
        <th>Baz</th>
      </tr>
    </thead>
  </table>
  <div class="container" v-bind="containerProps">
    <div v-bind="wrapperProps">
      <table>
        <tbody>
          <tr v-for="item in list" :key="item.data">
            <td>{{ `Foo-${item.data}` }}</td>
            <td>{{ `Bar-${item.data}` }}</td>
            <td>{{ `Baz-${item.data}` }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { useVirtualList } from '@vueuse/core'
import { ref } from 'vue';
const items = ref([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
const { list, containerProps, wrapperProps } = useVirtualList(items, { itemHeight: 26, overscan: 1 })

</script>
<style>
.container {
  height: 300px;
  width: 400px;
  display: flex;
  flex-direction: column;
  align-items: start;
}

table {
  color: black;
  position: relative;
  padding-top: 26px;
}

table thead {
  font-weight: bold;
}

table th,
table td {
  width: 100px;
  border: 1px solid red;
}
</style>
```
