### ISSUE TITLE
usewebsocket

### ISSUE THREAD

**Issue by Ale6333499** [vueuse/vueuse#2444]
### Describe the bug

usewebsocket中的最新data消息只能观看不能使用

### Reproduction

11

### System Info

```Shell
{
    "value": ""
}
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HongxuanG** [comment]
为啥不能使用？

**Comment by Ale6333499** [comment]
> 

新手不太懂，我看文档这个好像是只读，求解答
