### ISSUE TITLE
[rxjs] Add watcher options as argument of "from" method

### ISSUE THREAD

**Issue by d-corler** [vueuse/vueuse#245]
We don't have the ability to configure the watcher inside the "from" method.

I suggest to add an optional argument :

```ts
// packages/rxjs/from/index.ts
import { from as fromRxjs, fromEvent as fromEventRx, ObservableInput, Observable } from 'rxjs'
import { filter, mergeMap } from 'rxjs/operators'
import { Ref, isRef, watch, WatchOptions } from 'vue-demi' // <-- Add type

export function from<T>(value: ObservableInput<T> | Ref<T>, options?: WatchOptions): Observable<T> { // <-- Add optional argument
  if (isRef<T>(value)) {
    return new Observable((subscriber) => {
      watch(value, val => subscriber.next(val), options) // <-- Pass options
    })
  }
  else {
    return fromRxjs(value)
  }
}

[...]
```
However, I fear that this may mislead people into believing that options are also available for standard observables (fromRxjs). Does someone have a suggestion 🤔 ?

**Comment by antfu** [comment]
Wondering the reason to have the options, to configure `flush`? I think it's ok to have the options as long as we add proper jsdoc to describe that is the Vue watch options. Or on the other hand, we can have a more explicit API like `fromRef`.

**Comment by mdbetancourt** [comment]
to achieve the effect of 
{
    flush: 'post'
}
you can do it at the rxjs way with

```ts
from(refValue).pipe(
  waitUntil(rendered()) // i guess 'withLatestFrom' could do the job, rendered could be an observable which emit when the dom is updated
).subscribe(...)
```

**Comment by antfu** [comment]
Close for inactive.
