### ISSUE TITLE
The generic type for useFirestore() cannot have optional properties

### ISSUE THREAD

**Issue by BenJackGill** [vueuse/vueuse#2450]
### Describe the bug

When typing `useFirestore()` with a generic I cannot use an interface that has optional properties because TypeScript throws this error:

> No overload matches this call

In the examples below the `User` interface has a required `name` property which causes typescript to throw the error.

```TypeScript
interface User {
  id?: string;
  name: string; // <-- When this property is required the error will show, changing it to optional removes the error
}

const userQuery = doc(db, 'users', 'my-user-id');
const userData = useFirestore<User>(userQuery); // <-- The error shows here on "userQuery"
```

I have found one workaround, but it's not great.

You can use `useFirestore(userQuery) as Ref<User>` which removes the error and gives it the correct type.

But doing this is not a good solution because I'm basically telling the compiler "I know better" than what the compiler is saying. So it would be much better to have proper typing without resorting to this workaround.

```TypeScript
interface User {
  id?: string;
  name: string;
}

const userQuery = doc(db, 'users', 'my-user-id');
const userData = useFirestore(userQuery) as Ref<User>; // <-- See changes made here
```

I think this is a bug that needs addressing.

### Reproduction

I cannot get stackblitz to work with VueUse and typescript. If a setup is provided I will make a reproduction for the above bug.

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 46.80 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /opt/homebrew/bin/node
    npm: 8.12.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.5
    Safari: 16.1
  npmPackages:
    @vueuse/core: ^9.5.0 => 9.5.0 
    @vueuse/firebase: ^9.1.0 => 9.1.0 
    vue: ^3.2.37 => 3.2.37
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
this is not vueuse problem,I think.
```
const userQuery = doc(db, 'users', 'my-user-id');
```
you missing type in this line -> this will ref to type `DocumentReference<DocumentData>` instead of `DocumentReference<User>`

Then you passing this object to useFirestore<User>(which must have a type `DocumentReference<User>` as you declare), this will cause the error.

you should init a query with type `User`

firebase have these methods(param is not same, don't use firestore so I could not provide implements):
```
export declare function doc(firestore: Firestore, path: string, ...pathSegments: string[]): DocumentReference<DocumentData>;
export declare function doc<T>(reference: CollectionReference<T>, path?: string, ...pathSegments: string[]): DocumentReference<T>;
```

**Comment by BenJackGill** [comment]
Thanks, this pointed me in the right direction.

I created a full explanation of how to get around this issue here: https://stackoverflow.com/questions/74456704/how-to-type-usefirestore-with-optional-properties

But I will copy the essential code below for anyone else who is looking here...

In short - `withConverter` can be used on the end of Firestore `doc` or `collection` methods to correctly type them. It takes a single `converter` argument. And what is shown below is a re-usable "generic converter" that takes an Interface of your choice.

So you put `.withConverter(converter<MyInterfaceHere>())` on the end of `collection` or `doc` and voila! You have type safety!

Here is the full example:

```lang-TypeScript
interface User {
  id?: string;
  name: string;
}

const converter = <T>() => ({
  toFirestore: (data: PartialWithFieldValue<T>) => data,
  fromFirestore: (snap: QueryDocumentSnapshot) => snap.data() as T,
});

const userDocRef = doc(db, 'users', 'my-user-id').withConverter(
  converter<User>()
);
const userData = useFirestore<User>(userDocRef);
```

Now `userData` has a type of `Ref<User | null | undefined>` and you can access all the `User` properties without error.

It's Firestore with all the type safety you love from TypeScript!
