### ISSUE TITLE
`reactifyObject` doesnt apply methods.

### ISSUE THREAD

**Issue by DaniGTA** [vueuse/vueuse#2457]
### Describe the bug

```
const test = reactifyObject({
  a: "test",
  t: ()=> {
    console.error("test")
  }
});
test.t();
```

`test.t();` doesn`t work.

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAnJMAAzk9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKnFeDArGQMPkGWhshQCKRIBRgxGYwEQmms2GLLZHMQJPJlI2iG2e0OAF1mEY6AZDWhQABBMBgSYLdCgVIagwQVJEAA8VGyAB1zCp4JIqABeFMgAB+NSiFBmBgzEDAFAALHm0yoVGBY9xcyAZkqbNISx3EPVgrRkF32xxa+ndC3xNYbCP67UlS28PJWNOVAA+OsqBPiurJ3CpFSx0qeFsADTzKjQxEM5BbmzPwzX6c3rG3ZjjaQPR7zAE0zxer4gWxCO8HwTYZk2IFdnkFaQiDoDU6mkFRgH8G4AFl2BuRgVGsaBZCMEIAHlSl2KVEIOGoOFmFQAHI7Rudk6kQai0zgzUOEQrcOB3N8KKo6jJmGTjuNScNyGY2x5GQRDUiklRs2wxBcLofCiJI6VtGAdcIDQFQ8xk6Q80YddpB07R7GzFckPXes2zYf1Jh7SiOG0PSUAMkB7HXA40wOewAG4030yZpDMgKJOwOzEAcjgnJckB9MaPNPPC2TkM2LCwnI+S8XQvEzPpZghNfESI0DeLaEbN9E3A9dZ2kedF2XUp4BbIJ4D6CgAFYyTJNxKhgNAqH6rqeuXIx-U2FtC1LZdUk2eq824IdlzAFtEpAddSm3HsW0o-gaCoEcH3rBNkEgcw5oWkAq02Aw8xXYBkMvAxVAOA5QLOiBsGOjdPout0ruQPA+o4Aa2o64kepBgbvGgYIQhGs88BbTt1pXXLIUe-cIEPMs3o+86QLA7JIOYCdfiIGhfWwRAAAVKMGDT1w-AwdIBaRJGweAjPTZ7yB0gA5Ug8EPDged8+k3qAA

### System Info

```Shell
Check vueuse link.
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sunupdong** [comment]
It should be to use `test.t().value`, followed by `.value`

**Comment by syy11cn** [comment]
> It should be to use `test.t().value`, followed by `.value`

Agree with this comment. 👍 

As you can see below, `test.t` is a function returns a `ComputedRef`. Only when you read the `.value` property will the function in `computed` be called.

So, just use `test.t().value` to call the function.

![image](https://user-images.githubusercontent.com/57290456/204098736-4acb3309-4a6d-4be9-8e5d-e02981229f81.png)

**Comment by DaniGTA** [comment]
Okay, I think I got it. Thanks for the explanation.
