### ISSUE TITLE
(ssr) useWindowSize should not use an initialWidth of Infinity

### ISSUE THREAD

**Issue by pimlie** [vueuse/vueuse#2461]
### Describe the bug

Was using something similar to the following code:

```js
const { width } = useWindowSize()

watchEffect(() => {
  const columnCount = Math.floor(width.value / 200)

  const columns = []
  for (let i = 0; i < columnCount; i++) {
    columns.push([])
  }
})
```

and it took a while to understand why my Nuxt3 pages did not load from the server and I had to disable this watcher, load page from server and re-enable this watcher after which it worked thx to HMR on the client.

Looking at the code it turns out that window.width is Infinity on the server, so the above code results in an infinite loop. I dont have a good proposal for what the value should be, I guess either 0 or the most used screen resolution would be the best?

### Reproduction

See above

### System Info

```Shell
Nuxt 3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JMaylor** [comment]
FYI you can set an initial width for this composable with an `initialWidth` option:

```
const { width } = useWindowSize({ initialWidth: 1600 })
```

Maybe this helps solve your issue?

**Comment by pimlie** [comment]
Thanks @JMaylor, I have actually switched my implementation to not use the above code / useWindowSize at all. But this issue  / caveat still exists I guess? But feel free to close it if you feel thats warranted :)
