### ISSUE TITLE
useAbortController

### ISSUE THREAD

**Issue by rwv** [vueuse/vueuse#2463]
### Clear and concise description of the problem

`useAbortController` that will call `controller.abort()` automatically on unmounted.

### Suggested solution

similar to this:

```
const { controller } = useAbortController();
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by rwv** [comment]
P.S. I can work on a PR.

**Comment by chaii3** [comment]
> P.S. I can work on a PR.

Could you add more functionality?
It looks like it easier without the composition

**Comment by zkulbeda** [comment]
I suggest embeding `AbortController` in functions with `onCleanup` argument such as `watch` and `watchEffect`. Also they will catch `DOMExeption` with name `AbortError` and ignore it.

Use case and implementation:
```ts
function watchWithSignal(source, cb, options = {}){
  return watch(source, async (value, oldValue, onCleanup) =>
  {
    try {
      const controller = new AbortController();
      onCleanup(() => { 
        controller.abort();
      });
      await cb(value, oldValue, controller.signal, onCleanup);
    } catch (error) {
      if (error instanceof DOMException && error.name == "AbortError") {
        return;
      }
      throw error;
    }
  }, options);
}

watchWithSignal(reference, async (value, oldValue, signal) => {
    result.value = await (await fetch("https://example.com/"), { signal }).json();
});

watchEffectWithSignal(async (signal) => {
    result.value = await (await fetch("https://example.com/", {
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(reference.value),
      signal,
    })).json();
});
```
The fetch request will be aborted as soon as the reference value changed.

**Comment by rwv** [comment]
> > P.S. I can work on a PR.
> 
> Could you add more functionality? It looks like it's easier without the composition

Add reactive aborted

``` js
aborted = ref(controller.aborted)
controller.signal.addEventListener("aborted", ()=>{aborted=true})

# onUnmounted remove event listener 
```

Also, maybe we could add a parent signal. For example:
```
parentSignal.addEventListener("aborted",()=>{controller.abort()})
```

**Comment by andrewvasilchuk** [comment]
@antfu do you think it's reasonable to work on the `watchEffectWithSignal` composable implementation? I usually need to cancel a previous request, which is still in flight, when a ref value changes. Also the possible names are: `watchAbortableEffect`, `watchEffectAbortable`, `watchEffectCancellable`.
