### ISSUE TITLE
The layout switch of the usevirtuallist component causes the page to get stuck

### ISSUE THREAD

**Issue by daLeiStrive** [vueuse/vueuse#2481]
### Describe the bug

When there is too much content on the page, the scrolling plug-in will cause a stuck delay and a poor user experience

### Reproduction

No link

### System Info

```Shell
When moving elements, avoid modifying the top, right, bottom and left attributes. Instead, use transform: translate()
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
We are deprecating `useVirtualScroll` in favor of https://github.com/Akryum/vue-virtual-scroller

See https://github.com/vueuse/vueuse/pull/2658
