### ISSUE TITLE
[useVirtualList] allow group list

### ISSUE THREAD

**Issue by flrnt** [vueuse/vueuse#2492]
### Clear and concise description of the problem

I wanna use virtualList to display a list of grouped elements. Like ` { fruits: ['bananas', 'apple'], vegetables: ['potatoes', 'tomatoes'], ...  } ` but it's not accepting this kind of object at first.
Note that I render this grouped list into details elements allowing collapsing potentially n elements from the list.

### Suggested solution

Enable group list / collection

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
We are deprecating `useVirtualScroll` in favor of https://github.com/Akryum/vue-virtual-scroller

See https://github.com/vueuse/vueuse/pull/2658
