### ISSUE TITLE
`useWebSocket` doesn't auto-reconnect when it doesn't receive a pong within its specified timeout duration

### ISSUE THREAD

**Issue by jasontheiler** [vueuse/vueuse#2506]
### Describe the bug

In its current state the [heartbeat's pong timeout](https://github.com/vueuse/vueuse/blob/cfcc295261f463c74d80fcb9863cb4bdd7e673b9/packages/core/useWebSocket/index.ts#L275) calls the composable's `close()` function to close the WebSocket connection if it doesn't receive a pong within its specified timeout duration. The `close()` function unfortunately sets the composable's internal `explicitlyClosed` variable to `true`, which causes the composable to not auto-reconnect. Also, it closes the WebSocket connection gracefully and doesn't throw an error.

This implementation could be intentional, so it might now even be a bug per se, but I doubt it because the comment inside the heartbeat's pong timeout callback even states: _auto-reconnect will be trigger with ws.onclose()_
This just doesn't actually happen because of the aforementioned situation.

In my opinion the composable should throw an error that will be caught by its `onError()` function and attempt to auto-reconnect after it reached the pong timeout.

The creation of a minimal reproduction is a little bit more effort than I think would be worth it for this issue, but if you'd still require one to be absolutely sure, I'll create a repo for it.

### Reproduction

https://github.com/vueuse/vueuse/blob/cfcc295261f463c74d80fcb9863cb4bdd7e673b9/packages/core/useWebSocket/index.ts#L275

### System Info

```Shell
System:
    OS: Linux 4.19 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
    Memory: 20.90 GB / 24.99 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 18.6.0 - ~/.local/state/fnm_multishells/16636_1670247225995/bin/node
    Yarn: 1.22.19 - ~/.local/state/fnm_multishells/16636_1670247225995/bin/yarn
    npm: 8.13.2 - ~/.local/state/fnm_multishells/16636_1670247225995/bin/npm
  npmPackages:
    @vueuse/core: ^9.5.0 => 9.5.0
    @vueuse/math: ^9.5.0 => 9.5.0
    @vueuse/nuxt: ^9.5.0 => 9.5.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jasontheiler** [comment]
Are there no other opinions about this issue? :/

**Comment by Poliziano** [comment]
I would love to see this fixed. Part of the reason my team wanted to use this composable was for the auto-reconnect logic. If the pong timeouts out (which is likely if you lose WiFi, for example) then I would expect it to attempt to re-establish a connection using the configuration defined in `autoReconnect`.

**Comment by jasontheiler** [comment]
Why does the stale bot close issues as "completed" when nothing is actually completed?
