### ISSUE TITLE
useScreenSafeArea not working on iphone 13 device (os 15)

### ISSUE THREAD

**Issue by lhoucinecherif** [vueuse/vueuse#2511]
### Describe the bug

useScreenSafeArea doesn't work on iphone 13 device, (using lambdatest.com), the demo page always show 0px for all variables

### Reproduction

open the https://vueuse.org/core/useScreenSafeArea/#demo page on iphone device or a device testing tool like lambdatest.com or browserstack

### System Info

```Shell
the current deployed vueuse on official website demo: 9.6.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by okxiaoliang4** [comment]
It's a doc bug. because does't set viewport-fit=cover

**Comment by zenonux** [comment]
useScreenSafeArea top 一直为0，要考虑constant和env的兼容性吧
