### ISSUE TITLE
`watchDebounced` is not working with Vue 2.7 using Nuxt (2.15.8)

### ISSUE THREAD

**Issue by imfaisalkh** [vueuse/vueuse#2514]
### Describe the bug

I've created a minimal example to demonstrate the issue: https://codesandbox.io/s/wild-pond-ew835y?file=/composables/useBookings.js

In this example you can see that regular `watch` method triggers for each change in `counter` variable; but `watchDebounced` is not getting triggered at all.

It should ideally trigger with the debounced interval.

Note: i'm using `<script setup>` tag in `pages/index.vue` component.

### Reproduction

https://codesandbox.io/s/wild-pond-ew835y?file=/composables/useBookings.js

### System Info

```Shell
System:
    OS: Linux 5.13 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 4.93 GB / 62.72 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Sun79** [comment]
I encountered the same issue. After troubleshooting, I found that the problem was caused by the vue module loaded by vue-demi and the vue module loaded in the project not being the same JavaScript file. By using resolve.alias to force the loading of the cjs module, this issue can be resolved.
```js
{
  resolve: {
    alias: {
      '@vueuse/core': '@vueuse/core/index.cjs',
    },
  }
}
```
