### ISSUE TITLE
useGeolocation not working properly with Firefox

### ISSUE THREAD

**Issue by gimyboya** [vueuse/vueuse#2523]
### Describe the bug

Assuming we have the following code:
```vue
<script setup lang="ts">
import { ref, Ref } from "vue";
import { useGeolocation, usePermission } from "@vueuse/core";

let coordinates: Ref<GeolocationCoordinates | undefined> = ref(undefined);
let geolocationError: Ref<GeolocationPositionError | null> = ref(null);
let geolocationStart: undefined | (() => void) = undefined;
let geolocationStope: undefined | (() => void) = undefined;

const geolocationAccess = usePermission("geolocation", {
  controls: true,
});

function promptPermissions() {
  const { coords, error, resume, pause } = useGeolocation({
    enableHighAccuracy: true,
  });
  coordinates = coords;
  geolocationError = error;
  geolocationStart = resume;
  geolocationStope = pause;
}
</script>

<template>
  <div class="wrapper">
    <pre lang="json">{{
      JSON.stringify(
        {
          geolocationAccess: {
            isSupported: geolocationAccess.isSupported.value,
            state: geolocationAccess.state.value,
          },
        },
        null,
        2
      )
    }}</pre>

    <p v-if="!geolocationAccess.isSupported.value">
      Your Browser doesn't support geolocation
    </p>
    <p
      v-if="
        geolocationAccess.isSupported.value &&
        (geolocationAccess.state.value === undefined ||
          geolocationAccess.state.value === 'prompt')
      "
      class="my-1 text-sm italic"
    >
      We need permissions to be grated to use the geolocation feature.
      <button @click="promptPermissions">Prompt me</button>
    </p>
    <p
      v-if="
        geolocationAccess.isSupported.value &&
        geolocationAccess.state.value === 'denied'
      "
    >
      Geolocation permissions have been denied. you can grant permissions again
      by your settings. At the start of your address bar
    </p>
  </div>
</template>

```

It works fine with chrome where we can prompt the user and check if the permissions are granted
However with Firefox it doesn't seem to work as expected as it only detect the change when the user click on `Remember my choice` option. if they allow temporary or deny the change isn't picked up.
 

### Reproduction

https://codesandbox.io/p/sandbox/lingering-snowflake-84gzww?selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A32%2C%22startColumn%22%3A19%2C%22startLineNumber%22%3A32%7D%5D&file=%2Fsrc%2FApp.vue&workspace=%257B%2522activeFileId%2522%253A%2522cl8oq844p000plqd96ssl8lu7%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252FApp.vue%2522%252C%2522%252Fsrc%252Fmain.js%2522%252C%2522%252Fpackage.json%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clbj55sl600573b6h5s8ct1ja%2522%253A%257B%2522key%2522%253A%2522clbj55sl600573b6h5s8ct1ja%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clbj5b1v4014m7rd96wa6bv4v%2522%252C%2522key%2522%253A%2522clbj5b1nj00ru3b6h9j2oeqk8%2522%252C%2522isMinimized%2522%253Atrue%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clbj55sl600583b6hovt6umta%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clbj55sl600573b6h5s8ct1ja%2522%252C%2522spacesOrder%2522%253A%255B%2522clbj55sl600573b6h5s8ct1ja%2522%255D%257D

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 114.99 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v14.20.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Firefox: 107.0.1
    Safari: 16.1
  npmPackages:
    @vueuse/core: ^9.4.0 => 9.5.0 
    @vueuse/nuxt: ^9.4.0 => 9.5.0
```
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
I believe this is a somewhat expected outcome. It seems like firefox will require you to ask for permission each time you want to check the location of the user unless you tell it to remember your choice. Either way, this is not something that can be fixed by VueUse and is a browser level issue.
