### ISSUE TITLE
Is UseDraggable really using storage for initial value?

### ISSUE THREAD

**Issue by bergden-resonai** [vueuse/vueuse#2527]
### Describe the bug

I'm trying to follow the example here:
https://github.com/vueuse/vueuse/blob/cfcc295261f463c74d80fcb9863cb4bdd7e673b9/packages/core/useDraggable/index.md?plain=1#L39
But with `storage-type="local"` (how can I see the legal values for this type other than `session`?)

I do see an entry created by the name I passed for `storage-key` with x,y same as the `initial-value`, but they're never updated, so upon refresh the element returns to the same place.

Following is a video of the [example in the documentation](https://vueuse.org/core/useDraggable/) not working:

https://user-images.githubusercontent.com/37291459/206917313-2df03c0f-a242-4f81-b744-a4fd93a9f3c0.mp4

I can't find anything in the code to indicate this should work, but I also couldn't find how the localStorage entry is created to begin with...

### Reproduction

https://stackblitz.com/edit/vitejs-vite-4ye5qc/?file=package.json,src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 76.88 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 100.0
    Safari: 16.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
Fixed in https://github.com/vueuse/vueuse/pull/2575
