### ISSUE TITLE
useCounter loop option

### ISSUE THREAD

**Issue by SwatDoge** [vueuse/vueuse#2528]
### Clear and concise description of the problem

Right now, `useCounter` has 2 additional options to set the minimum and maximum counting level:

```ts
useCounter(props.index, { min: 0, max: 3));
```

When the counter reaches the maximum value, it will stay at its maximum value when you try to increase it. In some it is useful to "overflow" the number back to 0, and vice versa. 

### Suggested solution

An additional option for useCounter, which enables this behaviour.

```ts
useCounter(props.index, { min: 0, max: 3, loop: true));
```

### Alternative

Not being a lazy developer.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
https://github.com/vueuse/vueuse/pull/2531#issuecomment-1354969596
