### ISSUE TITLE
`useUrlSearchParams` issue in Vue 2.7

### ISSUE THREAD

**Issue by george-ayris** [vueuse/vueuse#2533]
### Describe the bug

Following the [documentation](https://vueuse.org/core/useurlsearchparams/?foo=bar&vueuse=awesome#type-declarations), assigning to the `params` object in Vue 2.7 doesn't appear to be updating the URL.

No working [Vue 2.7 repo](https://codesandbox.io/s/romantic-morning-qbv91b?file=/src/App.vue), where I can't see the URL change.

Equivalent working [Vue 3 repo](https://codesandbox.io/s/zen-feather-d4sno2?file=/src/App.vue:0-707), where I can see the URL change.

I'm slightly wary this is a reactivity system difference issue, but hopefully I've not made any mistakes in how I'm using the library?

Thanks for your help.

### Reproduction

https://codesandbox.io/s/romantic-morning-qbv91b?file=/src/App.vue

### System Info

```Shell
From my development environment where I've also observed the issue.  

  System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 122.36 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.4.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 105.0.1
    Safari: 16.1
  npmPackages:
    @vueuse/core: ^9.6.0 => 9.6.0 
    vue: ^2.7.13 => 2.7.13
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by workkk98** [comment]
looks like vue3 execute `write` function, but vue2 doesn't.

seems to be here.
![image](https://user-images.githubusercontent.com/40513678/209641911-4224e545-e98e-4c70-8552-894552ae1e1b.png)

**Comment by workkk98** [comment]
I think it's because vue3 use proxy, though initial value is empty object, assign some value, callback will invoke.
But vue2 use defineProperty, only can watch predefined key. so in this case, initial value is a empty object.And u change some  value, will not work.

**Comment by workkk98** [comment]
This is a example. https://codesandbox.io/s/vue-2-playground-forked-ielskg?file=/src/main.js

**Comment by george-ayris** [comment]
I was hoping to at least get a triage of if this should (or will) be fixed. Can anyone help with that?

**Comment by impeiran** [comment]
maybe this change caused the problem #1583 
https://github.com/vueuse/vueuse/pull/1583#discussion_r1132007759

**Comment by nicooprat** [comment]
Thanks for the investigation. Would be cool to fix because alternatives like `useRouteQuery` needs `@vueuse/router ` depending on Vue 3; so projects on Vue 2 can't use any route related composables.

**Comment by odex21** [comment]
related to https://github.com/vuejs/composition-api/issues/933#issuecomment-1300606930

**Comment by joaopedrodcf** [comment]
Did anyone found a solution for this problem ? Also tested in vue 2.7 and could see the same problem.

The params contain what is in query param but doesn't update if we do `params.foo = "bar"` as the example from the docs: https://github.com/vueuse/vueuse/blob/main/packages/core/useUrlSearchParams/index.md
