### ISSUE TITLE
Uncaught DOMException in useLocalStorage

### ISSUE THREAD

**Issue by Kilbourne** [vueuse/vueuse#2534]
### Describe the bug

Same bug of #1105;  fixed by #1124 but not for useLocalStorage:
trying to access window.localStorage needs to be wrapped in a try-catch as can catch a DOMException.
https://github.com/vueuse/vueuse/blob/cfcc295261f463c74d80fcb9863cb4bdd7e673b9/packages/core/useLocalStorage/index.ts#L20-L27

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rptfks/

### System Info

```Shell
Not Needed
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ml1nk** [comment]
Issue is still valid and should be fixed, currently you need to wrap it yourself.
