### ISSUE TITLE
(useVirtualList): support config: threshold, when list item count is less than threshold, stop virtual rerendering

### ISSUE THREAD

**Issue by joyexpr** [vueuse/vueuse#2535]
### Clear and concise description of the problem

virtuallist rerendering costs much cpu , and brings whitespace.  if list item count is acceptable, it is better to  total rendered at once. so I hope useVirtualList can support config: threshold, when list item count is less than threshold, stop virtual rerendering.

threshold is diffenert from overscan, it is possible I like to set  threshold=100 and overscan=20 to make each virtuallist rerendering small and quick when list item count is big, and  without virtuallist rerendering when list item count is small

### Suggested solution

add config: threshold, when list item is less than threshold, stop virtual rerendering

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
We are deprecating `useVirtualScroll` in favor of https://github.com/Akryum/vue-virtual-scroller

See https://github.com/vueuse/vueuse/pull/2658

**Comment by joyexpr** [comment]
tried vue-virtual-scroller, not feel good, strongly hope to keep useVirtualList, it's more easier, more predictable

**Comment by jo-finndian** [comment]
Agreed with @joyexpr.
