### ISSUE TITLE
(useVirtualList): expose currentIndex

### ISSUE THREAD

**Issue by joyexpr** [vueuse/vueuse#2538]
### Clear and concise description of the problem

when we leave the page and back, I  want to keep the last place of the list

so I need to know and save the currentIndex when onDeactivated, and when back onActivated to scrollTo(currentIndex)

### Suggested solution

expose currentIndex to know scroll at where now

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
We are deprecating `useVirtualScroll` in favor of https://github.com/Akryum/vue-virtual-scroller

See https://github.com/vueuse/vueuse/pull/2658
