### ISSUE TITLE
useDraggable supports absolute and restricts drag to the parent element only

### ISSUE THREAD

**Issue by laterdays** [vueuse/vueuse#2548]
### Clear and concise description of the problem

useDraggable supports absolute and restricts drag to the parent element only

### Suggested solution

useDraggable supports absolute and restricts drag to the parent element only

fixed doesn't work well in a real-world setting

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by laterdays** [comment]
@wheatjs  Whether it can be supported

**Comment by wheatjs** [comment]
> @wheatjs  Whether it can be supported
> 

I'll investigate, I believe I have gotten it working before.
