### ISSUE TITLE
useTimeAgo adds double quotes to the output

### ISSUE THREAD

**Issue by ItsAndy** [vueuse/vueuse#2557]
### Describe the bug

When using "useTimeAgo" I expect the string output to simply be a string. 
So, in a vue component, if I have ...

```
useTimeAgo(new Date(item.createdAt));
```
I would expect the output to be 
```
five minutes ago
```
But instead the output is 
```
"five minutes ago"
```

The workaround is to munge the string and strip out the quotes, but it seems like either I'm missing a config or this is unintended.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-yasuog?file=src/App.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 11.53 GB / 31.73 GB
  Binaries:
    Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/components: ^9.2.0 => 9.6.0
    @vueuse/core: ^9.2.0 => 9.6.0
    vue: ^3.2.33 => 3.2.45
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
`useTimeAgo` returns a ref, ideally, you should use it in the script and reference it:

```html
<script setup>
import { useTimeAgo } from '@vueuse/core';

const time = useTimeAgo(new Date(2021, 0, 1))
</script>

<template>
  <h1>Hello VueUse!</h1>
  <p>Why is this in quotes???</p>
  <p>Date: {{ time }}</p>
</template>
```
