### ISSUE TITLE
Add "onSuccess" option for "useAsyncState" function

### ISSUE THREAD

**Issue by only52607** [vueuse/vueuse#2560]
### Clear and concise description of the problem

I'm using the `useAsyncState` function, which provides a useful `onError` option to do something on failure. Also, I often do something else after a successful execution, but I don't seem to see an option like `onSuccess` in the type definition of the UseAsyncStateOptions interface. I wonder if it would be useful to add a similar `onSuccess` option.

### Suggested solution

Add an `onSuccess` option to the `UseAsyncStateOptions` interface.

### Alternative

I achieved my purpose by using the following code, but I think providing onSuccess option can save writing these boilerplate codes.

```js
const { state, isReady, isLoading } = useAsyncState(
  axios
    .get('https://jsonplaceholder.typicode.com/todos/1')
    .then(t => t.data),
  { id: null },
)

watch(() => isReady.value, () => {
  if(isReady.value) {
    doSomething()
  }
})

```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Bustuk** [comment]
I'll create a PR on it

**Comment by Alfred-Skyblue** [comment]
> 我会在上面创建一个 PR



> 我会在上面创建一个 PR

Already [PR](https://github.com/vueuse/vueuse/pull/2561)
