### ISSUE TITLE
useFocus doesn't update on blur

### ISSUE THREAD

**Issue by AnnaYuS** [vueuse/vueuse#2565]
### Describe the bug

At some point after 9.6.0 `focused` from `useFocus` is not set to false on `blur`. It might have something to do with this change https://github.com/vueuse/vueuse/pull/2540

### Reproduction

https://stackblitz.com/edit/vue-6quiul?file=src/App.vue

### System Info

```Shell
Chrome, FF
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vaakian** [comment]
you are right, #2540 has broken this. I just made a new PR fixing it.
