### ISSUE TITLE
[computedAsync] unexpected behavior in SSR

### ISSUE THREAD

**Issue by mathijs81** [vueuse/vueuse#2572]
### Describe the bug

I use computedAsync to load data from servers and return values immediately in SSR. However, in SSR, the returned value is never used and only the 'initial state' is returned.

A minimal nuxt example is https://github.com/mathijs81/computedasync-repro-ssr-bug
`pnpm generate` (or opening the source of the page in `pnpm dev`) generates a file with "hello loading..." instead of the expected "hello SERVERTIME".

I tried to dig a little bit into it, and I'm not 100% sure whether it's purely because async calls just run slightly later than the synchronous flow of execution or that it also has to do with that that Vue turns off all reactivity in SSR mode?

Fixing this problem so that a synchronous response would also work in SSR would be the best, but otherwise maybe the documentation should mention that SSR won't fill the result even if the callback returns immediately?

### Reproduction

https://github.com/mathijs81/computedasync-repro-ssr-bug

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 2.55 GB / 23.43 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
  npmPackages:
    @vueuse/nuxt: ^9.9.0 => 9.9.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Chapaev17** [comment]
By default it is not lazy, so it immediately executes on the client side and clears the already filled state on the server. Use `lazy: false`.
`
const userInfo = computedAsync(
  async () => { /* your logic */ },
  null,
  { lazy: true },
)
`
