### ISSUE TITLE
usePointerLock function and useMouse enhancement

### ISSUE THREAD

**Issue by daniser** [vueuse/vueuse#2584]
### Clear and concise description of the problem

I'd be glad to submit a PR that incapsulates [Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) functionality within a composable.

### Suggested solution

Right now I'm using this code in my project:
```js
import { ref } from "vue";
import { unrefElement, useEventListener } from "@vueuse/core";
import type { MaybeElementRef } from "@vueuse/core";

/**
 * Reactive pointer lock.
 */
export function usePointerLock(target?: MaybeElementRef<HTMLElement>) {
  const element = ref<Element | null>()

  function lock(e: MaybeElementRef<HTMLElement> | Event) {
    const target = e instanceof Event ? <Element>e.target : unrefElement(e)
    target && target.requestPointerLock()

    const cleanupChange = useEventListener(document, 'pointerlockchange', () => {
      (element.value = document.pointerLockElement) || cleanupChange()
    })

    const cleanupError = useEventListener(document, 'pointerlockerror', () => {
      cleanupChange()
      cleanupError()
    })
  }

  function unlock() {
    element.value && document.exitPointerLock()
  }

  target && lock(target)

  return {
    lock,
    unlock,
    element,
  }
}

export type UsePointerLockReturn = ReturnType<typeof usePointerLock>
```
I decided to allow passing `Event` into the `lock` function so user may directly attach it to element as event handler:
```vue
<template>
    <div @mousedown.ctrl="lock" @mouseup="unlock"></div>
</template>

<script setup lang="ts">
const { lock, unlock, element } = usePointerLock()
</script>
```
This is the most likely usage scenario as browsers blocks any attempts to lock pointer without preceding user input:
```
Uncaught (in promise) DOMException: A user gesture is required to request Pointer Lock.
```
Also, `useMouse` must be amended to accept `movement` mouse tracking type:
```js
else if (type === 'movement') {
  x.value = event.movementX
  y.value = event.movementY
}
```
It's needed as it's the only way to track mouse when pointer lock mode is activated.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by vaakian** [comment]
Great! it would be better to add a `isSupported` flag using `useSupported` function, for user to be aware of the browser compatibility.

for example:
https://github.com/vueuse/vueuse/blob/dc3ebe80bc61ee56004fdcd417cb234ee749e41e/packages/core/useScreenOrientation/index.ts#L17
