### ISSUE TITLE
useAxios 

### ISSUE THREAD

**Issue by 810505339** [vueuse/vueuse#2586]
### Clear and concise description of the problem

useAxios add a delay option  

### Suggested solution

```
const { data, isFinished, execute, isLoading } = useAxios('', { method: 'GET' }, instance,{
delay :1000
})
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
Can you give a use case for this? Seems like it might be better to use a delay function and then call execute as is seems like a pretty niche use case
