### ISSUE TITLE
Delete lines in useDrauu

### ISSUE THREAD

**Issue by oefeningen** [vueuse/vueuse#2594]
### Clear and concise description of the problem

When using Drauu, the example shows you can delete lines one at a time.
But with the vueuse integration i can only clear the canvas.
I also don't see a way to save the image.

### Suggested solution

It would be great if this is also integrated.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
The eraser in useDrauu is a brush. You can set the brush mode to `eraseLine` to erase individual lines.
