### ISSUE TITLE
`useWebsocket` same message can't be trigger

### ISSUE THREAD

**Issue by dengshenkk** [vueuse/vueuse#2598]
### Describe the bug

```
const {data} = useWebsocket('ws://xxx')
watchEffect(() => {
  console.log(data.value)
})
```
### every second same message on server, same message only print once.
> solution
```
const {data} = useWebsocket('ws://xxx',{onMessage(ws,event){
  console.log(event.data)
}})
```
### Reproduction

null

### System Info

```Shell
System:
    OS: macOS 11.6.6
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 625.07 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/Library/Caches/fnm_multishells/25407_1672293355777/bin/node
    npm: 6.14.15 - ~/Library/Caches/fnm_multishells/25407_1672293355777/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 14.1.2
  npmPackages:
    @vueuse/core: ^9.9.0 => 9.9.0 
    vue: ^3.2.45 => 3.2.45
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
This is just how Vue reactivity works, take a look at the [documentation](https://vuejs.org/api/reactivity-core.html#watcheffect) to learn more. I'd suggest just using `onMessage` for your use case.

**Comment by zuisong** [comment]
dded a dataWithTimestamp property, which can solve this problem. 
```typescript
function useWebSocketWithTimestamp<Data = any>(
  url: Parameters<typeof useWebSocket>[0],
  options?: Parameters<typeof useWebSocket>[1],
) {
  const dataWithTimestamp = ref({
    data: undefined as Data,
    timestamp: Date.now(),
  });
  const originReurn = useWebSocket<Data>(url, {
    ...options,
    onMessage: (ws, event) => {
      dataWithTimestamp.value = {
        data: event.data,
        timestamp: Date.now(),
      };
      options?.onMessage?.(ws, event);
    },
  });

  return {
    dataWithTimestamp: dataWithTimestamp,
    ...originReurn,
  };
}


```
