### ISSUE TITLE
useColorMode values with separate attributes should have separate states

### ISSUE THREAD

**Issue by VividLemon** [vueuse/vueuse#2603]
### Describe the bug

When using useColorMode, if you the composable in two spots, eg a parent/sibling/etc, if they have different attributes, they should have different states... 

Basically, if you have in a child a useColorMode composable, like `const b = useColorMode({attribute: 'someAttribute', selector: 'html'})`

Then in a parent, or sibling, `const a = useColorMode({attribute: 'someOtherAttribute', selector: 'body'})` 

They should have different states. However, if you change the value of 'a', it will change the value of 'b'.

Note: when I originally went to make a reproduction using the vueuse link, it defaulted to version "^7.6.2", where it **did NOT** have this same issue. I then went to the current version: "^9.9.0", and it DID have the issue. Try playing around with the versions to see the difference

Imo they _should_ share the state when bound to the same attribute AND selector, and should NOT share the state when bounded to different attribute/selector

### Reproduction

https://stackblitz.com/edit/vitejs-vite-4u3jst?file=package.json

### System Info

```Shell
System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 5.21 GB / 15.55 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.0 - /run/user/1000/fnm_multishells/168491_1672695201418/bin/node
    Yarn: 1.22.19 - /run/user/1000/fnm_multishells/168491_1672695201418/bin/yarn
    npm: 8.19.2 - /run/user/1000/fnm_multishells/168491_1672695201418/bin/npm
  Browsers:
    Brave Browser: 108.1.46.144
    Firefox: 108.0.1
  npmPackages:
    @vueuse/core: ^9.9.0 => 9.9.0 
    vue: ^3.2.45 => 3.2.45
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kovsu** [comment]
```js
const a = useColorMode({
  attribute: 'data-bs-theme',
  selector: 'body',
  storageKey: "data-bs-theme"
});
```
The key of the value saved to localStorage is `storageKey`, not `attribute`.

**Comment by VividLemon** [comment]
K. Thank you for the help
