### ISSUE TITLE
useLocalStorage integrated with Pinia, the storage value just update once

### ISSUE THREAD

**Issue by GuMengYu** [vueuse/vueuse#2605]
### Describe the bug

appeared after 800f74f49197b11ee5691ac8f4061eb2459ad07e

@vueuse/core: 9.8.1 is ok

<img width="887" alt="image" src="https://user-images.githubusercontent.com/22021419/210335480-9131bd9b-cf59-4589-b898-d3c243cbcb0f.png">

### Reproduction

https://stackblitz.com/edit/vitejs-vite-7bhe6s

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 45.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Edge: 108.0.1462.54
    Safari: 16.2
  npmPackages:
    @vueuse/core: 9.8.2 => 9.8.2
    vue: ^3.2.45 => 3.2.45
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 43081j** [comment]
probably the same as #2567 , that last update introduced a bug into `useStorage`

**Comment by jdk2pq** [comment]
This still appears to be an issue with 9.13.0: https://stackblitz.com/edit/vitejs-vite-ovythd?file=package.json

![Screen Shot 2023-02-20 at 4 48 11 PM](https://user-images.githubusercontent.com/1759726/220203374-9e069037-3055-4538-9f33-1e687e7a8243.png)

Could this ticket be reopened? Thanks.

**Comment by 43081j** [comment]
fwiw it does seem like a different bug but the same effect

**Comment by s-dehaan** [comment]
I am suffering from the same effect and have also created a minimal [repo](https://github.com/s-dehaan/useLocalStorage-bug) to reproduce.
