### ISSUE TITLE
onMounted is called when there is no active component instance to be associated with

### ISSUE THREAD

**Issue by mrleblanc101** [vueuse/vueuse#2608]
### Describe the bug

I'm trying to use `useBreakpoint` and `breakpointsTailwind` but I get a warning in the console and the composable is not working.

Here is my component:
```vue
<template>
    <Transition
        enter-from-class="translate-x-full"
        leave-to-class="translate-x-full"
        enter-active-class="transition duration-300"
        leave-active-class="transition duration-300"
    >
        <div
            v-if="weekSummaryByProjects && weekSummaryByProjects.length && (breakpoints.greater('lg') || menuOpened)"
            class="p-4 py-6 w-full sm:w-96 border-l dark:border-gray-800 shrink-0 absolute lg:static top-16 right-0 bottom-0 bg-white dark:bg-gray-900 z-10 flex lg:!flex flex-col gap-2 shadow-lg lg:shadow-none"
            v-on-click-outside.bubble="onClickOutside"
        >
            <div
                v-for="[project, duration] in weekSummaryByProjects"
                class="p-4 bg-gray-100 dark:bg-gray-800 rounded gap-4 w-full font-bold flex justify-between"
            >
                <span>{{ project }}</span>
                <span>{{ duration }}</span>
            </div>
        </div>
    </Transition>
</template>

<script lang="ts" setup>
import { breakpointsTailwind, useBreakpoints } from '@vueuse/core';
import { useStore } from '@/stores/index';
import { storeToRefs } from 'pinia';

const breakpoints = useBreakpoints(breakpointsTailwind);
const store = useStore();
const { weekSummaryByProjects, menuOpened } = storeToRefs(store);

function onClickOutside() {
    menuOpened.value = false;
}
</script>
```

> onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

<img width="1358" alt="Capture d’écran, le 2023-01-03 à 05 04 38 1" src="https://user-images.githubusercontent.com/17392251/210336119-56e7db6d-0ad1-47da-af94-fe9a2a5a3b8a.png">

### Reproduction

Coming

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 3.93 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Chrome Canary: 111.0.5515.0
    Firefox: 107.0.1
    Safari: 16.1
    Safari Technology Preview: 16.4
  npmPackages:
    @vueuse/components: ^9.9.0 => 9.9.0
    @vueuse/core: ^9.9.0 => 9.9.0
    @vueuse/nuxt: ^9.9.0 => 9.9.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 1084350607** [comment]
Check storeToRefs. This warn said you use onMounted in function but not inside a componet lifecircle. UseBreakPoints use getCurrentInstance to check whether inside a component.

**Comment by mrleblanc101** [comment]
@1084350607 storeToRefs is a Pinia function and is completely unrelated to my issue.

**Comment by 1084350607** [comment]
Can you provide a repo link. I check the useBreakPoints, nothing wrong.

**Comment by mrleblanc101** [comment]
I moved `breakpoints.greater('lg')` from the v-if in the template to the script `const isLgOrGreater = breakpoints.greater('lg');` and it solved my issue.

I think it's just the error message is very unclear and the documentation make no mention of not being able to use `breakpoints.greater('lg')` directly in the template.

**Comment by mrleblanc101** [comment]
@wheatjs @JiuRanYa Why was this closed ?
Is this a bug, will the doc be improved ?

**Comment by wheatjs** [comment]
I don't believe this is a bug. If you want to add a note to the documentation then a PR is welcome

**Comment by mrleblanc101** [comment]
@wheatjs You don't believe it's a bug or you know it's not a bug ?

**Comment by wheatjs** [comment]
As far as the implementation it is not a bug. If you want to add a note to the documentation that is fine.

**Comment by scvnc** [comment]
@wheatjs I would strongly suggest that the documentation surrounding this should be updated-- I have also run into this situation.  I would consider it a bug because it's a design flaw in naming convention.  Based on the way they are named, they *should* be allowed to be used outside the context of a setup function, but they can not.

The vue docs say:

> [Naming](https://vuejs.org/guide/reusability/composables.html#naming)
> It is a convention to name composable functions with camelCase names that start with "use".

and 

> [Usage restrictions](https://vuejs.org/guide/reusability/composables.html#usage-restrictions)
> Composables should only be called synchronously in <script setup> or the setup() hook.

The design of this composable does not adhere to these standards beucase the functions that `useBreakpoints()` expose are actually also composables and must be called synchronously in the context of the setup function.  Therefore they are named incorrectly and should be called something like 

```ts
const {useGreater, useBetween} = useBreakpoints()
```

On that note, perhaps useBreakpoints should be renamed to something like 

```ts
const {useGreater} = createBreakpointsComposables(breakpointsTailwind)
```

**Comment by CasperSocio** [comment]
I came here because we're having the same problem when using `useDark` in our application. We're on v10.9.0.
