### ISSUE TITLE
useAuth signInWithPopup requires auth and provider

### ISSUE THREAD

**Issue by kevinstory** [vueuse/vueuse#2619]
### Describe the bug

The current documentation shows the following for useAuth which presents an error message from Firebase:
`const signIn = () => signInWithPopup(new GoogleAuthProvider())`

The signInWithPopup method takes two parameters, auth and provider, which results in the firebase error "TypeError: Cannot read properties of undefined (reading 'constructor')"

My suggestion is changing the documentation to which works as expected without error:
`const signIn = () => signInWithPopup(getAuth(app), new GoogleAuthProvider());`

### Reproduction

https://stackblitz.com/edit/vitejs-vite-buszlr?file=src/App.vue
(removed firebase config info for this example)
### System Info

```Shell
System:
    OS: Linux 6.0 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 55.06 GB / 62.55 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
    npm: 9.1.3 - ~/.nvm/versions/node/v19.1.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
  npmPackages:
    @vueuse/core: ^9.10.0 => 9.10.0 
    @vueuse/firebase: ^9.10.0 => 9.10.0 
    vue: ^3.2.45 => 3.2.45
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
Closed via #2624
