### ISSUE TITLE
@vueuse/core has no exported member named 'and'. Did you mean 'rand'?

### ISSUE THREAD

**Issue by vasu-garg-ee** [vueuse/vueuse#2632]
### Describe the bug

Could not import **and** from '@vueuse/core' to conditionally disable magic keys.

### Reproduction

Simply try to import it, you will get syntax error.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 17.68 GB / 31.73 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by okxiaoliang4** [comment]
what's your vueuse version? try this?
```typescript
import { logicAnd } from '@vueuse/math'
```

**Comment by vasu-garg-ee** [comment]
My vueuse version is 9.10.0 and I have taken reference from [here](https://vueuse.org/core/useMagicKeys/#conditionally-disable). Please update it here. Thanks
