### ISSUE TITLE
Calculation not processed

### ISSUE THREAD

**Issue by Createwj** [vueuse/vueuse#2633]
### Describe the bug

console.log(useSum(0.1 + 0.2).value == 0.3)   // false
 

### Reproduction

production

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 87.80 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 108.0.5359.124
    Firefox: 103.0.1
    Safari: 15.1
  npmPackages:
    @vueuse/core: ^9.10.0 => 9.10.0 
    @vueuse/math: ^9.10.0 => 9.10.0 
    vue: 3.2.37 => 3.2.37
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
This is not an issue of VueUse, this is a JavaScript issue. See for more information https://javascript.plainenglish.io/why-0-1-0-2-0-3-in-javascript-d7e218224a72
