### ISSUE TITLE
Change [index.md] to [README.md]

### ISSUE THREAD

**Issue by Nstd** [vueuse/vueuse#2638]
### Clear and concise description of the problem

When browse files in `package` directory, `index.md` is not automatically shown.

### Suggested solution

Change the name to `README.md`

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)

**Comment by wheatjs** [comment]
This is because index.md is a [Vitepress](https://vitepress.vuejs.org/) page.
