### ISSUE TITLE
onKeyStroke fires rapidly when OS keyrepeat is active

### ISSUE THREAD

**Issue by katerlouis** [vueuse/vueuse#2639]
### Clear and concise description of the problem

As a developer using VueUse I want to benefit from keyboard shortcuts / hotkeys so users have an easier time navigating my app. 

unlike vue-hotkey or vue-shortkey back in the Vue 2 world, `onKeyStroke` fires the handler rapidly when keyrepeat is active.

A workaround could be to set `{ eventName: 'keyup' }`, but makes the action feel slow and might not what you expect when you hold down the key. 

Both `keydown` and `keypress` both have the same issue.

I'm sure you could make another workaround using `useDebounceFn`, but I (and many others) always need to fiddle until it works as expected. `useDebounceFn` is not as intuitive. Debouncing is also not a real solution, just another workaround.

### Suggested solution

I suggest to add the function `onKeyStrokeOnce` which works just as `onKeyStroke` but triggers only once on keydown/keypress, then "locks the function", and only unlocks it after `keyup` happened. 

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by vaakian** [comment]
Currently, you can do this:
```js
onKeyStroke('w', (e) => {
  if (e.repeat)
    return
})
```

Also made a PR #2652 integrating this feature.

**Comment by katerlouis** [comment]
Nice <3 

I personally still would prefer a separate function for this to keep things short and clean, but a setting in an options-object is more than fine. I didn't even know that `e.repeat` is a thing. Love it <3

**Comment by vaakian** [comment]
I agree with that, but I  was struggling on: if we separate a function `onKeyStrokeOnce`, then we may also need to provide `onKeyUpOnce`, `onKeyUpOnce`, `onKeyDownOnce`, `onKeyPressOnce` for the existing functions for consistency. Yet a `repeat` option solves all. 

Anyway, I think we can have them both, just added `onKeyStrokeOnce` to the PR~

**Comment by katerlouis** [comment]
Whatever is more likely to be accepted is fine with me :)

One more arguments for new functions: It's easier to pick up when there is a `onKeyStrokeOnce` function in the docs. The function name immediately explains whats going on. And the mere existence of `onKeyStrokeOnce` tells users that `onKeyStroke` is NOT firing just once.
