### ISSUE TITLE
useOnline composable not reacting to network changes

### ISSUE THREAD

**Issue by lugeib** [vueuse/vueuse#2648]
### Describe the bug

Tried the useOnline composable and found out it is not working.
Even if wrapped around reactive method.

Attached a screenshot with use, network state and output data.

![image](https://user-images.githubusercontent.com/16768438/212006427-8d685049-869c-422d-bd11-639cea11015f.png)

### Reproduction

Try turning off wifi, unplugging eth cable or turning on airplane mode and see the demo page or a custom project not reacting to the network change

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 5.86 GB / 15.87 GB
  Binaries:
    Node: 16.18.0 - E:\Program Files\NodeJS\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - E:\Program Files\NodeJS\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
I followed your reproduction steps and the function worked as expected. Are you sure you are not somehow still connected? If this is a bug it is much more likely it is a chrome bug than a bug with the function. Check `navigator.connection` in the console to verify

**Comment by lugeib** [comment]
Hi wheatjs, thanks for your reply.

I checked navigator.connection, and indeed it had onchange = null... added a custom callback just to test and it worked.

My question here is, would that be a browser issue ? (my browser) or maybe the composable isn't assigning that event in the first place ?

I'm new to vueuse, so excuse me if i'm making dumb questions.

**Comment by lugeib** [comment]
UPDATE:
I remembered that I have installed VirtualBox, and it's network adapter with it.

So it was always enabled or connected, so I was virtually always connected.

![image](https://user-images.githubusercontent.com/16768438/212191652-e4eb1cad-da14-42b0-8f8f-b7fe0ef49cb4.png)

I disabled it and the composabel worked like a charm.

Sorry for the time loss.
