### ISSUE TITLE
中文文档什么时候可以出来呢

### ISSUE THREAD

**Issue by pan52yu** [vueuse/vueuse#2654]
### Clear and concise description of the problem

> 英文读起来有点费劲

### Suggested solution

> 想问一下 什么时候会出中文文档

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by vaakian** [comment]
https://vueuse.org/why-no-translations.html
