### ISSUE TITLE
Reactivity issue

### ISSUE THREAD

**Issue by Ayoub-Elmendoub** [vueuse/vueuse#2655]
### Describe the bug

# Issue
```js
const isCollapsed = breakpoints.isSmallerOrEqual('lg')
```
isCollapsed should be Ref<Boolean> but in my case is Boolean

# Reproduction
```vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { breakpointsTailwind, useBreakpoints } from '@vueuse/core'

const breakpoints = useBreakpoints(breakpointsTailwind)
const isCollapsed = breakpoints.isSmallerOrEqual('lg')
</script>

<template>
  <h1 class="bg-red-500 h-24 text-black">{{ isCollapsed }}</h1>
</template>

```

### Reproduction

https://vueuse.org/core/usebreakpoints/#usebreakpoints

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
    Memory: 2.82 GB / 7.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
    npm: 9.3.0 - ~/.nvm/versions/node/v19.4.0/bin/npm
  Browsers:
    Firefox: 108.0.2
  npmPackages:
    @vueuse/core: ^9.9.0 => 9.9.0 
    vue: ^3.2.41 => 3.2.42
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vaakian** [comment]
The function starts with `is` are one-time check, you should use `smallerOrEqual` instead:
```js
const isCollapsed = breakpoints.smallerOrEqual('lg')
```
