### ISSUE TITLE
[Features] @vueuse/router add transform data (get/set)

### ISSUE THREAD

**Issue by kieuminhcanh** [vueuse/vueuse#2663]
### Clear and concise description of the problem

Some time I would like to transform data before use. In my case. There are two case to use.

// orders?page=2&orderBy=no:asc&orderBy=status:desc
```js
const filters = reactive({
  page: useRouteQuery('page', '1', {
    transform: ({
      get: (value) => parseInt(value),
      set: (value) => value.toString()
    })
  }),
  orderBy: useRouteQuery('orderBy', [], {
    transform: ({
      get: (value) => value.map((v) => v.split(':'))
        .map(([key, order]) => ({
          key: key.toLowerCase(),
          order: order.toLowerCase(),
        })),
      set: (value) => value.map(({ key, order }) => `${key}:${order}`)
    })
  })
})
```
From orders?page=2&orderBy=no:asc&orderBy=status:desc
We will have
```
filters.page = 1
filters.orderBy = [{ key: 'no', order: 'asc' }, { key: 'status', order: 'desc' }]
```
Otherways
```
filters.page = 2
filters.orderBy = [{ key: 'no', order: 'desc' }, { key: 'time', order: 'desc' }]
// =>> orders?page=2&orderBy=no:desc&orderBy=time:desc
```

### Suggested solution

Add transform data in **ReactiveRouteOptions** 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kieuminhcanh** [comment]
@antfu I hope this feature can be useful for integrated to @vueuse/router.

**Comment by demershov** [comment]
> @antfu I hope this feature can be useful for integrated to @vueuse/router.

I think this issue should be reopen.

**Comment by petitkriket** [comment]
it's a common use case to transform complex data type back and forth (lists, objects)
the concern is legit, in the meantime I am switching to this package that supports it if anyone need a quick solution
https://github.com/Djaler/vue-use-route-query

**Comment by doutatsu** [comment]
+ 1 from me on this

**Comment by mahoushoujoarale** [comment]
@antfu the same to me.

**Comment by maxswann-nexuspoint** [comment]
In case this helps anyone in the future, I solved this by using a computed get/set as a proxy to the useRouteQuery.

My use case was transforming a date to and from a specific string format.
```
import { format, parse } from 'date-fns';

const dateQuery = useRouteQuery('date', '2024-02-19');
const date = computed<Date>({
    get() {
        return parse(dateQuery.value, 'yyyy-MM-dd');
    },
    set(val: Date) {
       dateQuery.value = format(val, 'yyyy-MM-dd');
    },
})
```

**Comment by kieuminhcanh** [comment]
+1 again. To reopen this issue

**Comment by kieuminhcanh** [comment]
@doutatsu, @petitkriket @demershov @mahoushoujoarale 
Could you guys  please+1 or comment to reopen this issue.

**Comment by doutatsu** [comment]
@kieuminhcanh Considering this was closed a year ago, I'd suggest opening a new issue instead to get traction again
