### ISSUE TITLE
UseFetch throws an error when 2nd or 3rd arguments are null or undefined

### ISSUE THREAD

**Issue by hahn-kev** [vueuse/vueuse#2664]
### Describe the bug

In my code I've wrapped useFetch in a helper function and I've passed in arguments, like this:
```ts
function useAppFetch(url: URL, options: RequestInit, useFetchOptions?: UseFetchOptions) {
  return useFetch(url.toString(), options, useFetchOptions)
}
```

and if I call `useAppFetch` without providing a `useFetchOptions` object then I get the following error:
```
Uncaught (in promise) TypeError: right-hand side of 'in' should be an object, got undefined
    containsProp index.mjs:196
    containsProp index.mjs:196
    isFetchOptions index.mjs:2270
    useFactoryFetch index.mjs:2323
    useAppFetch http-service.ts:106 <---- my user code passing the 3rd arg as null
```

This is a simplification, the reason I've wrapped it instead of using `createFetch` is because I've made some type changes so this isn't exactly the same but it still has the issue.

a simple reproduction looks like this: `useFetch('someUrl', undefined)` which based on the docs [here](https://vueuse.org/core/usefetch/#type-declarations) it should work fine that way.

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAnJMAAzk9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKnFeDArGQMPkGWhshQCKRIBRgxGYwEQmms2GLLZHMQJPJlI2iG2e0OAF1mEY6AZDWhQABBMBgSYLdCgVIagwQVJEAA8VGyAB1zCp4JIqABeFMgAB+NSiFBmBgzEDAFAALHm0yoVGBY9xcyAZkqbNISx3EPVgrRkF32xxa+ndC3xNYbCP67UlS28PJWNOVAA+OsqYDAazITXYG4HA5phPDZPEFfPQXSIh0DV1aQb-w3ACy7BujEfiAsiGkdhUBxqHCzCoADkdo3OydSIMBaY3pqHD3sAKhYmAAQgn+AFAXmCx5gA3GmaZtsgCFuHGrj-tmH5fj+ujaMBpposMRgQDAPYVnQkzBMMbHzAAjMMqSbNIyAAPwAPoAI6kBASrBCE2Y8cB77YKQET2AR8hESo267pCFHIahVDaNojjZiuKgAFIAgA8gAcpMRGSNg8B0EYITaFQpHhoY5BKSpBjvlW9j2Dh9IHkAA

### System Info

```Shell
reproduced [here](https://play.vueuse.org) so it's whatever that version is.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alfred-Skyblue** [comment]
I suspect that when you use it, the incoming parameter is `undefined`, because `vueuse` needs to perform type judgment on `options` and `useFetchOptions`, so you must pass an `object` when using it, not `undefined`.

It is recommended that you add a default value when using :

```ts
function useAppFetch(url: URL, options: RequestInit, useFetchOptions?: UseFetchOptions) {
  return useFetch(url.toString(), options ?? {}, useFetchOptions ?? {})
}
```
