### ISSUE TITLE
[useMagicKeys] Shift + non-alphabetic key stucks the key

### ISSUE THREAD

**Issue by smarroufin** [vueuse/vueuse#2667]
### Describe the bug

Using `useMagicKeys`, when I hit `shift+?` I may have `?` key stuck as pressed after releasing the two keys.

The issue only happens when releasing `shift` first:
- I hit `shift+?`, I release `?` first, then I release `shift`: No key is stuck
- I hit `shift+?`, I release `shift` first, then I release `?`: `?` key is stuck

This issue occurs with non-alphabetic keys, meaning the key has two values, one without modifier, one with shift modifier.

**Might be** the same issue as [#1312](https://github.com/vueuse/vueuse/pull/1312), since I produce it on macOS, whatever the browser used. Didn't have the chance to test it on another OS.

Easily reproductible on the [useMagicKeys demo page](https://vueuse.org/core/usemagickeys/#demo).

https://user-images.githubusercontent.com/7547335/213487707-f0d89133-b925-4de8-b0c2-088899167caa.mp4

On the above video, I first try by releasing `?` first, then the second try I release `shift` first. Result, `?` is stuck.

### Reproduction

https://vueuse.org/core/usemagickeys/#demo

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 84.06 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.volta/tools/image/node/16.18.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 109.0.5414.87
    Firefox: 106.0.5
    Safari: 16.0
  npmPackages:
    @vueuse/core: ^9.11.0 => 9.11.0 
    @vueuse/electron: ^9.11.0 => 9.11.0 
    @vueuse/math: ^9.11.0 => 9.11.0 
    @vueuse/nuxt: ^9.11.0 => 9.11.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Syntax-J** [comment]
same here 🙁

**Comment by erikherberg** [comment]
This issue is independent of the OS.
