### ISSUE TITLE
useScroll on window

### ISSUE THREAD

**Issue by victorh5** [vueuse/vueuse#2669]
### Describe the bug

Hi everyone, i'm here to ask for your help!

I am trying to use `useScroll` composable but isn't working without setting the height! In my problem i'm not using `overflow: scroll;` and i think thats why doesnt work. But i am here to see if exists another way to use!

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tduaws/?file=src%2FApp.vue

### System Info

```Shell
"dependencies": {
    "@vueuse/core": "^9.11.1",
    "vue": "^3.2.45"
 },
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
You need to pass in `document` into `useScroll` like `useScroll(document)`

See updated demo: https://stackblitz.com/edit/vitejs-vite-jsmugh/?file=src%2FApp.vue
