### ISSUE TITLE
useFetch should update data only if request was successfull

### ISSUE THREAD

**Issue by pbrzosko** [vueuse/vueuse#2674]
### Clear and concise description of the problem

I have an API, which returns error message, when a request fails. So imagine an endpoint which returns list of options that are supplied to the dropdown component. This component expects an Array. If I execute such a request with useFetch and it fails because of an error, API returns not an array but an error message. And then this error message is in the data state of the useFetch, so I can not use it as options for the combobox.

### Suggested solution

I think data state should only be changed in 2xx responses. Returned data in errorneous requests should be stored in a different state - maybe errorData? For errorneous request data should probably contain initialData config value.

### Alternative

Now I have to do workaround, add computed property over data ref and return it only if status is 2xx, otherwise an empty array.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Alfred-Skyblue** [comment]
I agree with your point of view, but I don't know if this will affect other people's use

**Comment by floydback** [comment]
These changes broke my code and make me rollback. 

For example. The server returns status 422 [Unprocessable Content].  I attached some custom data in the response body explaining what's wrong with the content. Same with 429 "Too many requests". There are several reasons for this error and additional information may be helpful. 

How do I now send error 4** with some json data?

**Comment by pbrzosko** [comment]
I would say you need to use onFetchError or afterError and get error response there and set whatever you like from it to error ref.

**Comment by floydback** [comment]
So now I need to use some global ref to store error data? Because I can't find a way to overload and pass response data from onFetchError method to my component.

**Comment by pbrzosko** [comment]
whatever you return from onFetchError will be passed to error ref AFAIR, look at the code

**Comment by floydback** [comment]
Thank you, I got it.

**Comment by pbrzosko** [comment]
if (options.onFetchError)
            ({ error: errorData } = await options.onFetchError({ data: responseData, error: fetchError, response: response.value }))
          error.value = errorData

So whatever you return in error will be set in error ref.

**Comment by emersonbottero** [comment]
this change broke my code too.
while in dev I don't have access to the api responses so I mock the responses adding the content of json files to the data.
works in version 9, not in version 10.

why to prevent that ? 

my code
```ts
export function mockedFetch<T>(url: string, mockContent?: Promise<T>): UseFetchReturn<T> {
  return useFetch(url, {
    async onFetchError(ctx) {
      if (import.meta.env.DEV && mockContent) {
        const mock = (await mockContent) as { default: T }
        console.warn(`[DEV]mocking call to ${ctx.response?.url}`)
        ctx.error = null
        ctx.data = mock.default
      }

      return ctx
    }
  })
}
```

**Comment by alikdelrisco** [comment]
This breaking change was not added to the v10 release notes.
