### ISSUE TITLE
useFetch - options for gracefully refetching

### ISSUE THREAD

**Issue by jmroon** [vueuse/vueuse#2677]
### Clear and concise description of the problem

When using useFetch, If you are writing to the url ref fairly quickly, there's no guarantee that the last url value in useFetch will be the one returned. You can test this fairly easily by quickly changing the url parameter on the useFetch page with refetch on:
https://vueuse.org/core/useFetch/

Since the requests can return out of order, you can run into issues where you get a 404 on a correct url or have the error become out of sync:

![image](https://user-images.githubusercontent.com/36086006/214602260-1d3cdd9e-637e-4796-8af0-c14563d63f13.png)
![image](https://user-images.githubusercontent.com/36086006/214602673-3767bc50-80cf-44dd-8c6a-57534f2d8fbf.png)

### Suggested solution

Could this perhaps be addressed by allowing previous requests to be automatically aborted if the url value changes?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Alfred-Skyblue** [comment]
Fix in PR #2750
