### ISSUE TITLE
Add useJwt function

### ISSUE THREAD

**Issue by lstoeferle** [vueuse/vueuse#269]
I was thinking about a reactive way of handling a [JWT](https://jwt.io/introduction), since the token often expires/changes after a few minutes. The function should decode the `payload` part of the token and return it as a reactive object, providing the basic claims, which can be extended using generics.

I already implemented some parts of the described functionality in a non reactive way. It would be nice to be able to contribute a reactive solution to this project. What do you think @antfu ?

**Comment by antfu** [comment]
Sounds good! If you would need to wrap with some third party library, I'd recommend to put in `@vueuse/integrations`

**Comment by lstoeferle** [comment]
Alright, I will open a PR as soon as I'm finished with this.

**Comment by lstoeferle** [comment]
Thought about using a 3rd party library for it. https://github.com/auth0/jwt-decode seems very promising.
