### ISSUE TITLE
With useAxios, it cannot use execute after it has been aborted.

### ISSUE THREAD

**Issue by pieterwouda** [vueuse/vueuse#2697]
### Describe the bug

Using execute from useAxios will stop working after a request has been aborted.
Similar implementation with useFetch will just work fine.

```js
import { useFetch } from '@vueuse/core';
import { useAxios } from '@vueuse/integrations/useAxios';

const {
  data: fetchData,
  execute: fetchExecute,
  abort: fetchAbort,
} = useFetch('https://reqres.in/api/users/2?delay=2', {}, { immediate: false });

const {
  data: axiosData,
  execute: axiosExecute,
  abort: axiosAbort,
} = useAxios('https://reqres.in/api/users/2?delay=2', {}, { immediate: false });

function getDataWithFetch() {
  fetchAbort(); // Abort current request.
  fetchExecute(); // Still works after being aborted.
}

function getDataWithAxios() {
  axiosAbort(); // Abort current request.
  axiosExecute(); // Doesn't work anymore after being aborted.
}
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-xpwc3e/?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 16.03 GB / 31.23 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE        
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^9.12.0 => 9.12.0
    @vueuse/integrations: ^9.12.0 => 9.12.0
    vue: ^3.2.45 => 3.2.45
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alfred-Skyblue** [comment]
Resolved in PR #2728
