### ISSUE TITLE
useAxios may need to provide hooks

### ISSUE THREAD

**Issue by jbaubree** [vueuse/vueuse#2713]
### Clear and concise description of the problem

When we use fetching APIs like fetch or axios, we need almost all the time to work with data, specially setting mapping response data.
Currently, the only solution i found to do that with `useAxios` is using watcher and i find this not optimize:
```
const { data, isFinished } = useAxios('/api/posts')
watch(isFinished, (value), {
  if (value && data.value)
    mapAndSetMyData(data.value)
})
```

### Suggested solution

Add hooks like `onFetchResponse`, onFetchError and onFetchEnd like this is setup on [useFetch](https://vueuse.org/core/usefetch/#events)

I dont know the best way to do it so i can't create PR for that, i hope that this idea will be found good and someone can implement this feature.
This will be awesome.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Alfred-Skyblue** [comment]
I think a parameter should be added to options to monitor the callback function for the success or failure of the request

```js
const onSuccess = (result) => {
  console.log("Success!", result);
};
useAxios("/api/posts", { method: "POST" }, { onSuccess });

```
