### ISSUE TITLE
useMagicKeys doesn't reset current when toggling fullscreen

### ISSUE THREAD

**Issue by haykkh** [vueuse/vueuse#2723]
### Describe the bug

If we toggle full screen using a keyboard shortcut, eg:

```ts
import { useMagicKeys, useFullscreen, whenever } from "@vueuse/core"

const { f, current } = useMagicKeys()

const { toggle: toggleFullscreen } = useFullscreen()

whenever(f, async () => await toggleFullscreen())
```

the `f` key isn't cleared from `current`. We can see in the reproduction that `f` stays visible in _Keys Pressed_. If we add some event listeners to inspect what's going on

```ts
useEventListener("keydown", (e) => {
  console.log("keydown", e)
  console.log("current", current)
})
useEventListener("keyup", (e) => console.log("keyup", e))
```

It seems like when you toggle fullscreen the `keyup` event doesn't fire, at least on `window`, meaning that `useMagicKeys` also doesn't trigger its `keyup` event to remove `f` from `current` and `proxy`. By logging `current` we can also see that subsequent `keydown`s after it is "stuck" log both our `f` key and other pressed keys, eg `current: Proxy {'f', 'n'}`.

I've also tried toggling fullscreen without `useFullscreen`, eg with MDN's [example](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API/Guide#example), but the issue still occurs, so I don't think it's an issue with the `useFullscreen` implementation.

Note on reproduction, stackblitz doesn't allow us to enter fullscreen so you will have to run it locally.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-nupqjv/?file=src%2FDemo.vue

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.28 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 96.0
    Firefox Developer Edition: 110.0
    Safari: 16.2
  npmPackages:
    @vueuse/components: 8.2.5 => 8.2.5
    @vueuse/core: 9.12.0 => 9.12.0
    @vueuse/head: 0.7.6 => 0.7.6
    @vueuse/integrations: 8.2.5 => 8.2.5
    @vueuse/math: 9.11.0 => 9.11.0
    @vueuse/shared: 8.2.5 => 8.2.5
    vue: 3.2.25 => 3.2.25
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by shimaokun** [comment]
You can refer to the following website information, which may be the reason
https://www.qyyshop.com/info/810357.html
