### ISSUE TITLE
bug: useTextSelection 监听不到 a 标签的 href 跳转

### ISSUE THREAD

**Issue by xuxchao** [vueuse/vueuse#2727]
### Describe the bug

复现步骤：
1. 打开网址 https://vueuse.org/core/useSessionStorage/
2. 控制台输入：
```
window.document.addEventListener('selectionchange', () => {
  console.log('selectionchange', window.getSelection()?.toString())
})
```
此时鼠标选中文字会打印出来选中的文字
3. 切换侧边栏，发现没有触发 selectionchange 事件，但是 window.getSelection()?.toString() 的值已经是 '' 了。但是由于 selectionchange 监听不到。导致 useTextSelection 返回的 text 值不正确

### Reproduction

https://vueuse.org/core/usetextselection/#usetextselection

### System Info

```Shell
vueuse 官网即可复现。
操作系统 window 11
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alex-Programer** [comment]
"切换侧边栏" 是什么意思？具体操作？

**Comment by businiaoyo** [comment]
What does it have to do with "useSessionStorage" ? and what is the "侧边栏"?

**Comment by antfu** [comment]
Sorry I didn't get what you mean.
