### ISSUE TITLE
Editor components automatic ref for values

### ISSUE THREAD

**Issue by padcom** [vueuse/vueuse#2730]
### Clear and concise description of the problem

Imagine you have a popup window, like a dialog box, for editing a set values. In this scenario we need to have a copy of the original value (usually provided via `modelValue` or just `value`) that is one-way synchronized to the prop. This means that you can change the value locally, and it will stay that way until the prop value that it was originally retrieved from changes.

That way, we have a ref that can be used with v-model inside of the dialog box that gets initialized and automatically updated whenever that prop changes. The upside is that we can directly v-model bind it to inputs and we have full control over when that value gets propagated upwards (which will mean then the prop value will change and the local copy will get updated with the latest changes).

### Suggested solution

I think a good name for it would be `editorRef`

### Alternative

Alternatively, one uses a watch from options API and a local data field to accomplish the same result.

The following video describes how the editor components are created: https://youtu.be/RmH9_ly5Tew

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
https://github.com/vueuse/vueuse/pull/2731#issuecomment-1429919976
