### ISSUE TITLE
No answers when I do search on the vueuse.org, but it works before.

### ISSUE THREAD

**Issue by businiaoyo** [vueuse/vueuse#2742]
### Describe the bug

Perhaps it doesn`t matter, I can use the local se
![fialure search](https://user-images.githubusercontent.com/44898875/217721722-8623a0dd-0883-4ef6-84b8-d819ba08b352.png)
arch. 

### Reproduction

https://vueuse.org/

### System Info

```Shell
windows 10
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tobychidi** [comment]
Just came here because of this same issue. Search is broken on our site

**Comment by daolanfler** [comment]
same here, aflter cleaning localstorage and open in incognito mode, still not working.

**Comment by brc-dd** [comment]
Should be fixed now.
