### ISSUE TITLE
WebSocket: Heartbeat should reset on every message

### ISSUE THREAD

**Issue by ms-fadaei** [vueuse/vueuse#2754]
### Describe the bug

Hi ✋ 
In the current implementation of the [useWebSocket](https://github.com/vueuse/vueuse/tree/main/packages/core/useWebSocket), the heartbeat will send a `ping` after every specified amount of time. but it should reset the heartbeat after receiving any message, as receiving any message means that the connection is normal.

I think you should reset (pause/resume) the heartbeat interval on every message. Can I work on this proposal?

### Reproduction

// ...

### System Info

```Shell
// ...
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Djuvl** [comment]
Any update? I need this feature too. At leaset , the timer resume function need be exposed.
