### ISSUE TITLE
About the useSortabled function

### ISSUE THREAD

**Issue by Alfred-Skyblue** [vueuse/vueuse#2766]
### Clear and concise description of the problem

When I use third party table or list components in my project, I may need to use the function of drag and drop sorting. For the vue component provided by SortableJS, it needs to be the root element of a list, but for third-party components, we cannot require It must expose the root element slot of the list to us, so it cannot meet my current needs. I need a hook to implement responsive drag and drop sorting. I have submitted a  PR #2763  for this and hope it can be adopted, thanks!

### Suggested solution

```ts
import { useSortable } from '@vueuse/integrations'
import { ref } from 'vue'

const el = ref<HTMLElement | null>(null)
const list = ref([{ id: 1, name: 'a' }, { id: 2, name: 'b' }, { id: 3, name: 'c' }])

useSortable(el, list)
```

### Demo

#2763 

https://user-images.githubusercontent.com/55641773/218645000-de04edfd-4fc1-4a2e-9bf7-2077da57562c.mp4

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Alfred-Skyblue** [comment]
resolved #2763

**Comment by Soviut** [comment]
@Alfred-Skyblue Vue.draggable (SortableJS component for Vue) has a `tag` prop that you can set to `tr` to make an entire table row draggable.

https://github.com/SortableJS/vue.draggable.next#tag

**Comment by Alfred-Skyblue** [comment]
> @Alfred-Skyblue Vue.draggable (SortableJS component for Vue) has a `tag` prop that you can set to `tr` to make an entire table row draggable.
> 
> https://github.com/SortableJS/vue.draggable.next#tag

You can set it to tr, but we can't put it inside a third party component. See the demo implementation I wrote.

**Comment by messenjer** [comment]
Maybe we can also implement the component `UseSortable` like in the other functions? 

```
<useDraggable v-model="list">
    <div v-for="item in list" :key="item.id">
      {{ item.name }}
    </div>
</useDraggable>
```

What do you think?

**Comment by Alfred-Skyblue** [comment]
> Maybe we can also implement the component `UseSortable` like in the other functions?
> 
> ```
> <UseSortable v-model="list">
>     <div v-for="item in list" :key="item.id">
>       {{ item.name }}
>     </div>
> </UseSortable>
> ```
> 
> What do you think?

Thanks for the suggestion, it has been committed

**Comment by erropix** [comment]
@Alfred-Skyblue, is there anyway to make it work for nested lists?

**Comment by Andrew0914** [comment]
Hi, 

Someone has an example of two lists, to move element between lists ? 🤔

**Comment by alexmccabe** [comment]
@Alfred-Skyblue I can see that the code for the component has been committed, but it's not exported for use. Any reason why?

**Comment by mrleblanc101** [comment]
The component doesn't appear to exist and is not documented anywhere
