### ISSUE TITLE
如何在ts中使用useAxios请求数据，返回自己定义的数据结构？

### ISSUE THREAD

**Issue by sky185959** [vueuse/vueuse#2769]
### Describe the bug

我想返回自己定义的数据结构，在使用useAxios是中的data返回具体的数据
// 接口返回的结构
interface Response<T> {
  StatusCode: number;
  BusinessInfo: string;
  Data: MetaData<T>;
}

// 数据的列表结构
interface MetaData<T> {
  TotalCount: number;
  Items: Array<T>;
}

// 数据结构
interface TeamInfo {
  TeamName: string;
  TeamCode: string;
}

const { data, isLoading, isFinished } = useAxios<MetaData<TeamInfo>, Response<TeamInfo>>('/api/getTeamInfoList', { method: 'GET' });
 我想要的是useAxios中返回的data是MetaData<T> 泛型结构的数据，其中泛型数据结构是TeamInfo
 但是实际data中返回的数据是
{
	"StatusCode": 200,
	"BusinessInfo": "OK",
	"Data": {
		"TotalCount": 21,
		"Items": [{
			"TeamName": "A001",
			"TeamCode": "A001"
		}]
	}
},

我想要的返回数据是：
{
  "TotalCount": 21,
  "Items": [{
	  "TeamName": "A001",
	  "TeamCode": "A001"
  }]
}

请问这种我该是如何处理，是否需要自定义axios的返回的拦截器处理数据？

### Reproduction

https://vueuse.org/integrations/useAxios/

### System Info

```Shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
    Memory: 93.63 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.96
    Safari: 15.6.1
  npmPackages:
    @vueuse/core: ^9.12.0 => 9.12.0
    vue: ^3.2.38 => 3.2.38
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alfred-Skyblue** [comment]
拦截器处理一下

**Comment by sky185959** [comment]
在自定义的拦截器处理响应结果返回 res.data的时候，使用const { data, isLoading, isFinished } = useAxios<MetaData, Response>('/api/getTeamInfoList', { method: 'GET' });调用以后的data是_value是undefined，
源码中返回的data直接是整个response对象
![image](https://user-images.githubusercontent.com/11226694/219244027-c28e994b-47a1-4d8c-b1db-85a098db2160.png)

**Comment by Alfred-Skyblue** [comment]
不知道你的返回结构是什么样的，或者你可以写个简单的demo

**Comment by sky185959** [comment]
返回结构如下：
```
// 接口返回的结构
interface Response {
  StatusCode: number;
  BusinessInfo: string;
  Data: MetaData;
}

// 数据的列表结构
interface MetaData {
  TotalCount: number;
  Items: TeamInfo [];
}

// 数据结构
interface TeamInfo {
  TeamName: string;
  TeamCode: string;
}
```

**Comment by Alfred-Skyblue** [comment]
你要确保拦截器最终返回的对象是你想要的

**Comment by sky185959** [comment]
> 在自定义的拦截器处理响应结果返回 res.data的时候，使用const { data, isLoading, isFinished } = useAxios<MetaData, Response>('/api/getTeamInfoList', { method: 'GET' });调用以后的data是_value是undefined， 源码中返回的data直接是整个response对象 ![image](https://user-images.githubusercontent.com/11226694/219244027-c28e994b-47a1-4d8c-b1db-85a098db2160.png)

大兄弟，自定义拦截器 res.data以后useAxios返回的data就是undefined了，我这里都贴图了，

**Comment by Alfred-Skyblue** [comment]
useAxios会把res.data返回，但是你最初讲的实际返回了data的上层结构，[文档](https://vueuse.org/integrations/useAxios/)提供的案例是没有这个问题的，如果你在使用中出现了这种问题，希望可以提供在线案例参考
