### ISSUE TITLE
Incorrect return type of until when used with timeout

### ISSUE THREAD

**Issue by adrianjost** [vueuse/vueuse#2804]
### Describe the bug

When using `until` with a timeout, the typing incorrectly is narrowed down to the until condition.

Without timeout, the type is correctly narrowed down to the `toBeNull` condition.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/22987140/220575142-0dc2a284-e147-43cd-afa3-36080580ff28.png">

but when a timeout is added, that timeout could also resolve the promise, which means the condition does not need to be matching yet.
So in the following example, the return type is wrongly narrowed to `null`.
<img width="623" alt="image" src="https://user-images.githubusercontent.com/22987140/220575282-cf79f37b-24d6-4a14-8870-31289f2bdc3b.png">
When using `throwOnTimeout: true`, it would be correct again, though.

Here's also a small excerpt from a real-life use-case we have (although I had to leave out the calculation of the computed)

<img width="982" alt="image" src="https://user-images.githubusercontent.com/22987140/220574551-6c2c169f-d58b-449e-9e15-4fc54e6d747d.png">

It's kind of the opposite issue described in: https://github.com/vueuse/vueuse/issues/1492

### Reproduction

see bug description screenshots

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.25 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /opt/homebrew/opt/node@18/bin/node
    npm: 9.3.1 - /opt/homebrew/opt/node@18/bin/npm
  npmPackages:
    @vueuse/core: ^9.3.0 => 9.3.0 
    vue: ^2.7.10 => 2.7.10
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by adrianjost** [comment]
I don't think it's stale. The Bug still exists in the lastest release.

**Comment by smallnine9** [comment]
I want to say my view: If we want correct type, that will be a run-time problem, but ts do the static compile work, umm, I don't know how to let ts justify the correct type.
Hope anyone can solve this issue

**Comment by antfu** [comment]
Thanks for bringing this up. But as pointed out, I don't think the type can always align to the runtime behaviour, and I don't know if there is anything we could do to improve this. I am closing this issue for now but feel free to bring up in PR if anyone finds a better solution.
