### ISSUE TITLE
Typescript Error when using useStorage in Pinia Store - pnpm

### ISSUE THREAD

**Issue by robinpilz** [vueuse/vueuse#2819]
### Describe the bug

When using useStorage in a Pinia store declaration typescript throws the following error:

`The inferred type of 'useCounterStore' cannot be named without a reference to '.pnpm/@vueuse+shared@9.8.0_vue@3.2.47/node_modules/@vueuse/shared'. This is likely not portable. A type annotation is necessary.`

![2023-02-25 11_33_07-counter ts](https://user-images.githubusercontent.com/60291821/221352505-ebb5f882-db51-483d-845b-7cfc9911465c.png)

The Error disappears when importing RemovableRef seperately but then there would be an unused import. I also found that the error disappears when setting `"preserveSymlinks: true"` in the tsconfig but then typescript complains about vue not having exports named Ref, createApp etc.

I could reproduce it by setting up a new project with create-vue and just installing vueuse/core, therefore I believe it actually is a bug, but please correct me if some setup with pnpm/typescript etc. is wrong here.

### Reproduction

https://github.com/robinpilz/vueuse-pinia-minimal-repro

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 4.66 GB / 15.47 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
  Browsers:
    Firefox: 110.0
  npmPackages:
    @vueuse/core: 9.8.0 => 9.8.0 
    vue: ^3.2.47 => 3.2.47
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hotsaucejake** [comment]
I'm getting the same.

<img width="1216" alt="Screenshot_20230305_111509" src="https://user-images.githubusercontent.com/6332533/222972361-d19dc27b-f59d-420e-9b4d-4c98010c83d7.png">

**Comment by Ragura** [comment]
This bug is still present, specifically when using `useStorage` inside a Pinia store.
The repo posted above illustrates the issue perfectly.

**Comment by sloba88** [comment]
I am also struggling with this.

**Comment by Anoesj** [comment]
This is still an issue, why is this closed?

**Comment by Anoesj** [comment]
I found a quickfix, which is to import `type RemovableRef`. You don't even have to use it anywhere, just importing it will fix the TS error.

Example below taken from your repro, but turned into Setup store notation, haven't tested Option syntax).

### Before:
```ts
import { useLocalStorage } from "@vueuse/core";
import { defineStore } from "pinia";

export const useCounterStore = defineStore('counterStore', () => {
  const test = useLocalStorage('test', false);

  return {
    test,
  };
});
```

### After:
```ts
import { useLocalStorage } from "@vueuse/core";
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- Needed to prevent TS error
import { defineStore, type RemovableRef } from "pinia";

export const useCounterStore = defineStore('counterStore', () => {
  const test = useLocalStorage('test', false);

  return {
    test,
  };
});
```

### After (variant)
To make sure other devs don't remove the import, you could use it like this:
```ts
import { useLocalStorage } from "@vueuse/core";
import { defineStore, type RemovableRef } from "pinia";

export const useCounterStore = defineStore('counterStore', () => {
  const test = useLocalStorage('test', false) satisfies RemovableRef<boolean>;

  return {
    test,
  };
});
```

Note that I'd use `satisfies`, not `as`, since we preferably don't do any type casting, we just want to validate that it's the given type.

**Comment by Deeplycovered-leaf** [comment]
![image](https://github.com/vueuse/vueuse/assets/44355642/b16d0f03-439b-4d31-8a92-297ef7c8e737)

**Comment by Flowko** [comment]
not stale

**Comment by lateek35** [comment]
Shouldn't this issues be re-opened ? 
The hot fix seems to work, but not sure this is the intended behavior

**Comment by andymerskin** [comment]
Small correction to the above workaround: `type RemovableRef` is exported by `@vueuse/core`, not `pinia` 👍 
```typescript
import { type RemovableRef } from '@vueuse/core`
```

**Comment by bbugh** [comment]
This is still an issue, the fix using `type RemovableRef` does work as a workaround, though.

```ts
import { useStorage, type RemovableRef } from '@vueuse/core'
```

**Comment by wcheek** [comment]
Still an issue. 

My project builds even when my LSP is complaining. Using `vtsls` the hotfix is not working for me to remove the error. Seems like an issue with the LSP and `pnpm`? I'm not even using `vueuse` in this module and getting this error.

**Comment by Jess-2021** [comment]
This seems like a TS issue. Here is how i solved it.
[https://github.com/microsoft/TypeScript/issues/29808#issuecomment-540292885](https://github.com/microsoft/TypeScript/issues/29808#issuecomment-540292885)

```
"baseUrl": ".",
"paths": {
    "@vue/shared": ["node_modules/@vue/shared"]
}
```

**Comment by vallemar** [comment]
I try to use this solution but it doesn't work...
```ts
import { type RemovableRef } from '@vueuse/core`
```

**Comment by xihuanxiaorang** [comment]
Is there a good solution to this problem now?
