### ISSUE TITLE
Transition Pipeline

### ISSUE THREAD

**Issue by salakhovilia** [vueuse/vueuse#282]
a cool feature will be the creation of a complex transitions pipeline

**Comment by antfu** [comment]
Not very understand what you mean, can you share some examples? Thanks.

**Comment by salakhovilia** [comment]
If we add a trigger mechanism that will start the animation after the end of the previous animation (or any other condition), then it will be possible to build complex scenes with many related animations.

There is something similar in gsap: https://greensock.com/docs/v3/GSAP/Timeline

Thanks!

**Comment by antfu** [comment]
Sounds cool as long as we don't get that complicated as GSAP (in that case we should just use it directly).

@salakhovilia Do you have an API style in mind? I think we can have a new function from `useTransition` (or maybe build on top of it) so that we can have a basic version and an advanced one for users to choose from.

/cc @scottbedard Wondering what's your idea this? Thanks!

**Comment by scottbedard** [comment]
I could see this being useful, especially for complex enter / exit animations. We can probably keep things simple with something like this https://codesandbox.io/s/reverent-tree-yf37c?file=/src/App.vue

Not sure what the API for this would look like. This is the first thing that comes to mind 🤷‍♂️ 

```js
const first = ref(0);
const second = ref(0);
const third = ref(0);

const { start } = useTransitionPipeline([
  () => first.value = 1,
  () => second.value = 1,
  () => third.value = 1,
]);

start()
```

We'd probably also need ways to define custom transition options for each piece in the pipeline. The `useTransition` function already supports reactive durations and transitions, so maybe something like this would work...

```js
useTransitionPipeline([
  [() => first.value = 1, { duration, transition }],
  [() => second.value = 2, { duration, transition }],
]);
```

**Comment by salakhovilia** [comment]
We can do something like a script, for example:
```
const { start, pause, resume } = useTransitionPipeline([
  {
    type: 'transition',
    handler: () => {
      first.value = 1;
    },
    condition: "onFinished",
    children: [
      {
        type: 'transitionGroup',
        handler: () => {},
        condition: () => {
          return true;
        },
        children: [],
        options: {}
      }
    ],
    options: {duration, transition}
  }])
```

**Comment by scottbedard** [comment]
@salakhovilia I'm not sure I follow what all those options are for. Is the goal to have a helper to run sequentially from one transition to another (along a pre-planned path)? Or to have transitions branching onto different paths dynamically as it progresses?

**Comment by salakhovilia** [comment]
@scottbedard we can make a helper for sequential and parallel execution of animations, so I wrote all these settings

**Comment by antfu** [comment]
I am thinking about this style:

```ts
const { start } = useTransitionPipeline(refA, targetValue, { duration, transition })
					.then(refB, targetValueB, { duration, transition })
					.then(refC, targetValueC)
                    .build() // or maybe we don't need it
```

WDYT?

**Comment by scottbedard** [comment]
@antfu I don't care for a `.then(ref, value, options)` API. It's works for sequential transitions, but I'm not sure how you would express parallel transitions. With a callback function, the user is free to change as much state as they want, or stagger secondary transitions using a `setTimeout` call. But thinking about it more, the API I proposed would make defining those easing function / durations more difficult 🤔 

I think we need more clarification from @salakhovilia on exactly what the goal is here. The main question I have is if we're trying to accommodate sequential transitions, or complex trees that can have many things happening at once and dynamically branching onto different paths.

**Comment by salakhovilia** [comment]
I think that simple sequential transitions are not as important as complex transitions. they give more opportunities to implement ideas

**Comment by webfansplz** [comment]
Favor of #364 , PR has already merged .
