### ISSUE TITLE
Breakpoints: Exactly what I was looking for - but not working in my case well

### ISSUE THREAD

**Issue by demiro** [vueuse/vueuse#2823]
### Describe the bug

Please check this website:
`[https://article-factory-landing-git-redesign-article-factory.vercel.app/](Article-Factory.com)`

the code I am using on the landing page for responsiveness is this:

```
<AppPage>
    <template #toolbar>
      <LandingPageToolbar v-if="breakpoints.isGreaterOrEqual('md')" />
    </template>

    <LandingPageToolbar v-if="breakpoints.isSmaller('md')" />
    ...
</AppPage>
```

where LandingPageToolbar component is just the text you see on top: (AI GENERATED TEXT PROSE....).

What I want to achieve is is the window is bigger than md breakpoint, then display it on top as the page's toolbar, if not, display it inline as the page's content.

It works, on the first page load, but is not working well when resizing the window

Is there any way of actually make it responsive? and change the value consistently when resizing? I think sometimes it does, that's why it is confusing a bit

### Reproduction

https://article-factory-landing-git-redesign-article-factory.vercel.app/

### System Info

```Shell
everything is more or less latest


System:
    OS: Windows 10 10.0.19045
    CPU: (40) x64 Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz  
    Memory: 26.45 GB / 47.88 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^9.13.0 => 9.13.0
    vue: ^3.2.47 => 3.2.47
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AlexRainHao** [comment]
I encounter the same problem, have you solved it?
