### ISSUE TITLE
Websocket retry connection strategy

### ISSUE THREAD

**Issue by salakhovilia** [vueuse/vueuse#283]
In case of problems with the Internet, a mechanism for reconnecting to the server is required

**Comment by antfu** [comment]
Sounds good, would you like to create a PR for it? Thanks.

**Comment by salakhovilia** [comment]
yes, I will definitely create a pull request, thanks

**Comment by shuperry** [comment]
#325

**Comment by shuperry** [comment]
@antfu I created r PR，the netlify checks run failed, but I cann't see the logs.
