### ISSUE TITLE
useLocalStorage为什么每次都会触发`写`操作啊(useLocalStorage Why can trigger 'write' operation every time)

### ISSUE THREAD

**Issue by zhangenming** [vueuse/vueuse#2837]
### Describe the bug

```js
useLocalStorage('test', [], {
    serializer: {
      read: (v: any) => {
        debugger
        return v ? JSON.parse(v) : null
      },
      write: (v: any) => {
        debugger // 除了第一次, 之后每次刷新都会触发写
        return JSON.stringify(v) 
      },
    },
  })
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rptfks/?file=src%2FApp.vue

### System Info

```Shell
.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhangenming** [comment]
![image](https://user-images.githubusercontent.com/21235555/222744315-ab2d06cd-b481-4503-a0db-97910daae8d8.png)

**Comment by kovsu** [comment]
![image](https://user-images.githubusercontent.com/82451257/222815144-d9a638c1-6fb6-4b0b-8af6-05f66877da75.png)
![image](https://user-images.githubusercontent.com/82451257/222815242-fad68b22-6a91-46f6-ac7e-040e2e4bbfa9.png)
![image](https://user-images.githubusercontent.com/82451257/222815209-425be02d-d634-41fe-862c-6b5eff666f0b.png)

Because of `write` as `vue watch's callback` function was executed when you use `useLoacalStorage`.

**Comment by kovsu** [comment]
![image](https://user-images.githubusercontent.com/82451257/222824527-0e06cb35-6e93-453b-ae0b-15c69e4eb982.png)

And the `write` will execute the `serializer.write`.

**Comment by zhangenming** [comment]
![image](https://user-images.githubusercontent.com/21235555/222872363-7292b62b-f1d7-4299-a8be-38ad46663439.png)

so its feature or bug?
