### ISSUE TITLE
High-level api for working with websocket similar to working with event emitter

### ISSUE THREAD

**Issue by salakhovilia** [vueuse/vueuse#284]
when working with websocket, he often has to implement the same functionality, for example, when registering the first listener, you need to subscribe to the channel, and when registering the next next listeners, you must use the existing subscription, this is part of the functions that are very often required when working with websocket, I would like to make a pull request if you find this functionality appropriate

**Comment by antfu** [comment]
That a good idea and I kinda want to have this for a while but don't get a chance to have this demand in real-world applications. PR is definitely welcome, thanks!

**Comment by justice47** [comment]
Right now we have `useWebSocket` - https://vueuse.org/core/usewebsocket/
Can we consider this issue closed?
