### ISSUE TITLE
Validation opportunity of stored values

### ISSUE THREAD

**Issue by webJose** [vueuse/vueuse#2842]
### Clear and concise description of the problem

Imagine a value in a customer's ` localstorage` that was once valid, but due to the usual progression of the application, the value is no longer valid.

For example, imagine a user's preferred count of something used to have no cap (no maximum), and maybe due to high demand or maybe because the user used to be Premium and no longer is, the user's preferred value is now exceeding the permitted maximum.

By doing `useStorage('count', someDefault)` on this customer's browser, the value will immediately be beyond the maximum.

### Suggested solution

The `UseStorageOptions<>` type should allow for a validation function that runs when the value is retrieved from storage.  The final value imported will be the return value of whatever validation function was provided.

```js
useStorage('count', 0, {
    validate: (storedVal, defaultVal) => {
        // The stored value is tested here.  If it doesn't pass, it is modified.
        // As example:
        if (storedVal > someMaximum) {
            return defaultVal;
        }
        return storedVal;
    }
})
```

### Alternative

I know of no alternatives.  If anyone has one, I'll be happy to hear about it.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by webJose** [comment]
Aliving the post.  Team, I think this is a good feature to have.  Without it, I personally don't think I can use this in production.  Rules change, data types change, etc. during application upgrades.  We need an opportunity to correct/validate/delete localstorage values.

**Comment by webJose** [comment]
So many contributors, and none cared to have a look at this.  Sad days.

**Comment by mkeyy0** [comment]
https://vueuse.org/core/useStorage/#custom-serialization
