### ISSUE TITLE
Issue when using two instances of useIntersectionObserver

### ISSUE THREAD

**Issue by brendan1212** [vueuse/vueuse#2851]
### Describe the bug

See [codesandbox repro link](https://codesandbox.io/p/sandbox/pensive-leftpad-wylq9u?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A11%7D%5D).

When using 2 instances (the second element well below the first element on the page), and when the 1st element is recognized as visible -- the 2nd element is also incorrectly recognized as visible.

Is this a bug or is this an incorrect usage?

### Reproduction

https://codesandbox.io/p/sandbox/pensive-leftpad-wylq9u?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A11%7D%5D

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 1.01 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 108.0.5359.124
    Firefox Developer Edition: 110.0
    Safari: 16.3
  npmPackages:
    @vueuse/core: ^9.13.0 => 9.13.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ItMaga** [comment]
This occurs by cause when an intersection callback is called and both targets are visible due to false flags and collapsed margins.

You can try to set the second target to a bigger margin or use padding, and that should work
