### ISSUE TITLE
SpeechSynthesis demo code error.

### ISSUE THREAD

**Issue by adoin** [vueuse/vueuse#2862]
### Describe the bug

Demo code `
 const stop = () => {
    speech.stop();
  };
`
reports error "TS2339: Property 'stop' does not exist on type '{ isSupported: Ref ; isPlaying: Ref ; status: Ref ; utterance: ComputedRef ; error: Ref...>; toggle: (value?: boolean | undefined) => void; speak: () => void; }'."
And the entity has no sop function.

### Reproduction

https://vueuse.org/core/useSpeechSynthesis/

### System Info

```Shell
System:
    OS: Windows 10 10.0.17763
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 14.07 GB / 31.93 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\jsrepo\node_global\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.2989
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jw-foss** [comment]
The stop method was introduced in https://github.com/vueuse/vueuse/pull/2774 at version `9.13.0`, what version of `Vueuse` you are using? Perhaps you are using an older version of `Vueuse`.
