### ISSUE TITLE
useArrayDifference method does not handle 0 correctly

### ISSUE THREAD

**Issue by simpleoo0o** [vueuse/vueuse#2868]
### Describe the bug

const list1 = ref([0, 1, 2, 3, 4, 5])
const list2 = ref([0, 1, 2])
const result = useArrayDifference(list1, list2)

expect：result.value: [3, 4, 5]
actual：result.value: [0, 3, 4, 5]

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4iAFFN1I5cHuZu3r9QYjMYCITTWbDS7ka63e6VRBUc4ARgADJN0aiKKVENIIBj1tgtjt9iAjicCEQrjdhjNrM92Fwzp9vr8uhwerw+gMhqNxuCZnNoYhYbS6ogUZiMdjcfjUYTiXtDgBdZhGOgGFDoUAAQTAYEmC21IFSeDABggqSIAB4qNkAHwAHWwwGA1mQpAM0gOB2d1uGduI9ueEik0iIdDNdWkKmA-huOo4FRCajoRiMiGstjSBxqHFmKgA5MLRfDHoXnZGwNHYyprCZc0Z83giwtqJoK9hnc6ZthkDGgv3kSoALx1xBGbQYVGMFTI2eNWftWcAFlnAFZlfYe-J+ypB9JmmP61OZ3OF1ud32Y+7PTGx7DE8nU+nMzZuNoD-P93R+41t7Yu6sJqkxePA2i3l6hqGOQ9hkswADCrB1HauCpIa5DGqa5qWmctrZM6Kg1PI0gjo6IB4PIrDkYRKilPAZEgEE8B9BQ66oqibiVDAaBUNxbEcTR5g1JqmyMQAfioMwGEJRGpF8jHcNg3yySoYCMY0qmlChmaMfm-A0FQQlOsJ1rIJA5jyaR5ErpsMkgParoqMQME5gc-rmRA2AmURZkWfEiAKeRyAtnxHA8cxrEAJwcVx4VoN40DBCEAnkSoeCMdIFCaQ5ACy7A3LGcYWjiBgqD6HkWSZ-qBsGzDiJIMhEDQ6rYIgAAK+aDNowC0SVnhoCoADK0iSNg8CMLRLkGOQg0AHKkHgOIcJN2AHHBPoHEAA

### System Info

```Shell
win11
chrome
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by leemove** [comment]
maybe all falsy values have same problems
