### ISSUE TITLE
problem with vueuse and nuxt 3 in docker : window is not defined

### ISSUE THREAD

**Issue by unknownman** [vueuse/vueuse#2874]
### Describe the bug

when i use vueuse in a docker with nuxt 3 in dev mode i recieved this error when i serve pages that using elements functions like useElementHover

### Reproduction

https://github.com/unknownman/nuxiword

### System Info

```Shell
System:
    OS: Linux 5.15 Alpine Linux
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 5.88 GB / 7.77 GB
    Container: Yes
    Shell: 1.35.0 - /bin/ash
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  npmPackages:
    @vueuse/core: ^9.13.0 => 9.13.0 
    @vueuse/nuxt: ^9.13.0 => 9.13.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Dedicatus546** [comment]
i get the same problem.

the follow code fragment make application crash.

![image](https://user-images.githubusercontent.com/48575405/226557264-4852c23d-bf28-42cc-a1cb-ec779d9e505d.png)

in node environment maybe wo should use `typeof window === 'object'` instead ?

just like following code:

```javascript
function fn() {
  if (typeof window === "undefined") {
    return "no window.";
  }
  return "window!";
}
```

**Comment by Thy3634** [comment]
i get the same problem in vitepress
