### ISSUE TITLE
useScroll updating on container resize

### ISSUE THREAD

**Issue by 719media** [vueuse/vueuse#2875]
### Clear and concise description of the problem

The default values in useScroll for arrivedState are:
https://github.com/vueuse/vueuse/blob/main/packages/core/useScroll/index.ts#L136-L141

This can be problematic for dynamic height/width containers that may not have a scroll, and whose default arrived left/bottom are false but in reality are true (just that the onScrollHandler has not had a chance to fire).

### Suggested solution

I solved this myself by faking the event in order to get the newly calculated values in arrived, and firing the function on my own:

```
function fireScrollOnElement() {
  if (scrollElement.value) {
    const scrollEvent = new Event('scroll');
    scrollElement.value.dispatchEvent(scrollEvent);
  }
}
```

One problem with this method is that the scroll event is still subject to passive: false and any other delays built into the function, so you still may need to (artificially) wait for a scroll update. Also I noticed that the listeners don't get attached immediately (synchronously) to the element when using useScroll in setup, and so executing the above code solution in mounted() won't fire the scroll (as it hasn't been `addToEventListener`d yet so to speak). So in mounted, you'll have to await nextTick() or something so that the scroll handler will fire when firing a customEvent.

Another related issue is if stuff INSIDE the scroll container changes, which is most reliably solved by using a resizeObserver. I don't think this library should worry about that (becomes bloated), but perhaps there is a more "first-party" way to get the scroll calculations to refire without having to issue a scrollEvent? Just noting it for your review.

### Alternative

I think an export of the "onScrollHandler" function, modified to use the element bound (instead of event, as there wouldn't be one) would be a nice fix. It could then be fired by any process to get instant recalculation.

Additionally, this library could go "above and beyond" by creating a resizeObserver element. It could be cool, but it also may introduce unwanted bloat.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by 719media** [comment]
Something like this: https://github.com/vueuse/vueuse/pull/2876

**Comment by antfu** [comment]
I think we better trigger the calculation on `onMounted` automatically, exposing calculateScrollData does not sounds like a good idea for users to learn and understand
