### ISSUE TITLE
useOnline always false

### ISSUE THREAD

**Issue by rashidpathiyil** [vueuse/vueuse#2884]
### Describe the bug

useOnline is always `false` on my colleague's chrome(working on another browser) but it's also working fine on my machine.

When I check his browser console and run
`navigator.onLine`
`false`

<img width="714" alt="MicrosoftTeams-image (8)" src="https://user-images.githubusercontent.com/15140041/226254080-f1d03685-ca11-49a3-87a9-e86cb25fc59d.png">

### Reproduction

I can't reproduce it on my system

### System Info

```Shell
## System:
OS: macOS 13.2.1
CPU: (8) arm64 Apple M2
Memory: 99.77 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh

## Binaries:
Node: 16.17.1 - /usr/local/bin/node
Yarn: 1.22.19 - /us/local/bin/yarn pm: 8.15.0 - /us/local/bin/npm

## Browsers:
Chrome: 111.0.5563.64
Firefox Developer Edition: 110.0
Safari: 16.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by valgeirb** [comment]
I'm experiencing the same exact problem.

```
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 70.72 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.5.0 - ~/.volta/tools/image/node/16.14.2/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 109.0.1
    Safari: 16.4
```

**Comment by cawa-93** [comment]
`useOnline` just read `navigator.onLine` and react when it changed. So if `navigator.onLine` return `false` then `useOnline` expected return `false` as well. 

https://github.com/vueuse/vueuse/blob/e71d6f21e9c25655692c59e167ade4d0e0d13d1e/packages/core/useNetwork/index.ts#L81

**Comment by nicolascvoodoo** [comment]
This might be related to https://issues.chromium.org/issues/41293401
