### ISSUE TITLE
useVirtualList - scroll length and scroll position not adjusted when list shrinks

### ISSUE THREAD

**Issue by vincesp** [vueuse/vueuse#2888]
### Describe the bug

Consider an application where the length of the rendered list changes. Example could be a master-detail view.

Here is an example app: https://playcode.io/1326765

Steps to reproduce:

- Click on the button "Large list"
- Scroll to the bottom of the list
- Click on the button "Small list"

Expected behavior:

The scroll length of the virtual list is adjusted to reflect the new, smaller number of items in the list.

Actual behavior:

The scroll length and scroll position are not adjusted and a list that seems to be empty is displayed to the user, as all available items are outside of the viewport.

- Click on the button "Scroll to top"

This triggers a recalculation of the scroll length.

### Reproduction

https://playcode.io/1326765

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (96) x64 Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
    Memory: 174.82 GB / 187.52 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.14.2 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.0 - /usr/bin/npm
    Watchman: 20230129.130010.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 110.0.5481.177
    Chromium: 111.0.5563.64
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vincesp** [comment]
@antfu are there any updates on this issue?

**Comment by vincesp** [comment]
Are there any updates on this bug?

**Comment by gephrey** [comment]
same problem encountered here

**Comment by gephrey** [comment]
> same problem encountered here

had to watch list length when scroll to top when gets smaller

**Comment by vincesp** [comment]
@OrbisK @antfu was this fixed? Otherwise, maybe re-open this issue
