### ISSUE TITLE
FormatTimeAgoOptions doesn't allow using custom units

### ISSUE THREAD

**Issue by jamesfoster** [vueuse/vueuse#2891]
### Describe the bug

While trying to override the built-in units with a custom set (I want a minimum granularity of 1 day) I noticed that the type for `FormatTimeAgoOptions<UnitNames>` has a property `units: UseTimeAgoUnit<UseTimeAgoUnitNamesDefault>[]` instead of `units: UseTimeAgoUnit<UnitNames>`

This restricts the implementer to only use the unit names mentioned in `UseTimeAgoUnitNamesDefault`. Notice that the `messages` property on the same type is correctly typed as `UseTimeAgoMessages<UnitNames>`, but the `units` property would cause compiler errors.

The following code demonstrates the error:

```ts
import { UseTimeAgoUnit, UseTimeAgoMessages, useTimeAgo } from '@vueuse/core';

type CustomUnits = 'ticks' | 'cycles' | 'rotations';

const messages: UseTimeAgoMessages<CustomUnits> = {
  ticks: (n, past) => n === 1 ? past ? 'last tick' : 'next tick' : `${n} tick${n > 1 ? 's' : ''}`,
  ...
}

const units: UseTimeAgoUnit<CustomUnits>[] = [
  { name: 'ticks', value: 1234, max: 12345 },
  ...
]

useTimeAgo(date, { units, messages });
                   ^^^^^ type error here
```

### Reproduction

-

### System Info

```Shell
-
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jesuismaxime** [comment]
Bump!
