### ISSUE TITLE
useStorageAsync does not read initial value from storage

### ISSUE THREAD

**Issue by aparajita** [vueuse/vueuse#2895]
### Describe the bug

First of all, thank you for such a fantastic lib! It has completely revolutionized the way I code. 🙏🏽 

There is a bug in `useStorageAsync` right here: https://github.com/vueuse/vueuse/blob/418585d87ab12fd5333c7bd66b806b9aae025153/packages/core/useStorageAsync/index.ts#L98

`read` is async, but the result is not being awaited. This results in a race condition that causes the value in storage to be overridden by `initialValue`. The reproduction illustrates this.

The simple solution is to make `useStorageAsync` itself async, because the call to `read` has to be awaited. This will unfortunately be a breaking change for existing code, but I don't see any way around this.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rpc4fb?file=src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.23 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.7.0 - ~/Library/pnpm/node
    npm: 9.5.0 - ~/Library/pnpm/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.64
    Firefox: 107.0.1
    Safari: 16.3
  npmPackages:
    @vueuse/core: ^9.13.0 => 9.13.0 
    vue: ^3.2.47 => 3.2.47
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alfred-Skyblue** [comment]
I noticed that you did not return a Promise<number> in storeAsync.getItem, although you executed Promise.resolve(state) in setTimeout. However, it does not affect the return value of getItem. Therefore, your code should be written like this:

```ts
const storeAsync = {
  getItem: () => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(state)
      }, 100)
    })
  }
}
```

**Comment by aparajita** [comment]
Correct! Thanks for catching that. But if you increase 100 to 1000, you will see the async value start at 13, then change to 7 after one second. This is inconsistent with the documentation and with expected behavior, as the stored value is not awaited and there is effectively a race condition between the initialValue and the stored value.

**Comment by Alfred-Skyblue** [comment]
Based on your description, do you expect that there is no default value by default, and instead, the default value should only be used if the asynchronous execution is completed and no value is retrieved? If so, you can use this setting externally:

```ts
const initialValue = 13
const storeAsync = {
  getItem: () => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(state || initialValue)
      }, 100)
    })
  }
}

const asyncValue = useStorageAsync('foo', undefined, storeAsync);
```

**Comment by aparajita** [comment]
> do you expect that there is no default value by default, and instead, the default value should only be used if the asynchronous execution is completed and no value is retrieved?

Correct, that is consistent with useStorage and with what one would expect.

The solution you gave is unworkable, it prevents initialValue from being passed, and in TypeScript it would require defining the state to be `State | undefined`, which is also unworkable.

I'll say it again: the code as it exists is incorrect. Calling the async `read` function without awaiting the response is a race condition and makes the stored value unreliable.

I made an awaited async wrapper around useStorageAsync that fixes this problem. Though not absolutely complete, it serves my needs.

```ts
import { useStorageAsync as vueUseStorageAsync } from '@vueuse/core'

/**
 * A wrapper around @vueuse/useStorageAsync that fixes the bug where
 * the stored value is not used.
 */
export async function useStorageAsync<T>(
  key: string,
  initialValue: MaybeComputedRef<T>,
  storage?: StorageLikeAsync,
  options?: UseStorageAsyncOptions<T>
): Promise<RemovableRef<T>> {
  let value = initialValue

  if (storage) {
    const storedValue = await storage.getItem(key)

    if (storedValue !== null) {
      switch (typeof initialValue) {
        case 'string':
          value = storedValue as T
          break

        case 'number':
          value = parseFloat(storedValue) as T
          break

        case 'boolean':
          value = (storedValue === 'true') as T
          break

        case 'object':
          value = JSON.parse(storedValue) as T
          break

        default:
          value = undefined as T
      }
    }
  }

  return vueUseStorageAsync<T>(key, value, storage, options)
}
```

**Comment by aparajita** [comment]
Actually it turns out my workaround did not fix the issue, the race condition still exists. I copied the source of useStorageAsync into my project, changed `read()` to `await read()`, and now everything works correctly.

**Comment by aparajita** [comment]
> I think we should add a `onLoad' event to options that developers may have chance to wait initial value prepared.

Good idea.

**Comment by gomorizsolt** [comment]
@aparajita hey, i've also run into this recently. is your workaround (that is, copying the source of `useStorageAsync` into our projects and making the composable itself async) still valid and the only way to get this to work? 🫤

**Comment by aparajita** [comment]
> @aparajita hey, i've also run into this recently. is your workaround (that is, copying the source of `useStorageAsync` into our projects and making the composable itself async) still valid and the only way to get this to work? 🫤 

AFAIK yes. There is no way to make this correct without changing the code AND awaiting a result.
