### ISSUE TITLE
useInfiniteScroll doesn't work in Nuxt3 app, but does in Vue3 app. Why?

### ISSUE THREAD

**Issue by dosstx** [vueuse/vueuse#2896]
### Describe the bug

When using the `useInfiniteScroll` composable from VueUse, the page won't load more data when user scrolls to the bottom of the viewport in a Nuxt 3 app. It works fine, however, in Vue 3. 

I am using the `useInfiniteScroll` composable from VueUse like so in a Nuxt3 app:

```js
<script setup lang="ts">
import { useInfiniteScroll } from '@vueuse/core';

const el = ref<HTMLElement>(null);
const data = ref([]);
const total = ref(0);

useInfiniteScroll(el, loadData, { distance: 10 });

loadData();

async function loadData() {
  if (data.value.length !== 0 && data.value.length >= total.value) return;
  const res = await fetch(
    `https://dummyjson.com/products/?limit=10&skip=${data.value.length}`
  );
  const d = await res.json();
  total.value = d.total;
  data.value = data.value.concat(d.products);
}
</script>

<template>
  <div ref="el" class="el h-100">
    <div v-for="item in data" class="card">
      <img :src="item.thumbnail" alt="" />
      <h3>{{ item.title }}</h3>
      <p>{{ item.description }}</p>
    </div>
  </div>
</template>
```

Here's a full Nuxt3 reproduction here: https://stackblitz.com/edit/nuxt-starter-buzm4q?file=pages/index.vue

A working Vue3 version is here: https://stackblitz.com/edit/vitejs-vite-9i25xx?file=src/App.vue

### Reproduction

https://stackblitz.com/edit/nuxt-starter-buzm4q?file=pages/index.vue

### System Info

```Shell
Microsoft Edge, Windows 11, Nuxt 3.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sechi747** [comment]
```vue
<template>
  <div ref="el" class="scroll-area">
    <div v-for="item in data" class="card">
      <img :src="item.thumbnail" alt="" />
      <h3>{{ item.title }}</h3>
      <p>{{ item.description }}</p>
    </div>
  </div>
</template>

<style>
.scroll-area {
  height: 100vh;
  overflow-y: auto;
  overflow-x: hidden;
}
</style>
```
That's because `el` is not set a scroll area. In your code, the scroll bar actually been set on `document`.
