### ISSUE TITLE
useChangeCase splits strings containing special characters

### ISSUE THREAD

**Issue by ig1na** [vueuse/vueuse#2912]
### Describe the bug

When using **useChangeCase** with **capitalCase** option, if the string contains special characters, the string is splitted and capitalized

The example in the reproduction on stackblits should result in "Abçdêfg" but instead is "Ab D Fg"

### Reproduction

https://stackblitz.com/edit/vitejs-vite-lms6jg?file=src/App.vue

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
    Memory: 3.66 GB / 15.60 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
  npmPackages:
    @vueuse/core: ^8.6.0 => 8.6.0 
    @vueuse/head: ~0.7 => 0.7.4 
    @vueuse/integrations: ^9.13.0 => 9.13.0 
    vue: ~3.2 => 3.2.26
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by attheGarden** [comment]
maybe you can use  `stripRegexp` configuration to achieve
eg：`useChangeCase('Abçdêfg', 'capitalCase', { stripRegexp: /[\s^\s]/g })`
