### ISSUE TITLE
Can useFirestore have a param like global/keepAlive?

### ISSUE THREAD

**Issue by mmommo** [vueuse/vueuse#292]
Instead of using createGlobalState, can we have an additional param to keep the ref alive? As with createGlobalState, we simply loose 'provide'.

If my understanding is correct, please see below.

```
if(!global){
tryOnUnmounted(() => {
      close()
    })
}
```

Cheers!

**Comment by antfu** [comment]
Sounds reasonable, would you like to make a PR for it? I'd like to have the `autoDispose: false` option (default to `true`) which we also can make it available for other functions.

**Comment by antfu** [comment]
Shipped in v4.0.11
