### ISSUE TITLE
`useRefHistory` does not update the history

### ISSUE THREAD

**Issue by marco-gattelli** [vueuse/vueuse#2920]
### Describe the bug

First of all thanks for this amazing set of composables, your work is admirable!

I'm experiencing some issue with the `useRefHistory`, basically I'm playing around with it using the simple example in the documentation.
It seems like the `history` is not updated automatically, when call `commit` the `history` is updated as expected though. It seems like the watch does not fire when it should.

I guess it is a problem of packages.
The code I'm using is pretty straightforward:
```js
<template>
  <div>
    <button @click="increase">
      increase
    </button>
    <div v-for="h in history" :key="h.timestamp">
      {{ h }}
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRefHistory } from '@vueuse/core'

const counter = ref(0)
const { history } = useRefHistory(counter)

function increase() {
  counter.value = Date.now()
}
</script>
```

### Reproduction

https://vueuse.org/core/useRefHistory/#userefhistory

### System Info

```Shell
System:
    OS: macOS 12.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 85.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 15.3
  npmPackages:
    @vueuse/core: ^9.13.0 => 9.13.0 
    vue: ^2.7.0 => 2.7.8
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marco-gattelli** [comment]
I'm seeing that also the `useCounter` composition is not re-rendering when the value is increase:
```js<template>
  <div>
    <span @click="increase">increase</span>
    <span>{{ count }}</span>
  </div>
</template>

<script setup>
import { useCounter } from '@vueuse/core'

const { count, inc } = useCounter(0)

function increase() {
  inc()
}
</script>
```

the DOM is not updated with the new value, but if I include another composable like `useMouse` and use it into the template the DOM is updated also with the right value of the `count`:
```js
<template>
  <div>
    <span @click="increase">increase</span>
    <span>{{ count }} - {{ x }} - {{ y }}</span>
  </div>
</template>

<script setup>
import { useCounter, useMouse } from '@vueuse/core'

const { count, inc } = useCounter(0)
const { x, y } = useMouse()

function increase() {
  inc()
}
</script>
```

**Comment by marco-gattelli** [comment]
could be related to this https://github.com/vueuse/vue-demi/issues/102#issuecomment-1010791454?

**Comment by mupinnn** [comment]
I had the same issue too when using `useCounter` with  `vue@^2.7.7`
