### ISSUE TITLE
【useVModel】失去响应式

### ISSUE THREAD

**Issue by beloved-zh** [vueuse/vueuse#2921]
### Describe the bug

使用 reactive 对象或数组  v-model 
useVModel 解析成 Ref 直接修改失去响应式
vue官方文档中 Ref 可以直接对 .value 进行修改
![image](https://user-images.githubusercontent.com/52067640/229060827-4b103cd2-4154-428b-9bae-835acff02222.png)

父组件
```
<script setup lang="ts">
  // const data = reactive<Record<string, any>[]>([{ id: 1, name: '张三' }]);
  const data = reactive<Record<string, any>>({ id: 1, name: '张三' });
</script>

<template>
  父组件 {{ data }}
  <a-b-c v-model="data" />
</template>
```

子组件
```
<script setup lang="ts">
  import { useVModel } from '@vueuse/core';

  type Props = {
    // modelValue: Record<string, any>[];
    modelValue: Record<string, any>;
  };

  const props = withDefaults(defineProps<Props>(), {});

  const emit = defineEmits<{
    // (e: 'update:modelValue', model: Record<string, any>[]): void;
    (e: 'update:modelValue', model: Record<string, any>): void;
  }>();

  const data = useVModel(props, 'modelValue', emit, { deep: true });

  const generateData = () => {
    // 响应式失效
    // data.value = [{ id: 2, name: '李四' }];
    // 响应式成功
    // data.value.push({ id: 2, name: '李四' })
    // 响应式失效
    data.value = { id: 2, name: '李四' };
    // 响应式成功
    // data.value.name = '李四';
  };
</script>

<template>
  子组件 {{ data }}
  <a-button type="primary" @click="generateData">修改</a-button>
</template>
```

### Reproduction

https://codesandbox.io/s/usevmodel-zbpsrg?file=/src/components/HelloWorld.vue

### System Info

```Shell
System:                                                        
    OS: Windows 10 10.0.19044                                    
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics         
    Memory: 653.90 MB / 15.37 GB                                 
  Binaries:                                                      
    Node: 16.14.0 - d:\software\nodejs\node.EXE                  
    Yarn: 1.22.18 - d:\software\nodejs\yarn.CMD
    npm: 8.15.0 - d:\software\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^9.13.0 => 9.13.0
    vue: ^3.2.40 => 3.2.47
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by enpitsuLin** [comment]
It seems assgin to a reactive object in v-model in vue 3 don't update view, maybe a bug in vuejs/core

as a workaound

```html
<script setup>
const data = reactive([{ id: 1, name: "张三" }]);
</script>
<template>
  <hello-world :model-value="data" @update:model-value="Object.assign(data , $event)" />
</template>
```

**Comment by MinatoHikari** [comment]
```js
const data = reactive({ id:1 })
const dataRef = ref(data)
dataRef.value = { id:2 }
data.id = 3

console.log(dataRef.value)
console.log(data)
```
Then you known why you can't use vModel in this way.
