### ISSUE TITLE
请问可否新加一个中文版本的文档?

### ISSUE THREAD

**Issue by rjl-cli** [vueuse/vueuse#2923]
### Clear and concise description of the problem

I hope there can be a Chinese document, which can be convenient for users with poor English proficiency

### Suggested solution

类似于vue官方文档，有一个语言切换的按钮

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Alfred-Skyblue** [comment]
https://vueuse.org/why-no-translations.html
