### ISSUE TITLE
Running unit tests and getting Cannot find module '@vueuse/integrations/useFocusTrap' from 'path.to.Component.vue'

### ISSUE THREAD

**Issue by daniilgri** [vueuse/vueuse#2928]
### Describe the bug

Vue: 2.6,
jest:  27.5.1,
@vue/test-utils: 1.3.0,
@vueuse/core: 9.13.0,
@vueuse/integrations: 9.13.0,
focus-trap: 7.4.0

When I run all my unit tests I'm getting this error:
`Cannot find module '@vueuse/integrations/useFocusTrap' from 'src/path/to/some/Component.vue'`

And in that Component.vue I have this line of code:
`import { useFocusTrap } from '@vueuse/integrations/useFocusTrap';`

When I run the dev server everything works correctly without any error. Btw, I also had already integrated `onClickOutside` helper method from `vueuse/core` and everything worked correctly until now.

I have `use-focus-trap.d.ts` file which content is:
```
export interface UseFocusTrapOptions extends Options {
  /**
   * Immediately activate the trap
   */
  immediate?: boolean;
}
export interface UseFocusTrapReturn {
  /**
   * Indicates if the focus trap is currently active
   */
  hasFocus: Ref<boolean>;
  /**
   * Indicates if the focus trap is currently paused
   */
  isPaused: Ref<boolean>;
  /**
   * Activate the focus trap
   *
   * @see https://github.com/focus-trap/focus-trap#trapactivateactivateoptions
   * @param opts Activate focus trap options
   */
  activate: (opts?: ActivateOptions) => void;
  /**
   * Deactivate the focus trap
   *
   * @see https://github.com/focus-trap/focus-trap#trapdeactivatedeactivateoptions
   * @param opts Deactivate focus trap options
   */
  deactivate: (opts?: DeactivateOptions) => void;
  /**
   * Pause the focus trap
   *
   * @see https://github.com/focus-trap/focus-trap#trappause
   */
  pause: Fn;
  /**
   * Unpauses the focus trap
   *
   * @see https://github.com/focus-trap/focus-trap#trapunpause
   */
  unpause: Fn;
}
/**
 * Reactive focus-trap
 *
 * @see https://vueuse.org/useFocusTrap
 * @param target The target element to trap focus within
 * @param options Focus trap options
 * @param autoFocus Focus trap automatically when mounted
 */
export declare function useFocusTrap(
  target: MaybeElementRef,
  options?: UseFocusTrapOptions
): UseFocusTrapReturn;
```
and in my `test-setup.js` file I have:
```
import vueCompositionApi from '@vue/composition-api';
import Vue from 'vue';

Vue.use(vueCompositionApi);
```

### Reproduction

no-link.com

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   
    Memory: 8.41 GB / 15.80 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^9.13.0 => 9.13.0
    @vueuse/integrations: ^9.13.0 => 9.13.0
    vue: ~2.6.14 => 2.6.14
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nkeyy0** [comment]
I have the same issue,  can someone take a look at this?
