### ISSUE TITLE
`v10.0.0-beta.2` - SwipeDirection no longer available

### ISSUE THREAD

**Issue by rafaellehmkuhl** [vueuse/vueuse#2936]
### Describe the bug

I'm receiving the following message on [v10.0.0-beta.2](https://github.com/vueuse/vueuse/releases/tag/v10.0.0-beta.2):

`Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@vueuse_core.js?v=8d27e92b' does not provide an export named 'SwipeDirection'.`

I think it's related with [this](https://github.com/vueuse/vueuse/pull/2863) change.

### Reproduction

Probably not needed

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 89.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.23.0-20220130.1630 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 111.0.1
    Safari: 15.6.1
  npmPackages:
    @vueuse/core: 10.0.0-beta.2 => 10.0.0-beta.2
    vue: ^3.2.33 => 3.2.33
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Yes it's an intentional breaking change. Use string literals instead.

**Comment by rafaellehmkuhl** [comment]
> Yes it's an intentional breaking change. Use string literals instead.

Ok.

Just to be sure, wouldn't using enums be a safer approach in the sense of having type checks and intelligent code completion?
