### ISSUE TITLE
How to configure a custom window for vueuse。

### ISSUE THREAD

**Issue by AprilTong** [vueuse/vueuse#2939]
### Clear and concise description of the problem

How to configure a custom window for vueuse, now using the micro-frontend, in the sub-applications, all the methods of vuesue are invalid.

### Suggested solution

Export a method that can be passed into window

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Basically all VueUse function provide `{ window }` options

**Comment by AprilTong** [comment]
> Basically all VueUse function provide `{ window }` options

onClickOutside，this method does not seem to support, how to solve.
