### ISSUE TITLE
useVModel 是一个对象

### ISSUE THREAD

**Issue by liuruil** [vueuse/vueuse#2940]
### Describe the bug

当我传递 useVModel 是一个对象的时候
好想没有触发 app.js的 handleClicK 事件
这是bug吗？

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ay63pb/?file=src%2FApp.vue,src%2Fcomponents%2FHelloWorld.vue,src%2Fmain.js

### System Info

```Shell
浏览器
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alfred-Skyblue** [comment]
For referencing type data, you need to use the "passive" and "deep" options to achieve two-way binding:

```ts
const data = useVModel(props, 'modelValue', emit, {
  passive: true,
  deep: true
})
```
