### ISSUE TITLE
useEventListener 希望可以支持 preventDefault、stopPropagation设置

### ISSUE THREAD

**Issue by feiying-tf** [vueuse/vueuse#2941]
### Clear and concise description of the problem

现在还不支持preventDefault、stopPropagation设置，使用的时候还是有点不足

### Suggested solution

支持 preventDefault、stopPropagation设置

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Please describe more clearly of what you propose.
