### ISSUE TITLE
Component usage creates excessive `div` element

### ISSUE THREAD

**Issue by Heniker** [vueuse/vueuse#2947]
### Clear and concise description of the problem

Using components from `@vueuse/components` creates a `div` element. This is probably not a desired behavior, as most of those component do not display anything and only provide some kind of functionality (e.g. `OnClickOutside`).

### Suggested solution

Use [Renderless Components](https://vuejs.org/guide/components/slots.html#renderless-components) instead.

Sample code that does not create a `div`:
```js
import * as v from 'vue'

/**
 * Component that resends all props passed to it as writeable v-slot arguments
 * 
 * @example <provide-value :a="42" v-slot="slot"><button v-on:click ="slot.a++">{{slot.a}}</button></provide-value>
 */
export const ProvideValue = v.defineComponent({
  inheritAttrs: false,
  setup(_, { attrs, slots }) {
    const writeableProps = v.reactive(Object.assign({}, attrs))

    return () => v.renderSlot(slots, 'default', v.normalizeProps(writeableProps) || {})
  },
})
```

### Alternative

Mention `div` creation in docs.

### Additional context

https://vueuse.org/guide/components.html

Can provide a PR if desired.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Please provide concrete examples of which component is creating a div for you.

**Comment by Heniker** [comment]
https://github.com/vueuse/vueuse/blob/main/packages/core/onClickOutside/component.ts

Here is a [sandbox](https://codesandbox.io/p/sandbox/sad-sea-buj7ul?file=%2Fsrc%2FApp.vue) that shows `OnClickOutside` component creates a `div` element.

If you inspect HTML elements you will see 2 `<section>` elements and 1 `<div>` element created by `OnClickOutside`.

`OnClickOutside` was chosen purely for showcase. I am pretty sure all vueuse components use the same code that produces a `div` element.

**Comment by smallnine9** [comment]
I checked [sandbox](https://codesandbox.io/p/sandbox/sad-sea-buj7ul?file=%2Fsrc%2FApp.vue), and I found there is indeed an extra div:
![image](https://user-images.githubusercontent.com/35493996/231957397-c63fccfd-03d9-429d-a973-420f2eefcf3f.png)

And I think the reason why this happen is this line:
https://github.com/vueuse/vueuse/blob/d142af15d613861ab22e13eaaea92499e02a7e92/packages/core/onClickOutside/component.ts#L22

Maybe we can write a new render function like that:
![image](https://user-images.githubusercontent.com/35493996/231960458-4176a3f7-310e-4cf0-b51c-3e9bebb6d697.png)

But is this a fine change? What's your opinion? @antfu

**Comment by smallnine9** [comment]
well，the question is how can we just bind @trigger  to the slot element

**Comment by antfu** [comment]
For OnClickOutside specifically, I don't know how we could improve that. I'd say use composables over components if you are strict about it. Otherwise, I am also open to PR for improvements.
