### ISSUE TITLE
`watchImmediate` only fires callback when the new value is truthy

### ISSUE THREAD

**Issue by ferreira-tb** [vueuse/vueuse#2950]
### Describe the bug

If I want to do something like the snippet below, the callback only fires if the value changes to `true`. It is similar to the behavior of `whenever`.

```typescript
const captcha = ref<boolean>(false);

watchImmediate(captcha, (isCaptchaActive) => {
    if (isCaptchaActive) {
        myStore.active = false;
    } else {
        ...
    }
});
```

I looked in the source code and there is indeed an `if` checking if the value is truthy.

```typescript
export function watchImmediate<T>(source: WatchSource<T | false | null | undefined>, cb: WatchCallback<T>, options?: WatchOptions) {
  return watch(
    source,
    (v, ov, onInvalidate) => {
      if (v)
        cb(v, ov, onInvalidate)
    },
    {
      ...options,
      immediate: true,
    },
  )
}
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ehkbcf?file=src/App.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 19.16 GB / 31.37 GB
  Binaries:
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.34)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This is a bug. PR welcome :)
