### ISSUE TITLE
'useColorMode' functionality, but more abstract

### ISSUE THREAD

**Issue by VividLemon** [vueuse/vueuse#2955]
### Clear and concise description of the problem

The situation I have encountered is requiring my project to add an attribute to the body tag based off of the state of a component's modelValue.

So, how does this relate to useColorMode? Well, useColorMode already has all the functionality I need. The only thing I don't need in this case is persistence, which even with useDark, and useColorMode, I am not a fan of having on by default...

useColorMode already has the ability to dynamically add attribute to certain tags -- given that they exist. 

So, what I am looking for is an alternative to this, but with a more abstract naming scheme. useColorMode indicates that it's attempting to set the color of the app, but in this case, all I need to do is add an attribute to the body that is bound to a boolean state. 

### Suggested solution

Create a more abstract version of useColorMode, but with persistence off by default. I am not sure what the name of the composable would be... Perhaps this is just nitpicking and doesn't really have a good place to be added. 

Such an abstraction would contain _optional_ persistence, it would not include the stuffs for color modes. It would take in a selector and an attribute, on toggle it based on a boolean input.

### Alternative

I'd have to manually handle dom manipulation. Alternatively, I could hack together useColorMode to work for what I am needing it to.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Is it already able to disable it, right?
<img width="609" alt="image" src="https://user-images.githubusercontent.com/11247099/231417853-988927d3-9633-4c05-ae00-dbaaafad8cdc.png">

I don't think we will have yet another function for different defaults.

Thanks for bringing this up.

**Comment by VividLemon** [comment]
> Is it already able to disable it, right? <img alt="image" width="609" src="https://user-images.githubusercontent.com/11247099/231417853-988927d3-9633-4c05-ae00-dbaaafad8cdc.png">
> 
> I don't think we will have yet another function for different defaults.
> 
> Thanks for bringing this up.

This isn't really the purpose of the issue
