### ISSUE TITLE
Add a way to manually trigger evaluation of computedAsync

### ISSUE THREAD

**Issue by hagabaka** [vueuse/vueuse#2958]
### Clear and concise description of the problem

I often use `computedAsync` for network requests, so that when a component's props update, the request is automatically refetched. However I also need to manually refresh the data, for example after a create/delete/update operation, and `computedAsync` provides no built-in way to do it.

### Suggested solution

It would be nice if `computedAsync` could provide a way to trigger a manual refresh.

### Alternative

I'm aware of two workarounds,

- Using `useAsyncState` instead, which allows manual refresh, but requires using a `watch` to automatically refresh based on dependencies.
- Adding a `ref` to the `computedAsync` callback, to be used to trigger a refresh just by reassigning it. However I feel that the need to manually refresh async data is common enough to warrant this to be a built-in feature.

`computedWithControl` has a trigger method, but I don't see a way to use async callbacks with it. Let me know if I'm missing something.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by doits** [comment]
+1
