### ISSUE TITLE
🐞: `useSessionStorage` clear data not immediately

### ISSUE THREAD

**Issue by chioio** [vueuse/vueuse#2959]
### Describe the bug

Code:
```js
const data = useSessionStorage('KEY', '')

const handleStore = () => {
  data.value = 'ABC'
}

const handleClear = () => {
  data.value = null
  console.log(data.value) // null
  console.log(sessionStorage.getItem('KEY')) // ABC
}
```

### Reproduction

https://codesandbox.io/s/angry-butterfly-g98elk?file=/src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 102.11 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/Library/Caches/fnm_multishells/25267_1653168489651/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/Library/Caches/fnm_multishells/25267_1653168489651/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This is how Vue works. You need to `await nextTick()` or path `{ flush: 'sync' }`
