### ISSUE TITLE
Docs: extra sort option for versions

### ISSUE THREAD

**Issue by Jogai** [vueuse/vueuse#2967]
### Clear and concise description of the problem

As a developer using VueUse, I wish to see an extra sort option for "Version", just like "Category".  That way you would be able to see what's introduces in the latest release. For me it would be more valuable than sort by "updated" (not saying that need to be removed).

### Suggested solution

Add the "version" option to the "Sort by" resulting in a view like "Category" with all the functions grouped by version. 

The problem here I think is that its hard to see in what version a function appeared. Since its not there already it should be added to the frontmatter of each function. Am I correct that it would be necessary to go trough all the change logs to find that information? 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sorry, I didn't get it. If you are under some version, you can use the versions build to see the available functions for each version.

<img width="195" alt="image" src="https://user-images.githubusercontent.com/11247099/232006235-9a9250b0-2647-4a1b-94ea-a82d01e9fa0a.png">

**Comment by Jogai** [comment]
Sorry, I'll try explain it with an image. Here is a mockup, so the contents of the versions are wrong, but that's the view I meant to explain:
![image](https://user-images.githubusercontent.com/1233188/232035681-cd0e9ab8-2baa-40f9-bfe3-14cdc52cca0a.png)

In reality under v10 would be the functions (I think):
 - useParentElement
 - usePerformanceObserver
 - useAnimate
 - createReusableTemplate
 - createTemplatePromise
 - watchDeep
 - watchImmediate
 - toRef
 - toValue
 - useArrayDifference
 - useArrayIncludes
 - useSortable

And I know the option to navigate between the versions, but its kind of hard to see what the difference is regarding available functions.

But hey, if it's out of scope its fine. The library is awesome anyway.
