### ISSUE TITLE
Give useVModel key a default value

### ISSUE THREAD

**Issue by HomyeeKing** [vueuse/vueuse#297]
I've struggled this for a long time since there's a type problem with this

here is what I need, I want to give the key a default value `modelValue`

```ts
export function useVModel<P extends object, K extends keyof P>(
    props: P,
 ++   key: K = 'modelValue',
    emit?: (name: string, value: any) => void,
  ) {
    const vm = getCurrentInstance()
    // @ts-expect-error mis-alignment with @vue/composition-api
    const _emit = emit || vm?.emit || vm?.$emit?.bind(vm)
  
    return computed<P[K]>({
      get() {
        return props[key]
      },
      set(value) {
        _emit(`update:${key}`, value)
      },
    })
  }
```

but the type issue seems can't be solved
and is it unworthy since it just write less a keyname?

**Comment by antfu** [comment]
Well, tho I agree this could make life easier, it breaks the Vue 2 compatibility as `modelValue` is a Vue 3 thing. Maybe we could have a runtime check `isVue2` from `vue-demi` to do it. WDYT?

**Comment by HomyeeKing** [comment]
yeah, we can make it compatible through `vue-demi`, but what's  really annoying me is the type 😅

**Comment by antfu** [comment]
```ts
key?: K
``

and

```ts
if (key == null) 
	key = isVue2 ? 'value' : 'modelValue'
```

**Comment by HomyeeKing** [comment]
sorry, my mind still stay at vue3 and default value in function params  , when set default value in params ,  the type is  hard for me

**Comment by antfu** [comment]
Would you like a make a PR for it? or I can do that as well.

**Comment by HomyeeKing** [comment]
sure, let me do this
I have something to do today,  maybe later in this weekend

**Comment by antfu** [comment]
Take your time. Thanks!

**Comment by HomyeeKing** [comment]
how to do the test?  it takes me for while to write the test case, and find that we are short of test utils dependencies 

and it seems can't  run the project successfully
![image](https://user-images.githubusercontent.com/49113249/105487878-c0675700-5ceb-11eb-9446-69acd0d05673.png)

**Comment by HomyeeKing** [comment]
how to do the test?  It tooks me for while to write the test case and find that we are short of test utils  👀

and it seems we can't run the doc successfully 
![image](https://user-images.githubusercontent.com/49113249/105488644-e80aef00-5cec-11eb-9afa-d3ad14581e82.png)
