### ISSUE TITLE
useElementVisibility not working anymore after upgrade

### ISSUE THREAD

**Issue by francoism90** [vueuse/vueuse#2970]
### Describe the bug

First, congrats on releasing v10.0.0! :)

One of the issues I'm having after is upgrading, is `useElementVisibility` stops working. It always hides the element, even when it's in the viewport.
I'm using this inside a `PostItem.vue` component on an overview page with infinite scroll:
```vue
<template>
  <div ref="element" class="min-h-16 h-16">
    <template v-if="visible">
      <div class="card">card</div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { useElementVisibility } from "@vueuse/core";

const element = ref<HTMLElement | undefined>();

const visible = useElementVisibility(element);
</script>
```

It's hard to provide a reproduction link, as it could have something to do with my code. Maybe you also provide a better solution for this, as Quasar provided an observer that does this on the fly.

Thanks!

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rptfks

### System Info

```Shell
System:
    OS: Linux 6.2 Fedora Linux 37
    CPU: N/A
    Memory: N/A
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/bin/node
    npm: 9.5.0 - /usr/bin/npm
  npmPackages:
    @vueuse/components: ^10.0.0 => 10.0.0 
    @vueuse/core: ^10.0.0 => 10.0.0 
    @vueuse/head: ^1.1.23 => 1.1.23 
    @vueuse/math: ^10.0.0 => 10.0.0 
    vue: ^3.2.47 => 3.2.47
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Your reproduction is empty

**Comment by schelmo** [comment]
this was fixed by #2968

**Comment by cuebit** [comment]
`useElementVisibility` now uses `useIntersectionObserver` which broke in v10 and is resolved by #2968 – you'll want to wait for a patch release.

**Comment by antfu** [comment]
Patch released. Thanks

**Comment by francoism90** [comment]
@antfu Sorry for posting an empty example! I've pasted the wrong URL. :/

Thanks for the quick fix! :)
