### ISSUE TITLE
createReusableTemplate to support prop `name` for define and reuse

### ISSUE THREAD

**Issue by baozouai** [vueuse/vueuse#2975]
### Clear and concise description of the problem

I think we can provide prop `name` to reuse template, if not provide, default name is `default`.

 for example:

```vue
<script setup lang="ts">
const [TemplateWithName, ReuseTemplateWithName] = createReusableTemplate<{ msg: string }>()
</script>

<template>
  <TemplateWithName v-slot="{ msg }">
    <div>TemplateWithDefaultName: {{ msg }}</div>
  </TemplateWithName>
  <TemplateWithName v-slot="{ msg }" name="template1">
    <div>TemplateWithTemplate1: {{ msg }}</div>
  </TemplateWithName>
  <TemplateWithName v-slot="{ msg }" name="template2">
    <div>TemplateWithTemplate2: {{ msg }}</div>
  </TemplateWithName>
  <ReuseTemplateWithName msg="ReuseTemplateWithDefaultName" />
  <ReuseTemplateWithName msg="ReuseTemplateWithDefaultName" />
  <ReuseTemplateWithName name="template1" msg="ReuseTemplateWithTemplate1" />
  <ReuseTemplateWithName name="template1" msg="ReuseTemplateWithTemplate1" />
  <ReuseTemplateWithName name="template2" msg="ReuseTemplateWithTemplate2" />
  <ReuseTemplateWithName name="template2" msg="ReuseTemplateWithTemplate2" />
</template>
```

and the result is like:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/33510001/232175879-15150833-f348-4dce-b602-22134fffbc46.png">

### Suggested solution

use the Map to cache the render by the template name -- prop `name`

like 

```ts
const renderMap = new Map<string, Slot | undefined>()
```

### Alternative

1.define prop `name` for define and reuse
```ts
const define = defineComponent({
    props: {
      name: String,
    },
    ...
  })

  const reuse = defineComponent({
    props: {
      name: String,
    },
   ...
 })
``` 

2.use Map to cache render by templateName
```ts
const DEFAULT_NAME = 'default'
const renderMap = new Map<string, Slot | undefined>()
const define = defineComponent({
  ...,
  setup(props, { slots }) {
    return () => {
      const templateName = props.name || DEFAULT_NAME
      renderMap.set(templateName, slots.default)
    }
  },
})

const reuse = defineComponent({
  ...,
  setup(props, { attrs, slots }) {
    return () => {
      const templateName = props.name || DEFAULT_NAME
      const render = renderMap.get(templateName)
      if (!render && process.env.NODE_ENV !== 'production')
        throw new Error(`[VueUse] Failed to find the definition of reusable template ${templateName}`)
      return render?.({ ...attrs, $slots: slots })
    }
  },
})
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
The reason I was not doing this is that I don't want to populate the props, as providing `name` as a prop should also be valid. I initially implemented it like that in `vue-reuse-template`. I think it's better to create `createReusableTemplate` multiple times to create multiple pairs. Thanks.
