### ISSUE TITLE
Passing `useToggle`s `toggle` as event handler

### ISSUE THREAD

**Issue by seahindeniz** [vueuse/vueuse#2979]
### Clear and concise description of the problem

Currently, when we pass `toggle` handler to an event attribute, the first parameter creates an issue because of the `event` parameter makes it always receive a truthy value. 
And as you can guess, it creates a problem and the workaround is passing an arrow function `@click="() => toggle()"`

### Suggested solution

Instead of creating a callback in the middle of it, can we just use `toggle` as value and when `useToggle` receives an object with an instance of `Event`, it can just toggle's the value on/off.

To have something like
`@click="toggle"`

### Additional context

We can at least replace this message with something else that explains the situation.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/5789670/232220240-e3c24568-177d-4978-b594-d3917c4b38b5.png">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
> `@click="() => toggle()"`

You don't need to do that, `@click="toggle()"` would work.

**Comment by seahindeniz** [comment]
Isn't that a nice suggestion 🙏🏻 I wasn't unaware of that syntax. God I love Vue ❤️
