### ISSUE TITLE
feature: expect useAsyncValidator expose clearErrors function

### ISSUE THREAD

**Issue by zenonux** [vueuse/vueuse#2993]
### Clear and concise description of the problem

feature: expect useAsyncValidator expose clearErrors function

### Suggested solution

```
  const clearErrors=()=>{}
return {
clearErrors 
}
```

### Alternative

```
  const resetErrors=()=>{}
return {
resetErrors 
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by smallnine9** [comment]
Please describe what do you want to realize with the clearErrors function

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
