### ISSUE TITLE
`usePointerSwipe` misses touch events in Chromium based mobile browsers

### ISSUE THREAD

**Issue by razorness** [vueuse/vueuse#2995]
### Describe the bug

On my search for a simple and tiny solution for a drag feature, I tested [`usePointerSwipe`](https://vueuse.org/core/usePointerSwipe/) because of its possible support for mouse and touch guestures on my Xiamoi 12 with Android 13 and Microsoft Edge Mobile `v112.0.1722.40`, Chrome Mobile `v112.0.5615.48` and Firefox `v111.1.1`.

I found out that it works flawless in Firefox while the both chromium based browsers Chrome and Edge miss every 2nd attempt to swipe.

Here is a small video recorded with Microsoft Edge Mobile:

https://user-images.githubusercontent.com/684302/232769916-2dbc9f03-3b4a-4d2c-b845-ee5ce4498181.mp4

### Reproduction

https://vueuse.org/core/usePointerSwipe/

### System Info

```Shell
Device Type: Smartphone
OEM: Xiaomi
Model: 12 5G (2201123G)
OS: MIUI Global 14.0.5 based on Android 13
Browser: Microsoft Edge Mobile v112.0.1722.40 / Chrome Mobile v112.0.5615.48
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sumerokr** [comment]
I have the same issue.

**Comment by sumerokr** [comment]
Figured out that the issue comes from the fact that the element doesn't have `touch-action: none` CSS style.
Vueuse applies it on `pointerdown` event
```
targetRef.value?.style?.setProperty('touch-action', 'none')
```

and resets it on `pointerup` event
```
targetRef.value?.style?.setProperty('touch-action', 'initial')
```

but the problem is that these changes apply only a moment later, after DOM updates (and it's too late, browser applied a default behavior already).
As a workaround you can force CSS style `touch-events: none !important;` on your target element. This should do the trick.

**Comment by razorness** [comment]
@sumerokr Nice tip!
