### ISSUE TITLE
The useClipboard function does not work on mobile WeChat App

### ISSUE THREAD

**Issue by yangjiakai** [vueuse/vueuse#3008]
### Describe the bug

When using WeChat on a mobile phone to open an application that uses useClipboard, it is not possible to successfully copy the content, and the official demo cannot obtain the value.

![e1651edb3022798d30907454e10659a](https://user-images.githubusercontent.com/35951244/233607419-b6e2823b-348a-4eb3-9fe3-b3acce27c37f.jpg)

### Reproduction

https://github.com/vueuse/vueuse

### System Info

```Shell
Android，Wechat
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I think it's how it works.

**Comment by Mister-Hope** [comment]
I also noticed this problem just yet, I agree with @antfu that this is the expected behavior, but a lot of Chinese app use built-in browsers to open web page, and they just silently disable these permissions by default.

So I was thinking maybe a new option called 'fallback' could be helpful? When clipboard write permission is denied, automactially try again using the legacy way.
