### ISSUE TITLE
RollupError: "Fragment" is not exported when updating to @vueuse/core 10.x

### ISSUE THREAD

**Issue by Santobert** [vueuse/vueuse#3009]
### Describe the bug

In our CI environment the following error occurs during `vite build`:

```txt
"Fragment" is not exported by "node_modules/@vueuse/core/node_modules/vue-demi/lib/index.mjs", imported by "node_modules/@vueuse/core/index.mjs".
file: /builds/.../node_modules/@vueuse/core/index.mjs:3:135
1: import { noop, makeDestructurable, toValue, isClient, tryOnScopeDispose, isIOS, tryOnMounted, computedWithControl, isObject, objectOmit, promiseT...
2: export * from '@vueuse/shared';
3: import { isRef, ref, shallowRef, watchEffect, computed, inject, isVue3, version, defineComponent, h, TransitionGroup, shallowReactive, Fragment, ...
                                                                                                                                          ^
4: 
5: function computedAsync(evaluationCallback, initialState, optionsOrRef) {
error during build:
RollupError: "Fragment" is not exported by "node_modules/@vueuse/core/node_modules/vue-demi/lib/index.mjs", imported by "node_modules/@vueuse/core/index.mjs".
```

What seems odd to me is that the error message says it could not import from `vue-demi/lib/index.mjs`, but actually it should import from `vue-demi/lib/v2.7/index.mjs`.

### Reproduction

https://gitlab.com/dlr-shepard/frontend/-/jobs/4155485338

### System Info

```Shell
System:
    OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (1) x64 Intel(R) Xeon(R) CPU @ 2.30GHz
    Memory: 2.85 GB / 3.60 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  npmPackages:
    @vueuse/core: 10.0.2 => 10.0.2 
    vue: 2.7.14 => 2.7.14
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Santobert** [comment]
Funnily enough, the problem is due to a misconfigured gitlab-ci cache. I wonder if the cause of this issue is related to https://github.com/vueuse/vueuse/issues/2972 and was cached at that moment and therefore occurred from then on.

I'm writing this in case anyone else has this problem too

**Comment by jschirrmacher** [comment]
How did you solve this "misconfigured gitlab-ci cache" problem, @Santobert ?
I have exactly the same error message.
