### ISSUE TITLE
createReusableTemplate Inconsistent with normal write performance 与正常写表现不一致

### ISSUE THREAD

**Issue by masterYi101** [vueuse/vueuse#3012]
### Describe the bug

The result of reusing the template is inconsistent with my normal writing of a label. After reusing the template, an error is reported.

复用模版和我正常写一个标签结果不一致  复用模版后报错了 

### Reproduction

https://stackblitz.com/edit/vitejs-vite-s9qy2n?file=src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.6.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 107.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0
    Safari: 16.4.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I consider this is element's limitation. I don't think where is something we can do on our side.
