### ISSUE TITLE
`createTemplatePromise` error with `<teleport>`

### ISSUE THREAD

**Issue by Jazcash** [vueuse/vueuse#3013]
### Describe the bug

I'm trying to use the new [createTemplatePromise](https://vueuse.org/core/createTemplatePromise/#source) helper with a dialog/modal, but it crashes the vue renderer when using the transition option and `teleport`.

The dialog doesn't open with any transition, and then typing in the input or pressing any button causes the crash with error:

```
Uncaught (in promise) TypeError: child.el.getBoundingClientRect is not a function
```

If I move the `teleport` outside the templatePromise element it works better, but the enter transition still doesn't work and also this means it's incompatible with typical Modal components which use the `teleport` element. Have tried this with [PrimeVue's dialog](https://primevue.org/dialog/) component and it gets the same error.

I can see in the demo on your docs that you simply used a fixed position element to represent a dialog, but that's not practical for complex apps which have many containers. A fixed position element will only be relative to the closest `position: relative` ancestor, which is why most Vue modals make use of `teleport` instead.

### Reproduction

https://codesandbox.io/p/sandbox/elastic-monad-wix8wh?file=%2Fsrc%2Fcomponents%2FExample.vue

### System Info

```Shell
npmPackages:
    @vueuse/core: ^10.0.2 => 10.0.2
    vue: ^3.2.37 => 3.2.47
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by FishYui** [comment]
I also have the same problem, is there any follow-up?

**Comment by ListenV** [comment]
I'm having the same problem.
