### ISSUE TITLE
useVModel can not use v-model with vue2

### ISSUE THREAD

**Issue by likeswinds** [vueuse/vueuse#302]
how about this

``` ts
  let event = `update:${key}`
  const model = vm?.$options.model
  if (model?.prop === key) {
    event = model?.event!
  }
  return computed<P[K]>({
    get() {
      return props[key!]
    },
    set(value) {
      _emit(event, value)
    }
  })
```

**Comment by antfu** [comment]
Are you talking about custom v-model options? I think this could do but should only apply when there is no `key` provided. Would you like to create a PR for it? Thanks.

**Comment by likeswinds** [comment]
yes,custom v-model. I haven't created PR yet, but I'll try.

**Comment by likeswinds** [comment]
yes,custom v-model. I haven't created PR yet, but I'll try.
