### ISSUE TITLE
ERROR: does not provide an export named 'isBoolean'

### ISSUE THREAD

**Issue by kaikaibenkai** [vueuse/vueuse#3020]
### Describe the bug

```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/@vueuse/core/index.mjs?v=7e0d9610' does not provide an export named 'isBoolean' (at lodash.default.js:641:1)
```

In `nuxt.config.ts`:
```ts
export default defineNuxtConfig({
  ssr: false,
  modules: [
    '@vueuse/nuxt',
    '@element-plus/nuxt',
  ],
  devServer: {
    port: 2016,
  },
});
```

After the dev server starts, a white screen will appear.

### Reproduction

Run in Nuxt 3.4.1

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 400.50 MB / 7.23 GB
  Binaries:
    Node: 18.15.0 - C:\nodejs\node.EXE
    Yarn: 1.22.19 - C:\nodejs\yarn.CMD
    npm: 9.6.4 - C:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/core: ^10.1.0 => 10.1.0
    @vueuse/nuxt: ^10.1.0 => 10.1.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
`isBoolean` is never a part of VueUse's API. It's removed in v10 and you should maintain one your own or use other library.

**Comment by kaikaibenkai** [comment]
> `isBoolean` is never a part of VueUse's API. It's removed in v10 and you should maintain one your own or use other library.

But it is still used in `@vueuse/nuxt` 😥

**Comment by kaikaibenkai** [comment]
Oh, I see. I rebuilt the tauri program to resolve the issue.

**Comment by vhxubo** [comment]
遇到同样的问题，问题依赖配置如下。

```json
"devDependencies": {
  "@vueuse/core": "^13.0.0",
  "@vueuse/nuxt": "^13.0.0",
},
"dependencies": {
  "element-plus": "2.3.2",
}
```

该问题由 `element-plus` 引起，已在[2.3.4](https://github.com/element-plus/element-plus/releases/tag/2.3.4)版本修复。

方法一：将`element-plus`升级到 `2.3.4` 或者更新的版本

方法二：使用和`element-plus`一样的依赖版本，`"@vueuse/core": "^9.1.0",`

## 相关链接

[\[Component\] [scrollbar] @vueuse/core 升级到10以上版本，没有isNumber方法了 · Issue #12493 · element-plus/element-plus](https://github.com/element-plus/element-plus/issues/12493)

[refactor: extract isClient and isNumber isBoolean by btea · Pull Request #12504 · element-plus/element-plus](https://github.com/element-plus/element-plus/pull/12504)

[Release 2.3.4 · element-plus/element-plus](https://github.com/element-plus/element-plus/releases/tag/2.3.4)
