### ISSUE TITLE
There is an exception when using useTemplateRefsList  inside a slot

### ISSUE THREAD

**Issue by wht300** [vueuse/vueuse#3023]
### Describe the bug

1、Create a component with a `slot`
```
<!-- LayoutWrap.vue --> 
<template>
    <div>
        <slot></slot>
    </div>
</template>
```
2、Do v-for :ref="refs.set" in LayoutWrap

```
<!-- App.vue --> 
<template>
  <LayoutWrap>
    on slot
    <template v-for="value in list" :key="value">
      <div v-show="index===value"  :ref="refs.set">{{ value }}</div>
    </template>
    <div>refs.length:{{ refs.length }}</div>
  </LayoutWrap>
  <br>
  <div>
    on div
    <template v-for="value in list" :key="value">
      <div v-show="index===value"  :ref="refs2.set">{{ value }}</div>
    </template>
    <div>refs2.length:{{ refs2.length }}</div>
  </div>
</template>

<script setup>
import {  ref } from 'vue';
import { useTemplateRefsList } from '@vueuse/core';
import LayoutWrap from '@/components/LayoutWrap.vue';

let index = ref(1);
const list=ref([1,2,3])
const refs = useTemplateRefsList();
const refs2 = useTemplateRefsList();
</script>

```
![image](https://user-images.githubusercontent.com/19592895/233969908-91b6f9bd-d4d2-46bd-a394-c196a003d584.png)

### Reproduction

https://github.com/wht300/vue-error

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 833.01 MB / 15.87 GB
  Binaries:
    Node: 14.21.2 - D:\Apps\NodeJs\node.EXE
    Yarn: 1.22.19 - D:\Apps\NodeJs\yarn.CMD
    npm: 6.14.17 - D:\Apps\NodeJs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.48), ChromiumDev (114.0.1788.0)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/core: ^10.1.0 => 10.1.0
    vue: 3.3.0-beta.1 => 3.3.0-beta.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wht300** [comment]
I think this should be vue about update event related bugs, I go back to vuejs/core github repository to raise issues

**Comment by wht300** [comment]
I originally raised an issue with https://github.com/vuejs/core/issues/8153, but it was closed, the answer is by design https://github.com/vuejs/core/issues/8153#issuecomment-1522076487
if so, then maybe `useTemplateRefsList `needs to consider this exception scenario

**Comment by rtcpw** [comment]
I have also encountered this problem. The `useTemplateRefsList` depends on the `onBeforeUpdate` to be called. However, when the elements you are monitoring via `useTemplateRefsList` are rendered in child components, the `onBeforeUpdate` will not get called on the parent component.

https://github.com/vuejs/core/issues/4686

I currently believe it is impossible to implement `useTemplateRefsList` to work reliably in all circumstances due to VueJs engine limitations.
