### ISSUE TITLE
useMagicKeys - doesn't trigger on releasing and pressing again the second key in a combination

### ISSUE THREAD

**Issue by rchl** [vueuse/vueuse#3026]
### Describe the bug

I don't know for sure whether it's a bug or just an alternative behavior that should be considered a feature...

With a code like:

```ts
import { useMagicKeys } from '@vueuse/core'

const keys = useMagicKeys()
const commandX = keys['Meta+X']

watch(commandX, pressed => {
    console.info({pressed})
})
```

and:
 - press and hold Command
 - press X
 - release X
 - press X

I would expect the watch to trigger after each press of X rather than only the first time it's pressed.

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAnJMAAzk9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKnFeDArGQMPkGWhshQCKRIBRgxGYwEQmms2GLLZHMQJPJlI2iG2e0OAF1mEY6AZDWhQABBMBgSYLdCgVIagwQVJEAA8VGyAD4ADrmFQJsAp3QS0FYvAQakuEtgazIZybFR4UgGWRgf3xOgEZCTFQAUWguhU5YVKjlKmr93YBlB0kk8CQ9Vc2EQkRUNgnIQTwxzGZUWeTxBUxAotQ4AF40yAtGZexWbsgTyo0DBECFj6eTyngMBTCoDgdV9v09gf6mzyCtIRAtpqHDSCo77WEYjBJHGdifjUHCzCoADkCxoRmYF1JB754gAsggdBQAA0g+zgHMhqFoXaNzsnUiBYdgGYzNgyCQfeITOIe-g3ER8AkeR3HaPYrHyBxKiFsWVAABoqLxXHIBgaEEYg0gQAA1LJaGehm4nsZBfaVtUvEwdoZJidgkQIbo2jSdSslwcZNygoeKZQRum6mCY2guSCjjAF53kXgqcLEIYqiabxACMwWfhmBz2PSzDinUya4Kk4bkJGIDRo2cZnEm2RebUSpPng8isCeXmlPAT5BPAfQUAArGSZJuJUMBoFQXWte1NWZkY-qbE+AB+UkSoNm6pJs0hPtwSqIBw029k+jSraU6XLU+KH8DQVCDX+m4JsgkDmLN80ngALJsBgvm+u6RWkX6rmdxbHVm70XW6V0sHgnUcN1jXNcS7WA913jQMEIT9TeeBPtIFAbSAKYEewkKPbGpSeJ+353Odf4AcQKZAZIMhEDQvpzgACihgzaEFmbY54aAqACE6+IwXkRQY5BswAcqQeA4xw3PYEl9JfkAA

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 1.09 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.1
    Safari: 16.4
  npmPackages:
    @vueuse/core: ^10.1.0 => 10.1.0
    @vueuse/nuxt: ^10.1.0 => 10.1.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rchl** [comment]
As a workaround I guess I can do something like:

```ts
useMagicKeys({
  passive: false,
  onEventFired(e) {
    if (e.metaKey && e.key === 'x' && e.type === 'keydown') {
      e.preventDefault()
      console.info('pressed')
    }
  },
})
```

but that completely bypasses the nice high-level API.

**Comment by olinoles** [comment]
This appears to be a duplicate of #2298. Unfortunately no fix as of yet I believe.

**Comment by rchl** [comment]
In Vue 2 I've been using `vue-shortkey` where it worked as expected. Maybe there is something to be learn from [it's code](https://github.com/fgr-araujo/vue-shortkey/blob/master/src/index.js)

**Comment by ThePpeecc** [comment]
I spent some time looking into this and came some up with a somewhat awkward solution using `customRef` and the `deep` property on watchers.

From what I understand, the reason `vue-shortkey` works as expected is due to it firing an event every time `keydown` is registered. 
A similar effect to `vue-shortkey` can be made by using using `customRef` rather than `ref` in `useMagicKeys`, and then set the `deep` property on any watcher.

Updating the proxy in `useMagicKeys`
```js
const proxy = new Proxy(
    refs,
    {
      get(target, prop, rec) {
        if (typeof prop !== 'string')
          return Reflect.get(target, prop, rec)

        prop = prop.toLowerCase()
        // alias
        if (prop in aliasMap)
          prop = aliasMap[prop]
        // create new tracking
        if (!(prop in refs)) {
          if (/[+_-]/.test(prop)) {
            const keys = prop.split(/[+_-]/g).map(i => i.trim())
            refs[prop] = computed(() => keys.every(key => toValue(proxy[key])))
          }
          else {
            // This part changed
            refs[prop] = customRef((track, trigger) => {
              let val = false
              let oldVal = val
              return {
                get() {
                  track()
                  return val
                },
              
                set(value) {
                  val = value
                  if (val || oldVal !== val) {
                    trigger()
                  }
                  oldVal = val
                }
              }
            })
          }
        }
        const r = Reflect.get(target, prop, rec)

        return useReactive ? toValue(r) : r
      },
    },
  )
```

Then use it like this:

```js
import { useMagicKeys, whenever } from '@vueuse/core'
const { meta_z } = useMagicKeys()

whenever(meta_z, () => console.log('Meta + Z pressed'), {deep: true})

```

While this solution works, I feel like it is too awkward to be the actual resolution to the issue.
What do people think?
