### ISSUE TITLE
useStorage to store es6 symbols

### ISSUE THREAD

**Issue by sherif414** [vueuse/vueuse#3039]
### Describe the bug

i know you can't use symbols as keys for the localstorage, however is it possible to use them as values?

```
const defaultState =  { id: Symbol( ), name: 'john doe'}
const state = useStorage('state', defaultState)

in the current implementation the symbols with be ignored and won't be added to the local storage at all .
```

inside local storage : `{ name: 'john doe' }`
when state is logged:  `{ name: 'john doe' }`

is there any way to use symbols with useStorage?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-f5qurm?file=src/App.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz
    Memory: 2.90 GB / 7.80 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.58)   
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^10.1.0 => 10.1.0
    vue: ^3.2.47 => 3.2.47
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dogyeong** [comment]
you can use [custom serialization](https://vueuse.org/core/useStorage/#custom-serialization) with global symbol.
[example](https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAnJMAAzk9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKnFeDArGQMPkGWhshQCKRIBRgxGYwEQmms2GLLZHMQJPJlI2iG2e0OAF1mEY6AZDWhQABBMBgSYLdCgVIagwQVJEAA8VGyAB1zCp4JIqABeFMgAB+NSiFBmBgzEDAFAALHm0yoVGBY9xcyAZkqbNISx3EPVgrRkF32xxa+ndC3xNYbCP67UlS28PJWNOVAA+OsqJPZNfp+ub4gr0YqOxSmBH+Rsf0uakqLxQfLIBIVJCTBPDZP79f1h9xxBoFTAYAVG-VIVAOA511fd9t0grdnkFaQiDoDU6mkf9-BuAFHwQNIDhqDhZhUAByO0bnZOpEEItM0zbB8nABEI8FKCVMMkbA-GzHRiEcbMVxUYYAD16MYiUUxTbRtFEyIAGp7FE+wABJhkmVIH20LjqPPVCkGkABxLxSkMISmLLDjtGQBjjJY3xuN4oyJUmWoODMizmOkVipmsRtoEQbRhjsgxRPEySZLk4ZGCI+SAEZCPsRwqNsTS3BQHs6EMOgAC8exUUyuOy3jgHXOgTG0ABCXLrGkThzGwUgInXCqqrolyDCsti1McAB+DNEF0-TDOa9qVD-AApAEAHkADlJkgXIfNytNwOwDTsFom5JDSzL6hymz-3qnrGtCMBEDlFRiGy7MOMI8zhIMQiVC64hlNYVr4G0RwRvGqaH3coqQnahb4po1DgLSDi8UwupsIk9NCIWCg8QoW9DAoB9IaQChImCXQUeawjwvXfyHLqbRCNqVgYvx9N+BoX1sBBSn6wKncgJSjaez-Jn6y5lRrAgKg-zEVmgk2xhPy55I+z-NbUuFntReZxb60W2SloSlaJUQSYvFekHw0Mch7HpMCgA)

**Comment by sherif414** [comment]
@dogyeong it works, thanks
but i can't really use it for my usecase since i'll have to come up with a unique key for every symbol, which defeats their purpose

**Comment by michealroberts** [comment]
@sherif414 I think the premise is that `Symbols` by their nature have to be unique, so they aren't easily serialisable in the traditional sense ... you'd have to have some custom behaviour to do this. 

What is your use case for having a value as a `Symbol()` ... it feels like the use case isn't quite correct.

**Comment by sherif414** [comment]
@michealroberts 
i needed them as keys for a TransitionGroup component, i just gave up and settled for a random string generator function.

**Comment by michealroberts** [comment]
@sherif414 Do you mean a loop bound key, so using v-for with :key ... if so, is there anything else you could compile together that would make the. "pseudo-unique" ... maybe a generated ulid / uuid or similar?

**Comment by sherif414** [comment]
@michealroberts yes thats exactly my usecase.
i ended up making a little helper function
```
export function getRandomString(length: number): string {
  let result = ''
  while (result.length < length) {
    const randomSubstring = Math.random().toString(36).substring(2)
    result += randomSubstring.slice(0, length - result.length)
  }
  return result
}
```

coming up with a custom serializer seemed an over complication for such a simple usecase.
but its still worth to discuss the topic for other future uses

**Comment by michealroberts** [comment]
#@sherif414 I'd probably utilise a random string generation library for this example, although not critical your Math.random isn't truly random ... it seems a bit overkill just to generate a random id. What is your data structure like as an example ...

**Comment by sherif414** [comment]
the random string serves no purpose other than being used as a key for the v-for. 
here is the relevant [code](https://github.com/sherif414/shade-ui/blob/a19ed90d7b117028ddd6f1d80bc2476bfbfb04b9/packages/shady-ui/src/components/notification/index.ts#LL29C29-L29C29)

its a useNotification composable
when called it will push a new notification object to the notifications array
this array will be rendered with a v-for and thats why i need a unique key for every notification object

**Comment by michealroberts** [comment]
@sherif414 Yeh that seems logical. Apologies, I assumed you had more control over the data.

The only alternative I would recommend is having a Map() iterable, with the key being the timestamp of the notification with millisecond precision (or maybe some other unique property). Use the unique key of the map to be the source of truth. With the timestamp, as it is an incrementing number you'll be able to keep ordering / sorting too. Bonus that the key can be used in the v-for loop too.

**Comment by michealroberts** [comment]
@sherif414 Just be aware that Math.random() on just 6 characters might not give you proper randomness over large datasets. But for 1-10 (which is the number you'd mainly expect for notifications that haven't been read), this should be sufficient.

**Comment by sherif414** [comment]
@michealroberts the notifications are ephemeral and would last about 10s - 30s most of the time.
so yeah its fine

**Comment by michealroberts** [comment]
@sherif414 Yeh, fair. I'd honestly push new Date().getTime() at the time of the notification creation / push to your data structure (* I would definitely recommend using that as your unique key to a Map, and use that). It would simplify your code, and getTime() would be super optimised in most browser engines, as with Maps.

**Comment by sherif414** [comment]
thanks for the tip
