### ISSUE TITLE
Can't change ctx.data on onFetchErroe

### ISSUE THREAD

**Issue by emersonbottero** [vueuse/vueuse#3041]
### Describe the bug

I need to mock the response only while in DEV. 
It worked on version 9 and it stopped on version 10.

See my comments in https://github.com/vueuse/vueuse/issues/2674#issuecomment-1526927866 
There you have the full context.

P.S.: the docs are giving examples changing data on the onFetchErrror hook.

### Reproduction

Clone the [repo](https://github.com/emersonbottero/pinia-usefetch) and update the version to 10 

### System Info

```Shell
Windows 10, node 16, chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by emersonbottero** [comment]
How do I use it! https://github.com/emersonbottero/pinia-usefetch/blob/8dbee1da23f9dedcfd842929e61f545fcfc2b0e0/src/api/useFetch.ts#L62

**Comment by emersonbottero** [comment]
@smallnine9 
mine works, check the response in the network tab

v9
![image](https://user-images.githubusercontent.com/12377432/236351720-560b4cb0-b2fd-4d2e-b513-685051ff3aeb.png)
v10
![image](https://user-images.githubusercontent.com/12377432/236352765-a2e1d501-ba44-4fef-bea4-02a0ee306165.png)


when the request fail it doesn't even reach the afterFetch lifecycle.

**Comment by smallnine9** [comment]
@emersonbottero I found out it. In your repo, it needs a localStorage item.
https://github.com/emersonbottero/pinia-usefetch/blob/8dbee1da23f9dedcfd842929e61f545fcfc2b0e0/src/api/useFetch.ts#L67
And when I added it, it finally works.
Could you just fix this little problem to benefit anyone else who want to participate in? :)

**Comment by emersonbottero** [comment]
done

**Comment by emersonbottero** [comment]
That's just an example.. in an real app we can have hundreds of calls. So I still think we should be able to change at least in dev mode

**Comment by emersonbottero** [comment]
No one?

**Comment by emersonbottero** [comment]
No one again?

**Comment by emersonbottero** [comment]
.

**Comment by emersonbottero** [comment]
I altered my solution to use mirages.
