### ISSUE TITLE
Support passing multiple refs or DOM elements to useFocusTrap

### ISSUE THREAD

**Issue by simonkuran** [vueuse/vueuse#3043]
### Clear and concise description of the problem

focus-trap supports passing multiple elements to it to create a larger trap area. [focus-trap's Multiple Elements demo](https://focus-trap.github.io/focus-trap/#multipleelements-heading) and the [source code for the demo](https://github.com/focus-trap/focus-trap/blob/master/docs/js/multiple-elements.js). `useFocusTrap` doesn't activate if you pass it multiple refs or DOM elements.

I have a hamburger menu that opens below the main nav with the hamburger icon. I'd like to trap the focus within the menu when it is open, but also be able to focus on the hamburger icon. In this case being able to pass in an array of DOM elements would be the most convenient since my two trap targets are in different components in my app.

### Suggested solution

I would like to be able to pass more than one ref or DOM element into `useFocusTrap` like so.

```Vue
<template>
    <div>
        <div ref="targetOne" id="target-one">
            <button>Focus One</button>
        </div>

        <div>
            <button>Do Not Focus</button>
        </div>
        
        <div ref="targetTwo" id="target-two">
             <button>Focus Two</button>
        </div>
    </div>
</template>
<script setup>
// Pass two refs
const targetOne = ref();
const targetTwo = ref();
const { hasFocus, activate, deactivate } = useFocusTrap([targetOne, targetTwo]);
onMounted(() => {
    activate();
});

// Or pass two DOM elements
const domElements = ref([]);
const { hasFocus, activate, deactivate } = useFocusTrap(domElements);
onMounted(() => {
    domElements.value = [document.getElementById('target-one'), document.getElementById('target-two')];
    activate();
});
</script>
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by michealroberts** [comment]
@simonkuran @okxiaoliang4 I can take a look at this if you're happy with the proposal?

**Comment by alalpod** [comment]
Hi, can we reopen this issue? We have a dropdown and it's body sometimes used with teleport. It would be great if we are able to pass several target elements.
