### ISSUE TITLE
useElementVisibility detects wrong

### ISSUE THREAD

**Issue by MarijnFK** [vueuse/vueuse#3044]
### Describe the bug

useElementVisibility returns true/false incorrectly. I thought this was due to css in my project, but even without styling it detects wrong.
Then i went to https://vueuse.org/core/useElementVisibility/#demo and noticed it is wrong there as well, see screenshot.
I think the larger the element is, the more it detects wrongly.

![image](https://user-images.githubusercontent.com/47977238/235424627-11093926-f5ee-4882-bfb0-684e3ee6a145.png)

### Reproduction

https://vueuse.org/core/useElementVisibility/#demo

### System Info

```Shell
see vueuse website
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by businiaoyo** [comment]
It is not a bug.
You can set the threshold option to 0 to suit your requirements.(default 0.1)
Reading the Type Declarations section of the documentation.
https://vueuse.org/core/useIntersectionObserver/#type-declarations

**Comment by MarijnFK** [comment]
Is it possible to set the threshold using the useElementVisibility? Or does that always default to 0.1?
