### ISSUE TITLE
Add a way to trigger change event for the same file when using useFileDialog

### ISSUE THREAD

**Issue by AmitJoki** [vueuse/vueuse#3045]
### Clear and concise description of the problem

The `change` event triggers only if the file is different every time. If the same file is chosen, the `change` event is not triggered but we want it to.

It's a popular use case, see - https://stackoverflow.com/questions/4109276/how-to-detect-input-type-file-change-for-the-same-file

I'd like to submit a PR for this issue.

### Suggested solution

We could set `this.value = null;` on `input.onclick` event in `useFileDialog`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zaqvil** [comment]
I am trying to add a parameter `opentoClear` to solve this problem
