### ISSUE TITLE
useVirtualList - list is empty if container is bound to template ref

### ISSUE THREAD

**Issue by vincesp** [vueuse/vueuse#3048]
### Describe the bug

`useVirtualList` cannot be used with Vue's [template refs](https://vuejs.org/guide/essentials/template-refs.html). If the HTML element that binds to the `containerProps` also has a
template ref, then the `list` returned by `useVirtualList` remains empty:

```html
<script setup>
//...
const scroller = ref(null)
const { list, containerProps, wrapperProps, scrollTo } = useVirtualList(allItems, {
  itemHeight: 24,
})
</script>

<div v-bind="containerProps" ref="scroller">
  <div v-bind="wrapperProps">
    <div v-for="item in list" class="item" :key="item">{{ item }}</div>
  </div>
</div>
```

Removing `ref="scroller"` from the code above will fix the virtual list.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-5x9fwn?file=src/components/VirtualList.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vueuse/core: 10.1.0 => 10.1.0 
    vue: 3.2.47 => 3.2.47
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by coderwei99** [comment]
You can't bind ref anymore. 
containerProps already has the ref attribute. ref is already bound when you use v-bind. You can't cover it
```vue
<div v-bind="containerProps" ref="scroller"> //here
```

**Comment by vincesp** [comment]
In this case, I have a suggestion: extend the `interface UseVirtualListReturn<T>` to also include the reference to the element.

```js
const { list, containerProps, wrapperProps, scrollTo, containerRef } = useVirtualList(allItems, {
  itemHeight: 24,
})
```

As I can see from the code that `useVerticalVirtualList()` and `useHorizontalVirtualList()` are already returning it.

**Comment by vincesp** [comment]
I understand. So this is the right way to get the `ref` then:

```
const { list, containerProps, wrapperProps, scrollTo } = useVirtualList(
  allItems,
  {
    itemHeight: 24,
  }
);
const scroller = computed(() => containerProps.ref);
```

[Stackblitz](https://stackblitz.com/edit/vitejs-vite-e86mpe?file=src/components/VirtualList.vue)
