### ISSUE TITLE
Differentiate undefined and null in useRouteQuery

### ISSUE THREAD

**Issue by some-user123** [vueuse/vueuse#3050]
### Clear and concise description of the problem

I would like to differentiate these URLs:
1. `/foo`
1. `/foo?q`
1. `/foo?q=bar`

Using `const q = useRouteQuery('q')` there is no differentiation between the first two:
1. `q === null`
1. `q === null`
1. `q === 'bar'`

### Suggested solution

Differentiate `null` and `undefined`:

`const route = useRoute()` :
1. `route.query.q === undefined`
1. `route.query.q === null`
1. `route.query.q === 'bar'`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ml1nk** [comment]
Not sure if this isn't a bug instead of a enhancement, because it ignores the different meaning of null and undefined inside Vue Router.

**Comment by some-user123** [comment]
Agree with you. But I don't think, I can change the labels.

**Comment by some-user123** [comment]
@anteriovieira: You seem to be working on related functionality (#3184) . Would you mind looking at this potential bug as well? Many thanks in advance! 🙏

**Comment by some-user123** [comment]
I just upgraded to 10.3.0. Was this issue really solved?

`useRouteQuery('q')` is of type `globalThis.Ref<string | string[] | null>`. `undefined` still seems missing.
