### ISSUE TITLE
feature proposal: UseAxios - can we configure dynamic input?

### ISSUE THREAD

**Issue by HoaDevDn** [vueuse/vueuse#3051]
### Clear and concise description of the problem

I wish you can add an option to configure dynamic input so that i just call `execute()` is enough

```
import { useAxios } from '@vueuse/integrations/useAxios';
import axios from 'axios';

const instance = axios.create({ baseURL: 'https://dummyjson.com' });

export default defineComponent({
  setup() {
    const id = ref('');
    const title = ref('');
    const address = ref('');

    const { data, execute, isLoading } = useAxios(
      `/products/${id.value}`,
      {
        method: 'PUT',
        data: { title: title.value, address: address.value },
      },
      instance,
      { immediate: false },
    );

    const login = async (e: any) => {
      e.preventDefault();
      execute();
    };

    const renderContent = () => {
      if (isLoading.value) {
        return <div>loading</div>;
      }

      return (
        <div>
          <form onSubmit={login}>
            <div>
              id:
              <select name="id" v-model={id.value}>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
              </select>
            </div>
            <div>
              title:
              <input type="text" name="title" v-model={title.value} />{' '}
            </div>
            <div>
              address:
              <input type="text" name="address" v-model={address.value} />
            </div>
            <button type="submit">Submit</button>
          </form>
          <div>
            URL: {`products/${id.value}`}
            <br />
            data: <br /> {`title: ${title.value} `}
            <br /> {`address: ${address.value}`}
          </div>
        </div>
      );
    };

    return () => renderContent();
  },
});

```

for now, we can't
[Untitled_ May 3, 2023 9_56 PM.webm](https://user-images.githubusercontent.com/23466462/235958562-7b3974a3-ddb5-4ca8-b556-b303ad94a10e.webm)

![Untitled_ May 3, 2023 9_56 PM (3)](https://user-images.githubusercontent.com/23466462/235964831-efdc989e-2028-47a8-81a8-6107ac55b6e7.gif)

Hope we can add these to header and payload, just use execute() without passing the params to it

URL: products/1
title: a
address: b

### Suggested solution

No response

### Alternative

No response

### Additional context

No response

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by HoaDevDn** [comment]
```
const { data, execute, isLoading } = useAxios(
     computed(() => `/products/${id.value}`),
      computed(() => ({
        method: 'PUT',
        data: { title: title.value, address: address.value },
      })),
      instance,
      { immediate: false },
    );
```
Thanks for replying @VividLemon 
But this code does not work
is there any way to make my issue work?

**Comment by VividLemon** [comment]
It doesn't work because it requires an update to vueuse
