### ISSUE TITLE
When useVmodel is used with an object passed as props, it will directly modify the data passed

### ISSUE THREAD

**Issue by chenglu4343** [vueuse/vueuse#3062]
### Describe the bug

When binding an object with useVmodel, changes to the values on the object will also result in changes to the props data, regardless of whether the parent component accepts the change or not.

If used as follows:
```js
const task = useVModel(props, 'task', emits, {
  passive: true,
  deep: true,
  clone: true,
});
```

It may result in an infinite loop when changes are received by the parent component.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-cttd23?file=src/App.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vueuse/core: ^10.1.2 => 10.1.2 
    vue: ^3.2.47 => 3.2.47
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by coderwei99** [comment]
Hello, in my opinion, useVmodel is normal.  What you printed is task and new value, and your original lists have not changed. If you have different opinions, please tell me
```typescript
function updateTask(task: Task, index: number) {
  console.log("I don't accept change，but lists is changed", task);  //task is new value. It should be consistent with the latest values of the child components
  console.log(lists); // The lists values are your parent component's own
}
```

**Comment by chenglu4343** [comment]
I think when passing the task as a prop to the TaskCom component, if the parent component doesn't explicitly accept this change, I expect the TaskCom component not to directly modify the task data.

If it's a controlled component, it should always display the task value passed in as a prop. If it's an uncontrolled component, it should maintain a local copy of the task value that can be changed locally, but the task value passed in through the props should always remain unchanged.

In other words, I expect that whether the child component's changes are controlled or uncontrolled, they should not update the task value passed in through props, as I think that directly modifying props is not good programming behavior.

Just like how a configured eslint can prevent you from modifying props:

```js
props.task.done = true;
```

You will get an eslint error preventing you from doing this: Unexpected mutation of "task" prop

However, after using useVmodel to bind to task.done like v-model, eslint cannot detect this direct modification of the prop, so the child component can directly modify the task value passed in through props:

```js
const task = useVModel(props, 'task', emits, {
  passive: true,
  deep: true,
  // clone: true,
});

task.value.done = true;
```

**Comment by Sevody** [comment]
Also encountered this problem. It seems like if the parent component passes props via v-model,  useVModel will trigger watch cyclically:
```ts
// vueuse/packages/core/useVModel
/index.ts
// ...
if (passive) {
    const initialValue = getValue()
    const proxy = ref<P[K]>(initialValue!)

    watch(
      () => props[key!],
      v => {
       // called cyclically
        proxy.value = cloneFn(v) as UnwrapRef<P[K]>
       }
    )

    watch(
      proxy,
      (v) => {
        // called cyclically
        if (v !== props[key!] || deep)
          triggerEmit(v as P[K])
      },
      { deep },
    )

    return proxy
  }
// ...
```

and if performs a deep comparison between v and props[key!], which will stopping the circle called:
```ts
watch(
      proxy,
      (v) => {
        // deep comparison to stop triggerEmit in deep mode
        if (
          (!deep && v !== props[key!]) ||
          (deep && !isEqual(cloneDeep(v), cloneDeep(props[key!])))
        ) {
          triggerEmit(v as P[K]);
        }
      },
      { deep },
    );
```
I'm not sure this is the right approach...

**Comment by Sevody** [comment]
Also encountered the infinite loop  problem. It seems like if the parent component change the props in `clone: true` mode, useVModel will trigger watch cyclically:

```ts
// vueuse/packages/core/useVModel
/index.ts
// ...
if (passive) {
    const initialValue = getValue()
    const proxy = ref<P[K]>(initialValue!)

    watch(
      () => props[key!],
      v => {
       // called cyclically
        proxy.value = cloneFn(v) as UnwrapRef<P[K]>
       }
    )

    watch(
      proxy,
      (v) => {
        // called cyclically
        if (v !== props[key!] || deep)
          triggerEmit(v as P[K])
      },
      { deep },
    )

    return proxy
  }
// ...
```
and if performs a deep comparison between v and props[key!], which will stopping the circle called:
```ts
watch(
      proxy,
      (v) => {
        // deep comparison to stop triggerEmit in deep mode
        if (
          (!deep && v !== props[key!]) ||
          (deep && !isEqual(cloneDeep(v), cloneDeep(props[key!])))
        ) {
          triggerEmit(v as P[K]);
        }
      },
      { deep },
    );
```
I'm not sure this is the right approach...
