### ISSUE TITLE
useColorMode and useDark affects the transtion property

### ISSUE THREAD

**Issue by wabi-habi** [vueuse/vueuse#3063]
### Describe the bug

When using useColorMode and useDark with @vueuse/core, version 9 does not affect the transition property, but updating to version 10 disables the transition property!

### Reproduction

>10

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 301.06 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zaqvil** [comment]
Because the `disableTransition` has added a default field that is `true` in v10.You should add this param with `false`.
<img width="427" alt="image" src="https://user-images.githubusercontent.com/24447053/236410197-5b35eaac-0b58-4199-8bb3-cd99977e2565.png">

**Comment by wabi-habi** [comment]
> Because the `disableTransition` has added a default field that is `true` in v10.You should add this param with `false`.
> <img alt="image" width="427" src="https://user-images.githubusercontent.com/24447053/236410197-5b35eaac-0b58-4199-8bb3-cd99977e2565.png">

Thanks for the reply, it has been solved, step in the hole: if only useColorMode, set `disableTransition` to `false` is not effective, also must set `disableTransition` of useDark to `false` as well
