### ISSUE TITLE
[FEATURE REQUEST] useSSE

### ISSUE THREAD

**Issue by go4cas** [vueuse/vueuse#3064]
### Clear and concise description of the problem

The `useWebSocket` composable provides a really good web socket client. It would be great if we could have a similar client for Server Sent Events (SSE).

### Suggested solution

- Add server SSE endpoint URL as an argument to the composable.
- Parameters to enable connection retry: `retries` (number of retries) and `retryInterval` (seconds between retries)
- Event hooks to receive events/messages
- Event hook on connection
- Event hook on disconnection

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
I think I'll have a use for this coming up soon, so I might look into doing an implementation for it in the next week or so.
