### ISSUE TITLE
Moved element loses state (useSortable)

### ISSUE THREAD

**Issue by Robstei** [vueuse/vueuse#3073]
### Describe the bug

The function moveArrayElement removes and reads the element to the list. This causes the element to rerender and lose its state.

This behaviour could either be documented or changed by moving the elements in a copied array before changing the ref itself.

Manually reordering before overwriting the ref could look like this:

```
useSortable("#card-wrapper-state-kept", items, {
  onUpdate: (e) => {
    const newCards = items.value.slice();
    moveArrayElement(newCards, e.oldIndex, e.newIndex);
    items.value = newCards;
  },
});
```

### Reproduction

https://github.com/Robstei/usesortable_rerender

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 9.27 GB / 15.56 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.63
    Firefox: 112.0.2
  npmPackages:
    @vueuse/integrations: ^10.1.2 => 10.1.2 
    vue: ^3.2.47 => 3.2.47
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by smallnine9** [comment]
This issue arises due to #2924

**Comment by smallnine9** [comment]
<img width="1445" alt="截屏2023-05-14 13 41 31" src="https://github.com/vueuse/vueuse/assets/35493996/9135af6c-6303-48df-a439-f2459c6a085b">

When we use sortablejs， it will disorder the sequence of text nodes and element nodes.
And when we using vue to update dom, vue will move node before the text node anchor, so we have to remove an element from the list and then add it to ensure the vue can work correctly
