### ISSUE TITLE
Can the useMousePressed support specifying left, right, middle mouse button, or ignoring one of them?

### ISSUE THREAD

**Issue by uovol** [vueuse/vueuse#3074]
### Clear and concise description of the problem

Currently, all mouse buttons are triggered by default. 

In some cases, I only want the left button to trigger press. So I want useMousePressed to support a button that specifies the mouse.

In addition, when the right mouse button is pressed, the value of passed is always true unless the left or middle button is clicked. 

It seems that the "mouseup" event of the right mouse button did not take effect, maybe it was blocked by the right-click menu?(Is this a bug?)

[https://vueuse.org/core/useMousePressed](https://vueuse.org/core/useMousePressed) This link can be reproduced.

### Suggested solution

useMousePressed Support mouse button options

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by smallnine9** [comment]
sounds reasonable
maybe we can add
```
useMousePressed({
mouseButton: 'left'
})
```
let uses can monitor the mouse at a finer granularity

**Comment by smallnine9** [comment]
And maybe we should prevent contextmenu event when click right mouse button? should we ?

**Comment by uovol** [comment]
> 

Maybe can be used as a options, just enable prevent by default when mouseButton: 'right'. if this is valid

**Comment by uovol** [comment]
Thanks a million. thank you for your hard work
