### ISSUE TITLE
canScrollVertical & canScrollHorizontal properties to useScroll

### ISSUE THREAD

**Issue by bennyschudel** [vueuse/vueuse#3079]
### Clear and concise description of the problem

I would like to show a shadow on the edges that have content that is hidden. As it is of now, I don't know an easy way because **bottomArrived**  and **rightArrived** are **false** when there is no scrolling at all.

### Suggested solution

I suggest do either change **bottomArrived**  and **rightArrived** to **true** when there is no scrolling or even add more flags like **canScrollVertical**  and **canScrollHorizontal**

### Alternative

Check if the container can scroll with javascript and a directive.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by smallnine9** [comment]
same problem #2875
