### ISSUE TITLE
通过带锚点的链接进入 https://vueuse.org/functions.html 时无法显示正确的过滤结果。

### ISSUE THREAD

**Issue by AemonCao** [vueuse/vueuse#3087]
### Describe the bug

一个文档错误，在访问这个地址时： <https://vueuse.org/functions.html#category=Time> ，过滤结果显示不正确。

错误的：<img width="1224" alt="截屏2023-05-11 18 35 42" src="https://github.com/vueuse/vueuse/assets/19542659/e1a4683a-3a1a-4eae-85ca-7296cade6a55">

正确的：<img width="1226" alt="截屏2023-05-11 18 36 34" src="https://github.com/vueuse/vueuse/assets/19542659/322e14a5-3da2-47ed-a4c4-3a64a3e837b1">

### Reproduction

https://github.com/vueuse/vueuse/blob/main/packages/functions.md

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 127.45 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 7.15.1 - /opt/homebrew/bin/npm
    Watchman: 2021.12.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 113.0.5672.92
    Safari: 16.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by okxiaoliang4** [comment]
When doc using build mode, will got a error `Hydration completed but contains mismatches`. I think maybe is [vitepress](https://github.com/vuejs/vitepress/issues?q=is%3Aissue+Hydration+completed+but+contains+mismatches+) bug。
