### ISSUE TITLE
Proposed Feature: useFireAuth

### ISSUE THREAD

**Issue by jacobclevenger** [vueuse/vueuse#309]
This is a proposal for a new feature called `useFireAuth`. It would live under the `@vueuse/firebase` package. The general idea would be to provide a reactive `user` object as well as a reactive `isAuthenticated` and reactive `authenticationStatus` to allow for easier development using Firebase's authentication API.

- The reactive `user` object would  provide an instance of the `firebase.User` type if a user is authenticated otherwise it will be null.
- The `isAuthenticated` object would be `true` if the user is authenticated otherwise it will be `false`.
- The `authenticationStatus` would provide 3 different states, `Pending`, `Unauthenticated`, and `Authenticated`. This would allow for a user to provide a loading UI state that wouldn't be possible with the `isAuthenticated` object. 

The general idea I have for how this might work would be something like
```html
<script setup lang="ts">
import firebase from 'firebase/app'
import 'firebase/auth'
import { useFireAuth } from '@vueuse/firebase'

 const { user, isAuthenticated, signInWithPopup } = useFireAuth()

const signIn = () => {
  signInWithPopup(new firebase.auth.GithubAuthProvider())
}
</script>

<template>
  <div>
    <button v-if="!isAuthenticated" @click="signIn">Sign in with Github</button>
    <pre v-else>{{ user }}</pre>
  </div>
</template>
```

If you like this idea let me know and I'd be more than happy to create a PR for it. Also if you have any ideas for improvements on the proposed API let me know and I'll try to incorporate them into the proposed feature if you think it would be worth adding to the project. 😄

**Comment by antfu** [comment]
Sounds good, that's see the PR, thanks!
