### ISSUE TITLE
extendRef and vue@3.3.2 use toRef value is incorrect

### ISSUE THREAD

**Issue by hairyf** [vueuse/vueuse#3093]
### Describe the bug

```ts
import { extendRef } from '@vueuse/core'
import { toRef, ref } from 'vue'
const loading = ref(false)
const value= ref([])
const extendValue = extendRef(value, { loading })
const toLoading = toRef(extendValue, 'loading')
toLoading.value // []
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-4xxdjs/?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz     
    Memory: 1.33 GB / 15.90 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by coderwei99** [comment]
~~~javascript
const toLoading = toRef(extendValue, 'loading') 
// extendValue is of type ref, so toRef does nothing, it simply returns extendValue
~~~

vue toRef source
~~~javascript
export function toRef(
  source: Record<string, any> | MaybeRef,
  key?: string,
  defaultValue?: unknown
): Ref {
  if (isRef(source)) { 
    return source // here return your extendValue
  } else if (isFunction(source)) {
    return new GetterRefImpl(source) as any
  } else if (isObject(source) && arguments.length > 1) {
    return propertyToRef(source, key!, defaultValue)
  } else {
    return ref(source)
  }
}
~~~

**Comment by hairyf** [comment]
I don't understand, so is this a Vue error because it was effective in previous versions

If that's the case, extendRef will become very limited. I have used a lot on previous projects, what should I do?

**Comment by smallnine9** [comment]
In fact, I found extendRef doesn't work (using vueuse.org demo code)

**Comment by smallnine9** [comment]
Because vue3.3 change the impl of toRef, maybe we should make compatibility.

**Comment by antfu** [comment]
`extendRef` was not intended to use along with `toRef`. In that case, I think it's better to use something like `propertyToRef` instead.

**Comment by hairyf** [comment]
`propertyToRef 'has not been exposed. @ antfu, do you have any alternative solutions?
