### ISSUE TITLE
useInfiniteScroll - Hidden elements are loaded automatically

### ISSUE THREAD

**Issue by k983551019** [vueuse/vueuse#3098]
### Describe the bug

当需要监听的实例滚动被隐藏时， 会自动触发load more
useInfiniteScroll - Hidden elements are loaded automatically

### Reproduction

https://stackblitz.com/edit/vitejs-vite-u6bt1k/?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz
    Memory: 5.29 GB / 24.00 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/components: ^10.1.2 => 10.1.2
    @vueuse/core: ^10.1.2 => 10.1.2
    @vueuse/head: ^1.1.26 => 1.1.26
    vue: 3.3.2 => 3.3.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by smallnine9** [comment]
I'd love to add logic to cancel `loadmore` when display none. But if we set the visibility to hidden, should the `loadmore` function work? 🤔

**Comment by k983551019** [comment]
> I'd love to add logic to cancel `loadmore` when display none. But if we set the visibility to hidden, should the `loadmore` function work? 🤔

  "@vueuse/core": "^9.13.0"
  https://stackblitz.com/edit/vitejs-vite-wevedw/?file=package.json
I don't know if that's the design,
Hide should not continue **loadmore**
