### ISSUE TITLE
Add leading/trailing options to debounce functions

### ISSUE THREAD

**Issue by VincEnterprise** [vueuse/vueuse#3099]
### Clear and concise description of the problem

See: 

[#2029](https://github.com/vueuse/vueuse/issues/2029)

Please re-open  🙏

### Suggested solution

Merge this?

[#2029](https://github.com/vueuse/vueuse/issues/2029)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by VincEnterprise** [comment]
bump

**Comment by antfu** [comment]
Yeah definitely. PR Welcome :)
