### ISSUE TITLE
vue not export `propertyToRef` and cannot use the properties of `extendRef` on the `template`

### ISSUE THREAD

**Issue by hairyf** [vueuse/vueuse#3105]
### Describe the bug

previous question: #3093

Is there a similar alternative since Vue did not expose `propertyToRef`?

```ts
// hook.ts
import { extendRef } from '@vueuse/core'
import { toRef, ref } from 'vue'
export function useTestHook() {
   const loading = ref(false)
   const value= ref([])
   return extendRef(value, { loading })
}
```

```html
<script setup>
   import { useTestHook } from './hook'
   // not export propertyToRef error
   import { toRef, propertyToRef } from 'vue'
   
   const value = useTestHook()
   const loading = toRef(value, 'loading') // ref([])
</script>

<template>
   <!-- cannot use the extendRef properties -->
   <div :class=[loading && '...']>
     ...
   </div>
</template>
```

additionally, I made a pull request in vue/core, but it was rejected. It's possible that my description wasn't clear enough, which has caused many projects that use `extendRef` to fail upgrading to versions higher than `vue@3.3.2`. I would greatly appreciate it if this could be resolved.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-4xxdjs/?file=src%2FApp.vue

### System Info

```Shell
-
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It shouldn't be hard for you to implement a `propertyToRef` on your codebase I think, even like:

```ts
function propertyToRef(data, prop) {
  return computed({
    get() { return data[prop] },
    set(v) { data[prop] = v }
  }
}
```
