### ISSUE TITLE
@vue/composition-api is not declared as a dependency

### ISSUE THREAD

**Issue by unikitty37** [vueuse/vueuse#312]
With a Vue 2 app, after running `yarn add @vueuse/core`, compilation fails with

```
Failed to compile.

./node_modules/vue-demi/lib/index.esm.js
Module not found: Error: Can't resolve '@vue/composition-api' in '/usr/src/frontend/node_modules/vue-demi/lib'
```

Running `yarn add @vue/composition-api` fixes this.

Could VueUse declare `@vue/composition-api` as a dependency so it installs automatically, or does this break things for Vue 3 apps?

**Comment by antfu** [comment]
We have defined @vue/composition-api as peerDependencies, depends on your package manager, they would install it automatically or throw a warning. We assume users already aware the @vue/composition-api plugin is needed to have Composition API works in Vue 2.

**Comment by TonyPythoneer** [comment]
Excuse me @antfu 

I have the same issue about this situation. Could you help me how to set up or resolve this issue? thx
https://github.com/nuxt/nuxt.js/issues/9567

**Comment by Corgis** [comment]
yarn add @vue/composition-api
