### ISSUE TITLE
全屏时不再显示提示【按ESC 退出全屏】。

### ISSUE THREAD

**Issue by isrun** [vueuse/vueuse#3124]
### Clear and concise description of the problem

弹出的提示框按ESC退出全屏，需要配置项。配置后，全屏时不再显示提示【按ESC 退出全屏】。
显示的时长太长了。往往熟悉全屏功能的用户，要看此提醒。

### Suggested solution

目前

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
It's from the browser, not something we could change.
