### ISSUE TITLE
Type mismatch in `useToggle`

### ISSUE THREAD

**Issue by Raiondesu** [vueuse/vueuse#313]
In the definition of `useToggle`, its return type is set to either `() => void` or `[Ref<boolean>, () => void]`:
https://github.com/vueuse/vueuse/blob/dfd0dea8b3288b99bcc662954dbf92a63a4d9e41/packages/shared/useToggle/index.ts#L10-L11

which is incorrect, because in actuality the function returns either `() => boolean` or `[Ref<boolean>, () => boolean]`:
https://github.com/vueuse/vueuse/blob/dfd0dea8b3288b99bcc662954dbf92a63a4d9e41/packages/shared/useToggle/index.ts#L13-L22

So...

Is this intentional?

If not, then I'll gladly fix the types, because returning `boolean` from the resulting toggle function (instead of `void`) is actually very useful:
```ts
const isOn = ref(false);
const toggle = useToggle(isOn);

// So we can then just do
setOnState(toggle())

// instead of
toggle()
setOnState(isOn)
// which is much more cumbersome, especially in templates
```

And the return types should match the return values so that a user won't find themselves in an awkward situation trying to use the toggle function directly in an arrow function:
```ts
const canToggle = true;
const isOn = ref(false);
const toggle = useToggle(isOn);

// TS doesn't recognize the error here, obviously
const toggleOn = (): void => canToggle ? toggle() : undefined;

// but!
console.log(toggleOn());
//=> true
```

**Comment by antfu** [comment]
Oh sure, let's fix it, thanks for catching this!
