### ISSUE TITLE
useScroll: cannot pass window to "getComputedStyle" as an element

### ISSUE THREAD

**Issue by mjnoroozi** [vueuse/vueuse#3136]
### Describe the bug
when I try to pass window to useInfiniteScroll as the element to track scroll on it, this issue occurs.

the error:
```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'
```

I checked the source of error found that since the useInfiintieScroll passes the element to useScroll and the useScroll passes the element to `getComputedStyle` to get the desired element data, the error is occurs.
The `getComputedStyle` calls inside the `setArrivedState` function in the useScroll.

### Reproduction

-

### System Info

```Shell
-
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by OneLoneFox** [comment]
Is there any specific reason you have to use window and can't just use document.body? getComputedStyle is used to calculate the correct scroll direction `flex-direction: column-reverse|row-reverse` is used

**Comment by OneLoneFox** [comment]
Is there any specific reason you have to use window and can't just use document.body? getComputedStyle is used to calculate the correct scroll direction where `flex-direction: column-reverse|row-reverse`

**Comment by OneLoneFox** [comment]
Is there any specific reason you have to use window and can't just use document.body? getComputedStyle is used to calculate the correct scroll direction where `flex-direction: column-reverse|row-reverse` is used

**Comment by steklopod** [comment]
I have the same error after nuxt ipgrade to 3.8.1:

```js


const scrollBox = ref<HTMLDivElement>()

const { arrivedState } = useScroll(scrollBox) // <-- 👈🏻 This gives an error now
```

Before update everything was working
<img width="1396" alt="Снимок экрана 2023-11-16 в 16 06 03" src="https://github.com/vueuse/vueuse/assets/29500153/c82fc989-f14f-48ec-b6ec-873e5fcd5213">

<img width="1037" alt="Снимок экрана 2023-11-16 в 16 06 23" src="https://github.com/vueuse/vueuse/assets/29500153/28758128-b5ca-49fd-86a6-93d70b58cbbd">

**Comment by wangliangxin** [comment]
> I have the same error after nuxt ipgrade to 3.8.1:
> 
> ```js
> const scrollBox = ref<HTMLDivElement>()
> 
> const { arrivedState } = useScroll(scrollBox) // <-- 👈🏻 This gives an error now
> ```
> 
> Before update everything was working <img alt="Снимок экрана 2023-11-16 в 16 06 03" width="1396" src="https://private-user-images.githubusercontent.com/29500153/283497921-c82fc989-f14f-48ec-b6ec-873e5fcd5213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjEyMDksIm5iZiI6MTcwNjI2MDkwOSwicGF0aCI6Ii8yOTUwMDE1My8yODM0OTc5MjEtYzgyZmM5ODktZjE0Zi00OGVjLWI2ZWMtODczZTVmY2Q1MjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMGE4NTRiZmYzMDY2OWM3YmIwZjY5YTU0ODI1NDZiMzBhZDUwZWZmNTYyODljMjBhMzQ0MjJjODZkOGZhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_zmuhOeY1zwW56oz3PrzHITJfALSYohjnx4B3Pp_is">
> 
> <img alt="Снимок экрана 2023-11-16 в 16 06 23" width="1037" src="https://private-user-images.githubusercontent.com/29500153/283498026-28758128-b5ca-49fd-86a6-93d70b58cbbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjEyMDksIm5iZiI6MTcwNjI2MDkwOSwicGF0aCI6Ii8yOTUwMDE1My8yODM0OTgwMjYtMjg3NTgxMjgtYjVjYS00OWZkLTg2YTYtOTNkNzBiNThjYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYjQ3ZGQ1Yjc0NmU1ZGQwYjQxOTA3ZWU3YWE0ZDI4M2M0MGM5NDY4NDQxOTdkZGNkOGY1ZDk3OGVkNTJkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZibElmyhfBJ-exU7zmFta4KRAvblEKo7eNQZ7_c4hpk">

"I also encountered the same problem. How did you solve it?"

**Comment by mu16zi** [comment]
I remember that I used document instead of window object as the element and that worked,
but I though this issue was fixed after the pull request merged and I didn't test it after that.
upgrade your vuevue pkg and then check if the problem is fixed or not, Or Try to use document instead of window if you want to track scroll on it.

**Comment by mu16zi** [comment]
> > I have the same error after nuxt ipgrade to 3.8.1:
> > ```js
> > const scrollBox = ref<HTMLDivElement>()
> > 
> > const { arrivedState } = useScroll(scrollBox) // <-- 👈🏻 This gives an error now
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Before update everything was working <img alt="Снимок экрана 2023-11-16 в 16 06 03" width="1396" src="https://private-user-images.githubusercontent.com/29500153/283497921-c82fc989-f14f-48ec-b6ec-873e5fcd5213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjEyMDksIm5iZiI6MTcwNjI2MDkwOSwicGF0aCI6Ii8yOTUwMDE1My8yODM0OTc5MjEtYzgyZmM5ODktZjE0Zi00OGVjLWI2ZWMtODczZTVmY2Q1MjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMGE4NTRiZmYzMDY2OWM3YmIwZjY5YTU0ODI1NDZiMzBhZDUwZWZmNTYyODljMjBhMzQ0MjJjODZkOGZhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_zmuhOeY1zwW56oz3PrzHITJfALSYohjnx4B3Pp_is">
> > <img alt="Снимок экрана 2023-11-16 в 16 06 23" width="1037" src="https://private-user-images.githubusercontent.com/29500153/283498026-28758128-b5ca-49fd-86a6-93d70b58cbbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjEyMDksIm5iZiI6MTcwNjI2MDkwOSwicGF0aCI6Ii8yOTUwMDE1My8yODM0OTgwMjYtMjg3NTgxMjgtYjVjYS00OWZkLTg2YTYtOTNkNzBiNThjYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYjQ3ZGQ1Yjc0NmU1ZGQwYjQxOTA3ZWU3YWE0ZDI4M2M0MGM5NDY4NDQxOTdkZGNkOGY1ZDk3OGVkNTJkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZibElmyhfBJ-exU7zmFta4KRAvblEKo7eNQZ7_c4hpk">
> 
> "I also encountered the same problem. How did you solve it?"

I remember that I used document instead of window object as the element and that worked,
but I though this issue was fixed after the pull request merged and I didn't test it after that.
upgrade your vuevue pkg and then check if the problem is fixed or not, Or Try to use document instead of window if you want to track scroll on it.

**Comment by steklopod** [comment]
> > I have the same error after nuxt ipgrade to 3.8.1:
> > ```js
> > const scrollBox = ref<HTMLDivElement>()
> > 
> > const { arrivedState } = useScroll(scrollBox) // <-- 👈🏻 This gives an error now
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Before update everything was working <img alt="Снимок экрана 2023-11-16 в 16 06 03" width="1396" src="https://private-user-images.githubusercontent.com/29500153/283497921-c82fc989-f14f-48ec-b6ec-873e5fcd5213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjEyMDksIm5iZiI6MTcwNjI2MDkwOSwicGF0aCI6Ii8yOTUwMDE1My8yODM0OTc5MjEtYzgyZmM5ODktZjE0Zi00OGVjLWI2ZWMtODczZTVmY2Q1MjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMGE4NTRiZmYzMDY2OWM3YmIwZjY5YTU0ODI1NDZiMzBhZDUwZWZmNTYyODljMjBhMzQ0MjJjODZkOGZhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_zmuhOeY1zwW56oz3PrzHITJfALSYohjnx4B3Pp_is">
> > <img alt="Снимок экрана 2023-11-16 в 16 06 23" width="1037" src="https://private-user-images.githubusercontent.com/29500153/283498026-28758128-b5ca-49fd-86a6-93d70b58cbbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjEyMDksIm5iZiI6MTcwNjI2MDkwOSwicGF0aCI6Ii8yOTUwMDE1My8yODM0OTgwMjYtMjg3NTgxMjgtYjVjYS00OWZkLTg2YTYtOTNkNzBiNThjYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYjQ3ZGQ1Yjc0NmU1ZGQwYjQxOTA3ZWU3YWE0ZDI4M2M0MGM5NDY4NDQxOTdkZGNkOGY1ZDk3OGVkNTJkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZibElmyhfBJ-exU7zmFta4KRAvblEKo7eNQZ7_c4hpk">
> 
> "I also encountered the same problem. How did you solve it?"

It's not solved yet because MR is not merged

**Comment by steklopod** [comment]
> > > I have the same error after nuxt ipgrade to 3.8.1:
> > > ```js
> > > const scrollBox = ref<HTMLDivElement>()
> > > 
> > > const { arrivedState } = useScroll(scrollBox) // <-- 👈🏻 This gives an error now
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Before update everything was working <img alt="Снимок экрана 2023-11-16 в 16 06 03" width="1396" src="https://private-user-images.githubusercontent.com/29500153/283497921-c82fc989-f14f-48ec-b6ec-873e5fcd5213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjEyMDksIm5iZiI6MTcwNjI2MDkwOSwicGF0aCI6Ii8yOTUwMDE1My8yODM0OTc5MjEtYzgyZmM5ODktZjE0Zi00OGVjLWI2ZWMtODczZTVmY2Q1MjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMGE4NTRiZmYzMDY2OWM3YmIwZjY5YTU0ODI1NDZiMzBhZDUwZWZmNTYyODljMjBhMzQ0MjJjODZkOGZhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_zmuhOeY1zwW56oz3PrzHITJfALSYohjnx4B3Pp_is">
> > > <img alt="Снимок экрана 2023-11-16 в 16 06 23" width="1037" src="https://private-user-images.githubusercontent.com/29500153/283498026-28758128-b5ca-49fd-86a6-93d70b58cbbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjEyMDksIm5iZiI6MTcwNjI2MDkwOSwicGF0aCI6Ii8yOTUwMDE1My8yODM0OTgwMjYtMjg3NTgxMjgtYjVjYS00OWZkLTg2YTYtOTNkNzBiNThjYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYjQ3ZGQ1Yjc0NmU1ZGQwYjQxOTA3ZWU3YWE0ZDI4M2M0MGM5NDY4NDQxOTdkZGNkOGY1ZDk3OGVkNTJkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZibElmyhfBJ-exU7zmFta4KRAvblEKo7eNQZ7_c4hpk">
> > 
> > 
> > "I also encountered the same problem. How did you solve it?"
> 
> If I'm not mistaken, I remember that I used document instead of window object as the element and that worked for my case, but I though this issue was fixed after the pull request merged and I didn't test it after that. upgrade your vueuse pkg and then check if the problem is fixed or not, Or Try to use document instead of window if you want to track scroll on it.

The Scroll is on an HtmlElement. Not on window/document.

**Comment by Blackfaded** [comment]
Facing the same issue on a component which is a componentinstance. Would love to see the above PR merged
