### ISSUE TITLE
useMouse don't working

### ISSUE THREAD

**Issue by XurshidKarimov** [vueuse/vueuse#3138]
### Describe the bug

useMouse don't working. Showing only 0, 0

<template>
  <div>
    <p>{{ x }} {{ y }}</p>
  </div>
</template>

<script setup>
import { reactive } from 'vue'
import { useMouse } from '@vueuse/core'

const {x, y} = reactive(useMouse())

</script>

### Reproduction

https://github.com/vueuse/vueuse/blob/main/packages/core/useMouse/index.ts

### System Info

```Shell
Windows 11 Pro
22H2
AMD Ryzen 5 5500U with Radeon Graphics            2.10 GHz
20.0 GB (19.4 GB usable)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XurshidKarimov** [comment]
solved

**Comment by xjArea** [comment]
How ? I meet the same problem, Now I know it need `vueuse/shared` module, but I don't know how to use it, I mean how to import this module ? here is my code, when the mouse is move, the `log` will change, but the `span` always `0`. 😭😭😭

```html
<script async="async" src="https://cdn.jsdelivr.net/npm/es-module-shims@1.8.0/dist/es-module-shims.min.js"></script>
<script type="importmap">
{ "imports" : {
    "vue"            : "https://cdn.jsdelivr.net/npm/vue@3.3.4/dist/vue.esm-browser.prod.js",
    "@vueuse/core"   : "https://cdn.jsdelivr.net/npm/@vueuse/core@10.2.1/+esm", 
    "@vueuse/shared" : "https://cdn.jsdelivr.net/npm/@vueuse/shared@9.13.0/+esm"
} }
</script>

<div id="app01">
    <span>mouse : {{x}} | {{y}}</span>
</div>
<script type="module">
import * as Vue from 'vue';
import * as VueUseCore from '@vueuse/core';
import * as VueUseShared from '@vueuse/shared'; // how to use it ?

let vc01 = Vue.createApp({
    setup : function(props, {attrs, emit, slots, expose, }){
        
        let { x, y, } = VueUseCore.useMouse();
        
        setInterval(function(){
            console.log(x.value, y.value);
        }, 1000);
        
        return { x, y, };
        
    },
});
let vi01 = vc01.mount('#app01');
</script>
```

**Comment by xjArea** [comment]
Oh, I see, is the `+esm`, we can't use jsdelivr provide the `+esm` file, because it will no read `@vueuse/shared` module.
Change the code like below, that will be fine. 😑😑😑

```html
<script async="async" src="https://cdn.jsdelivr.net/npm/es-module-shims@1.8.0/dist/es-module-shims.min.js"></script>
<script type="importmap">
{ "imports" : {
    "vue-demi"       : "https://cdn.jsdelivr.net/npm/vue-demi@0.14.5/lib/v3/index.min.mjs",
    "vue"            : "https://cdn.jsdelivr.net/npm/vue@3.3.4/dist/vue.esm-browser.prod.js",
    "@vueuse/core"   : "https://cdn.jsdelivr.net/npm/@vueuse/core@10.2.1/index.min.mjs", 
    "@vueuse/shared" : "https://cdn.jsdelivr.net/npm/@vueuse/shared@10.2.1/index.min.mjs"
} }
</script>

<div id="app01">
    <span>mouse : {{x}} | {{y}}</span>
</div>

<script type="module">
import * as Vue from 'vue';
import * as VueUseCore from '@vueuse/core';

let vc01 = Vue.createApp({
    setup : function(props, {attrs, emit, slots, expose, }){
        let { x, y, } = VueUseCore.useMouse();
        return { x, y, };
    },
});

let vi01 = vc01.mount('#app01');
</script>
```
