### ISSUE TITLE
setting the value of x or y too often will result in a 'Maximum call stack size exceeded' error

### ISSUE THREAD

**Issue by koenpeters** [vueuse/vueuse#3140]
### Describe the bug

Not sure if I misuse useDraggable here, but when I run the code below I get a 'Maximum call stack size exceeded' error. The code sets the value of the x ref that is returned by useDraggable repeatedly. When errors start occuring it logs the iteration count and the error itself. In my case this is always after 574 iterations. 

```
<template>
  <div ref="windowRef"></div>
</template>

<script lang="ts" setup>
import { ref, onMounted } from "vue";
import { useDraggable } from "@vueuse/core";

const windowRef = ref<HTMLElement>();
const { x } = useDraggable(windowRef);
let i = 0;

onMounted(() => {
  setInterval(() => {
    i++;
    try {
      x.value = 0;
    } catch (error) {
      console.log(i, error);
    }
  }, 1);
});
</script>
```

The error:

> RangeError: Maximum call stack size exceeded
    at Object.get2 [as get] (reactivity.esm-bundler.js:425:19)
    at Reflect.get (<anonymous>)
    at Object.get2 [as get] (reactivity.esm-bundler.js:444:25)
    at Reflect.get (<anonymous>)
    at Object.get2 [as get] (reactivity.esm-bundler.js:444:25)
    at Reflect.get (<anonymous>)
    at Object.get2 [as get] (reactivity.esm-bundler.js:444:25)
    at Reflect.get (<anonymous>)
    at Object.get2 [as get] (reactivity.esm-bundler.js:444:25)
    at Reflect.get (<anonymous>)

This does not happen when I set the x value via the position ref:

```
<template>
  <div ref="windowRef"></div>
</template>

<script lang="ts" setup>
import { ref, onMounted } from "vue";
import { useDraggable } from "@vueuse/core";

const windowRef = ref<HTMLElement>();
const { position } = useDraggable(windowRef);
let i = 0;

onMounted(() => {
  setInterval(() => {
    i++;
    try {
      position.value.x = 0;
    } catch (error) {
      console.log(i, error);
    }
  }, 1);
});
</script>
```

For reproduction see the link and then look in the console for the error 

### Reproduction

https://stackblitz.com/edit/vitejs-vite-mjfkvg?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 441.09 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 112.1.50.121
    Chrome: 113.0.5672.126
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @vueuse/components: ^10.1.0 => 10.1.2 
    @vueuse/core: ^10.1.0 => 10.1.2 
    vue: ^3.2.33 => 3.3.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fxjs** [comment]
Same
