### ISSUE TITLE
Is there a plan like Lodash that import on demand?

### ISSUE THREAD

**Issue by ankyo** [vueuse/vueuse#3146]
### Clear and concise description of the problem

I only use a few functions, but import the whole 200K file, I want to import only the functions I use

### Suggested solution

I wish I could import only the functions I use like lodash

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't know what do you mean. We support three-shaking since day one. And much better than Lodash I believe.

**Comment by ankyo** [comment]
Thanks, I didn't notice the file size, I just saw that the whole file was referenced
--------------------------------------------------------------------------------------------------
@vueuse+core@10.1.2_vue@3.3.2/node_modules/@vueuse/core/index.mjs

**Comment by Adizbek** [comment]
@antfu, maybe I did something wrong, but i could not find the cause. I've analyzed my bundle and it's huge. I think there is problem with tree-shaking ? 

<img width="479" alt="image" src="https://github.com/user-attachments/assets/741cab77-66dc-4bfe-8b8a-00b1c789bf49" />

The only used imports:
<img width="809" alt="image" src="https://github.com/user-attachments/assets/cbb474c9-6172-4349-a730-153379a02d19" />
