### ISSUE TITLE
useCookies doesnt write/read cookie 😞

### ISSUE THREAD

**Issue by Asim-Tahir** [vueuse/vueuse#315]
Thanks for the graceful project 🙏
I made a [demo](https://codesandbox.io/s/demo-usecookies-not-working-heheq?file=/src/components/HelloWorld.vue) into `HelloWorld.vue` component. Am I overlooking something in this demo?
Thx for your help in advance

**Comment by jacobclevenger** [comment]
Make sure you have the `universal-cookie` package installed. I created a small demo that you can checkout to see how it works https://github.com/jacobclevenger/vueuse-cookies-demo

**Comment by Asim-Tahir** [comment]
Thank you for your time.
Thx for the demo, its working very well.
