### ISSUE TITLE
refDebounced doesn't work with objects

### ISSUE THREAD

**Issue by HugeLetters** [vueuse/vueuse#3158]
### Describe the bug

`debTest` gets updated immediately instead of after a 1000ms delay.
```typescript
const test = ref({ value: 'TEST' });
const debTest = refDebounced(test, 1000, { maxWait: 2000 });
```

Doing this works but is quite wordy with bigger objects.
```typesript
const test = ref({ value: 'TEST' });
const debTest = refDebounced(
	computed(() => ({ value: test.value.value })),
	1000,
	{ maxWait: 2000 }
);
```

### Reproduction

examples provided above

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 2.19 GB / 15.33 GB
  Binaries:
    Node: 20.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/core: ^10.1.2 => 10.1.2
    @vueuse/nuxt: ^10.1.2 => 10.1.2
    vue: ^3.3.2 => 3.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HugeLetters** [comment]
In case anyone stumbles upon this I've solved this later with - however if your object is deeply nested I assume this wouldn't work on deep properties.
```typescript
const test = ref({ value: 'TEST' });
const debTest = refDebounced({...test}, 1000, { maxWait: 2000 });
```

**Comment by XavierChevalier** [comment]
I've the same issue and the way you solving this doesn't work for me.
I think the `deep` parameter should be added, like `watch` function.

**Comment by Weasy666** [comment]
Can we reopen this? `refDebounced` still doesn't work with objects
