### ISSUE TITLE
useRouteParams with transform: Number won't accept 0 as value

### ISSUE THREAD

**Issue by tdebooij** [vueuse/vueuse#3160]
### Describe the bug

When using useRouteParams with { transform: Number }, setting the value to 0 will throw `Uncaught (in promise) Error: Missing required param "pagenumber"`. Probably because 0 is a falsy value.

Reproduction case:
```
const pageIndex = useRouteParams("pagenumber", 1, { transform: Number });

pageIndex.value = 0
```

This means I either have to stop using the transform: Number, and manually cast my value, or check for the 0 value and manually replace the route param. Would be awesome if this could be fixed.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cbjufi?file=pages%2F[pageindex]%2Frepro.vue

### System Info

```Shell
MacOs, Nuxt 3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anteriovieira** [comment]
Hi @tdebooij , the pull request #3184 fix it
