### ISSUE TITLE
changelog missing

### ISSUE THREAD

**Issue by Mister-Hope** [vueuse/vueuse#3163]
### Describe the bug

The ci of 10.2.0 failed, and I am not seeing release note or changelog.md in this repo.

Have you ever thought placing a CHANGLOG.md so that people can view changes between versions at one place for all?

### Reproduction

Not needed

### System Info

```Shell
Not related
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Thanks for the notice, the release is fixed now. I have no interest in maintaining CHANGELOG.md as they create duplications with GitHub releases.
