### ISSUE TITLE
useRouteParams break encoded url params

### ISSUE THREAD

**Issue by liwuyi27** [vueuse/vueuse#3164]
### Describe the bug

- pass the string contains slash('/') to route params, vue-router will encode it automatically.
`<router-link :to="{ name: 'reproduction', params: { foo: 'foo/a', bar: 'bar/a' }}"></router-link>`
get url: **/reproduction/foo%2Fa/bar%2Fa**
- then change the param **foo** by useRouteParams method 
`const foo = useRouteParams('foo');
foo.value = 'foo/b'`
get url: /**reproduction/foo/b/bar/a**
1) useRouteParams did not encode **'foo/b'** passed to **foo**;
2) even useRouteParams decoded param **bar** from `bar%2Fa` to `bar/a`;

### Reproduction

https://stackblitz.com/edit/vue-nxn5wt?file=src%2FApp.vue

### System Info

```Shell
Browsers:
    Google Chrome: 114.0.5735.134
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mwhispers** [comment]
> For me, I think this is reasonable. `useRouteParams` is a shorthand for a reactive `route.params`. So it should have the same behavior as navigation functions like `router.replace` or `router.push`. If you want to get encoded parameters, you should pass encoded parameters to `useRouteParams()`. A simple [case](https://stackblitz.com/edit/vue-hfgsrw?file=src%2Fcomponents%2FReproduction.vue).

Thanks for your reply! But i don't think this is reasonable.
First, in fact, vue-router would always `encode params` when join the path and `decode params` when extract from path.
Here is vue router docs about [Params](https://router.vuejs.org/api/interfaces/RouteLocationNormalizedLoaded.html#Properties-params) and [Path](https://router.vuejs.org/api/interfaces/RouteLocationNormalizedLoaded.html#Properties-path).
So, no mather `router.push`、`router.replace` or `route-link` should have the same behavior mentioned above. [Sample Code](https://stackblitz.com/edit/vue-uwccux?file=src%2Fcomponents%2FReproduction.vue)
- Code beblow **works well**:
`router.replace({ name: 'reproduction', params: { foo: 'foo/e'}})`
- Code likes source code of useRouteParams **can not work**:
`router.replace({ ...route, params: { foo: 'foo/c' } });` 
- If delete property **path**, it **works well**:
`const route = { ...route, params: { foo: 'foo/c'}};
delete route.path;
router.replace(route);`

Second, useRouteParams change **bar**  from `foo%2Fa` to `foo/a`, but i did not touch **bar**.This is a bug!

**Comment by Tzyito** [comment]
this is different from using the router directly, so I think this should be a bug, so i've just made a new [PR](https://github.com/vueuse/vueuse/pull/3182) to fix it.
