### ISSUE TITLE
useDark应用在v-model中会导致组件的动画失效

### ISSUE THREAD

**Issue by Cxk-1233** [vueuse/vueuse#3167]
### Describe the bug

代码如下
```vue
<script setup>
import { useDark, useToggle } from '@vueuse/core'
let isDark = useDark();
</script>
<template>
<el-switch v-model="isDark"></el-switch>
</template>
``` 

### Reproduction

https://github.com/Cxk-1233/use-dark-debug.git

### System Info

```Shell
无错误信息
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CooperHash** [comment]
![image](https://github.com/vueuse/vueuse/assets/73218815/2b0310b8-9836-4467-9b13-0edafe253f1e)

**Comment by Cxk-1233** [comment]
> ![图像](https://user-images.githubusercontent.com/73218815/248438551-2b0310b8-9836-4467-9b13-0edafe253f1e.png)
我并没有期望useDark为我处理css或是主题，动画是交由我来处理的，如果我使用
`
let dark = useDark();
v-mode="dark"
`
的写法，那么我的动画将会消失！
我尝试过
`
const toggleDark = useToggle(useDark());
let dark = useDark();
let isDark = ref(false);
watch(isDark, (newCount, oldCount) => {
  toggleDark();
});
`
我的动画仍然消失了，或许你没有理解我表达的意思，你应该阅读并尝试我的代码

**Comment by Cxk-1233** [comment]
> > ![图像](https://user-images.githubusercontent.com/73218815/248438551-2b0310b8-9836-4467-9b13-0edafe253f1e.png)
> > 我并没有期望useDark为我处理css或是主题，动画是交由我来处理的，如果我使用
> > `let dark = useDark(); v-mode="dark"`
> > 的写法，那么我的动画将会消失！
> > 我尝试过
> > `const toggleDark = useToggle(useDark()); let dark = useDark(); let isDark = ref(false); watch(isDark, (newCount, oldCount) => {   toggleDark(); });`
> > 我的动画仍然消失了，或许你没有理解我表达的意思，你应该阅读并尝试我的代码
In my Reproduction I give you two ways to write it,
1、`<el-switch v-model="isDark"></el-switch>`
2、`<el-switch v-model="isDark2"></el-switch>`
You should observe their animation, you will find that the animation of code 2 is normal, while the animation of code 1 is gone, and the switch switch becomes stiff

**Comment by leslie1312** [comment]
hi, you can try call it like this:
```ts
let isDark = useDark({ disableTransition: false })  // the default value is true
```
more options can be found here: [useColorMode#type-declarations](https://vueuse.org/core/useColorMode/#type-declarations)

**Comment by Cxk-1233** [comment]
> hi, you can try call it like this:
> 
> ```ts
> let isDark = useDark({ disableTransition: false })  // the default value is true
> ```
> 
> more options can be found here: [useColorMode#type-declarations](https://vueuse.org/core/useColorMode/#type-declarations)

I returned the version to "@vueuse/core" : "^9.1.0" and it worked

**Comment by antfu** [comment]
`disableTransition` is defaulted to be true in v10, you can disable it as @ leslie1312 mentioned.
