### ISSUE TITLE
useRouteQuery not reactive to navigation

### ISSUE THREAD

**Issue by some-user123** [vueuse/vueuse#3173]
### Describe the bug

If a query parameter is changed (e.g. by `navigateTo`), the resulting object is not changing.

To reproduce:
- Open repro link
- Enter "foo" and press navigate

Expected: param changes to `foo` along with change of URL.
Actual: param remains empty

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hkxvge?file=pages%2Findex.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @vueuse/router: ^10.2.0 => 10.2.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rdunk** [comment]
I'm seeing this issue after updating from `10.1.2` to `10.2.0`. Is it related to #3002?

**Comment by anteriovieira** [comment]
Hi guys, thanks for your report. I will investigate and fix it as soon as possible.

**Comment by duttonkj** [comment]
Having the same issue but with one caveat.  It only seems to break after running `npm run build`.  Continues to work for me in `development` but breaks in `production`.
