### ISSUE TITLE
Improve docs for createReusableTemplate

### ISSUE THREAD

**Issue by texastoland** [vueuse/vueuse#3179]
### Clear and concise description of the problem

I'd like to update `createReusableTemplate`'s docs:

1. They're missing some details from the [original](https://github.com/antfu/vue-reuse-template/blob/347f6d33ae917dd3166a93d2f9746c6a49d23282/README.md) like passing `$slots`.
2. They don't address how to forward attributes (simple but tricky to figure out).
3. The current naming convention leads to confusion like in #2975.

### Suggested solution

**Re. naming convention:**

Instead of:

```html
<script setup>
const [DefineTemplate, ReuseTemplate] = createReusableTemplate()
</script>

<template>
  <DefineTemplate>
    <!-- something complex -->
  </DefineTemplate>

  <dialog v-if="showInDialog">
    <ReuseTemplate />
  </dialog>
  <div v-else>
    <ReuseTemplate />
  </div>
</template>
```

A clearer alternative would simply be to not destructure:

```html
<script setup>
const MyComponent = createReusableTemplate()
</script>

<template>
  <MyComponent.define>
    <!-- something complex -->
  </MyComponent.define>

  <dialog v-if="showInDialog">
    <!-- clear where to find its definition -->
    <MyComponent.reuse />
  </dialog>
  <div v-else>
    <MyComponent.reuse />
  </div>
</template>
```

In context:

![VueUse Playground example](https://pbs.twimg.com/media/FzcguWOXgAAvHmy?format=jpg&name=4096x4096)

### Alternative

```html
<script setup>
const [TemplateMyComponent, MyComponent] = createReusableTemplate()
</script>

<template>
  <!-- kebab-case emulates core template tag -->
  <template-my-component>
    <!-- something complex -->
  </template-my-component>

  <dialog v-if="showInDialog">
    <MyComponent />
  </dialog>
  <div v-else>
    <MyComponent />
  </div>
</template>
```

In context:

![VueUse Playground example](https://pbs.twimg.com/media/FzcMGQeWcAEH1TY?format=jpg&name=4096x4096)

### Additional context

I'd also like to build up an example iteratively to explain each feature:

1. Show an example with duplication.
2. Refactor 2 sub-components into reusable templates.
3. Refactor the 2 reusable templates into 1 using slots.
4. Show how to forward attributes (even `v-model`) to a child component.
4. Reimplement the original 2 templates using the new 1.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by texastoland** [comment]
I tweeted the [example](https://twitter.com/texastoland/status/1672843009862270977?s=20) above and there seemed to be significant interest. PR welcome?

**Comment by thedamon** [comment]
I agree the docs could be improved. The only example of using it multiple times with different names is in the Typescript support section, so it's a little unclear that that's intended. We get the problem of it not being clear that we're defining variable names in our use when the default names are so descriptive of what's happening but never what we'd actually use

I agree that just having a different example in the docs would nudge us the right way.

I read through the whole docs but skipped the typescript section and was still thinking 'i want multiple templates, and i want to name them whatever i want!'

**Comment by texastoland** [comment]
I assume they'd be open to a PR I just haven't had a Vue project recently!
