### ISSUE TITLE
clipboard: text is nothing when copied text from other window before

### ISSUE THREAD

**Issue by xdewx** [vueuse/vueuse#3189]
### Describe the bug

though copied before, but can't get  content copied with `text` before `copy` is invoked.

It seems that `text` can only be set by `copy`, why not set `text` to the last copied content when init useClipboard?

### Reproduction

directly

### System Info

```Shell
windows 11
vueuse/core 9
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jd-solanki** [comment]
Can you please provide reproduction? You can use stackblitz, codesandbox or https://play.vueuse.org/

**Comment by Husky-Yellow** [comment]
Maybe it's because your tab bar doesn't get focus，
I didn't find this problem when the current tab was focused, you can try
[MDN Document/hasFocus](https://developer.mozilla.org/zh-CN/docs/Web/API/Document/hasFocus)
