### ISSUE TITLE
✨ new composable `toValueDeep`

### ISSUE THREAD

**Issue by jd-solanki** [vueuse/vueuse#3190]
### Clear and concise description of the problem

Hi 👋🏻 

We are aware of `toValue` inroduced in vue 3.3 but this doesn't work for nested object. assume toValue for nested ref:
```ts
const x = { a: ref(1) }

toValue(x) // { a: ref(1) }

toValueDeep(x) // { a: 1 }
``` 

Other examples are:
```ts
const x = ref({ a: ref(1), b: { c: ref(2) } })
const y = ref([{ a: ref(1) }, { a: ref(2) }])
const x = [{ a: ref(1) }, { a: ref(2) }]
```

### Suggested solution

N/A

### Alternative

N/A

### Additional context

I was working on this composable but typescript is hard when it comes to recursion & looping 😅 

Here's my rough implementation if someone want to work further:
```ts
const toValueDeep = <T>(value: MaybeRefOrGetter<T>): T => {
  const _val = toValue(value)

  if (isRef(_val))
    return toValueDeep(_val)
  else if (Array.isArray(_val))
    return _val.map(toValueDeep)
  else if (typeof _val === 'object' && _val !== null)
    return Object.fromEntries(
      Object.entries(_val)
        .map(
          ([k, v]) => [k, toValueDeep(v)],
        ),
    )

  return _val
}
```

<details>
<summary>Once we have this I'll try to give new PR for new composable `useUrl`</summary>

```ts
const postId = ref(1)
useUrl('https://jsonplaceholder.typicode.com/posts/{postId}/comments', {
  query: { q: 'ticket' },
  params: { postId },
})
// returns => https://jsonplaceholder.typicode.com/posts/1/comments?q=ticket
```

This will be super useful for useFetch as current useFetch isn't provide way to pass `query` via object and we have to create additional computed property for this.

</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sounds good :)

I would like to see of the performance difference between your approach and `toRaw(reactive(obj))` if you want to experiment a bit.

Feel free to PR

**Comment by jd-solanki** [comment]
I don't have expertice in calculating the performance matrix but if you think `toRaw(reactive(obj))` is workaround and efficient enough then we can close this issue.

> _P.S. Thanks for the new trick: `toRaw(reactive(obj))`_ 😉

**Comment by antfu** [comment]
Oh I see now your approach of `toValueDeep` might be tricky as it will evaluate all nested functions as `toValue` will consider them as getters. I think it's better to avoid that and use `toValue` when you explicitly expect a getter function. Let's close this for now.

**Comment by jd-solanki** [comment]
Hey @antfu,

While working on #3191 I found that `toRaw(reactive(obj))` doesn't really give the correct value: [example](https://play.vuejs.org/#eNp9kU9rwzAMxb+K8aUplITRW+k29qeH7rCNbuxkBiZRM3eObWylLZR898nOku4w6pMlPT1+D534nXP5vgW+4MtQeuWQBcDW3QijGmc9shPzsJ0xtB9StzCjSpao9vRDu5EH1rGttw2bkMlEGGFKawKySqJk1+wkDKPnbMB1tYhO2dVUmO4s9PLw2GuTXTbYZ9FhStqiiA6ft8OK1ZBrW2e/i6RYFj05MVOB0DgtEahaFmPBZxwDrW9Vne+CNZQ3sQle2sYpDf7FoSJ7wRcDteBSa3t4Sj30FH7ol19Qfv/T34Vj7An+6iGA34Pg4wylrwH78ertGY70H4eNrVpN6gvDDVD0NjL2svvWVIT9R5do1+lqytTvYXVEMGEIFUGjskt6weleDxein3Hn+Tzt0dl49wP40bs8).

Notice, postId is still ref and not a raw value. The purpose of toValueDeep is to get the raw value for all the nested reactive/ref as well.

Can we reopen this?

> _P.S. I need this composable to work further on useFetch's query param._

**Comment by jd-solanki** [comment]
@Alfred-Skyblue Can you help me with the types for mentioned composable so that I can finish #3191

**Comment by Alfred-Skyblue** [comment]
> @Alfred-Skyblue Can you help me with the types for mentioned composable so that I can finish #3191

Do you hope that I can help you complete the return value type of TypeScript toValueDeep?

**Comment by jd-solanki** [comment]
> Do you hope that I can help you complete the return value type of TypeScript toValueDeep?

Yes, I'll write the tests & demo page with new PR. Do you want me to make a PR first?

**Comment by Alfred-Skyblue** [comment]
@jd-solanki 

```ts

type ToValueDeep<T> = T extends Ref<infer V>
  ? ToValueDeep<V>
  : T extends Array<infer U>
  ? Array<ToValueDeep<U>>
  : T extends object
  ? {
      [K in keyof T]: ToValueDeep<T[K]>
    }
  : T

const toValueDeep = <T>(value: MaybeRefOrGetter<T>): ToValueDeep<T> => {
  const _val = toValue(value)

  if (isRef(_val)) return toValueDeep<T>(_val)
  else if (Array.isArray(_val))
    return _val.map(v => toValueDeep(v)) as ToValueDeep<T>
  else if (typeof _val === 'object' && _val !== null)
    return Object.fromEntries(
      Object.entries(_val).map(([k, v]) => [k, toValueDeep(v)])
    ) as ToValueDeep<T>

  return _val as ToValueDeep<T>
}

```

**Comment by jd-solanki** [comment]
Thanks, I'll open the new PR ASAP.
