### ISSUE TITLE
Using "useDark|VueUse" to control "Dark Mode" toggles will cause animation exceptions，In the `el-switch`,

### ISSUE THREAD

**Issue by Cxk-1233** [vueuse/vueuse#3194]
### Describe the bug

Not only `el-switch`, if you use switch to control "Dark Mode", and use 'v-mode' to implement data binding, it will cause animation exceptions；

This issue will not appear in version `9.1.0`;

The animation exception I'm referring to is the animation that slides from left to right when the 'el-switch' state changes, don't get me wrong, I submitted lssues once before, but the issue didn't work out and I had to lower the version to `9.1.0`

### Reproduction

https://github.com/Cxk-1233/use-dark-debug.git

### System Info

```Shell
No abnormal information
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Duplicated of #3063

`useDark` now disable transition global on switching in v10, You can disable it via `disableTransition: false`
