### ISSUE TITLE
使用【useDark, useToggle】控制element-plus Switch组件切换会导致动画异常

### ISSUE THREAD

**Issue by imleeou** [vueuse/vueuse#3200]
### Describe the bug

```

<script setup lang="ts">
import { useDark, useToggle } from '@vueuse/core'

const isDark = useDark()
const toggleDark = useToggle(isDark)
</script>

<template>
  <el-switch v-model="isDark" inline-prompt  @change="toggleDark"></el-switch>
</template>

```
在使用` "@vueuse/core": "^10.2.1",`时，Switch组件过渡效果异常。
切换版本至` "@vueuse/core": "^9.13.0",`可避免此问题。

### Reproduction

https://vueuse.org/core/useDark/

### System Info

```Shell
Vue Version: 3.2.37
Element Plus Version: 2.3.7
VueUse: 10.2.1
Browser / OS: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Build Tool: Vite
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
发 Issue 之前花点时间搜索一下

https://github.com/vueuse/vueuse/issues/3194#issuecomment-1612664571
