### ISSUE TITLE
useLongPress doesn't prevent mouse click

### ISSUE THREAD

**Issue by Andy-d-g** [vueuse/vueuse#3203]
### Describe the bug

Hello, 

Using UseLongPress with the mouse doesn't prevent the click event.
It works fine with the mobile press.

If I make a long press with my trackpad, both counter will be increase same if I add the `prevent` attribute which should avoid to increase the counter of the "basicCounter"

Thank you

### Reproduction

https://codesandbox.io/s/peaceful-rain-pqk7qt?file=/src/App.vue:72-92

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 33.29 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.5.1
    Firefox: 114.0.2 (64 bits)
  npmPackages:
    @vueuse/components: ^10.2.1
    @vueuse/core": ^9.2.0
    vue: ^3.3.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JiuRanYa** [comment]
PreventDefault means stop dom's default action, not dom's another event. More details [here](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault).

**Comment by Jannchie** [comment]
Right now it seems difficult to implement a long press trigger to block the @click event. But I think it's a necessary feature.

A workaround would be to create a new flag to determine if a long press is in progress, like this:

```
const counter = ref(0);
const basicCounter = ref(0);
const flag = ref(false);

const onLongPress = (e) => {
  flag.value = true;
  counter.value++;
};
const onPress = (e) => {
  if (flag.value) {
    flag.value = false;
    return;
  }
  basicCounter.value++;
};
```

**Comment by aquarius-wing** [comment]
Consider using "mousedown" instead of "click". The prevent property will function effectively with "mousedown".

**Comment by ephilippo** [comment]
I agree, this would be welcome.  Switching to `mousedown` is a quick workaround, but it isn't the behavior I want.
