### ISSUE TITLE
Reading in useClipboard could be optional

### ISSUE THREAD

**Issue by mzgajner** [vueuse/vueuse#321]
We're using `useClipboard` for a very simple use-case: a snippet of code and a button to copy it.
![snippet](https://user-images.githubusercontent.com/1853648/106921206-15539600-670c-11eb-92ab-e84f1b04da13.png)
In other words - we don't need the functionality of reading from the clipboard, we just write to it.

The issue is that even though we just do `const { copy } = useClipboard()`, this attaches event listeners for copy/cut events internally. As a consequence, if a user ignores the provided copy button and instead tries to mark and copy the text manually, they get a permission popup from their browser, which seems slightly suspicious in this situation.

I think it would be reasonable to prevent this behaviour by making reading explicitly opt-in, perhaps by having separate `useClipboardRead` and `useClipboardWrite` or by passing something like `useClipboard({ read: true })`.

Would love to open a PR if you feel like this is a valid use case, let me know what you think the most sensible API would be.

**Comment by antfu** [comment]
Sure, sounds reasonable. Let's see the PR, thanks!
