### ISSUE TITLE
error integrations:

### ISSUE THREAD

**Issue by EmmanuelMartinez** [vueuse/vueuse#3211]
### Clear and concise description of the problem

I already installed the package and when loading the component I get this error integrations:1 Uncaught Error: 
 integrations:1 Uncaught Error: Could not resolve "focus-trap" imported by "@vueuse/integrations". Is it installed?

`
import { UseFocusTrap } from '@vueuse/integrations/useFocusTrap/component'`

### Suggested solution

any suggestions?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Ericlm** [comment]
> I'm having the same problem, however it is with the [Sortable](https://github.com/SortableJS/Sortable) integration. As soon as I'm using it, the following error shows up : `Could not resolve "async-validator" imported by "@vueuse/integrations". Is it installed?`.
> 

I solved it by replacing the import from `import { useSortable } from '@vueuse/integrations'` to `import { useSortable } from '@vueuse/integrations/useSortable'`. This is also what is recommended [in the integrations doc](https://vueuse.org/integrations/README.html#tree-shaking).

**Comment by EmmanuelMartinez** [comment]
I solved it by installing focus-trap separately
`npm i focus-trap`
