### ISSUE TITLE
Integrations/sortable : wrong number of items after `moveArrayElement` call

### ISSUE THREAD

**Issue by Ericlm** [vueuse/vueuse#3216]
### Describe the bug

I'm trying to use the sortable integration with `useSortable` inside a component. The reordering of HTML elements works well, however, the call to `moveArrayElement` seems buggy:
<img width="201" alt="Capture d’écran 2023-07-06 à 22 48 26" src="https://github.com/vueuse/vueuse/assets/19361503/70674f3f-d7d4-4912-a468-85a0ffd855b2">
As you can see, there is a log before the call and there is 3 items in the array; however, after the call, only two items are appearing ; the dragged item seems to disappear.

### Reproduction

https://codesandbox.io/p/sandbox/confident-mendel-6vjzsd?file=%2FREADME.md

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 466.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - ~/.asdf/installs/nodejs/20.4.0/bin/node
    npm: 9.7.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
    Safari Technology Preview: 17.0
  npmPackages:
    @vueuse/components: ^10.2.1 => 10.2.1 
    @vueuse/core: ^10.2.1 => 10.2.1 
    @vueuse/integrations: ^10.2.1 => 10.2.1 
    vue: ^3.3.4 => 3.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azamat-sharapov** [comment]
You need nextTick(), see https://github.com/vueuse/vueuse/blob/main/packages/integrations/useSortable/index.md#tips

**Comment by AlejandroAkbal** [comment]
> This is still happening!
> 
> [codesandbox.io/p/sandbox/test-vueuse-sortable-forked-k783fk?file=%2Fsrc%2FApp.vue%3A38%2C19](https://codesandbox.io/p/sandbox/test-vueuse-sortable-forked-k783fk?file=%2Fsrc%2FApp.vue%3A38%2C19)

@Ericlm

**Comment by Ericlm** [comment]
Yeah is seems that it keeps logging only two items in the array now... Pretty strange 🤔 Anyway, I preferred to implement the reordering myself to avoid any problem with asynchronous code. This is in the doc with : `// nextTick required here as moveArrayElement is executed in a microtas` but I don't really understand why. Anyway, seems easier to reorder with `oldIndex` and `newIndex` instead of calling `moveArrayElements`.

I'll reopen the issue as there could be an easier way to handle this (making it synchronous maybe) 🙂

**Comment by idesignzone** [comment]
I am facing this problem in Nuxt.
without nextTick, sortable works fine but with nextTick, result array is missing an item after drag.

```
useSortable(el, list, {
  onUpdate: (e) => {
    moveArrayElement(list.value, e.oldIndex, e.newIndex);
    nextTick(() => {
      console.log(list.value.map((i) => i.id));
    });
  },
});
```

```
"@vueuse/core": "^10.7.2",
"@vueuse/nuxt": "^10.7.2",
```
