### ISSUE TITLE
Cannot use useInfiniteScroll version v9-13 or higher in Chrome 69.

### ISSUE THREAD

**Issue by Nuctori** [vueuse/vueuse#3225]
### Describe the bug

t is very easy to reproduce the error when accessing the official useInfiniteScroll example page using Chrome 69 browser, and the page cannot be accessed. However, version v8.9.4 is not affected

[https://vueuse.org/core/useInfiniteScroll/#useinfinitescroll](url)
![image](https://github.com/vueuse/vueuse/assets/23477613/173acbb4-1883-47d4-a45c-6ff424e27667)

### Reproduction

https://vueuse.org/core/useinfinitescroll/#useinfinitescroll

### System Info

```Shell
win10, chrome69
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kaine0923** [comment]
I think you can try to set the output of your bundling process to **es5**，vueuse  are `target: es2017`
