### ISSUE TITLE
useDark blocking the ability to transition an element

### ISSUE THREAD

**Issue by devloos** [vueuse/vueuse#3233]
### Describe the bug

StackOverflow question: [here](https://stackoverflow.com/questions/76645956/vueuse-usedark-function-blocking-the-ability-to-transition-an-element)

Hey I have been troubleshooting this for a while but can't seem to figure it out. To give some context I am creating a dark mode for my site and I am using useDark from the vueuse library which is referenced here: [useDark](https://vueuse.org/core/useDark/#usedark)

essentially it checks localStorage then user preferences to find whether they prefer light or dark mode. it then provides a boolean ref that we can use to do whatever. also it applies the class dark to the html documentElement <html class="dark">.

so whats the problem, well i am using tailwindcss to create a toggle button that allows the user to switch between light and dark.

here is a stackblitz example: [using ref not useDark](https://stackblitz.com/edit/vitejs-vite-zpbeof?file=src%2FApp.vue)

code reference:
```vue
<script setup>
import { useDark, useToggle } from '@vueuse/core';
import { ref } from 'vue';

const isDark = ref(true);
// const isDark = useDark();
const toggleDark = useToggle(isDark);
</script>

<template>
  <button
    class="h-8 w-16 pl-1 rounded-full bg-slate-300"
    type="button"
    @click="toggleDark()"
  >
    <div
      class="h-7 w-7 rounded-full bg-slate-400 transition-all"
      :class="{ 'translate-x-7': isDark }"
    />
  </button>
</template>
```

this essentially does nothing when using a ref and that is intentional to show that the transition of that toggle works fine

the problem i am having is if you comment out the ref and use useDark ref instead there is no smooth transition. I have troubleshooted so much to get to this point and I am absolutely lost as to why.

one thing you can do to force it to work is adding!transition-all to the inner div giving it importance but I dont know if this is the correct fix or if i just worked around it. What I am looking for is why this is happening

I have tried adding the dark class to the documentElement but using only a ref and it seemed to work as well but then I would not be using useDark and also would need to manage my own localStorage and use preferences lookup.

also i have done it using raw css and i get the same incorrect behavior

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zpbeof?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 40.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    npm: 9.6.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @vueuse/core: ^10.2.1 => 10.2.1
    @vueuse/head: ^1.1.26 => 1.1.26
    vue: ^3.3.4 => 3.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JehhB** [comment]
I believe this behavior is expected since the `useDark` feature disables transitions on the switch by default. To resolve the issue, you can pass `{ disableTransition: false }` as an option to `useDark`. However, if you wish to keep transitions disabled but still animate the button, you can modify the indicator's class from `transition-all` to `!transition-all`. This change will give priority to the animation over the disabled transition style.

**Comment by devloos** [comment]
It is interesting that this would be the default. I am also curious as to how they are able to do this, do they add some sort of class selector to the element that we might be using the ref with? It seems confusing and weird that this would be the normal behavior am I wrong?

If this is the only way to fix it maybe it should be documented a bit more: https://vueuse.org/core/useDark/#usedark

**Comment by JehhB** [comment]
It is indeed not clear in the documentation and it is quite hidden in the type declarations for 'useColorMode' that this behaviour is the default. For why this is the default and how it works, this [https://paco.me/writing/disable-theme-transitions](article) is linked in the documentation of the property. So i think the better option is to just give a higher importance to the `transition-all` property of the switch.

**Comment by devloos** [comment]
Will do @JehhB thanks for the help and the insight!

**Comment by vikramsoni2** [comment]
why not add the CSS to disable transitions, switch the style from light/dark and remove the  CSS after its done ?

**Comment by MeshackNzuki** [comment]
> I believe this behavior is expected since `useDark` disables transitions on the switch by default. To resolve the issue, you can pass `{ disableTransition: false }` as an option to `useDark`. However, if you wish to keep transitions disabled but still animate the button, you can modify the indicator's class from `transition-all` to `!transition-all`. This change will give priority to the animation over the disabled transition style
yes this works. Thanks

import { useDark, useToggle } from "@vueuse/core";
const isDark = useDark({ disableTransition: false });
const toggleDark = useToggle(isDark);

**Comment by Tchilly** [comment]
Why the heck isn't this clearly stated in the docs.. this wasted a good 1-2 hours ...

**Comment by vikramsoni2** [comment]
> Why the heck isn't this clearly stated in the docs.. this wasted a good 1-2 hours ...

Its always good to read the source code of the composables, they are very small and clean. And gives you much better understanding about how this work

**Comment by Tchilly** [comment]
> > Why the heck isn't this clearly stated in the docs.. this wasted a good 1-2 hours ...
> 
> Its always good to read the source code of the composables, they are very small and clean. And gives you much better understanding about how this work

Going forward I’ll remember this, but having defaults that are blocking should be documented to. I assumed my css was wrong, and spent quite some time debugging for something I wouldn’t even start looking at if it wasn’t for a quick google search 😅

**Comment by vikramsoni2** [comment]
> > > Why the heck isn't this clearly stated in the docs.. this wasted a good 1-2 hours ...
> > 
> > 
> > Its always good to read the source code of the composables, they are very small and clean. And gives you much better understanding about how this work
> 
> Going forward I’ll remember this, but having defaults that are blocking should be documented to. I assumed my css was wrong, and spent quite some time debugging for something I wouldn’t even start looking at if it wasn’t for a quick google search 😅

This is the only place where the transition override is needed. In normal scenarios, you dont want all your elements and components to run their transitions when you switch the theme. Imagine everything on your screen is changing color with different duration…

**Comment by Tchilly** [comment]
I agree, it’s a nice feature. But still, a few lines of documentation.. Like you said; it’s the only place it’s being used 👌🏼
