### ISSUE TITLE
useZoomable & useDraggable enhancement

### ISSUE THREAD

**Issue by Jannchie** [vueuse/vueuse#3238]
### Clear and concise description of the problem

We already have `useDraggable`, which works wonderfully. However, there's no support in the library for zooming and viewport dragging (`useZoomable`). If we could add this, it would be a breeze to implement a zoom & drag interaction logic similar to draw.io or Figma.

We could utilize the CSS transform property to make the zoomable functionality. However, the current `useDraggable` doesn't account for transforms — when a parent component has custom transforms, dragging fails to properly position the mouse location and movement distance.

I therefore sincerely suggest that:

1. Add a `useZoomable` function, providing interaction logic similar to Figma.
2. Enhance the `useDraggable` function to allow it to adapt to parent element transforms.

### Suggested solution

In fact, I've spent the evening implementing a Demo: https://[vzad.vercel.app](https://vzad.vercel.app/)/. Here's the source code: https://github.com/Jannchie/vzad. It provides figma-like interaction logic. I also modified `useDraggable` to make it transform-compatible.

My suggestion 1 may not move forward due to the new functions involved. But suggestion 2 involves only enhancements to existing functions and may be worth doing.

My current idea is to get the transform style from the parent component by default, or you can pass in a ref of an element as the transform style source. The downside is that it can't accommodate multiple transform transforms. In most cases, this should be enough.

---

I understand that the team has limited energy not to accept new functions. So here are only suggestions. I am more than willing to contribute code if it is ever opened to add new functions!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by 3aluw** [comment]
Hey there, thanks for delving into this matter! I encountered a similar problem with "usedraggable" and raised an [issue](https://github.com/vueuse/vueuse/issues/3199). Additionally, I faced the same issue when utilizing CSS tags like "transform/zoom."

Nonetheless, it's possible that my problem might be resolved by this [pull request](https://github.com/vueuse/vueuse/pull/3219). I'm unsure whether the "transform" issue will be solved by it.
