### ISSUE TITLE
New function proposal: useSwipe

### ISSUE THREAD

**Issue by lstoeferle** [vueuse/vueuse#324]
Hello @antfu,

I'm back with another function proposal 😄. Few weeks ago I worked on a composable which handles swipe detection based on the `touchStart`, `touchMove` and `touchEnd` event.

```javascript
export enum SwipeDirection {
  UP = "UP",
  DOWN = "DOWN",
  RIGHT = "RIGHT",
  LEFT = "LEFT",
}

export function useSwipe(
  el: MaybeRef<HTMLElement | null>,
  threshold: number,
  onSwipeEnd: (direction: SwipeDirection, range: number) => void,
  onSwipe?: (e: TouchEvent, rangeX: number, rangeY: number) => void
)
```

I can open a PR if you think this will add value to your library 😄

**Comment by antfu** [comment]
Sounds great! Let's see the PR. One thing tho is I think we can have the last three arguments as an options object.
