### ISSUE TITLE
Allow configuration to parse the response by default in `useFetch`

### ISSUE THREAD

**Issue by DeepKumbhare85** [vueuse/vueuse#3242]
### Clear and concise description of the problem

Hi 👋 

I'm building application where I need to make an API call. For this I'm using `useFetch` but everytime I have to prepend `.json` to each `useFetch`. Can I some how specify it in `createFetch`?	

### Suggested solution

Provide config in `createFetch` to parse the response as JSON.

### Alternative

N/A

### Additional context

While checking the source code, I found that [this](https://github.com/vueuse/vueuse/blob/main/packages/core/useFetch/index.ts#L318-L323) code isn't used anywhere 🤔 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Eternal-Rise** [comment]
I think, it may be possible with simple wrapper, like

```
const _useFetch = createFetch(config)
export const useFetch = (...args) => useFetch(...args).json()
```

And than, if your request requires another type of response, you can just override it with another method call.

```
const image = useFetch(url).blob()
```

**Comment by DeepKumbhare85** [comment]
Hello @Eternal-Rise ,

Thanks for the solution.But when implementing in my project, it hangs my project. although works fine in new fresh project.
