### ISSUE TITLE
`useMediaControls` breaks video autoplay feature

### ISSUE THREAD

**Issue by quentint** [vueuse/vueuse#3263]
### Describe the bug

When using `useMediaControls` on a video element with the `autoplay` attribute, it breaks its feature.

You'll find in the reproduction a video with `useMediaControls`, and one without. You'll notice only the second one autoplays: https://jrlztc-3000.csb.app/ (make sure to run this link to try it out, as it does not behave the same when in the editor's preview pane, because of the peculiar [autoplay policy](https://developer.chrome.com/blog/autoplay/)).

I believe it has to do with overriding the sources, but I can't explain why.

### Reproduction

https://codesandbox.io/p/sandbox/sweet-dream-jrlztc

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 809.49 MB / 2.01 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    pnpm: 7.1.0 - /usr/local/bin/pnpm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @vueuse/core: ^10.2.1 => 10.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by francoism90** [comment]
@quentint Could you try this:
```js
onMounted(() => {
  playing.value = true
})
```
It looks like `useMediaControls` is intercepting the playing event.

**Comment by quentint** [comment]
That doesn't work, because you can't play a video with a script if the user has not interacted with the page yet :/

**Comment by wvffle** [comment]
Works fine on Firefox, does not work on Chromium

**Comment by francoism90** [comment]
@quentint This is normal behavior, you should interact with the page first, unless the user accepts autoplay policy.

I don't know why autoplay does not work, are you sure it's muted?

**Comment by quentint** [comment]
To me nothing works on Firefox (behavior is the same across all browsers).

> I don't know why autoplay does not work, are you sure it's muted?

I am 😉 Did you check my reproduction?

> Maybe you need to use the play() method instead.

That's going to be the same issue: you can't `play()` a video if the user has not interacted with the page. Also, having to do that would confirm the `autoplay` feature is broken by `useMediaControls`.

**Comment by slavanossar** [comment]
I was just experiencing this issue, it looks like `useMediaControls` doesn't check the initial `muted` attribute when setting the default value of the corresponding `shallowRef`

![Image](https://github.com/user-attachments/assets/24ba6312-c3be-44b1-b219-d7323a99ac8f)

Chrome is the only browser that doesn't like this, also tested on Brave, Firefox and Safari.

Seems like 5d19a2d introduced this regression.
