### ISSUE TITLE
Function Proposal: useFetch

### ISSUE THREAD

**Issue by jacobclevenger** [vueuse/vueuse#327]
I'm proposing a new function called `useFetch`. I think maybe the API could be similar to `useAxios` but for `fetch` since people may not want to add Axios to their project.

I'm thinking something like this

```ts
const { finished, response, error, data } = useFetch('http://example.com', { options })
```

I imagine it will return something like this
```ts
export interface FetchOptions {
  // Indicates if the fetch request has completed
  finished: boolean

  // The raw response from request
  response: Response | null

  // The error if there was one during the request
  error: any

  // Either the JSON or Text response of the request
  data: object | string
}
```

I've started implementing this in a personal project but thought it might fit well here.

Some of the features I'd like to include are the following:

- **Using an Object for headers**
  This would only make a slight adjustment to the current fetch options. Basically it would allow the user to pass in the normal options for headers as well as an object that would automatically be converted to a Headers object. Although perhaps you'd like us to avoid changing the default options, let me know what you think is best if you like this proposal.

```ts
export interface FetchConfig extends Omit<RequestInit, 'headers'> {
  headers: HeadersInit | ObjectHeaders
}
```

- **Returning either json or text in the data object**
  Typically when using fetch you will have to do something like `fetch().then(response => response.json()).then(json => ...)` but this function would read the `content-type` headers and automatically assign the `data` ref to what the response is, either text or json

Anyway let me know what you think of this feature. If you like it I'd be happy to make a PR. Thanks 😄

**Comment by antfu** [comment]
Sounds cool, please go ahead. Would love to have a ref showing the status of the request and abort it as well. Thanks

https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

**Comment by dheimoz** [comment]
Hey guys. Thanks for the great work. I wonder if you have seen https://github.com/sindresorhus/ky

A wrapper or a plugin would be excellent and will save a few hours of your precious time.

**Comment by jacobclevenger** [comment]
@antfu Sounds good, I'll add the status ref and look into the Abort controllers
