### ISSUE TITLE
perf: IntersectionObserver to reuse observer

### ISSUE THREAD

**Issue by privatenumber** [vueuse/vueuse#3271]
### Describe the bug

1. It _looks_ like a new observer is created on every watch change. So if an array of elements are passed in and changed, a new observer will be created and the previous one won't be cleaned up?

https://github.com/vueuse/vueuse/blob/ac88fd760fb0a191004cbd96aa67e60c8680b9f9/packages/core/useIntersectionObserver/index.ts#L81

2. A new observer is created per component instance and is not shared across multiple instances. This blog post demonstrates the performance costs of having many observers: https://www.bennadel.com/blog/3954-intersectionobserver-api-performance-many-vs-shared-in-angular-11-0-5.htm

	There should be a Weak Map or something where the key if the component object and type is the observer so we can make one observer for each component. Not sure how to go about doing this yet.

### Reproduction

N/A (not a bug)

### System Info

```Shell
N/A (not a bug)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by n0099** [comment]
https://stackoverflow.com/questions/55867849/one-intersectionobserver-to-observe-many-elements-or-one-intersectionobserver-pe
https://www.bennadel.com/blog/3954-intersectionobserver-api-performance-many-vs-shared-in-angular-11-0-5.htm
https://github.com/snewcomer/intersection-observer-admin
https://www.measurethat.net/Benchmarks/Show/27735/1/one-intersectionobserver-per-one-element-vs-one-interac
https://github.com/snewcomer/intersection-observer-admin
https://github.com/thebuilder/react-intersection-observer
