### ISSUE TITLE
`createGlobalState` don't call again when component update.

### ISSUE THREAD

**Issue by jackchoumine** [vueuse/vueuse#3275]
## `createGlobalState` don't call again when component update.

hooks.js

```js
import { createGlobalState } from '@vueuse/core'
import { ref } from 'vue'

export function useTestHook() {
  console.log('call useTestHook')
  const name = ref('jack chou') // u can call http api
  return {
    name,
  }
}
export const useGlobalState = createGlobalState(() => {
  console.log('call createGlobalState')
  const { name } = useTestHook() // get data from other hook, example: useTestHook
  return { name }
})
```
use useGlobalState in `Child.vue` component:

```html
<script setup>
import { useGlobalState,useTestHook } from './hooks'
const {name}=useGlobalState()
const {name:name1}=useTestHook()
</script>

<template>
  <h1>name from  useGlobalState {{ name }}</h1>
   <h1>name from useTestHook  {{ name1 }}</h1>
</template>
```
in App.vue
```html
<script setup>
import { ref } from 'vue'
import Child from './Child.vue';
let updateKey = ref('123')
setTimeout(()=>{
  updateKey.value = 'abc'
},2000)
</script>

<template>
  <Child :key="updateKey"/>
</template>
```
> when Child.vue update, useGlobalState dont call again， why ?  It is a featrue or bug? 

> In general, hooks should call when setup ready in component， but this action is so different from a common case. 

### Reproduction

[Vue SFC Playground](https://play.vuejs.org/#eNp9VE2P2jAQ/StWLgGVxrDcKKBtV6t+SW3V5ZhL1hlIwLEj26GsUP57x3YSEii9BMbz3vi9mZHPwceyjI4VBItgqZnKS0M0mKpcxyIvSqkMORMFW1KTrZIFCREadqmnLOdpk4ioi2yt8EMsOBhSlWli4Du8kZWtMQpnD/NwHAu8YJMXICszGo1X63MsOmR0THgFiA+TV4YX1ZOH6XSKnCX16lAXBgaKkiMDI0KWXsbiAG+rOOhKxQHF9JJ22GASeN3vi6SM9loKNI2XExI3CR0HC+JO7NkjWqk0UCYV2EQcZMaUekEpSwXyU+D5UUUCDBVlQfvwx9k0mkdT+g50EQe2YI1eUIDRTIptvru6nsmizDmon6XJpRjKSDiXf765M6MqmLTnLAN2+Mf5Xp+82l8KNKgjau9yJlE7MD79/PIDTvi/SxYyrXjj9E7yN2jJK6vRwz5VIkXZPZxT+9V1Mxe7jX4+GRC6NWWFum44fBxgy57+Y/0idx7Ne13sNu12a1Vvb3Ean7l8TfiLwflPMNyANl+kPHTrHNEMQx1aHk5GI00kBdSrIXc0vgIs7GfmYG1Nj7nsKQbu4LKrGOG2ZrO1JXsBVxrJ+Uxcsq6XFIGecsXp+2gJsz5juPPOIO4b9qrrDFOA2f7FbUP6W+y6cv8VaAzCyQG2lWB2gn15ozHO0lmwrZMcIi53o5DhkvRh+CZ0IOP9Nw/GPmEHwjJZtRCFU1airUoceOKD2v64T6PIl7tq8OrWOz5CZLW+r/SGMNTbTgxLD61TSnB7CT5HiW+bNBkoYucxIXBKcESw6HOGFpuyztU4qP8CxevyeQ==)

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 1.67 GB / 15.79 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.16.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 78.0.3904.108
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by businiaoyo** [comment]
It is a feature.
useGlobalState called but the callback was not.
see the source code.
```
export function createGlobalState<Fn extends AnyFn>(
  stateFactory: Fn,
): Fn {
  let initialized = false
  let state: any
  const scope = effectScope(true)

  return ((...args: any[]) => {
    if (!initialized) {
      state = scope.run(() => stateFactory(...args))!
      initialized = true
    }
    return state
  }) as Fn
}
```

**Comment by jackchoumine** [comment]
> It is a feature. useGlobalState called but the callback was not. see the source code.
> 
> ```
> export function createGlobalState<Fn extends AnyFn>(
>   stateFactory: Fn,
> ): Fn {
>   let initialized = false
>   let state: any
>   const scope = effectScope(true)
> 
>   return ((...args: any[]) => {
>     if (!initialized) {
>       state = scope.run(() => stateFactory(...args))!
>       initialized = true
>     }
>     return state
>   }) as Fn
> }
> ```

how to pass agrs? I can not find this using method in docs.

**Comment by jd-solanki** [comment]
@jackchoumine https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/composables/useAnu.ts#L16-L18

`createGlobalState` is called once initially and later the callback function gets executed as a composable.
