### ISSUE TITLE
usePushNotifications

### ISSUE THREAD

**Issue by Fanna1119** [vueuse/vueuse#328]
As title says. A utility for push notifications.

Things we can look at to make this possible either with or without a wrapper.

#### Documentation
https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Best_Practices
https://developer.mozilla.org/en-US/docs/Web/API/Push_API

#### possible wrapper(s)
https://pushjs.org/

Issues:
Push Notifications not supported by safari browsers(mobile and desktop)

**Comment by antfu** [comment]
Not very familiar with this. How about drafting a PR so we can have a closer look? Thanks.

**Comment by wheatjs** [comment]
In the interest of closing up older issues I say I can either write a wrapper for `pushjs` and we can have it under integrations or maybe we close this issue if not. Looking at the API for `pushjs` though I'm not sure how much it will benefit from a wrapper since it is already pretty clean.

**Comment by lovetingyuan** [comment]
any progress ?

**Comment by curtgrimes** [comment]
Is this issue still relevant or could it be closed now that we have https://vueuse.org/core/useWebNotification/?

**Comment by wheatjs** [comment]
Seems like it

**Comment by epeleg** [comment]
It is my understanding that pushNotifications and webNotifications though they sound like similar things are actually two very different things . while webNotifications serve as a glorified Alert message PushNotifications are the mechanism that allows a server to send a notification to any of the clients that have subscribed to this service (even if the client is not active at the moment)..
