### ISSUE TITLE
Vue warning when using `useBreakpoints`

### ISSUE THREAD

**Issue by lukereative** [vueuse/vueuse#3283]
### Describe the bug

A warning is produced when using `useBreakpoints`:

```
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-heui5u

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/core: ^10.3.0 => 10.3.0 
    vue: ^3.3.4 => 3.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You should use:

```vue
<script setup>
import { useBreakpoints } from '@vueuse/core';
const breakpoints = useBreakpoints({ lg: 1024 });
console.log(breakpoints);
const lg = breakpoints.greaterOrEqual('lg')
</script>

<template>
  <h1>Hello VueUse!</h1>
  <a
    href="https://vueuse.org/"
    target="_blank"
    v-if="lg"
    >Documentation</a
  >
</template>

<style></style>
```

Avoid creating ref in render function

**Comment by mreduar** [comment]
> You should use:
> 
> ```
> <script setup>
> import { useBreakpoints } from '@vueuse/core';
> const breakpoints = useBreakpoints({ lg: 1024 });
> console.log(breakpoints);
> const lg = breakpoints.greaterOrEqual('lg')
> </script>
> 
> <template>
>   <h1>Hello VueUse!</h1>
>   <a
>     href="https://vueuse.org/"
>     target="_blank"
>     v-if="lg"
>     >Documentation</a
>   >
> </template>
> 
> <style></style>
> ```
> 
> Avoid creating ref in render function

Hello @antfu! What about if I need to do it in the script and not in the template?
Check [this example](https://stackblitz.com/edit/vitejs-vite-uzshgv/?file=src%2FApp.vue,src%2Fmain.js)
In this example I use it inside a computed property and receive the warning
