### ISSUE TITLE
useDark不更新问题

### ISSUE THREAD

**Issue by eric755** [vueuse/vueuse#3285]
### Describe the bug

引入useDark, useToggle；const isDark = useDark()；const toggleDark = useToggle(isDark);
通过监听isDark的变化，来进行页面的主题切换；
出现问题：当页面当前的主题色，与widow系统即将切换的主题色和页面相同，监听不到isDark的变化；尽管多次切换也是如此
如果与widow系统即将切换的主题色和页面不相同，则能监听到

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rfeawt/?file=src%2FApp.vue

### System Info

```Shell
系统：Windows 10 家庭中文版 64
浏览器：Chrome 版本 115.0.5790.110
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's expected. https://vueuse.org/core/useDark/#behavior

Or you can use https://vueuse.org/core/usePreferredDark/
