### ISSUE TITLE
CDN doesn't seem to work

### ISSUE THREAD

**Issue by tom-adsfund** [vueuse/vueuse#329]
I have the error: "n is undefined".

**Comment by tom-adsfund** [comment]
That's in Firefox.

In Chromium, I get "Cannot read property 'isClient' of undefined".

And that's with the following in the head tag:

```
  <script src="https://unpkg.com/vue@next"></script>
  <script src="https://unpkg.com/@vueuse/core"></script>
```

**Comment by antfu** [comment]
How about this?

```html
  <script src="https://unpkg.com/vue@next"></script>
  <script src="https://unpkg.com/@vueuse/shared"></script>
  <script src="https://unpkg.com/@vueuse/core"></script>
```

We might need to either bundle the shared module or properly document this.

**Comment by tom-adsfund** [comment]
Unfortunately that doesn't work either.

**Comment by tom-adsfund** [comment]
I'd be so happy if this could be fixed, the power of this library is amazing!

**Comment by rogeraabbccdd** [comment]
same problem here, `window.VueUse` returns an empty object and errors.
![chrome_k3TEMCM1vp](https://user-images.githubusercontent.com/15815422/108595987-054ede00-73bd-11eb-8066-a3aad7fe2457.png)

```html
<script src="https://unpkg.com/vue@next"></script>
<script src="https://unpkg.com/@vueuse/core"></script>
<script src="https://unpkg.com/@vueuse/shared"></script>
```

**Comment by antfu** [comment]
Can you help to confirm if this works now with 4.0.0-beta.2? Thanks

```html
  <script src="https://unpkg.com/vue@next"></script>
  <script src="https://unpkg.com/@vueuse/shared"></script>
  <script src="https://unpkg.com/@vueuse/core"></script>
```

**Comment by rogeraabbccdd** [comment]
Yes, it works!
Thanks for quick fix!
