### ISSUE TITLE
useOnline always true on Firefox

### ISSUE THREAD

**Issue by deejayjay** [vueuse/vueuse#3295]
### Describe the bug

I am using v117.0b3 of Firefox Developer edition. I am trying to use useOnline in my Vue3 project, and the composable returns an online status of true even though the device is not online. The status shown is correct in other browsers, though.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-odnznq?file=src%2FApp.vue

### System Info

```Shell
Firefox Developer Edition v117.0b3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by francoism90** [comment]
It works fine here, tested on Firefox (flatpak).

Do you use any privacy tweaks?

**Comment by francoism90** [comment]
@deejayjay I used the reproduction url + VueUse doc.

If I'm not mistaken, it's not that reliable: https://developer.mozilla.org/en-US/docs/Web/API/Window/online_event

I think it's better to check if the API (or something else) can be reached.
