### ISSUE TITLE
useFetch error data NOT returned on non-network errors

### ISSUE THREAD

**Issue by mu16zi** [vueuse/vueuse#3296]
## description
when for example a 400 error occurs, the fetch fails and returned an error and the onFetchError hook calls successfully, but it our server send a data on internal errors like error message or error code i cannot get it neither from "error" property nor "data" (the data value is null and error value is just an error that thrown).

so i cant handle our server-internal errors and i get only a thrown error instead the error data that the server responsed.

## expectation
I expect to return the responsed data in non-network errors in the "error" property.

## solution 
not sure but i think this line ( /useFetch/index.js, line 453 ) should be something like this:
` data.value = responseData || null `

OR provide an option for useFetch to show the error data ( responseData on errors ) in some way.
means that if any non-network erros occured, we should provide the response data as the error data.

### Reproduction

-

### System Info

```Shell
its not depends on system or browser
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Amirhosein-hshm** [comment]
yes i have same problem too.

can you find a solution for that? 

i call useFetch and it return data.value null.

**Comment by mjnoroozi** [comment]
> 

Are amirhosein :)

they fixed the problem by adding an option on version 10.4.1
so update your package to the corresponding version and set the updateDataOnError flag as true in your useFetch options

also can see this
https://vueuse.org/core/useFetch/#:~:text=ctx%0A%20%20%7D%2C%0A%7D)-,The%20onFetchError%20option%20can%20intercept%20the%20response%20data%20and%20error%20before%20it%20is%20updated%20when%20updateDataOnError%20is%20set%20to%20true,-.

**Comment by dcrystalj** [comment]
This solved the issue for me. Looks like issue can be closed
