### ISSUE TITLE
useFetch: isFetching is false if previous request was cancelled

### ISSUE THREAD

**Issue by Eternal-Rise** [vueuse/vueuse#3300]
### Describe the bug

When we start a new request before the previous one has ended, isFetching remains false.

### Reproduction

https://codesandbox.io/s/xenodochial-ioana-wch2l5?file=/src/App.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics         
    Memory: 3.48 GB / 13.83 GB
  Binaries:
    Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vueuse/core: ^10.2.1 => 10.2.1 
    @vueuse/router: ^10.3.0 => 10.3.0 
    vue: ^3.2.4 => 3.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chaii3** [comment]
Hello! As I can see the first request will be aborted, right ?

**Comment by Eternal-Rise** [comment]
Yes, it will. And second one will be with isFetching: false

**Comment by tobyzerner** [comment]
Just ran into this. I think this is what's happening internally:

1. `execute` function is called the first time, calls `loading(true)` and fires first request
2. `execute` function is called the second time, calls `abort()` and then `loading(true)` immediately after, fires second request
3. first request aborts and its `finally` handler calls `loading(false)`

**Comment by chaii3** [comment]
> Just ran into this. I think this is what's happening internally:
> 
> 1. `execute` function is called the first time, calls `loading(true)` and fires first request
> 2. `execute` function is called the second time, calls `abort()` and then `loading(true)` immediately after, fires second request
> 3. first request aborts and its `finally` handler calls `loading(false)`

Yeah, you can call the simple flushAwaits function to clean microtasks and get the finally call before loading(true) (2). But I struggled with tests.

**Comment by tobyzerner** [comment]
This is still a bug
