### ISSUE TITLE
useDateFormat returns "" quotation marks around output

### ISSUE THREAD

**Issue by Iterator98** [vueuse/vueuse#3311]
### Describe the bug

When I use {{ useDateFormat(2023-08-12 11:29:14, 'YYYY-MM-DD HH:mm') }}, the result adds quotation marks to the output: "2023-08-12 11:24" instead of 2023-08-12 11:24.

Is there anyway to remove them?

Thanks!

### Reproduction

https://stackblitz.com/edit/vitejs-vite-uosxzd/?file=index.vue,package.json

### System Info

```Shell
VUE 3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lzl0304** [comment]
useDateFormat actually returns `computed`, but
[Ref unwrapping in templates only applies if the ref is a top-level property in the template render context.](https://vuejs.org/guide/essentials/reactivity-fundamentals.html#caveat-when-unwrapping-in-templates)

https://github.com/vuejs/core/issues/5578

Can be used like this:
```javascript
<script setup lang="ts">
import { useNow, useDateFormat } from '@vueuse/core'

const formatted = useDateFormat(useNow(), 'YYYY-MM-DD HH:mm:ss')
</script>

<template>
  <div>{{ formatted }}</div>
</template>
```

**Comment by shaokeyibb** [comment]
Same issue when using `useTimeAgo` function

**Comment by madyanmalfi** [comment]
As useDateFormat returns computed, you can simple return its value and it would be without quotes. I ended up adding method like this : 

`const formatDate = (date: Date) => useDateFormat(date, 'DD MMM YYYY').value;`
