### ISSUE TITLE
Handle cancellation and multiple executions in `useAsyncState`, and allow to manually trigger refresh in `computedAsync`

### ISSUE THREAD

**Issue by segevfiner** [vueuse/vueuse#3328]
### Clear and concise description of the problem

`useAsyncState` and `computedAsync` are rather similar but each lack some functionality it would be nice to bring them more inline in terms of functionality with each other.

Two things I noticed is that `useAsyncState` doesn't handle cancellation or calling `execute` multiple times while the promise is still not resolved, and that `computedAsync` has no way to manually execute the query.

### Suggested solution

`useAsyncState` should handle multiple concurrent calls to execute and supply cancellation like `computedAsync`, `computedAsync` should allow to manually trigger execution.

### Alternative

Be frustrated if you need both missing behaviors in one composable.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by bodograumann** [comment]
Duplicate: https://github.com/vueuse/vueuse/issues/2958

**Comment by segevfiner** [comment]
But that one is closed

**Comment by bodograumann** [comment]
Indeed. Just wanted to point out that this has been brought up before and link the issues, if anybody stumbles upon one or the other ;-)

**Comment by segevfiner** [comment]
Bump for stale bot (AKA Ignore all issues bot)

**Comment by bodograumann** [comment]
"Closed as completed" doesn't sound right.
Also seems like the stale bot is deprecated and should be replaced with the stale action :thinking:

**Comment by MuXiu1997** [comment]
A better option might be to use [`Vue Query`](https://vue-query.vercel.app/#/)
