### ISSUE TITLE
useElementSize returns 0 in onMounted

### ISSUE THREAD

**Issue by henrikhansson** [vueuse/vueuse#3332]
### Describe the bug

Hi,
`useElementSize` returns 0 in the `onMounted` hook. Using `offsetWidth` on the same element returns the correct value. This is only a problem when the element dimensions are needed in `onMounted`.

```js
<template>
  <div ref="container">
    <h1>{{ width }}</h1>
  </div>
</template>

<script setup lang="ts">
const container = ref();
const { width } = useElementSize(container);

onMounted(() => {
  console.log(`useElementSize: ${width.value}`);
  console.log(`offsetWidth: ${container.value.offsetWidth}`);
});
</script>


```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-7k6kry?file=app.vue

### System Info

```Shell
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M2
    Memory: 5.16 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: 115.0.1901.203
    Safari: 16.6
  npmPackages:
    @vueuse/core: ^10.3.0 => 10.3.0 
    @vueuse/nuxt: ^10.3.0 => 10.3.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wusiquan** [comment]
I found `watch` could get the width ref value

```js
const container = ref();
const { width } = useElementSize(container);

watch(width, (w) => {
  console.log(`useElementSize: ${w.value}`);
  console.log(`offsetWidth: ${container.value.offsetWidth}`);
});
```
