### ISSUE TITLE
Split packages

### ISSUE THREAD

**Issue by orionna319** [vueuse/vueuse#3339]
### Clear and concise description of the problem

VueUse is a great library, but I probably don't need so much functionality, I just want to import useDraggable and I don't need anything else, like import lodash.clonedeep instead of lodash. 

### Suggested solution

Like this
```
npm install 'vueuse.useDraggable'
import useDraggable from 'vueuse.useDraggable'
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks. But no we are not interested in doing that as the packages are already well tree-shakable.
