### ISSUE TITLE
useJwt of jwt-decode error when build production.

### ISSUE THREAD

**Issue by dongpdgm** [vueuse/vueuse#3343]
### Describe the bug

I'm using useJwt of @vueuse/integrations. When I build the project in production I get the following error:

`ERROR in ./node_modules/@vueuse/integrations/useJwt.mjs 3:0-36
Module not found: Error: Can't resolve 'jwt-decode' in 'D:\Library\Vue3\sample\node_modules\@vueuse\integrations'
resolve 'jwt-decode' in 'xxx\node_modules\@vueuse\integrations'
  Parsed request is a module
  using description file: xxx\node_modules\@vueuse\integrations\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in xxx\node_modules\@vueuse\integrations\node_modules
        single file module
          using description file: xxx\node_modules\@vueuse\integrations\package.json (relative path: ./node_modules/jwt-decode)`.

I checked the project's package.json again and realized that, it seems that the "jwt-decode" library is being declared wrong. It should be declared in "dependencies".

### Reproduction

https://codesandbox.io/s/zealous-hodgkin-znp579?file=/package.json

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz
    Memory: 4.39 GB / 31.75 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.10 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Hatunavu** [comment]
I've had a similar experience. At present, the temporary solution is to add the "jwt-decode" library. I think they declared an error in the dependency in the package.json.

**Comment by Zhang-Wei-666** [comment]
![image](https://github.com/vueuse/vueuse/assets/37876877/d878c5f0-8315-44ae-bedb-cc7f5afd170c)
