### ISSUE TITLE
useFetch composable should have any type instead of unknow.

### ISSUE THREAD

**Issue by alokVishu** [vueuse/vueuse#3345]
### Describe the bug

I am currently utilizing the useFetch composable function. I have observed that it requires a specific type instead of being unknown. I constantly have to add "any" whenever I use it. Does anyone know of a better solution to this issue?

```
const { data, error } = await useFetch<any>(createUrl('/pages/profile/header'))
```

### Reproduction

https://vueuse.org/core/useFetch/#basic-usage

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 80.88 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v18.12.1/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.5.2
  npmPackages:
    @vueuse/core: ^10.3.0 => 10.3.0 
    @vueuse/math: ^10.3.0 => 10.3.0 
    vue: ^3.3.4 => 3.3.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AlexandreAtErgosign** [comment]
Unknown forces you to set a type. In contrast, any tells typescript to ignore the type. It seems to be counter-intuitive to fetch any data instead of unknown data.
