### ISSUE TITLE
Allow timeout/interval functions to run on the server

### ISSUE THREAD

**Issue by loilo** [vueuse/vueuse#3348]
### Clear and concise description of the problem

I am using Vue reactivity in terminal applications. When I wanted to use `useIntervalFn`, I realized that it just won't do anything because of the underlying `isClient` check (which naturally is `false` in a CLI app).

This is a good default, but I think it's something that users should be able to opt out of for niche use cases like this.

### Suggested solution

I suggest adding an option to disable the `isClient` check in `useIntervalFn` and related composables (`useInterval`, `useTimeout`, `useTimeoutFn`) as well as composables using them (`useTimestamp`, `useTimeoutPoll`).

The option could be a boolean named `clientOnly`, defaulting to `true`. (I would not introduce the terms "server" or "SSR" into the option since client/server is not an applicable dichotomy in a terminal environment.)

### Additional context

If you're open to the idea of such an option, I'd be happy to submit a pull request.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by loilo** [comment]
This is what I've done, yes, I had already found a solution for me before I opened the issue.
The issue is rather for getting a sentiment whether this is something others have come across (so it may be worth addressing) or if I'm basically one of just a small handful of people encountering this. 😁

**Comment by antfu** [comment]
While I see your user case can be valid, for VueUse we just can't include every feature that is "theoretically useful". If you are able to prove this is a common use case I'd be happy to have it

**Comment by loilo** [comment]
Absolutely agreed. That's why I opened the issue in the first place, to get feedback from others.
However now that I spell that out, this should have been a "discussion" in the first place, I guess...

**Comment by loilo** [comment]
Okay, I'll close this issue for now to not keep the issue count needlessly high. I might open a discussion for this topic when projects like [Vue TermUI](https://github.com/vue-terminal/vue-termui) come along further, so that this approach might become less niche-y.
