### ISSUE TITLE
在vue2.7 + vue/cli4.5.18中10.4.0版本报错

### ISSUE THREAD

**Issue by yanbowe** [vueuse/vueuse#3349]
### Describe the bug

<img width="1329" alt="image" src="https://github.com/vueuse/vueuse/assets/43030980/7476f221-140c-4cba-9c72-44a3cf52e458">
从10.3.0升级至10.4.0npm run dev报错
10.3.0是没有问题的

### Reproduction

https://github.com/vueuse/vueuse/releases/tag/v10.4.0

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 32.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.0
  npmPackages:
    @vueuse/core: 10.4.0 => 10.4.0 
    vue: 2.7.14 => 2.7.14
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by djkloop** [comment]
same error

**Comment by RuanZhongNan** [comment]
也遇到了类似于的错误。
