### ISSUE TITLE
Changes made to `useEventListener` not working: close is not defined

### ISSUE THREAD

**Issue by userquin** [vueuse/vueuse#335]
Some change made deletes `stop` function...

**Comment by userquin** [comment]
Try to recover this from history:

https://github.com/vueuse/vueuse/commit/cde4563f80c25b23aaefb3fcf75ed16336bfd0c0#diff-830e350c5d6d8c12673ac43e7736d6171361e43f9a9a9cef443b5715b6d84745

![imagen](https://user-images.githubusercontent.com/6311119/108597285-8c359380-7388-11eb-920a-a9f4c022f72d.png)

**Comment by antfu** [comment]
Thanks for spotting this out! I don't even remember I made this mistake 😅
