### ISSUE TITLE
useUrlSearchParams replaces state when write mode is disabled leading to lost history operations

### ISSUE THREAD

**Issue by Csszabi98** [vueuse/vueuse#3352]
### Describe the bug

This is more of a compound issue

First of all:
The`useUrlSearchParams` function uses `history.replaceState` even when the `write` option is set to `false`.

Second of all:
The replace function is being triggered by a vue watcher and it can happen that the watcher will hold out-of-sync data by the time the replace function gets invoked and this leads to losing any search params that were set during this period.

See: https://github.com/vueuse/vueuse/blob/main/packages/core/useUrlSearchParams/index.ts#L101 and https://github.com/vueuse/vueuse/blob/main/packages/core/useUrlSearchParams/index.ts#L127

### Reproduction

https://stackblitz.com/edit/vitejs-vite-hbxfog?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 54.95 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/Library/Caches/fnm_multishells/1254_1692686638196/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/1254_1692686638196/bin/yarn
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/1254_1692686638196/bin/npm
  Browsers:
    Brave Browser: 115.1.56.14
    Chrome: 116.0.5845.110
    Firefox: 113.0.2
    Firefox Developer Edition: 115.0
    Safari: 16.5.2
  npmPackages:
    @vueuse/core: 10.2.1 => 10.2.1
    @vueuse/head: 1.1.23 => 1.1.23
    @vueuse/integrations: 10.2.1 => 10.2.1
    vue: 3.3.4 => 3.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hybridwebdev** [comment]
The fact it's been 2 weeks without so much as a comment is disgusting. I'm facing the same issue, and it seems the only option us to roll my own solution, or modify the code directly and have it break next release.

How can dev just ignore this issue? Has this project been abandoned? Should people look at an alternative solution to vueuse, as they seem uninterested in maintaining this code base?
