### ISSUE TITLE
How to use useTimeAgo to display in Chinese

### ISSUE THREAD

**Issue by facexyy** [vueuse/vueuse#3356]
### Clear and concise description of the problem

![image](https://github.com/vueuse/vueuse/assets/125525983/a0c7d5d6-7389-4449-a2c6-5df666bbffc6)

Can be changed to Chinese restrictions

### Suggested solution

Can be changed to Chinese restrictions

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Jannchie** [comment]
You can use [Intl RelativeTimeFormat API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat), which is built-in in browser.
