### ISSUE TITLE
useElementBounding options are ignored

### ISSUE THREAD

**Issue by george-martinec** [vueuse/vueuse#3357]
### Describe the bug

using options (UseElementBoundingOptions) on method useElementBounding does nothing, I am using options

- windowResize?: boolean;
- windowScroll?: boolean;

---

Sample code
```javascript
const { width, height } = useElementBounding(target, {
    windowResize: false,
    windowScroll: false,
});
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-9vgjun/?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor            
    Memory: 33.76 GB / 47.95 GB
  Binaries:
    Node: 19.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/core: ^10.4.0 => 10.4.0 
    @vueuse/nuxt: ^10.4.0 => 10.4.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nothing-sy** [comment]
@vueuse/core version of your demo is too low, windowScroll will not work properly. 
You should not use width and height(Viewport units) to test the options because it will trigger ResizeObserver. Please try to use top/bottom/x/y...

**Comment by george-martinec** [comment]
@nothing-sy Shouldn't the `ResizeObserver` be disabled if `windowResize` is `false` ?
