### ISSUE TITLE
[Router] useRouteParams value reset to default value

### ISSUE THREAD

**Issue by s-montigny-desautels** [vueuse/vueuse#3360]
### Describe the bug

If two components use the same `name` for `useRouteParams` and one of them is unmounted, the other value will be reset to the default value. I believe #3184 introduced this bug by using a shared cache for a route.

For the reproduction, a param must be set in the url. It should look something like this: `https://vitejsvite1457up-ym5u-v24x4fdq--3000--33975f1d.local-credentialless.webcontainer.io/testing`

### Reproduction

https://stackblitz.com/edit/vitejs-vite-1457up?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 6.4 Fedora Linux 38 (Workstation Edition)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 15.51 GB / 31.05 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.local/share/pnpm/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Firefox: 116.0.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by arsenitem** [comment]
Facing same issue after upgrading from 10.1.2 to 10.3.0

**Comment by s-montigny-desautels** [comment]
Not stale, still an issue and a PR is pending.
