### ISSUE TITLE
useVModels can't be set to passive true (TS error)

### ISSUE THREAD

**Issue by s-montigny-desautels** [vueuse/vueuse#3361]
### Describe the bug

I have this code:
```
const { x, y, width, height } = useVModels(props, emit, { passive: true });
```

I'm having the following error with typescript. `Type 'true' is not assignable to type 'false'.ts(2322)`
The typing seem to be missing a generic to match change made in #3055:
`(property) UseVModelOptions<any, false>.passive?: false | undefined`

### Reproduction

Not required

### System Info

```Shell
Not required
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by throrin19** [comment]
Same error for me. To fix that I have to do this : 

```ts
const { myOtherModel } = useVModels(props, emit, { passive : true as false });
```
