### ISSUE TITLE
Incorrect behavior in useTextareaAutosize when resizing vertically or both axes

### ISSUE THREAD

**Issue by daniilgri** [vueuse/vueuse#3372]
### Describe the bug

I tried to play around a little bit with `useTextareaAutosize ` and it seems like it has some issues with resizing when using Y axis or using both axes. Though only X axis works just fine. Something I can do about it?

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2QAfAAdcwqXPJ1KbaSEiDZ3NllTWIwAXkzIALResJZApfLKmIFDwrBoBhrIDMYACtZb5agCeQyF71l1AC9KCEhzny2AE9xdFKaBxewB1fTSADkzn1sU4KnotIA-Avy8Msznk8M08R089hdIiHQtXVpCpgP4bgAVT0G0QCBQwCHU6FnFQDhqDhZhUPcHRuTk6kQPcAG5s2zGZsGQb9f3rYtGFMAQAmglQqz-RBAMLYswISGdEG0ex0MZZhJTqNNcFSKNyBjOtaGXRMzlTbIW1qFVe07bBWCvFRSngXsgngPoKAAVlJUk3EqGA0CoHT1M0uSjCDTZewAPxUGYDDk+te24FVEA4OSwF7Ro5NKTinMndhaRBBdbzzZBIHMOzawAFk2GyQHTYBf2IQxVAOA572CiBsEClRkzS0KgN7ZA8G0jhdOU1SAE5NKK3TvGgYIQkM2tT17aQKHcmKAFl2EhOKVATUpPGglK7hC2970fZ9mHESQZCIGgA2wRAAAU4MGbRgBbPrPDQFQAWkSRsHgRgWwSgxyG2gA5Ug8H6jgjuwA57EZZKgA

### System Info

```Shell
it's just a playground
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by daniilgri** [comment]
Hey, still wondering if it is a bug or did I missed something to add?

**Comment by AnnaYuS** [comment]
Having a problem with vertical resizing as well. Looks like a bug to me

**Comment by EgorPopovPP** [comment]
+1

**Comment by scottbedard** [comment]
It looks like a bug to me as well, I'm unable to get this working in Chrome, Firefox, or Safari. To be honest, it might not be worth fixing. Maybe it's time to sunset this utility in favor of native CSS.

```html
<textarea style="field-sizing: content" />
```

This isn't supported in Firefox yet, so leaving a best-effort javascript implementation in our library is still a good idea. But what if we put a notice at the top of the documentation page that it may not be needed?

@OrbisK do you have any about this? Do you know if we have a policy regarding functions that are no longer necessary?

**Comment by OrbisK** [comment]
> This isn't supported in Firefox yet, so leaving a best-effort javascript implementation in our library is still a good idea. But what if we put a notice at the top of the documentation page that it may not be needed?
> 
> [@OrbisK](https://github.com/OrbisK) do you have any about this? Do you know if we have a policy regarding functions that are no longer necessary?

Sounds good to me! 

I cant speak for the whole team but we would like to deprecate if possible. (PR welcome)
