### ISSUE TITLE
A tiny type inconsistency between useFileDialog and useDropZone

### ISSUE THREAD

**Issue by 1001v** [vueuse/vueuse#3385]
### Clear and concise description of the problem

Hello. I've successfully used useFileDialog and useDropZone composables combination to create a file input form with DnD feature.  However, I've faced a tiny issue creating a shared callback function, since useFileDialog expects `(files: FileList | null) => void`, while useDropZone expects `(files: File[] | null) => void`. So, if I want to have a shared callback, it's type should look like this: `(files: FileList | File[] | null) => void`.

### Suggested solution

Use the same param type `FileList | null` or `File[] | null` for both composables.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by CurrrBell** [comment]
+1 for this, I just ran into it myself. Their use cases are very similar and it would be nice if they behaved more similarly

**Comment by bblanchon** [comment]
In addition to the inconsistency in the callback type, there is also a huge difference in the way we set the callback:

```js
const { onChange } = useFileDialog()

onChange ((files) => {
  // ...
})
```

vs

```js
useDropZone(dropZoneRef, {
  onDrop(files) {
    // ...
  },
})
```

There must be a way to make them more alike.

**Comment by adamreisnz** [comment]
I've opened #4085 which addresses these and some additional discrepancies and proposed solutions
