### ISSUE TITLE
ResizeObserver as a directive

### ISSUE THREAD

**Issue by runarberg** [vueuse/vueuse#3391]
### Clear and concise description of the problem

`useResizeObserver` has a similar API as `useIntersectionObserver`, as a developer it feels like resize observer should also have a handy directive accompanying it similar to `v-intersection-observer`.

### Suggested solution

Add a directive `v-resize-observer` which would work just like `v-intersection-observer`. Or from the current [demo](https://github.com/vueuse/vueuse/blob/main/packages/core/useResizeObserver/demo.vue):

```vue
<script lang="ts" setup>
import { ref } from "vue";
import { vResizeObserver } from "@vueuse/components";

const text = ref("");

function handleResize([{ contentRect }]: ResizeObserverEntry[]) {
  const { width, height } = contentRect;
  text.value = `width: ${width}\nheight: ${height}`;
}
</script>

<template>
  <textarea v-resize-observer="handleResize" v-text="text" />
</template>
```

### Alternative

Do nothing, `useResizeObserver` isn’t actually that hard to use.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by randomseed42** [comment]
It seems vResizeObserver is not in @vueuse/components, could you help to verify that?
`Module '"@vueuse/components"' has no exported member 'vResizeObserver'`
