### ISSUE TITLE
[useSortable] not support Nested Sortables

### ISSUE THREAD

**Issue by WangJincheng4869** [vueuse/vueuse#3393]
### Clear and concise description of the problem

嵌套排序的使用场景还是很多的，希望可以继续完善使其支持嵌套排序。（There are still many usage scenarios for nested sorting, and we hope to continue improving it to support nested sorting.）
[Nested Sortables Example](https://sortablejs.github.io/Sortable/#nested)

### Suggested solution

希望可以支持嵌套排序（Hope to support nested sorting）

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by esmatullaharifi** [comment]
Any updates on this?

**Comment by osgrub** [comment]
@WangJincheng4869 were you able to find a workaround or has there been any update on nested sorting?

**Comment by WangJincheng4869** [comment]
> @WangJincheng4869 were you able to find a workaround or has there been any update on nested sorting?

我直接使用的 `sortablejs` （I directly used ` sortablejs`）

**Comment by julienreszka** [comment]
is there a plan to support nested sortables at some point?
