### ISSUE TITLE
feat: add parse and stringify/serialize options to useUrlSearchParams

### ISSUE THREAD

**Issue by vincerubinetti** [vueuse/vueuse#3398]
### Clear and concise description of the problem

The current `useUrlSearchParams` is nice, but only supports raw string variables. When using React, I use this great library [`use-query-params`](https://www.npmjs.com/package/use-query-params) which has a bunch of built-in "param types" so you can specify that a certain param should always be interpreted as a boolean (for example). When having a lot of different types of variables you want to sync with the url, this drastically reduces the amount of code you have to write.

### Suggested solution

The `use-query-params` is a big and involved library. I'm not proposing to implement all of those features.

Instead, I think a good simple solution that could help us out a lot would be to have `useUrlSearchParams` accept parse and stringify/serialize options that run when getting/setting the variable from the url params. I guess it would look something like this:

```js
// our own defined param types
const booleanParam = {
  parse: (value) => Boolean(value),
  stringify: (value) => String(value)
}
const csvParam = {
  parse: (value) => value.split(","),
  stringify: (value) => value.join(",")
}

const params = useUrlSearchParams('history', {
  // extra top level key so our param names don't conflict with options
  paramTypes: {
    // our param names and types
    showCountryBorders: booleanParam,
    selectedCountries: csvParam
  }
})
```

I don't think this would be too much work for you folks to add, but it would allow us to define whatever param types we want and re-use them across our codebases.

### Alternative

I'm you could accomplish this with Vue `watch`s and `computed`s, but it'd be a lot of extra code and duplicated variables.

### Additional context

Could also look at this library for inspiration, which is now archived/deprecated:
https://github.com/oarepo/vue-query-synchronizer

**Some custom solutions I'm working on** in a related discussion:
https://github.com/vuejs/router/discussions/1990

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Kronhyx** [comment]
this is still important to add

@antfu

**Comment by BenJackGill** [comment]
Yes I also think so. Can we reopen? Would love to have string arrays showing as `foo=apple,orange,cake` instead of the current `foo=apple&foo=orange&foo=cake` and I think this suggestion would help with that conversion.
