### ISSUE TITLE
Add an AI chat dialog for docs

### ISSUE THREAD

**Issue by 0xinhua** [vueuse/vueuse#3405]
### Clear and concise description of the problem

Hi, I've developed a free open-source tool called [Documate](https://documate.site/). It's an AI chat dialog that answers questions based on the document content. I can submit a PR to the Vueuse documentation site if you're interested.

[site-screen-record.webm](https://github.com/vueuse/vueuse/assets/10118666/28dbef3d-41d8-421b-94d7-9b7298195724)

### Suggested solution

- Diret answers questions by the content of documents with AI, It assists people in using documents more easily.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for bringing this up, but we have no interest in maintaining one on our own. We are counting on external services, like GitHub Copliot X or so, to provide such capability for us.
