### ISSUE TITLE
useStore not unwrapping MaybeRefOrGetter

### ISSUE THREAD

**Issue by arnKo** [vueuse/vueuse#3417]
### Describe the bug

The `defaults` argument of `useStore` is typed as `MaybeRefOrGetter`:

```ts
export function useStorage<T extends(string | number | boolean | object | null)>(
  key: string,
  defaults: MaybeRefOrGetter<T>,
  storage: StorageLike | undefined,
  options: UseStorageOptions<T> = {},
): RemovableRef<T>
```

However the value is not correctly unwrapped in [line 148]( https://github.com/vueuse/vueuse/blob/728c3c57d1cb658c424648b94a76af88ded91fad/packages/core/useStorage/index.ts#L148C3-L148C73):

```ts
const data = (shallow ? shallowRef : ref)(defaults) as RemovableRef<T>
```

If using a getter function `() => T` as `defaults`, `data` will be: `RemovableRef<() => T>` instead of `RemovableRef<T>`.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-6bznlt?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 5.15 Linux Mint 21.2 (Victoria)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 19.58 GB / 31.19 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.19.4 - /usr/bin/npm
  Browsers:
    Chrome: 117.0.5938.88
    Chromium: 117.0.5938.62
  npmPackages:
    @vueuse/core: ^10.4.1 => 10.4.1
    vue: ^3.3.4 => 3.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by arnKo** [comment]
Additionally, using a `computed` as `defaults` results a warning from vue: `Write operation failed: computed value is readonly`

**Comment by jizai1125** [comment]
update `@vueuse/core` to latest

**Comment by arnKo** [comment]
Updated to 10.5.0. The problem remains. The provided example already uses 10.5.0
