### ISSUE TITLE
Allow headers to be set with useWebSocket

### ISSUE THREAD

**Issue by digipigeon** [vueuse/vueuse#3425]
### Clear and concise description of the problem

Inability to set headers when using useWebSocket

### Suggested solution

Allow a `headers` option to be set for example

```
const { status, data, close } = useWebSocket('ws://websocketurl', {
  heartbeat: true,
  headers: {
    "x-jwt": "My JSON Web Token"
   }
})
```

### Alternative

I have not found any workarounds for this problem so far.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chenjiezi** [comment]
You can try this.
```
const { open, send } = useWebSocket('ws://websocketurl', {
  Immediate: false
})

send(JSON.stringify({"x-jwt": "My JSON Web Token"}));
open();
```

`send` has a buffering function, and data will not be sent until the socket is connected.

https://github.com/vueuse/vueuse/blob/fb08312267dde14cb6eb879119b03870bb711d8f/packages/core/useWebSocket/index.ts#L197-L202

**Comment by lsim** [comment]
Well this is a bummer. I would have thought this was a fairly common requirement - and a fairly simple thing to add.

I know, I know - do it yourself.. 😄
