### ISSUE TITLE
Speech recognition not working in Brave browser

### ISSUE THREAD

**Issue by five1** [vueuse/vueuse#3428]
### Describe the bug

isSupported is being returned as true, however the browser only appears to listen very briefly and no text is returned in the result.

Tested using the demo at https://vueuse.org/core/useSpeechRecognition/#demo.

### Reproduction

https://vueuse.org/core/useSpeechRecognition/#demo

### System Info

```Shell
Tested in Brave Version 1.58.129 Chromium: 117.0.5938.88 (Official Build) (64-bit) on Windows 11.
Also does not work on MacOS (Brave browser user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36).
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by benoitlahoz** [comment]
Same in Electron...
