### ISSUE TITLE
📃 Restore composable type at the end of page

### ISSUE THREAD

**Issue by jd-solanki** [vueuse/vueuse#3433]
### Clear and concise description of the problem

Hi 👋🏻 

Previously, I was easy to look at all available options we can use for composable when we had it's type defined right under the composable docs. However, with new docs I have to open source code everytime to check what options it accepts and had to go through whole code.

### Suggested solution

Restore the type

### Alternative

Checking the source code and figuring out the available options for composable 🥱

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Interestingly I thought it was on purpose 🤣 workarounded atm https://github.com/vueuse/vueuse/commit/9b0103bab17546afb5bf7fdc4388cbe6520df9f0

**Comment by jd-solanki** [comment]
I was referrring to this section:
![image](https://github.com/vueuse/vueuse/assets/47495003/3678eb15-8ff7-4ee6-97c0-ce496bf92350)

If docs are autodeployed, still API section is missing:
![image](https://github.com/vueuse/vueuse/assets/47495003/e6b058ec-2289-4a74-90ba-5a10dfe9f533)
