### ISSUE TITLE
useAsyncState is not work correct when {immediate: false}

### ISSUE THREAD

**Issue by namwebdev** [vueuse/vueuse#3445]
### Describe the bug

promise is executed when pass options `{ immediate: false }` in useAsyncState

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2QAOuYVPBJFQALzpkAAPxqUQoMwM2YgYAoABZC5mVCowAnuAWQDMVTZpOXu4h6sFaMhe12OA2s7p2+JrDZx03air23h5Kw5yoAHyZgAqKGkmeTwzTxHXz2F0iIdC1dWkKmA-huoeQIVsAOkibSBxqHFmKgA5A6bk5OpEF-TNM07ZAbzvSD30YJwACVEAgKgQjguhkCKVhkN8FRPzze9EEfZ8oFfd9tEbGpEGkOxtF-c00WGfZ5BbaBEF0KUaA4SZQh8GYaFtOYEioHVhmJX97AoptuN0GxtBvPN13iSYmOwbR7HsSZJPiGTVPqBSVAgqVEEmLx4HIkAt10dCVHudgDFBbBWBvUo0igQwg1BSIdNMLJpAAQkLdTGAou86CoNAVGwUgIlw4Ks2AS8CDTd8IqMQwbgOTMJIUI4QElOo01wVIo3IGMQDjFik14VMMyzBdpCXFc11KeB2yCeA+goABWUlSTcSoYDQKgBu63q1yMINNnbEsKzXVJNgawtuFHNcwHbRpmoK-t22-fgaCocdNyzZNkEgcx5sWkBa02AxC3XYA72IQxVAOA4D1OiBsCOpsTrO+JPUu5A8H6jhBvazqAE5epBwbvGgYIQlGwsVDwdsew2kB1wAWXYSEHpUBMXMrV73rOo6DyPE9mGnX4iBoANsEQAAFb9Bm0YAKMJzwItfSRsHgOKmyegxyAigA5Ug8Bcjg4oOexGVeoA

### System Info

```Shell
all systems, all browsers
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alfred-Skyblue** [comment]
After a Promise object is created, it will automatically execute internally, which is uncontrollable. You should pass a function.

```ts

import { useAsyncState } from '@vueuse/core'

const { state, isReady, isLoading } = useAsyncState(
  () => {
    return fetch('https://jsonplaceholder.typicode.com/todos/1')
      .then(t => t.json())
      .then(r => console.log('This should not be called when init!'))
  },
  { id: null },
  { immediate: false },
)

```

**Comment by namwebdev** [comment]
@Alfred-Skyblue 
Thank you for your answer.
I no longer have any problems with this issue.
I will close this.
