### ISSUE TITLE
onLongPress: does not work on iOS when target has children

### ISSUE THREAD

**Issue by darrylnoakes** [vueuse/vueuse#3451]
### Describe the bug

When the target element has children, the `pointerleave` is fired on scroll (after a `pointercancel`) on the child. The `pointerup` event is not fired in this case (the other event listened for by `onLongPress`).
Here, Chrome fires a separate `pointerleave` event on the parent, but Safari does not.
As the `pointerleave` event does not bubble, the timeout is never cleared on Safari.

I am not sure if Chrome's behavior is correct. The spec is not clear on exactly when and where the `pointerleave` event should be fired.
Either way, `onLongPress` needs to also clear the timeout on `pointercancel` or `pointerout`.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-77y2zn?file=src%2FApp.vue

#### StackBlitz

```Shell
System:
  OS: Linux 5.0 undefined
  CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 0 Bytes / 0 Bytes
  Shell: 1.0 - /bin/jsh
Binaries:
  Node: 18.18.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.4.2 - /usr/local/bin/npm
  pnpm: 8.6.12 - /usr/local/bin/pnpm
npmPackages:
  @vueuse/core: ^7.6.2 => 7.6.2 
  vue: ^3.2.25 => 3.2.31
```

#### My laptop

```Shell
System:
  OS: Windows 10 10.0.22621
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 13.72 GB / 31.80 GB
Binaries:
  Node: 18.15.0 - ~\AppData\Local\Volta\tools\image\node\18.15.0\node.EXE
  Yarn: 3.2.0 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
  npm: 9.5.0 - ~\AppData\Local\Volta\tools\image\node\18.15.0\npm.CMD
  pnpm: 6.16.0 - ~\AppData\Roaming\npm\pnpm.CMD
Browsers:
  Edge: Chromium (118.0.2088.24)
npmPackages:
  @vueuse/components: ^10.4.1 => 10.4.1
  @vueuse/core: ^10.4.1 => 10.4.1
  vue: ^3.3.4 => 3.3.4
```

OS is actually Windows 11.

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pixlguru** [comment]
As a temp fix  set css pointer-events:none to the targets children
