### ISSUE TITLE
logicAnd does not work with Pinia Store

### ISSUE THREAD

**Issue by adarshmadrecha** [vueuse/vueuse#3452]
### Describe the bug

`logicAnd` when used  with `whenever` triggers even though the value in store is `false`.

```js
import { useMagicKeys, whenever } from '@vueuse/core';
import { logicAnd } from '@vueuse/math';
import { useAppStore } from './mystore.js';

const appState = useAppStore();
const { Shift_A } = useMagicKeys();
whenever(logicAnd(Shift_A, appState.isGlobalShortcut), () => {
   // This will be trigged even though the value of `appState.isGlobalShortcut` is `false`.
});
```

```js
// contents of ./mystore.js'
import { defineStore } from 'pinia';

export const useAppStore = defineStore({
  id: 'app',
  state: () => ({
    // Keyboard Shortcuts enable/disable Tracking
    isGlobalShortcut: false,
  }),
});
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jpn1ul?embed=1&file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.12 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/core: ^7.6.2 => 7.6.2 
    @vueuse/math: ^10.4.1 => 10.4.1 
    vue: ^3.2.25 => 3.3.4 

```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment]
Try converting your store to refs using `storeToRefs` from pinia

```ts
import { storeToRefs } from 'pinia';
const appState = storeToRefs(useAppStore());
```

See: https://stackblitz.com/edit/vitejs-vite-xgccrx?file=src%2FApp.vue

**Comment by adarshmadrecha** [comment]
Thanks a ton, this fixes the issue.
