### ISSUE TITLE
VueUse CDN ESM Build

### ISSUE THREAD

**Issue by RihanArfan** [vueuse/vueuse#3455]
### Describe the bug

 I have tried my best trying to use VueUse via ESM through JSDelivr ESM, esm.run (by JSDelivr), unpkg?module and skypack.dev but ran into problems.

Vue supports CDN via ES Module build, but you cannot use VueUse via global and Vue via ESM without facing vue-demi errors.
- https://vuejs.org/guide/quick-start.html#using-the-es-module-build
- https://vuejs.org/guide/quick-start.html#using-vue-from-cdn

Everything works fine using Vue + VueUse Global CDN build.

The error I'm facing is that while loading via JSDelivr (+esm) or esm.run (by JSDelivr, likely similar to +esm), useMouse() _loads_ but don't actually work, and instead shows x/y as 0/0. 

I'm not sure whether to reopen as a feature request for an official ESM build like what Vue have done. I've opened the issue as a bug, but the issue is ESM builds generated but not functioning by JSDelivr (and erroring for other CDNs with similar features). I understand this isn't directly the fault of VueUse.

### Reproduction

https://stackblitz.com/edit/web-platform-kylmug?file=index.html

### System Info

```Shell
117.0.2045.47 (Official build) (64-bit)
@vueuse/shared@10.4.1
@vueuse/core@10.4.1
```

### Used Package Manager

Browser ESM

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jbotka** [comment]
Hello, any news here? I am facing the same issue and I am not able to get running Vue3 with ESM from jsdelivr.

**Comment by RihanArfan** [comment]
Not stale

**Comment by RihanArfan** [comment]
With the help of [this StackOverflow post](https://stackoverflow.com/a/76740598), I've gotten it working. Essentially, ensure that the CDN isn't bundling deps together and use import maps to specify the CDN link for each necessary package.

<details><summary>via esm.sh</summary>
<p>

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Testing</title>
  </head>
  <body>
    <div id="app">{{ message }} x: {{ x }} y: {{ y }}</div>

    <script type="importmap">
      {
        "imports": {
          "vue": "https://esm.sh/vue@3.4/dist/vue.esm-browser.prod.js",
          "vue-demi": "https://esm.sh/vue-demi@0.14/lib/v3/index.mjs?external=vue",
          "@vueuse/shared": "https://esm.sh/@vueuse/shared@10/index.mjs?external=vue-demi",
          "@vueuse/core": "https://esm.sh/@vueuse/core@10/index.mjs?external=@vueuse/shared,vue-demi"
        }
      }
    </script>

    <script type="module">
      import { createApp, ref } from 'vue';
      import { useMouse } from '@vueuse/core';

      createApp({
        setup() {
          const message = ref('Hello Vue!');

          const { x, y } = useMouse();

          return { message, x, y };
        },
      }).mount('#app');
    </script>
  </body>
</html>
```

</p>
</details> 



<details><summary>via JSDelivr</summary>
<p>

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Testing</title>
  </head>
  <body>
    <div id="app">{{ message }} x: {{ x }} y: {{ y }}</div>

    <script type="importmap">
      {
        "imports": {
          "vue": "https://cdn.jsdelivr.net/npm/vue@3.3.4/dist/vue.esm-browser.prod.js",
          "vue-demi": "https://cdn.jsdelivr.net/npm/vue-demi@0.14/lib/v3/index.min.mjs",
          "@vueuse/shared": "https://cdn.jsdelivr.net/npm/@vueuse/shared@10/index.min.mjs",
          "@vueuse/core": "https://cdn.jsdelivr.net/npm/@vueuse/core@10/index.min.mjs"
        }
      }
    </script>

    <script type="module">
      import { createApp, ref } from 'vue';
      import { useMouse } from '@vueuse/core';

      createApp({
        setup() {
          const message = ref('Hello Vue!');

          const { x, y } = useMouse();

          return { message, x, y };
        },
      }).mount('#app');
    </script>
  </body>
</html>
```

</p>
</details>

**Comment by BananaAcid** [comment]
@RihanArfan your solution found its way into https://stackblitz.com/edit/bananaacid-vue3-esm-browser-only?file=README.md 
;)
