### ISSUE TITLE
OnClickoutside: the callback was triggered accidentally when the target is undefined

### ISSUE THREAD

**Issue by Zephyrrro** [vueuse/vueuse#3465]
### Describe the bug

In the following case, the target element will render after the `focus` event triggered, but the click outside callback was also called even the `input` is ignored.

After seeking the source code, I found the `pointerdown` event listener may have some problem.
```ts
useEventListener(window, 'pointerdown', (e) => {
  const el = unrefElement(target)
  if (el)
    shouldListen = !e.composedPath().includes(el) && !shouldIgnore(e)
}, { passive: true }),
``` 
Because the target element is `undefined` in the first time, so it won't change the value of  `shouldListen`. But in this case, `shouldListen` should be `false`

https://github.com/vueuse/vueuse/assets/43735265/713991b6-5338-43d3-a6f5-c036fa52e5ac

### Reproduction

https://stackblitz.com/edit/vitejs-vite-gvkvun?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.72 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 7.18.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by shawDirectUser** [comment]
meet this bug +1
