### ISSUE TITLE
Picture preview function

### ISSUE THREAD

**Issue by yoruxyy** [vueuse/vueuse#3467]
### Clear and concise description of the problem

I would like to ask if Vueuse has the function of enlarging and previewing images, similar to clicking on an image to enlarge it and display it in full screen

### Suggested solution

none

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sorry this is out-of-scope of VueUse
