### ISSUE TITLE
useRafFn delta is always 0

### ISSUE THREAD

**Issue by slavanossar** [vueuse/vueuse#3481]
### Describe the bug

I tried using the new `fpsLimit` option for `useRafFn`, but noticed that when a value is set the callback function never runs.

This issue is that this line never runs

https://github.com/vueuse/vueuse/blob/aca6a79227f7f8b06760d756dfbb4cc5958b445d/packages/core/useRafFn/index.ts#L67

which causes `delta` to always be `0`. It needs to also be included in the conditional

https://github.com/vueuse/vueuse/blob/aca6a79227f7f8b06760d756dfbb4cc5958b445d/packages/core/useRafFn/index.ts#L60-L63

I will open a PR for this since it's a very simple fix.

### Reproduction

https://github.com/slavanossar/vueuse-useraffn-delta-bug

### System Info

```Shell
System:
    OS: macOS 12.6.9
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 35.24 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.n/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.7.3 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 117.1.58.137
    Safari: 16.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bernhardberger** [comment]
I just stumbled upon this myself. `fpsLimit` option doesn't work and breaks the function
