### ISSUE TITLE
useWakeLock partially broken on IOS device

### ISSUE THREAD

**Issue by vandelpavel** [vueuse/vueuse#3484]
### Describe the bug

I'm testing over an IPad (IOS 16.5) and as you can see the "wakeLock" feature should be supported on that version: https://developer.mozilla.org/en-US/docs/Web/API/WakeLock#browser_compatibility

You can directly test it with the demo of the composable and as you can see the feature seems to work just fine except when you leave the page and you come back (loosing and getting back the visibility).

**What is expected**
The feature should be reactivated

**What is actually happening**
The feature isn't reactivated and we can get the next error "NotAllowedError: Permission was denied"

**Any additional comments**
While looking into the "useWakeLock" composable source code I saw that:

The composable manually intercepts the "document visibility" event. Whay don't you use the actual "useDocumentVisibility" composable?
The event listener gets called correctly with no issues by itself
I saw that the line of code that generates the error is the one containing wakeLock.value = await navCopy.wakeLock.request("screen"); inside the onVisibilityChange function
Not really sure if it's related to a race condition or something handled differently from IOS. The error happens when reassigning "wakeLock" and not by just calling the "request()"
Same happens both with safari and chrome

### Reproduction

https://vueuse.org/core/useWakeLock/

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 2.59 GB / 15.71 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.8.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (118.0.2088.46)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/core: ^10.2.1 => 10.2.1
    vue: ^3.3.4 => 3.3.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Doctor-wu** [comment]
Found a issue in webkit https://bugs.webkit.org/show_bug.cgi?id=205104.
But since you mentioned that hapened in both safari and chrome, that might not be the reason of the issue.
I'll try to figure out (Not a promise, since I'm not sure if I can fix it 😂).
Maybe you can try to release the wakeLock when the document isn't visible.

**Comment by dosstx** [comment]
According to the "[Screen Wake Lock API" reference page](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API#concepts_and_usage): "Only visible (active) documents can acquire the screen wake lock."

Could that be a reason for your issue?
