### ISSUE TITLE
Extract the main colors of the image

### ISSUE THREAD

**Issue by facexyy** [vueuse/vueuse#3487]
### Clear and concise description of the problem

Is there any such method in vueuse that can give an image URL and extract the main color of the image?

### Suggested solution

1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
This seems out of the scope of VueUse. I'd suggest either looking for another library or creating your own separate library.
