### ISSUE TITLE
CDN build: "shared" not available, breaks useLocalStorage

### ISSUE THREAD

**Issue by tom-adsfund** [vueuse/vueuse#349]
When I try to use useLocalStorage, I get the error `shared.watchWithFilter is not a function`.

**Comment by antfu** [comment]
What's the version you are using? Can you share a minimal repro?

**Comment by tom-adsfund** [comment]
I'm using shared v4.1.1, and core 4.2.0.b1. But you can see the problem when you put the script tags as you say for CDN, and then try to access "watchWithFilter", because it doesn't appear on the VueUse object, or anywhere else.

**Comment by antfu** [comment]
Make sure you are using the same version for shared and core, and both of them should be ^4.2.0

**Comment by tom-adsfund** [comment]
OK, that's working, thanks so much.

The versions I was using were from when the issue about CDN was first closed. But maybe that's because I was too quick to get a copy.
