### ISSUE TITLE
[use-axios] Expose axios config

### ISSUE THREAD

**Issue by pengzhen-developer** [vueuse/vueuse#3491]
### Clear and concise description of the problem

``` JavaScript
const instance = useAxios('', { method: GET , headers: {}, others: {}})

// in useHooks , need axios config
const value = useHooks(instance)
```

### Suggested solution

``` JavaScript
// the instance expose the axios config
const instance = useAxios('', { method: GET , headers: {}, others: {}})

instance.config.method => GET
instance.config.headers => {}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Jokerzhzh** [comment]
Hi! I think since this axios config is defined by u, there is no need to export this config again.
Isn’t it okay to use it this way?
```js
const config =  { method: GET , headers: {}, others: {}}
const instance = useAxios('',config)

instance.config = config

```
