### ISSUE TITLE
Is there a function similar to useResetData?

### ISSUE THREAD

**Issue by hengshanMWC** [vueuse/vueuse#3502]
### Clear and concise description of the problem

Scenario: User information needs to be reset back to default data after logging out

I couldn't find a similar function in the documentation

### Suggested solution

I feel like there should be. This is how I do it now. I’m afraid of reinventing the wheel.
```ts
import type { UnwrapNestedRefs } from 'vue'

export function useResetData<T extends object>(obj: T): [UnwrapNestedRefs<T>, (newData?: Partial<T>) => void, T] {
  const value: T = Object.create(obj)
  const data = reactive<T>(value)
  function reset(newData: Partial<T> = obj) {
    Object.assign(data, newData)
  }
  return [data, reset, value]
}



```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JianJroh** [comment]
just define default data 
```js
const defaultData = {
  name: 'sunny'.
  age: 18,
}
const data = ref(defaultData)

// when need to reset
data.value = defaultData
````

**Comment by hengshanMWC** [comment]
> ```ts
> data
> ```

In some cases, I don't want to write `.value`

**Comment by chaii3** [comment]
> > ```ts
> > data
> > ```
> 
> In some cases, I don't want to write `.value`

You can try to use useCloned
