### ISSUE TITLE
useFetch should not fetch if the url is `null`, `undefined` or empty

### ISSUE THREAD

**Issue by DrFelder** [vueuse/vueuse#3514]
### Clear and concise description of the problem

`useFetch`s intended purpose is to handle reactive fetching dependant on URL changes.
In some projects, the URL might be null, undefined or empty when the code runs for the first time. This results in unnecessary requests and errors in the log.
Least surprising would be if the request was not fired at all -- one exception might be a baseURL present at the time.

This can currently only be handled by rejecting a Promise in the beforeFetch method which leads to unexpected errors itself.

### Suggested solution

* useFetch does not fetch if the url is `null`, `undefined` or empty
* useFetch can be configured to fire if the URL is one of the mentioned values by telling it to do so (via config)

suggestion:
* a baseURL being present is viewed the same as a URL being present (requests to "" actually make sense if the baseURL is present)

### Alternative

Provide an alternative that developers can use to tell useFetch "go ahead, this is a valid URL!"

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Doctor-wu** [comment]
Maybe you can set the `immediate` props to false in order to avoid triggering the fetch at the initial time?

**Comment by arjun-aju07** [comment]
> Maybe you can set the `immediate` props to false in order to avoid triggering the fetch at the initial time?

In that case, what if we trigger `execute()` when the url is null ? That would lead to un-necessary error and request mentioned above right ?

**Comment by Doctor-wu** [comment]
> > Maybe you can set the `immediate` props to false in order to avoid triggering the fetch at the initial time?
> 
> In that case, what if we trigger `execute()` when the url is null ? That would lead to un-necessary error and request mentioned above right ?

You can trigger `execute()` when you check the URL is not null, such as `url.value && execute()`

**Comment by DrFelder** [comment]
> > > Maybe you can set the `immediate` props to false in order to avoid triggering the fetch at the initial time?
> > 
> > 
> > In that case, what if we trigger `execute()` when the url is null ? That would lead to un-necessary error and request mentioned above right ?
> 
> You can trigger `execute()` when you check the URL is not null, such as `url.value && execute()`

You are leaving out that one of the big use cases of useFetch is the reactive re-fetch on URL changes. None of your solutions consider that. [arjun-aju07](https://github.com/arjun-aju07) is right, too -- the same issues would occurr if we `execute()`.

If I only needed to fetch something once, I would use fetch directly.

**Comment by Doctor-wu** [comment]
> > > > Maybe you can set the `immediate` props to false in order to avoid triggering the fetch at the initial time?
> > > 
> > > 
> > > In that case, what if we trigger `execute()` when the url is null ? That would lead to un-necessary error and request mentioned above right ?
> > 
> > 
> > You can trigger `execute()` when you check the URL is not null, such as `url.value && execute()`
> 
> You are leaving out that one of the big use cases of useFetch is the reactive re-fetch on URL changes. None of your solutions consider that. [arjun-aju07](https://github.com/arjun-aju07) is right, too -- the same issues would occurr if we `execute()`.
> 
> If I only needed to fetch something once, I would use fetch directly.

Got you, my previous reply is only for the first time of fetch, and if you want to check the`url` in each fetch, you can use the `beforeFetch` params, `beforeFetch` will be invoked before the fetch actually invoked, and `url` will be passed into `beforeFetch`, you can cancel the fetch if the`url` is falsy by invoke `cancel` method which will be passed into `beforeFetch` as well.

**Comment by chaii3** [comment]
Absolutely agree with @DrFelder. It looks useless to execute fetch with falsy URL value. 
@Doctor-wu can you suggest any cases we need that?

**Comment by Doctor-wu** [comment]
> Absolutely agree with @DrFelder. It looks useless to execute fetch with falsy URL value. 
> @Doctor-wu can you suggest any cases we need that?

use beforeFetch

**Comment by Doctor-wu** [comment]
> Absolutely agree with @DrFelder. It looks useless to execute fetch with falsy URL value. @Doctor-wu can you suggest any cases we need that?

@chaii3 I explained it above. At first, I thought this issue was just to avoid initiating a useless fetch when the URL is empty for the first time. If you want to check the URL before each fetch, it is recommended to use beforeFetch.

**Comment by gscpw** [comment]
Not sure why this has been closed. I want to avoid initiating a useless fetch when the URL is empty. How can I do that?
