### ISSUE TITLE
reactiveOmit第二个参数为函数时，key和value传值反了，和官网顺序不一致

### ISSUE THREAD

**Issue by tororo00** [vueuse/vueuse#3518]
### Describe the bug

 Object.fromEntries(Object.entries(toRefs(obj)).filter(([k, v]) => !predicate(toValue(v) as T[K], k as K)))
应该是
 Object.fromEntries(Object.entries(toRefs(obj)).filter(([k, v]) => !predicate(k as K,toValue(v) as T[K],)))

### Reproduction

https://github.com/vueuse/vueuse/blob/main/packages/shared/reactiveOmit/index.ts

### System Info

```Shell
@vueuse/core 10.5.0

    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 118.0.5993.118
    Edge: Chromium (118.0.2088.76)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/core: ^10.5.0 => 10.5.0
    @vueuse/motion: ^2.0.0 => 2.0.0
    vue: ^3.3.4 => 3.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Doctor-wu** [comment]
To avoid impact on users who use the old version, Fix the parameters order in the doc instead of change the code implement

**Comment by tororo00** [comment]
This is a new feature, not an old one
