### ISSUE TITLE
Add factory function for useFetch

### ISSUE THREAD

**Issue by 3nuc** [vueuse/vueuse#352]
Usecase:
```ts
//myPersonalProject/src/logics/api.ts
import { useFetchFactory } from '@vueuse/core'
const API_BASE_URL = process.env.API_BASE_URL!
//useFetchFactory returns the same properties as useFetch, just that it has the url prefix set to API_BASE_URL
export const useFetchWithBaseUrl = useFetchFactory(API_BASE_URL); 

```

```ts
//myPersonalProject/components/foo.vue
<script setup>
import { useFetchWithBaseUrl } from '@/logics/api.ts'
const { data } = useFetchWithBaseUrl('/users');
</script>
```

It'd be nice to have an equivalent of `axios.create({baseUrl: API_BASE_URL})` (I know useFetch uses fetch) for useFetch aswell.

Problems with this proposal:
This is basically ... reimplementing axios.create({baseUrl}), with the same dilemmas on the lib developer side like "should I add a / if the user does useFetchFactory('www.google.com') and then useFetchWithBaseUrl('abc') -> www.google.comabc" and so on

Alternatives:
Instead of adding a factory, add documentation on useFetch's side about how to create such a wrapper yourself. It's just tricky in TS since useFetch has 3 overloads

Obviously you can just do this instead:

```ts
//myPersonalProject/components/foo.vue
<script setup>
import { useFetch } from '@vueuse/core'
import { API_BASE_URL } from '@/utils/api.ts'
const { data } = useFetch(`${BASE_URL}/users`);
</script>
```

**Comment by antfu** [comment]
Sounds good to me, and I'd like to have it named as

```ts
const useMyFetch = createFetch({ baseUrl: 'http://xxx.com/' })
```

to align with other functions we already have.

Would you like to make a PR for it? Thanks!

/cc @jacobclevenger in case you are also interested in this

**Comment by jacobclevenger** [comment]
Sure, I'd be happy to pick this up. Will send a PR this weekend!
