### ISSUE TITLE
onClickOutside Not working according to my expectations

### ISSUE THREAD

**Issue by Lazydd** [vueuse/vueuse#3522]
### Describe the bug

When clicking on oneself, the pop-up layer does not disappear. If changed to `v-on-click-outside.bubble`. When I click on the first component, its corresponding pop-up layer appears, but when I click on the second component, the first pop-up layer is not turned off, How can I solve this problem

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tamxq1/?file=src%2FAbc.vue,src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700F
    Memory: 1.47 GB / 15.79 GB
  Binaries:
    Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (118.0.2088.76)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/components: ^10.5.0 => 10.5.0
    @vueuse/core: ^10.5.0 => 10.5.0
    vue: ^3.3.4 => 3.3.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Doctor-wu** [comment]
It seems not the bug of `onClickOutside`, when you click the `picker` when the`popup` is visible,`popup` emit update to parent to set the`visible` false, mean while, the parent listen to the click event as well, it toggle the state of `visible`, lead to set the `visible` to true again, you should use`ignore` props to ignore the parent element

**Comment by Lazydd** [comment]
> It seems not the bug of `onClickOutside`, when you click the `picker` when the`popup` is visible,`popup` emit update to parent to set the`visible` false, mean while, the parent listen to the click event as well, it toggle the state of `visible`, lead to set the `visible` to true again, you should use`ignore` props to ignore the parent element

Thanks, that works. My code is also related to `Teleport`
