### ISSUE TITLE
vue2.x下 使用useVModel 不能双向绑定

### ISSUE THREAD

**Issue by baowenqing** [vueuse/vueuse#3523]
### Describe the bug

> 版本
 `
 "@vueuse/core": "^10.5.0",
    "vue": "^2.6.10",
`
我的代码：

> parentView 父组件
```js

<child-view  v-model="name"/>

```

> childView 子组件
```js
export default {
  props: ['value'],
  emits: ["input"],
  setup(props, {emit}) {
    const nameProp = useVModel(props, "value", emit)
    useTimeout(1000, {
      callback: () => {
        nameProp.value = 'danke'
      }
    })
}
```

2.x的项目   useVModel(props, "value", emit)   这样写的话  一直会出现不能更新值的问题    

看了下源码 如果修改为useVModel(props, null, emit)     key=null的时候  才可以测试通过  

![635769c1206ed258afdc22b53dfb4a3](https://github.com/vueuse/vueuse/assets/20606825/fe3b0399-f93a-4da7-96d5-61dae4ab5796)

现在这样修改表现    但是觉得很奇怪。。。麻烦帮我看下这个问题 谢谢啦~
```js
export default {
  props: ['value'],
  emits: ["input"],
  setup(props, {emit}) {
    const nameProp = useVModel(props, null , emit)
    useTimeout(1000, {
      callback: () => {
        nameProp.value = 'danke'
      }
    })
}
```

### Reproduction

见上述例子

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 3.35 GB / 31.35 GB
  Binaries:
    Node: 16.20.1 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.18.0 - D:\nodejs\npm.CMD
    pnpm: 8.6.11 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (118.0.2088.76)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alfred-Skyblue** [comment]
childView:

```js
export default {
  props: ['value'],
  emits: ["input"],
  model: {
    prop: 'value',
    event: 'update:value'
  },
  setup(props, {emit}) {
    const nameProp = useVModel(props, "value", emit)
    useTimeout(1000, {
      callback: () => {
        nameProp.value = 'danke'
      }
    })
}

```
