### ISSUE TITLE
UseAxios onSuccess function not passing header response (now passing only data)

### ISSUE THREAD

**Issue by puncreative** [vueuse/vueuse#3532]
### Clear and concise description of the problem

UseAxios onSuccess function not passing header response (now passing only data)

Can you passing response object to onSuccess function? or add more header response to function

### Suggested solution

onSuccess: (data, header) => {}

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by huiliangShen** [comment]
you can get the response
```ts
const { data, response } = useAxios(
  'https://jsonplaceholder.typicode.com/todos/1',
)
```

**Comment by puncreative** [comment]
Thank yo

เมื่อ อ. 7 พ.ย. 2566 เวลา 08:21 huiliangShen ***@***.***>
เขียนว่า:

**Comment by puncreative** [comment]
But when i want to set response data and response header to my reactive
state, i cant set in onSuccess
Function callback. I must watch response and set on. Watch function instead
เมื่อ อ. 7 พ.ย. 2566 เวลา 08:21 huiliangShen ***@***.***>
เขียนว่า:
