### ISSUE TITLE
Global state causing many updates

### ISSUE THREAD

**Issue by tom-adsfund** [vueuse/vueuse#354]
I have the value of a part of the global state going in as a prop to a component. That component has an update lifecycle function. That function is being called repeatedly even though the global state isn't changing.

I'm assuming this isn't the desired behavior?

**Comment by antfu** [comment]
Can you share a repro?

**Comment by tom-adsfund** [comment]
I don't currently have time.

On the problem itself, I'm assuming that the storage is polled and that triggers an update when it should be checking if anything has actually changed. I could be wrong.

**Comment by antfu** [comment]
Then bring this up when you have time to give more context and information. Otherwise, it's impossible to tell which part is wrong for you.
