### ISSUE TITLE
VueUse 1.6.0 - Cannot read properties of null (reading 'document')

### ISSUE THREAD

**Issue by frasza** [vueuse/vueuse#3543]
### Describe the bug

With VueUse 1.6.0 I have got an error that is not present in version 1.5.0.
Error:
```
nuxt.js:97 [nuxt] error caught during app initialization TypeError: Cannot read properties of null (reading 'document')
```
In the reproduction I have produced error with using `useInfiniteScroll` function (found same for `useScroll`) and it happens because on top of ref element I have an element with conditional rendering. 
While testing, I have noticed that if I remove condition for rendering the element, error does not appear.
I have an example where I need the condition to be part of element tree that renders scrolling element and it worked in 1.5.0

### Reproduction

https://github.com/frasza/vueuse-nuxt-scroll

### System Info

```Shell
Nuxi info:
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.9.0
- Builder:          -
- User Config:      modules, ssr, devtools
- Runtime Modules:  @vueuse/nuxt@10.6.0, @nuxtjs/tailwindcss@6.9.4
- Build Modules:    -
------------------------------
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by joaopslins** [comment]
Having the exact same issue here in Vue.

Likely related to this change: https://github.com/vueuse/vueuse/pull/3384
