### ISSUE TITLE
Utility for repeated transitions

### ISSUE THREAD

**Issue by scottbedard** [vueuse/vueuse#355]
Hi, a common use case I find myself in with `useTransition` is needing to run the same transition one way (usually `0` to `1`) multiple times. Below is an example of how I've typically been handling this problem ([see example here](https://codesandbox.io/s/sad-firefly-m45fs?file=/src/App.vue))

```js
const source = ref(0);

const transition = useTransition(source);

const progress = computed(() => source.value ? 1 - (source.value - transition.value) : 0);

const tick = () => {
  source.value += 1;
};
```

While making this computed `progress` value works, it's a bit verbose and has the following limitations...

1. There isn't an easy way to "reset" the progress. In other words, have it snap-change back to `0`
2. There isn't an easy way to pause / resume transitions, they must run to completion

Would you be open to adding a higher-order utility for this use case? Here are my initial thoughts on what the API might look like, though I'm not quite sure I like these names 🤔  

```ts
const {
  output, // current value
  pause, // pause a running transition
  resume, // continue a paused transition
  reset, // set progress to 0
  run, // run transition, would be the same as reset() then resume()
} = useRepeatableTransition({ duration, transition, onStarted, onFinished })
```

Note: This is somewhat related to the conversation in #282, though covering a simpler use case

**Comment by antfu** [comment]
Sounds good, looking forward to it!

**Comment by scottbedard** [comment]
Cool, I'm going to keep workshopping the idea more before opening a PR. I want to make sure what I submit is something I'm going to be happy with and fits my different use cases. I'm currently playing with a promise based API. I'm not sure if I like this better or not, but it certainly opens the door to different ways of expressing the animation loop and my game logic...

```js
const { animate, output, pause, resume, reset } = useAsyncTransition(options)

animate()
  .then(() => {
    // transition complete, safe to run again
  })
  .catch(() => {
    // stopped before completing
  })
```

**Comment by scottbedard** [comment]
Closing this issue in favor of https://github.com/vueuse/vueuse/issues/364 as a place to think about these sort of things
