### ISSUE TITLE
`useCurrentElement()` returns empty text node

### ISSUE THREAD

**Issue by matthew-dean** [vueuse/vueuse#3554]
### Describe the bug

I'm in an environment where Vue is stapled on top of Knockout. As a result, the Vue compiler has the `comments: true` option turned on (Knockout parses comments for directives).

In my case, that means that `useCurrentElement()` can sometimes trip me up. For example, in an element like this:
```vue
<template>
  <!-- comment -->
  <div></div>
</template>
```
`useCurrentElement()` will return the text node that precedes the comment and not the `<div>` in this case, which isn't useful. Can text nodes be skipped automatically? I'm not sure if this is a bug or feature request, but IMO I'd lean towards a bug because useCurrentElement() has no real usefulness in terms of the root element of a template if the whitespace is returned.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-mhdbqk?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 77.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/Caches/fnm_multishells/1130_1699906441495/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/1130_1699906441495/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/1130_1699906441495/bin/npm
    pnpm: 8.10.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.1
  npmPackages:
    @vueuse/core: ^10.1.2 => 10.5.0 
    @vueuse/nuxt: ~10.4.1 => 10.4.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alfred-Skyblue** [comment]
I tend to believe this is Vue's intention, where comment nodes are also recognized as nodes. In this case, there are multiple nodes under the template.

https://play.vuejs.org/#eNp9kU9rg0AQxb/KdCloQc0ht2CENgSaQv/QFnrZi+jEmq67y+5qLcHv3lkltocQQXDfvHn+dubIbrVOuhbZiqW2MLV2YNG1OuOybrQyDo5Qodu0xqB0O2ldLguMQMlH1UqHJQywN6qBgEICLrksFJmga2B9pjG88Za5OQxvYJ3BkUsA36cEJkJVYYBifXqyIKK0RBvV/yTXKChhoDddTLgESgeHjRa5QzoBpFdxTHFNQz+GOJ60su6yexRCwYcyokwXXvAxcyuLmLNEsa+r5GCVpJGMYJxRlq4FmmftaqLkbDUh+1pOkd8Po+ZMi9FJLz6x+DqjH2zvNc5eDFo0HXI211xuaGRTefv2hD19z8VGla0g94XiK9IEW8842e5aWRL2P99IuxsXW8vq3W57h9KeLuVBvXMY/ZzRSjcXrv6Hu0yWYx+thg2/zE7GUg==
