### ISSUE TITLE
Remove `onKeyStroke` listener

### ISSUE THREAD

**Issue by alisherafat01** [vueuse/vueuse#3567]
### Clear and concise description of the problem

I'm using `onKeyStroke` but I want to disable it's functionality in code in some cases(for example after 5000ms of mounted hook in vue) but I can't find the API to remove listener.
How to do that?

### Suggested solution

It can be something like this:
```
const listener = onKeyStroke(['s', 'S', 'ArrowDown'], () => {
  // do something
})
setTimeout(()=>{
  listener.remove();
},5000)
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Alfred-Skyblue** [comment]
https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2QAfAAdcwqYDAGb8aQHA7Z5PDNPELPYUulAIJcznKBBWAAXkzICM1ZA6eseFYHjLtf68nTz2F0iIdC1dWkuZU1hMBxqHFmKgA5As19mp9qOLPgCp5ABpRAhAHSFcwNJLowrvDrh03Tl1RBb6u2eTIWcFlUqFvzxAjG0Ul7GzbMZmwL8anMf9j1Pc9L0QbQMDXZA10YdcAXQ9dQw4FdIjUVhImwNc-R0RwW3TXNsxUWiVB-aQo0MVQAGoWOzA5QPfRliyAA
