### ISSUE TITLE
Idea: Detect browser capabilities

### ISSUE THREAD

**Issue by itpropro** [vueuse/vueuse#357]
I think it would be helpful to have a utility for some basic browser capabilities to e.g. control fallbacks for old browsers. Maybe we could choose some important ones from modernizr (https://modernizr.com/docs)?

**Comment by antfu** [comment]
For many functions, we already have an `isSupported` flag for each one. Or what's your proposed API for that?

**Comment by itpropro** [comment]
You are right, it's better to have the `isSupported` flag and have additional utility functions for additional needed functionalities .
