### ISSUE TITLE
Does not work on nuxt 2, gives a "command not found error"

### ISSUE THREAD

**Issue by slidenerd** [vueuse/vueuse#3572]
### Describe the bug

![image](https://github.com/vueuse/vueuse/assets/5139030/a0a8e25f-2c35-4f89-8691-3cb38fb77388)

### Reproduction

https://codesandbox.io/p/sandbox/vueuse-nuxt-error-kccrrd

### System Info

```Shell
Follow exactly the steps mentioned in documentation to install vueuse on Nuxt 2.17.2

- The guide outlines these steps
- Step 1: Install vueuse core and vueuse nuxt packages
 - npm i -D u/vueuse/nuxt u/vueuse/core
- Step 2: Modify nuxt.config.js to add this line under buildModules
 - '@vueuse/nuxt',
- Step 3: Test the use windowSize function on pages/index.vue
- Step 4: npm run dev
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Doctor-wu** [comment]
That seems not the issue of vue-use, maybe you should commit an issue in nuxt community
