### ISSUE TITLE
Index.d.ts error since 4.3

### ISSUE THREAD

**Issue by Jogai** [vueuse/vueuse#358]
Header looks like this:

    import { Fn, MaybeRef, ConfigurableEventFilter, ConfigurableFlush, Pausable } from '@vueuse/shared';
    export * from '@vueuse/shared';
    import { Ref, defineComponent, ComputedRef, WritableComputedRef, ToRefs } from 'vue-demi';
    import { Ref as Ref$1 } from 'vue-demi';

Giving me "'"vue-demi"' has no exported member named 'ToRefs'. Did you mean 'toRefs'?"
Also, line 4 seems redundant since Ref is imported on line 3?

**Comment by antfu** [comment]
Updated your `@vue/composition-api` to `1.0.0-rc.3` and this should be fixed.

> Also, line 4 seems redundant since Ref is imported on line 3?

That's the weird behavior of `rollup-plugin-dts` but it shouldn't matter anyway.

**Comment by Jogai** [comment]
Thanks, confirmed
