### ISSUE TITLE
useBreakpoint functions MaybeRefOrGetter

### ISSUE THREAD

**Issue by VividLemon** [vueuse/vueuse#3587]
### Clear and concise description of the problem

On the return of https://github.com/vueuse/vueuse/blob/8ba4df8b6a343945681083cd0a0687135213fc1e/packages/core/useBreakpoints/index.ts#L88

It doesn't allow you to modify the parameter value reactively. This is an issue as you can't modify the behavior of the various greater() functions

### Suggested solution

Add MaybeRefOrGetter to the various functions that return Ref, greater, between, greaterOrEqual

### Alternative

There is no alternative besides writing a function for each variation and dynamically switching between each branch. Or replacing the ref

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by VividLemon** [comment]
@antfu @Doctor-wu I'm still getting a type error when I do
![image](https://github.com/vueuse/vueuse/assets/31498096/44cd934a-62b8-4102-b7cb-a62667b97d9d)

**Comment by Doctor-wu** [comment]
> @antfu @Doctor-wu I'm still getting a type error when I do ![image](https://private-user-images.githubusercontent.com/31498096/288139352-44cd934a-62b8-4102-b7cb-a62667b97d9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MjgzMTQsIm5iZiI6MTcwMTgyODAxNCwicGF0aCI6Ii8zMTQ5ODA5Ni8yODgxMzkzNTItNDRjZDkzNGEtNjJiOC00MTAyLWI3Y2ItYTYyNjY3Yjk3ZDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAyMDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MDc0MjJjZjAzMjk0N2Q5ZmQzN2UyMjIwNGMyZmIxYTMwMWE4M2FjMDI3NTE4OGE3NTkyOTNiYzA5Y2MwYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OgA788MWYBGBjc7mUnuKtSQaTVee75lfXadezvSQLCY)

@VividLemon `greaterOrEqual` parameter's type is supposed to extends `keyof breakpoints` which should extends string, you can use `computed(() => greaterOrEqual(props.responsive ?? 'sm').value)`, that should work reactivity

**Comment by Doctor-wu** [comment]
But I feel like your pattern is closer to the convention of Vueuse, so maybe we should make it more intuitive @VividLemon
