### ISSUE TITLE
Cookie is not a constructor

### ISSUE THREAD

**Issue by kissu** [vueuse/vueuse#3589]
### Describe the bug

The default example does not work with Nuxt3
https://vueuse.org/integrations/useCookies/#common-usage

With the following code
```html
<template>
  <div>
    <strong>locale</strong>: {{ cookies.get('locale') }}
    <hr>
    <pre>{{ cookies.getAll() }}</pre>
    <button @click="cookies.set('locale', 'ru-RU')">Russian</button>
    <button @click="cookies.set('locale', 'en-US')">English</button>
  </div>
</template>

<script setup>
import { useCookies } from '@vueuse/integrations/useCookies'

const cookies = useCookies(['locale'])
</script>
```

![image](https://github.com/vueuse/vueuse/assets/5133074/306d4687-6e54-48dc-b3aa-3d41d8af5917)

Btw, I do have a different error on Stackblitz: https://stackblitz.com/~/github.com/kissu/vueuse-cookie-nuxt3
`_universal_cookie.default is not a constructor`, but it's probably related

### Reproduction

[Codesandbox reproduction](https://codesandbox.io/p/github/kissu/vueuse-cookie-nuxt3/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpfro7kb00072v6k6ihnmhqd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpfro7kb00032v6k2naogfh2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpfro7kb00052v6knqs91a04%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpfro7kb00062v6kianyfvca%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpfro7kb00032v6k2naogfh2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpfro7kb00022v6kmw0r87ao%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clpfro7kb00032v6k2naogfh2%2522%252C%2522activeTabId%2522%253A%2522clpfro7kb00022v6kmw0r87ao%2522%257D%252C%2522clpfro7kb00062v6kianyfvca%2522%253A%257B%2522id%2522%253A%2522clpfro7kb00062v6kianyfvca%2522%252C%2522activeTabId%2522%253A%2522clpfrrs0i00qn2v6k4qn1ijez%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clpfrrs0i00qn2v6k4qn1ijez%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clpfro7kb00052v6knqs91a04%2522%253A%257B%2522id%2522%253A%2522clpfro7kb00052v6knqs91a04%2522%252C%2522activeTabId%2522%253A%2522clpfro8dx007u2v6k6ym8hclg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpfro7kb00042v6klmwved1c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clpfro7n4000defgvhbjkc5le%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clpfro8dx007u2v6k6ym8hclg%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clpfrohg200bd2v6k08ysytel%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 48.68 GB / 62.70 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.9.2 - ~/.local/share/pnpm/pnpm
    bun: 1.0.9 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 119.1.60.118
    Chrome: 119.0.6045.159
  npmPackages:
    @vueuse/integrations: ^10.6.1 => 10.6.1 
    vue: ^3.3.8 => 3.3.9
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Doctor-wu** [comment]
Unable to access your reproduction's workspace

**Comment by kissu** [comment]
@Doctor-wu oh indeed, fixed the Codesandbox one!

**Comment by fs-innonova** [comment]
I/m facing the same issue :/

**Comment by Doctor-wu** [comment]
Hi, @kissu & @fs-innonova, I found that it's a problem with the version of `universal-cookies`, in `@vueuse/integration`, we use the `4.0.4` version of `universal-cookies`, and I tried to install the correct version and then it works in the project, hope this can help you

**Comment by kissu** [comment]
Quick question probably not worth opening a new issue @Doctor-wu, does `useCookies` support SSR?
I thought it would but it has some mismatch errors with something like
```html
<div v-if="cookies.get('locale') == 'ru-RU'">hello</div>
```

**Comment by Doctor-wu** [comment]
> Quick question probably not worth opening a new issue @Doctor-wu, does `useCookies` support SSR?
> I thought it would but it has some mismatch errors with something like
> ```html
> <div v-if="cookies.get('locale') == 'ru-RU'">hello</div>
> ```

TBH, I'm not quite sure about this 😂

**Comment by CesarWatrin** [comment]
> Hi, @kissu & @fs-innonova, I found that it's a problem with the version of `universal-cookies`, in `@vueuse/integration`, we use the `4.0.4` version of `universal-cookies`, and I tried to install the correct version and then it works in the project, hope this can help you

Thank you so mush @Doctor-wu  🙏
