### ISSUE TITLE
useRafFn docs show incorrect api usage

### ISSUE THREAD

**Issue by jacobclevenger** [vueuse/vueuse#359]
In the documentation for the [`useRafFn`](https://vueuse.org/core/useRafFn/) it show the following usage
```ts
import { useRafFn } from '@vueuse/core'

const { pause, resume } = useRafFn((elapsed) => {
  console.log(elapsed.value)
})
```

This doesn't seem correct to me as there is no elapsed varaible passed to the callback. If it is meant to have one I'll be happy to create a PR, otherwise I think we should update the docs to reflect the api

**Comment by antfu** [comment]
Let's update the docs then. Thanks!
