### ISSUE TITLE
[bug] `useStorage` instances are not updated when deleting the key/value

### ISSUE THREAD

**Issue by MathieuRA** [vueuse/vueuse#3598]
### Describe the bug

If multiple instances of `useStorage` point to the same `key`, when deleting the key/value, only the instance used for the deletion is updated, the other instances keep the previous value.

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2QAfAADWqsTMqYiGchoFTAYA1ViJA4HZPDNPEdMAHWwqYzmdKlTzBYMRZLZfb9RUVZrdcbzdKAQS5nOUCCsAAvA2+GAqInEIuVMhQkGFyBSnUaBw0MSwJsN1K6KDSgnYABuFSQKhp7DwNAAVhPi-T4tnMHiiVIy6rvmhYoDW479PIo7JuBk4qNOP47tYeCsB466biE26LnuHAHkeJ5nkEoKPHeD5Pi+76bJ+350LAf4qEhKFpJudQIGkXbkGBE6Qc8wrSEQdBanU0glv4NwAgkFRIIONQcLMKgAOQOjcnJ1Ig8lNk2MzYJu5aJHOomIOJLFINo8kwIgITyYwKjYKQET2Jp8g6f2Kj6XiRmSYgpnmZZ1m2fZGnYEY-CyqK-iAak2iOMATYqCo-ZRiBrkKQkCTqdgByBcFthyvRtCMVFJaxfFlSJd2aT6f5BhNgcjJVkAA

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 9.41 GB / 15.33 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Brave Browser: 119.1.60.118
    Chrome: 119.0.6045.159
  npmPackages:
    vue: ^3.3.4 => 3.3.8
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DaedalusHatak** [comment]
By setting it back to null it's being deleted therefore not updated. If you really need to have 2 different variables for the same element maybe consider switching it to empty string or make it async with nextTick to reset it after
