### ISSUE TITLE
useWebNotification demo is not working

### ISSUE THREAD

**Issue by jamols09** [vueuse/vueuse#3600]
### Describe the bug

Hi the demo does not work when clicking the "Show Notification"

### Reproduction

https://vueuse.org/core/useWebNotification/#demo

### System Info

```Shell
-na
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by huiliangShen** [comment]
you should allow your website notifications, maybe!
![image](https://github.com/vueuse/vueuse/assets/14904550/cf2c071e-9ee0-44a9-946f-81e1748c4dd3)

**Comment by michael-harvey** [comment]
On a mac notifications also need to be enabled on the app level `System Settings -> Notifications -> [Browser name]`

**Comment by michealroberts** [comment]
Hey team. I originally wrote the `useWebNotification()` composable, and originally it was working ... 

However, testing in both a secure and local insecure context, I am not seeing the notification being triggered. I see no reason for it not to work ... I have granted permissions. I will dig into the demo today and see what changes have been made over time ...

**Comment by SampsonCrowley** [comment]
@michealroberts this probably should be it's own issue as a feature request, but would you consider returning the `notification` ref in the composable while you're already working on it? it would be nice to be able to run logic around whether a notification was already open or if it's currently closed without needing to add a couple one-liner "onOpen" and "onClose" functions every time and increasing the number of references in the app. right now it's almost literally the only reason I need the hooks (not that they don't have other massive values, just that 90% of the time the only reason I need to have hooks is to track the open/closed state

**Comment by michael-harvey** [comment]
@SampsonCrowley Apologies if I misinterpreted this, but isn't that already possible with the `notification` ref property returned by the hook?

**Comment by michealroberts** [comment]
@SampsonCrowley The notification ref is returned, but you could also use the callback hooks if you wanted to as well.

If you needed more than those hooks provide then it is completely up to you as to how you consume this. Although I would argue that those event hooks are essentially what you will probably utilise anyway.

Is there a particular reason why the hooks 🪝 wouldn't be enough?

**Comment by SampsonCrowley** [comment]
@michealroberts I think you're misinterpreting my request, but thanks for letting it back in.

_needing_ the hooks is exactly what I was asking to be able to avoid. When the base ref is _only_ accessible through the hooks, then if you want to keep proper reactivity, the component using the compostable has to keep is own local ref as well. It's a ref of a ref. If that doesn't make much sense over text, sorry. This way the notification is returned directly, and is either null (a.k.a. "falsey") when closed, or a notification class object (a.k.a. truthy) so you can run "open/closed" rendering logic directly without adding additional memory usage and latency from needing to create additional functions and register them with the on open/onClose hooks _and_ from needing to add additional refs just to track whether it's in open or closed state, when the existence of the notification itself provides that tracking already

**Comment by michealroberts** [comment]
Hi @SampsonCrowley I don't think that would be the case.

If you would like to achieve something like what you're stating you would use as:

```ts
const { notification, open, close } = useWebNotification()

const isOpen = computed(() => !!notification.value)
```

And then call open / close as needed ...

**Comment by SampsonCrowley** [comment]
@michealroberts exactly. **Or** even more simply now, which was why I asked for it (I'm very thankful for what might look like just a simple addition to some)

```jsx
<Button v-if="notification" />
```

It's a helpful addition. It can be used both as an existence check and to do more advanced operations without needing changes from the framework

**Comment by michealroberts** [comment]
@SampsonCrowley This composable returns the notification, so although you asked for it - it's already been implemented.

**Comment by epeleg** [comment]
Can someone please tell me how should this look when it DOES work?
running locally (via local host over http) on windows 10 using the following code:
```
import { useWebNotification } from '@vueuse/core';
const testUseWebNotification= () => {
  const {
    isSupported,
    //notification,
    show,
    //close,
    onClick,
    onShow,
    onError,
    onClose,
  } = useWebNotification({
    title: 'Hello, VueUse world!',
    dir: 'auto',
    lang: 'en',
    renotify: true,
    tag: 'test',
  })

  if (isSupported.value) {
    alert('web notification isSupported');
    show();

    onClick(()=>{alert('web notification clicked')});
    onShow(()=>{alert('web notification showen')});
    onError(()=>{alert('web notification error')});
    onClose(()=>{alert('web notification close')});
  }
}
```
calling testUseWebNotification does trigger the alwert saying that it isSupported and I even get the 'web notification showen' alert but where is the notification itself? (its not it the window notifications center...)

when connecting to the vueuse site and the page with the demo via my phone, pressing the "show Notification"  green button asked for premissions and after I approved it added below the green button the following error:
TypeError: Failed to construct 'Notification': illegal constructor.
Use ServiceWorkerRegistration.showNotification() instead.

maybe this can help someone understand what is going on here....

**Comment by OrbisK** [comment]
> Can someone please tell me how should this look when it DOES work? running locally (via local host over http) on windows 10 using the following code:
> 
> ```
> import { useWebNotification } from '@vueuse/core';
> const testUseWebNotification= () => {
>   const {
>     isSupported,
>     //notification,
>     show,
>     //close,
>     onClick,
>     onShow,
>     onError,
>     onClose,
>   } = useWebNotification({
>     title: 'Hello, VueUse world!',
>     dir: 'auto',
>     lang: 'en',
>     renotify: true,
>     tag: 'test',
>   })
> 
>   if (isSupported.value) {
>     alert('web notification isSupported');
>     show();
> 
>     onClick(()=>{alert('web notification clicked')});
>     onShow(()=>{alert('web notification showen')});
>     onError(()=>{alert('web notification error')});
>     onClose(()=>{alert('web notification close')});
>   }
> }
> ```
> 
> calling testUseWebNotification does trigger the alwert saying that it isSupported and I even get the 'web notification showen' alert but where is the notification itself? (its not it the window notifications center...)
> 
> when connecting to the vueuse site and the page with the demo via my phone, pressing the "show Notification" green button asked for premissions and after I approved it added below the green button the following error: TypeError: Failed to construct 'Notification': illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.
> 
> maybe this can help someone understand what is going on here....
```html
<script setup>
const {
  isSupported,
  notification,
  show,
  close,
  onClick,
  onShow,
  onError,
  onClose,
} = useWebNotification({
  title: 'Hello, VueUse world!',
  dir: 'auto',
  lang: 'en',
  renotify: true,
  tag: 'test',
})

if (isSupported.value)
  show()
</script>
```

**Comment by OrbisK** [comment]
I am closing this issue. @jamols09 if you have any issue please reopen or create a new one :)
