### ISSUE TITLE
Almost no composition APIs work, undefined imports

### ISSUE THREAD

**Issue by Bluskript** [vueuse/vueuse#361]
When trying this in a project based off of `vitesse`, I found that I was unable to use almost any composition APIs available. Most of them had an error like `watch is not defined`, or `ref is not defined`. After doing some digging, the offending line was found [here](https://github.com/vueuse/vueuse/blob/main/packages/core/useEventListener/index.ts)

![image](https://user-images.githubusercontent.com/52386117/109654044-bb3dc900-7b2f-11eb-8938-95cf24c4febe.png)

```vue
<script setup lang="ts">
import { useMouse } from '@vueuse/core'

const {xMouse, yMouse} = useMouse()
</script>
<template>
  <div />
</template>
```

**Comment by antfu** [comment]
Can't reproduce, please provide a minimal reproduction.

**Comment by Bluskript** [comment]
https://github.com/harmony-development/tempest/tree/tempest-vitesse

This isn't modified from the original vitesse template much, but still experiences this issue

**Comment by antfu** [comment]
Confirmed your fork did have this error on my machine as well. But can't find the problem. As I still do see the problem on Vitesse, I guess it's more related to setup but VueUse itself. To help me better investigating on this, you can

- Generate a new repo with the **latest** Vitesse
- Made changes that introduce this error in **a separated commit**, that way I can see the diff and identified the problem better.

Thanks

**Comment by Bluskript** [comment]
I have now updated the branch to show diffs. https://github.com/harmony-development/tempest/commit/ec5f7413beca4e28fc4bb6268798a49efd69d376

**Comment by Bluskript** [comment]
I have no idea what's wrong with this... I have tried isolating libraries I included in the build one by one to see if one of them is causing an issue, but the issue was still not resolved.

**Comment by antfu** [comment]
Might be related to your switch from `pnpm` to `yarn`? Which version of yarn are you using?

**Comment by Bluskript** [comment]
I actually only switched from `pnpm` in order to figure out the problem. I have tried installing dependencies with:
`pnpm` 5.18.1
`yarn` 1.21.1
`npm` 7.5.4

**Comment by Bluskript** [comment]
https://pastebin.com/9peVuFUp
Here's the install log when using `pnpm`, it might be useful...

**Comment by Bluskript** [comment]
I found the source of the problem! After installing `v-wave`, `vueuse` stops working...

**Comment by justintaddei** [comment]
v-wave is pretty much the "to-do MVP" of vue directives. Any idea what might be causing the issue? I'll be able to troubleshoot in a couple of hours. 

The only thing it does that is any relation to the issue (that I can think of) is register a `pointerdown` event.

**Comment by justintaddei** [comment]
Is `useMouse` the only hook breaks or do other/all hooks break?

**Comment by Bluskript** [comment]
All hooks that use Vue break. I'm fairly certain that [isVue3](https://github.com/justintaddei/v-wave/blob/master/src/utils/isVue3.ts#L10) might be causing the issues.

**Comment by justintaddei** [comment]
Interesting, I'll take a look at that. Although I don't, at first glance, see what could be causing the issue. If I understand it correctly vue-demi distinguishes between vue2 and vue3 at install time. I'm distinguishing which version based on the first character of Vue.version at run time.

I'll take a closer look this afternoon.

**Comment by Bluskript** [comment]
More strange behavior:
If I use the default vitesse template and install `v-wave`, no errors occur.
If I create a new module under `src/modules/ripple.ts`, no errors occur.
If I add `import "v-wave"` at the top of `ripple.ts`, I get the error `ref is not defined`. *note that I didn't install the plugin into Vue, I just imported it.*
If I delete that import statement, *the error doesn't go away*. Even after restarting the dev server.

**Comment by Bluskript** [comment]
I found a solution but it doesn't seem like a good one:

Exclude `v-wave` from being optimized in vite.config.ts:
```diff
  optimizeDeps: {
    include: [
      'vue',
      'vue-router',
      '@vueuse/core',
    ],
    exclude: [
      'vue-demi',
+     'v-wave',
    ],
  },

**Comment by justintaddei** [comment]
The strangest thing to me is that it results in `ref is not defined` seeing as I don't make use of any of Vue 3's Composition API.

I'm installing the example now. I'll see what I can find.

**Comment by justintaddei** [comment]
This may be old news, but the error appears to be thrown at the import statement in vue-demi:

![image](https://user-images.githubusercontent.com/16705594/109870368-3e8e1600-7c27-11eb-9aba-37719fe6a522.png)


If you're not familiar with vue-demi's internal workings, it runs a `postinstall` hook that replaces its `main` file with a specific one depending on the version of Vue that is installed.


This is probably the strangest issue I've ever seen. I'm going to open an issue with vue-demi and see if they have any idea.

**Comment by justintaddei** [comment]
> I found a solution but it doesn't seem like a good one:
> 
> Exclude `v-wave` from being optimized in vite.config.ts:

I just tried removing `vue-demi` from `optimizeDeps.exclude` and the error has disappeared.
Why was `vue-demi` excluded?

**Comment by antfu** [comment]
> Exclude v-wave from being optimized in vite.config.ts:

Can confirm this works

> I just tried removing vue-demi from optimizeDeps.exclude and the error has disappeared.

Unfortantually, this is not working for me.

> Why was vue-demi excluded?

It's because `vue-demi` exports all the entries from Vue where Vite will try to bundle another Vue instance inside `vue-demi` which may cause problems. Since vue-demi supports esm and it's a small single file, there is no need to be optimized either.

**Comment by Fanna1119** [comment]
I had this issue too could not really pinpoint the problem,
it might have been some version or vue mixed with vue-demi messing up things.
for me after 'npm update' it seem to sort things out.

**Comment by justintaddei** [comment]
Please try in combination with [v-wave@beta](https://www.npmjs.com/package/v-wave/v/1.2.9-beta.0) (`npm i v-wave@beta`)  and let me know if it resolves the issue. I've changed how v-wave detects a vue3 environment and it shouldn't cause this problem anymore.

**Comment by justintaddei** [comment]
@antfu were you able to confirm if this resolved the issue?
