### ISSUE TITLE
About using draggable components to add drag switches

### ISSUE THREAD

**Issue by QC2168** [vueuse/vueuse#3610]
### Clear and concise description of the problem

I using [drag components](https://github.com/vueuse/vueuse/blob/main/packages/core/useDraggable/index.ts),  I couldn't find a switch to disable drag and drop functionality. Can you provide a switch like this? Enable developers to use more flexibly

### Suggested solution

provide a props attribute to switch drag or fixed

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by alexzhang1030** [comment]
Closed via #3613
