### ISSUE TITLE
useResizeObserver returns method which shadows builtin window method

### ISSUE THREAD

**Issue by snoozbuster** [vueuse/vueuse#3612]
### Clear and concise description of the problem

`useResizeObserver` returns an object with `{ stop, isSupported }`. Calling this `stop()` function will disconnect the resize observer and cleanup watchers. However, there is a [`window.stop()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/stop) method which already exists. This means that if a line such as `const { stop } = useResizeObserver` call is removed, the code which uses `stop()` will not begin to generate an error (lint or type), and its removal might be missed, causing unintended and potentially very confusing or difficult to track down behavior, as `window.stop()` is not a common part of modern JS development.

### Suggested solution

- Return the method under an additional name (eg, `stopObserving`, `disconnect`, or `cancel`)
- Mark the original as `@deprecated`
- Use the new name in all documentation
- Remove it entirely in a future release

I would also suggest auditing other functions/documentation and making this update across the board. 

### Additional context

This is not a hypothetical - I fixed a [very similar issue](https://github.com/bcakmakoglu/vue-flow/pull/787) (which didn't use VueUse in this case, but used `const stop = watch(...)`) in a major vue graphing library some time back. I think it would be best practice to avoid using `stop` as a name for cleanup methods returned from compositions.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Alfred-Skyblue** [comment]
Actually, we are returning an object, and this object has two properties: `isSupported` and `stop`. Both of these properties are functions, and you can directly invoke them. You can use the object to call `stop`. However, `window.stop` is just a property within the `window` object, and it can be shortened by omitting `window`. We haven't overridden `window.stop`; it's just scoped differently. In Vue, you can also use `const stopWatch = watch()` without any difference. If you have concerns, you can try the following approach:

```ts
const { stop: stopObserver } = useResizeObserver(/* ... */)
stopObserver()

// or

const observer = useResizeObserver(/* ... */)
observer.stop()

```
