### ISSUE TITLE
[useVModel]：The value recorded by useVModel in the event captured by devtool is incorrect

### ISSUE THREAD

**Issue by Steve245270533** [vueuse/vueuse#3635]
### Describe the bug

**Home.vue**
```vue
<template>
  <div class="home">
    <h1>app-user: {{ user }}</h1>
    <my-input v-model="user" />
  </div>
</template>

<script setup lang="ts">
import MyInput from '../components/MyInput.vue';
import { ref } from 'vue';

const user = ref({
  name: 'steve',
  work: false,
});
</script>
```
**MyInput.vue**
```vue
<template>
  <input v-model="model.name" />
  <div>
    <input v-model="model.work" id="work" type="checkbox" />
    <label for="work">上班</label>
  </div>
</template>

<script setup lang="ts">
import { useVModel } from '@vueuse/core';

type UserType = {
  name: string;
  work: boolean;
};

const props = defineProps<{
  modelValue: UserType;
}>();

const emits = defineEmits(['update:modelValue']);

const model = useVModel(props, 'modelValue', emits, {
  passive: true,
  deep: true,
});
</script>
```
Every time the props data is modified in the subcomponent, although the update: modelValue event is correctly triggered, the value recorded in devTools always references the latest value, rather than a snapshot of the change：
![image](https://github.com/vueuse/vueuse/assets/46118247/9da2480b-0109-4584-9b9e-46aa6608c5aa)

### Expected
Capable of accurately recording snapshots of each state change

### Reproduction

https://stackblitz.com/edit/vitejs-vite-x5gdz1?file=src%2Fpages%2FHome.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/core: ^9.13.0 => 9.13.0 
    @vueuse/rxjs: ^10.2.1 => 10.2.1 
    vue: ^3.2.33 => 3.2.40
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Doctor-wu** [comment]
<img width="829" alt="CleanShot 2023-12-11 at 11 52 15@2x" src="https://github.com/vueuse/vueuse/assets/44631608/2aeb14da-e108-4991-b63f-3b83957cb15b">
Hi @Steve245270533 , it looks like not the problem of Vueuse cuz the log's contents are correct, maybe you should submit an issue in [Vue devtools](https://github.com/vuejs/devtools/issues)

**Comment by Steve245270533** [comment]
> Hi @Steve245270533 , this doesn't seem to be a Vueuse issue cuz the log's contents are correct, maybe you should submit an issue in [Vue devtools](https://github.com/vuejs/devtools/issues)
> 
> <img alt="CleanShot 2023-12-11 at 11 52 15@2x" width="829" src="https://private-user-images.githubusercontent.com/44631608/289420687-2aeb14da-e108-4991-b63f-3b83957cb15b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTQwMTcsIm5iZiI6MTcwMjI5MzcxNywicGF0aCI6Ii80NDYzMTYwOC8yODk0MjA2ODctMmFlYjE0ZGEtZTEwOC00OTkxLWI2M2YtM2I4Mzk1N2NiMTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDExMjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MjMzMTNlNGFlMDE2NDVhMmQyZmI1YTY5MmU3N2I1MGFjNWE4MTQxY2IwNzY5Yjg1Nzk1ZmYzYjc4ZDc5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.30od26CKLz7itJ_pwXgMgzUeBIBLAw3ALECOP9gMrD4">

On the surface, it appears to be correct, but in reality, we still cannot obtain the snapshot values of the changes：
![image](https://github.com/vueuse/vueuse/assets/46118247/d6d4efd2-86c5-44ce-9adc-08dad1f4e969)

**Comment by Doctor-wu** [comment]
@Steve245270533 That's because it's the same ref. When you expand the `[[Target]]`, it reads the newest value which should be `steve123` because it had been changed after this log. The console prints the runtime value which is `steve1`.

**Comment by Doctor-wu** [comment]
> @Steve245270533 That's because it's the same ref. When you expand the `[[Target]]`, it reads the newest value which should be `steve123` because it had been changed after this log. The console prints the runtime value which is `steve1`.

And I believe that's the same reason why the Vue devtool displays the same value.
If you take a snapshot of that ref, you will find the runtime value is correct.
![CleanShot 2023-12-11 at 20 10 31@2x](https://github.com/vueuse/vueuse/assets/44631608/73e3ad7e-a6fe-454e-b6cb-506fdf179143)

**Comment by Doctor-wu** [comment]
Hey @Steve245270533 , I'm going to close this issue. If you have any more questions, please feel free to open another issue.
