### ISSUE TITLE
Problem reactive data in useRouteQuery for list query

### ISSUE THREAD

**Issue by mohamadkhalili** [vueuse/vueuse#3636]
### Describe the bug

dont work list reactive data in useRouteQuery

### Reproduction

https://stackblitz.com/edit/vitejs-vite-pjwtpr/?file=src%2FApp.vue,package.json

### System Info

```Shell
Binaries:
    Node: 20.6.1 - ~/.nvm/versions/node/v20.6.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.6.1/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v20.6.1/bin/npm
    pnpm: 8.11.0 - ~/.nvm/versions/node/v20.6.1/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.123
  npmPackages:
    @vueuse/core: ^9.13.0 => 9.13.0 
    @vueuse/router: ^9.13.0 => 9.13.0 
    vue: ^3.3.4 => 3.3.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Doctor-wu** [comment]
You should install `vue-router` in your project, Vueuse will not bundle `vue-router` in the lib output.
https://stackblitz.com/edit/vitejs-vite-armyfc?file=src%2Fmain.js
<img width="1283" alt="CleanShot 2023-12-11 at 17 13 03@2x" src="https://github.com/vueuse/vueuse/assets/44631608/50a6d0f2-10be-49b8-80c2-ec68bac5ae29">

**Comment by mohamadkhalili** [comment]
I didn't mean vue-router installation error
thank you for install vue-router but changes of values ​​in url are not applied.

**Comment by Doctor-wu** [comment]
@mohamadkhalili , could you please provide more details about the issue?

**Comment by Doctor-wu** [comment]
@mohamadkhalili , I noticed that you should use `category.value = xxx` to update the ref. If it is urgent, you can write the code in that way. I will try to figure out if we can update the ref when the reference is not changed.

**Comment by mohamadkhalili** [comment]
Sometimes I feel like I migrated to vue2. 
In general, there is a feeling that reactiveness has not been paid much attention in the implementation.

For example, I encountered a problem somewhere else, and that was that when there were several seRouteQuery values ​​in one file, another change would cause another one to be watched.
Example:
const category = useRouteQuery<Array<string> | undefined>('category', [])
const rangeDate = useRouteQuery<[string, string] | undefined>('rangeDate', undefined)
watch(() => route.query.category, async () => {
    console.log('change category');
})
change value for category and change rangeDate and next can see change category

**Comment by Doctor-wu** [comment]
In fact, Vueuse pays a lot of attention to `reactive`, which is the core concept of Vueuse. `useRouteQuery` uses `customRef` internally to handle reactivity, but this may not cover all cases. We will strive to improve it. Could you please create a new issue to address the problem you mentioned above? @mohamadkhalili

**Comment by mohamadkhalili** [comment]
#3644

**Comment by Doctor-wu** [comment]
Thx, we will address the problem in the new issue~
