### ISSUE TITLE
useTransition v5 improvements

### ISSUE THREAD

**Issue by scottbedard** [vueuse/vueuse#364]
The [`useTransition`](https://vueuse.org/core/useTransition/) function is a good building block, but I often find myself having to stack helpers on top of it. Since we're revisiting functions for 5.0, there are some changes I'd like to make. All of these changes are purely additive, and compatible with the current API.

### ~Controls https://github.com/vueuse/vueuse/pull/362, https://github.com/vueuse/vueuse/pull/397~

It would be great if we could expose some of the underlying utilities. The most obvious things that come to mind are the `pause` and `resume` functions that are being completely wasted right now! Here is what I'm thinking for the current implementation of the controls API.

```ts
const { output, pause, resume } = useTransition(source, { controls: true })
```

> **Withdrawn:** This feature ended up being more complex than anticipated, and I have decided not to implement it at this time. An alternative strategy for pause / resume functionality was described in https://github.com/vueuse/vueuse/pull/397

### Vectors #376

Currently `useTransition` only supports a single value. This is fine for simple use cases where the value is needed for text purposes, but is inadequate for non-trivial use cases like for game rendering. There is no good way to perform multiple transitions at once. For each value added, a separate requestAnimationFrame loop is needed, separate easing functions, separate `onFinished` logic, and so on...

There is no reason our function can't also support a vector as input, and produce a transitioned vector as output. This would give awesome flexibility when building graphs that require X/Y coordinates, working with libraries like Three.js, transitioning RGB values, or really anything where animations share a common duration. Here is the API I think that we should support.

```ts
// the number api will remain unchanged, under the hood this will be treated as [n]
const n = ref(0)

const output = useTransition(n, options) // <- ComputedRef<number>

// and the vector api will support any number of dimensions
const position = ref([x, y, z])

const output = useTransition(position, options) // <- ComputedRef<[number, number, number]>
```

### Enabling / disabling transitions #436

Our transitions right now simply watch the source number, and begin a requestAnimationFrame loop whenever that value changes. This makes it difficult to change that value _without_ transitioning, which there are plenty of situations that call for. It would be nice to also accepted a `Ref<boolean>` that allows us to turn the transition on and off.

```ts
const disabled = ref(true)

const output = useTransition(source, { disabled })
```

### Delayed transitions #386

Right now producing delayed or staggered transitions is a pain because it has to be done via custom easing functions that are idle for some amount of time, or via watchers that implement the delay on separate refs. It would much simpler if we just accepted a `MaybeRef<number>` that allows us to set a timeout between the source changing and the raf loop starting.

```ts
const output = useTransition(source, { delay: 200 })
```

### ~Repeatable transitions~

Often it's necessary to perform the same transition over and over again. Right now this can be achieved with the following pattern, but it is such a common need that it would be nice if it was built in.

```ts
const transition = useTransition(source)

const output = computed(() => source.value ? 1 - (source.value - transition.value) : 0)

source.value++
```

My current thinking is that to create a repeatable transition, we can just accept `{ from, to }` as input.

```ts
const transition = useTransition({ from: 0, to: 1 }, options)

transition().then(() => {
  // transition complete, safe to run again
}).catch(() => {
  // transition interrupted
})
```

> **Withdrawn:** The problem solved by repeatable transitions is fairly different from the one `useTransition` was originally designed for. I've decided it best to implement this feature as its own function.

### Miscellaneous improvements

- ~The preset `linear` transition should use a simple identity function, there is no need to define it using a cubic bezier curve.~
- ~Bump the default duration from `500` to `1000`. When prototyping without defining options, I find half a second is just fast enough to be awkward.~

**Comment by antfu** [comment]
> Controls

Sounds good! 

> Vectors

Besides Array vectors, it will be great to have transitions for objects, which could be incremental (e.g. only update a prop at a time). A bit like [vueuse/motion](https://github.com/vueuse/motion) by @Tahul.

> Repeatable / Enabled

Passing a ref into sounds good, I also think we can use controls to do that. With some extra `restart` `update` functions.

Overall, this sounds like a good improvement for me. If it goes a bit complicated, maybe we can split out some logic into another function and reused it in `useTransition` internally.

/cc @Tahul would love to hear what you think about this as well, thanks

**Comment by scottbedard** [comment]
I think for all of these changes, a proper rewrite of the function is in order. I noticed when implementing vector support that things are starting to get a little complicated and messy. Below is a quick outline of my goals for a maintainable function going forward.

1. **Improve type coverage**<br />Now that we have more than one way to use the function, we need to ensure proper Typescript support. This means writing the necessary overloads and returning strong types. For instance, returning `[number, number]` instead of `number[]`.
2.  **Use a linear progress transition**<br />We can simplify how the output value is calculated by computing it from a linear progress value `0` to `1`. This will make the code more readable, and let us keep the easing function logic together.
3. **Handle `MaybeRef` everywhere**<br />I didn't consider this in the original vector implementation, but we need to be able to handle a static array of reactive values. This will actually be the ideal way to use vectors, because it will let the compiler ensure the length of the vector does not change.

For anyone interested, these changes are currently being implemented here, and will be the next PR.
https://github.com/scottbedard/vueuse/blob/next/packages/core/useTransition/next.ts

**Comment by scottbedard** [comment]
@antfu I'm beginning to implement `{ controls: true }` to expose the `pause` and `resume` functions, and the static types are starting to get pretty complex. We may want to implement type testing. Let me know if you have any thoughts on this matter.
https://github.com/scottbedard/vueuse/blob/2e7f26aab8d0f71d6ba236e051787f233a1bb2c8/packages/core/useTransition/controls.ts#L90-L115

**Comment by antfu** [comment]
@scottbedard sure, go ahead and make the implementation. I can handle the type testing
