### ISSUE TITLE
useVModels的实际结果vueuse本身声明的结果不一致，影响根据是否传入某个prop的判断

### ISSUE THREAD

**Issue by conttonEr** [vueuse/vueuse#3645]
### Describe the bug

根据声明类型，结构useVModels得到的类型声明为：Ref<String | undefined> | undefined，但实际结果却只有前半段：Ref<String | undefined>，没有后半段：|undefined。
造成的结果就是没法根据是否传入某个prop来做判断，当然，如果传了某个值，但传入的值恰好是undefined得手，理因判断为传入了该值，只不过值是undefined。
下面是打印截图。
![image](https://github.com/vueuse/vueuse/assets/72963388/3a374124-be1d-4742-b184-4548524e11c7)

### Reproduction

不需要吧？！

### System Info

```Shell
Binaries:
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Doctor-wu** [comment]
@conttonEr 可以提供一下你的类型代码截图吗, 然后描述一下你预期是怎样的呢?

**Comment by Doctor-wu** [comment]
或许可以这样?
```typescript
preId?.value !== undefined
    ? node?.value
      ? (flag.value = 'Insert')
      : (flag.value = 'Add')
    : (flag.value = 'edit')
```
