### ISSUE TITLE
`tryOnMounted` not compactible with Vue 2

### ISSUE THREAD

**Issue by DarknessChaser** [vueuse/vueuse#3649]
### Describe the bug

The changes in version 10.7.0 https://github.com/vueuse/vueuse/pull/3597 seem to cause useLocalStorage to no longer support vue2.6 and vue2.7.

## vue2.6.14 + @vue/composition-api1.7.2 error message

<img width="782" alt="image" src="https://github.com/vueuse/vueuse/assets/22089140/01976bc8-66f3-4ab9-ad79-a5b966977d87">

see https://stackblitz.com/edit/vue2-vue-cli-a9cecv?file=src%2Fcomponents%2FHelloWorld.vue

## vue 2.7.16-beta.1 error message

<img width="770" alt="image" src="https://github.com/vueuse/vueuse/assets/22089140/5a703f6b-9f0b-4ba8-a982-3ba47714ad0e">

see https://codesandbox.io/p/sandbox/vue2-createreusabletemplate-qg4jxm?file=%2Fsrc%2FApp.vue&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq35117p00063b6hk9igf2y2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq35117o00023b6h0r5ithxg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq35117o00033b6hy44e1bro%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq35117o00053b6h3yb2a5t2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq35117o00023b6h0r5ithxg%2522%253A%257B%2522id%2522%253A%2522clq35117o00023b6h0r5ithxg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq535zdj00023b6hj4upmz4l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq535zdj00023b6hj4upmz4l%2522%257D%252C%2522clq35117o00053b6h3yb2a5t2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq35117o00043b6h92eun3ax%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq35117o00053b6h3yb2a5t2%2522%252C%2522activeTabId%2522%253A%2522clq35117o00043b6h92eun3ax%2522%257D%252C%2522clq35117o00033b6hy44e1bro%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq35117o00033b6hy44e1bro%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Reproduction

see https://stackblitz.com/edit/vue2-vue-cli-a9cecv?file=src%2Fcomponents%2FHelloWorld.vue

### System Info

```Shell
System:
    OS: macOS 14.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 39.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.volta/tools/image/node/14.21.3/bin/node
    npm: 6.14.18 - ~/.volta/tools/image/npm/6.14.18/bin/npm
  Browsers:
    Chrome: 120.0.6099.109
    Edge: 120.0.2210.61
    Safari: 17.1
    Safari Technology Preview: 17.4
  npmPackages:
    @vueuse/core: ^10.7.0 => 10.7.0 
    @vueuse/math: ^10.2.1 => 10.2.1 
    vue: 2.6.11 => 2.6.11
```

### Used Package Manager

npm

### Validations

- [X] #3654
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DarknessChaser** [comment]
It seems to be caused by the different behavior of the setup function.

**Comment by Doctor-wu** [comment]
That appears to be a problem with the `tryOnMounted` hooks instead of `useLocalStorage`. I will attempt to resolve it.

**Comment by Doctor-wu** [comment]
As a deeper investigation, it's `vueDemi::isVue3` flag bug
<img width="749" alt="CleanShot 2023-12-15 at 10 53 11@2x" src="https://github.com/vueuse/vueuse/assets/44631608/43d33f31-f24d-4307-8f69-dcb17bd06233">

**Comment by Doctor-wu** [comment]
@DarknessChaser This works well on my local, did you get some errors in your local repo or some what? It seems that `vue-demi`'s `postInstall` didn't trigger in CodeSandbox
<img width="745" alt="CleanShot 2023-12-15 at 15 32 01@2x" src="https://github.com/vueuse/vueuse/assets/44631608/045862ed-b092-460e-848c-8ef2d1edecc1">

**Comment by DarknessChaser** [comment]
@Doctor-wu 首先感谢您的帮助！

实际上我用的是 vue2.6.11+@vue/composition-api1.7.2的组合。我更新了https://stackblitz.com/edit/vue2-vue-cli-a9cecv?file=src%2Fcomponents%2FHelloWorld.vue上的例子。

![image](https://github.com/vueuse/vueuse/assets/22089140/a9cec046-37c1-48c3-b10e-61a00d4824d6)
这段代码执行了两次。

第一次 
![image](https://github.com/vueuse/vueuse/assets/22089140/541e3e05-ff13-452d-9417-2132f4f2f2fb)

第二次
![image](https://github.com/vueuse/vueuse/assets/22089140/a6c4df27-016a-46a9-804f-52a5f6482c24)
proxy消失了……

![image](https://github.com/vueuse/vueuse/assets/22089140/14185cd6-f448-4a30-b7db-d7ab50c4b38d)
vue2 or 3的判断看上去工作正常
![image](https://github.com/vueuse/vueuse/assets/22089140/73f2ceb3-01ab-480f-9b32-0bdb10a06556)

**Comment by Doctor-wu** [comment]
@DarknessChaser Could you show me your repo with me so that I can figure out what's actually going on because the reproduction's vue-demi appears to be the wrong vue version.

**Comment by Doctor-wu** [comment]
OK, it appears to be the bug taken by https://github.com/vueuse/vueuse/pull/3185/commits/1b9673a2782178bf45542f874dc592c223281d06. It returns `instance.proxy` in Vue2 but an instance with a`proxy` field would be used in `@vue/composition-api`.

**Comment by DarknessChaser** [comment]
> OK, it appears to be the bug taken by [1b9673a](https://github.com/vueuse/vueuse/commit/1b9673a2782178bf45542f874dc592c223281d06). It returns `instance.proxy` in Vue2 but an instance with a`proxy` field would be used in `@vue/composition-api`.

good news!
It seems to be working normally on vue2.7!

bad news
vue2.6 still has problems
![image](https://github.com/vueuse/vueuse/assets/22089140/8d918281-9499-41ad-93e5-f30489beeba0)

**Comment by Doctor-wu** [comment]
> > OK, it appears to be the bug taken by [1b9673a](https://github.com/vueuse/vueuse/commit/1b9673a2782178bf45542f874dc592c223281d06). It returns `instance.proxy` in Vue2 but an instance with a`proxy` field would be used in `@vue/composition-api`.
> 
> good news! It seems to be working normally on vue2.7!
> 
> bad news vue2.6 still has problems ![image](https://private-user-images.githubusercontent.com/22089140/298055009-8d918281-9499-41ad-93e5-f30489beeba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTEyNDQsIm5iZiI6MTcwNTg5MDk0NCwicGF0aCI6Ii8yMjA4OTE0MC8yOTgwNTUwMDktOGQ5MTgyODEtOTQ5OS00MWFkLTkzZTUtZjMwNDg5YmVlYmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMzU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNjUyYjU2ZmRmNTA3ZWVlNTZiNjBjNDRmYjkwZDZlZGI1YzY4ZTNhNmE1NTQyNGJlMDY1NzQ1NjU4MjQxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zLxU101vyMMC7B7DAco4k7yi7bgr6kAMfskFeOi75c8)

Did you experience this error in your local repo? It seems `vue-demi` didn't work well in this reproduction.
