### ISSUE TITLE
useGamepad does not update gamepads on change of state and does not provide gamepad index

### ISSUE THREAD

**Issue by AntoninRousset** [vueuse/vueuse#3652]
### Describe the bug

The reactive array of gamepads returned by `useGamepad` is not updated when buttons are pressed nor axes are moved.
Furthermore, `gamepad.index` is always undefined.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-w4fyuq?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 6.1 Gentoo Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 5.11 GB / 15.27 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.8.1 - /usr/bin/npm
    pnpm: 8.12.0 - /usr/bin/pnpm
  npmPackages:
    @vueuse/core: ^10.6.1 => 10.7.0
    @vueuse/nuxt: ^10.6.1 => 10.7.0
    vue: ^3.3.8 => 3.3.10
  Browsers:
    Firefox: 115.5.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ysmilda** [comment]
Running into the same issue. After the initial update the inputs are not updated anymore. This happens in the [demo](https://vueuse.org/core/useGamepad/#demo) and locally.
