### ISSUE TITLE
Typescript type error with syncRef when one value is readonly

### ISSUE THREAD

**Issue by VividLemon** [vueuse/vueuse#3669]
### Describe the bug

There is a weird issue when using syncRef with readonly values

```ts
import {syncRef} from '@vueuse/core'
import {ref} from 'vue'

const i = ref<readonly string[]>([])
const b = ref<string[]>([...i.value])

syncRef(i, b, {
  direction: 'ltr',
  transform: (v) => [...v],
})
```
syncRef fails in this code stating "v" is type unknown. "v" should be correctly inferred to by of type readonly string[], and subsequently the code should have no issues as the transform is making a copy

### Reproduction

(read desc)

### System Info

```Shell
System:
    OS: Linux 6.6 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 19.39 GB / 30.50 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.7.0 - /run/user/1000/fnm_multishells/40622_1703374850077/bin/node
    npm: 10.1.0 - /run/user/1000/fnm_multishells/40622_1703374850077/bin/npm
    pnpm: 8.6.5 - ~/.local/share/pnpm/pnpm
    bun: 1.0.2 - ~/.bun/bin/bun
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Doctor-wu** [comment]
@VividLemon  You should use transform like this
```typescript
    syncRef(i, b, {
      direction: 'ltr',
      transform: {
        ltr: (v) => [...v]
      },
    })
```
