### ISSUE TITLE
Non reactive composable (useCookies)?

### ISSUE THREAD

**Issue by kissu** [vueuse/vueuse#3682]
### Describe the bug

Using `useCookies` directly into a component is working perfectly fine. ✅ 

```vue
<template>
<button @click="cookies.set('capuccino', 'works 🍪')">set cookie</button>
<div>cookie? {{ cookies.get('capuccino') }}</div>
<button @click="cookies.remove('capuccino')">remove cookie</button>
</template>

<script setup lang="ts">
import { useCookies } from '@vueuse/integrations/useCookies'

const cookies = useCookies([], { autoUpdateDependencies: true })
</script>
```

Wrapping it in a composable and it doesn't anymore. :x:
Not sure if I'm missing something really basic here? 🤔 

```html
<template>
<button @click="set('capuccino', 'works 🍪')">set cookie</button>
<div>cookie? {{ get('capuccino') }}</div>
<button @click="remove('capuccino')">remove cookie</button>

<button @click="number++">big one {{ number }}</button>
</template>

<script setup lang="ts">
const { get, set, remove } = useCookies()

const number = ref(0)
</script>
```

I saw that if I add/remove a cookie, **then** click a button to update some unrelated ref
```html
<button @click="number++">big one {{ number }}</button>
```
I can see that my `get('capuccino')` is actually updated. Until then, it looks like it's not reactive at all.

Meanwhile, I can see that the function works well (by inspecting the cookie in the devtools).

The composable is quite simple too
```js
export function useCookies() {
  function get(name: string) {
    const { get } = VueUseCookies([], { autoUpdateDependencies: true });
    return get(name)
  }

  function set(name: string, value: string) {
    const { set } = VueUseCookies([], { autoUpdateDependencies: true })
    return set(name, value)
  }

  function remove(name: string) {
    const { remove } = VueUseCookies([], { autoUpdateDependencies: true })
    return remove(name)
  }

  return { get, set, remove }
}
```

As a side note, [Nuxt's useCookie](https://nuxt.com/docs/api/composables/use-cookie) is perfectly reactive with the same workflow. But I need both of them, the one from Nuxt and from VueUse. 🤗 

### Reproduction

The reproduction URL is not really relevant since we cannot create cookies on either Codesandbox or Stackblitz from what I saw. 😞 
https://stackblitz.com/~/github.com/kissu/vueuse-cookie-nuxt3

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 52.64 GB / 62.70 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.9.2 - ~/.local/share/pnpm/pnpm
    bun: 1.0.9 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.109
    Chrome: 119.0.6045.159
  npmPackages:
    @vueuse/integrations: ^10.6.1 => 10.6.1 
    vue: ^3.3.8 => 3.3.9
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by OsamaHaikal** [comment]
Whenever you call useCookies(), it has its own touches ref that tracks reactivity. Creating multiple instances means you’re not sharing that same touches ref, so the reactivity doesn’t carry over.

can you explain why you need this wrapper composable .. if this is a must do you think this can solve thet issue for you?

```export function useCookies() {
  const cookies = VueUseCookies([], { autoUpdateDependencies: true })

  // reuse the same instance methods every time
  return {
    get: cookies.get,
    set: cookies.set,
    remove: cookies.remove,
  }
}```

**Comment by ilyaliao** [comment]
I think you can try [createSharedComposable](https://vueuse.org/shared/createSharedComposable)？
