### ISSUE TITLE
useElementVisiblity threshold is not configurable

### ISSUE THREAD

**Issue by rikzwarthoff** [vueuse/vueuse#3709]
### Describe the bug

useElementVisiblity set a default threshold of 0 
Please see comments here: https://github.com/vueuse/vueuse/pull/3308

### Reproduction

https://github.com/vueuse/vueuse/pull/3308

### System Info

```Shell
vueuse 10.4.0 and up
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Archetipo95** [comment]
There is a typo in the title: change it to `useElementVisibility threshold is not configurable`
Also linked to #3525
