### ISSUE TITLE
[Bug] useImage does not load the image when the "src" is changed reactively

### ISSUE THREAD

**Issue by javipuche** [vueuse/vueuse#3717]
### Describe the bug

If you go to the link with the example and click "change url2," the image won't load. However, if you set '/photo.jpeg' as the value for url2 and click again, it will work.

### Reproduction

https://stackblitz.com/edit/vue3-script-setup-with-vite-bmmsr6?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 124.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.14.1 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 120.1.61.116
    Safari: 15.5
  npmPackages:
    @vueuse/core: 10.7.1 => 10.7.1 
    @vueuse/integrations: 10.7.1 => 10.7.1 
    vue: 3.4.10 => 3.4.10
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 17359898647** [comment]
This is because your configuration item is not reactive, so the function cannot listen, you can try this，https://stackblitz.com/edit/vue3-script-setup-with-vite-qz8mwg?file=src%2FApp.vue

**Comment by javipuche** [comment]
Oh! Thank you @17359898647! Sorry for reporting a false bug.
