### ISSUE TITLE
Docs navigation/overlays not working

### ISSUE THREAD

**Issue by ChrisGV04** [vueuse/vueuse#3721]
### Describe the bug

If i try to use the search bar or dropdown navigation items from the header of vueuse.org, they don't work. I tried on multiple devices and browsers but it doesn't seem to work anywhere. On mobile I can't even open the navigation menu.

This might be an issue with the overlays used site-wide since I can't get any popup, slideover or dropdown to open.

### Reproduction

https://vueuse.org

### System Info

```Shell
Not relevant. Issue on live vueuse.org website.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Can you check it agian now?

**Comment by ChrisGV04** [comment]
Hi @antfu 
It's working again! Thank you very much 🚀
