### ISSUE TITLE
useWindowSize doesn't work with computed

### ISSUE THREAD

**Issue by StreakingMan** [vueuse/vueuse#3745]
### Describe the bug

I'm try to wrap window size as computed value, just like

```javascript
const { width, height } = useWindowSize()
const computedWindowHeight = computed(()=>{
  // other stuff
  return height.value
})
```

and browser seems crashed, keep blank page, can't see any log. Am I using it incorrectly or some bugs in useWindowSize?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-4duith?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 49.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.9.0 - ~/Library/pnpm/pnpm
    bun: 1.0.23 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.234
    Edge: 121.0.2277.83
    Safari: 17.0
  npmPackages:
    @vueuse/components: ^10.7.2 => 10.7.2 
    @vueuse/core: ^10.6.1 => 10.7.2 
    vue: ^3.4.10 => 3.4.15
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by huiliangShen** [comment]
You need `import { computed } from 'vue'`

**Comment by StreakingMan** [comment]
> You need `import { computed } from 'vue'`

oh, I'm so stupid 😭

**Comment by StreakingMan** [comment]
But what I can confirm is that there were no relevant errors in my project, maybe there was a problem in another part.
