### ISSUE TITLE
There is ambiguity in the `once` parameter of the `whenever` function

### ISSUE THREAD

**Issue by chizukicn** [vueuse/vueuse#3748]
### Clear and concise description of the problem

Since Vue3.4, Vue has added the `once` parameter of `watch`, and the `whenever` function inherits this parameter.

```ts
const isReady = ref(false);
whenever(isReady,()=>{
   console.log("ready~")
},{ 
   once: true
})
```
When the condition is updated to false for the first time, the callback function will not be called.

### Suggested solution

Can we implement a `once` parameter in `whenever` to override the `once` of `watch`?

For example:
```ts
export function whenever<T>(source: WatchSource<T | false | null | undefined>, cb: WatchCallback<T>, options?: WatchOptions) {
  const stop = watch(
    source,
    (v, ov, onInvalidate) => {
      if(options.once)
        stop()
      if (v)
        cb(v, ov, onInvalidate)
    },
   {
      ...options,
      once: false
   },
  )
  return stop
}

```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by noook** [comment]
That seems like a nice solution to assure backward compatibility for Vue < 3.4

**Comment by antfu** [comment]
Yeah I think overriding makes sense as the `once` should be relevant to `whenever` rather than in the internal watch
