### ISSUE TITLE
bug with useDraggable 

### ISSUE THREAD

**Issue by neu-yuyang** [vueuse/vueuse#3755]
### Describe the bug

when i use useDraggable with a img element, or a div inner with a img tag, the element is not draggable; you need to set the img tag attribute 'draggable' to false to resolve this bug;

### Reproduction

https://stackblitz.com/edit/vitejs-vite-wdwgnn/?file=src%2FApp.vue

### System Info

```Shell
chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mnenie** [comment]
Hello @neu-yuyang ! If it's still relevant to you -> you can set the  `preventDefault: true` in options
so without you still have this bug, but it is resolves by my pr, where by default it is forbidden to drag images with the `useDraggable` without  `preventDefault: true`
