### ISSUE TITLE
useUrlSearchParams is not reactive between different instances

### ISSUE THREAD

**Issue by Eternal-Rise** [vueuse/vueuse#3759]
### Describe the bug

const query = useUrlSearchParams('history');
const query2 = useUrlSearchParams('history');

query.foo = '1';
// query2 will not be updated

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jyzhw1/?file=src%2FApp.vue,package.json

### System Info

```Shell
does not matter
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stephenhebert** [comment]
This is my workaround:
```
// workaround for https://github.com/vueuse/vueuse/issues/3759

import { useUrlSearchParams as useVueUseUrlSearchParams } from '@vueuse/core'

const paramsInstances = new Map<string, ReturnType<typeof useVueUseUrlSearchParams>>()

export function useUrlSearchParams(preserve = true) {
  const key = window.location.pathname
  if (!preserve || !paramsInstances.has(key))
    paramsInstances.set(key, useVueUseUrlSearchParams())

  return paramsInstances.get(key)!
}
```

**Comment by Akryum** [comment]
My workaround:
https://gist.github.com/Akryum/d22899ba7b380918062c6fa65ee87f10

**Comment by nicooprat** [comment]
Recently used this package that also allows transforming values when setting/getting it from queries: https://github.com/Djaler/vue-use-route-query

**Comment by BenJackGill** [comment]
I'm using `useUrlSearchParams` inside a Pinia store to avoid this problem. If implemented in a composable, a new instance of the parameters is created each time the composable is invoked (e.g., in a component or another composable). Using it in a store is my workaround.

**Comment by OrbisK** [comment]
should be possible with https://vueuse.org/shared/createSharedComposable/#createsharedcomposable

if not please reopen this issue :)
