### ISSUE TITLE
How to solve the problem of sharing the same event on nodes with onClickOutside

### ISSUE THREAD

**Issue by parlay96** [vueuse/vueuse#3777]
### Clear and concise description of the problem

![image](https://github.com/vueuse/vueuse/assets/32978177/1e4c6fa9-3b4d-43f2-b6ca-e59df49579b2)
![image](https://github.com/vueuse/vueuse/assets/32978177/e6517b43-53a1-4580-99eb-cc4f6f5d7ab0)
My component is used multiple times on a page, resulting in event conflicts and binding multiple events. This can cause me to click Yes, but I don't know who I clicked on

### Suggested solution

How to solve it

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by OrbisK** [comment]
Maybe I'm wrong, but if you have two elements and a clickoutside on both, then two events should be triggered unless you press one of the elements. So that we can help, a reproduction would be very helpful

**Comment by OrbisK** [comment]
i can't reproduce the problem:
https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgqFQAHio2RU1iMAF4ADogaSVJDSAsAPjz5hTKgAEp4vEk6gYqJWU6nhhniBWq23O1nELmC0WOCXGuXW9W6xFEpEmy2q+3O9226UAglsGWAPIBXU0FSeWg2aTt1f9eRl57C6RESt0LV1aQqYAqeTioKwbfSXdpA41DizFQAHIHRuTk6kQQDb3vDhH2fbMVF-Ix-zwICFkg7BKxmbBkEfYcSxUHN+yMbRsFICJ7Ew+QcPiYtEGkZpCOzEiyIMCiMOwV93xgT9v20PC6MYfcPBVAiyxULC2CDSYvHgbRiUYRBhOkew2M4ugPx3OgaD42j6MExSj1E8SqKlRBpNYWTGn0pSVMrRlmElOoM1wVIo3IGNC1oMAEyTXh02yCdahVfMQDweRWALCdSngEKgngPoKAAVlJUk3EqGA0CodKkpSyKqyMINNhCgA-YyDDylNUk2aQQu4FVEA4CqVDAEKxxAKKnIakL-34GgW3ajcJ1TZBIHMKqaoLAAWTZypAMtgGfYhDFUA4DnbEaIEGhcNrGz0JpYFCso4DK4oSgBOFK0uOtBvGgYIQhygsVDwELpAoNqywAWXYSEFpUBNSk8BC1ruUbu0XbIL2YcRJBkIgaADbBEAABX-QZtGACcAc8NAVABaRJGweBGAnJaDHIXGADlSDwQGOBJ7ADnsRlVqAA

please reopen the issue with an reproduction or additional information :)
