### ISSUE TITLE
useFileSystemAccess updateData fails

### ISSUE THREAD

**Issue by PhE** [vueuse/vueuse#3779]
### Describe the bug

Calling updateData() on a modified file fails:
```
filesystem:1 Uncaught (in promise) DOMException:
The requested file could not be read, typically due to permission problems
that have occurred after a reference to a file was acquired.
```
Note that if the underlying file is not modified, updateData() does not fail ... but is useless.

### Reproduction

[This commit](https://github.com/vueuse/vueuse/commit/57011c4dceb9c7ad3806e176818af9429b704124) adds an `update` button to the demo page to reproduce the bug 

1. go to the `http://localhost:5173/core/useFileSystemAccess/` page
2. click `Open` and select any `dummy.txt` file
3. click `Update` button, no error
4. modify the underlying `dummy.txt`, save it
5. click `Update` button, the erro occurs

### System Info

```Shell
System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (16) x64 AMD Ryzen 7 7840U w/ Radeon 780M Graphics
    Memory: 17.15 GB / 28.11 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.13.0 - /usr/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 9.2.0 - /usr/bin/npm
    pnpm: 8.15.1 - ~/src/vueuse/node_modules/.bin/pnpm
    bun: 1.0.6 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 121.1.62.156
    Chrome: 121.0.6167.160
  npmPackages:
    @vueuse/core: workspace:* => 10.7.2 
    @vueuse/integrations: workspace:* => 10.7.2 
    @vueuse/math: workspace:* => 10.7.2 
    @vueuse/rxjs: workspace:* => 10.7.2 
    @vueuse/shared: workspace:* => 10.7.2 
    vue: ^3.4.15 => 3.4.15
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ilyaliao** [comment]
Closed via #3780
