### ISSUE TITLE
useBreakpoints: onMounted is called when there is no active component instance to be associated with.

### ISSUE THREAD

**Issue by moritzkalwa** [vueuse/vueuse#3785]
### Describe the bug

When using the useBreakpoints package this warning gets thrown.

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2QAOuYVPBJFQALzpkAAPxqUQoMwM2YgYAoABZC5mVCowAnuAWQDMVTZpOXu4h6sFaMhe12OA2s7p2+JrDZx03air23h5Kw5yoAHyNlTJyV1NO4VIqBOlTztgAahZUaGIhnI7eJl+Gm6zO9Ye7MibSx9PhYAmpfr1vRB20aR9nybZM4xbT8VGICg6CMds6GQAE8EMAxC3ApsXFKKAt2TYYoITVJnwItNiHXZ5hWkIg6C1OppA1N8OH3GCjA4WYVAAckmYZdxYj9UijcguMzOjtQ4RjgBULEwACEEVAOGoOLwbiFlErJ6MklRpLxAAhawIBgbUzGkZwlPYziuIdG5OTqRANMzTtkEY8pECMkyVWcPMdK3Ag01IPA0BUABWELSUYFRRg6WtJnaAB2ELrDwLcEw4JBguJMkIqi4YVAANgADkmRLkq3TY0oylRiXCnLooATnaEqktoTMDgAbkzJz5BcnSVGQNDpXqJSfP0wzjNYUzkG0NyPMmrz7E67BuuwXrkNQ9CVB82T5KobRtEcPN136wagw4bRC38uhAsLewoyAxbGWYfjWKE6MQxAIjPxTcitwXaQlxXNdSngdsgngPoKFqtxKhgNAqFhqHSVJNcjCDTZ2xLCs11STYAcLbhRzXMAQOBvd+3bDj+BoKhxyw5NkEgcxcfxkBawqzDgGkm8DFUA4DgIxmIGwemheZz1WYGmGODh8HIfq5Hpbh7xoGCEIkcvPB2x7UCQHXABZdhIS5o8IBPSt+cFpnSOGcjKOYadfiIGgA2wRAAAUOMGbRgFSs3PGCgFpEkbB4EYLcefIYKADlApPDhw+wA57EZfmgA

### System Info

```Shell
System:
    OS: macOS 13.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 102.10 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.asdf/installs/nodejs/20.11.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.7.0-1 - ~/.asdf/shims/pnpm
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 16.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zekunjin** [comment]
Maybe `smaller` function ( or some else method like this ) can only be used at the top level of `setup` component?

I found this method used `isSupported` util inside, and it called `onMounted` hook. This util is used in `useMediaQuery` for check if current environment support `checkMedia` funtion.

Try this way:

```vue
import Coordinate from './Coordinate.vue'
import { computed } from 'vue'
import { useBreakpoints } from '@vueuse/core'

const breakpoints = {
  medium: 550, // 34.375rem
  large: 1100, // 68.75rem
  xlarge: 1500, // 93.75rem
};

const _b= useBreakpoints(breakpoints);
const xs = _b. smaller("medium");

const isSmaller = computed(() => xs.value);
```

Or directly use the `xs` variable.

It seems necessary to add a tip in documents for avoid this warning.

**Comment by rasmus0201** [comment]
> Maybe `smaller` function ( or some else method like this ) can only be used at the top level of `setup` component?
> 
> I found this method used `isSupported` util inside, and it called `onMounted` hook. This util is used in `useMediaQuery` for check if current environment support `checkMedia` funtion.
> 
> Try this way:
> 
> ```
> import Coordinate from './Coordinate.vue'
> import { computed } from 'vue'
> import { useBreakpoints } from '@vueuse/core'
> 
> const breakpoints = {
>   medium: 550, // 34.375rem
>   large: 1100, // 68.75rem
>   xlarge: 1500, // 93.75rem
> };
> 
> const _b= useBreakpoints(breakpoints);
> const xs = _b. smaller("medium");
> 
> const isSmaller = computed(() => xs.value);
> ```
> 
> Or directly use the `xs` variable.
> 
> It seems necessary to add a tip in documents for avoid this warning.

It seems wrong that you can't use the API either way IMO, and nothing (naming etc) indicates that it shouldn't work. And it won't be responding to reactivity changes, since it won't work inside of a computed. 

E.g. something like this won't work: 
``` 
const props = withDefaults(defineProps<Props>(), {
  breakpoint: "md",
});

const breakpoints = useBreakpoints(Breakpoints);
const useSplitTables = computed(() => breakpoints.smaller(props.desktopBreakpoint).value);
```

if `props.breakpoint` changes your way doing it won't work (maybe you could do something with a watcher?). And the above will cause an error because of the `onMounted` hook.

**Comment by zekunjin** [comment]
You are right, there is nothing indicates that it shouldn't work. It seems has been fixed by this pr: [fix(useMounted): hold the instance](https://github.com/vueuse/vueuse/commit/2f66e6f8b68933feb3f4ae3b60ccb4478ee5794b)

I've just come to know that `onMounted` has the second parameter for specifying the instance.

Thank you for reply.
