### ISSUE TITLE
useMediaControls

### ISSUE THREAD

**Issue by wheatjs** [vueuse/vueuse#379]
Just thought of this, but I have not completely thought through the API yet, since I wanted to get some feedback on it first. I guess the general idea would be something like a `useVideo` function(maybe it could be more general like `useMedia` not sure). Generally I think it could look something like 

```ts
import { ref } from 'vue'
import { useVideo } from '@vueuse/core'

const video = ref<HTMLVideoElement>()
const { isPlaying, currentTime, duration, play, pause } = useVideo(video)
```

Currently most of the html5 video functionally is implemented through events, so I thought it might be nice if we had a reactive api for it. Let me know what you think of this idea and if you have any API suggestions. If you approve, I'll get a PR going 😄

**Comment by antfu** [comment]
Sounds cool. Let's see the PR!

About the naming, wdyt for `useVideoControls()`?

**Comment by jacobclevenger** [comment]
`useVideoControls` sounds good, although there is also the `<audio>` element so we could also have either both `useVideoControls` and `useAudioControls` or just `useMediaControls`

**Comment by antfu** [comment]
Let's see how much works needed for supporting each. If there are a lot of shared logics sure we can have `useMediaControls`, otherwise it's better to implement separately and make `useMediaControls` a universal wrapper for them.

**Comment by jacobclevenger** [comment]
So far I've gotten both audio and video to work under a singular function with no changes, so I think we can keep them under just `useMediaControls`. According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs), they use the same API and only have a few differences, like the `poster` property for example, so I think we won't need separate functions
