### ISSUE TITLE
`breakpointsTailwind` from the `useBreakpoints` composable is not auto-imported in Nuxt

### ISSUE THREAD

**Issue by stefanobartoletti** [vueuse/vueuse#3790]
### Describe the bug

Like the title says, `breakpointsTailwind` from the `useBreakpoints` composable is not auto-imported in Nuxt.

As you can see from the following StackBlitz environment, I've correctly set up the Nuxt module in the project. 
This is the only problem that I've noticed, every composable is auto-imported as expected (even `useBreakpoints`), but `breakpointsTailwind` must be manually imported or an error is returned.

I'm not 100% sure whether this is an actual bug, or it is how it is supposed to work (as, from what I understand, `breakpointsTailwind` is not composable in a strict sense), but it looks like an inconsistent behavior so I thought of reporting it.

I think it would be nice if it could be auto-imported as well. But if the present behavior is how it is supposed to work, an explicit note in the docs about it could help to understand the situation better.

### Reproduction

https://stackblitz.com/edit/github-vkrsiz?file=app.vue

### System Info

```Shell
I cannot run `npx envinfo --system --npmPackages '{vue,@vueuse/*}' --binaries --browsers
` on stackblitz.

Feel free to ask for more info if needed.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zekunjin** [comment]
Nuxt auto imports depends on [unimport](https://github.com/unjs/unimport), and vueuse builtin presets does not includes `breakpointsTailwind`, because breakpoints are deliberately not auto-imported.

Maybe this pr can helps you. [feat: update vueuse breakpoints preset](https://github.com/unjs/unimport/pull/328#issuecomment-1952588517)

**Comment by antfu** [comment]
This is intentional: https://github.com/unjs/unimport/pull/328#issuecomment-1952297545

Happy to update the docs mentioning it if anyone wants to send a PR. Thanks!

**Comment by zekunjin** [comment]
I'm not quite sure about which functions are not auto-imported >_<.

It seems that not only the functions start with `use` are auto-imported, like `onClickOutside` is also included.

Therefore, I'm uncertain about how to describe this in the documents. Do you have any suggestions?

**Comment by stefanobartoletti** [comment]
Thanks for the replies.

I'm available to improve the docs for the `useBreakpoints` composable if needed, but I don't want to step into it if @zekunjin is already working on it. Let me know.

**Comment by zekunjin** [comment]
I haven't made any changes to the docs yet. I would be very grateful if you could improve it.

**Comment by stefanobartoletti** [comment]
Fine, I'll do this then. 
I'm quite busy with a project, but I think that I can work on it this weekend
