### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'mounted')

### ISSUE THREAD

**Issue by Ttou** [vueuse/vueuse#3797]
### Describe the bug

when upgrade @vueuse/nuxt to 10.8.0, cause nuxt bridge error

<img width="2100" alt="image" src="https://github.com/vueuse/vueuse/assets/4298437/a6db9779-28fc-4156-b492-24ce9ee8a02f">

### Reproduction

https://stackblitz.com/~/github.com/Ttou/vueuse-nuxt-issue

### System Info

```Shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M2
    Memory: 2.91 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/Library/Caches/fnm_multishells/8660_1708431704282/bin/node
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/8660_1708431704282/bin/npm
    pnpm: 8.15.3 - /opt/homebrew/bin/pnpm
  Browsers:
    Safari: 17.3.1
  npmPackages:
    @vueuse/core: 10.8.0 => 10.8.0 
    @vueuse/nuxt: 10.8.0 => 10.8.0 
    vue: ^2.7.16 => 2.7.16
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sigtm** [comment]
For context, this appears to have been introduced by passing `instance` to `onMounted`, in this commit:

https://github.com/vueuse/vueuse/commit/2f66e6f8

I see this fix has been merged, but it does not work on my end:

https://github.com/vueuse/vueuse/commit/ee2977b72bfb1be68c0c2ad555fbd2659968a9b2

However, if I change `null` to `undefined`, as in `isVue2 ? undefined : instance`, it seems to work. I don't know enough about Vue internals to know if that breaks something else though, so I will have to leave it to someone more capable.
