### ISSUE TITLE
useActiveElement() not working

### ISSUE THREAD

**Issue by imvimol** [vueuse/vueuse#3799]
### Describe the bug

I am creating the shortcut using useMagicKeys() and useActiveElement() from vueuse; 

const activeElement = useActiveElement();
    const notUsingInput = computed(
      () =>
        activeElement.value?.tagName !== 'INPUT' &&
        activeElement.value?.tagName !== 'TEXTAREA',
    );
    const keys = useMagicKeys();
    const questionMarkPressed = keys['?'];
    whenever(logicAnd(questionMarkPressed, notUsingInput), () => {
      console.log("This is ? press outside the textarea");
    });

i'm trying to use this logic to create shortcut of " ? " when we press " ? " outside the textarea something like that. But It doesn't seem work for me using this logic. Can someone help me ?

### Reproduction

useMagicKeys() and useActiveElement()

### System Info

```Shell
useMagicKeys() and useActiveElement()
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jaketig** [comment]
This should be fixed now via #3815.

Here's a working example sample:

https://stackblitz.com/edit/vitejs-vite-qhfqvb?file=src%2FApp.vue

**Comment by ilyaliao** [comment]
Closed via #3815
