### ISSUE TITLE
useMounted does not work in vue2.7

### ISSUE THREAD

**Issue by yanbowe** [vueuse/vueuse#3803]
### Describe the bug

由于getCurrentInstance()在vue2.7和vue3获取的instance实例结果不同，在vue2.7中 onMounted第二个参数的值应该为instance?.proxy，设置为instance会导致报错，由于vue-demi中的onMounted的参数类型不支持ComponentPublicInstance，先设置为null保证在vue2.7中可以正常运行

### Reproducti
on

https://github.com/vueuse/vueuse/releases/tag/v10.8.0

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 54.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 16.0
  npmPackages:
    @vueuse/core: 10.8.0 => 10.8.0 
    vue: 2.7.16 => 2.7.16
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dylanFdvhuset** [comment]
+1 when using useWindowSize

**Comment by begedin** [comment]
After updating to 10.9.0, i still seem to be experiencing it with `useVirtualList`

```
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().
```

```
      at warn$2 (node_modules/vue/dist/vue.common.dev.js:5054:21)
      at Object.onMounted (node_modules/vue/dist/vue.common.dev.js:3912:13)
      at useMounted (node_modules/@vueuse/core/index.cjs:503:13)
      at useSupported (node_modules/@vueuse/core/index.cjs:511:21)
      at useResizeObserver (node_modules/@vueuse/core/index.cjs:2523:23)
      at useElementSize (node_modules/@vueuse/core/index.cjs:2681:27)
      at useVirtualListResources (node_modules/@vueuse/core/index.cjs:6763:16)
      at useVerticalVirtualList (node_modules/@vueuse/core/index.cjs:6889:21)
      at useVirtualList (node_modules/@vueuse/core/index.cjs:6747:123)
```

**Comment by yanbowe** [comment]
> > 先设置为null保证在vue2.7中可以正常运行
> 
> `onMounted` 的第二个参数设置为 null 似乎并没有使 `useMounted` 生效，始终会报 warning。 https://github.com/vuejs/vue/blob/bed04a77e575d6c4c1d903f60087dca874f7213e/src/v3/apiLifecycle.ts#L10

应该设置为void 0

**Comment by xsfour** [comment]
准确的是不是还是应该传`instance?.proxy`？类型用`as`来规避是不是就好了

**Comment by nguyentranchung** [comment]
useDark, useClipboard still have problem

[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().

**Comment by Ttou** [comment]
useFullscreen still have problem

**Comment by kooriookami** [comment]
When to release?
