### ISSUE TITLE
useTimeout to return Pausable&Stoppable and being able to pause/resume timer

### ISSUE THREAD

**Issue by marcoarruda** [vueuse/vueuse#3807]
### Clear and concise description of the problem

I've been implementing a composable in my Vue3 project that allows using a timeout that can be paused and resumed with the time left. I tried using useTimeout in the first place, but I can only `stop` and re`start` it again, which restarts the timer, do not continue from where it stopped

### Suggested solution

Rewrite the existing `useTimeout` to return a `Pausable & Stoppable` instead of `Stoppable` type

### Alternative

A **new method** `usePausableTimeout` to return `Pausable & Stoppable`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ilyaliao** [comment]
As issue #3889 is closed, I will also close this issue. Thank you again for your contributions.
