### ISSUE TITLE
usePrecision - unexpected result with negative values

### ISSUE THREAD

**Issue by Arizy** [vueuse/vueuse#3816]
### Describe the bug

When I use the `usePrecision` with negative reactive data, the returned result is not as expected. When the value I set is -1.035, the result I expect is -1.04.
```ts
const negative = ref(-1.035);
const negativeResult = usePrecision(negative, 2); // -1.03
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-m7xgfd?file=src%2FApp.vue

### System Info

```Shell
does not matter
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tao-Lionel** [comment]
`
const negative = ref(-1.035);
const negativeResult = usePrecision(negative, 2, { math: "floor" }); // -1.04
`

**Comment by Arizy** [comment]
> @Arizy I think you should use like this.
> 
> ```js
> const negative = ref(-1.035);
> const negativeResult = usePrecision(negative, 2, { math: "floor" }); // -1.04
> ```

Thanks for your advice. But I think the logic for numbers should be consistent when the third parameter is not set (see stackblitz). Maybe I thought it could both keep decimals and round off.

**Comment by Alexance** [comment]
By default, it uses `Math.round` to round the given number. According to the document https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round, it works correctly. In my opinion, changing this logic will produce unpredictable mistakes because it won't be aligned with the standard https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-math.round.

You can combine two `math` options to achieve what you want:

```typescript
const initial = ref(-1.035);
const final = usePrecision(initial, 2, () => ({
  math: initial.value > 0 ? 'round' : 'floor',
}));
```

**Comment by Arizy** [comment]
Indeed, what you said makes sense, and this logic should be aligned with the standards.
