### ISSUE TITLE
useMousePressed - account for target initially being `null` in non client-only components

### ISSUE THREAD

**Issue by DamianGlowala** [vueuse/vueuse#3818]
### Clear and concise description of the problem

Currently, I can't find a way to declare `useMousePressed` in the top level `<script setup>` of a component, which doesn't have the target element available straightaway (initially is `null` before the component mounts). Could this be handled internally, please?

### Suggested solution

Watch target internally and apply listeners based on its presence.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kongmoumou** [comment]
Any usage example?

**Comment by DamianGlowala** [comment]
Sure! Here you are:
```
<template>
  <div ref="templateRef" />
</template>

<script setup lang="ts">
const templateRef = ref<HTMLDivElement | null>(null)

const { pressed } = useMousePressed({
  target: templateRef // will initially be null and useMousePressed does not account for this
})
</script>
```

**Comment by VividLemon** [comment]
How does one press on a mouse without the page being mounted?

**Comment by DamianGlowala** [comment]
Obviously you can't, hence I created this issue asking whether it would be possible to delegate this check to the `useMousePressed`, rather than having to account for this myself.

**Comment by VividLemon** [comment]
I guess I was a bit confused as to the question. Is the issue that `target` requires `HTMLElement` and not `HTMLElement | null`?

**Comment by DamianGlowala** [comment]
This appears to be an issue most likely related to a third-party library and how it exposes a template ref.

Appreciate your help guys, will close it for now.
