### ISSUE TITLE
useImage - loading option - lazy

### ISSUE THREAD

**Issue by botmaster** [vueuse/vueuse#3826]
### Describe the bug

Hello,
I'm not sure I understand the purpose of the useImage `loading` option. If it's the HTML loading property 'lazy' or 'eager', it doesn't work. `isLoading` is always true.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-wzzjye?file=src%2Fcomponents%2FPhotoItem.vue,src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/core: ^10.8.0 => 10.8.0 
    vue: ^3.4.19 => 3.4.20
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by TheVaan** [comment]
In my understanding `isLoading` is true until the image is fully loaded. That means, `isLoading` is true, even when loading the image is hold off.

**Comment by Doctor-wu** [comment]
If you use `lazy` for the loading mode, images won't load until it almost shows in the viewport ([according to the doc](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/loading#timing_of_the_load_event)). So in this case, `isLoading` will never loaded since the `img` doesn't render at all, it is suggest to use like this.
```typescript
  <img v-show="!isLoading" :src="imageOptions.src" class="w-[300px] h-[200px]" loading="lazy" />
```
