### ISSUE TITLE
useConfirmDialog isRevealed in v-if only works when useConfirmDialog used with destructured object.

### ISSUE THREAD

**Issue by regen2k** [vueuse/vueuse#3832]
### Describe the bug

I use useConfirmDialog like this:

template:
```
<div v-if="isRevealed">show1</div>
<div v-if="conf.isRevealed">show2</div>
```

script setup:
```
const { isRevealed, ...remaining } = useConfirmDialog();
const conf = `useConfirmDialog();
```

I would expect neither show1 nor show2 is shown.

Actually: show2 is visible.

Do I use something wrong here?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-pw7tbr?file=src%2FApp.vue

### System Info

```Shell
latest
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markglattback** [comment]
Yes - inside of templates nested refs are not automatically unwrapped (this is standard Vue behaviour) so in the second case you're actually checking the truthy status of the `conf.isRevealed` ref, which is always `true`.

Update your template to this:

`<div v-if="conf.isRevealed.value">show2</div>`

**Comment by regen2k** [comment]
Thank you so much
