### ISSUE TITLE
createGlobalState Why does persistent state encapsulation fail?

### ISSUE THREAD

**Issue by InfernalAzazel** [vueuse/vueuse#3840]
### Describe the bug

I don't want to use pinia because createGlobalState is simple and convenient enough
I have encountered
createGlobalState Why does persistent state encapsulation fail?
It has no effect when switching languages, may I ask if I used it incorrectly?
store.ts
```
import { createGlobalState, useStorage } from '@vueuse/core'
import { GlobalStorageKey } from '@/config'
import { computed } from 'vue'


/** 存储全局响应变量 */
export const useGlobalState = createGlobalState(() =>{
  const storage = useStorage(GlobalStorageKey, {
    token_type: '',
    access_token: '',
    locale: '',
  })
  const access_token = computed(()=> storage.value.access_token)
  const token_type = computed(()=> storage.value.token_type)
  const locale =  computed(()=> storage.value.locale)

  function setAccessToken(value: string) {
    storage.value.access_token = value
  }
  function setTokenType(value: string) {
    storage.value.token_type = value
  }

  function setLocale(value: string) {
    storage.value.locale = value
  }
  return {
    access_token,
    token_type,
    locale,
    setAccessToken,
    setTokenType,
    setLocale
  }
})
```
src/locales/index.ts
```
import { createI18n } from 'vue-i18n';
import zhCN from './zhCN';
import enUS from './enUS';
import { useGlobalState } from '@/composables/store'

const {locale} = useGlobalState()
const i18n = createI18n({
  legacy: false,
  locale: locale.value === ''?'en_us': locale.value, // 设置语言环境
  // fallbackLocale: 'en_us', // 没有中文的话默认英文
  messages: {
    // 配置语言
    'zh_cn': zhCN,
    'en_us': enUS
  }
})

export default i18n
```

### Reproduction

.

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) Gold 6242R CPU @ 3.10GHz
    Memory: 5.65 GB / 31.34 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/n/bin/node
    Yarn: 1.22.21 - ~/n/bin/yarn
    npm: 10.2.3 - ~/n/bin/npm
    pnpm: 8.12.1 - ~/n/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.109
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by loongzhu** [comment]
I didn't find your code for setting `loacle` and there is no problem with `storage.value.locale = value`
