### ISSUE TITLE
useScrollLock > `overflow: hidden` persists or is reapplied in certain scenarios

### ISSUE THREAD

**Issue by ChristophJeworutzki** [vueuse/vueuse#3846]
I've come across a little hiccup since this [update](https://github.com/vueuse/vueuse/pull/3798).

It seems that in certain scenarios, `overflow: hidden` persists or is reapplied after setting `scrollLock` to `false`

I have a feeling this might be tied to a race condition, where `overflow: hidden` is being incorrectly set as the "initial state." 

_Originally posted by @ChristophJeworutzki in https://github.com/vueuse/vueuse/issues/3798#issuecomment-1979200565_

**Comment by ChristophJeworutzki** [comment]
Additional Context:

While testing this scenario, I accidentally called isLocked.value = false twice in a row. This seems to trigger the issue consistently, leading me to believe there might be a race condition at play. It appears that overflow: hidden might be incorrectly set as the "initial state" during these circumstances.

**Comment by loongzhu** [comment]
I find it when the initial style of the element is `overflow: hidden` and I fix it

**Comment by mrleblanc101** [comment]
I confirm that reverting to 10.8.0 from 10.9.0 fixed the issue for me.
