### ISSUE TITLE
useScroll - arrivedState.top bug in iOS Safari

### ISSUE THREAD

**Issue by Nathan7139** [vueuse/vueuse#3860]
### Describe the bug

In iOS Safari, there's a bug where the scrollTop property can be manipulated by user interaction to be less than zero, causing unexpected behavior in the useScroll function. The current implementation is:
https://github.com/vueuse/vueuse/blob/9f10ad06a4fd2b4e6325dc72a3d1e36a62b6c254/packages/core/useScroll/index.ts#L218
To fix this issue, I suggest:
```javascript
const top = scrollTop <= (offset.top || 0) 
```

### Reproduction

https://github.com/vueuse/vueuse/assets/144317846/b09078c5-85e7-4e34-b89a-627c183f34ca

### System Info

```Shell
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1
    Memory: 68.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    pnpm: 8.7.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.3
    Safari Technology Preview: 17.4
  npmPackages:
    @vueuse/core: ^10.3.0 => 10.7.2 
    vue: ^3.3.4 => 3.3.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yxiZo** [comment]
I have encountered this issue as well. When I need to create ceiling animations, it leads to animation stuttering in the iOS environment.

**Comment by 719media** [comment]
The same thing is true with scrollLeft and any overflow container that has elasticity (on more than just iOS). I'm not exactly sure why Math.abs is used in either of these scenarios.

**Comment by 719media** [comment]
Tracking this through, I see the reason for Math.abs is due to https://github.com/vueuse/vueuse/commit/23b9a34e6969e8fbbd27075262d5f07c2f45d132

Seems like the Math.abs should instead just be a sign flip instead of Math.abs in the scenario when reverse is happening. I'll make a PR

**Comment by 719media** [comment]
Let me know if there's anything on this issue that is questionable or needs to be done differently, would love to get it merged!
