### ISSUE TITLE
`Maximum recursive updates exceeded` when using props as source in `useMediaControls`

### ISSUE THREAD

**Issue by vaaski** [vueuse/vueuse#3873]
### Describe the bug

I am building a video player and think `useMediaControls` is a great fit.
However, during development I get the `Maximum recursive updates exceeded` during every (soft) reload.

I narrowed the issue down to using a props property in the src attribute of `useMediaControls`.
Not sure if `src` isn't meant to be used this way or if it's a bug though.

https://github.com/vaaski/use-media-controls-repro/blob/main/src/components/VideoPlayer.vue#L1-L14

To reproduce:
- clone [the repo](https://github.com/vaaski/use-media-controls-repro)
- run dev server
- change something in `components/VideoPlayer.vue` (e.g. add an empty line in the `<script setup>`)
- there'll be this error in the console:

![image](https://github.com/vueuse/vueuse/assets/17879327/be449776-6150-4760-ae19-b9124fef9d07)

### Reproduction

https://github.com/vaaski/use-media-controls-repro

### System Info

```Shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 22.21 GB / 31.85 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE     
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD        
    pnpm: 8.15.4 - ~\AppData\Roaming\npm\pnpm.CMD        
  Browsers:
    Brave: Version 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ilyaliao** [comment]
I did not encounter this issue in my [tests](https://stackblitz.com/edit/vitejs-vite-fwgswjca?file=src%2FApp.vue). Please confirm if the problem still exists or provide another reproduction.

**Comment by vaaski** [comment]
I was able to reproduce my issue in my repro repo, but after updating dependencies within range and `@vueuse/core` to latest, it seems to be fixed. Thanks!
