### ISSUE TITLE
useTextareaAutosize: onResize callback fires not only on resize

### ISSUE THREAD

**Issue by oleksandr-hyriavets** [vueuse/vueuse#3884]
### Clear and concise description of the problem

useTextareaAutosize has the option [onResize](https://github.com/vueuse/vueuse/blob/main/packages/core/useTextareaAutosize/index.ts#L15). First of all, it is undocumented, so it's probably worth it to add it to the docs.
Then, it is called on every change of the input and textarea. 

### Suggested solution

- add the onResize callback to docs
- call it only when size actually changes

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by huiliangShen** [comment]
actually, `useTextareaAutosize` only focus on `height` update. so, the `onResize` callback need trigger only when textarea height changed!

**Comment by oleksandr-hyriavets** [comment]
> huiliangShen

makes sense
