### ISSUE TITLE
Instructions for @vueuse/useQRCode are incorrect

### ISSUE THREAD

**Issue by takuhii** [vueuse/vueuse#3898]
### Describe the bug

Current instructions state that `npm i qrcode@^1` then you can 
```
import { useQRCode } from '@vueuse/integrations/useQRCode'
```

However the correct import is actually
```
import { useQRCode } from 'qrcode'
```

This is because the integration has been installed separately, and I haven't installed it via `npm i @vueuse/integrations` there needs to be a clearer instruction to show novice users that there is a different approach depending on how you install it.

### Reproduction

https://vitejsviteokimtm-hvy2--3000--7dbe22a9.local-credentialless.webcontainer.io

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 77.95 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 121.1.62.156
    Chrome: 123.0.6312.87
    Edge: 123.0.2420.65
    Safari: 17.4.1
  npmPackages: 
    vue: ^3.4.21 => 3.4.21
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pkc918** [comment]
Is there useQRCode in the qrcode pageckage?

**Comment by Alfred-Skyblue** [comment]
`useQRCode` is provided by `@vueuse/integrations`, and qrcode does not provide the `useQRCode` method. If you need to use it, please install it as follows:

```bash
npm i @vueuse/integrations qrcode@^1
```

- Use:

```ts
import { useQRCode } from '@vueuse/integrations'
```
