### ISSUE TITLE
useSwipe - onSwipe and onSwipeEnd not fired when touch moves back within threshold

### ISSUE THREAD

**Issue by ThijsAmersfoort** [vueuse/vueuse#390]
When a user swipes past the threshold, onSwipeStart is fired and isSwiping.value is set to true. However, when the user moves the touch back within the threshold, direction.value is set back to null, isSwiping.value is set to false and onSwipe is not fired anymore, even though the swipe is started but the user is moving back the touch. Also, when the touch is ended within the threshold, onSwipeEnd is not fired, even though the swipe was started. This causes the animation reliant on these functions to break, as does the demo on the vueUse website.

Expected behavior is that, as soon as a swipe is started, isSwiping.value should remain true an onSwipe should keep firing, up until touchend, also when the user moves the touch back within the threshold. Also, when a swipe is started, onSwipeEnd should also fire when the touch is moved back within the threshold.

To solve this, as soon as the threshold is passed, a variable should be set to indicate a swipe has started, and in the callback for touchmove and touchend, direction.value should not be checked to know if a swipe is going on, but this variable, so that even though the user moves the touch back within the threshold, the callback is aware a swipe is going on. Alternatively, direction.value could still be used in the if statement, but should not be set to null after a swipe has started and a user moves the touch back, but only after the swipe has ended.

**Comment by Tahul** [comment]
Hey 😀,

You can take a look at [@vueuse/gesture](https://github.com/vueuse/gesture).

I implemented what you are describing, porting react-use-gesture to Vue.

It already works, and I'm currently working on the documentation!

Please let me know if you have any suggestions!

**Comment by lstoeferle** [comment]
Hey @ThijsAmersfoort,

thanks for reporting this issue. I will try take some time fixing it thus week. ;)
