### ISSUE TITLE
property is error ？

### ISSUE THREAD

**Issue by WatcherOne** [vueuse/vueuse#3900]
### Describe the bug

it's <.value> ?
<img width="808" alt="截屏2024-04-01 14 39 58" src="https://github.com/vueuse/vueuse/assets/26219414/9ed4b79a-83e7-4fa6-9b75-8e81d4100904">

### Reproduction

is .value ?

### System Info

```Shell
browsers
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Do you want to send a quick PR to fix it? Thanks

**Comment by jahnli** [comment]
![image](https://github.com/vueuse/vueuse/assets/20943608/5147323b-9ed2-403c-87d2-bb71992f5e35)
Seems normal

**Comment by Alfred-Skyblue** [comment]
Fixed in #2858, please refer to the official documentation for accuracy. Any discrepancies in third-party translated versions should be reported to the respective repository for resolution.
