### ISSUE TITLE
useDraggable will trigger a click event after each drag and drop completion

### ISSUE THREAD

**Issue by 3261564019** [vueuse/vueuse#3901]
### Describe the bug

how to retain click events while retaining drag and drop functionality

### Reproduction

no

### System Info

```Shell
no
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Nomango** [comment]
Can't find an elegant solution. There is a temporary approach.

```ts
const isDragging = ref(false);

useDraggable(dragger, {
  onMove: () => {
    isDragging.value = true;
  },
  onEnd: () => {
    setTimeout(() => {
      isDragging.value = false;
    }, 100);
  },
});

function onClick() {
  if (!isDragging.value) {
    // do sth
  }
}
```
