### ISSUE TITLE
[Features] useRouteQuery transform data (get/set)

### ISSUE THREAD

**Issue by kieuminhcanh** [vueuse/vueuse#3929]
### Clear and concise description of the problem

Some time I would like to transform data before use. In my case. There are two case to use.

// orders?page=2&orderBy=no:asc&orderBy=status:desc
```js
const filters = reactive({
  page: useRouteQuery('page', '1', {
    transform: ({
      get: (value) => parseInt(value),
      set: (value) => value.toString()
    })
  }),
  orderBy: useRouteQuery('orderBy', [], {
    transform: ({
      get: (value) => value.map((v) => v.split(':'))
        .map(([key, order]) => ({
          key: key.toLowerCase(),
          order: order.toLowerCase(),
        })),
      set: (value) => value.map(({ key, order }) => `${key}:${order}`)
    })
  })
})
```
From orders?page=2&orderBy=no:asc&orderBy=status:desc
We will have
```
filters.page = 2
filters.orderBy = [{ key: 'no', order: 'asc' }, { key: 'status', order: 'desc' }]
```
Otherways
```
filters.page = 2
filters.orderBy = [{ key: 'no', order: 'desc' }, { key: 'time', order: 'desc' }]
// =>> orders?page=2&orderBy=no:desc&orderBy=time:desc
```

### Suggested solution

Add transform (get/set) function in **ReactiveRouteOptions** 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kieuminhcanh** [comment]
+

**Comment by kieuminhcanh** [comment]
+1

**Comment by kieuminhcanh** [comment]
+2

**Comment by miquelromero** [comment]
Because of this missing feature, when working with numbers you cannot easily remove the query value from the url when setting back the default value.
Reproduction link:
https://stackblitz.com/edit/vitejs-vite-v43zsp?file=src%2FPage.vue

This is problematic, for example, with pagination (which is the docs example): if you navigate form page 1 to 2 and then back to page 1.

For now I've copied to our codebase the composable and extended it so, instead of:
```
const page = useRouteQuery('page', '1', { transform: Number })
```
We can do:
```
const page = useRouteQuery('page', '1', { transform: { get: Number, set: String }})
```
