### ISSUE TITLE
Chrome Extension APIs

### ISSUE THREAD

**Issue by ultimateshadsform** [vueuse/vueuse#3935]
### Clear and concise description of the problem

Hello! It would be nice with a package that is related to Chrome Extensions APIs like chrome.storage.sync, chrome.storage.local etc.

These APIs are not the same as local storage etc.

Maybe have it in a @vueuse/chrome-extension package or something like that.

For apis only meant to be run in a chrome extension environment.

Would be nice to have some wrappers like useStroage but something like useExtensionStorage or maybe useChromeStorage or something like that.

### Suggested solution

To create a new package meant for browser extension APIs.

### Alternative

Would be nice to implement it in Vueuse since it's all mostly related to composables and stuff.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by pavi2410** [comment]
Great idea. I work on a Chrome extension project and could use it. It should use web-ext polyfill to target browsers other than Chrome.

**Comment by antfu** [comment]
I would say feel free to go ahead and create your own library and share with the community and see how people find it useful - later we could discuss about if you want to merge it into VueUse. The general principle is that we can't provide integrations for everything in the world, and we already have so many functions to maintain. So for now, I don't think we will do it officially. Thanks.

**Comment by ultimateshadsform** [comment]
> I would say feel free to go ahead and create your own library and share with the community and see how people find it useful - later we could discuss about if you want to merge it into VueUse. The general principle is that we can't provide integrations for everything in the world, and we already have so many functions to maintain. So for now, I don't think we will do it officially. Thanks.

Of course! I would be happy to! 😀
