### ISSUE TITLE
使用useWebSocket会一直开启关闭重启

### ISSUE THREAD

**Issue by Anima-No** [vueuse/vueuse#3936]
### Describe the bug

使用的版本为：    "@vueuse/core": "^10.9.0"
这是一段运行的代码
`

const state = reactive({
  server: 'ws://124.222.224.186:8800',
  retryTimeout: 3000,
  sendValue: '',
  recordList: [],

});

const { status, data, send, close, open } = useWebSocket(state.server, {
  heartbeat: {
    message: 'ping',
    interval: state.retryTimeout
  },
  autoReconnect: true,
});

watchEffect(() => {
  if (data.value) {
      state.recordList.push(data.value);
      console.log(state.recordList)
  }
  //会一直开启，关闭，重启
  console.log(status.value)
});

如果这个ws无法连接请自行换个可以用的wss
`
由于Reproduction内无法使用ws链接，请自行更换wss链接即可复现

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ytf48z?file=package.json,src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0 
    vue: ^3.2.25 => 3.2.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Anima-No** [comment]
15:00:53 [vite] hmr update /src/App.vue
App.vue?import&t=1714114853783:30 CONNECTING
client.ts:352 [vite] hot updated: /src/App.vue
App.vue?import&t=1714114853783:30 OPEN
App.vue?import&t=1714114853783:30 CLOSED
App.vue?import&t=1714114853783:30 CONNECTING
App.vue?import&t=1714114853783:30 OPEN
App.vue?import&t=1714114853783:30 CLOSED
App.vue?import&t=1714114853783:30 CONNECTING
App.vue?import&t=1714114853783:30 OPEN
App.vue?import&t=1714114853783:30 CLOSED
App.vue?import&t=1714114853783:30 CONNECTING

**Comment by qq406601626** [comment]
After you send the ping message content, the server needs to return a pong message to you

**Comment by Anima-No** [comment]
Thank you. I'll try it next time.

**Comment by DonutGeek** [comment]
> After you send the ping message content, the server needs to return a pong message to you

Can I customize the server reply message？

**Comment by qq406601626** [comment]
> > After you send the ping message content, the server needs to return a pong message to you
> 
> Can I customize the server reply message？

yes，you can

**Comment by SadmiB** [comment]
When I use heartbeat and autoReconnect together the re-connection is triggered each time we send a ping, @Anima-No I assume this is your issue too?

**Comment by Anima-No** [comment]
> When I use heartbeat and autoReconnect together the re-connection is triggered each time we send a ping, @Anima-No I assume this is your issue too?

yes

**Comment by DonutGeek** [comment]
> > > After you send the ping message content, the server needs to return a pong message to you
> > 
> > 
> > Can I customize the server reply message？
> 
> yes，you can

How to set it up

**Comment by varzy** [comment]
I encountered the same problem and had to switch to native APIs.

**Comment by ilyaliao** [comment]
> I encountered the same problem and had to switch to native APIs.

Do you have any error messages or minimal reproduction?

**Comment by varzy** [comment]
> > I encountered the same problem and had to switch to native APIs.
> 
> Do you have any error messages or minimal reproduction?

Sorry I don't have time to check the original code or submit a PR to fix the issue, so I have provided a minimal project for your reference.

https://github.com/varzy/demo-of-vue-use-websocket

Please use `npm run dev` and `bun server.ts` to launch the project. I think the core issue is that I need to encode the format of the heartbeat, please check this line in `stores/useHandshakerStore.ts`:

handshaker.value = useWebSocket(url, {
  heartbeat: {
    message: encodeMessage('ping')
  },
}

**Comment by ilyaliao** [comment]
The disconnection issue occurs because the server does not respond when it receives a message, causing the front-end heartbeat to fail.

try this
```js
import { WebSocketServer } from 'ws'

const wss = new WebSocketServer({ port: 9090 })

wss.on('connection', function connection(ws) {
  ws.on('message', function message(data) {
    console.log('received: %s', data)
    ws.send('Hello from server!')
  })
})

console.log('WebSocket server is running on port 9090')
```
