### ISSUE TITLE
`useEventSource` is missing header configuration

### ISSUE THREAD

**Issue by quando1910** [vueuse/vueuse#3938]
### Clear and concise description of the problem

As a developer using `useEventSource`, I want to have `headers` options for useEventSource, so that we can add an Authorization token for the event source in some cases.### 

### Suggested solution

Add `headers?: { [name: string]: string };` in interface `EventSourceInit`
Then pass headers when execute `new EventSource`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by transtone** [comment]
why completed it?
