### ISSUE TITLE
useColorMode and useDark trigger reflows every time they are used

### ISSUE THREAD

**Issue by jpleclerc** [vueuse/vueuse#3955]
### Describe the bug

The bug has two parts:
1. `useColorMode`'s default onChange function is triggered as soon as the composable is called. Unless the `disableTransition: false` option is used, the page will reflow and negatively impact performance on complex pages. 
2. The onChange function will be triggered once per `useColorMode` usage whenever we toggle the dark mode, triggering a reflow each time.

This also affects `useDark` since it directly uses `useColorMode`.

Two mitigating solutions until this is fixed:
1. Use `useDark` and `useColorMode` once and share the ref across the app to avoid unnecessary calls to the onChange functions. This is not possible whenever a library uses the composable.
2. Use `disableTransition: false` to avoid page reflows, but then again, if a library doesn't use the option, we have the same problem.

Potential fixes I can think of:
1. Do not call the onChange function on usage
2. Do not call the onChange function if nothing changed
3. Do not register the same onChange function multiple times

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ksex6y

Here is what it looks like in the performance profiler when I run useDark every second.
![image](https://github.com/vueuse/vueuse/assets/1129404/324c8f64-3bc6-4dd5-9506-344975927e99)

### System Info

Vueuse v10, doesn't happen in v9

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pkc918** [comment]
Please provide an online case about the issues，thx.

**Comment by jpleclerc** [comment]
> Please provide an online case about the issues，thx.

@pkc918 Added repro + screenshot. I tried with vueuse v9 and the problem is not there. I think it happens since the disableTransitions default has been set to true: https://github.com/vueuse/vueuse/commit/5c82cf3ae9628d0ef7b86254affc37b2196a9d9a

**Comment by ilyaliao** [comment]
I will close this issue as it seems that #4001 has resolved part of it. Feel free to reopen it or create a new issue.
