### ISSUE TITLE
useTextareaAutosize

### ISSUE THREAD

**Issue by muster-mark** [vueuse/vueuse#3962]
### Describe the bug

The textarea increases in height before necessary. I do not think this is as intended, or I imagine it would be mentioned in the docs.  The following video was recorded from the example page https://vueuse.org/core/useTextareaAutosize on Firefox . The behaviour is the same on Chrome.

https://github.com/vueuse/vueuse/assets/12281979/4bad66c7-228d-4c6a-bd01-ce41a657ab6b

### Reproduction

https://vueuse.org/core/useTextareaAutosize/

### System Info

```Shell
Not applicable as issue apparent on vueuse.org demo.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lzl0304** [comment]
You need to add the following styles
```css
textarea {
  -ms-overflow-style: none;
  scrollbar-width: none;
}

textarea::-webkit-scrollbar {
  display: none;
}
```

https://vueuse.org/core/useTextareaAutosize/#usage
