### ISSUE TITLE
useWebNotification not working on chrome mobile device

### ISSUE THREAD

**Issue by ibnusyawall** [vueuse/vueuse#3979]
### Describe the bug

I have grant permission of the notification request but notification not showing on chrome browser mobile device, works perfect on chrome dekstop device only, how to solve the problem?

The error like this when im using mobile device:
```
TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.
```

### Reproduction

https://vueuse.org/core/useWebNotification/

### System Info

```Shell
System:
    OS: Android 11; CPH2269 Build/RP1A.200720.011

Browsers:
    Chrome: 125.0.6422.52
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vladyslav-mikhieiev** [comment]
@antfu  As a result, this [PR](https://github.com/vueuse/vueuse/pull/3980) spams empty push notifications on the desktop. Just [go to the demo](https://vueuse.org/core/useWebNotification/#usewebnotification) and without pressing the button we will see 2 push notifications

**Comment by KarolMilewski** [comment]
> @antfu As a result, this [PR](https://github.com/vueuse/vueuse/pull/3980) spams empty push notifications on the desktop. Just [go to the demo](https://vueuse.org/core/useWebNotification/#usewebnotification) and without pressing the button we will see 2 push notifications

I confirm. We have the same problem ^

**Comment by vusatui** [comment]
Yes, it starts to spam a message after every single call of the composable. I think it should be treated as a bug.
