### ISSUE TITLE
useWebNotification demo doesn't work in Arc webbrowser or in Safari (with notifications enabled)

### ISSUE THREAD

**Issue by WouS95** [vueuse/vueuse#3997]
### Describe the bug

When using the [demo](https://vueuse.org/core/useWebNotification) useWebNotification i see the button and can click it. Then in the Arc browser i get a popup asking for permission. I accept that. Then when using the button again nothing shows, not even a console error. It just silently fails. The same happens on Safari mobile (iphone) with notifications enabled in the settings.

When using the Google Chrome webbrowser the notification shows once. When clicking the button again nothing shows and the notification silently fails.

### Reproduction

https://vueuse.org/core/useWebNotification

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 46.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  Browsers:
    Chrome: 125.0.6422.77
    Safari: 17.5

Arc broswer is not listed, but it is installed as my default browser, Based on Chromium version 125.0.6422.112 (Officiële build) (arm64)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CasperSocio** [comment]
Why was this closed? I'm having the same issue in Arc Version 1.85.0 (59596)
Chromium Engine Version 134.0.6998.45

**Comment by CasperSocio** [comment]
Alright. I assume it was closed because—like me—you quickly discovered that Arc notifications was set to `None` in system settings. I suggest adding this as a tip in the documentation.
