### ISSUE TITLE
useInfiniteScroll Infinite loop 

### ISSUE THREAD

**Issue by kingwrcy** [vueuse/vueuse#4000]
### Describe the bug

I haven't started scrolling the scroll bar yet, but it keeps calling the function onLoadMore in an infinite loop. The code is copied from the demo of the official website.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jcnxvx?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/components: ^10.10.0 => 10.10.0 
    @vueuse/core: ^10.10.0 => 10.10.0 
    vue: ^3.4.27 => 3.4.27
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by RandallAnjie** [comment]
You need to add height and overflow attributes to the outer div to ensure that the page has enough space for scrolling

```
<div style="height: 400px; overflow: auto;" v-infinite-scroll="[onLoadMore, { distance: 10 }]">
    <div v-for="item in data" :key="item">
      {{ item }}
    </div>
  </div>
```

It seems that the examples on the official website do not add these two attributes.

**Comment by andrewvasilchuk** [comment]
I believe this behavior is expected. Even if you don't scroll, the callback will still be triggered to fetch more items and fill the remaining height.

The reproduction link you provided does not contain a valid example of the issue.

**Comment by FacundoBrum16** [comment]
i have the same issue, It makes me feel insecure

**Comment by pdelucia96** [comment]
I have the same problem.
The problem is we have a v-for but isn't the div with a repeater to scroll, instead is the body tag that scroll.
There is a way to attach the event to the body scroll?

**Comment by CofCat456** [comment]
The problem still exists?

**Comment by zhaoyuqiqi** [comment]
I have the same problem.
Have you made any progress?

**Comment by AlansCodeLog** [comment]
I also ran into this. After trying to reproduce it, I realized that there is a `canLoadMore` option one can use. Maybe it should be added to the default examples, as this will happen whenever there are so few items that the container won't scroll.

Here is the "reproduction"/fix (removing the canLoadMore causes infinite calls). https://stackblitz.com/edit/vitejs-vite-6ujom66u?file=src%2FApp.vue

**Comment by ilyaliao** [comment]
> 我也遇到了這個。在嘗試重現它之後，我意識到有`canLoadMore`一個可以使用的選項。也許應該將其添加到預設範例中，因為只要項目太少而容器無法滾動，就會發生這種情況。
> 
> 這是“複製”/修復（刪除 canLoadMore 會導致無限調用）。https://stackblitz.com/edit/vitejs-vite-6ujom66u?file=src%2FApp.vue

Yes, because without setting the canLoadMore condition, it will continuously trigger until the scrolling distance exceeds the container height. In the example you provided, where the height is set to 500px, it will continuously attempt to add items until the height is exceeded and it stops.

**Comment by ilyaliao** [comment]
> I also ran into this. After trying to reproduce it, I realized that there is a `canLoadMore` option one can use. Maybe it should be added to the default examples, as this will happen whenever there are so few items that the container won't scroll.
> 
> Here is the "reproduction"/fix (removing the canLoadMore causes infinite calls). [stackblitz.com/edit/vitejs-vite-6ujom66u?file=src%2FApp.vue](https://stackblitz.com/edit/vitejs-vite-6ujom66u?file=src%2FApp.vue)

Yes, because without setting the canLoadMore condition, it will continuously trigger until the scrolling distance exceeds the container height. In the example you provided, where the height is set to 500px, it will continuously attempt to add items until the height is exceeded and it stops.

**Comment by AlansCodeLog** [comment]
Yes, I understand now, it's just this is not obvious and I expected the example code to work in a situation like this. I can do a PR to add canLoadMore to the example and a note regarding this.

The only thing, looking at it again, the directive version has an example without options which is probably not a good idea. Is there a situation where the option shouldn't be specified? I'm sure people have been using the function without it, but it's possible their code is only working because their list always loads enough content to fill the container when they've tested it.
