### ISSUE TITLE
The project packaging will report this TypeScript error.

### ISSUE THREAD

**Issue by xstxhjh** [vueuse/vueuse#4006]
### Describe the bug

node_modules/@vueuse/shared/index.d.ts:398:119 - error TS1128: Declaration or statement expected.

398 declare function makeDestructurable<T extends Record<string, unknown>, const A extends readonly any[]>(obj: T, arr: A): T & A;
                                                                                                                          ~
Found 10 errors in the same file, starting at: node_modules/@vueuse/shared/index.d.ts:398

### Reproduction

new version

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 96.42 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.15.4 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
    bun: 1.1.6 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.113
    Safari: 17.2.1
  npmPackages:
    @vueuse/core: ^10.10.0 => 10.10.0 
    vue: ^3.4.27 => 3.4.27
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xstxhjh** [comment]
I downgraded to version 10.9.0 and there would be no such error.I downgraded to version 10.9.0 and there would be no such error.

**Comment by oliver139** [comment]
Same here, got the same error while deploying to production yesterday
I downgraded to 10.9.0 to resolve the error
```json
{
  "dependencies": {
    "@vueuse/core": "~10.9.0",
  }
}
```

**Comment by brenoepics** [comment]
After some research, I discovered that the issue occurs when you run VueUse 10.10.0 with TypeScript versions below 5. This [commit](https://github.com/vueuse/vueuse/commit/4ea131a2ccff41742a0de8600f790edc1f8632e2) broke support for TypeScript versions below 5 because [`const` modifier on type parameters](https://github.com/microsoft/TypeScript/pull/51865) was added in TypeScript 5.

It wasn't a problem for me to update the TypeScript version. However, I'm not sure about @xstxhjh, @oliver139, and others. If it's an issue for them, a maintainer could consider reverting this commit.

**Comment by oliver139** [comment]
> After some research, I discovered that the issue occurs when you run VueUse 10.10.0 with TypeScript versions below 5. This [commit](https://github.com/vueuse/vueuse/commit/4ea131a2ccff41742a0de8600f790edc1f8632e2) broke support for TypeScript versions below 5 because [`const` modifier on type parameters](https://github.com/microsoft/TypeScript/pull/51865) was added in TypeScript 5.
> 
> It wasn't a problem for me to update the TypeScript version. However, I'm not sure about @xstxhjh, @oliver139, and others. If it's an issue for them, a maintainer could consider reverting this commit.
> 

Ok, I see. I am having TS ~4.5.5 here and would see if I am able to upgrade the TS version.

Thanks anyway!

**Comment by drahkrub** [comment]
> ..., a maintainer could consider reverting this commit.

Would be nice if this happens, because our projects depends on https://quasar.dev/ which does not support Typescript >= 5 right now.

**Comment by Bassadin** [comment]
I think it should at least be marked as a potential breaking change, not supporting TS<5 anymore :D

**Comment by oliver139** [comment]
> I think it should at least be marked as a potential breaking change, not supporting TS<5 anymore :D

Agree. Where minor version change should be backward compatible I think?
