### ISSUE TITLE
useWebNotification emitting notification when mounted

### ISSUE THREAD

**Issue by Ryan-santos** [vueuse/vueuse#4017]
### Describe the bug

When the user already has notifications enabled, it emits two notifications (without body) when the component is mounted.

_Including that the error apparently occurs in the documentation itself_

### Reproduction

https://vueuse.org/core/useWebNotification

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 1.94 GB / 15.84 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vueuse/nuxt: ^10.10.0 => 10.10.0
    vue: ^3.4.21 => 3.4.27
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 9romise** [comment]
Sorry, this was my mistake. This PR fixes the issue: #4019 . You can patch it in your registry to temporarily fix it.

**Comment by bblanchon** [comment]
I'm having the same issue, too.
Is anything preventing the PR from being merged?

**Comment by squarou** [comment]
+1

**Comment by vladyslav-mikhieiev** [comment]
+1

**Comment by oligety** [comment]
Hi @9romise , 
Is there any update on this pull request? This is holding us back from upgrading from 10.9.0 to newer versions. And we prefer not to patch this.
