### ISSUE TITLE
为什么没有 useRequest

### ISSUE THREAD

**Issue by jxh150535011** [vueuse/vueuse#4018]
### Clear and concise description of the problem

为什么没有一款好用的 useRequest， 看看别人的，这种库才是能快速解决问题的。简单把常见api 包装 成use 形式，层级还是太低了。往上层业务走两步。上层应用大概也就10个左右 常见hook 包装一下就好。例如下面的：
https://inhiblabcore.github.io/docs/hooks/useRequest/

### Suggested solution

useRequest 很有用

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by beijixiaohu** [comment]
呃…你是不是要找：https://vueuse.org/core/useAsyncState/#useasyncstate

**Comment by antfu** [comment]
Feel free to create and maintain your own. We no longer accept new functions.
