### ISSUE TITLE
Can't call control functions from callback using immediate=true in watchPausable

### ISSUE THREAD

**Issue by ttonyh** [vueuse/vueuse#4024]
### Describe the bug

When using `watchPausable` and setting `immediate=true`, you are unable to call any of the control functions (stop/pause/resume) from the watcher callback. You'll get a similar error to this:

```
Uncaught (in promise) ReferenceError: can't access lexical declaration 'pause' before initialization
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-vgyb95

### System Info

```Shell
System:
    OS: Linux 6.9 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 57.12 GB / 94.03 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.0.0 - ~/.nvm/versions/node/v22.0.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v22.0.0/bin/npm
    pnpm: 9.1.3 - ~/.nvm/versions/node/v22.0.0/bin/pnpm
    bun: 1.1.9 - ~/.bun/bin/bun
  Browsers:
    Chromium: 125.0.6422.141
  npmPackages:
    @vueuse/components: ^10.10.0 => 10.10.0
    @vueuse/core: ^10.10.0 => 10.10.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Gianthard-cyh** [comment]
actually calling an function like this will cause an error:

```js
function foo(fn) {
    function bar() {
        console.log('bar function is called');
    }

    fn();  // Call the passed fn function

    return bar;  // Return the bar function
}

// Attempting to call an undefined function within the closure, leading to an error: "ReferenceError: Cannot access 'bar' before initialization"
// This error occurs because within the closure's parameter function, the returned function 'bar' is not yet defined.
const bar = foo(() => {
    bar();  // Trying to call an undefined function 'bar' here results in the error.
});

bar();  // Now, you can call the returned bar function
```

Please provide the reason that why you want to call `pause` in the callback function. 

I'm not entirely sure what this piece of code is intended to do. Could you provide more context or explanation so that I can better understand?

**Comment by Gianthard-cyh** [comment]
@ttonyh, thank you for clarifying and providing the use case.

I would like to clarify that I am not a member of the VueUse project. If the maintainers think it's reasonable to add an option like `paused=true` to watchPausable to specify an initially paused state, I would be happy to submit a PR. And that might work for you.

**Comment by Gianthard-cyh** [comment]
And here might be a possible workaround: 
https://stackblitz.com/edit/vitejs-vite-ybvavv?file=src%2FTest.vue

```typescript
const { eventFilter: filter, pause, resume } = pausableFilter();

watchWithFilter(
  props.modelValue,
  (newVal, oldVal) => {
    console.info('WATCH: WEIGHT IMPERIAL SEL: MODEL: ', newVal);
    pause();
    localModel.value = newVal ?? null;
    resume();
  },
  {
    eventFilter: filter,
    immediate: true,
  }
);
``` 

by using `pausableFilter` and `watchWithFilter`, it will not cause an error because the event filter is defined before watch function is called. You can call `pause` and `resume` in any other parts in your code now. And actually `watchPausable` is just a alias of `watchWithFilter` with a `pausableFilter`.
