### ISSUE TITLE
useBreakpoints doesn't work correctly

### ISSUE THREAD

**Issue by bertonix-dm** [vueuse/vueuse#404]
The issue itself is quite straightforward, breakpoint service functions (`smaller`, `between`) shouldn't include last max-width pixel of media query into account. (e.g. 767px is "sm" but 768 isn't)

I've attached two screenshots where you can see the issue itself

useBreakpoints() vs tailwind:

### 767px

![image](https://user-images.githubusercontent.com/59884106/113023737-9f5d2f80-918e-11eb-9243-2745486cd758.png)

### 768px

![image](https://user-images.githubusercontent.com/59884106/113023893-cf0c3780-918e-11eb-8404-ada65b27bc69.png)
(it's smaller and greater than "md" at the same time)

### My current workaround (hope you fix it ASAP, be me to it):

```
  install: (app: App): void => {
    const breakpoints = useBreakpoints(breakpointsTailwind)

    breakpoints.smaller = (k) => {
      return useMediaQuery(`(max-width: ${breakpointsTailwind[k] - 1}px)`)
    }

    app.config.globalProperties.$breakpoints = breakpoints
    app.provide('breakpoints', breakpoints)
  }
  ```
  
yet another thing, there is a typo in documentation. there is no `larger`, should be `greater` instead 😄 

![image](https://user-images.githubusercontent.com/59884106/113024967-0deebd00-9190-11eb-873f-88d1dbdef68d.png)

P.S. thanks for the "vueuse" it's just sick!

**Comment by AndrewSparrowww** [comment]
Thanks for posting, found it pretty annoying.

**Comment by wheatjs** [comment]
Thanks for the report, I'll take a look at this tonight
