### ISSUE TITLE
onClickOutside: Argument of type 'Ref<null>' is not assignable to parameter of type 'MaybeElementRef'.

### ISSUE THREAD

**Issue by productfrontenddeveloper** [vueuse/vueuse#405]
![Screen Shot 2021-03-30 at 20 28 51](https://user-images.githubusercontent.com/38668796/113030693-8bb5c700-9196-11eb-8b5a-6f61ae0d5869.png)
iam used some [example](const target = ref(null)
    onClickOutside(target, (event) => accessor.modalComponent.setQuicSearchInterfaceField({ key: 'isOpen', value: false })))

```
const target = ref(null)
   
 onClickOutside(target, (event) => accessor.modalComponent.setQuicSearchInterfaceField({ key: 'isOpen', value: false }))
 ```

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/113093850-42f81f80-9223-11eb-8668-f4a4f4c37366.png)

Didn't see the error, what's your tsconfig.json?

**Comment by productfrontenddeveloper** [comment]
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": ["esnext", "esnext.asynciterable", "dom"],
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "baseUrl": ".",
    "importsNotUsedAsValues": "preserve",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"]
    },
    "types": ["@types/node", "@nuxt/types", "nuxt-i18n", "nuxt-tailvue"]
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}
```

**Comment by productfrontenddeveloper** [comment]
This happened after a few updates, but I'm not sure which one. didn't exist before

**Comment by productfrontenddeveloper** [comment]
![Screen Shot 2021-03-31 at 15 26 32](https://user-images.githubusercontent.com/38668796/113144034-7e034e80-9235-11eb-8f1a-6e9ae97ad768.png)
some -> "@vue/composition-api": "1.0.0-rc.6"

**Comment by productfrontenddeveloper** [comment]
vscode update + reload vscode + yarn.lock delete and install fixed :)

**Comment by productfrontenddeveloper** [comment]
> Doesn't find anything suspicious. Maybe updates your vue version?

"@vue/runtime-dom": "3.0.10", 2 vs -> 3 update and see problem

**Comment by wheatjs** [comment]
@productfrontenddeveloper I'm unable to reproduce this using the latest vue version(3.0.10). Can you provide a link to a minimal reproduction repo

**Comment by sibbng** [comment]
That `_refBrand` thing only exist in https://github.com/vuejs/composition-api/blob/master/src/reactivity/ref.ts

Seems related to changes in https://github.com/vuejs/composition-api/pull/668

**Comment by wheatjs** [comment]
@productfrontenddeveloper is this still an issue for you?

**Comment by productfrontenddeveloper** [comment]
> @productfrontenddeveloper is this still an issue for you?

no

**Comment by rich1e** [comment]
What is the cause of this problem? How to solve it?

![image](https://github.com/vueuse/vueuse/assets/29914689/c571fa50-1bdd-46bb-82b2-c98106664387)
