### ISSUE TITLE
Consider debouncing setter of Ref returned from `useDebounce`

### ISSUE THREAD

**Issue by cypressious** [vueuse/vueuse#407]
I was playing around with `useDebounce` and wrote the following component

```vue
<template>
  <input v-model="query">
</template>

<script lang="ts">
import { defineComponent, ref, watchEffect } from "vue";
import { useDebounce } from "@vueuse/core";

export default defineComponent({
  name: "CompositionApiComponent",
  setup() {
    const query = useDebounce(ref(''), 500)
    watchEffect(() => console.log(query.value))

    return {
      query
    }
  }
})
</script>
```

To my surprise, everytime I typed a letter, the `watchEffect` triggered and printed the value of `query`. What I expected to happen was that the `console.log` was debounced and only after I didn't type anything for 500ms, the current value will be printed.

I went to read the source of `useDebounce` and discovered that the setter of the returned `Ref` isn't actually debounced. Instead, only changes to the original `Ref` are reflected debouncedly. What I needed to write was

```ts
const query = ref('')
const queryDebounced = useDebounce(query, 500)
watchEffect(() => console.log(queryDebounced.value))
```

which seems a bit verbose. So I modified my code to the following which did what I wanted

```ts
const _query = ref('')
const query = computed({
  get: () => _query.value,
  set: useDebounceFn(v => _query.value = v, 500)
})
```

My proposal is to modify `useDebounce` so that setting values on the debounced `Ref` are also debounced.

**Comment by cypressious** [comment]
Thinking a bit more about the issue, a couple of questions popped up.

In the current form, writes to the debounced `Ref` are not reflected back to the original `Ref`. Is this intended? If not, maybe `useDebounce` should return a `Readonly<Ref<T>>`?

In that case a new function similar to my last code snippet would make sense that doesn't take a `Ref` as an argument and returns a mutable `Ref` where changes are debounced.

Alterantively, it could be decided that writes to a `Ref` returned by `useDebounce` are allowed and are reflected back to the original `Ref`. However, this could be a breaking change for clients that rely on the current behavior.

**Comment by antfu** [comment]
> useDebounce should return a Readonly<Ref<T>>

Yeah, that was expected. At the time it was written, Vue 2 does not support the `readonly` API, but it does now. Thank you for spotting this and if you want, I'd be appreciated for a PR.
