### ISSUE TITLE
`onLongPress` :  callback hook is fired only once when long press

### ISSUE THREAD

**Issue by deka** [vueuse/vueuse#4071]
### Describe the bug

``` js
const number = ref(0);
const htmlRefIncrement = ref();
onLongPress(
  htmlRefIncrement,
  () => {
    number.value += 1;
  },
  {
    delay: 100,
  }
);
</script>
```
onLongPress callback hook is fired only once.
I expect it to be called every 100 milliseconds

### Reproduction

https://stackblitz.com/edit/vitejs-vite-txwsq6?file=src%2FApp.vue

### System Info

```Shell
"@vueuse/core": "^10.11.0",
"vue": "^3.2.25"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Aaron-zon** [comment]
https://github.com/vueuse/vueuse/assets/47178158/9d55d798-6c0b-4745-ac75-f2db2f8ff443

It looks correct.

**Comment by deka** [comment]
Thanks @Aaron-zon 
When i keep pressing the button (long press), I expect the hook to be called several times , every 100 ms (delay)
Isn't this the expected behavior ?

**Comment by Aaron-zon** [comment]
the documentation only mentions that this listens for long press events, so it is just a listener function similar to click.

In the example code, the callback function is triggered only when you long press for more than 100 milliseconds; it does not trigger repeatedly every 100 milliseconds.

![image](https://github.com/vueuse/vueuse/assets/47178158/d38184a1-49d1-426f-b2fc-afb18c582e56)

**Comment by deka** [comment]
I understand use case. 
Is there a way to turn this bug into a feature request?

**Comment by Aaron-zon** [comment]
```javascript
const number = ref(0);
const htmlRefIncrement = ref();
onLongPress(
  htmlRefIncrement,
  () => {
    setInterval(() => { number.value += 1 }, 100)
  },
  {
    delay: 100,
  }
);

```

**Comment by deka** [comment]
Thanks @Aaron-zon,

> ```js
> const number = ref(0);
> const htmlRefIncrement = ref();
> onLongPress(
>   htmlRefIncrement,
>   () => {
>     setInterval(() => { number.value += 1 }, 100)
>   },
>   {
>     delay: 100,
>   }
> );
> ```

Something like that, yes, but of course the incrementing has to stop when the button is released.
