### ISSUE TITLE
useFocusWithin doesn't respond to document.hasFocus()

### ISSUE THREAD

**Issue by cyyynthia** [vueuse/vueuse#4083]
### Describe the bug

When using `useFocusWithin`, it will not take into account whether the document has focus or not, unlike :focus-within it tries to emulate.

This can be observed on vueuse's website; focusing an input on the demo page and moving focus out of the browser will cause the style to change, but the form will still be considered focused by vueuse.

### Reproduction

https://vueuse.org/core/useFocusWithin/

### System Info

```Shell
System:
    OS: Linux 6.9 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 2.20 GB / 15.58 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
    Yarn: 1.22.22 - /bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v22.1.0/bin/npm
    pnpm: 9.4.0 - ~/files/projects/radix-vue/radix-vue/node_modules/.bin/pnpm
    bun: 1.1.10 - /bin/bun
  Browsers:
    Chromium: 125.0.6422.112
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ilyaliao** [comment]
Closed via #4134
