### ISSUE TITLE
useBreakpoint and useMediaQuery cause "Hydration text mismatch" on Nuxt

### ISSUE THREAD

**Issue by sharifzadesina** [vueuse/vueuse#4102]
### Describe the bug

This bug can be related to #912

It seems like `useWindowSize`, we need to use the `tryOnMounted` function also for `useMediaQuery`, to prevent the mismatch error.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4j78pj

### System Info

```Shell
Doesn't matter.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MoeinMirkiani** [comment]
struggling with the same issue 🤕

**Comment by soylomass** [comment]
Same

**Comment by jamesray** [comment]
same issue

**Comment by N-index** [comment]
Same issue, maybe [vue.js 3.5 data-allow-mismatch](https://vuejs.org/api/ssr.html#data-allow-mismatch) can solve it, 
The most common case is that a `class` is set with useMediaQuery ref variable, so we can write code list this: 
```html
<div 
    data-allow-mismatch="class" 
    :class="isLargeScreen && 'largeScreen'"
>
     lorem...
</div>
```

Up to now, I've noticed that the latest version([v3.13.1](https://github.com/nuxt/nuxt/releases)) of Nuxt has already supported vue 3.5, I would like to try it later.

**Comment by Tofandel** [comment]
For now I rolled out my own composable to deal with this

```ts
import { createSharedComposable, useBreakpoints as useBreakpointsVueUse } from '@vueuse/core';
import breakpoints from '~/breakpoints';
import { MaybeRefOrGetter } from '@vueuse/shared';

export const useBreakpoints = createSharedComposable(() => {
  type K = keyof breakpoints;
  const ssrSize = 768;

  const mounted = ref<boolean>(false);
  const realBreakpoints = useBreakpointsVueUse(breakpoints);
  onMounted(() => (mounted.value = true));
  const getValue = (point: MaybeRefOrGetter<K>) => Number.parseInt(breakpoints[unref(point)].replace('px', ''));
  const proxyComputed = <Signature>(realMethod: Signature, fakeMethod: Signature): ReturnType<Signature> => {
    return (...args: Parameters<Signature>) => {
      const real = realMethod(...args);
      return computed(() => (mounted.value ? real.value : fakeMethod(...args)));
    };
  };
  return {
    greaterOrEqual: proxyComputed(realBreakpoints.greaterOrEqual, (k) => ssrSize >= getValue(k)),
    smallerOrEqual: proxyComputed(realBreakpoints.smallerOrEqual, (k) => ssrSize <= getValue(k)),
    greater: proxyComputed(realBreakpoints.greater, (k) => ssrSize > getValue(k)),
    smaller: proxyComputed(realBreakpoints.smaller, (k) => ssrSize < getValue(k)),
    between: proxyComputed(realBreakpoints.between, (a, b) => {
      return computed(() => ssrSize >= getValue(a) && ssrSize < getValue(b));
    }),
    isGreater(k: MaybeRefOrGetter<K>) {
      return this.greater(k).value;
    },
    isGreaterOrEqual(k: MaybeRefOrGetter<K>) {
      return this.greaterOrEqual(k).value;
    },
    isSmaller(k: MaybeRefOrGetter<K>) {
      return this.smaller(k).value;
    },
    isSmallerOrEqual(k: MaybeRefOrGetter<K>) {
      return this.smallerOrEqual(k).value;
    },
    isInBetween(a: MaybeRefOrGetter<K>, b: MaybeRefOrGetter<K>) {
      return this.between(a, b).value;
    },
    current: proxyComputed(realBreakpoints.current, () =>
      mountedObject.keys(breakpoints).filter((key) => getValue(key) >= ssrSize),
    ),
    active() {
      const bps = this.current();
      return computed(() => (bps.value.length === 0 ? '' : bps.value.at(-1)));
    },
  };
});
```

**Comment by judy00** [comment]
I might have encountered a similar issue. 
I'm using Nuxt3 + VueUse's `useMediaQuery`, and using `useMediaQuery` to determine the value of a `class`, but even when isLargeScreen is true, the correct dynamic styling isn't applied.

This is my minimal [reproduction](https://stackblitz.com/edit/nuxt-starter-3ntdcv5x?file=pages%2Findex.vue).
