### ISSUE TITLE
Incorrect `createEventHook` types

### ISSUE THREAD

**Issue by zumm** [vueuse/vueuse#4106]
### Describe the bug

You can pass any number of arguments to `trigger` and this is pretty useful, but type says you are limited to just one.

### Reproduction

-

### System Info

```Shell
System:
    OS: Windows Server 2016 10.0.14393
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 4.45 GB / 15.93 GB
  Binaries:
    Node: 18.16.0
    pnpm: 8.6.3
  npmPackages:
    @vueuse/core: ^10.11.0 => 10.11.0
    @vueuse/nuxt: ^10.11.0 => 10.11.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pkc918** [comment]
The `args` parameter is asserted to be a tuple containing only one parameter of type `T`. This means that the `trigger` function only accepts a single argument of type `T` and does not accept multiple arguments. 

The code is as follows:

```ts
const trigger: EventHookTrigger<T> = (...args) => {
  return Promise.all(Array.from(fns).map(fn => fn(...(args as [T]))))
}
```

**Comment by zumm** [comment]
But why there is this limitation? Implementation of trigger (besides type) allows to pass more than one argument. Is there good reason why it should be restricted to just one argument?

**Comment by pkc918** [comment]
I also have the same question, haha.

**Comment by zumm** [comment]
Anyway i think type and implementation should work in same way. Either be restricted to just one argument or allow multiple. Latter is better in my opinion.
