### ISSUE TITLE
useInfiniteScroll still calls onLoadMore even though component is unmounted

### ISSUE THREAD

**Issue by andrewvasilchuk** [vueuse/vueuse#4109]
### Describe the bug

Even though the component is unmounted, the onLoadMore callback is still being called

### Reproduction

https://play.vuejs.org/#eNqVVdtu2kAQ/ZWRX0gksEMuUuUaBFR5SB/aqmn7ZKky9tjesN61vLsEhPj3zvpWAiRRXpB358yZs3Nj58zL0l0bdHwnUHHFSg0KtSmnoWBFKSsNO6gwhT2klSxgQNBBKHrjvL12vbllIVNrWPSGRWsIRSyF0lBGGcLEkl4MosFlKAKvCUwh6aCxKHmkkU4AgcJYMynqAx3z8fSPwd8KwSh8ECkTTONjXEnOYWmywCNAC7UvsB8A92sUEKUaK1DPTMc5ExloCTpaQugsQmcIOkeII86XUbwigUphYhFBLBOcnoQKvPoemOpCKM1IgWXAZAhoA+pcmixvmCXlRKDQ5AFGFNIIjYnbCvU6pUHC1sS05TgJnYQpSsPWh5Tj5jNkUenDbbkJnf5ZwdJoLSnQtrQOzSl0YBZzFq/opk00JZm85oHXID7uv7T+iyP/wCO13fcc1iOW9i6TNih4HWBxCrCsLYAaoC9z4B00gDN0mnYaFVHpPikpqE131iVsDSp0fKhv7B012ijBgtnL0Mm1LpXveUaUq8ylInidfXbljm/dTx5nS4+JBDdu8URMw45nRkCquqfyqMLkNbaXqNmYSMfu1ZuEsazwPTqLOUdmufah2FNStKJRSll2lBLbZ4xj9b20yXyZGmpN+fy1vtOVwV5ZnGO8OnP/pKjXrNAfFSqs1iS7t+moylA35vvHb7ih795YyMTw9pGvGH+iktxYjQ1sYURCsg9wtdqHusI0rL/U/UajUN2jrNA6GzW+LvuXN57+X+6Ne3uQxXpjfWzv9abT9dMBD8t4sPU4o59m6wnDOa29E4oLixnCBV7CZNrIt76So8tldjHoFpTdmfsP7s1ruwDo93jc6GS4VUWzacPTTHYbqIg2oxxZlmsf7sbXJW0hucYqpcr4EBkt+10UcEbzncqKvBgwAXdE469wa8+E2u2AwX4f0Ly1Agw/M+r1H4Wtx3tPoV105inHdH9JrG0ZYqS6uzc3zv4fsqxEDg==

### System Info

```Shell
npmPackages:
  @vueuse/core: ^10.11.0 => 10.11.0 
  vue: ^3.4.33 => 3.4.33
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by andrewvasilchuk** [comment]
I narrowed down the problem to [this line](https://github.com/vueuse/vueuse/blob/main/packages/core/useInfiniteScroll/index.ts#L82). Even though the `element.value` is `null`, the `observedElement.value` still points to the list. It seems like the computed value wasn't recomputed for some reason.

**Comment by zyyv** [comment]
An internal error. You can temporarily manually manage component uninstallation to resolve the error.

[Playground](https://play.vuejs.org/#eNqVVdtO20AQ/ZWpX5JKwW4KSJUxiKTigaq0VSl9slRt7LG9ZL1reXdDUJR/76xvBMJFvFjeuZw5Mzs+3nizqvJXFr3Qi3RS88qARmOrs1jyslK1gQ3UmMEWslqVMKLQUSwH56wz+8HMoZCrc8wHx7xzxDJRUhuoWI5w6kDHIzb6GMsoaAtTSToYLCvBDNIJINKYGK5kc6BjMT37a/FGI1iNlzLjkhu8TmolBCxsHgUU0IW6DtwLwMUKJbDMYA36jpuk4DIHo8CwBcTePPYmYAqEhAmxYMmSCGqNqYuIEpXi2V6pKGjswHVfQhtODBwCphNAV9AUyuZFi6xoJhKloQywslRWGkz9jmjQM41SviKke4GnsZdyTWO4DyETuD6BnFUhHFXr2BvaihbWGEWF7iuX0J5iD84TwZMlWbpB05ApaxYFbcT78xcuf/4kPwqIbf8+g9UBz4aU064oBH3AfD/AoXYBtADDNUfBzgJ4E69dp4OSVf6tVpLWdONS4s6hYy+ExuJstGgHKZbcGWOvMKbSYRBYWS1zny4h6P3nn/zpkf8lEHwRcJni2i9vCWnS45xTIN16oAtWY/oS2uOo8ymBTv1PrwImqsa34FzMc2AOaxvLLQ3FaPqUMp4/GYnbMy6w/lm5YT4eDa2muvvW2ExtcWCWFJgsn7Hfato1R/RXjRrrFdEefIbVOZrWfXH9A9f0PjhLlVrRNfmC8zdqJazj2IbNrUyJ9k5cw/ayuWH6WP/oi7VBqfumHNFmGk18c+1fX2n9ge6hf7QzxUax3qd7g2tffvrA3WvczVDypv/yH4GePCij4PRolVFaIUgaWzvXN/KqS23dGRMayR/LPSJjhzKBMX6E07N2CA5FCfSFysejXuac8rYD7AaVMPldsfSKeIcwbrI/7FT2V0x0Y49lU3qno3Eb3yDt5RDn9sa27xT7z0616PlUI+hkhZsDCYrrloSkl82SrQ8K5HlhQjiefq5IOtUK64zWKQRmjRoENBKcRClTNWVx4BKOCSZc4r07U9RmAxy224hEoiNgxTP61Pzd3BK91QoJ6DOtPIX7R2TdnhMiLat/eOht/wOJtoLa)

**Comment by zyyv** [comment]
This is not a `vueuse` issue. Vue has solved this problem in next versions. You can try upgrading the vue version.
See [Playground](https://play.vuejs.org/#eNqVVdtu2kAQ/ZWRX0gksEMuUuUaBFR5SB/aqmn7ZKky9tjesN61vLsEhPj3zvpWAiRRXpB358yZs3Nj58zL0l0bdHwnUHHFSg0KtSmnoWBFKSsNO6gwhT2klSxgQNBBKHrjvL12vbllIVNrWPSGRWsIRSyF0lBGGcLEkl4MosFlKAKvCUwh6aCxKHmkkU4AgcJYMynqAx3z8fSPwd8KwSh8ECkTTONjXEnOYWmywCNAC7UvsB8A92sUEKUaK1DPTMc5ExloCTpaQugsQmcIOkeII86XUbwigUphYhFBLBOcnoQKvPoemOpCKM1IgWXAZAhoA+pcmixvmCXlRKDQ5AFGFNIIjYnbCvU6pUHC1sS05TgJnYQpSsPWh5Tj5jNkUenDbbkJnf5ZwdJoLSnQtrQOzSl0YBZzFq/opk00JZm85oHXID7uv7T+iyP/wCO13fcc1iOW9i6TNih4HWBxCrCsLYAaoC9z4B00gDN0mnYaFVHpPikpqE131iVsDSp0fKhv7B012ijBgtnL0Mm1LpXveUaUq8ylInidfXbljm/dTx5nS4+JBDdu8URMw45nRkCquqfyqMLkNbaXqNmYSMfu1ZuEsazwPTqLOUdmufah2FNStKJRSll2lBLbZ4xj9b20yXyZGmpN+fy1vtOVwV5ZnGO8OnP/pKjXrNAfFSqs1iS7t+moylA35vvHb7ih795YyMTw9pGvGH+iktxYjQ1sYURCsg9wtdqHusI0rL/U/UajUN2jrNA6GzW+LvuXN57+X+6Ne3uQxXpjfWzv9abT9dMBD8t4sPU4o59m6wnDOa29E4oLixnCBV7CZNrIt76So8tldjHoFpTdmfsP7s1ruwDo93jc6GS4VUWzacPTTHYbqIg2oxxZlmsf7sbXJW0hucYqpcr4EBkt+10UcEbzncqKvBgwAXdE469wa8+E2u2AwX4f0Ly1Agw/M+r1H4Wtx3tPoV105inHdH9JrG0ZYrxx79yrUcTLPHLHzv4fmfxGaw==)

**Comment by andrewvasilchuk** [comment]
@zyyv I'm still using Vue 2.7. Do you think it makes sense to keep your changes to address issues in this older version of Vue? Additionally, `@vueuse/core` states that it supports Vue 2.
