### ISSUE TITLE
useRouteQuery triggers reactivity twice

### ISSUE THREAD

**Issue by aethr** [vueuse/vueuse#4112]
### Describe the bug

When updating a ref created with `useRouteQuery`, `trigger` is called twice:
- once during the `set` method (https://github.com/vueuse/vueuse/blob/main/packages/router/useRouteQuery/index.ts#L68)
- again during the `watch` callback on the route (https://github.com/vueuse/vueuse/blob/main/packages/router/useRouteQuery/index.ts#L94)

This doesn't appear to trigger watchers twice if watching the ref directly. This may be because vue isn't calling watchers if an equality check passes (old value === new value).

This **is** an issue if you create a `computed` with a non-scalar value using the value from the ref, like:

```js
const foo = useRouteQuery('foo');
const bar = computed(() => ({ bar })); // gets re-created twice whenever foo is updated
```

In this case watchers will be called twice because the object created by the computed will not pass an equality check, even if all the inner values are the same.

This is also presumably an issue with `useRouteParams` and `useRouteHash` with both take a similar approach.

I will try to create a PR to fix this by applying the same check inside the watcher that's used in the setter:

```js
  watch(
    () => route.query[name],
    (v) => {
        // add the same equality check to prevent unnecessary trigger
        if (query === v)
          return

      query = v

      _trigger()
    },
    { flush: 'sync' },
  )
```

### Reproduction

https://codesandbox.io/s/async-silence-q52wwm?file=/src/views/Home.vue

### System Info

```Shell
System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 9.01 GB / 31.02 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
  Browsers:
    Chrome: 126.0.6478.126
  npmPackages:
    @vueuse/core: ^10.11.0 => 10.11.0
    @vueuse/router: ^10.11.0 => 10.11.0
    vue: ^3.4.27 => 3.4.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Isn't this what vue expects? Please refer to the [documentation](
https://vuejs.org/guide/essentials/watchers#deep-watchers).

You can watch the `testComputed.value.v` change.
```diff
watch(
- testComputed,
+ () => testComputed.value.v,
  () => {
    watcherActual.value += 1;
  }
);
```

**Comment by aethr** [comment]
@zyyv the issue isn't with deep vs shallow watchers, it's simply that the effect is triggered twice for a single `set` operation.

1. we set a value using the ref in user land code
2. inside the proxy `set` method `trigger` is called, effects are triggered
3. in a `nextTick` in the `set` method we update the URL using `router.replace` or `router.push`
4. this triggers a change to `route.query[name]`
5. we're watching for changes to `route.query[name]`
6. we call `trigger` again **for the value we just set in step 3**, effects are triggered again but the value hasn't changed

If there is a scenario or use case where step 6 is needed I'd be keen to understand it.

My use case is a screen where users can make several different types of selections, with each put in a route query (using useRouteQuery). I create a `computed` object that gathers and transforms them all into the shape I need to send to a backend API query. I watch the computed object for changes, and send a new back-end request each time it does, using the computed object for the back-end query.

Currently, each time the user interacts with any control, the computed triggers two effects for the same user selection, sending duplicate API queries.

```js
// these are passed as props to controls that will set new values when user interacts
const selection = useRouteQuery('selection');
const period = useRouteQuery('period');

const apiParams = computed(() => ({
  area: selection.value,
  period: mapDateStringToDatetime(period.value),
  limit: 100,
  offset: 0,
}));
const apiData = ref();

watch(userParams, async () => {
  // this fetch is triggered twice for a single user selection
  apiData.value = fetch('/api/route', { query: apiParams.value });
});
```

**Comment by Bobakanoosh** [comment]
Another use-case example where this breaks something:

I tried using [unovis](https://unovis.dev/), which by default have an animation when the dataset changes.

I have a `useRouteQuery` hooked up to a filter for the chart, so now when that changes, my `computed` that transforms the data gets recalculated twice within ~300ms of eachother, breaking the animations.
