### ISSUE TITLE
Request of Backport of `@vueuse/router` -> `useRouteQuery` to Vue 2

### ISSUE THREAD

**Issue by klondikemarlen** [vueuse/vueuse#4117]
### Clear and concise description of the problem

I'm still writing some code projects in Vue 2, and I'd love to have all the Vue 3 goodness I can.
Specifically, I have two tables on the same page, and I want to be able to watch the route query params for both tables independently.

### Suggested solution

Using `import { useRoute, useRouter } from "vue2-helpers/vue-route` I have been able to back-port @vueuse/router -> useRouteQuery to Vue 2.

I'd love it if this could be come a standard thing, rather than having to role my own. 

### Additional context

See https://github.com/icefoganalytics/travel-authorization/commit/f899f10013a6e3116c149ccf0b6a760a78d89bca

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sorry, we would no longer add more support to Vue 2 as it already reached EOL. You might need keep using the fork.

**Comment by klondikemarlen** [comment]
I understand completely. I shall take your response back to my project manager, and hopefully they will find the money, so that I don't have to support Vue 2 either!
