### ISSUE TITLE
getting EventBus error on emit

### ISSUE THREAD

**Issue by anurag-gautam-maersk** [vueuse/vueuse#4126]
### Describe the bug

I have created  one event bus file. eventBus.ts
`import { useEventBus } from "@vueuse/core";
export const eventBus = useEventBus<string>("tas-event");
`
Now I want to trigger the event from One file to another file 
lets say 
**a.vue**
```
import { eventBus } from "@/helpers/eventBus";
const oneFunction = ()=>{
const clickHandler = (status: string, label: string) => {
   eventBus.emit("filterAppointments", true);
};
}

```

**b.vue**
```
import { eventBus } from "@/helpers/eventBus";
onMounted(() => {
  console.log(eventBus);
  eventBus.on("filterAppointments", (payload: any,) => {
    console.log("Event received:", payload, arg);
   
  });
});
```
but I am getting below error in EventBus library. 
eventBus.emit("filterAppointments", true);

Can someone help me to reslove this solution 
<img width="650" alt="image" src="https://github.com/user-attachments/assets/0f709ced-6b75-4d8b-aca1-2a357dfa593f">

<img width="479" alt="image" src="https://github.com/user-attachments/assets/4fb9c90c-b668-4b40-9946-91b827423ea9">

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zkbwtc?file=src%2FeventBus.js,src%2FApp.vue,src%2FsecondComp.vue

### System Info

```Shell
Browser
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [ ] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by huiliangShen** [comment]
The utilization of your code is incorrect, plz look the official  example code. 
```ts
import { useEventBus } from '@vueuse/core'

const bus = useEventBus<string>('news')

function listener(event: string) {
  console.log(`news: ${event}`)
}

// listen to an event
 bus.on(listener)

// fire an event
bus.emit('The Tokyo Olympics has begun')

```

**Comment by Nightwishes** [comment]
You should pass in a function instead of a string,
I guess you want to accept parameters,you can write code like this

A.vue
``` javascript
import { eventBus } from "@/helpers/eventBus";
const oneFunction = ()=>{
const clickHandler = (status: string, label: string) => {
  eventBus.emit({ status, label });
};
}
```

B.vue
```javascript
import { eventBus } from "@/helpers/eventBus";
  eventBus.on((params) => {
    console.log('run code', params);
    textData.value = params.label;
  });
```

**Comment by anurag-gautam-maersk** [comment]
@Nightwishes Thanks Its working 👍
