### ISSUE TITLE
useChangeCase is broken in beta

### ISSUE THREAD

**Issue by mathiasrando** [vueuse/vueuse#4139]
### Describe the bug

When running the newest beta version of `useChangeCase` it fails. It works fine when running in development(Nuxt), but it fails after build(Nuxt). The [demo page for useChangeCase](https://vueuse.org/integrations/useChangeCase/#usechangecase) is also broken when selecting the beta version.

![Screenshot 2024-08-08 at 13 02 32](https://github.com/user-attachments/assets/b36c94cb-d1d3-40e8-a720-5679336b64ed)

The code in question(`packages/integrations/useChangeCase/index.ts`):
![image](https://github.com/user-attachments/assets/1030f7b6-c53f-48a8-b318-644f153345b2)

When logging out `changeCase` imported in module it becomes clear that doing `Object.values` won't work as it would have to check the keys in order to match the `endsWith("Case")`:
![image](https://github.com/user-attachments/assets/10f4f52c-9a3e-4e2d-981c-985b661477df)

### Reproduction

https://github.com/vueuse/vueuse/blob/main/packages/integrations/useChangeCase/demo.vue

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 84.19 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 8.6.12 - /opt/homebrew/bin/pnpm
    bun: 1.0.3 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 127.0.6533.90
    Safari: 17.5
  npmPackages:
    @vueuse/core: ^11.0.0-beta.2 => 11.0.0-beta.2 
    @vueuse/integrations: ^11.0.0-beta.2 => 11.0.0-beta.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ilyaliao** [comment]
Closed via #4140 #4130
