### ISSUE TITLE
Updated MaybeRef breaks usage of unref

### ISSUE THREAD

**Issue by johuhype** [vueuse/vueuse#4144]
This is breaking the usage of unref (at least in 2.7)

For `dialogTitle: MaybeRef<string>`, when using
`const title = unref(dialogTitle);`
we are now getting 
![image](https://github.com/user-attachments/assets/6522e3fb-48a9-49d6-8b79-ec00a2b224ed)
instead of `title: string`

Does this mean unref has to get updated or should we use isRef (which is still working as expected for a MaybeRef type)?

_Originally posted by @johuhype in https://github.com/vueuse/vueuse/issues/4099#issuecomment-2283692239_

**Comment by ilyaliao** [comment]
<img width="377" alt="截圖 2024-12-23 晚上10 44 35" src="https://github.com/user-attachments/assets/98ff5a68-0bea-458c-95cc-2700b4f1f292" />

It looks like it's been fixed, feel free to reopen if not.
