### ISSUE TITLE
useWebsocket heartbeat message is allowed to be set to function

### ISSUE THREAD

**Issue by gxy5202** [vueuse/vueuse#4147]
### Clear and concise description of the problem

The scenario in which the heartbeat needs to be given a timestamp each time it returns
`message: () => String(new Date().getTime())`

### Suggested solution

useWebSocket heartbeat message type can be changed to 
```
type MessageReturnType = string | ArrayBuffer | Blob
type MessageType = MessageReturnType  | (() => MessageReturnType)
```
```
function resolveHeartbeatMessage(message) {
    if (typeof message === 'function') {
           return message()
    }
    
    return message ?? DEFAULT_PING_MESSAGE;
}
if (options.heartbeat) {
    const {
      message,
      interval = 1000,
      pongTimeout = 1000,
    } = resolveNestedOptions(options.heartbeat)
     
    const currentMessage = resolveHeartbeatMessage(message);
    const { pause, resume } = useIntervalFn(
      () => {
        send(currentMessage , false)
        if (pongTimeoutWait != null)
          return
        pongTimeoutWait = setTimeout(() => {
          // auto-reconnect will be trigger with ws.onclose()
          close()
          explicitlyClosed = false
        }, pongTimeout)
      },
      interval,
      { immediate: false },
    )

    heartbeatPause = pause
    heartbeatResume = resume
  }
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Mutter45** [comment]
I also think that making messages a function is more adaptable，and submitted relevant pr

**Comment by kkulebaev** [comment]
I encountered the same problem, I think making messages a function would be more flexible

**Comment by antfu** [comment]
https://github.com/vueuse/vueuse/pull/4116 fixes it
