### ISSUE TITLE
Error removing property from getComputedStyle in useCssVar

### ISSUE THREAD

**Issue by pdanpdan** [vueuse/vueuse#4156]
### Describe the bug

The property cannot be removed from computed style.

https://github.com/vueuse/vueuse/blob/a9b49f5bf8ca87540bcd4bf24e8bfa39905bd15c/packages/core/useCssVar/index.ts#L56C9-L56C63

### Reproduction

https://vueuse.org/core/useCssVar/#demo

### System Info

```Shell
Chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VChet** [comment]
Error is also triggered on the demo page https://vueuse.org/core/useCssVar/

![image](https://github.com/user-attachments/assets/0c3bad12-ebe7-437e-9fa1-5d489c73d9bd)
