### ISSUE TITLE
how can i get '@vueuse/docs-utils'

### ISSUE THREAD

**Issue by blackcai** [vueuse/vueuse#4159]
### Describe the bug

demo: https://github.com/vueuse/vueuse/blob/main/packages/core/useAnimate/demo.vue

I can't find this dependency：'@vueuse/docs-utils'

### Reproduction

https://github.com/vueuse/vueuse/blob/main/packages/core/useAnimate/demo.vue

### System Info

```Shell
[vite] Internal server error: Failed to resolve import "@vueuse/docs-utils" from "src/views/core/useAnimate/index.vue". Does the file exist?
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's not published as it's not a public pacakge, and it's not designed for end users to consume. If you need it, feel free to vendor the source code.

**Comment by mybister** [comment]
@antfu 
I am facing a similar issue using Laravel with Vue3. Trying to implement https://vueuse.org/core/useMediaControls as in demo https://github.com/vueuse/vueuse/blob/main/packages/core/useMediaControls/demo.vue npm/Vite-process fails with missing @vueuse/docs-utils (line 3 in the demo code, import { stringify } from '@vueuse/docs-utils').
So how are we supposed to get this public demo running when parts of the required code are not public (per your statement)?

**Comment by blackcai** [comment]
@mybister  I replace it with JSON.stringify, and i had run all the demos, and they only used this method in '@vueuse/docs-utils'.

**Comment by mybister** [comment]
@blackcai thanks a lot!!! Works. Still odd from my POV to see this happen in this demos ...
