### ISSUE TITLE
useSwipe Y swipe error

### ISSUE THREAD

**Issue by bndrmrtn** [vueuse/vueuse#4171]
### Describe the bug

When I use the useSwipe() method, in that area I cannot move the whole page up and down.
I am working on a chat app and I use this for messages. When too many messages under each other, and I want to scroll, the useSwipe also prevents that so I cannot scroll the page up and down. Is there a solution for this?

The attached video demonstrates the issue.

https://github.com/user-attachments/assets/e86defa2-ecc0-4f8a-986d-48e45329cdd6

https://github.com/user-attachments/assets/57550452-c8e2-4cf8-9aa0-e02c441d63ca

### Reproduction

https://vueuse.org/core/useSwipe/

### System Info

```Shell
Any browser.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fabienmacko** [comment]
Hey, same question here. Did you found a solution for this ?

**Comment by bjugan** [comment]
Hi, I had to register the events as not passive to fix a similar problem (set passive option to false). Not sure why though... :-)

**Comment by ilyaliao** [comment]
Hey, I just submitted a PR that addresses the problem. If possible, could you please check if it resolves the issue? Thank you!
