### ISSUE TITLE
使用 onClickOutside 函数在 firefox 浏览器下 ignore 配置项包含 el-checkbox 导致忽略配置失效

### ISSUE THREAD

**Issue by dengjuncong** [vueuse/vueuse#4178]
### Describe the bug

我的项目需要使用 onClickOutside 捕获点击元素外部事件，同时忽略某个外部元素。当忽略的元素内部包含 el-checkbox 组件时。在 firefox 浏览器下点击 el-checkbox 组件同样会触发 onClickOutside 事件，其它浏览如 chrome、edge 则不会出现问题。
示例代码如下：
![screenshot-20240827-174816](https://github.com/user-attachments/assets/46d377c7-f54f-41d8-8d17-21df05856e77)

### Reproduction

无

### System Info

```Shell
Firefox 129.0.2
"@vueuse/head": "^0.7.6"
"vue": "^3.4.31"
"element-plus": "^2.7.7",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Onion-L** [comment]
@dengjuncong 我注意到只有在使用el-checkbox组件时才会出现问题，有可能是不同浏览器对于点击事件的冒泡处理不同。在chrome浏览器中点击事件被触发两次，源码中的event.detail第一次为1第二次为0，但是在firefox中两次均为1。你可以看看是否可以阻止冒泡。
chrome:
![image](https://github.com/user-attachments/assets/aa636d21-5cec-48ed-9aea-1c0710095c37)
firefox:
![image](https://github.com/user-attachments/assets/f9d0387c-6891-47de-9aec-0161b746a6e2)

**Comment by ilyaliao** [comment]
Closed via #4185
