### ISSUE TITLE
Wrong information for elementY when scrolling

### ISSUE THREAD

**Issue by leoatfentech** [vueuse/vueuse#4180]
### Describe the bug

When scrolling, the elementY get changed, if we stop scrolling and move the cursor again the value goes back to its normal.

https://github.com/user-attachments/assets/ede78bd3-b5ab-4a0c-9dbe-2c7016c78558

### Reproduction

https://vueuse.org/core/useMouseInElement/#usemouseinelement

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M3
    Memory: 106.08 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - ~/.nvm/versions/node/v21.7.3/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.3/bin/npm
  Browsers:
    Chrome: 128.0.6613.85
    Safari: 17.6
  npmPackages:
    @vueuse/components: ^10.10.0 => 10.10.0
    @vueuse/core: ^10.10.0 => 10.10.0
    vue: ^3.4.21 => 3.4.27
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pkc918** [comment]
It seems to be an issue with useMouse. When the page has already been scrolled and the mouse moves to get new coordinates, then scrolling again triggers an issue caused by executing `pos[1] + window.scrollY`. To resolve this, the last scroll position of the page needs to be recorded, and the difference between the two scrolls should be calculated.
