### ISSUE TITLE
useWebSocket auto reconnect breaks for ping

### ISSUE THREAD

**Issue by freakbite** [vueuse/vueuse#4181]
### Describe the bug

My solution to issue #4160 caused another auto reconnect issue. When a ping fails it closes the connection using close(), therefor resetting the wsRef, causing no reconnect to run due to the new "wsRef.value = ws" guard.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-u2yhht?file=package.json,src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/core: ^11.0.3 => 11.0.3 
    vue: ^3.2.25 => 3.2.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by freakbite** [comment]
PR created #4182

**Comment by zigomir** [comment]
I just tried @freakbite's https://github.com/vueuse/vueuse/pull/4182 (thank you!) and it fixes the problem for us. I hope it can be reviewed and merged 🙏🤞
