### ISSUE TITLE
`useFileDialog` should also return `onCancel` handler

### ISSUE THREAD

**Issue by AndreyYolkin** [vueuse/vueuse#4183]
### Clear and concise description of the problem

I want user to pick a file to upload, but i don't know if user still selecting the file or he already closed the picker. 

`onChange` triggers only after files selection/reset, but not after dialog just closed and that's ok, we just need another handle for that

### Suggested solution

I propose to extend useFileDialog with additional handler, named `onCancel`, which will be coupled with native `oncancel` event and fire a callback when user just closes the picker without picking a file

### Alternative

Also I can suggest making open() to return a promise (it's void now), which resolves on file changes and rejects on cancel. It solves our case specifically, but could be a breaking change, especially unhandled rejection

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AndreyYolkin** [comment]
Hi, here is the active PR with the implementation: https://github.com/vueuse/vueuse/pull/4184 . Feel free to comment the code 🌟

**Comment by CofCat456** [comment]
I think we can close this issue now!
