### ISSUE TITLE
Doc: Official web page guide example url jump to error

### ISSUE THREAD

**Issue by 13RTK** [vueuse/vueuse#4195]
### Describe the bug

Once I left-click the link in the popup page of hooks in the [examples](https://vueuse.org/guide/#usage-example), the result page is 404.
But if I right-click the link, and choose open in a new tab, it will bring me to the right page.

The same problems exist in all the example hooks popup links(usePreferredDark, useMouse, useLocalStorage)

![image](https://github.com/user-attachments/assets/a0c7157b-4590-4ea9-bafd-3b6a0db5fec1)
![image](https://github.com/user-attachments/assets/6b71b5b7-1f1a-40b3-8143-47983f6630f4)

### Reproduction

https://vueuse.org/guide/#usage-example

### System Info

```Shell
Microsoft Edge Version 128.0.2739.54 (Official build) (arm64)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by averrois** [comment]
I just come to report the same issue that I noticed, when u use the search Modal, the value that u pops up to use takes to 404 page

**Comment by zhangruiKU** [comment]
Developing locally doesn't seem to have this problem, may need to change the connection address to start with https://vueuse.org/core/

**Comment by EvgenyWas** [comment]
It happens only if you navigate to this link in the same tab, if you open it in another tab initially it works.
