### ISSUE TITLE
useFocusTrap: new function

### ISSUE THREAD

**Issue by wheatjs** [vueuse/vueuse#420]
This is a proposal that would live under `@vueuse/integrations` as `useFocusTrap`. It would be a wrapper around https://github.com/focus-trap/focus-trap

My proposed api would look something like although I'm not 100% set on the names for the methods yet. Let me know if you think this would be a good addition and I'll open a PR

```ts
import { ref } from 'vue'
import { useFocusTrap } from '@vueuse/integrations'

const container = ref()
const { isTrapped, activate, deactivate  } = useFocusTrap(container, { options })
```

**Comment by antfu** [comment]
Sounds good!

**Comment by lstoeferle** [comment]
Maybe use `hasFocus` instead of `isTrapped`. Just my opinion 😉 you can also keep it like it is 👍

**Comment by wheatjs** [comment]
> Maybe use `hasFocus` instead of `isTrapped`. Just my opinion 😉 you can also keep it like it is 👍

Yeah I think I might go with that. I was a bit unsure about the name `isTrapped`

**Comment by ronca85** [comment]
how is this used in nuxt 3?
