### ISSUE TITLE
Remove useVModel and useVModels

### ISSUE THREAD

**Issue by ARZarkesh** [vueuse/vueuse#4209]
### Describe the bug

According to vue latest updates which added `defineModel` macro, I suggest to deprecate these two composables.

### Reproduction

Nothing.

### System Info

```Shell
Nothing.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alfred-Skyblue** [comment]
We need to ensure that it works properly in Vue 2.

**Comment by antfu** [comment]
We could update the docs to mention that and do soft deprecation. PR welcome :)

**Comment by MetRonnie** [comment]
Does the composable do anything special when using with `setup()` in the Options API?

The docs example for `useVModel` omits defining the prop and `emits`:

https://vueuse.org/core/useVModel/#usage
```js
import { useVModel } from '@vueuse/core'

export default {
  setup(props, { emit }) {
    const data = useVModel(props, 'data', emit)

    console.log(data.value) // props.data
    data.value = 'foo' // emit('update:data', 'foo')
  },
}
```

However it looks like it doesn't do anything magic for `props` and `emits`, you still have to define those yourself?

**Comment by Shinigami92** [comment]
Does Vue 3 already have support for `useVModel(props, 'propname', emit, { passive: true, deep: true })`, to deeply react on arrays?

**Comment by alexzhang1030** [comment]
I'm not sure. We are developing a project with Vue and Tsx, which heavily relies on `useVModel`.

**Comment by Shinigami92** [comment]
> We could update the docs to mention that and do soft deprecation. PR welcome :)

@antfu potentially I (or someone else if someone is faster) should update docs to suggest using `defineModel`, but `useVModel` is here to stay for now based on the community specific use-cases.
