### ISSUE TITLE
Remove redundant `delay` parameter from `execute` function in `useAsyncState` composable

### ISSUE THREAD

**Issue by 1337huania** [vueuse/vueuse#4214]
### Clear and concise description of the problem

The `execute` function in `useAsyncState` currently accepts a `delay` parameter.

This parameter is potentially redundant because `delay` can be managed by calling `promiseTimeout` before invoking `execute`:
```js
await promiseTimeout(1000)
await execute(payload)
```

Additionally, the `delay` parameter complicates the process of calling `execute` with a payload directly, as it requires passing an `delay` argument or wrapping execute in another function (e.g. direct event handling `@customEvent="(value) => execute(0, value)"` instead of `@customEvent="execute"`).

Link to [VueUse Playground](https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2QAfAAdcwqVMZoqsCBp7DwNAqYDAJwFou+FQHA7J4Zp4hZnPJsxgALZlQ9lTEQzkAC8mZAxJH3d7oTAiGHIGwpDwpUQHHHOZ75zsEBLM5HnplAUQ2lJjBUABJEB4VZNpJUkNIowPEPZVz3Wz3k2BrOmKypkDfUnWDbDJ+iCto2zbps8wrSEQdBanU0jlv4NyhsgIS2AC-5pAcNQcLMKgAOQOjcnJ1IgBHZtmMzYH+SF-omiAnnuUAHiedDINWxZ+Dhg7IYgqHoVAmEMdoE4QGhtg6HQoK8cSjiDum5YTj20gcGEwDKb21G0dYyDajRaS8RAkQQMENSINIdjaAABuaaLDPs8hgAm3C6FKNAcNeIQ+DMNC2nMCRUDqwynsA0kHNZz5rlp8i0VQiauEZJlmbp+k3JMjnYNoUW9r21jSJw5gAAp4fQ6W6VKHjaPFN45b2OFQImdg6MueEcI4GnRT2+WFSoJWzOxiCTNYuwytI2itXUdU9gcE6zdg9iMswkp1MWDFRuQMYgHGzkMSmzYTrUKqzng8isC+KilPAs5BPAfQUAArKSpJuJUMBoPFHAwI9z0XUYQabLOAB+KgzAYF2pJs0iztwKrLhdYCzo0F2lKty6znh-A0FQq5vrmelbvEnrQyOAAsmzgyA36Vv2BiqPWjYE9gePJkzRNQ7OyB4K9X1oLd90AJzPTz73eNAwQhD9I4qHgs7SBQyNUwAsuwkI-gmS4GIBjOQMz2bgRmUGSDIRA0AG2CIP1gzaJ1PYa54ZaYZIJaMBOtPkGWAByC5LhwrvYAci31gcQA)

### Suggested solution

- Remove the delay parameter from the execute function: Simplifies the API by removing unnecessary parameters.
- Simplify the function signature to allow direct payload execution: Streamlines the process of calling execute with payloads, making it more intuitive and reducing boilerplate.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by alexzhang1030** [comment]
this requires the current scope to be `async` scope. I think `delay` is more convenient than`promiseTimeout`

**Comment by alexzhang1030** [comment]
Closing via this might introduce a breaking change. If you have other ideas, feel free to open a new issue. Thanks a lot.
