### ISSUE TITLE
Global Event Bus

### ISSUE THREAD

**Issue by brokolosov** [vueuse/vueuse#422]
Any plans for adding a global event Bus? For example wrapper to [mitt](https://github.com/developit/mitt)

**Comment by antfu** [comment]
Do you have any proposal API in mind?

**Comment by brokolosov** [comment]
Just like the rest...

`
import { useBus } from '@vueuse/core'

export default defineComponent({
  setup() {
    const {emit, on, off} = useBus()

   emit('foo-event', {value: 'bar'})
  },
})
`

**Comment by lstoeferle** [comment]
> Just like the rest...
> 
> ```es6
> import { useBus } from '@vueuse/core'
> 
> export default defineComponent({
>     setup() {
>     const {emit, on, off} = useBus()
> 
>     emit('foo-event', {value: 'bar'})
>   },
> })
> ```

I'm using [mitt](https://github.com/developit/mitt) for custom events in Vue3. Could be used as an integration function 😉
