### ISSUE TITLE
useSortable: wrong order of elements

### ISSUE THREAD

**Issue by liuhbin** [vueuse/vueuse#4222]
### Describe the bug

Same issue as #2924, which was fixed in #2926, the bug reappeared after merging #3322.

The problem mentioned in #3216.
After `const element = array.splice(from, 1)[0]`, the missing element in `nextTick(console.log(array))` should be the expected behavior.

### Reproduction

https://vueuse.org/integrations/useSortable/

### System Info

```Shell
-
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Mutter45** [comment]
Thanks for your feedback

I seem to be having the same problem；
![image](https://github.com/user-attachments/assets/ef509b66-7e73-45e3-b41e-73d5ca4a6b38)

It seems that the following code causes the DOM to be re-rendered
```
(list as MaybeRef).value = array
```

**Comment by alexmnv** [comment]
As a workaround one can explicitly call `moveArrayElement` and pass the array by value. The `list` parameter must be a `Ref`, not a `ShallowRef`.

```
import { useSortable, moveArrayElement } from "@vueuse/integrations/useSortable";

useSortable(el, list, {
  onUpdate: (e) => moveArrayElement(list.value, e.oldIndex, e.newIndex)
});
```
