### ISSUE TITLE
`useFetch` does not stringify array payload

### ISSUE THREAD

**Issue by abdul-alhasany** [vueuse/vueuse#4234]
### Describe the bug

When sending an array as a payload in `useFetch`, it does not get stringified. 

As per the  reporoduction example, under payload tab (devtools) you would see `[object Object]` 

![image](https://github.com/user-attachments/assets/fac53d0b-5f2a-45b0-9a2f-def97dd69dd8)

Objects work as expected. 

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2QAfAAdcwqZOlAIJcznKBBWAAXkzLFIpXo0kr6eQ1dryeG+f68iz2BbaeIneewukRDoWrq0hUwH8NwsiGkdhUBxqHFmKgA5A6bpy6ogV9nh9qOGOJ9YTAujEu8KuFjvsNmZthkGPahwL2WVMftFhUg+0NIOORGEkdQwL4aA1IYNwHD69i3vID7jionoygEaQLq+eLTrOujaCu5posM5qlGYkx1PAwzag+K4AROw4EGmiaIKBRjgSh9iTOR0jaE+eCsfs8jaPYADc2bZkY-CyqKKiNjWwT8eO2YqAhmxIak-HZgcjIHAcQA

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 6.02 GB / 15.95 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.3.0 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.4 - ~\.bun\bin\bun.EXE
  Browsers:
    Chrome: 128.0.6613.138
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vueuse/core: ^11.1.0 => 11.1.0
    vue: ^3.5.6 => 3.5.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Curs3W4ll** [comment]
Same issue here

**Comment by see-more** [comment]
You can specify the payloadtype when use `post(payload,type)` 
```javascript
import { useFetch } from '@vueuse/core'
import { ref } from 'vue'

const form = ref([{test:true, working: false}])
const { execute } = useFetch('https://httpbin.org/post', { immediate: false }).post(form,'json').json();

function submit() {
  execute()
}
```

**Comment by abdul-alhasany** [comment]
Amazing. It resolved the issue.
