### ISSUE TITLE
jest tests are failing for vue2 and 3

### ISSUE THREAD

**Issue by gluecksmensch** [vueuse/vueuse#425]
I cloned `vueuse` to my local machine to get some inspiration of how you included `vue-demi`. After `npm install` and running the tests (`npm run test:2` or `npm run test:3`) I get jest errors.

For vue 3 tests only: `Cannot find module 'jwt-decode' or its corresponding type declarations.`.
For vue 2 there are 26 failed tests.

Node: v14.15.4
npm: 6.14.10

**Comment by wheatjs** [comment]
Since VueUse uses yarn workspaces can you try running `yarn install` instead and then try running the tests
