### ISSUE TITLE
SwipeDirection no longer exported

### ISSUE THREAD

**Issue by u12206050** [vueuse/vueuse#4256]
### Describe the bug

When using useSwipe in typescript, I was able to import the `SwipeDirection` enum to use in my logic like so:
```
const { direction } = useSwipe(el);
watch(direction, dir => {
	if (dir === UseSwipeDirection.LEFT) 'ping';
	if (dir === UseSwipeDirection.RIGHT) 'pong';
});
```
		
After the latest updates, this has been renamed to `UseSwipeDirection` but also isn't exported anymore so I can't use it. It is basically a breaking change but couldn't find any mention of the change in the release notes.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-xqpywp?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1
    Memory: 312.58 MB / 16.00 GB
    Shell: 3.2.2 - /usr/local/bin/sh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 129.0.6668.70
    Edge: 129.0.2792.52
  npmPackages:
    @vueuse/core: ^11.1.0 => 11.1.0 
    @vueuse/integrations: ^9.13.0 => 9.13.0 
    vue: ^3.5.6 => 3.5.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This was an intended breaking change of VueUse v11: https://github.com/vueuse/vueuse/commit/f285c12eca3c2f746c4c5bf50235fc5cb7f8112e

Use literal strings like `'left'` instead.
