### ISSUE TITLE
Failed to resolve entry for package "@vueuse/core" error in my vitepress projects. 

### ISSUE THREAD

**Issue by DeFUCC** [vueuse/vueuse#428]
Can't figure out why this error suddenly crashed my two vitepress projects. I've got vueuse v 4.7.0. The only thing I've done is installed `n` package and changed my node js version to v. 14.  

```
vitepress v0.12.2
vite v2.1.2
failed to start server. error:
 Error: Failed to resolve entry for package "@vueuse/core". The package may have incorrect main/module/exports specified in its package.json.
   ...
 ERROR  Command failed with exit code 1.
```
`vueuse` is used only for dark mode toggle in the theme, so removing the buttons helps to revive my sites for now. Please, help me cope with this sudden break.

**Comment by DeFUCC** [comment]
Sorry, deleting mode_modules helped me with this issue.

**Comment by dheimoz** [comment]
thanks @DeFUCC for the follow up.
