### ISSUE TITLE
useRouteQuery effect triggers twice

### ISSUE THREAD

**Issue by jack-allocate** [vueuse/vueuse#4281]
## What triggers it?
This only seems to happen when the watch source is a getter that returns an object, and when using transform:
```ts
const pageNumber = useRouteQuery('pn', 1, { transform: Number })
() => ({pageNumber: pageNumber.value})
```
but not
```ts
const pageNumber = useRouteQuery('pn', 1, { transform: Number })
() => pageNumber.value
```

## The Issue
If you were to put a breakpoint on L92 of `useRouteQuery` in my reproduction, you would find the following:
![image](https://github.com/user-attachments/assets/aac15975-7316-416b-a63b-a8571dccd1a7)

As you can see, `route.query.pn` is `"6"`, but the internal value of `query` is `6`, due to the fact that I pass a `transform`. Since `"6" === 6` is false, it bypasses the fix implemented in https://github.com/vueuse/vueuse/pull/4113, causing the reactivity to still trigger twice.

## Code Changes
Problematic lines of code: https://github.com/vueuse/vueuse/blob/798077d678a2a8cd50cc3c3b85a722befb6087d4/packages/router/useRouteQuery/index.ts#L92-L93

Proposed Change:
```ts
  if (query === transform(v))
        return
```

## Incorrect test case
I believe the following test case (and potentially other test cases) is flawed.
https://github.com/vueuse/vueuse/blob/798077d678a2a8cd50cc3c3b85a722befb6087d4/packages/router/useRouteQuery/index.test.ts#L247

In the actual vue router, `route.query.page` would *never* be a `number`, it would always be a `string`, since it comes directly from the URL.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-21psys?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/core: ^7.6.2 => 7.6.2 
    @vueuse/router: ^11.1.0 => 11.1.0 
    vue: ^3.2.25 => 3.2.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by star-hs** [comment]
这带来了新的问题，举例：
```javascript
  const page_size = useRouteQuery('page_size', '10', {
    transform: {
      get: (v: string | undefined) => v ? Number(v) : 10,
      set: (v: number) => v === 10 ? undefined : v.toString(),
    }
  });
  const duration = useRouteQuery('duration', '', {
    transform: {
      get: (v: string | undefined) => v ? v.split(',').map(Number).filter(i => !isNaN(i)) : [],
      set: (v: number[]) => v.length ? v.join(',') : undefined,
    }
  });

  watch(
    [duration, page_index],
    (_1, _2, onCleanup) => {
      const p = fetchWorkorderList();
      onCleanup(() => {
        p.cancel();
      });
    },
    {
      immediate: true,
    },
  );
```
当我修改pageindex从1改成2的时候。@vueuse/router中index.mjs中的query变化为：
1、let query = route.query[name]; // undefined
2、v = transformSet(v);
query = v === toValue(defaultValue) ? void 0 : v; // 字符串2
这本身是预期的，但是watch () => route.query[name]的时候，if (query === tranformget(v))会导致 if ('2' === 2) 最终没有return而是走到下面的_trigger();

这本身并不会带来什么问题，问题就出在我代码中的watch，是watch的多个依赖项。
_trigger()导致我代码中的watch再次开始比对，恰好我duration这种依赖项因为是引用类型，实际的地址变了，导致又触发了一次watch handler。最终导致我每次会点下一页实际触发了两次fetchWorkorderList。

我当然可以在代码里规避这个问题，我想表达的是，这个useRouteQuery的设计是有缺陷的，特定情况下会触发bug。

**Comment by star-hs** [comment]
#4112 已经解决了重复触发的问题，这个对我来说足够了。当前issue的解决方案能解决本issue描述的问题，但无异于引入了新的BUG

我认为造成这种新的MR解决了新的issue却导致旧病复发的根本原因是早期设计的失误。一开始transform就该支持get/set，怎么可以只有一种。
