### ISSUE TITLE
Nuxt module doesn't install @vueuse/core

### ISSUE THREAD

**Issue by Mateleo** [vueuse/vueuse#4285]
#### Steps to Reproduce:
1. Ran the following command to install `@vueuse/nuxt` as a Nuxt module:
   ```bash
   pnpm add @vueuse/nuxt@latest -D --ignore-scripts
   ```
2. After installation, I noticed that the package `@vueuse/core` was missing.

#### Expected Behavior:
According to the [official documentation](https://vueuse.org/nuxt/README.html), the `@vueuse/core` package should be installed alongside `@vueuse/nuxt`. This is not happening during the installation process.

Btw should `@vueuse/nuxt` and `@vueuse/core` be added to the project's `devDependencies`, or `Dependencies`?

### Reproduction

https://github.com/Mateleo/mini-reproduction-nuxt-vueuse

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 AMD Ryzen 5 2400G with Radeon Vega Graphics
    Memory: 7.91 GB / 15.93 GB
  Binaries:
    Node: 22.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.89)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @vueuse/nuxt: ^11.1.0 => 11.1.0
    vue: latest => 3.5.12
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by OrbisK** [comment]
Hey, you seem to have confused `npx nuxi@latest module add` with `pnpm add`. Using `nuxi` should install the deps.

If your project is not released as a package, it doesn't matter whether you put it in deps or devDeps. I always put everything in devDeps :)


feel free to reopen the issue if needed :)
