### ISSUE TITLE
useElementBounding cannot update the position changes caused by async components loading.

### ISSUE THREAD

**Issue by wtto00** [vueuse/vueuse#4288]
### Describe the bug

The page uses `defineAsyncComponent` to introduce an asynchronous component. Waiting for the asynchronous component to load can cause layout changes on the page, and `useElementBounding` cannot recognize the position changes resulting from this situation.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-d1tgzf?file=package.json,src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 446.12 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - ~/Library/Caches/fnm_multishells/40536_1729329533174/bin/node
    npm: 10.8.1 - ~/Library/Caches/fnm_multishells/40536_1729329533174/bin/npm
    pnpm: 9.12.2 - ~/Library/Caches/fnm_multishells/40536_1729329533174/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.101
    Edge: 130.0.2849.46
    Safari: 17.2
  npmPackages:
    @vueuse/core: ^11.1.0 => 11.1.0 
    vue: ^3.5.10 => 3.5.12
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wtto00** [comment]
`useElementBounding` cannot update the position changes caused by `transitioin` or `animation`.

https://stackblitz.com/edit/vitejs-vite-d1tgzf?file=package.json,src%2FApp.vue

- Click the refresh button in right preview frame.
- Click `Update top & bottom` button to check `async components`.
- Click `Update left & right` button to check `transitioin or animation`.

**Comment by CofCat456** [comment]
try this https://stackblitz.com/edit/vitejs-vite-juwlhb?file=src%2FApp.vue

**Comment by wtto00** [comment]
@CofCat456 Thanks very much.

Perfect, this solution basically works. However, it seems there's a slight discrepancy with the `animationend` callback. I tried adding a `setTimeout(0)`, but it didn't seem to help.
