### ISSUE TITLE
[Bug]: Ctrl is not working with useMagicKeys

### ISSUE THREAD

**Issue by jd-0001** [vueuse/vueuse#429]
Your provided code snippet which includes `Ctrl` example also isn't working.

I even tried it in Vue 3 with a fresh installation.

### Isn't working (From docs page)
```vue
<script setup>
import { watch }  from 'vue'
import { useMagicKeys } from '@vueuse/core'

const keys = useMagicKeys()
const shiftCtrlA = keys['Shift+Ctrl+A']

watch(shiftCtrlA, (v) => {
  if (v)
    console.log('Shift + Ctrl + A have been pressed')
})
</script>
```

### Works (`ctrl` is removed)
```vue
<script setup>
import { watch }  from 'vue'
import { useMagicKeys } from '@vueuse/core'

const keys = useMagicKeys()
const shiftCtrlA = keys['Shift+A']

watch(shiftCtrlA, (v) => {
  if (v)
    console.log('Shift + Ctrl + A have been pressed')
})
</script>
```

### Isn't working
```vue
<script setup>
import { watch }  from 'vue'
import { useMagicKeys } from '@vueuse/core'

const keys = useMagicKeys()
const shiftCtrlA = keys['Ctrl+A']

watch(shiftCtrlA, (v) => {
  if (v)
    console.log('Shift + Ctrl + A have been pressed')
})
</script>
```

**Comment by wheatjs** [comment]
Thanks for the report, can confirm it is not working. As a workaround until we get this fixed you can use `control` instead of `ctrl`. You can also use `controlLeft` and `controlRight`. We can see if @antfu wants to rename control to `ctrl` though since that seems like his original intention.

**Comment by jd-0001** [comment]
Hi @antfu using

```
const { Ctrl_k } = useMagicKeys()
```

Opens browser search along with hotkey trigger. But if you check VueUse docs, triggering *ctrl+k* doesn't open browser search.

So do we have anything which doesn't open browser search or in general disable system/app hotkeys?

**Comment by antfu** [comment]
I would say it's better to avoid overriding system hotkeys. But if you want, you can do it by:
https://vueuse.org/core/useMagicKeys/#custom-event-handler
