### ISSUE TITLE
When scroller reaches the threshold value and stays there, function is triggered continuously

### ISSUE THREAD

**Issue by shaik4949** [vueuse/vueuse#4301]
### Describe the bug

When i scroll down to reach threshold value, and stays there, function is triggered continuously. I want to trigger the function only once when scroll position is unchanged and stays in threshold value. 

### Reproduction

it is not on any repo

### System Info

```Shell
chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CofCat456** [comment]
Do you mean `useInfiniteScroll`?

**Comment by shaik4949** [comment]
Yes when I used it, I am getting above problem

**Comment by CofCat456** [comment]
Sorry, could you provide me with a minimal reproduction?

**Comment by shaik4949** [comment]
@CofCat456 Here is my code explained:

`<table ref="tableRef">
  <thead>....</thead>
  <tbody>....</tbody>
</table>
<script lang="ts">
  import { defineComponent } from "vue";
  import { useInfiniteScroll } from "@vueuse/core";
  export default defineComponent({
  name: "Table_Component",
  components: {},
  mounted() {
    this.setupInfiniteScroll(this.$refs.tableRef);
  },
  methods: {
    setupInfiniteScroll(target: any) {
      if (target) {
        useInfiniteScroll(target, this.handleScroll, {
          threshold: 20, // Distance from the bottom to trigger the infinite scroll
        });
      } else {
        console.error("Target is undefined!");
      }
    },
    handleScroll() {
      //Here API is being called
    }
  },
});
</script>
`

In above code, when user scrolls to the bottom of table, condition is satisfied and handleScroll() is being called. 

When user scrolls to bottom of table first time, handleScroll() is called which calls API. Now scroller position shifts up due to addition of items in table.

Now again when user scrolls to bottom of table 2nd time, handleScroll() is called which blocks API call as no more items are present. And scroller position remains in the bottom. 

Since scroller position is unchanged, handleScroll() is being called continuously. <== This i want to stop. I want handleScroll() method to be called only once as soon as scroller reaches bottom. It should not be called continuously. 

Hope you understood the usecase now?

**Comment by CofCat456** [comment]
Yes, thanks for providing the code. I think you can use **canLoadMore** to temporarily solve this problem. When no more items to scroll, returning false from canLoadMore can stop.

**Comment by shaik4949** [comment]
Can u give me example usage of canLoadMore ? Sample code will be helpful (I tried to search usage from https://vueuse.org/core/useInfiniteScroll/ website, but couldn't find any sample or description)

**Comment by CofCat456** [comment]
Like this https://stackblitz.com/edit/vitejs-vite-n49yoe?file=src%2FApp.vue
