### ISSUE TITLE
`useVModelObject`

### ISSUE THREAD

**Issue by sapphi-red** [vueuse/vueuse#431]
This is a new function proposal.

This function is a helps implementing `v-model="obj"`.

### Usage 
```vue
<template>
  <div>
    <input v-model="a" type="text" />
    <input v-model="b" type="text" />
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType, watch } from 'vue'
import { useVModelObject } from './useVModelObject'

export default defineComponent({
  props: {
    modelValue: {
      type: Object as PropType<{ a: string, b: string }>,
      required: true
    }
  },
  setup(props) {
    const data = useVModelObject(props)
    return { ...data }
  }
})
</script>
```

### Sample implementation
```ts
import { computed, getCurrentInstance, WritableComputedRef } from 'vue'

export const useVModelObject = <P, K extends keyof P>(
  props: P,
  key = 'modelValue' as K,
  emit?: (name: string, ...args: any[]) => void
): { [KK in keyof P[K]]: WritableComputedRef<P[K][KK]> } => {
  const vm = getCurrentInstance()
  const _emit = emit ?? vm!.emit

  const computedObject: any = {}
  for (const k of Object.keys(props[key])) {
    computedObject[k] = computed({
      get() {
        return (props[key] as any)[k]
      },
      set(v) {
        _emit(`update:${key}`, { ...props[key], [k]: v })
      }
    })
  }
  return computedObject
}
```

**Comment by antfu** [comment]
I kinda get what are you trying to achieve - destructure the props object into an object of refs right? I found this name could be a bit confusing. Also, think this could be quite common when you want to use `toRefs` for a `Ref<{ ... }>`, maybe we can have something a bit more general. Meaning:

```ts
const objRef = ref({ x: 5, y: 6 })
const { x, y } = toNestedRefs(objRef)
```

So in your cases, we can simply have

```ts
const { a, b } = toNestedRefs(useVModel(props, 'modelValue'))
```

(not sure the naming yet

WDYT?

**Comment by sapphi-red** [comment]
Oh yes, the function you suggested is what I actually wanted to have. Great!

This function (`toNestedRefs`) and `toRefs` have a similar return values, so I think the name should be `toRefsFromObjectRef` / `toRefsFromRef` or something: a name which specifies the input value.

**Comment by antfu** [comment]
The implementation looks good, just need to find a proper name. 

- toNestedRefs
- toRefsFromObjectRef
- toRefsFromRef
- refToRefs
- toRefs (extend the functionality of Vue's toRefs, fallback to Vue's toRefs when it's not a ref of object)
- computedRefs

/cc @vueuse/team WDYT?

**Comment by wheatjs** [comment]
Hmm personally I like the idea of extending `toRefs` although I can maybe also see `toRefsFromRef` or `refToRefs`. `computedRefs` doesn't make too much sense to me though and `toRefsFromObjectRef` is a bit long and I'm not sure how clear `toNestedRefs` is.

**Comment by Tahul** [comment]
I really like the idea.

The "toNestedRefs" naming seem pretty clear to me.

I really love the idea of "extending" the `toRefs()` function too.

**Comment by sapphi-red** [comment]
Extending `toRefs` sounds great. I will make a PR.
