### ISSUE TITLE
useBase64 result is not look like it's name

### ISSUE THREAD

**Issue by juetan** [vueuse/vueuse#4311]
### Describe the bug

when input is string or something, the result is actually Data URL instead of base64, is that expected?

### Reproduction

https://vueuse.org/core/usebase64/

### System Info

```Shell
chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jackcodetw** [comment]
Do you mean `aGVsbG8gd29ybGQ=...` instead of `data:text/plain;base64,aGVsbG8gd29ybGQ=?`

**Comment by juetan** [comment]
> Do you mean `aGVsbG8gd29ybGQ=...` instead of `data:text/plain;base64,aGVsbG8gd29ybGQ=?`

yes, maybe useDataURL for data:text/plain;base64,aGVsbG8gd29ybGQ=?

**Comment by antfu** [comment]
Yeah, you are right. At least we should align with the output format to have it consistent. We could have an option to specify the dataURL should be outputted. PR welcome
