### ISSUE TITLE
useFileDialog does not work on macos safari when open function is not directly bound to the template

### ISSUE THREAD

**Issue by Fsystem** [vueuse/vueuse#4315]
### Describe the bug

```
<template>
<li @click="replaceOpenCheck">
  <span>xxx</span>
</li>
</template>
<script setup>
import {
  useFileDialog
} from '@vueuse/core'

async function replaceOpenCheck() {
  // do something
  if (xxx()) {
    return
  }
  replaceOpen()
}
const {
  files: replaceFiles,
  open: replaceOpen,
  reset: replaceReset,
  onChange: onReplaceChange
} = useFileDialog({
  accept: '.zip',
  directory: false,
  multiple: false,
  reset: true
})
onReplaceChange((files) => {
  console.log(files)
}
</script>
```

### Reproduction

<template> <li @click="replaceOpenCheck">   <span>xxx</span> </li> </template> <script setup> import {   useFileDialog } from '@vueuse/core'  async function replaceOpenCheck() {   // do something   if (xxx()) {     return   }   replaceOpen() } const {   files: replaceFiles,   open: replaceOpen,   reset: replaceReset,   onChange: onReplaceChange } = useFileDialog({   accept: '.zip',   directory: false,   multiple: false,   reset: true }) onReplaceChange((files) => {   console.log(files) } </script>

### System Info

```Shell
macos intel 13.7
"@vueuse/core": "^11.1.0"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jackcodetw** [comment]
Hi, could you elaborate more on what you mean by "not working"?

**Comment by Fsystem** [comment]
Additional information, as follows， I test it does not work on safari
https://stackblitz.com/edit/vitejs-vite-zfn3pf?file=package.json

**Comment by jackcodetw** [comment]
Thanks, I see

**Comment by jackcodetw** [comment]
It seems to be related to [Safari's security reasons](https://medium.com/@fibianmejia/navigating-click-events-handling-hidden-inputs-in-safari-vs-chrome-139bce1e29b2).

Here is another minimal reproduction
https://stackblitz.com/edit/vitejs-vite-bvakvd?file=src%2FApp.vue

**Comment by Fsystem** [comment]
I see. Maybe I need to show a message box to tell the user to reclick.
