### ISSUE TITLE
`useUserMedia` "devices" example has type errors

### ISSUE THREAD

**Issue by manniL** [vueuse/vueuse#4321]
### Describe the bug

The [vueuse.org/core/useUserMedia](https://vueuse.org/core/useUserMedia/) in the `useUserMedia` docs is faulty and throws type errors as `constraints` nested values don't accept a ref.

![](https://private-user-images.githubusercontent.com/13759936/269010047-d0aff605-aff5-45a7-861f-52c39ceb0a87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NTQ2MDYsIm5iZiI6MTczMDY1NDMwNiwicGF0aCI6Ii8xMzc1OTkzNi8yNjkwMTAwNDctZDBhZmY2MDUtYWZmNS00NWE3LTg2MWYtNTJjMzljZWIwYTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE3MTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkOTA5ZGU0Nzc1OTEzN2QzYzQ3ZTFmNzlkOTMwZGMwN2VjYWFkM2E1YWI4ZmFmMDFiOWQwYjZmZGU2YjUyYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CVAz7hl3mrfMiHX6azj_CUxq3-TuPvNcXbRJk2NlpDk)

Originally reported in https://github.com/vueuse/vueuse/issues/3414

### Reproduction

https://stackblitz.com/edit/vueuse-4321?file=src%2FApp.vue (StackBlitz doesn't show TS errors well, running locally is easier).

### System Info

```Shell
stackblitz
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ilyaliao** [comment]
I think we can close this issue!

**Comment by manniL** [comment]
Thanks for fixing! Resolves by #4322
