### ISSUE TITLE
Allow `useRafFn` to accept `MayBeRef` for fps limit.

### ISSUE THREAD

**Issue by Jannchie** [vueuse/vueuse#4335]
### Clear and concise description of the problem

Currently, `useRafFn` cannot dynamically adjust the frame rate, because the `fpsLimit` option is a normal number, and cannot be a ref value. In applications like games, being able to adjust the frame rate through settings is a common requirement. I experimented with changing it to `MayBeRef`, which allows control of the frame rate using a ref value. I am willing to submit a pull request for this enhancement.

### Suggested solution

Basically, it’s just necessary to modify the `useRafFn` options signature and change the internal variable to a computed property:

```ts
const intervalLimit = computed(() => {
  const value = unref(fpsLimit)
  return value ? 1000 / value : null
})
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ilyaliao** [comment]
Closed via #4409
