### ISSUE TITLE
UseMouse produces incorrect values in scroll event handler

### ISSUE THREAD

**Issue by JustinBordage** [vueuse/vueuse#4345]
### Describe the bug

As the title says the mouse position produces incorrect values specifically when a scroll event is triggered without any movement from the mouse. This is because it uses the extractor type that it uses is "page" (which is actually the only type that allows scroll detection). However, the problem is that the "event.pageX" & "event.pageY" already include the window scroll offset, so when it adds the scroll position, it's actually adding it to a value that already includes it.

To clarify the values handled in the scroll event handler actually produces a sum from the following pseudo-code:
`pixelsFromTopLeftEdgeExcludingScroll + oldScrollOffset + currentScrollOffset`

To correct this, the scroll event handler should instead be using "event.clientX" & "event.clientY" not whatever extractor that is computed from the "type" options property. The demo repository I linked below has a copy of the useMouse composable which I've hot-fixed to correct the bug, as well as a visual comparison between the current implementation & the hot-fixed implementation.

I've tested this on the both the Chrome & Brave browsers.

Tested package versions:
- Project 1 (Private Repo):
      - @vueuse/core: ^10.7.0 => 10.7.0 
      - vue: ^3.4.21 => 3.4.29
- Project 2 (Demo repro linked below):
      - @vueuse/core: ^11.2.0 => 11.2.0
      - vue: ^3.5.12 => 3.5.13

### Reproduction

https://github.com/JustinBordage/useMouse-Scrolling-Bug

### System Info

```Shell
System:
    OS: Linux 6.11 Fedora Linux 40 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
    Memory: 11.51 GB / 30.65 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
Binaries:
    Node: 20.17.0 - /usr/bin/node
    npm: 10.8.2 - /usr/bin/npm
Browsers:
    Brave Browser: 130.1.71.123
    Chrome: 130.0.6723.116
npmPackages:
    @vueuse/core: ^11.2.0 => 11.2.0
    vue: ^3.5.12 => 3.5.13
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ilyaliao** [comment]
I think #4244 already fix this.

**Comment by JustinBordage** [comment]
> I think #4244 already fix this.

Possibly, I'll check it out tomorrow.

**Comment by JustinBordage** [comment]
> > I think #4244 already fix this.
> 
> Possibly, I'll check it out tomorrow.


Sorry this took so long to validate, I had work responsibilities that kept me busy since my last comment. After trying it out, I can confirm that yes issue #4244 does fix the issue mentioned above.

**Comment by JustinBordage** [comment]
> > I think #4244 already fix this.
> 
> Possibly, I'll check it out tomorrow.


Sorry this took so long to validate, I had work responsibilities that kept me busy since my last comment. After trying it out, I can confirm that yes Issue #4244 does fix the issue mentioned above.
