### ISSUE TITLE
BUG | `useRouteQuery` | Error: Invalid value used as weak map key

### ISSUE THREAD

**Issue by mukundshah** [vueuse/vueuse#4364]
### Describe the bug

The application encounters a `500 Internal Server Error` with the message: `Invalid value used as weak map key`. The issue appears during server-side rendering (SSR).

**Steps to Reproduce**

1. Set up a Nuxt 3 project using Vue 3 and `@vueuse/router`.
2. Use the `useRouteQuery` composable inside the setup function of a component.
3. Run the application in SSR mode.
4. Trigger a page load that invokes the component using `useRouteQuery`.

### Reproduction

https://stackblitz.com/edit/github-rjiawx?file=app.vue

### System Info

```Shell
System:
    OS: macOS 15.1.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 32.85 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 23.3.0 - ~/.asdf/shims/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.9.0 - ~/.asdf/shims/npm
    pnpm: 9.14.2 - /usr/local/bin/pnpm
    bun: 1.1.37 - /usr/local/bin/bun
Browsers:
    Chrome: 131.0.6778.86
    Edge: 131.0.2903.70
    Safari: 18.1.1
npmPackages:
    @vueuse/core: ^11.3.0 => 11.3.0 
    @vueuse/router: ^11.3.0 => 11.3.0 
    nuxt: ^3.14.1592 => 3.14.1592 
    vue: latest => 3.5.13
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mukundshah** [comment]
Closing this because, I made a wrong reproduction.

**Comment by gbyesiltas** [comment]
I'm having this same issue when I try to use `useRouteQuery` in my unit tests 🤔

**Comment by Eazash** [comment]
@mukundshah Please reopen this issue as the bug is still present. Your reproduction is still valid, as this error occurs when a router instance isn't available. Nuxt doesn't seem to create a router until there is a `/pages` directory and/or the `NuxtPage` component is called

Here's a minimal reproduction https://stackblitz.com/edit/vitejs-vite-8shpmc8u?file=src%2FApp.vue

**Comment by zumm** [comment]
I can confirm the problem is still a thing. This issue seems abandoned, should we open new issue?

**Comment by zumm** [comment]
And there is workaround: you can pass nuxt version of router and route as `useRouteQuery`'s options.

```ts
import { useRoute, useRouter } from '#imports'
import { useRouteQuery } from '@vueuse/router'

const router = useRouter()
const route = useRoute()

const query = useRouteQuery<string | undefined>('query', undefined, { router, route })
```

**Comment by Pandazaur** [comment]
I has the same issue on a Vue.js (+ Vite) monorepo project. It was due to "@vueuse/router" was installed in the parent directory (monorepo base) instead of the package.json of the Vue project

**Comment by bartoszrudzinski** [comment]
> I has the same issue on a Vue.js (+ Vite) monorepo project. It was due to "@vueuse/router" was installed in the parent directory (monorepo base) instead of the package.json of the Vue project

seems this is an issue, so this is a bug and should be fixed
