### ISSUE TITLE
useMagicKeys: Documentation errors (`alias` and default mapping of `meta`)?

### ISSUE THREAD

**Issue by ahku** [vueuse/vueuse#437]
On the [documentation page](https://vueuse.org/core/usemagickeys/#usemagickeys):

![image](https://user-images.githubusercontent.com/1736890/114010358-50855900-9864-11eb-9d0d-377ef502e767.png)

Shouldn't `alias` be `aliasMap` here?

And, isn't the meta key the Command key (Mac). [KeyboardEvent.metaKey](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey). Maybe it's not referring to this event?

**Comment by antfu** [comment]
Yeah, it's my mistake. Fixing now
