### ISSUE TITLE
BUG | `useFocusWithin` | Watching the `focused` value results in it triggering twice when focus changes inside the element

### ISSUE THREAD

**Issue by cernymatej** [vueuse/vueuse#4372]
### Describe the bug

After the change introduced in https://github.com/vueuse/vueuse/pull/4134, the `focused` ref from `useFocusWithin` is set to `false` whenever a `focusout` event occurs. This behavior means that when the focus transitions from one element to another within the tracked element, the value changes as follows:
```ts
// *an element is focused*
true
// *focus jumps from one element to another within the tracked element*
false
true
```

## Expected behaviour
I would expect the value of `focused` to remain unchanged when the focus doesn't leave the tracked element.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-kbzgai?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/core: ^7.6.2 => 7.6.2 
    vue: ^3.2.25 => 3.2.31
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ben-lau** [comment]
Hi there, I retested the `useFocusWithin` in the version before #4134 , the behavior is consistent with the current version, here is the demo: [https://stackblitz.com/edit/vitejs-vite-6u6hpf?file=src%2FApp.vue](https://stackblitz.com/edit/vitejs-vite-6u6hpf?file=src%2FApp.vue)
In the situation the document.activeElement will briefly change to the `body`, at this moment, the target doesn't contain the focus element. To solve your problem I will suggest you to use `wathchDebounce` and debounce 1ms.

**Comment by cernymatej** [comment]
Hmm, interesting. I can see that now. I must have made other changes when testing it in a project of mine, which "fixed" the behaviour.
Don't you think that the way it currently behaves is incorrect, though?

**Comment by ben-lau** [comment]
yep, I actually do think it's counterintuitive, although the browser implementation it like this. I'll make this hook act likes the behavior of the :focus-within CSS pseudo-class.
