### ISSUE TITLE
useInert / useInertElement: new function

### ISSUE THREAD

**Issue by userquin** [vueuse/vueuse#438]
See WICG inert [here](https://github.com/WICG/inert): it is related to useFocusTrap to avoid traverse with keyboard and mouse focusable dom elements outside the activated scope element.

It would be useful when using modal drawers and dialogs: in both cases, we need to trap focus and make the rest of the ui inert, making only traversable the drawer or dialog content.

Since we have a virtual dom, maybe it can be less intrusive than traverse all dom looking for focusable elements: see [WICG : Performance and gotchas](https://github.com/WICG/inert#performance-and-gotchas).

The WICG implementation looks for shadow dom elements,  maybe here we don't need to take care about it.

**Comment by wheatjs** [comment]
Do you have an example on how you'd like this API to work? 

Also seems like it might be a bit early to implement something like this as the support is still pretty poor https://caniuse.com/mdn-api_htmlelement_inert

**Comment by userquin** [comment]
I have looking into `useFocusTrap` code at seems it can be (re)used but with some changes/addons concerning a11y.

This api will be used as a `polyfill` while `modal/inert` native api not implemented as you pointed in the link. It can be detected just using:

```typescript
Element.prototype.hasOwnProperty('inert')
```
Since the logic we need to expose is just like `useFocusTrap`, I need to finish my tests with screen readers and I'll feedback results here.

I mainly use the wcag implementation when using modal dialogs, navigation drawers and blocking actions:
- for modal dialogs, the content below must be `inert` (inert subtrees) to not capturing mouse and focus events => using `useFocusTrap` works.
- for navigation drawer, `inert` its content when not shown, and when shown in modal `inert` main content that will appear below it (below navigation drawer overlay) => I haven't tested it yet.
- for blocking actions: sometimes it would be necessary to block the entire ui while processing some remote call or some expensive task and so it will be necessary to `inert` the entire main content while showing some activity progress (NProgress or similar)  => using `useFocusTrap` works.

The api will be the same of `useFocusTrap` but we need:
- adding `tabindex="-1"` for all focusable descendant nodes of the inerted element: I need to use a screen reader to check if `useFocusTrap` prevent inerted children elements to be exposed => for example, nested headings, tables, buttons...
- adding some css styles to prevent mouse interactions (text copy and others): just see the wcag polyfill css styles:
```css
[inert] {
  pointer-events: none;
  cursor: default;
}

[inert], [inert] * {
  user-select: none;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
}
```

**Comment by userquin** [comment]
And of course, if the native `inert` is available, the implementation will just add/remove `inert` attribute when activating or deactivating it to the target element.

**Comment by wheatjs** [comment]
Hmm, polyfilling a feature like this might be outside the scope of this library though. Writing polyfills can be pretty tedious, maybe it would be better to wait for it to be supported across most modern browsers?

**Comment by userquin** [comment]
I'm waiting for `modal/inert` support since 2015... 

I close this issue since it is out of scope of this library: the polyfill will be just using/wrapping the wcag implementation (some integration like `useFocusTrap` but forgot it).
