### ISSUE TITLE
BUG | `usePreferredDark` | not work for chrome

### ISSUE THREAD

**Issue by zhengzhibo** [vueuse/vueuse#4387]
### Describe the bug

usePreferredDark does not return the correct value when used in Google Chrome, but it works fine in Microsoft Edge and Firefox.

Chrome: Version 131.0.6778.109  
![image](https://github.com/user-attachments/assets/426f9aec-55f0-410e-866b-2f2882cff32d)

### Reproduction

https://vueuse.org/core/usePreferredDark/#usepreferreddark

### System Info

```Shell
windows 10
Chrome: Version 131.0.6778.109
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
In that case it might be a Chrome bug then? It works for my Brave `Version 1.73.97 Chromium: 131.0.6778.108 (Official Build) (arm64)`

Can you do some low-level tests on your side?
