### ISSUE TITLE
BUG | `useWebNotification` | Blank desktop notification when loaded

### ISSUE THREAD

**Issue by CFDan** [vueuse/vueuse#4391]
### Describe the bug

When using useWebNotification a blank Desktop Notification is sent on load. Replicated here https://vueuse.org/core/useWebNotification/#changelog

### Reproduction

https://vueuse.org/core/useWebNotification/#changelog

### System Info

```Shell
Include useWebNotification and on load a blank notification is shown
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by OrbisK** [comment]
#4019 is released with[v12.1.0](https://github.com/vueuse/vueuse/releases/tag/v12.1.0)

i will close this issue. If it is not fixed please reopen it :)
