### ISSUE TITLE
BUG | `useIntersectionObserver` | This error is ‘TypeError: v.tryOnScopeDispose is not a function     at Object.Ue [as useIntersectionObserver] (core:1:37555)’

### ISSUE THREAD

**Issue by ice909** [vueuse/vueuse#4399]
### Describe the bug

Import vueuse/Core in cdn mode
```js
mounted() {
   const trigger = document.querySelector('.trigger');
   window.VueUse.useIntersectionObserver(trigger, (entries) => {
       console.log(entries);
   });
}
```
Error reported in browser 
```
Uncaught TypeError: v.tryOnScopeDispose is not a function
    at Object.Ue [as useIntersectionObserver] (core:1:37555)
    at Proxy.mounted (index.html:257:25)
    at vue.global.js:5004:42
    at callWithErrorHandling (vue.global.js:2410:21)
    at callWithAsyncErrorHandling (vue.global.js:2417:19)
    at hook.__weh.hook.__weh (vue.global.js:4984:21)
    at flushPostFlushCbs (vue.global.js:2592:30)
    at render (vue.global.js:8137:9)
    at mount (vue.global.js:6123:15)
    at app.mount (vue.global.js:12199:21)
```

### Reproduction

cdn 

### System Info

```Shell
System:
    OS: Linux 6.9 Deepin 23 23
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 7.21 GB / 15.54 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ilyaliao** [comment]
Do you have [@vueuse/shared](https://vueuse.org/guide/#cdn) imported?

**Comment by ice909** [comment]
> Do you have [@vueuse/shared](https://vueuse.org/guide/#cdn) imported?

no

**Comment by ilyaliao** [comment]
> > Do you have [@vueuse/shared](https://vueuse.org/guide/#cdn) imported?
> 
> no

tryOnScopeDispose is exported from @vueuse/shared, and you must also import it.

```
<script src="https://unpkg.com/@vueuse/shared"></script>
<script src="https://unpkg.com/@vueuse/core"></script>
```

**Comment by ilyaliao** [comment]
> tryOnScopeDispose

tryOnScopeDispose is exported from @vueuse/shared, and you must import it as well.

```
<script src="https://unpkg.com/@vueuse/shared"></script>
<script src="https://unpkg.com/@vueuse/core"></script>
```
