### ISSUE TITLE
`useWebSocket` does not connect

### ISSUE THREAD

**Issue by lzzfnc** [vueuse/vueuse#441]
Hello 

I'm trying to setup a simple websocket connection with `VueUse` + `Nuxt`+ `@nuxtjs/composition-api` but the socket doesn't connect. `status` remains stuck in `CONNECTING` and does not upgrade to `OPEN`. 
I'm following the example provided in the docs without success. 

[Here's a sample repo](
https://github.com/lzzfnc/use-websocket/blob/main/pages/index.vue), and the code:

```vue
<template>
    <div class="container">
        data: {{ data }} 
        status: {{ status }} 

        <input v-model="message" type="text" />
        <button @click="send(message)">Send</button> <br />

        <button @click="close()">Close</button>
    </div>
</template>

<script>
import { useWebSocket } from "@vueuse/core";
export default {
    setup() {
        const { status, data, send, close } = useWebSocket(
            "wss://echo.websocket.org"
        );

        return {
            status,
            data,
            send,
            close,
        };
    },
    data() {
        return {
            message: "",
        };
    },
};
</script>
```

I've tried also the `useWebSocket` function of [vue-use-web](https://tarektouati.github.io/vue-use-web/functions/websocket.html) since I saw it in your references and shares the same syntax, and that's working fine.

I'm missing something ? 
thanks

**Comment by Shinigami92** [comment]
Does it work for you if you call `open()`? (Can also be accessed from the destructuring)

**Comment by wheatjs** [comment]
Just tested on the reproduction and `open` does work.

**Comment by Shinigami92** [comment]
With `4.10` there is also now a new option `immediate` that can be used to auto connect the WebSocket
With `5.0` this flag will turned on by default

**Comment by tujianglin** [comment]
In version 9.1, the state of CONNECTING is found again, and the OPEN cannot be reached

**Comment by rizypb** [comment]
I am using @vueuse/core v9.10.0 and the state of CONNECTING is found again. Also, cannot reach to OPEN state.
