### ISSUE TITLE
BUG | `useMounted` | Cannot read properties of undefined (reading 'mounted')

### ISSUE THREAD

**Issue by seahindeniz** [vueuse/vueuse#4416]
### Describe the bug

Vue 2.7 has an issue with `getCurrentInstance` that returns `proxy` instead of the instance itself. In fact, `proxy` property contains the instance.
So passing `instance` from
https://github.com/vueuse/vueuse/blob/d19606ba549167488c88502150cb26224a9a3ac7/packages/core/useMounted/index.ts#L16
to `onMounted` break it.
https://github.com/vuejs/vue/blob/9e88707940088cb1f4cd7dd210c9168a50dc347c/src/v3/apiLifecycle.ts#L34-L37

![image](https://github.com/user-attachments/assets/8c8c265d-d54f-4bc5-991b-4ff6aff7a166)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-dntjx7r4?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Linux 6.10 Alpine Linux
    CPU: (8) arm64 unknown
    Memory: 3.17 GB / 9.70 GB
    Container: Yes
    Shell: 1.34.1 - /bin/ash
  Binaries:
    Node: 14.20.1 - /usr/bin/node
    npm: 8.1.3 - /usr/local/bin/npm
  npmPackages:
    @vueuse/core: 12.0.0 => 12.0.0 
    vue: 2.7.14 => 2.7.14
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by seahindeniz** [comment]
I just realized this https://github.com/vueuse/vueuse/pull/4349 😞

**Comment by ilyaliao** [comment]
> I just realized this https://github.com/vueuse/vueuse/pull/4349 😞 

Yeah, it doesn't support Vue2 anymore.

**Comment by seahindeniz** [comment]
Yeah, thank you for the suggestion. It's good to know it was fixed before the dropping support 🙏🏻

**Comment by seahindeniz** [comment]
@antfu JFYI, I think this is outdated
![image](https://github.com/user-attachments/assets/c5aef306-844a-4f6d-818c-8b722691cfdd)
