### ISSUE TITLE
`useFetch` cannot post with different data

### ISSUE THREAD

**Issue by isgj** [vueuse/vueuse#442]
Is it possible to call once
```js
const {isFetching, post, ...} = userFetch('someURL', {
    immediate: false
})
```
and after, when some data have changed call more times?

```js
// This is inside a callback
post({data: '...'}).execute()
```

I'm able to do so once, but not more times. This is really handy when you have a form, the user submits it, some error happens (probably validation), user changes the data and submits it again. 

I see the code responsible for this  is 
```js
function setMethod(method: string) {
    return (payload?: unknown, payloadType?: PayloadType) => {
      if (!initialized) {
        config.method = method
        config.payload = payload
        config.payloadType = payloadType || typeof payload === 'string' ? 'text' : 'json'
        return shell as any
      }
      return undefined
    }
  }
```
Is there any reason for doing so that I'm missing?
Same for `setType`?

**Comment by wheatjs** [comment]
Hmm interesting, thanks for the report, I'll look into it.
