### ISSUE TITLE
potential bug: onClickOutside

### ISSUE THREAD

**Issue by wheatjs** [vueuse/vueuse#451]
It looks like `onClickOutside` is being called multiple times when the element target is not removed after the `onClickOutside` event is fired. This doesn't show up on the VueUse demo page because the targets are removed, but if they aren't it will be fired twice.

Here is a reproduction on [Vue SFC Playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IG9uQ2xpY2tPdXRzaWRlIH0gZnJvbSAnQHZ1ZXVzZS9jb3JlJ1xuXG5jb25zdCB0YXJnZXQgPSByZWYoKVxuY29uc3QgY2xpY2tlZCA9IHJlZigwKVxuXG5vbkNsaWNrT3V0c2lkZSh0YXJnZXQsICgpID0+IGNsaWNrZWQudmFsdWUgKz0gMSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBncmlkOyBwbGFjZS1jb250ZW50OiBjZW50ZXI7IHBsYWNlLWl0ZW1zOiBjZW50ZXI7IGhlaWdodDogMTAwJTsgZ2FwOiAxcmVtOyB1c2VyLXNlbGVjdDogbm9uZTtcIj5cbiAgICBDbGlja2VkIE91dHNpZGUge3sgY2xpY2tlZCB9fSB0aW1lKHMpXG4gICAgPGRpdiByZWY9XCJ0YXJnZXRcIiBzdHlsZT1cImJhY2tncm91bmQ6IHdoZWF0OyBwYWRkaW5nOiAycmVtOyBib3JkZXItcmFkaXVzOiAwLjI1cmVtO1wiPlxuICAgICAgQ2xpY2sgT3V0c2lkZSBvZiBtZVxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG5cdFx0XCJAdnVldXNlL2NvcmVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL2NvcmUvZGlzdC9pbmRleC5lc20uanNcIixcbiAgICBcIkB2dWV1c2Uvc2hhcmVkXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZXVzZS9zaGFyZWQvZGlzdC9pbmRleC5lc20uanNcIixcbiAgICBcInZ1ZS1kZW1pXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vdnVlLWRlbWkvbGliL2luZGV4LmVzbS5qc1wiXG4gIH1cbn0ifQ==)
 
Is this behavior intentional? Maybe this behavior was introduced in this issue https://github.com/vueuse/vueuse/issues/323? If this is intentional maybe we should add an option to only fire the event once.

**Comment by userquin** [comment]
the event is fired once, the problem is that it fires 2 events: a `pointerdown` followed by a `mousedown`, so it should be intentional.
```js
<script setup>
import { ref } from 'vue'
import { onClickOutside } from '@vueuse/core'

const target = ref()
const clicked = ref(0)

onClickOutside(target, (e) => {
  console.log(e)
  clicked.value += 1
})
</script>

<template>
  <div style="display: grid; place-content: center; place-items: center; height: 100%; gap: 1rem; user-select: none;">
    Clicked Outside {{ clicked }} time(s)
    <div ref="target" style="background: wheat; padding: 2rem; border-radius: 0.25rem;">
      Click Outside of me
    </div>
  </div>
</template>
```

**Comment by userquin** [comment]
Maybe [this](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events#event_properties) can be used to filter the callback call.

Previous link can also be used to make `useSwipe` work with mouse.

**Comment by wheatjs** [comment]
> @wheatjs the event is fired once, the problem is that it fires 2 events: a `pointerdown` followed by a `mousedown`, so it should be intentional.
> 
> ```js
> <script setup>
> import { ref } from 'vue'
> import { onClickOutside } from '@vueuse/core'
> 
> const target = ref()
> const clicked = ref(0)
> 
> onClickOutside(target, (e) => {
>   console.log(e)
>   clicked.value += 1
> })
> </script>
> 
> <template>
>   <div style="display: grid; place-content: center; place-items: center; height: 100%; gap: 1rem; user-select: none;">
>     Clicked Outside {{ clicked }} time(s)
>     <div ref="target" style="background: wheat; padding: 2rem; border-radius: 0.25rem;">
>       Click Outside of me
>     </div>
>   </div>
> </template>
> ```

Ah well yeah that's why I linked that one issue

**Comment by sibbng** [comment]
As long as `pointerdown` fires at both mouse and touch environment that `mousedown` and `touchstart` events are unnecessary.

Also providing a way to pass custom event names as argument would be nice. Some peoples may want to fire it after `pointerup` event.

Things to do:
1. Listen `pointerdown` as default
2. Allow event type string and array of strings as an option in third argument.
