### ISSUE TITLE
useStorage: Typescript error when deleting data from storage

### ISSUE THREAD

**Issue by khorsky** [vueuse/vueuse#452]
According to the [documentation](https://vueuse.org/core/useStorage/) I should be able to delete data from storage with simple

```
const state = useStorage('my-store', bool)

state = null
```
However TS compiler is complanin about invalid type: "Type 'null' is not assignable to type 'boolean'" in this case.

Is there a simple way how can I avoid this?

**Comment by wheatjs** [comment]
Nice catch, we'll take a look!

**Comment by DevilTea** [comment]
> According to the [documentation](https://vueuse.org/core/useStorage/) I should be able to delete data from storage with simple
> 
> ```
> const state = useStorage('my-store', bool)
> 
> state = null
> ```
> 
> However TS compiler is complanin about invalid type: "Type 'null' is not assignable to type 'boolean'" in this case.
> 
> Is there a simple way how can I avoid this?

Try to do this
```ts
store.value = null as unknown as boolean
```

**Comment by adrianjost** [comment]
You could set the type with `useStorage<boolean | null(...)>`. The downside is, that you then also have the `null` type when read the value

**Comment by antfu** [comment]
Until TS 4.4, we could have different type for getter and setter so this probably could be solved
