### ISSUE TITLE
`useMagicKeys` Seems to be linked to qwerty keyboard

### ISSUE THREAD

**Issue by matthieudou** [vueuse/vueuse#453]
Hey, 

I'm trying `useMagicKeys` on the vueuse website and when typing the letter `m` on my azerty keyboard, useMagicKeys is returning `Semicolon`. Same for every other qwerty/azerty differences.

Thank you by advance, and big thanks for this package, it's so cool

**Comment by wheatjs** [comment]
Thanks for the report, we'll take a look into this 😄 

I'll leave this here for reference as it might be useful in fixing this https://hacks.mozilla.org/2017/03/internationalize-your-keyboard-controls/
