### ISSUE TITLE
[Feature Request] Third Party Component Computed Property

### ISSUE THREAD

**Issue by jd-0001** [vueuse/vueuse#455]
Hi, This library is really helpful and awesome :heart: 

I used Vuetify, BootstrapVue, and Quasar in my development period. Recently, with Vue 3 update and change in template ref, Accessing components' internal value using computed is somehow a hard time for me. I am unable to find the best way for it.

e.g. I am using Vuetify's `v-menu` component and I want to get the computed value of its `isActive` property.

As we can only access the value of template ref in `onMounted`, I am unable to find out the best way to create computed of `refMenu.value.isActive`

So, May I know there can be util function for getting the internal value of the component (Similar to controlledComputed).

```js
import {templateRef, internalComputed} from '@vueuse/core'

// template ref
const refMenu = templateRef(null)

// Computed property which returns `null` until template ref is resolved
//  and once it is resolved returns computed value of given property.
const isMenuActive = internalComputed(refMenu, 'isActive')
```

Regards :pray:

**Comment by wheatjs** [comment]
You should just be able to do something like this though, right?
```ts
import { ref, computed } from 'vue'

const refMenu = ref(null)
const isMenuActive = computed(() => refMenu.value ? refMenu.value.isActive : null)
```

**Comment by jd-0001** [comment]
Yeah, I will try this in future and will let you know.

Thanks.
