### ISSUE TITLE
[feature] reactivePick: support computed keys

### ISSUE THREAD

**Issue by TimonLukas** [vueuse/vueuse#460]
Currently `reactivePick` allows you to pick options from an object and have the resulting object be reactive. While this is already useful, the function could be made a lot more useful if it was possible to also have the picking action itself be reactive, i.e. the keys to pick supporting a `Ref`. In my use case I have a component wrapping three subcomponents, and I want to pick the subcomponents props from the wrapper components props since not all subcomponents use all props (I have to keep this design for backwards compatibility).

I propose the following change (and I'll try to create a PR later):

Add a new overload to `reactivePick`:
```typescript
reactivePick<T extends object, K extends keyof T>(obj: T, keys: MaybeRef<K[]>): Ref<{ [S in K]: UnwrapRef<T[S]> }>
```

This overload will react to changes in the `keys` parameter and modify the returned computed ref accordingly.

**Comment by TimonLukas** [comment]
So I just realized that instead of doing `reactivePick(obj, computed(() => pick))` I can do `computed(() => reactivePick(obj, pick)`. Buuuut it might still be relevant/useful for somebody, so I'll leave the PR open in case you're interested :)

**Comment by wheatjs** [comment]
Based on the PR it seems like any future progress on this would be best in a new issue, so I'll close this on for now.
