### ISSUE TITLE
useStorage: improve "storage" event handling

### ISSUE THREAD

**Issue by gkubisa** [vueuse/vueuse#463]
[Handling of `storage` events](https://github.com/vueuse/vueuse/blob/00b8f31387651ccb4af22b25cfe638aeefa2a3c1/packages/core/useStorage/index.ts#L112) is currently very inefficient, as any storage event causes ALL listening `useStorage` instances to re-read data from the storage object, incurring the overhead of reading and parsing the data. It would be much more efficient to use the properties of the [StorageEvent](https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent) to:

- determine, if a ref should be updated by looking at the `key` and `storageArea` properties
- parse the new value from the `newValue` property

**Comment by antfu** [comment]
Sounds like a good enhancement, please go ahead and make a PR if you want. Thank you!
