### ISSUE TITLE
Usage of composable functions outside the "setup" function

### ISSUE THREAD

**Issue by gkubisa** [vueuse/vueuse#464]
When looking at functions like [useWindowSize](https://vueuse.org/core/useWindowSize/), [useWindowScroll](https://vueuse.org/core/useWindowScroll/), [useStorage](https://vueuse.org/core/useStorage/), etc I noticed that they [register event listeners on global objects](https://github.com/vueuse/vueuse/blob/00b8f31387651ccb4af22b25cfe638aeefa2a3c1/packages/core/useWindowSize/index.ts#L26) (eg `window`) but they do not expose any `stop` functions for removing the listeners explicitly. This effectively limits their usage to the `setup` function of components.

I also noticed that [some other composable functions do expose `stop` functions](https://github.com/vueuse/vueuse/blob/00b8f31387651ccb4af22b25cfe638aeefa2a3c1/packages/core/useEventListener/index.ts#L124), which makes them usable in any context - not limited to components.

This is clearly inconsistent and limits usage of many composable functions to being called only synchronously during a component's `setup` function execution. Would it be possible to make all composable functions usable outside the `setup` function, possibly by modifying each to expose a suitable "stop" function? This would also be consistent with the official [watchEffect](https://v3.vuejs.org/api/computed-watch-api.html#watcheffect) and [watch](https://v3.vuejs.org/api/computed-watch-api.html#watch) functions which also expose "stop" handles.

**Comment by antfu** [comment]
Awaits https://github.com/vuejs/rfcs/pull/212

**Comment by ameinhardt** [comment]
The above functions make use of useEventListener which seems to use [onScopeDispose](https://v3.vuejs.org/api/effect-scope.html#onscopedispose) to stop, isn't it? So the functions can be used in other scopes now, isn't it?

**Comment by FRSgit** [comment]
@ameinhardt Wanted to confirm that every function which uses onScopeDispose can be used in other/custom made scopes now. I've just tried it with a directive example and it seems to be working correctly.

**Comment by antfu** [comment]
Yes. From v6.0 we are using onScopeDispose for all the functions.
