### ISSUE TITLE
useUid - generate unique id for a Vue instance

### ISSUE THREAD

**Issue by 3nuc** [vueuse/vueuse#465]
When authoring accessible components, sometimes you need an unique id to use on eg. `<label for=""/>` elements or for `aria-describedby` attrs

```html
<template>
  <div id="description">This is a deadly {{animal}}</div>
  <span aria-describedby="dsecription">{{ animal ==== 'snake' ? 'sssssssssss' : 'bark?'  }}</span> 
</template>
```
The above example is wrong because what if you use the above component many times in the same wrapper component? The id="description" occurs several times and is not uniquely tied to one single, correct description

That can be fixed by doing :id="uid", where uid is the uniqe id generated during created() lifecycle hook

Propsal:
```
<script setup>
const {uid} = useUid();
</script>
```
I think it's worth providing it as a composable that you have to destructure rather than a raw function to prevent people from calling uuid() manually in the template (which I guess could generate a different id on rerenders, especially if you used uuid() multiple times in the template, with const {uuid} = useUuid() it's harder to run into that problem)

**Comment by wheatjs** [comment]
Curious as to how this would be different than doing something like
```html
<script setup>
import {  v4 as uuid } from 'uuid'

const id = uuid()
</script>
```

Since setup runs at around the same time as `beforeCreate` and `created` it would only be called once. `setup` won't rerun when it re-renders.

**Comment by 3nuc** [comment]
Yeah what you've posted would also work. Tbh what I described in OP is a really tiny menial utility function, but utility => damn I wonder if vueuse has it :P

**Comment by wheatjs** [comment]
Hmm yeah I think generating a uuid for each component automatically would probably be outside the scope of VueUse.

Maybe you have some idea on how to add some sort of reactivity to it. Otherwise I imagine the function would just be this 😅 
```ts
function useUid() {
  return uuid()
}
```

**Comment by bklik** [comment]
Came here kind of looking for the same thing. Here's another option:
```
// Returns a random Universally Unique Identifier (UUID)
export function useUUID(pattern?: string) {
    // Accept any desired pattern. If no pattern is provided
    // default to a RFC4122 UUID pattern.
    const _pattern = pattern ? pattern : 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx';

    // Replace each character in the pattern
    // leaving any non x|y character alone.
    return _pattern.replace(/[xy]/g, replacePattern);
}

function replacePattern(c: string) {
    // Random hexadecimal number
    const r = (Math.random() * 16) | 0;

    // If 'x' return hexadecimal number,
    // if 'y' return [8-11] randomly
    const v = c == 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
}
```
