### ISSUE TITLE
PhpStorm can't resolve `asyncComputed` variable in template

### ISSUE THREAD

**Issue by cawa-93** [vueuse/vueuse#476]
#### Reproduce the problem

1. Create Vue SFC:
 ```vue
    <template>
      <div>
        {{ myAsyncStr.toLowerCase }} <!-- Unresolved variable toLowerCase  -->
        {{ myStr.toLowerCase }} <!-- ok -->
      </div>
    </template>

    <script lang="ts">
    import {computed, defineComponent} from 'vue';
    import {asyncComputed} from '@vueuse/core';

    export default defineComponent({
      setup() {
        const myAsyncStr = asyncComputed(() => '', '');
        const myStr = computed(() => '');
        return {myStr, myAsyncStr};
      },
    });
    </script>
 ```
2. Check `{{ myAsyncStr.toLowerCase }}` line

#### Expected result
`myAsyncStr` resolves exactly as `myStr`

#### Actual result
PhpStorm Can't resolve `myAsyncStr` as `string`. Type is ` Ref<string> extends Ref<infer V> ? UnwrapRefSimple<V> : UnwrapRefSimple<Ref<string>>`

**Comment by wheatjs** [comment]
Is this still an issue? I couldn't reproduce it in VSCode. If it is an issue with PHPStorm I'm not quite show how we will be able to address it since that would seem like a bug with PHPStorm.

**Comment by antfu** [comment]
Yeah, but do agree we should change the internal ref to shallowRef to match with `computed`
