### ISSUE TITLE
Please use an explicit version number for vue-demi

### ISSUE THREAD

**Issue by gkubisa** [vueuse/vueuse#478]
Currently the version number of `vue-demi` is "latest" in package.json files, for example [here](https://github.com/vueuse/vueuse/blob/main/packages/core/package.json#L39). Could the supported version range of vue-demi be defined explicitly, like for all other dependencies? This would allow more control over dependencies not only in the VueUse project but also in projects which depend on VueUse.

PS. When the vue-demi version in VueUse is "latest", then it must also be "latest" in the dependent modules to avoid duplication.

**Comment by antfu** [comment]
Yeah, I think we can change it to "*"
