### ISSUE TITLE
`UntilBaseInstance#toMatch` assumes that `v` is always of the input type, but it's `unref`ed

### ISSUE THREAD

**Issue by Shinigami92** [vueuse/vueuse#482]
I have following statement where `portals` is of type `ComputedRef<Portal[]>`

```ts
await until(portals).toMatch((v) => v.length > 0);
//                                   ~~~~~~~ expect to use v.value.length
```

`UntilBaseInstance#toMatch` now assumes that its `v` argument is also of type `ComputedRef<Portal[]>` but it's `Portal[]`

The current workaround is to use `unref`

```diff
- await until(portals).toMatch((v) => v.length > 0);
+ await until(portals).toMatch((v) => unref(v).length > 0);
```

The solution could be using `MaybeRef` or something similar 🤔 

---

- [x] I'm willing to provide a PR for that  
      This would be my first contribution and really helpful to jump into the code and find out how it's working 🙂 
      _I need to find a time-slot in the next few days, that's why I'm creating an issue instead of directly opening a PR to fix it 😄_

**Comment by wheatjs** [comment]
@Shinigami92 Did you still want to make a PR for this? If not I can get one going later today. Also I think this might be a breaking change?

**Comment by Shinigami92** [comment]
Oh 😯 I totally forgot this PR :eyes: 
But I would be interested in doing it to get in touch with the code, but would be over weekend or so

**Comment by wheatjs** [comment]
Alright no problem 😄
