### ISSUE TITLE
Incompatible with vite and vue2

### ISSUE THREAD

**Issue by localhost5001** [vueuse/vueuse#485]
I've created a project with vite+vue2(using plugin)+vueuse and it looks like vueuse doesn't work properly in this setup.

The error I get:

```
vue.runtime.esm.js:619 [Vue warn]: Error in data(): "ReferenceError: ref3 is not defined"

found in

---> <Anonymous>
       <Root>
warn @ vue.runtime.esm.js:619
vue.runtime.esm.js:1888 ReferenceError: ref3 is not defined
    at Object.ref (index.esm.js:1)
    at useCounter (index.esm.js:698)
    at setup (App.vue:21)
    at mergedSetupFn (vue-composition-api.esm.js:1741)
    at vue-composition-api.esm.js:1527
    at activateCurrentInstance (vue-composition-api.esm.js:1454)
    at initSetup (vue-composition-api.esm.js:1525)
    at VueComponent.wrappedData (vue-composition-api.esm.js:1509)
    at getData (vue.runtime.esm.js:4748)
    at initData (vue.runtime.esm.js:4705)
```

I tried `useCounter` and `useStorage`, but I think it can be replicated with other methods.

Here is the project link to replicate: 
https://github.com/localhost5001/vite-vue2-vueuse-template

**Comment by lstoeferle** [comment]
Hi @localhost5001,
as far as I can see in your project the `vue-demi` dependency is missing ;) You also can move `vite-plugin-vue2` to the devDepedencies.

I created a `vite` + `vue2` template using `@vueuse/core` beginning of this year. it's maybe worth a look to get started :)

**Comment by localhost5001** [comment]
Hi @lstoeferle thank you for your reply, I will try your template. Thank you! Closing the issue.

> Hi @localhost5001,
> as far as I can see in your project the `vue-demi` dependency is missing ;) You also can move `vite-plugin-vue2` to the devDepedencies.
> 
> I created a `vite` + `vue2` template using `@vueuse/core` beginning of this year. It's maybe worth a look to get started :)
> 👉 [vite-vue2-windicss-starter](https://github.com/lstoeferle/vite-vue2-windicss-starter)
