### ISSUE TITLE
Testing useMagicKeys/onKeyStroke with vue-test-utils

### ISSUE THREAD

**Issue by syropian** [vueuse/vueuse#489]
I'm not sure if this would be considered an issue with VueUse or vue-test-utils, but I'm struggling to get a test working that relies on `useMagicKeys` or `onKeyStroke`. Here's a sample test where my code relies on checking if `Shift` is held:

```ts
describe("Shift-clicking items", () => {
  test("Selecting an item when no other item is selected selects all items from index 0 to the selected item", async () => {
    const wrapper = mount(App, { attachTo: document.body });

    await wrapper.trigger("keydown", { keyCode: 16 }); // Shift
    await wrapper.findAll("li")[5].trigger("click");
    expect(wrapper.vm.sortedItems).toEqual([0, 1, 2, 3, 4, 5]);
  });
});
```

Unfortunately the test fails — while the click is registered just fine, the Shift key does not seem to be detected. 

Edit: fwiw I also tried performing a more manual `keydown` trigger like so with no luck either:
```ts
document.dispatchEvent(new KeyboardEvent("keydown", { key: "Shift" }));
```

**Comment by lstoeferle** [comment]
Hi @syropian,
you probably registered the `useMagicKeys` event listener on the default target, which is `window`. Can you try to trigger the `keydown` event in your test like this:
```javascript
window.dispatchEvent(new KeyboardEvent("keydown", { key: "Shift" }));
```

**Comment by syropian** [comment]
@lstoeferle Ah! So obvious but I somehow missed that, thank you! Going ahead and closing this.
