### ISSUE TITLE
Good points, totally fine with using `{ controls: true }`.

### ISSUE THREAD

**Issue by ALTURKA** [vueuse/vueuse#490]
Good points, totally fine with using `{ controls: true }`.

About the first two points, you are right. I would say that is more about internal implementation, the docs could still remain the same because you could bundle the two functions in a single page (I think it is roughly the same to explain both ways). I think it is about trade-offs, as usual. Probably users that care a lot about performance are going to implement the timestamp themselves, and you can say that VueUse favors usability.

About naming, I first went with `useControlledTransition`, but `controlledRef` means something totally different so I think it will be confusing. You are right that uniform naming is important, maybe `useTransitionWithControls` could be a good name.

The other problem I see is there is no way to tell Typescript that the two functions are related and that it should show them to the user together (Imagine if when you are using `useTransition`, you will get `useTransitionWithControls` listed when you are writing the params somehow helping users to discover it). So this is a +1 for `{ controls: true }`.

_Originally posted by @patak-js in https://github.com/vueuse/vueuse/issues/362#issuecomment-792230721_

**Comment by wheatjs** [comment]
I'm confused, what exactly is the issue here 😅?
