### ISSUE TITLE
useMagicKeys: Meta key makes combined key stay active

### ISSUE THREAD

**Issue by florivdg** [vueuse/vueuse#491]
There is an issue with `useMagicKeys` when using the `Meta` key on a Mac in a combination with other keys that keeps the other pressed key stay active after releasing the keys.

You can actually see this behavior on the [useMagicKeys docs](https://vueuse.org/core/usemagickeys/) itself.
When you open search by pressing `MetaLeft + K` or `MetaRight + K` and then let go of the pressed keys you can see the `K` stay active (see attached GIF).

This is not happening when using a different modifier like `Ctrl`. Pressing `Ctrl + K` clears both keys when releasing as it is expected.

![meta_key](https://user-images.githubusercontent.com/4962933/117812221-d29cdf00-b261-11eb-91a1-78602e443f36.gif)

**Comment by wufeng87** [comment]
@florivdg @wheatjs How about to change the behavior to clear all current keys when metaLeft(Right) keyUp on mac? Maybe I could make a pr for that.

**Comment by ryanmoyo** [comment]
@wheatjs Maybe it's time to close this issue.
