### ISSUE TITLE
useMediaControls: Overwrites the values set by the attributes

### ISSUE THREAD

**Issue by cawa-93** [vueuse/vueuse#492]
https://github.com/vueuse/vueuse/blob/ecd649621c4f7a6703f3cf2d897eb81a2f47a5db/packages/core/useMediaControls/index.ts#L313-L320

I'm not sure if this was intended, but it overwrites the default (browser) values and those that were set by the attributes.

Example:
```html
<video controls src="">
```
```js
useMediaControls(video, {})
```
Expected:
```js
video.controls // true // set by attribute
video.preload // "metadata" // default browser behaviour
```
Actual:
```js
video.controls // false
video.preload // "auto"
```

**Comment by wheatjs** [comment]
Hmm yeah, perhaps whenever the user doesn't specify an option we can default to the attributes. Would you like to make a PR for this? If not I can do it sometime this week

**Comment by cawa-93** [comment]
Ok. I Create PR tomorrow.
