### ISSUE TITLE
useMediaControls: Unable to catch `error` event

### ISSUE THREAD

**Issue by cawa-93** [vueuse/vueuse#494]
https://github.com/vueuse/vueuse/blob/ecd649621c4f7a6703f3cf2d897eb81a2f47a5db/packages/core/useMediaControls/index.ts#L352-L360

If you use an unavailable source, the browser will throw an `error` event. But not on the `<video>` tag, but on one of the `<source>` tags (This behavior may be different between browsers, I did not conduct a thorough study). It is important to keep track of such errors. But because the '<source>` elements are inserted implicitly outside the template, there is no easy way to add listener events to them.

The only workaround I've found is to insert `<source>` tags into the template explicitly, and not pass `src` param to `useMediaControls`.

**Comment by wheatjs** [comment]
Hmm, that's a good point. Maybe we can return something like `const { onSourceError } = useMediaContrls()` that would fire whenever there is an error. I don't quite remember how to create functions like that but I know it is possible.

Perhaps you have another idea on how we could handle it though?

**Comment by wheatjs** [comment]
Of course we could also just introduce it as a config option. Not sure which option would be preferable tbh

```ts
useMediaControls(video, {
  onSourceError(e) {
  
  }
})
```
