### ISSUE TITLE
[feature]: createEventHook: new function

### ISSUE THREAD

**Issue by wheatjs** [vueuse/vueuse#496]
Was thinking perhaps we could introduce something like `useEventHook`. This would allow use to do something like what I mentioned in #494.

```ts
const { onSourceError } = useMediaControls()

onSourceError((e) => {
  console.log(e)
})
```

Perhaps there is already a way to do this in VueUse? If so then we can close this.

If not, there is in implementation in the vue-apollo library that looks like it would be a good stating point https://github.com/vuejs/vue-apollo/blob/v4/packages/vue-apollo-composable/src/util/useEventHook.ts

**Comment by antfu** [comment]
Sounds good! I want this for a while as well, but didn't got time to do that. I like your API style which matches with Vue's lifecyle hooks. But for the name, I'd prefer name it `createEventHook` as it returns functions instead of reactive states. WDYT>
