### ISSUE TITLE
useSwipe: make it work also with mouse

### ISSUE THREAD

**Issue by userquin** [vueuse/vueuse#511]
Since `useSwipe` only works with `touch` events, there is no way to make it work using the mouse.

This issue can be solved using [this](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events#event_properties) as pointed on https://github.com/vueuse/vueuse/issues/451#issuecomment-819164542.

**Comment by wheatjs** [comment]
I think @lstoeferle wrote this one. @lstoeferle any thoughts on this?

**Comment by lstoeferle** [comment]
I can have a look and add the mouse events too 👍

**Comment by ilkome** [comment]
When I have inital styles on **target** element and click to it, my inital styles removed and changed to **touch-action: initial**
