### ISSUE TITLE
useMediaControls: Playing state not changed when video reloaded

### ISSUE THREAD

**Issue by cawa-93** [vueuse/vueuse#513]
We consider a situation when the video was already on the page and then, for some reason, the source changes.

[Here is an playground that demonstrates the problem.](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHVzZU1lZGlhQ29udHJvbHMgfSBmcm9tICdAdnVldXNlL2NvcmUnXG4gIFxuY29uc3Qgb3JpZ2luU291cmNlID0gJ2h0dHBzOi8vaW50ZXJhY3RpdmUtZXhhbXBsZXMubWRuLm1vemlsbGEubmV0L21lZGlhL2NjMC12aWRlb3MvZmxvd2VyLndlYm0nXG5jb25zdCBzcmMgPSByZWYob3JpZ2luU291cmNlKVxuXG5jb25zdCBjaGFuZ2VTb3VyY2UgPSAoKSA9PiBzcmMudmFsdWUgPSBvcmlnaW5Tb3VyY2UgKyAnP3Q9JyArIERhdGUubm93KClcblxuY29uc3QgdmlkZW9FbGVtZW50ID0gcmVmKClcbmNvbnN0IHtwbGF5aW5nLCB2b2x1bWV9ID0gdXNlTWVkaWFDb250cm9scyh2aWRlb0VsZW1lbnQsIHtcbiAgYXV0b3BsYXk6IGZhbHNlLCAvLyA8LS1cbiAgY29udHJvbHM6IHRydWUsIFxuICBwcmVsb2FkOiAnbWV0YWRhdGEnLFxuICBzcmMsXG59KVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogZ3JpZDsgcGxhY2UtY29udGVudDogY2VudGVyOyBwbGFjZS1pdGVtczogY2VudGVyOyBoZWlnaHQ6IDEwMCU7IGdhcDogMXJlbTsgdXNlci1zZWxlY3Q6IG5vbmU7XCI+XG4gICAgPHZpZGVvICByZWY9XCJ2aWRlb0VsZW1lbnRcIj48L3ZpZGVvPlxuICAgIFxuICAgIHBsYXlpbmc6IHt7cGxheWluZ319XG4gICAgPGJ1dHRvbiBAY2xpY2s9XCJjaGFuZ2VTb3VyY2VcIj5cbiAgICAgIFVwZGF0ZSBWaWRlbyBTb3VyY2VcbiAgICA8L2J1dHRvbj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuXHRcdFwiQHZ1ZXVzZS9jb3JlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZXVzZS9jb3JlL2Rpc3QvaW5kZXguZXNtLmpzXCIsXG4gICAgXCJAdnVldXNlL3NoYXJlZFwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2Uvc2hhcmVkL2Rpc3QvaW5kZXguZXNtLmpzXCIsXG4gICAgXCJ2dWUtZGVtaVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pL2xpYi9pbmRleC5lc20uanNcIlxuICB9XG59In0=)

1. First load: Video does not play because `autoplay: false`.
1. Launch the video. The `playind` state changes to `true`
1. Change the source without stopping the video. The video will be reloaded and it will stop because  `autoplay: false`. However, the `playind` state will remain `true`.

I'm not sure which behavior is more appropriate here.

- On the one hand, it seems logical to respond to browser behavior. Because the browser stopped the video, you need to update the playback status. ([demo](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHVzZU1lZGlhQ29udHJvbHMgfSBmcm9tICdAdnVldXNlL2NvcmUnXG4gIFxuY29uc3Qgb3JpZ2luU291cmNlID0gJ2h0dHBzOi8vaW50ZXJhY3RpdmUtZXhhbXBsZXMubWRuLm1vemlsbGEubmV0L21lZGlhL2NjMC12aWRlb3MvZmxvd2VyLndlYm0nXG5jb25zdCBzcmMgPSByZWYob3JpZ2luU291cmNlKVxuXG5jb25zdCBjaGFuZ2VTb3VyY2UgPSAoKSA9PiBzcmMudmFsdWUgPSBvcmlnaW5Tb3VyY2UgKyAnP3Q9JyArIERhdGUubm93KClcblxuY29uc3QgdmlkZW9FbGVtZW50ID0gcmVmKClcbmNvbnN0IHtwbGF5aW5nLCB2b2x1bWV9ID0gdXNlTWVkaWFDb250cm9scyh2aWRlb0VsZW1lbnQsIHtcbiAgYXV0b3BsYXk6IGZhbHNlLCAvLyA8LS1cbiAgY29udHJvbHM6IHRydWUsIFxuICBwcmVsb2FkOiAnbWV0YWRhdGEnLFxuICBzcmMsXG59KVxuXG5jb25zdCBvbmxvYWQgPSAoKSA9PiBwbGF5aW5nLnZhbHVlID0gIXZpZGVvRWxlbWVudC52YWx1ZS5wYXVzZWRcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGdyaWQ7IHBsYWNlLWNvbnRlbnQ6IGNlbnRlcjsgcGxhY2UtaXRlbXM6IGNlbnRlcjsgaGVpZ2h0OiAxMDAlOyBnYXA6IDFyZW07IHVzZXItc2VsZWN0OiBub25lO1wiPlxuICAgIDx2aWRlbyAgcmVmPVwidmlkZW9FbGVtZW50XCIgQGxvYWRlZG1ldGFkYXRhPVwib25sb2FkXCI+PC92aWRlbz5cbiAgICBcbiAgICBwbGF5aW5nOiB7e3BsYXlpbmd9fVxuICAgIDxidXR0b24gQGNsaWNrPVwiY2hhbmdlU291cmNlXCI+XG4gICAgICBVcGRhdGUgVmlkZW8gU291cmNlXG4gICAgPC9idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcblx0XHRcIkB2dWV1c2UvY29yZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2UvY29yZS9kaXN0L2luZGV4LmVzbS5qc1wiLFxuICAgIFwiQHZ1ZXVzZS9zaGFyZWRcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL3NoYXJlZC9kaXN0L2luZGV4LmVzbS5qc1wiLFxuICAgIFwidnVlLWRlbWlcIjogXCJodHRwczovL3VucGtnLmNvbS92dWUtZGVtaS9saWIvaW5kZXguZXNtLmpzXCJcbiAgfVxufSJ9)).
- On the other hand, it may make sense to save the state of the video before updating, and play it back after the update. ([demo](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHVzZU1lZGlhQ29udHJvbHMgfSBmcm9tICdAdnVldXNlL2NvcmUnXG4gIFxuY29uc3Qgb3JpZ2luU291cmNlID0gJ2h0dHBzOi8vaW50ZXJhY3RpdmUtZXhhbXBsZXMubWRuLm1vemlsbGEubmV0L21lZGlhL2NjMC12aWRlb3MvZmxvd2VyLndlYm0nXG5jb25zdCBzcmMgPSByZWYob3JpZ2luU291cmNlKVxuXG5jb25zdCBjaGFuZ2VTb3VyY2UgPSAoKSA9PiBzcmMudmFsdWUgPSBvcmlnaW5Tb3VyY2UgKyAnP3Q9JyArIERhdGUubm93KClcblxuY29uc3QgdmlkZW9FbGVtZW50ID0gcmVmKClcbmNvbnN0IHtwbGF5aW5nLCB2b2x1bWV9ID0gdXNlTWVkaWFDb250cm9scyh2aWRlb0VsZW1lbnQsIHtcbiAgYXV0b3BsYXk6IGZhbHNlLCAvLyA8LS1cbiAgY29udHJvbHM6IHRydWUsIFxuICBwcmVsb2FkOiAnbWV0YWRhdGEnLFxuICBzcmMsXG59KVxuXG5jb25zdCBvbmxvYWQgPSAoKSA9PiBwbGF5aW5nLnZhbHVlID8gdmlkZW9FbGVtZW50LnZhbHVlLnBsYXkoKSA6IHZpZGVvRWxlbWVudC52YWx1ZS5wYXVzZSgpXG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBncmlkOyBwbGFjZS1jb250ZW50OiBjZW50ZXI7IHBsYWNlLWl0ZW1zOiBjZW50ZXI7IGhlaWdodDogMTAwJTsgZ2FwOiAxcmVtOyB1c2VyLXNlbGVjdDogbm9uZTtcIj5cbiAgICA8dmlkZW8gIHJlZj1cInZpZGVvRWxlbWVudFwiIEBsb2FkZWRtZXRhZGF0YT1cIm9ubG9hZFwiPjwvdmlkZW8+XG4gICAgXG4gICAgcGxheWluZzoge3twbGF5aW5nfX1cbiAgICA8YnV0dG9uIEBjbGljaz1cImNoYW5nZVNvdXJjZVwiPlxuICAgICAgVXBkYXRlIFZpZGVvIFNvdXJjZVxuICAgIDwvYnV0dG9uPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG5cdFx0XCJAdnVldXNlL2NvcmVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL2NvcmUvZGlzdC9pbmRleC5lc20uanNcIixcbiAgICBcIkB2dWV1c2Uvc2hhcmVkXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZXVzZS9zaGFyZWQvZGlzdC9pbmRleC5lc20uanNcIixcbiAgICBcInZ1ZS1kZW1pXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vdnVlLWRlbWkvbGliL2luZGV4LmVzbS5qc1wiXG4gIH1cbn0ifQ==)).

**Comment by wheatjs** [comment]
Good catch. I'm kind of leaning towards this option I think
> On the other hand, it may make sense to save the state of the video before updating, and play it back after the update. (demo).
