### ISSUE TITLE
feat: maybe extend unref

### ISSUE THREAD

**Issue by wheatjs** [vueuse/vueuse#524]
I'm not sure if there is already a way to do this, I've been looking and couldn't find anything so I figured I would open an issue. 

**Problem**
When writing components for VueUse currently we are doing something like this
```ts
export const UseMouse = defineComponent<MouseOptions>({
  setup(props, { slots, emit }) {
    const { x, y, sourceType } = useMouse(props)

    return () => {
      if (slots.default) {
        return slots.default({
          x: x.value,
          y: y.value,
          sourceType: sourceType.value,
        })
      }
    }
  },
})
```

**Possible Solution**
It is a little verbose and I'm thinking there might be some ways we can improve it. My first idea was to do something like either create a new function or extend `unref` so we could something like this instead. This would allows us to pass in either an object or array of refs and it would return the object of unref-ed refs.

```ts
export const UseMouse = defineComponent<MouseOptions>({
  setup(props, { slots, emit }) {
    const { x, y, sourceType } = useMouse(props)

    return () => {
      if (slots.default) {
        return slots.default(unref({ x, y, sourceType }))
      }
    }
  },
})
```

I'm not sure if there is a better way or a way that already exists to do this. If we do end up going forward with this should we rename it or extend just extend the `unref` function like how we extended the `toRefs` function here https://vueuse.org/core/toRefs/?

cc @antfu

**Comment by antfu** [comment]
A bit confused, couldn't we simply use `reactive`?

**Comment by wheatjs** [comment]
Oh yeah you are completely right, sorry for the issue 😅
