### ISSUE TITLE
[useStorage] Allow to use custom serializer

### ISSUE THREAD

**Issue by g-plane** [vueuse/vueuse#525]
Currently, `useStorage` will choose different serializer based on default value of `useStorage` call. However, in our case, we need to allow empty value like `null` or `undefined`. For example:

```ts
type Data = { text: string }

const data = useStorage<Data | null>('key', null)
```

The code above won't work as expected, because for the default value `null`, `useStorage` will choose the `any` serializer which will just simply stringify an object:

```ts
data.value = { text: '' }

// it will be converted to `[object Object]`
```

I wish we can pass a function as custom serializer. API may be like this:

```ts
const data = useStorage<Data | null>('key', null, JSON.stringify)
```

Its signature can be:

```ts
function useStorage<T>(key: string, defaultValue: T, serializer?: (data: T) => string) {}
```

**Comment by antfu** [comment]
Sounds reasonable, happy to have it. but how about:

```ts
function useStorage<T>(key: string, defaultValue: T, options?: { serializer?: (data: T) => string }) {}
```

**Comment by g-plane** [comment]
That will be better.
