### ISSUE TITLE
Can't acess to useFetch response's body on error ? 

### ISSUE THREAD

**Issue by NoBrainSkull** [vueuse/vueuse#526]
On a HTTP 400 response sent by the server (missing required fields in a form), useFetch only pass the statusText to the Error object. [source code](https://github.com/vueuse/vueuse/blob/068144d86e3fabf933edb35f1e5c5ee1c3ce2adb/packages/core/useFetch/index.ts#L327)

I'd like to access to the json body response where I can access to the details of the error (statusText is irrelevant in my case). Response's body is already consumed (Stream locked) and `data` object has not been populated since the error is thrown before it gets the chance.

Is this some kind of non-fetch-standard issue and should I use useAxios instead ?

**Comment by wheatjs** [comment]
I'll look into fixing this, thanks for the report

**Comment by schelmo** [comment]
also stumbled upon this (using the 5 beta)
i'm getting a 422 response with a json encoded response
to body is already consumed when trying to get it from the response object
maybe change:
```javascript
if (!fetchResponse.ok)
  throw new Error(fetchResponse.message)
```
to something like this:
```javascript
if (!fetchResponse.ok) {
  const error = new Error(fetchResponse.statusText)
  error.data = responseData
  throw error
}
```
then we would consume it via with:
```javascript
onFetchError((e) => console.log(e.message, e.data)
```
