### ISSUE TITLE
[templateRef]: error trigger?

### ISSUE THREAD

**Issue by wozien** [vueuse/vueuse#527]
My vue sfc code:
```vue
<template>
  <div class="app">
    <span ref="target" :data-count="count">{{ count }}</span>
    <button @click="onClick">click</button> 
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, watchEffect } from 'vue'
import { templateRef } from '@vueuse/core'

export default defineComponent({
  setup() {
    const count = ref(0)
    const target = templateRef('target')

    watchEffect(() => {
      console.log(target.value)
    })

    return {
      count,
      onClick: () => count.value++
    }
  }
})
</script>
```

![image](https://user-images.githubusercontent.com/17634819/119125078-f7fcca80-ba63-11eb-8304-da3dd3f896f4.png)

Why can not print when count is 1?

**Comment by wheatjs** [comment]
Try setting `flush: 'post'` on `watchEffect`. You can see a [working example here](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiYXBwXCI+XG4gICAgPHNwYW4gcmVmPVwidGFyZ2V0XCIgOmRhdGEtY291bnQ9XCJjb3VudFwiPnt7IGNvdW50IH19PC9zcGFuPlxuICAgIDxidXR0b24gQGNsaWNrPVwib25DbGlja1wiPmNsaWNrPC9idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdD5cbmltcG9ydCB7IGRlZmluZUNvbXBvbmVudCwgcmVmLCB3YXRjaEVmZmVjdCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHRlbXBsYXRlUmVmIH0gZnJvbSAnQHZ1ZXVzZS9jb3JlJ1xuXG5leHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuICBzZXR1cCgpIHtcbiAgICBjb25zdCBjb3VudCA9IHJlZigwKVxuICAgIGNvbnN0IHRhcmdldCA9IHRlbXBsYXRlUmVmKCd0YXJnZXQnKVxuXG4gICAgd2F0Y2hFZmZlY3QoKCkgPT4ge1xuICAgICAgY29uc29sZS5sb2codGFyZ2V0LnZhbHVlKVxuICAgIH0sIHsgZmx1c2g6ICdwb3N0JyB9KVxuXG4gICAgcmV0dXJuIHtcbiAgICAgIGNvdW50LFxuICAgICAgb25DbGljazogKCkgPT4gY291bnQudmFsdWUrK1xuICAgIH1cbiAgfVxufSlcbjwvc2NyaXB0PiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICAgXCJAdnVldXNlL2NvcmVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL2NvcmUvZGlzdC9pbmRleC5lc20uanNcIixcbiAgICAgXCJAdnVldXNlL3NoYXJlZFwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2Uvc2hhcmVkL2Rpc3QvaW5kZXguZXNtLmpzXCIsXG4gICAgIFwidnVlLWRlbWlcIjogXCJodHRwczovL3VucGtnLmNvbS92dWUtZGVtaS9saWIvaW5kZXguZXNtLmpzXCJcbiAgfVxufSJ9)

You can read more about effect flush here in the docs https://v3.vuejs.org/guide/reactivity-computed-watchers.html#effect-flush-timing

**Comment by wozien** [comment]
ok, thanks
