### ISSUE TITLE
[feature] watchOnce

### ISSUE THREAD

**Issue by Razi91** [vueuse/vueuse#530]
Sometimes it's good to have a watch that will react on change only once. I've made a function for this:

```ts
export const watchOnce = <T>(
  target: WatchTarget<T>,
  cb: (res: T, prev?: T) => any
) => {
  const unwatch = watch(target, (res, prev?: T) => {
    unwatch();
    cb(res, prev);
  });
  return unwatch;
}
```
It returns a function to disable the watch manually.

WDYT?

**Comment by dheimoz** [comment]
hye @Razi91 have you tried?
https://vueuse.org/shared/until/

 I wonder if that is what you want to achieve?

**Comment by Razi91** [comment]
I had to miss it somehow. It works the same way, but a bit different approach.

**Comment by dheimoz** [comment]
Glad that until helped.
