### ISSUE TITLE
`UseFetchReturnBase` interface

### ISSUE THREAD

**Issue by SadWood** [vueuse/vueuse#532]
when i use `useFetch(url, { immediate: false }).get().json()` as an argument.

no `UseFetchReturnBase`, only `UseFetchReturn`.

**Comment by antfu** [comment]
Not sure if I got you, but maybe you are looking for #454? If so, you can try upgrading to v5.0 #533

**Comment by SadWood** [comment]
> Not sure if I got you, but maybe you are looking for #454? If so, you can try upgrading to v5.0 #533

I need the `UseFetchReturnBase` type, but right now `index.d.ts` only exports the `UseFetchReturn` type.
The interim solution is to define the `UseFetchReturnBase` type in its own type definition file.
It would be a bit more convenient if could add the export of the `UseFetchReturnBase` type.
