### ISSUE TITLE
5.0 is on beta! 🎉

### ISSUE THREAD

**Issue by antfu** [vueuse/vueuse#533]
We have just released VueUse v5.0 beta!

```bash
npm i @vueuse/core@next @vueuse/shared@next
```

Docs: http://next.vueuse.org/
Branch: https://github.com/vueuse/vueuse/tree/next

## Features

- Renderless component usage with the new [`@vueuse/components`](https://next.vueuse.org/guide/components.html) package, by @wheatjs!
- New add-on [`@vueuse/electron`](https://github.com/vueuse/vueuse/tree/next/packages/electron), by @ArcherGu
- New `{ controls: true }` options for functions, #362
- Submodules support with better tree-shaking for `@vueuse/integrations` and `@vueuse/firebase`, #469

## BREAKING CHANGES

If you are using TypeScript, a round of typecheck should cover all the changes required.

- Previous deprecated APIs are now removed.
- Distribute files are now under package root instead of `./dist` (mostly affects CDN usage)
- `when` renamed to `until`
- `useFetch` method and type calling order changes, #454
- `useTransition` changes, #376 #385 #386 #436
- `useTimeAgo`, `useTimestamp`, `useTimeout`, `useNow`, `useInterval` API changes due to the new `controls` option, #362
- `useDeviceLight` removed, see https://developer.mozilla.org/en-US/docs/Web/API/DeviceLightEvent
- firebase: `useAuth` now requires the `firebase.auth` instance

**Comment by dheimoz** [comment]
Great work @antfu and @wheatjs . You are just awesome!!

**Comment by ArcherGu** [comment]
Nice work 😍

**Comment by web2033** [comment]
Hi.

> npm i @vueuse/core

still installs 4.11.2

I needed to add `next` to get 5.0.0

> npm i @vueuse/core@next

**Comment by antfu** [comment]
@web2033 Fixed, thanks
