### ISSUE TITLE
Unnecessary firebase import

### ISSUE THREAD

**Issue by husayt** [vueuse/vueuse#538]
https://github.com/vueuse/vueuse/blob/5e15d7a9622d7caa516bbff8ad7c066f157a617b/packages/firebase/useAuth/index.ts#L2

This import is unnecessary in most of cases
```
import firebase from 'firebase/app'
```
but makes difference to vendor bundle in all cases.

This is only needed for lines 18-20
https://github.com/vueuse/vueuse/blob/5e15d7a9622d7caa516bbff8ad7c066f157a617b/packages/firebase/useAuth/index.ts#L19

Let's either leave that out or use dynamic import. Which one would be preferable?

**Comment by wheatjs** [comment]
I don't think in 5.0 this is going to be a problem anymore, you can see #469 for more details.

**Comment by antfu** [comment]
In 5.0.0-beta.7, change your imports to submodules will do:

```ts
import { useFireStore } from '@vueuse/firebase/useFireStore'
```

**Comment by husayt** [comment]
@antfu this still doesn't solve the issue rasied here. 
The following
```
import firebase from 'firebase/app'
```
still remains.

**Comment by wheatjs** [comment]
I'm unsure of how this is a problem. If you are using this function you will have to have imported firebase anyway

**Comment by husayt** [comment]
Normally that wouldn't matter, but Firebase dependancies are big. So if this statically imported here it affects vendor's bundle size. That is why I prefer to load it dynamically and  call `useAuth` with FB instance, then import is not required here.

**Comment by antfu** [comment]
Ah, I see, @wheatjs maybe we ask user to import the auth instance explicitly instead? Nice timing for the breaking change btw

**Comment by husayt** [comment]
Here is a dynamic loader I use, maybe that can be incorporated here too. At least, that doesn't add static dependencies

**Comment by wheatjs** [comment]
We could technically avoid a breaking change if we used a dynamic import, but I'm unsure if which one would be preferable. Do we want to require the user to provide a firebase instance or dynamically import it if they don't provide one?

**Comment by antfu** [comment]
I don't think dynamic imports worthwhile for this case (save a few keystrokes to import implicitly) as dynamic import will introduce much more problems to handle.
