### ISSUE TITLE
useFetch and formData doesn't work

### ISSUE THREAD

**Issue by floydback** [vueuse/vueuse#539]
There are only one way I made send the FormData correctly

```
const formData = new FormData()
formData.append('id', id)
formData.append('file', blob)

const { data } = useFetch(path, { method: 'PUT', body: formData })
```

I do not understand what the [formData()](https://github.com/vueuse/vueuse/blob/5e15d7a9622d7caa516bbff8ad7c066f157a617b/packages/core/useFetch/index.ts#L76) method was created for. The _multipart/form-data_ never added but I suppose it [should](https://github.com/vueuse/vueuse/blob/5e15d7a9622d7caa516bbff8ad7c066f157a617b/packages/core/useFetch/index.ts#L292)

I've try without success
```
useFetch(url).formData().put(formData)
useFetch(url).put(formData).formData()
useFetch(url).put(formData, 'formData').formData()
```

Am I not understanding something or am I doing something wrong?

**Comment by userquin** [comment]
@floydback , @dheimoz it is a bug, I made PR #549, see also #542

**Comment by userquin** [comment]
@floydback `useFetch(url).put(formData, 'formData')` is the correct usage, `formData` is for the response.

You can also use `post` instead `put`: `useFetch(url).post(formData, 'formData')`.

On #542 you have some playground showing the usage.
