### ISSUE TITLE
useFetch: multipart form data header must be removed instead added

### ISSUE THREAD

**Issue by userquin** [vueuse/vueuse#542]
`useFecth` line 292 should be:
```typescript
if (config.payloadType === 'formData') {
  headers.remove('Content-Type')
} else {
  headers['Content-Type'] = 'text/plain'
}
```
The browser `fetch` will do the same check and will break the execution.

We need to check if the formData has any blob/file, in that case we just remove the header.

I think in that case it would be necessary to force the user to include the header, and so `useFetch` usage will be concise, but it is a `breaking change`, but if ppl do not create an  issue no one is using it (yet ;) ).

I suggest to force `multipart` usage to be explicity in the request (header) and so we can just remove the header once detected.

Here is a snippet from my own code building the `fetch` body:

```javascript
const buildBody = (body, headers) => {
  if (!body) {
    return body;
  }
  if (body instanceof FormData) {
    return body;
  }
  if (body instanceof Object) {
    const contentType = headers.get(CONTENT_TYPE);
    if (contentType === FORM_URL_ENCODED) {
      return encodeBodyObject(body, contentType);
    } else if (contentType === MULTIPART_FORM_DATA) {
      headers.delete(CONTENT_TYPE);
      const formData = new FormData();
      const jsonBody = {};
      Object.keys(body).forEach(key => {
        const value = body[key];
        if (value instanceof File) {
          formData.append(key, value, value.name);
        } else {
          jsonBody[key] = value;
        }
      });
      formData.append(
        "JSON_BODY",
        new Blob([JSON.stringify(jsonBody)], {
          type: APPLICATION_JSON
        })
      );
      return formData;
    } else {
      headers.set(CONTENT_TYPE, APPLICATION_JSON);
      return JSON.stringify(body);
    }
  }
  return body;
};

**Comment by userquin** [comment]
@wheatjs you can find an explantion [here](https://muffinman.io/blog/uploading-files-using-fetch-multipart-form-data/).

**Comment by userquin** [comment]
My logic is inverted, that is, if someone uses `FormData`, then I assume the `content-type` header is not in the request.

The problem here is that we are adding it, breaking the execution and maybe the user executing the request does not include the header...

**Comment by wheatjs** [comment]
Interesting, have you tested if this issue occures in `useFetch`?

**Comment by userquin** [comment]
I haven't tried it yet, but I will...

**Comment by userquin** [comment]
@wheatjs can you take a look at [this playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXHRpbXBvcnQgeyB1c2VGZXRjaCB9IGZyb20gJ0B2dWV1c2UvY29yZSdcbiAgXG5cbiAgY29uc3QgeyBwb3N0IH0gPSB1c2VGZXRjaCgnL211bHRpcGFydCcsIHtcbiAgICBtZXRob2Q6ICdQT1NUJyxcbiAgICBwYXlsb2FkVHlwZTogJ2Zvcm1EYXRhJyxcbiAgICBpbW1lZGlhdGU6IGZhbHNlXG4gIH0pXG4gIFxuICBjb25zdCBidWlsZEZvcm1EYXRhID0gYXN5bmMoKSA9PiB7XG4gICAgY29uc3QgZm9ybURhdGEgPSBuZXcgRm9ybURhdGEoKVxuICAgIGZvcm1EYXRhLmFwcGVuZChcbiAgICAgIFwiQVwiLCBcbiAgICAgIG5ldyBCbG9iKFxuICAgICAgICBbSlNPTi5zdHJpbmdpZnkoeyBtZXNzYWdlOiAnTXVsdGlwYXJ0IEEnfSldLCBcbiAgICAgICAgeyB0eXBlOiAnYXBwbGljYXRpb24vanNvbicgfVxuICAgICAgKSwgXG4gICAgICAndGVzdC1tdWx0aXBhcnQtYS5qc29uJ1xuICAgIClcbiAgICBmb3JtRGF0YS5hcHBlbmQoXG4gICAgICBcIkJcIiwgXG4gICAgICBuZXcgQmxvYihcbiAgICAgICAgW0pTT04uc3RyaW5naWZ5KHsgbWVzc2FnZTogJ011bHRpcGFydCBCJ30pXSwgXG4gICAgICAgIHsgdHlwZTogJ2FwcGxpY2F0aW9uL2pzb24nIH1cbiAgICAgICksIFxuICAgICAgJ3Rlc3QtbXVsdGlwYXJ0LWIuanNvbidcbiAgICApXG4gICAgcmV0dXJuIGZvcm1EYXRhXG4gIH1cbiAgXG4gIGNvbnN0IHVzaW5nVXNlRmV0Y2ggPSBhc3luYygpID0+IHtcbiAgICBjb25zdCBwYXlsb2FkID0gYXdhaXQgYnVpbGRGb3JtRGF0YSgpXG4gICAgdHJ5IHtcbiAgICAgIHBvc3QocGF5bG9hZCwgJ2Zvcm1EYXRhJykuZXhlY3V0ZSgpLnRleHQoKVxuICAgIH0gY2F0Y2goaWdub3JlKSB7XG4gICAgICAvLyBqdXN0IG9nbm9yZVxuICAgIH1cbiAgfVxuICBjb25zdCB1c2luZ05hdGl2ZUZldGNoID0gYXN5bmMoKSA9PiB7XG4gICAgdHJ5IHtcblx0XHRcdGNvbnN0IHJlc3BvbnNlID0gYXdhaXQgZmV0Y2goJy9tdWx0aXBhcnQnLCB7XG4gICAgICAgIG1ldGhvZDogJ1BPU1QnLFxuICBcdFx0XHRib2R5OiBhd2FpdCBidWlsZEZvcm1EYXRhKCksXG4gICAgICB9KVxuICAgIH0gY2F0Y2ggKGlnbm9yZSkge1xuICAgICAgLy8ganVzdCBpZ25vcmUgZXJyb3JcbiAgICB9XG4gIH1cbjwvc2NyaXB0PlxuPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgPGRpdiBjbGFzcz1cImJ1dHRvbnNcIj5cbiAgICAgIDxidXR0b24gQGNsaWNrPVwidXNpbmdVc2VGZXRjaFwiPlxuICAgICAgICBtdWx0aXBhcnQgdXNpbmcgPHN0cm9uZz51c2VGZXRjaDwvc3Ryb25nPlxuICAgICAgPC9idXR0b24+XG4gICAgICA8YnV0dG9uIEBjbGljaz1cInVzaW5nTmF0aXZlRmV0Y2hcIj5cbiAgICAgICAgbXVsdGlwYXJ0IHVzaW5nIDxzdHJvbmc+bmF0aXZlIGZldGNoPC9zdHJvbmc+XG4gICAgICA8L2J1dHRvbj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2PlxuICAgICAgQ2hlY2sgPHN0cm9uZz5tdWx0aXBhcnQvZm9ybS1kYXRhOyBib3VuZGFyeTwvc3Ryb25nPiBvbiBkZXZ0b29sc1xuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJtZXNzYWdlXCI+XG4gICAgICBVc2luZyA8c3Ryb25nPm5hdGl2ZSBmZXRjaDwvc3Ryb25nPiBlYWNoIHJlcXVlc3QgPHN0cm9uZz5zaG91bGQ8L3N0cm9uZz4gY2hhbmdlIHRoZSBib3VuZGFyeSBvZiA8c3Ryb25nPkNvbnRlbnQtVHlwZTwvc3Ryb25nPiByZXF1ZXN0IGhlYWRlciwgd2hpbGUgdXNpbmcgPHN0cm9uZz51c2VGZXRjaDwvc3Ryb25nPiwgdGhlIGJvdW5kYXJ5IDxzdHJvbmc+c2hvdWxkIGJlPC9zdHJvbmc+IHRoZSBzYW1lIG9uIGVhY2ggcmVxdWVzdC5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuPHN0eWxlPlxuICAuY29udGFpbmVyIHtcbiAgICBkaXNwbGF5OiBncmlkO1xuICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogMWZyO1xuICAgIGdyaWQtcm93LWdhcDogMXJlbTtcbiAgICBwYWRkaW5nOiAxcmVtO1xuICAgIGp1c3RpZnktaXRlbXM6IGNlbnRlcjtcbiAgfVxuICAuYnV0dG9ucyB7XG4gICAgZGlzcGxheTogZ3JpZDtcbiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdCgyLCAxZnIpO1xuICAgIGdyaWQtY29sdW1uLWdhcDogMXJlbTtcbiAgfVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG5cdFx0XCJAdnVldXNlL2NvcmVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL2NvcmUvZGlzdC9pbmRleC5lc20uanNcIixcbiAgICBcIkB2dWV1c2Uvc2hhcmVkXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZXVzZS9zaGFyZWQvZGlzdC9pbmRleC5lc20uanNcIixcbiAgICBcInZ1ZS1kZW1pXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vdnVlLWRlbWkvbGliL2luZGV4LmVzbS5qc1wiXG4gIH1cbn0ifQ==)? I cannot make it working, the `content-type` header using `useFetch` is always `text/plain`.

**Comment by userquin** [comment]
[here](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXHRpbXBvcnQgeyB1c2VGZXRjaCB9IGZyb20gJ0B2dWV1c2UvY29yZSdcbiAgXG4gIGNvbnN0IGJ1aWxkRm9ybURhdGEgPSAoKSA9PiB7XG4gICAgY29uc3QgZm9ybURhdGEgPSBuZXcgRm9ybURhdGEoKVxuICAgIGZvcm1EYXRhLmFwcGVuZChcbiAgICAgIFwiQVwiLCBcbiAgICAgIG5ldyBCbG9iKFxuICAgICAgICBbSlNPTi5zdHJpbmdpZnkoeyBtZXNzYWdlOiBgTXVsdGlwYXJ0IEE6ICR7TWF0aC5yYW5kb20oKX1gfSldLCBcbiAgICAgICAgeyB0eXBlOiAnYXBwbGljYXRpb24vanNvbicgfVxuICAgICAgKSwgXG4gICAgICAndGVzdC1tdWx0aXBhcnQtYS5qc29uJ1xuICAgIClcbiAgICBmb3JtRGF0YS5hcHBlbmQoXG4gICAgICBcIkJcIiwgXG4gICAgICBuZXcgQmxvYihcbiAgICAgICAgW0pTT04uc3RyaW5naWZ5KHsgbWVzc2FnZTogYE11bHRpcGFydCBCOiAke01hdGgucmFuZG9tKCl9YH0pXSwgXG4gICAgICAgIHsgdHlwZTogJ2FwcGxpY2F0aW9uL2pzb24nIH1cbiAgICAgICksIFxuICAgICAgJ3Rlc3QtbXVsdGlwYXJ0LWIuanNvbidcbiAgICApXG4gICAgcmV0dXJuIGZvcm1EYXRhXG4gIH1cblxuICBjb25zdCB7IHBvc3QsIGV4ZWN1dGUgfSA9IHVzZUZldGNoKCcvbXVsdGlwYXJ0Jywge1xuICAgIG1ldGhvZDogJ1BPU1QnLFxuICAgIHBheWxvYWQ6IGJ1aWxkRm9ybURhdGEoKSxcbiAgICBwYXlsb2FkVHlwZTogJ2Zvcm1EYXRhJyxcbiAgICBpbW1lZGlhdGU6IGZhbHNlXG4gIH0pXG4gIFxuICBjb25zdCB1c2luZ1VzZUZldGNoID0gYXN5bmMoKSA9PiB7XG4gICAgY29uc3QgcGF5bG9hZCA9IGJ1aWxkRm9ybURhdGEoKVxuICAgIGNvbnNvbGUubG9nKHBvc3QpXG4gICAgdHJ5IHtcbiAgICAgIGNvbnNvbGUubG9nKHBvc3QocGF5bG9hZCwgJ2Zvcm1EYXRhJykpXG4gICAgICBleGVjdXRlKClcbiAgICB9IGNhdGNoKGlnbm9yZSkge1xuICAgICAgLy8ganVzdCBpZ25vcmVcbiAgICB9XG4gIH1cbiAgY29uc3QgdXNpbmdOYXRpdmVGZXRjaCA9IGFzeW5jKCkgPT4ge1xuICAgIHRyeSB7XG5cdFx0XHRjb25zdCByZXNwb25zZSA9IGF3YWl0IGZldGNoKCcvbXVsdGlwYXJ0Jywge1xuICAgICAgICBtZXRob2Q6ICdQT1NUJyxcbiAgXHRcdFx0Ym9keTogYnVpbGRGb3JtRGF0YSgpLFxuICAgICAgfSlcbiAgICB9IGNhdGNoIChpZ25vcmUpIHtcbiAgICAgIC8vIGp1c3QgaWdub3JlIGVycm9yXG4gICAgfVxuICB9XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgIDxkaXYgY2xhc3M9XCJidXR0b25zXCI+XG4gICAgICA8YnV0dG9uIEBjbGljaz1cInVzaW5nVXNlRmV0Y2hcIj5cbiAgICAgICAgbXVsdGlwYXJ0IHVzaW5nIDxzdHJvbmc+dXNlRmV0Y2g8L3N0cm9uZz5cbiAgICAgIDwvYnV0dG9uPlxuICAgICAgPGJ1dHRvbiBAY2xpY2s9XCJ1c2luZ05hdGl2ZUZldGNoXCI+XG4gICAgICAgIG11bHRpcGFydCB1c2luZyA8c3Ryb25nPm5hdGl2ZSBmZXRjaDwvc3Ryb25nPlxuICAgICAgPC9idXR0b24+XG4gICAgPC9kaXY+XG4gICAgPGRpdj5cbiAgICAgIENoZWNrIDxzdHJvbmc+bXVsdGlwYXJ0L2Zvcm0tZGF0YTsgYm91bmRhcnkgb24gQ29udGVudC1UeXBlIHJlcXVlc3QgaGVhZGVyPC9zdHJvbmc+IG9uIGRldnRvb2xzXG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbiAgLmNvbnRhaW5lciB7XG4gICAgZGlzcGxheTogZ3JpZDtcbiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDFmcjtcbiAgICBncmlkLXJvdy1nYXA6IDFyZW07XG4gICAgcGFkZGluZzogMXJlbTtcbiAgICBqdXN0aWZ5LWl0ZW1zOiBjZW50ZXI7XG4gIH1cbiAgLmJ1dHRvbnMge1xuICAgIGRpc3BsYXk6IGdyaWQ7XG4gICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoMiwgMWZyKTtcbiAgICBncmlkLWNvbHVtbi1nYXA6IDFyZW07XG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuXHRcdFwiQHZ1ZXVzZS9jb3JlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZXVzZS9jb3JlL2Rpc3QvaW5kZXguZXNtLmpzXCIsXG4gICAgXCJAdnVldXNlL3NoYXJlZFwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2Uvc2hhcmVkL2Rpc3QvaW5kZXguZXNtLmpzXCIsXG4gICAgXCJ2dWUtZGVtaVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pL2xpYi9pbmRleC5lc20uanNcIlxuICB9XG59In0=)  other playground using `post` + `execute`

**Comment by userquin** [comment]
[this one](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cblx0aW1wb3J0IHsgdXNlRmV0Y2ggfSBmcm9tICdAdnVldXNlL2NvcmUnXG4gIFxuICBjb25zdCBidWlsZEZvcm1EYXRhID0gKCkgPT4ge1xuICAgIGNvbnN0IGZvcm1EYXRhID0gbmV3IEZvcm1EYXRhKClcbiAgICBmb3JtRGF0YS5hcHBlbmQoXG4gICAgICBcIkFcIiwgXG4gICAgICBuZXcgQmxvYihcbiAgICAgICAgW0pTT04uc3RyaW5naWZ5KHsgbWVzc2FnZTogYE11bHRpcGFydCBBOiAke01hdGgucmFuZG9tKCl9YH0pXSwgXG4gICAgICAgIHsgdHlwZTogJ2FwcGxpY2F0aW9uL2pzb24nIH1cbiAgICAgICksIFxuICAgICAgJ3Rlc3QtbXVsdGlwYXJ0LWEuanNvbidcbiAgICApXG4gICAgZm9ybURhdGEuYXBwZW5kKFxuICAgICAgXCJCXCIsIFxuICAgICAgbmV3IEJsb2IoXG4gICAgICAgIFtKU09OLnN0cmluZ2lmeSh7IG1lc3NhZ2U6IGBNdWx0aXBhcnQgQjogJHtNYXRoLnJhbmRvbSgpfWB9KV0sIFxuICAgICAgICB7IHR5cGU6ICdhcHBsaWNhdGlvbi9qc29uJyB9XG4gICAgICApLCBcbiAgICAgICd0ZXN0LW11bHRpcGFydC1iLmpzb24nXG4gICAgKVxuICAgIHJldHVybiBmb3JtRGF0YVxuICB9XG5cbiAgY29uc3QgeyAvKnBvc3QsICovZXhlY3V0ZSB9ID0gdXNlRmV0Y2goJy9tdWx0aXBhcnQnLCB7XG4gICAgaW1tZWRpYXRlOiBmYWxzZVxuICB9KS5wb3N0KGJ1aWxkRm9ybURhdGEoKSwgJ2Zvcm1EYXRhJylcbiAgXG4gIGNvbnN0IHVzaW5nVXNlRmV0Y2ggPSBhc3luYygpID0+IHtcbiAgICAvL2NvbnN0IHBheWxvYWQgPSBhd2FpdCBidWlsZEZvcm1EYXRhKClcbiAgICAvL2NvbnNvbGUubG9nKHBvc3QpXG4gICAgdHJ5IHtcbiAgICAgIC8vY29uc29sZS5sb2cocG9zdChwYXlsb2FkLCAnZm9ybURhdGEnKSlcbiAgICAgIGF3YWl0IGV4ZWN1dGUoKVxuICAgIH0gY2F0Y2goZSkge1xuICAgICAgLy8ganVzdCBpZ25vcmVcbiAgICAgIGNvbnNvbGUubG9nKCd1cHBzJywgZSlcbiAgICB9XG4gIH1cbiAgY29uc3QgdXNpbmdOYXRpdmVGZXRjaCA9IGFzeW5jKCkgPT4ge1xuICAgIHRyeSB7XG5cdFx0XHRjb25zdCByZXNwb25zZSA9IGF3YWl0IGZldGNoKCcvbXVsdGlwYXJ0Jywge1xuICAgICAgICBtZXRob2Q6ICdQT1NUJyxcbiAgXHRcdFx0Ym9keTogYnVpbGRGb3JtRGF0YSgpLFxuICAgICAgfSlcbiAgICB9IGNhdGNoIChpZ25vcmUpIHtcbiAgICAgIC8vIGp1c3QgaWdub3JlIGVycm9yXG4gICAgfVxuICB9XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgIDxkaXYgY2xhc3M9XCJidXR0b25zXCI+XG4gICAgICA8YnV0dG9uIEBjbGljaz1cInVzaW5nVXNlRmV0Y2hcIj5cbiAgICAgICAgbXVsdGlwYXJ0IHVzaW5nIDxzdHJvbmc+dXNlRmV0Y2g8L3N0cm9uZz5cbiAgICAgIDwvYnV0dG9uPlxuICAgICAgPGJ1dHRvbiBAY2xpY2s9XCJ1c2luZ05hdGl2ZUZldGNoXCI+XG4gICAgICAgIG11bHRpcGFydCB1c2luZyA8c3Ryb25nPm5hdGl2ZSBmZXRjaDwvc3Ryb25nPlxuICAgICAgPC9idXR0b24+XG4gICAgPC9kaXY+XG4gICAgPGRpdj5cbiAgICAgIENoZWNrIDxzdHJvbmc+bXVsdGlwYXJ0L2Zvcm0tZGF0YTsgYm91bmRhcnkgb24gQ29udGVudC1UeXBlIHJlcXVlc3QgaGVhZGVyPC9zdHJvbmc+IG9uIGRldnRvb2xzXG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbiAgLmNvbnRhaW5lciB7XG4gICAgZGlzcGxheTogZ3JpZDtcbiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDFmcjtcbiAgICBncmlkLXJvdy1nYXA6IDFyZW07XG4gICAgcGFkZGluZzogMXJlbTtcbiAgICBqdXN0aWZ5LWl0ZW1zOiBjZW50ZXI7XG4gIH1cbiAgLmJ1dHRvbnMge1xuICAgIGRpc3BsYXk6IGdyaWQ7XG4gICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoMiwgMWZyKTtcbiAgICBncmlkLWNvbHVtbi1nYXA6IDFyZW07XG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuXHRcdFwiQHZ1ZXVzZS9jb3JlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZXVzZS9jb3JlL2Rpc3QvaW5kZXguZXNtLmpzXCIsXG4gICAgXCJAdnVldXNlL3NoYXJlZFwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2Uvc2hhcmVkL2Rpc3QvaW5kZXguZXNtLmpzXCIsXG4gICAgXCJ2dWUtZGVtaVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pL2xpYi9pbmRleC5lc20uanNcIlxuICB9XG59In0=) should work but the `content-type` is set to `text/plain`

**Comment by userquin** [comment]
there is something wrong on `setMethod`, provided `payloadType` is `formData` but seems the assigment is wrong, see value tooltip once assigned:

![imagen](https://user-images.githubusercontent.com/6311119/120099252-d4f4a980-c13a-11eb-8715-c1948f261dc2.png)

**Comment by userquin** [comment]
the assigment should be `config.payloadType = payloadType || (typeof payload === 'string' ? 'text' : 'json');`

**Comment by userquin** [comment]
[here](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IHsgcmVmLCBjb21wdXRlZCB9IGZyb20gJ3Z1ZSdcblx0aW1wb3J0IHsgdXNlRmV0Y2ggfSBmcm9tICdAdnVldXNlL2NvcmUnXG4gIGltcG9ydCB7IHVzZVRvZ2dsZSB9IGZyb20gJ0B2dWV1c2Uvc2hhcmVkJ1xuICBcbiAgY29uc3QgbmF0aXZlRGF0YSA9IHJlZignJylcbiAgY29uc3QgdXNlTmF0aXZlID0gcmVmKGZhbHNlKVxuIFxuICBcbiAgY29uc3QgYnVpbGRGb3JtRGF0YSA9ICgpID0+IHtcbiAgICBjb25zdCBmb3JtRGF0YSA9IG5ldyBGb3JtRGF0YSgpXG4gICAgZm9ybURhdGEuYXBwZW5kKFxuICAgICAgXCJBXCIsIFxuICAgICAgbmV3IEJsb2IoXG4gICAgICAgIFtKU09OLnN0cmluZ2lmeSh7IG1lc3NhZ2U6IGBNdWx0aXBhcnQgQTogJHtNYXRoLnJhbmRvbSgpfWB9KV0sIFxuICAgICAgICB7IHR5cGU6ICdhcHBsaWNhdGlvbi9qc29uJyB9XG4gICAgICApLCBcbiAgICAgICd0ZXN0LW11bHRpcGFydC1hLmpzb24nXG4gICAgKVxuICAgIGZvcm1EYXRhLmFwcGVuZChcbiAgICAgIFwiQlwiLCBcbiAgICAgIG5ldyBCbG9iKFxuICAgICAgICBbSlNPTi5zdHJpbmdpZnkoeyBtZXNzYWdlOiBgTXVsdGlwYXJ0IEI6ICR7TWF0aC5yYW5kb20oKX1gfSldLCBcbiAgICAgICAgeyB0eXBlOiAnYXBwbGljYXRpb24vanNvbicgfVxuICAgICAgKSwgXG4gICAgICAndGVzdC1tdWx0aXBhcnQtYi5qc29uJ1xuICAgIClcbiAgICByZXR1cm4gZm9ybURhdGFcbiAgfVxuXG4gIGNvbnN0IHsgLypwb3N0LCAqL2V4ZWN1dGUsIGRhdGEgfSA9IHVzZUZldGNoKCdodHRwczovL2h0dHBiaW4ub3JnL3Bvc3QnLCB7XG4gICAgaW1tZWRpYXRlOiBmYWxzZVxuICB9KS5wb3N0KGJ1aWxkRm9ybURhdGEoKSwgJ2Zvcm1EYXRhJylcbiAgXG4gIGNvbnN0IHVzZUZldGNoRGF0YSA9IGNvbXB1dGVkKCgpID0+IHtcbiAgICBpZiAobmF0aXZlRGF0YS52YWx1ZSkge1xuICAgICAgcmV0dXJuICcnXG4gICAgfSBlbHNlIHtcbiAgICAgIGlmIChkYXRhLnZhbHVlKSB7XG4gICAgICAgIHJldHVybiBKU09OLnN0cmluZ2lmeShkYXRhLnZhbHVlKVxuICAgICAgfSBlbHNlIHtcbiAgICAgICAgcmV0dXJuICcnXG4gICAgICB9XG4gICAgfVxuICB9KVxuICBcbiAgY29uc3QgdXNpbmdVc2VGZXRjaCA9IGFzeW5jKCkgPT4ge1xuICAgIC8vY29uc3QgcGF5bG9hZCA9IGF3YWl0IGJ1aWxkRm9ybURhdGEoKVxuICAgIC8vY29uc29sZS5sb2cocG9zdClcbiAgICBuYXRpdmVEYXRhLnZhbHVlID0gJydcbiAgICB1c2VOYXRpdmUudmFsdWUgPSBmYWxzZVxuICAgIHRyeSB7XG4gICAgICAvL2NvbnNvbGUubG9nKHBvc3QocGF5bG9hZCwgJ2Zvcm1EYXRhJykpXG4gICAgICBhd2FpdCBleGVjdXRlKClcbiAgICB9IGNhdGNoKGUpIHtcbiAgICAgIC8vIGp1c3QgaWdub3JlXG4gICAgICBjb25zb2xlLmxvZygndXBwcycsIGUpXG4gICAgfVxuICB9XG4gIGNvbnN0IHVzaW5nTmF0aXZlRmV0Y2ggPSBhc3luYygpID0+IHtcbiAgICBuYXRpdmVEYXRhLnZhbHVlID0gJydcbiAgICB1c2VOYXRpdmUudmFsdWUgPSB0cnVlXG4gICAgdHJ5IHtcblx0XHRcdGNvbnN0IHJlc3BvbnNlID0gYXdhaXQgZmV0Y2goJ2h0dHBzOi8vaHR0cGJpbi5vcmcvcG9zdCcsIHtcbiAgICAgICAgbWV0aG9kOiAnUE9TVCcsXG4gIFx0XHRcdGJvZHk6IGJ1aWxkRm9ybURhdGEoKSxcbiAgICAgIH0pXG4gICAgICBuYXRpdmVEYXRhLnZhbHVlID0gYXdhaXQgcmVzcG9uc2UuanNvbigpXG4gICAgfSBjYXRjaCAoaWdub3JlKSB7XG4gICAgICAvLyBqdXN0IGlnbm9yZSBlcnJvclxuICAgIH1cbiAgfVxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG4gIDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwiYnV0dG9uc1wiPlxuICAgICAgPGJ1dHRvbiBAY2xpY2s9XCJ1c2luZ1VzZUZldGNoXCI+XG4gICAgICAgIG11bHRpcGFydCB1c2luZyA8c3Ryb25nPnVzZUZldGNoPC9zdHJvbmc+XG4gICAgICA8L2J1dHRvbj5cbiAgICAgIDxidXR0b24gQGNsaWNrPVwidXNpbmdOYXRpdmVGZXRjaFwiPlxuICAgICAgICBtdWx0aXBhcnQgdXNpbmcgPHN0cm9uZz5uYXRpdmUgZmV0Y2g8L3N0cm9uZz5cbiAgICAgIDwvYnV0dG9uPlxuICAgIDwvZGl2PlxuICAgIDxkaXY+XG4gICAgICBDaGVjayA8c3Ryb25nPm11bHRpcGFydC9mb3JtLWRhdGE7IGJvdW5kYXJ5IG9uIENvbnRlbnQtVHlwZSByZXF1ZXN0IGhlYWRlcjwvc3Ryb25nPiBvbiBkZXZ0b29sc1xuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJkYXRhXCI+XG4gICAgICA8cHJlIHYtaWY9XCJ1c2VOYXRpdmVcIj5cbiAgICAgICAge3sgbmF0aXZlRGF0YSB9fVxuICAgICAgPC9wcmU+XG4gICAgICA8cHJlIHYtZWxzZT5cbiAgICAgICAge3sgdXNlRmV0Y2hEYXRhIH19XG4gICAgICA8L3ByZT5cbiAgICA8L2Rpdj5cbiAgIFxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c3R5bGU+XG4gIC5jb250YWluZXIge1xuICAgIGRpc3BsYXk6IGdyaWQ7XG4gICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiAxZnI7XG4gICAgZ3JpZC1yb3ctZ2FwOiAxcmVtO1xuICAgIHBhZGRpbmc6IDFyZW07XG4gICAganVzdGlmeS1pdGVtczogY2VudGVyO1xuICB9XG4gIC5idXR0b25zIHtcbiAgICBkaXNwbGF5OiBncmlkO1xuICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogcmVwZWF0KDIsIDFmcik7XG4gICAgZ3JpZC1jb2x1bW4tZ2FwOiAxcmVtO1xuICB9XG4gIC5kYXRhIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBvdmVyZmxvdy14OiBhdXRvO1xuICB9XG4gIHByZSB7XG4gICAgZm9udC1zaXplOiAwLjZyZW07XG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuXHRcdFwiQHZ1ZXVzZS9jb3JlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZXVzZS9jb3JlL2Rpc3QvaW5kZXguZXNtLmpzXCIsXG4gICAgXCJAdnVldXNlL3NoYXJlZFwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2Uvc2hhcmVkL2Rpc3QvaW5kZXguZXNtLmpzXCIsXG4gICAgXCJ2dWUtZGVtaVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pL2xpYi9pbmRleC5lc20uanNcIlxuICB9XG59In0=) a playground using `httpbin.org`, once fixed we need to update `@vueuse` version on it and test again, the `useNativeFetch` is working as expected, we have the 2 files entries on the response.

**Comment by userquin** [comment]
Other issue I have found, is that we cannot reuse the execute method once called: we cannot change the payload once executed, since the first execution will change `initialized` to `false` and so, calling again `setMethod` will just do nothing, it is protected to avoid changing anything in the `config` object once `initialized` is set to `true`.

For example, I recently need to upload files in chunks of `127KB` to avoid increment `SSL buffer` (for security reasons) since I login my users with `SSL mutual auth`. With this restriction on `useFetch`, it will be a pain, the chunked upload is just using `Blob::slice` method to upload the corresponding chunk, but using `useFetch` we need to recreate the instance for each chunk.

**Comment by userquin** [comment]
added PR to fix wrong payload type assigment on `setMethod`: #549
