### ISSUE TITLE
Add return types for all composables

### ISSUE THREAD

**Issue by Shinigami92** [vueuse/vueuse#543]
I personally make use of heavy TypeScript by using the eslint rule [typedef](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/typedef.md)

So we could add a return type and export these explicitly for every function.
We also don't need to type them safly but just create somewhat aliases.

We can do that like so

```ts
export function useMouse(options: MouseOptions = {}) { /*...*/ }

export type UseMouse = ReturnType<typeof useMouse>
```

Are you open for such an addition?

---

Currently I'm forced to define these myself: https://github.com/Shinigami92/vizscript/blob/c3d26fd3f921787dab0bf25cb9d024d170824225/src/views/Viz.vue#L55-L56

**Comment by wheatjs** [comment]
I think it would be great to have them all export their interfaces. For ones that don't currently have an interface I think it would probably be a good idea to do what you suggested. For the ones that do, we can just export their interface

Are you interested in opening a PR? If you do I'd suggest targeting the next branch 🙂

**Comment by Shinigami92** [comment]
I will try
