### ISSUE TITLE
usePointerSwipe: target inital styles removed on click

### ISSUE THREAD

**Issue by ilkome** [vueuse/vueuse#548]
When I have initial styles on **target** element and click to it, my initial styles removed and changed to **touch-action: initial**
https://gfycat.com/nicesoftcoelacanth
https://github.com/ilkome/usepointerswipe/blob/master/src/App.vue

**Comment by jeffrey-dot-li** [comment]
should change 
```targetRef.value?.setAttribute("style", "touch-action: none");```
to 
```targetRef.value?.style.setProperty("touch-action", "none");```
from [this line](https://github.com/vueuse/vueuse/blob/cfc1ed8525ae1fabdb21b248999702a059ea9212/packages/core/usePointerSwipe/index.ts#L130)

**Comment by ilkome** [comment]
And this one to
https://github.com/vueuse/vueuse/blob/cfc1ed8525ae1fabdb21b248999702a059ea9212/packages/core/usePointerSwipe/index.ts#L102
