### ISSUE TITLE
seek a solution about the dist of vueuse that is not escaped from es6 to es5 

### ISSUE THREAD

**Issue by PaulChess** [vueuse/vueuse#551]
Hello, antfu!
I encountered a problem that I found the `dist` of `vueuse` didn't transfrom es6 to es5。So when i installed vueuse in my project and built it, the packaging product of my project contains es6 grammar such as `const`、`Arrow function` .etc。

I have a question that why the code in the npm package and cdn link of `vueuse` is not translated into`es5` 。I think perhaps installing npm packages directly or introducing cdn links in some of the company's projects will cause problems with low-version models so that we cannot use `vususe` in out projects。

![image](https://user-images.githubusercontent.com/69644161/120189583-1de75380-c24a-11eb-896f-e4586692787f.png)

I have tried to solve this question by myself。I think the config about `babel` in `babel.config.js` and `vue.config.js` is effective, because the code in my project has all successfully been translated into es5。
The version of my `babel` is `>7`, I wonder if it is my babel that does not translate the 3rd library in node_modules, I added it into the `config.module`, such as `config.module.include.add('/node_modules/@vueuse')`, but still failed。

Here is the part of the config of my `vue.config.js` and `babel.config.js`:
```javascript
// vue.config.js
    config.module
      .rule('js')
      .rule('vue')
      .include
      .add('/packages')
      .add('/examples')
      .add('/node_modules/@vueuse')
      .end()
      .use('babel')
      .loader('babel-loader')
      .tap((options) => options);
```
```javascript
// babel.config.js
module.exports = {
  presets: [
    ['@vue/cli-plugin-babel/preset', {
      useBuiltIns: 'usage',
    }],
  ],
  plugins: [
    [
      '@babel/plugin-transform-runtime', {
        corejs: 3,
      },
    ],
  ],
};
```

I really hope to find a solution from you, thank you! 😁

**Comment by userquin** [comment]
@antfu just downgrade `tsconfig.json` target to `ES5`: you will need to modify  `useURLSearchParams/index.ts`, line 50, just add `// @ts-ignore` before the for loop.

With these 2 changes `cjs` does not contain `es6` syntax.

`MODIFIED useURLSearchParams/index.ts`:

![imagen](https://user-images.githubusercontent.com/6311119/120239137-f1d5cd80-c25d-11eb-9645-ba38a188027d.png)

`ERROR ON useURLSearchParams/index.ts WITH ES5`:

![imagen](https://user-images.githubusercontent.com/6311119/120239255-26e22000-c25e-11eb-930f-61ba1523f765.png)

`MODIFIFED tsconfig.json`:

![imagen](https://user-images.githubusercontent.com/6311119/120239082-d10d7800-c25d-11eb-92df-d5c8be7ca322.png)

**Comment by userquin** [comment]
@antfu since you are using our best friend, `esno`, just changing `scripts/rollup.config.js`, adding a second config for only `esm` and removing it from the exisiting one, and configuring `plugins.typescript.tsconfigOverride.compilerOptions.target` entry correctly for each one, I have it working, that is, `es5` for `iief` and `cjs` and `es2017` for the module.

You will still need to add `@ts-ignore` on `useURLSearchParams/index.ts`, line 50.

I suggest you to downgrade `target: 'ES5'` on `tsconfig.json` file and so the build will not fail.

`MODIFIED scripts/rollup.config.js`

```typscrypt
  configs.push({
    input: `packages/${name}/index.ts`,
    output: [
      {
        file: `packages/${name}/dist/index.cjs.js`,
        format: 'cjs',
      },
      {
        file: `packages/${name}/dist/index.iife.js`,
        format: 'iife',
        name: iifeName,
        extend: true,
        globals: iifeGlobals,
        plugins: [
          injectVueDemi,
        ],
      },
      {
        file: `packages/${name}/dist/index.iife.min.js`,
        format: 'iife',
        name: iifeName,
        extend: true,
        globals: iifeGlobals,
        plugins: [
          injectVueDemi,
          terser({
            format: {
              comments: false,
            },
          }),
        ],
      },
    ],
    plugins: [
      typescript({
        tsconfigOverride: {
          compilerOptions: {
            target: 'ES5',
            declaration: false,
          },
        },
      }),
    ],
    external: [
      'vue-demi',
      '@vueuse/shared',
      ...(external || []),
    ],
  })

  configs.push({
    input: `packages/${name}/index.ts`,
    output: [
      {
        file: `packages/${name}/dist/index.esm.js`,
        format: 'es',
      },
    ],
    plugins: [
      typescript({
        tsconfigOverride: {
          compilerOptions: {
            target: 'es2017',
            declaration: false,
          },
        },
      }),
    ],
    external: [
      'vue-demi',
      '@vueuse/shared',
      ...(external || []),
    ],
  })
```

**Comment by antfu** [comment]
@userquin Thanks for looking into it, but honestly I think this should be done by the user side instead of changing our code to ES5 compatible. Even tho it might not be much code to change, but shipping higher version of ES also mean we could have more concise and efficient code for users does not require ES5 or lower. And on the other hand, it's also much easier to transpiling down and up.

For further proof, I would prefer to keep our codebase and build system as-is.

I don't mind to keep this issue opened for ppl to find solution on the user side (sorry I am not familiar with babel).

**Comment by userquin** [comment]
@antfu I agree with you, that's why there is no PR ;) 

@PaulChess have you try just including the babel in main and just build using modern flag enabled? This will build a modern using esm and legacy bundles.

**Comment by userquin** [comment]
@PaulChess I use this setup with `vue-cli-service`, but not tested with `@vueuse`, maybe you only need to add `transpileDependencies` on `vite.config.js`:

- install babel polyfill as dev dependency, for example: `"@babel/polyfill": "^7.0.0-beta.49"`
- add `babel.config.js` to the root directory of the project (you already have it):
```javascript
module.exports = {
  "presets": [
    ["@vue/app", {
        "useBuiltIns": "entry"
    }],
    ["@babel/preset-env", {
      "modules": false
    }]
  ]
};
```
- enable modern flag on `package.json`: `"build": "vue-cli-service build --modern"`
- add `import "@babel/polyfill";` at top of `main.js`.
- add `transpileDependencies` entry on `vue.config.js` file, for example I transpile `vuetify`, just include there `@vueuse` packages you use:
```javascript
module.exports = {
  transpileDependencies: ["vuetify"],
  ...
```

**Comment by PaulChess** [comment]
@userquin Thank you for your help!
I have just tried the method you provided, it works!  I forgot to add `transpileDependencies` option in my `vue.config.js`.
So we can indeed compile `vueuse` in our projects.

**Comment by icepole-jon** [comment]
@PaulChess 请问你是怎么设置的？我改了各种配置都没搞定babel转换，加了 `transpileDependencies: ["@vueuse/core"]` 也没用
能否贴一份具体的 `vue.config.js` 感谢！
