### ISSUE TITLE
How to read value in useLocalStorage?

### ISSUE THREAD

**Issue by xieyezi** [vueuse/vueuse#552]
First , I use `useLocalStorage` to init `IS_LOGIN` in `Login.vue`:

```ts
const isLogin = useLocalStorage('IS_LOGIN', true)
```
And then , I need read it in other pages, But I don't konw how to read it,  may be like this:

```
const token = useLocalStorage(key)
```
But it's tip me need `defalutValue`, So how to read it  exactly?

**Comment by antfu** [comment]
How about:

```ts
import { isLogin } from './shared'
```

**Comment by xieyezi** [comment]
@antfu 
Normally, the correct way to use is：
```ts
const isLogin = useLocalStorage('IS_LOGIN', true)
```
`defalutValue` should be  optional，when this parameter is passed in, it's should be carried out`storage.set` function.

And when I want to get value, I just use like this:

```ts
const isLogin = useLocalStorage('IS_LOGIN')
```
it's not need `defalutValue`.  It's should be carried out`storage.get` function.

How about this?

**Comment by antfu** [comment]
```ts
// shared.ts
export const isLogin = useLocalStorage('IS_LOGIN', true)
```

```ts
// a.vue

import { isLogin } from './shared'

console.log(isLogin.value)
```

```ts
// b.vue

import { isLogin } from './shared'

console.log(isLogin.value)
```

If you really want to just read the value only, why not:

```ts
localStorage.getItem('IS_LOGIN')
```

**Comment by xieyezi** [comment]
@antfu 

The main reason is that I need to set the value of IS_LOGIN after the login verification is completed, and then I need to get it in other pages.

I'll use `localStorage.getItem('IS_LOGIN')`, it's useful! 

Thanks!

**Comment by sherodtaylor** [comment]
^ Can this be reopened because it should do an initial fetch at least. useStorage has serializers for objects built in

**Comment by xieyezi** [comment]
Maybe you can provide pr for this.😀
