### ISSUE TITLE
useVModel 无效

### ISSUE THREAD

**Issue by hqylss111** [vueuse/vueuse#554]
//父组件
`<template>
  <div>
    <MyButton :foo='foo'  v-model="foo"></MyButton>
  </div>
</template>
<script>
import { ref } from "@vue/reactivity";
import MyButton from "../components/MyButton";
export default {
  components: {
    MyButton,
  },
  methods: {},
  computed: {},
  setup() {
    const foo = ref("1");
    return { foo };
  },
};
</script>

//子组件
`
<template>
  <div>
    <button @click="ceshi">我是子组件</button>
    {{ foo }}
  </div>
</template>

<script>
import { useVModel } from "@vueuse/core";

export default {
  props: {
    foo: String,
  },
  methods:{
    ceshi:function(){
      console.log(this);
      this.data = '我是测试' //修改无效 没有进行更新
    }
  },
  setup(props, { emit }) {
    const data = useVModel(props, "foo", emit);
    return { data};
  },
};`
`

**Comment by antfu** [comment]
Please proper format your code and describe your issue correctly
