### ISSUE TITLE
useObservable: should allow the consumer to pass an error handler

### ISSUE THREAD

**Issue by benlesh** [vueuse/vueuse#566]
Look at [where we're currently subscribing](https://github.com/vueuse/vueuse/blob/303705deaa3388fcaff990fa1159690d3f8248fc/packages/rxjs/useObservable/index.ts#L7), there's no error handler being passed.

This means that any error that happens in the observable will be "unhandled", which is fine, however, it might be worth giving users the option to handle the error like so:  `useObservable(source$, { onError: err => { /* do something */ } })`. The observable subscription would, of course, still terminate, however, RxJS would no longer treat errors that propagated to the point of subscription as "unhandled errors". (provided that the user supplied an error handler). If no `onError` is supplied, then we should allow RxJS to do it's thing.

**Comment by wheatjs** [comment]
Would probably prefer an event hook rather than an option https://vueuse.org/shared/createEventHook/

**Comment by benlesh** [comment]
@wheatjs that's interesting. And if that's more idiomatic for Vue, I'd happily do that. I'll create a second PR so it can be considered.
