### ISSUE TITLE
useToggle: add more methods

### ISSUE THREAD

**Issue by revyh** [vueuse/vueuse#585]
## The proposition
How about adding more methods to the `useToggle` and make ref readonly? Like
```js
const showModal = useToggle(initialValue);

showModal.state // readonly ref
showModal.enable() // the same as showModal.value = true
showModal.disable() // the same as showModal.value = false
showModal.toggle() // the same as showModal.value = !showModal.value
```

## Why
1. currently, users can change ref value, like `const [toggler] = useToggle(); toggler.value = 'string value'`
2. it's not aligned with other APIs. E.g. `useCouter` has `set` method instead of `const counter = useCounter(); counter.counter.value = 10`
3. it's debatable, but I think that `showModal.enable()` is nicer, terser, and more explicit than `showModal.value = true`

I can author the PR if needed.

**Comment by wheatjs** [comment]
This would be a breaking change though, right? Not sure if the tradeoffs are worth it

**Comment by revyh** [comment]
Yes, it would be a breaking change. I can make a pr that you can label by something like "6.0 release" and merge it when you decide to release the next major version.

**Comment by antfu** [comment]
I would prefer `toggle(true)` for force enabling, just like the `classList.toggle(true)` in DOM
