### ISSUE TITLE
[Feature Request] useFetch transform payload into search params when using GET method

### ISSUE THREAD

**Issue by xuzaixian** [vueuse/vueuse#586]
I think it's a quite usual case when sending request by GET method.

**Comment by xuzaixian** [comment]
If there is anyone likes this feature, i'd like to create pr for this

**Comment by wheatjs** [comment]
There has been discussion about this, but we are looking to slim down on `useFetch` and make it a minimal wrapper for the fetch api. Writing a `fetch` good library is pretty complicated so we would probably suggest using something like `useAxios` instead. We could also introduce something like `useKy`(https://github.com/sindresorhus/ky) if users wanted a more modern solution to `useAxios`

**Comment by xuzaixian** [comment]
Ok, I will use `useAxios` instread.

**Comment by Grawl** [comment]
I don't like Axios API and I don't like `useAxios` API, but I very liked `useFetch` API. I like it's error handling, before/after fetch hooks, and reactivity. Only two things that's missing is query builder for `.get()` request and mixed output type (some of my API methods returning different types: string in one scenario and JSON in another).

**Comment by IamMille** [comment]
> There has been discussion about this, but we are looking to slim down on `useFetch` and make it a minimal wrapper for the fetch api. 

Maybe I'm misunderstanding something here, but there is essentially no logic needed to be added? 
Just use `URLSearchParamsParams` and allow a parameter to be passed to the .get() method here?

**Comment by Grawl** [comment]
Also there is a good [`qs`](https://github.com/ljharb/qs) library to convert type safe object to query string, I use it like this:

```ts
export const getURL = (url: string, query?: Record<string, string | number>): string => {
	if (query !== undefined) {
		return `${url}?${qs.stringify(query)}`
	}
	return url
}
```
