### ISSUE TITLE
feat: useWindowFocus for when the document isn't focused but still visible

### ISSUE THREAD

**Issue by vaaski** [vueuse/vueuse#600]
I think this feature request is pretty self-explanatory.

A boolean ref stating if the document has focus or not.
This differs from useDocumentVisibility in that it'd use `window.onfocus`, `window.onblur` and `document.hasFocus()` instead.

I want to use this for a page that has a looping animation that represents an activated state, but it doesn't need to be distracting when the user is not actively working with the window and just has it open on a secondary display for example.

If you want I can work on a PR for this, should be rather easy.

**Comment by antfu** [comment]
Sounds good, PR welcome

**Comment by vaaski** [comment]
I've basically copied the useDocumentVisbility folder and modified it for useWindowFocus.

However it doesn't get added to packages/core/index.ts and also doesn't show up in the dev docs, not sure why. The contrib doc also didn't help me with that.

Here's [the commit](https://github.com/vaaski/vueuse/commit/8d631b0eb1d722d4f2750f21f61ca49f94900f50).

**Comment by wheatjs** [comment]
It will be added via the build commands, no need to worry about it. Can you make a PR from your fork, thanks

**Comment by vaaski** [comment]
perfect, thanks
