### ISSUE TITLE
onKeyUp('Space', e => console.log('Space key up')) doesn't work

### ISSUE THREAD

**Issue by ivanq3w** [vueuse/vueuse#610]
Why KeyFilter takes "key" from KeyboardEvent by default?
onKeyUp('  ', e => console.log('Space key actually up'))

Unclear workaround is KeyPredicate
```
export declare type KeyPredicate = (event: KeyboardEvent) => boolean
export declare type KeyFilter = null | undefined | string | KeyPredicate
```

onKeyUp(e => e.code === 'Space', e => console.log('Space key actually up'))

https://vueuse.org/core/onKeyStroke/#type-declarations

**Comment by wheatjs** [comment]
The `key` event represents the value the was inserted by the keyboard while `code` is the physical key. In general I think most cases people would prefer `key` to `code`.  Perhaps we could introduce a config option to `KeyStrokeOptions` to have it use `code` instead

**Comment by CasperSocio** [comment]
> for those who are looking why
> 
> ```js
>  onKeyStroke('Space', () => {
>   console.log('space key')
> })
> ```
> 
> does not work, it needs to be `' '` instead of `'Space'`:
> 
> ```js
>  onKeyStroke(' ', () => {
>   console.log('space key')
> })
> ```

Yes, but when using `v-on-key-stroke`, there is no way of selecting spacebar as a modifier.
