### ISSUE TITLE
`useDebounce` allow `maxWait`

### ISSUE THREAD

**Issue by isgj** [vueuse/vueuse#615]
Do you consider adding a `maxWait` option to `debounce` family functions?
It should be greater than the debounce time.

**Comment by antfu** [comment]
I am not sure if I understand what it does. Do you have any prior art that we could reference to?

**Comment by isgj** [comment]
It's the same as `maxWait` of [lodash debounce](https://lodash.com/docs/4.17.15#debounce)

> The maximum time func is allowed to be delayed before it's invoked.

Ex: with `debounce` and `wait = 500ms`, if there is an interaction every `400ms` the callback will never be called, it will be debounced forever. Sometimes in order to improve UX you want the callback to be called if a `maxWait` has been passed.

`wait = 500` `mawWait = 1000`

|time|interaction|callback called|action
|--|--|--|--|
|0|yes|no|debounced after 500ms|
|400|yes|no|debounced after 500ms|
|800|yes|no|debounced after 200ms (800(`now`)+500(`wait`) > 1000(`maxWait`))|
|1000|no|yes|set last call to now (next debounce can't be before 1500,  next `maxWait` can't be before 2000ms )|

If `maxWait` < `wait` it becomes a `throttle`
