### ISSUE TITLE
useStylesheet

### ISSUE THREAD

**Issue by wheatjs** [vueuse/vueuse#619]
This is a function I ended up writing for the Vueuse playground, but thought maybe it we might want to have here.

The general idea is to provide a reactive [CSSStyleSheet](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet)

The current API I have looks like something like
```ts
const { rules } = useStyleSheet('stylesheet-name')

rules.value = {
  '.my-special-class': 'background-color: red; display: block;',
}
```

Perhaps this api could be improved a bit during a PR if we want this. Of course this is also a pretty niche use-case especially in a vue application so I thought maybe I should make an issue before creating a PR

**Comment by antfu** [comment]
Sound like a thing. I'd prefer to accept a plain CSS string instead of an object as those rules replying on orders and might have duplicated selectors. Later on we could have another function to provide a css-in-js like objects to css string transform for composing with this.

**Comment by wheatjs** [comment]
Sounds good, I'll start a PR
