### ISSUE TITLE
useGeolocation -> Configurable Config

### ISSUE THREAD

**Issue by michealroberts** [vueuse/vueuse#620]
A brief look at the `useGeolocation` sensor documentation here: https://vueuse.org/core/useGeolocation/

There doesn't seem to be a way to *ACTUALLY* configure the PositionObjects of the Geolocation API as per Mozilla docs:

[https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition)

The vueUse documentation states that "useGeolocationfunction takes PositionOptions object as an optional parameter."

However, when I call it as:

```
    // Reactive Geolocation API. It allows the user to provide their location
    // to web applications if they so desire. For privacy reasons, the user is
    // asked for permission to report location information.
    const { coords, locatedAt, error } = useGeolocation({
      maximumAge: Infinity,
      enableHighAccuracy: false,
      timeout: Infinity
    })
```

It doesn't seem to call subsequent page loads from the cache?

I'm assuming that maybe a page load causes a load from fresh? Am I looking at a Browser specific issue?

Happy to be corrected, of course.

**Comment by michael-observerly** [comment]
So I have been testing the above config for a while - and as a team we can't see any caching occurring ... 

Browser: Version 91.0.4472.114 (Official Build) (arm64)

**Comment by antfu** [comment]
Not sure if I understand your questions. I'd actually use this API, so if you could help looking into the implementations and see if there is a fix could be apply and make a PR, we would be happy to have it. Thanks!

**Comment by michael-observerly** [comment]
Hi @antfu Anthony, many thanks for your reply.

Essentially, we're passing in options for `useGeolocation()` as:

```js
// Reactive Geolocation API. It allows the user to provide their location
    // to web applications if they so desire. For privacy reasons, the user is
    // asked for permission to report location information.
    const { coords, locatedAt, error } = useGeolocation({
      maximumAge: Infinity,
      enableHighAccuracy: false,
      timeout: Infinity
    })
```

But see no difference when we change these values, or. just call `useGeolocation()`.

It feels like we could be missing a trick here, but it seems that whatever we do - the function will just fallback to the defaults from the Geolocation API?

**Comment by gimyboya** [comment]
I think that is because the default values are always overriding the config passed as a param see here
