### ISSUE TITLE
useControllableValue

### ISSUE THREAD

**Issue by impeiran** [vueuse/vueuse#622]
Do we have a hook like the `useControllableValue` in `ahooks` ?
https://ahooks.js.org/hooks/state/use-controllable-value

In some cases, we need the state to be managed by itself or controlled by it's parent.

**Comment by antfu** [comment]
Meaning this https://vueuse.org/shared/controlledref?

**Comment by impeiran** [comment]
thanks a lot ~ but maybe not  what i want
