### ISSUE TITLE
Vue-demi import error

### ISSUE THREAD

**Issue by dragomirweb** [vueuse/vueuse#624]
Not sure is a good ideea to have vue-demi as dependency as any version.
![image](https://user-images.githubusercontent.com/29796024/125826088-57f2371e-6f09-422c-a8b1-c7ff358fd004.png)
They did a release and now:
![image](https://user-images.githubusercontent.com/29796024/125826189-ddc13906-8391-4e76-8578-610e74991380.png)

**Comment by antfu** [comment]
Working on it, keep track on https://github.com/vueuse/vue-demi/issues/73

**Comment by mrgodhani** [comment]
@antfu  Still seeing above error when running on webpack. Is this updated for the core package?
