### ISSUE TITLE
[useElementBounding]: doesn't update bounding box on scroll

### ISSUE THREAD

**Issue by jeffrey-dot-li** [vueuse/vueuse#626]
I'm a bit confused about what useElementBounding is *supposed* to do but if it is supposed to mirror [getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) like it says in the docs then it should update the properties such as `top` and `y` relative to the viewport scroll like the example in the mozilla documentation: 
![image](https://user-images.githubusercontent.com/46302202/125879294-79379e5d-3378-41de-8ab9-2e2f36ffdc65.png)
![image](https://user-images.githubusercontent.com/46302202/125879314-9ea50dde-eaf8-49bb-a701-22371137ea1c.png)

Currently bounding box doesnt change on scroll
![image](https://user-images.githubusercontent.com/46302202/125879350-5a582c3f-65ff-48fe-a5ef-667544249c2b.png)
![image](https://user-images.githubusercontent.com/46302202/125879362-de5b802e-f1d3-4487-bdd9-f2eb5c1679fd.png)

**Comment by jeffrey-dot-li** [comment]
Maybe this isn't what element bounding is intended for? In that case, can we add a hook for `getBoundingClientRect` similar to what is used in `useMouseInElement`?
https://github.com/vueuse/vueuse/blob/b3d1e2c8c6715dd972392c85a2080dcfe52cab09/packages/core/useMouseInElement/index.ts#L51

**Comment by pwang2** [comment]
I also feel it is weird to not have a BCR `reactive` to resizing, scrolling.   I managed to get it work as below, but feel not very satisfied. 

```ts
import { useElementBounding, useResizeObserver } from "@vueuse/core"
const triggerRect = reactive(useElementBounding(trigger))
useResizeObserver(document.documentElement, () => {
  Object.assign(triggerRect, useElementBounding(trigger))
})```

**Comment by m0dch3n** [comment]
not sure, if this is related too, but

```javascript
const mydiv = ref()
const { width } = useElementBounding(mydiv)
onMounted(() => {
  console.log('div', mydiv.value) // the div is consoled
  console.log('width value', width.value) // is still 0
  console.log('width clientrect', mydiv.value.getBoundingClientRect().width) // is correct width
  setTimeout(() => {
    console.log('width value 3', width.value) // is correct width value...
  })
})
```

The dimensions should be available after onMounted....

**Comment by Hebilicious** [comment]
@m0dch3n Had the same issue, #1541 fixes it 👍🏽
