### ISSUE TITLE
Vue2中，怎么使用useFullscreen让浏览器全屏？

### ISSUE THREAD

**Issue by DDDInJava** [vueuse/vueuse#627]
如题，vue版本 2，
怎么使用useFullscreen ，然后页面加载完成后，浏览器自动进入全屏？

**Comment by antfu** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen

> Note: This method must be called while responding to a user interaction or a device orientation change; otherwise it will fail.

Do yourself a favor to research a bit before asking, honestly, this is the issue tracker for the project, not somewhere to ask for help.

**Comment by DDDInJava** [comment]
Sorry！
