### ISSUE TITLE
[useFetch] Add `fetchError` and/or `fetchFinally` hooks

### ISSUE THREAD

**Issue by glen-84** [vueuse/vueuse#628]
There's currently no way to execute code (for example, hiding a spinner) when there is an error.

`onFetchError` can only be used when calling `useFetch`, but as far as I know, you can't configure this before-hand using `createFetch`.

Would it be possible to add a `fetchError` and/or a `fetchFinally` hook, to enable this?

**Comment by glen-84** [comment]
@antfu @wheatjs Could you please reopen this? (see https://github.com/vueuse/vueuse/pull/631#issuecomment-881700338)

**Comment by glen-84** [comment]
Thinking about this a bit more, and I think that `fetchError` is probably more useful than `fetchFinally`, unless the latter also includes an `error` object.

It might be useful to throw errors in a `fetchError` hook, in addition to stopping a spinner (for example).

**Comment by glen-84** [comment]
@wheatjs ?

**Comment by wheatjs** [comment]
> @wheatjs ?

Sorry was under the impression that you weren't interested in this anymore based on your last message. I'll get this done before v6.x is released if you are still wanting it

**Comment by glen-84** [comment]
No problem. Ya, I was just saying that I think `fetchError` might be more useful than `fetchFinally`.

**Comment by climba03003** [comment]
@glen-84 Hi, I am +1 for this feature and I have created a PR related to it.
Can you check if it fit your needs too?
