### ISSUE TITLE
`useIntervalFn` Allow immediately firing callback

### ISSUE THREAD

**Issue by hognevevle** [vueuse/vueuse#636]
Thank you for updating the docs (https://github.com/vueuse/vueuse/commit/6e7704e6f231fb8ea462e3be42cfa15a6c59cdfc)

I would, however, love to use the `immediate` feature as originally advertised, so I can actually trigger the callback immediately. Maybe this could be supported via a second option?

**Comment by antfu** [comment]
Yeah, happy to have it and PR welcome
