### ISSUE TITLE
[useInterval] a soft suggestion to this function's usage

### ISSUE THREAD

**Issue by TonyPythoneer** [vueuse/vueuse#638]
Using libs:

```
"@nuxtjs/composition-api": "^0.24.7", // it includes "@vue/composition-api": "1.0.0-rc.14",
"@vueuse/core": "^5.1.3",
```
---

https://vueuse.org/shared/useInterval/#usage

Originally, I expect that I can use `watch` to monitor the change of `intervalTrigger`. But, it seems invalid.

```
    const intervalTrigger = useInterval(1000);
    watch(intervalTrigger, () => {
      console.log('!!!!!!!!!!!!');
    });
```

Alternatively, I use `useIntervalFn`, so I don't have the issue.

If users want to use the combination of `useInterval` and `watch` and it doesn't work, I think that the document can make a hint  for uses who want to do the same thing as me.

**Comment by wheatjs** [comment]
This works fine for me. Can you provide a reproduction?

**Comment by TonyPythoneer** [comment]
Hmm, let me think about this. 
Let me close it.
