### ISSUE TITLE
Issue with @vue/composition-api v1.0.3

### ISSUE THREAD

**Issue by tobidalhof** [vueuse/vueuse#640]
Is anyone else unable to use `@vueuse/core ^5.1.4` with the [latest release](https://github.com/vuejs/composition-api/releases/tag/v1.0.3) of `@vue/composition-api`? Downgrading to `1.0.2` temporarily solves the issue.

Error message:

```
[vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.
```

It only affects components that are using `@vueuse/core` functions

**Comment by tobidalhof** [comment]
should be fixed after pr https://github.com/vueuse/vue-demi/pull/77 is merged

**Comment by antfu** [comment]
Please try https://github.com/vuejs/composition-api/releases/tag/v1.0.4
