### ISSUE TITLE
onClickOutside do not trigger on scrollbar click

### ISSUE THREAD

**Issue by VincentVanclef** [vueuse/vueuse#641]
Using this lovely library for a modal system, where i want to close the modal if you click on the backdrop. However, targeting the inner content with: onClickOutside does so it closes if i click the vertical scrollbar, incase the content overflows.

Would it be possible to disable that?

Atm ive hack-fixed it with:

```
        const content = ref(null);

        onClickOutside(content, (event) => {
            if (event.clientX < document.documentElement.clientWidth - SCROLLBARWIDTH) {
                props.dialog.close();
            }
        });
```

**Comment by Alucard17** [comment]
@antfu Can I take it?

**Comment by antfu** [comment]
@Alucard17 sure, thanks!

**Comment by sibbng** [comment]
Except Safari `document.documentElement.clientWidth` already giving scrollbar width excluded width. So `- SCROLLBARWIDTH` part is unnecessary if you are not using Safari or custom scrollbar element in your DOM and could result unexpected behaviors on other browsers. In this case I would suggest you using that:

```js
  const { clientWidth } = document.documentElement
  const scrollbarX =
    window.innerWidth -
    (clientWidth !== window.innerWidth
      ? clientWidth
      : SAFARI_SCROLLBARWIDTH)

  if (event.clientX < scrollbarX) {
    props.dialog.close()
  }
```

To fix this issue we should:
1- Handle vertical and horizontal scrollbars.
2- Be sure scrollbars are available. (by comparing `document.documentElement.clientHeight` and `document.documentElement.scrollHeight`)
3- Predefined scrollbar width/height for Safari if `clientWidth` and `window.innerWidth` are same and `scrollHeight` higher than `clientHeight` (and its X axis equivalents for horizontal scrollbars).
4- Provide a way to customize scrollbar width (for all cases not just safari, for custom scrollbars)

In my opinion modals who overflows viewport are rare use cases and implementing all of these are will unnecessarily raise this function's size. Instead we should make an utility function (i.e `isScrollbarClick()`) handles these cases outside `onClickOutside` function. Like the example up here.

**Comment by yulafezmesi** [comment]
for those who wondering checking `currentTarget` might be a solution.

  if (event.currentTarget) {
    handleDestory()
  }
