### ISSUE TITLE
@ Symbol conflicts the Typescript src import

### ISSUE THREAD

**Issue by cosmotranglobal** [vueuse/vueuse#646]
Please am using VUE3 with typescript.
And as standard the `tsconfig.json` file has an src directory import denoted as @.
```JSON
{
  "compilerOptions": {
     ...
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
   }
}
```

And the import for This vueuse is.
`import { usePackage} from '@vueuse/<package>'`
But doing so. Would give error.
**Module not found: Error: Can't resolve '@vueuse/\<package\>' in 'VUE\project\src'**

I believe it's a conflict due to the **@** symbol and the name of the module.

Please is there a fix on how to import this library on typescript Vue3? Thanks 🙏

**Comment by antfu** [comment]
I don't think it's related. There are hundreds of packages that starts with @ scopes. Guess there might be some misconfigure in your project.

**Comment by vixson** [comment]
@cosmotranglobal 
You can check out https://github.com/vuestorefront/shopware-pwa/issues/1541 or
https://github.com/vuejs/vue-cli/issues/1198
That might help you fix your tsconfig for this current issue.
