### ISSUE TITLE
Using shared composable in VueUse library for efficiency

### ISSUE THREAD

**Issue by jd-0001** [vueuse/vueuse#665]
According to this md (https://github.com/vuejs/rfcs/blob/master/active-rfcs/0041-reactivity-effect-scope.md). We can create a shared composable which is more efficient. I don't know if the current implementation of composable functions is using it. I checked the source code of `useMouse` but didn't found `onScopeDispose` hence I am raising this issue.

Regards.

**Comment by wheatjs** [comment]
https://github.com/vueuse/vueuse/blob/next/packages/core/useEventListener/index.ts#L122 See the next branch for the effect scope implementations. This will be available by default in v6.x, currently in beta. https://github.com/vueuse/vueuse/releases/tag/v6.0.0-beta.1
