### ISSUE TITLE
[Feature] useReactives

### ISSUE THREAD

**Issue by yooneskh** [vueuse/vueuse#670]
I have an idea to make a helper function similiar to `toRefs` named `toReactives` which gets a ref object and decomposes it into a normal object which every key is a `reactive` instead of a `ref`.

I wanted to make this mainly for decomposing `props` because right now we only have `toRefs` to do this and this forces us to have a `.value` every time we want to reference props in code.

My idea was that since `reactive()` deeply unwraps `refs`, such implementations would work.

```js
function toReactives(refObject) {

  const result = {};

  for (const key of Object.keys(refObject)) {
    result[key] = reactive(toRef(refObject, key));
  }

  return result;

};
```
```js
function toReactives(refObject) {

  const result = {};

  for (const key of Object.keys(refObject)) {
    result[key] = reactive(computed(() => refObject[key]));
  }

  return result;

};
```
```js
function toReactives(refObject) {

  const result = {};
  const refs = toRefs(refObject);

  for (const key of Object.keys(refs)) {
    result[key] = reactive(refs[key]);
  }

  return result;

};
```
but neither works, `ref`s are not unwrapped in any of these. i am ok to submit a PR if i be able to fix this.

**Comment by antfu** [comment]
This would probably do

```ts
function toReactive(r: Ref<T>): T {
  const proxy = new Proxy({}, {
    get(_, p, receiver) {
      return Reflect.get(r.value, p, receiver)
    },
    set(_, p, value, receiver) {
      return Reflect.set(r.value, p, value, receiver)
    }
  })

  return reactive(proxy)
}
```

**Comment by antfu** [comment]
I will give a try on the implication

**Comment by antfu** [comment]
close by #671

**Comment by yooneskh** [comment]
Thanks for your time and attention. sorry i was so busy these days and couldn't contribute. 

I had some questions on the new toReactive function.

1- How does that solve destructuring problem? I sould still loop on the props keys and construct a new object right?

2- This should work on primitives like strig too right?

3- can this be added like in vue-global-api?

**Comment by antfu** [comment]
1. No, it's a limitation of `reactive` / JS itself
2. No, proxy only work on object. You will get a runtime error if you try that.
3. Take a look at vue-global-api's dist, you will find how to define your custom global apis. `vue-global-api` will only include vue's composition-api itself for now
