### ISSUE TITLE
Error typing in useAsyncState

### ISSUE THREAD

**Issue by Djaler** [vueuse/vueuse#676]
Both `onError` callback and `error` ref have `Error` type. But error thrown from promise may be not an error (thanks, js). For example, I know one validation library that throws custom object instead of Error. So, I think, we should change `Error` to `unknown` here

**Comment by antfu** [comment]
Ok, pr welcome :)

**Comment by Djaler** [comment]
Sure, I can provide a PR. But wouldn't it be a breaking change?
