### ISSUE TITLE
onClickOutside presents event management difficulties

### ISSUE THREAD

**Issue by Aaron-Pool** [vueuse/vueuse#681]
I've recently that discovered that, since the onClickOutside listener does not allow you to target the basic `click` event, it creates issues with potentially interrupting the event.

Reproduction Example: https://rliqq.csb.app/

Imagine that the square is a content section for the user to interact with. I have a button to open the section, and then you can click off the section to collapse it. But, just in case this isn't obvious to the user I make the button a open/close toggle. So that the user can click off to close (if that is intuitive to them) _or_ the user can intentionally toggle the square closed.

Well, if you try to toggle it closed, both the clickOff and the click event fires and it starts to close and then reopens. If the onClickOutside usable used the `click` event, I could just handle this with some event phase/stop propagation settings. But since I can't use `click` they operate on a different even lifecycle and the two events don't interact.

Is there a reason the typing doesn't include `click` as a targetable event?

**Comment by sibbng** [comment]
As a author of that function adding that event was in my mind for a while. I just missed it on my initial commit and didn't want to rush to add it before seeing real world use cases. Thanks for demo 👌.
