### ISSUE TITLE
The ts type error causes the actual code to be inconsistent with the semantics

### ISSUE THREAD

**Issue by jiangmaniu** [vueuse/vueuse#685]
Since the `VueInstance` type is actually expressed as `any` instead of the expected `Vue` instance, the `MaybeElementRef` type dependent on `VueInstance` is also `any`. In the `useResizeObserver` method, the `target` parameter can be any Value, I can pass in any value such as numbers, strings, etc.Although there is a null value judgment in the `unrefElement` method, I personally feel that it does not meet the type semantics.

![image](https://user-images.githubusercontent.com/50100681/130177566-774cd513-7b67-4979-9c06-e7fc492b6dc7.png)

![image](https://user-images.githubusercontent.com/50100681/130177550-1fb16f32-f8db-4803-a066-390612739926.png)

If this is intentional or designed, can you explain the intention? or directly close the issue.

**Comment by zedyuan999** [comment]
I have the same opinion as you, I saw a package of unrefElement , There is a type VueInstance  which is actually any  in it

**Comment by zedyuan999** [comment]
I have the same opinion as you, I saw a package of `unrefElement` today , There was a type `VueInstance` which is actually any in it
