### ISSUE TITLE
[useVModel] shows ts(1117) error

### ISSUE THREAD

**Issue by jzs11** [vueuse/vueuse#688]
Hi,

I am facing an annoying error in the IDE by using the VueUse's useVModel. The project sill can compile, but the TS server keeps reporting this as a syntactical error. I have turned the strict mode off in the tsconfig file, but it still persists. 

![image](https://user-images.githubusercontent.com/2770401/130372091-8e98d2c7-ab48-4c94-9f3c-f1453f0db2b8.png)
![image](https://user-images.githubusercontent.com/2770401/130372099-b1e324c7-8abf-4c01-baa3-1b075a54e68d.png)

Any ideas I could get around with it?

BTW, why do we need to have :data and v-model:data to make it work?

Thanks

**Comment by dheimoz** [comment]
hey @jzs11 did you manage to sort it out?, Mind sharing with the community how?

Thanks.

**Comment by jzs11** [comment]
Hi @dheimoz, we just need to remove the :data for the short-hand binding. 
v-model:data binding is a two way binding and :data is one way binding 😉

For more info you can find here: https://stackoverflow.com/questions/42260233/vue-js-difference-between-v-model-and-v-bind
