### ISSUE TITLE
throttleFilter: maybe has a bug

### ISSUE THREAD

**Issue by rhdehf1030** [vueuse/vueuse#689]
Hello. Thanks for this awesome library.

I found **throttleFilter** executed twice within the durations.

https://github.com/vueuse/vueuse/blob/c403545538f50104baccd26afc411db76506aaa6/packages/shared/utils/filters.ts#L91-L96

I think the lastExec variable is not being modified in the setTimeout function

I want to check if there is a reason why lastExec is not modified in setTimeout function.

Thanks!

**Comment by antfu** [comment]
Looks like a bug, PR welcome, thanks!
