### ISSUE TITLE
Support new firebase SDK

### ISSUE THREAD

**Issue by wheatjs** [vueuse/vueuse#697]
Since firebase has released a new modular/smaller SDK we should look into supporting it at some point. Just opening an issue so I don't forget. Will look into adding this sometime over the weekend if I get the time.

https://firebase.googleblog.com/2021/08/the-new-firebase-js-sdk-now-ga.html

**Comment by FranciscoKloganB** [comment]
Any forecast on when this upgrade is going to be tackled?

**Comment by antfu** [comment]
I personally don't use Firebase recently and have no bandwidth to do it. There is an existing work #775 by @peter50216 but closed due to conflicts. If anyone wants to get it supported, you can start fresh or based on @peter50216's work.

One notable thing is that we might want to also support v8 for a while longer, so as discussed in #775, we should support two sub-modules like `@vueuse/firebase/v8` and `@vueuse/firebase/v9` and redirect the default `@vueuse/firebase` to `v8` and move in the next major version. Thanks.

**Comment by wheatjs** [comment]
So I was looking into making a PR for this earlier, but it seems kind of tricky. It seems like we will would need 2 separate npm packages to support this since v8 and v9 use different versions. Maybe there are ways to get around this, although I'm not sure exactly how to myself. 

I was thinking since our firebase functions are in their own package perhaps we could just upgrade to v9 and make a note in the docs for people using v8 to install a version that supports v8? I don't think there will be many changes coming to firebase v8, meaning our current composable should be pretty stable, so I feel like leaving it as an older package version wouldn't be a big issue, maybe I'm wrong?

**Comment by peter50216** [comment]
> I personally don't use Firebase recently and have no bandwidth to do it. There is an existing work #775 by @peter50216 but closed due to conflicts. If anyone wants to get it supported, you can start fresh or based on @peter50216's work.
> 
> One notable thing is that we might want to also support v8 for a while longer, so as discussed in #775, we should support two sub-modules like `@vueuse/firebase/v8` and `@vueuse/firebase/v9` and redirect the default `@vueuse/firebase` to `v8` and move in the next major version. Thanks.

Wrong mention :P, @peterekjs for visibility.

**Comment by antfu** [comment]
> I was thinking since our firebase functions are in their own package perhaps we could just upgrade to v9

That would also do, but since all packages in VueUse share the same version, doing this means we need to bump the major version for all packages. Could also work, but that might need to wait for a while.

**Comment by peterekjs** [comment]
Sorry guys for me being inactive about this. There are differences between version 8 and version 9 compat in the import declarations:
```ts
import type firebase from 'firebase' // Firebase 8
```
vs
```ts
import type firebase from 'firebase/compat' // Firebase 9 compat
```
Therefore as I suggested in #775, the code should be actually present 3 times with small alterations for a short period of time (till next vueuse major?). Actually non-breakable solution would IMO be:

- **firebase** - Nothing changes here
- **firebase-9** - Firebase 9 modular
- **firebase-9/compat** - Firebase 9 compat library

In following week or two I could be able to find some spare time for this so we can close this issue ASAP.

**Comment by antfu** [comment]
Is `firebase/compact` compactable with firebase 8? If so we could be able to introduce

- `firebase` - Firebase 9 Compact
- `firebase/next` - Firebase 9

to ship them without breaking change and flip around in next major version to

- `firebase` - Firebase 9
- `firebase/compat` - Firebase 9 compat

**Comment by peterekjs** [comment]
> Is `firebase/compact` compactable with firebase 8? If so we could be able to introduce
> 
> * `firebase` - Firebase 9 Compact
> * `firebase/next` - Firebase 9
> 
> to ship them without breaking change and flip around in next major version to
> 
> * `firebase` - Firebase 9
> * `firebase/compat` - Firebase 9 compat

I'm affraid because of the import path difference, we are not able simply to switch to the new version without potentially breaking anything.
> ```ts
> import type firebase from 'firebase' // Firebase 8
> ```
> 
> vs
> 
> ```ts
> import type firebase from 'firebase/compat' // Firebase 9 compat
> ```

**Comment by smakinson** [comment]
looking forward to the firebase 9 version

**Comment by smakinson** [comment]
@peterekjs I grabbed the firebase-9 userFirestore from your branch to give it a go. I notice one thing that I wonder if you might have input in. I tried using computed to return one of 2 useFireStore refs, but the ref from computed seems to interfere with the useFirestore ref. Is this expected?

**Comment by hoanghadu** [comment]
Is there any update on this issue?

**Comment by gilesbutler** [comment]
Likewise, would love to see an update.

I came across this yesterday after trying to use the RTDB on a new project.

**Comment by smakinson** [comment]
I pulled out the code from this PR and have been using it along side vueuese in my own composables directory and have not had any issues with it. If anyone needs it right away you might consider doing that as well.

**Comment by gilesbutler** [comment]
Thanks for the heads up @smakinson! I'll give that a go 👍

**Comment by hoanghadu** [comment]
@gilesbutler Thanks. I am looking forward to hearing from you.

**Comment by gilesbutler** [comment]
We decided to take a different path in the @hoanghadu

**Comment by nyambe** [comment]
What is the status on this? I use firebase quite often.  How can I help?

**Comment by justice47** [comment]
Docs stated that Firebase 9 is supported by default.
We can close this issue probably.
