### ISSUE TITLE
feat: useInfiniteScroll, is simple but useful

### ISSUE THREAD

**Issue by Jay214** [vueuse/vueuse#712]
```js
import { onUnmounted } from 'vue-demi'
import { useIntersectionObserver, IntersectionObserverOptions } from '../useIntersectionObserver'
import { MaybeElementRef } from '../unrefElement'

/**
 * infinite load scrolling.
 *
 * @see https://vueuse.org/useInfiniteScroll
 * @param endTarget a target element to trigger the callback
 * @param callback
 * @param options
 */
export function useInfiniteScroll(endTarget: MaybeElementRef, callback: Function, options: IntersectionObserverOptions) {
  const { stop, isSupported } = useIntersectionObserver(endTarget, (entries) => {
    if (entries[0].intersectionRatio <= 0) return
    callback()
  }, options)
  onUnmounted(() => {
    stop()
  })
  return {
    stop,
    isSupported,
  }
}
```

Use existing methods to achieve infinite load scrolling. 
This is an attempt,
It can be done much better

**Comment by wheatjs** [comment]
Sounds cool, seems like a good use case for a renderless component. Maybe something like

```html
<UseInfiniteScroll>
  <div v-for="post in posts">
    {{ post }}
  </div>
  <template #trigger>
    <button>Load More</button>
  </template>
</UseInfiniteScroll>
```

**Comment by Jay214** [comment]
> Sounds cool, seems like a good use case for a renderless component. Maybe something like
> 
> ```
> <UseInfiniteScroll>
>   <div v-for="post in posts">
>     {{ post }}
>   </div>
>   <template #trigger>
>     <button>Load More</button>
>   </template>
> </UseInfiniteScroll>
> ```

Thank you. I'll do it

**Comment by arjan-kitchenstories** [comment]
Hello, just some feedback from a potential user of this composable. It would be very useful indeed and I hope that it's still something you are planning to contribute to the collection!

Thank you for your idea and work (including all VueUse contributors) 👍

**Comment by JessicaSachs** [comment]
So, I'm thinking about this component and DX https://codesandbox.io/s/react-virtualized-infinite-scrolling-with-grid-1dmsf

An infinitely scrollable, virtualized list where you can see how many items are "above" your current cursor. The only downside is that if it's a virtualized list you have to currently:
1. Manage the itemHeight
2. Deal with `wrapperProps` and `containerProps`

<img width="619" alt="Screen Shot 2021-12-23 at 3 55 34 PM" src="https://user-images.githubusercontent.com/2801156/147290748-3dfc0eaf-31c2-46c9-89e3-95795b60116f.png">

This makes the API more complex, but with those constraints, it would be a really performant + helpful composable.

**Comment by wheatjs** [comment]
@JessicaSachs maybe it would be a good idea to have a `useInfinteVirtualScroll` for that? Since `useInfiniteScroll` should be pretty simple we probably don't want users to be forced into using a virtual list or having to pay for the extra size of the virtual list

**Comment by JessicaSachs** [comment]
Yeah that popped into my head too but I wasnt sure if it was too excessive.
Alternative is to overload the API for both usages..? But tbqh I think
you’re right. We’ll do two separate ones with an identical API, minus the
virtual scroll requirements.
