### ISSUE TITLE
feat: useWrapperWebComponent  an idea.

### ISSUE THREAD

**Issue by Jay214** [vueuse/vueuse#716]
I have an idea. to wrap and register a Vue component as a custom element like @vue/web-component-wrapper .
But I don't know how to do that.
```js
const myCustomeElement = useWrapperWebComponent(vueComponent, 'my-custom-element')
<template>
<my-custom-element> </my-custom-element>
</template>
```

**Comment by antfu** [comment]
Is this what you are looking for? https://v3.vuejs.org/guide/web-components.html
