### ISSUE TITLE
Nuxt build fails with .mjs/.cjs extensions

### ISSUE THREAD

**Issue by itpropro** [vueuse/vueuse#718]
Since 6.2.0, Nuxt fails to build (I think because of the changed file extensions):

```
[fatal] Nuxt build error
  ERROR in ./node_modules/@vueuse/core/index.mjs 800:50-62
  Can't import the named export 'bypassFilter' from non EcmaScript module (only default export is available)
  @ ./layouts/default.vue?vue&type=script&lang=js& (./node_modules/cache-loader/dist/cjs.js??ref--2-0!./node_modules/babel-loader/lib??ref--2-1!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&)
  @ ./layouts/default.vue?vue&type=script&lang=js&
  @ ./layouts/default.vue
  @ ./node_modules/.cache/nuxt/App.js
  @ ./node_modules/.cache/nuxt/index.js
  @ ./node_modules/.cache/nuxt/client.js
  @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/composition-api/register.js ./node_modules/.cache/nuxt/client.js
  
  ERROR in ./node_modules/@vueuse/core/index.mjs 3271:25-30
  Can't import the named export 'clamp' from non EcmaScript module (only default export is available)
  @ ./layouts/default.vue?vue&type=script&lang=js& (./node_modules/cache-loader/dist/cjs.js??ref--2-0!./node_modules/babel-loader/lib??ref--2-1!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&)
  @ ./layouts/default.vue?vue&type=script&lang=js&
  @ ./layouts/default.vue
  @ ./node_modules/.cache/nuxt/App.js
  @ ./node_modules/.cache/nuxt/index.js
  @ ./node_modules/.cache/nuxt/client.js
  @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/composition-api/register.js ./node_modules/.cache/nuxt/client.js

4500+ lines ...
```

**Comment by antfu** [comment]
That's weird, can you remove the `./node_modules/.cache` and try again?

**Comment by antfu** [comment]
I found this can confirmed it fixes the same issue on Vue CLI

https://stackoverflow.com/a/64907659

**Comment by danielroe** [comment]
Likely this should be included by default for wp4 in Vue CLI. It should already be present in next version of Nuxt (2.16): https://github.com/nuxt/nuxt.js/pull/9180

**Comment by antfu** [comment]
Closing this as this is not an issue of the project itself and an workaround is provided.

**Comment by itpropro** [comment]
Thanks for the provided workaround!

I've added it to my nuxt.config.json, but the problem still persists:

```
export default {
  // Fix to load .mjs modules correctly, see https://github.com/vueuse/vueuse/issues/718
  extend(config) {
    config.module.rules.push({
      test: /\.mjs$/,
      include: /node_modules/,
      type: 'javascript/auto',
    })
  },
...
```

Using nuxt 2.15.8 and @nuxtjs/composition-api 0.28.0. Would the workaround be to wait for Nuxt 2.16 to be released and hold back the update until then @danielroe?

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by daofresh** [comment]
**Nuxt**

The `extend` method is an option of the `build` property, so the correct configuration should be

```js
// nuxt.config.js

export default {
  build: {
    extend(config) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto"
      });
    }
  }
}
```

**Comment by patrikengborg** [comment]
Tried the proposed solution above from @daofresh, but now the error is this:

`Module not found: Error: Can't resolve '@vue/composition-api/dist/vue-composition-api.esm.js'`

**Comment by danielroe** [comment]
@patrikengborg Would you check whether there is a problem when you upgrade to the latest version of node 12 or 14?

**Comment by patrikengborg** [comment]
@danielroe I'm on node 14.17.5 and upgrading the composition api to latest seems to have solved it, thanks!
However, I get another error now `vueDemi.getCurrentScope is not a function`, when using the onClickOutside function, but I haven't investigated, so that might be on me.

**Comment by itpropro** [comment]
> **Nuxt**
> 
> The `extend` method is an option of the `build` property, so the correct configuration should be
> 
> ```js
> // nuxt.config.js
> 
> export default {
>   build: {
>     extend(config) {
>       config.module.rules.push({
>         test: /\.mjs$/,
>         include: /node_modules/,
>         type: "javascript/auto"
>       });
>     }
>   }
> }
> ```

Thanks for your reply, I had it in my build config, but failed to copy the config correctly ;)

**Comment by itpropro** [comment]
> @danielroe I'm on node 14.17.5 and upgrading the composition api to latest seems to have solved it, thanks!
> However, I get another error now `vueDemi.getCurrentScope is not a function`, when using the onClickOutside function, but I haven't investigated, so that might be on me.

I had that problem with Nuxt, but fixed it by updating `@vue/composition-api`, that implemented these since v1.1

**Comment by itpropro** [comment]
> Can you share a minimal reproduction? Thanks.

I cannot reproduce it with a new nuxt repo, so it has to be somewhere in my configuration or modules. I will have to fix that myself :)

**Comment by michael-observerly** [comment]
> **Nuxt**
> 
> The `extend` method is an option of the `build` property, so the correct configuration should be
> 
> ```js
> // nuxt.config.js
> 
> export default {
>   build: {
>     extend(config) {
>       config.module.rules.push({
>         test: /\.mjs$/,
>         include: /node_modules/,
>         type: "javascript/auto"
>       });
>     }
>   }
> }
> ```

I can confirm that this also worked for me, Nuxt 2.15.7 and @nuxtjs/composition-api": "^0.27.0 (@vueuse/core v6.2.1)

**Comment by SachinAgarwal1337** [comment]
I am using this library wih ionic 5 with vue and I am not able to resolve it this with given suggesions.
Any idea how can it be resolved for ionic?

**Comment by sxzz** [comment]
@antfu  Hello, `element-plus` uses this library. Is there a way for users to use it with zero configuration?

**Comment by antfu** [comment]
The way I see it is that Webpack 4 should release a patch to have built-in support for .mjs files (Note that Webpack 5, Vite, Rollup are working fine with this). Giving the whole ecosystem is moving in that direction, it won't be a problem that is only limited to this library.

**Comment by oz-** [comment]
I've been trying to get rid of this error using the configuration proposed by @antfu in a Storybook + Vue + Typescript project. 
Error doesn't show anymore, but Storybook Webpack server doesn't work anymore ("Cannot GET /"). 
Any idea for Storybook support?
