### ISSUE TITLE
Symbol([vue-router]: route location)" not found

### ISSUE THREAD

**Issue by reslear** [vueuse/vueuse#722]
```
"@ionic/vue": "6.0.0-beta.5",
"@ionic/vue-router": "6.0.0-beta.5",
"@vueuse/core": "^6.2.1",
"@vueuse/router": "^6.2.1",
"vue-router": "^4.0.11",
"vue": "^3.2.9",
"@vue/compiler-sfc": "^3.2.9",
"@vue/cli-plugin-router": "~4.5.13",
```

<img width="707" alt="Screenshot 2021-09-06 at 20 28 21" src="https://user-images.githubusercontent.com/12596485/132249053-94a546ed-9eb9-41d3-ac85-58125128263a.png">

and in setup 

<img width="475" alt="Screenshot 2021-09-06 at 20 45 19" src="https://user-images.githubusercontent.com/12596485/132250064-3739374b-72f2-4b2a-ae8e-22171ed75162.png">

return `undefined`

**Comment by andrey-hohlov** [comment]
Works this way:

```js
const router = useRouter();
const route = useRoute();

const type = useRouteQuery('type', null, { router, route });
```

But I have no idea why.

**Comment by antfu** [comment]
... I don't think this issue belongs here. I guess you might forget to register the router instance. Please use Discord or Stackoverflow to ask questions.

**Comment by matt-snider** [comment]
@andrey-hohlov Thanks for the workaround. Did you happen to figure out what the issue was?

**Comment by genu** [comment]
I'm not sure why, but it seems in my case at least I always have to do:

```ts
const type = useRouteQuery('type', null, { router: useRouter(), route: useRoute() });
```

This could be a bug?
