### ISSUE TITLE
Can't import errors

### ISSUE THREAD

**Issue by Dezaos** [vueuse/vueuse#724]
Vue.js v4.5.13 with typescript
Vueuse v6.2.1

I'm getting a lot of 'can't import' errors when using this package, I have included some of them. I installed using npm.

 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'bypassFilter' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'clamp' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'computed' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'containsProp' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'createEventHook' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'createFilterWrapper' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'createSingletonPromise' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'customRef' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'getCurrentInstance' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'getCurrentScope' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'identity' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs
Can't import the named export 'ignorableWatch' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/index.mjs

**Comment by antfu** [comment]
#718
