### ISSUE TITLE
v6.3.x is  broken with vue2

### ISSUE THREAD

**Issue by Toilal** [vueuse/vueuse#729]
Because some functions are imported from `vue` instead of `vue/demi`, latest release is broken with vue 2.

https://github.com/vueuse/vueuse/compare/v6.2.1...v6.3.1 

https://github.com/vueuse/vueuse/blob/d0fa468799fd9637dac86d9c695ccff2d220d9e7/packages/core/useDraggable/index.ts#L1

**Comment by antfu** [comment]
Thanks!
