### ISSUE TITLE
How to handle load error properly with useScriptTag

### ISSUE THREAD

**Issue by hikariNTU** [vueuse/vueuse#730]
Issue
---

Currently `useScriptTag` will store the src element tag when the script is loaded with `resolveWithElement`, and the scriptTag ref can be interact with later on. 

```ts
const resolveWithElement = (el: HTMLScriptElement) => {
  scriptTag.value = el
  resolve(el)
  return el
}
```

But when the script load fail, `resolveWithElement` will never be called, which cause the scriptTag ref remain null. The `unload` function cannot properly unload the script element cause there's no reference available for unload function. Neither `load` function can **retry** again since the same tag element will be found in querySelector.

Should I create another `useScriptTag` or manually query&remove the script and load it again?

**Comment by coolhome** [comment]
I ran into this problem as well. I was looking into solutions but I'm not sure on the best approach yet. Below are some ideas I have floating around so far.

h3. Idea 1:
If we set `scriptTag` after the element is added to the document anyone who watches the scriptTag may assume it is also loaded when in reality is in an error state. Adding an additional return property for isLoaded may be a solution?

h3. Idea 2
Maybe `useScriptTag` on error/abort should remove the element or at least on the event pass the scriptTag value and let the developer determine how to handle the error?
