### ISSUE TITLE
[feature] useDebouncedRefHistory - History with delayed recording

### ISSUE THREAD

**Issue by harmyderoman** [vueuse/vueuse#732]
History will commit changes not immediately but after the given number of milliseconds, which will be received by the third parameter
```
const history = useDebouncedRefHistory(source, options, ms)
```
I think it's easy to do it by copy and slightly changing the code in useRefHistory. One needs to wrap manualCommit in useDebounceFn which accepts ms

**Comment by patak-js** [comment]
Hey @harmyderoman! This is an interesting idea. I think we should try to generalize this a bit because we would need to add `useThrotledRefHistory` and so on for each filter type later.

One way would be to do nothing in the implementation and document how you can create a debounced (or other types) ref yourself to pass to ref history. But given that VueUse exposes the filters machinery, we could extend the `useRefHistory` API to take an optional `eventFilter`.
We should then compose it with the pausableFilter before passing them to ignorableWatch around here https://github.com/vueuse/vueuse/blob/49c3c662de63201d1b42684ef47e8814eb7780f3/packages/core/useRefHistory/index.ts#L154

I don't know if we already have a `composeFilter` function that could be used here, if not, I think we should provide one. We could accept an array of filters in `eventFilter` also for convenience, but I think right now the composables taking an event filter expect a single object.

**Comment by harmyderoman** [comment]
> https://github.com/vueuse/vueuse/blob/49c3c662de63201d1b42684ef47e8814eb7780f3/packages/core/useRefHistory/index.ts#L154
> 
> I don't know if we already have a `composeFilter` function that could be used here, if not, I think we should provide one. We could accept an array of filters in `eventFilter` also for convenience, but I think right now the composables taking an event filter expect a single object.

You're right at the moment `ignorableWatch` only accepts one filter, if you can rewrite it to accept an entire array, that will help us. I also found `debounceFilter`, maybe it can help.

**Comment by patak-js** [comment]
@antfu would you think that the `eventFilter` param should always take a single filter (and make people compose them if they need several), or overload it to take an array (and compose internally if the next function is not ready to take an array)?

@harmyderoman would you like to try to create a PR for this? Looks like an interesting refactoring.

**Comment by harmyderoman** [comment]
@patak-js sure, I am on it! Need to figure out how to create this in the best way.

**Comment by antfu** [comment]
`composeFilter` is a nice idea. I think for the function argument we should keep it a single one, and let ppl to wrap with `composeFilter` when they want to have multiple ones. In this case, we have an internal one, we could use `composeFilter` to combining with user provided filter.

**Comment by harmyderoman** [comment]
Hi @patak-js and @antfu! I studied the code and realized that there is no need to compose all filters together, for example, there is no need to apply `throttleFilter` and `debounceFilter` at the same time, but both of these filters work well with `pausableFilter`. Suddenly I found that the `pausableFilter` is already set up to take an `extendFilter`. So I suggest refactoring the `useRefHistory` function so that it can accept an `extendFilter` in `options`, and use it to create `useDebouncedRefHistory` and `usethrottleRefHistory`. 

The creation of the `composeFilter` function should be postponed for now, until better times, perhaps when we have more filters. So far I do not see the need for significant changes to the code base.

**Comment by antfu** [comment]
Sounds good! It's been a while and we almost forgot about the details 😄

**Comment by harmyderoman** [comment]
> Sounds good! It's been a while and we almost forgot about the details 😄

Great, then I'll start writing a PR.

**Comment by patak-js** [comment]
Awesome! And ya, there is no need to have `composeFilter` now. As more filters are added, it will be more important.

About the `extendFilter` param, I think we should use the same convention as other composables and use `eventFilter` here. It would be good at one point to change `extendFilter` to `eventFilter` in `pausableWatch` too (it could be made with a deprecation without a breaking change). The name `extendFilter` implies that there is a filter already in use internally but that is an implementation detail. Looks like `pausableWatch` is the only one with this naming convention.

**Comment by harmyderoman** [comment]
>  I think we should use the same convention as other composables and use `eventFilter` here. 

Ok.

**Comment by patak-js** [comment]
Oh, I just saw that `pausableFilter` and not `paisableWatch` is the one with `extendFilter`. That naming makes sense for filters then, and other composables would use `eventFilter` 👌

**Comment by harmyderoman** [comment]
@patak-js So name the 3rd param `expandFilter` in `useRefHistory`?

**Comment by patak-js** [comment]
`eventFilter` for `useRefHistory`, following other composables. `extendFilter` would only be used for filters like `pausableFilter`. In the future, I would prefer to have a `composeFilter` util so we dont need to add these `extendFilter` params to every filter.

**Comment by harmyderoman** [comment]
PR created
