### ISSUE TITLE
Use `borderBoxSize` instead `contentRect`

### ISSUE THREAD

**Issue by sibbng** [vueuse/vueuse#735]
Currently we are using `contentRect` on `useElementBounding`, `useElementSize` source and `useResizeObserver` demo.

https://github.com/vueuse/vueuse/search?q=contentrect

[ResizeObserver MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) says:

> Note: The content box is the box in which content can be placed, meaning the border box minus the padding and border width. The border box encompasses the content, padding, and border. See The box model for further explanation.

So `width` and `height` variables returned from these functions don't take padding and border width into account.

This is especially wrong behavior for `useElementBounding`. Its name sounds like it uses `getBoundingClientRect()` internally which is includes padding and border width in `width` and `height` properties.

In my opinion we have to switch to `borderBoxSize` on all these search results. What you think?

**Comment by antfu** [comment]
Yes, sounds reasonable. This could be a breaking change and we would need to have it in next version version.
