### ISSUE TITLE
 error  in ./node_modules/@vueuse/core/index.mjs  Can't import the named export 'bypassFilter' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by jnarowski** [vueuse/vueuse#743]
I am not able to import any packages. I've tried useTitle and useDebounce. I have just setup the latest version of vue3 and vueuse. 

**Error**
Failed to compile.

./node_modules/@vueuse/core/index.mjs 953:50-62
Can't import the named export 'bypassFilter' from non EcmaScript module (only default export is available)

**Versions**
"@vueuse/core@^6.3.3":
vue@^3.0.0:
  version "3.2.10"
node: 14.17.6

**Comment by xfranklin** [comment]
Same issue
vue "^3.0.0"
node "16.9.0"

**Comment by DZ-study** [comment]
+1
vue@3.0.4

**Comment by antfu** [comment]
#718
