### ISSUE TITLE
`useEventSource` no option to just watch specific events

### ISSUE THREAD

**Issue by Shinigami92** [vueuse/vueuse#747]
Currently you can register for some `events`, but still all events are triggered and passed to `data`.  
What is the best practice to handle specific events and observe the data for only such an event? So e.g. the used `data`-`watch` don't get triggered for every event.

**Comment by Shinigami92** [comment]
@wheatjs I think this issue can be converted into a discussion. I don't have the permission to do that 🙂

**Comment by Atinux** [comment]
Agree with @Shinigami92 

I would like to refactor this part to use `useEventSource` but does not seem easy so far: https://github.com/Atinux/discuss/blob/main/components/Messages.vue#L13-L35

**Comment by Atinux** [comment]
Would be nice also if there is a way to parse the data automatically here: https://github.com/vueuse/vueuse/blob/main/packages/core/useEventSource/index.ts#L57

Using [destr](https://github.com/unjs/destr) would be best
