### ISSUE TITLE
Maybe vueuse's issue when compiling with Vue 3.2.10+

### ISSUE THREAD

**Issue by feenn** [vueuse/vueuse#750]
In vue 3.2.10+, vue-compat is built in default exports mode instead of named mode. As a result, there are complie errors such as "in ./node_modules/@vueuse/core/index.mjs: Can't import the named export 'bypassFilter/tryOnUnmounted/unref/etc..' from non EcmaScript module (only default export is available)".
I'm not sure this is vueuse's issue cause my project depends on a lot of package except vueuse. After upgrading vue from 3.2.9 to 3.2.10+, these errors occurred. When I checked yarn.lock, I found that element-plus depends on @vueuse/core@6.2.0. So I try to post this issue here to look for further help. Wishes~

**Comment by antfu** [comment]
#718
