### ISSUE TITLE
feat: watchAtMost

### ISSUE THREAD

**Issue by webfansplz** [vueuse/vueuse#762]
i have an idea :
```ts

const watchAtMost = (source, fn, options = { max = 1 }) => {
  const { max } = options
  const count = ref(0)
  const stop = watch(source, (...args) => {
    fn(...args)
    count.value >= max && stop()
    count.value++
  }, options)
  return { count , stop }
}
```

**Comment by harmyderoman** [comment]
why does the function not return `{ count, stop }`?

**Comment by webfansplz** [comment]
> why does the function not return `{ count, stop }`?

good idea ～

**Comment by harmyderoman** [comment]
Also, count in return must be readonly, so you can't change it outside the function.

**Comment by webfansplz** [comment]
> Also, the `count` in return must be read-only, so you will not be able to change it outside the function.

Thanks for your suggest.

**Comment by harmyderoman** [comment]
You are wellcome!

**Comment by harmyderoman** [comment]
A good idea, but I think antfu will say that it is better to write a count filter so that it can then be applied to a whole family of functions.

**Comment by webfansplz** [comment]
> A good idea, but I think antfu will say that it is better to write a count filter so that it can then be applied to a whole family of functions.

nice suggest ! I will do so if this idea is approved.

**Comment by webfansplz** [comment]
PR has merged
