### ISSUE TITLE
feature: useFocusElement

### ISSUE THREAD

**Issue by gregveres** [vueuse/vueuse#763]
I found that focusTrap isn't really what I wanted, so I put together a useFocusElement that is passed a ref to an element and returns a Ref<boolean> that indicates if the element has focus or not and can be set true to give focus to the element. 

Is this something that could become part of vueuse? 

Here is the code I have. I think if I put together a PR, I would change the target argument to a MaybeElementRef like useFocusTrap. 

When setting up the onBlur and onFocus event handlers, I first search the given element for some sort of input field because I am using a UI library that ends up wrapping the input fields in layers of divs. 

```JS
import { ref, Ref, watch } from '@vue/composition-api';

export interface UseFocusElementReturn {
  focus: Ref<boolean>;
}

export function useFocusElement(target: Ref<any>): UseFocusElementReturn {
  const focus = ref(false);
  let input: undefined | HTMLElement;

  const focusTrue = () => {
    focus.value = true;
  };
  const focusFalse = () => {
    focus.value = false;
  };
  if ('value' in target) {
    // watch for changes in the target
    watch(
      () => target.value,
      (newTarget) => {
        if (input) {
          input.removeEventListener('blur', focusFalse);
          input.removeEventListener('focus', focusTrue);
        }
        if (newTarget && newTarget.$el) {
          input = newTarget.$el.querySelector('input, select, textarea');
          if (input) {
            input.addEventListener('blur', focusFalse);
            input.addEventListener('focus', focusTrue);
          }
        }
      },
      { immediate: true }
    );
    // watch for someone setting focus to true in order to focus the element
    watch(
      () => focus.value,
      (newValue, oldValue) => {
        if (newValue && !oldValue && input) {
          input.focus();
        }
      }
    );
  }
  return { focus };
}
```

**Comment by FRSgit** [comment]
Hey @gregveres!

Just so you know - I'm not either author nor maintaner of vueuse. But I also was looking for a similar thing regarding focus/blur handling.

I gave your code some thought and I've reworked it as bit, have a look:

```ts
import { MaybeElementRef, unrefElement, useEventListener } from '@vueuse/core';
import type { MaybeRef } from '@vueuse/shared';
import { computed, ref, unref, watch } from 'vue-demi';

export const useFocused = (
  { target, initialValue = false }:
  { target?: MaybeElementRef, initialValue?: MaybeRef<boolean> },
) => {
  const element = computed(() => unrefElement(target) ?? window.document.body);
  const focused = ref(unref(initialValue));

  const onFocus = () => { focused.value = true; };
  const onBlur = () => { focused.value = false; };

  const cleanupFocus = useEventListener(element, 'focus', onFocus, { passive: true });
  const cleanupBlur = useEventListener(element, 'blur', onBlur, { passive: true });

  const stopWatch = watch(focused, (focused, oldFocused) => {
    if (focused) {
      if (!oldFocused) element.value.focus();
    } else {
      if (!focused) element.value.blur();
    }
  }, { immediate: true, flush: 'post' });

  return {
    focused,
    cleanup() {
      stopWatch();
      cleanupFocus();
      cleanupBlur();
    },
  };
};
```

To simplify, I've used some of the shared vueuse methods. Also, I've added `blur` handling and possibility to cleanup all of the event handlers and a watcher (I needed that when used this composable in a directive scope where, unfortunately, there is no onUnmounted hook available :<). And lastly - now the function is accepting `initialValue` for the `focused` ref and the watcher runs immediately using [`flush: 'post'` option](https://v3.vuejs.org/guide/reactivity-computed-watchers.html#effect-flush-timing) (to make sure it's being run always after the component updates).

Please write what do you think about that - IMO this implementation is a bit closer to what is already within vueuse codebase.

**Comment by gregveres** [comment]
HI @FRSgit 

Nice. First, I wasn't sure there would be others who wanted this functionality as well.  I would like to hear your use cases. Mostly because of your comment that the watcher might not "fit" with the vueuse approach. For me, my entire use case centres on the need for the watcher. To create a top notch UI experience for my users, I need to programmatically set focus on certain put fields at the appropriate times. To do that, I need the watcher so that my code can just set focused.value = true and I know that the input now has focus.

You mentioned using it in a directive. What does the directive do?

I didn't add the blur handling because I have never needed to remove focus from an element, but it might as well be there for consistency. 

I think the initialValue is a good addition. I was going to convert to using things like MaybeElementRef if the maintainers said they wanted to add it. But I didn't know about the useEventListener. That makes things much easier than having to use a watch on the target. 

And finally, I think that splitting out the input search is good for a library, I don't have a use case (yet) for focusing anything other than an input, but I could see a use case for wanting to focus a button or something similar. 

On a style note, I am not a big fan of the way you did the parameters for the use function, but I see that some of the vueuse functions do that. It just isn't consistent though. 

overall, nice improvements.

**Comment by FRSgit** [comment]
My use case is an implementation of a tooltip directive. The directive might be attached to buttons, inputs, anything with `tabindex=""` (or it will add a tabindex by itself). Tooltip should be shown not only on hover, but also on focus, so it's accessible for keyboard users as well.

And well, in directive I cannot use things like `@focus` on a DOM element, so I need some other way of attaching events - such as this composable function.

Okay, you make a valid argument about the watcher. IMO it could be added here, but I'm not sure how that fits with general architecture of the `vueuse`. For the first implementation it should be fine I guess.

Regarding the parameters - yes, I see that many `vueuse` methods have differences in that regard. In the PR I would probably write an interface like it's done [here](https://github.com/vueuse/vueuse/blob/main/packages/core/useMousePressed/index.ts#L7-L33) - I just didn't want to make the example longer. My comment was already long enough 😄

**Comment by FRSgit** [comment]
Okey, I've just reminded myself about the EffectScope API. So instead of returning cleanup method I would just rely on `tryOnScopeDispose` used in `useEventListener` and `watch` to clean up itself. Also, I've reworked the example so it's similar to the `useMousePressed` composable (the main point being possibility to test it in `window`-lacking environments). See the example:

```ts
import { computed, ref, unref, watch } from 'vue-demi';
import { MaybeElementRef, unrefElement } from '../unrefElement'
import { useEventListener } from '../useEventListener'
import { ConfigurableWindow, defaultWindow } from '../_configurable'

export interface MousePressedOptions extends ConfigurableWindow {
  /**
   * Initial values
   *
   * @default false
   */
  initialValue?: boolean

  /**
   * Element target to be capture the focus/blur events
   */
  target?: MaybeElementRef
}

/**
 * Reactive element focus boolean.
 *
 * @see https://vueuse.org/useFocused
 * @param options
 */
export function useFocused(options: MousePressedOptions = {}) {
  const {
    initialValue = false,
    window = defaultWindow,
  } = options

  const focused = ref(initialValue)

  if (!window) {
    return { focused };
  }

  const onFocus = () => { focused.value = true; };
  const onBlur = () => { focused.value = false; };

  const target = computed(() => unrefElement(options.target) ?? window);

  useEventListener(target, 'focus', onFocus, { passive: true });
  useEventListener(target, 'blur', onBlur, { passive: true });

  watch(focused, (focused, oldFocused) => {
    if (focused) {
      if (!oldFocused) target.value?.focus();
    } else {
      if (!focused) target.value?.blur();
    }
  }, { immediate: true, flush: 'post' });

  return { focused };
}

```

**Comment by gregveres** [comment]
This looks good. I think the watch should be this though:

```JS
  watch(focused, (focused, oldFocused) => {
    if (focused) {
      if (!oldFocused) target.value?.focus();
    } else {
      if (oldFocused) target.value?.blur();
    }
  }, { immediate: true, flush: 'post' });
```

in the else clause you were checking !focused, which was already tested as true by the outer if statement.

**Comment by FRSgit** [comment]
@gregveres Yea, that's exactly what I had in mind, thanks! 🤝 
I'll file a PR with this one and link the issue. Let's see if `vueuse` team seems that as a valuable addition or not

**Comment by gregveres** [comment]
Hi @FRSgit 

I have started to create a PR for this, with the hopes that the maintainers will accept it. In setting up the demo, I have discovered that your code doesn't handle the initial value properly. The issue is that you lost my original code of setting up the watch on the target. The watch on the target was necessary to setup the event listeners, which you properly moved into useEventListner, but I also did the watch on the target because when you use the ref="" directive in vue, target is originally undefined. Then after the component renders, the ref is filled in. At this point is when we have a chance to focus or blur based on the initial value. 

Here is the code I am going to submit in the PR:

```JS
import { computed, Ref, ref, watch } from 'vue-demi'
import { MaybeElementRef, unrefElement } from '../unrefElement'
import { useEventListener } from '../useEventListener'
import { ConfigurableWindow, defaultWindow } from '../_configurable'

export interface FocusOptions extends ConfigurableWindow {
  /**
   * Initial value. If set true, then focus will be set on the target
   *
   * @default false
   */
  initialValue?: boolean

  /**
   * The target element for the focus and blur events.
   */
  target?: MaybeElementRef
}

/**
 * Reactive element focus boolean.
 *
 * @see https://vueuse.org/useFocus
 * @param options
 */
export function useFocus(options: FocusOptions = {}): Ref<boolean> {
  const {
    initialValue = false,
    window = defaultWindow,
  } = options

  const focused = ref(initialValue)

  if (!window)
    return focused

  const onFocus = () => { focused.value = true }
  const onBlur = () => { focused.value = false }

  const target = computed(() => unrefElement(options.target) ?? window)

  useEventListener(target, 'focus', onFocus, { passive: true })
  useEventListener(target, 'blur', onBlur, { passive: true })

  const setFocus = (focused: boolean, oldFocused: boolean) => {
    console.log(`in watch: ${focused}, ${oldFocused}`)
    if (focused) {
      if (oldFocused !== true) {
        target.value?.focus()
        if (target.value)
          console.log('focus called')
      }
    }
    else {
      if (oldFocused === true) target.value?.blur()
    }
  }
  watch(focused, setFocus, { immediate: true, flush: 'post' })
  watch(target, () => {
    setFocus(focused.value, false)
  }, { immediate: true, flush: 'post' })

  return focused
}
```

**Comment by gregveres** [comment]
Ah, I see we both replied at the same time. :)
I pretty much have the PR code ready to go.

Here is the demo that I was going to submit with the PR:
```JS
<script setup lang="ts">
import { ref } from 'vue-demi'
import { useFocus } from '.'

const text = ref()
const input = ref()
const button = ref()

const textFocus = useFocus({ target: text })
const inputFocus = useFocus({ target: input, initialValue: true })
const buttonFocus = useFocus({ target: button })

const setTextFocus = () => { textFocus.value = true }
const setInputFocus = () => { inputFocus.value = true }
const setButtonFocus = () => { buttonFocus.value = true }
const unsetTextFocus = () => { textFocus.value = false }
const unsetInputFocus = () => { inputFocus.value = false }
const unsetButtonFocus = () => { buttonFocus.value = false }
</script>

<template>
  <div>
    <p ref="text" :class="{'bg-green-200': textFocus}">
      Some text that can be focused
    </p>
    <input ref="input" class="item" />
    <button ref="button" class="item">
      button
    </button>
    <hr />
    <p v-if="textFocus">
      The text has focus
    </p>
    <p v-if="inputFocus">
      The input control has focus
    </p>
    <p v-if="buttonFocus">
      The button has focus
    </p>
    <div>
      <button @click="setTextFocus">
        focus text
      </button>
      <button @click="setInputFocus">
        focus input
      </button>
      <button @click="setButtonFocus">
        focus button
      </button>
    </div>
    <div>
      <button @click="unsetTextFocus">
        unfocus text
      </button>
      <button @click="unsetInputFocus">
        unfocus input
      </button>
      <button @click="unsetButtonFocus">
        unfocus button
      </button>
    </div>
  </div>
</template>

<style scoped>
.item:focus, bg {
  background-color: cadetblue;
}
</style>

```

**Comment by gregveres** [comment]
You will notice two significant differences from what you had put together:

1. the name: I am suggesting useFocus, not useFocused. The reason is because I am coming at it from the control point of view, where you are coming at it from the status point of view. I think it makes more sense that the control point of view also has a status component. But it seems strange that the status point of view has a control mechanism.
2. I am returning the ref directly and not wrapping it into an object. When I went to use the object in a component that had multiple useFocus() calls, I found it more awkward to use the object. It was much easier to have the useFocus return the ref directly so that I could easily assign it to whatever variable name I wanted.

**Comment by gregveres** [comment]
Ugg, I am on windows without WSL so contributing seems more difficult because a couple hundred files changed. Here is the .md file I would have submitted.

```md
---
category: Browser
---

# useFocus

Utility to track or set the focus state of a DOM element.

## Usage

```ts
import { useFocus } from '@vueuse/core'

const text = ref();
const textFocused = useFocus({ target: text })
```

```

**Comment by FRSgit** [comment]
Uf, good that I've commented here before doing any actual work then!

Okey, I think that part was missing form the original piece of code and I didn't think of that! It's a cool addition. I'm not sure if we couldn't make it a single watcher though, but maybe that'd be already too much pre-optimisation.

1. I get it, IMO it's a good explanation. I think it fits with the overall naming convention in the library.
2. This one I'm not sure - generally I prefer objects because they're more flexible when it comes to the possibility of returning additional APIs from the composable in the future. `const { focused: focusedInput } = useFocus(/* ... */);` for me looks pretty good.

Okay, can you commit the most important things you've got to the new branch in your fork repository and invite me to it with write privilege please? I'm on Mac, so maybe it'll be easier for me to rebuild everything and commit.

**Comment by gregveres** [comment]
I have created the fork, checked in the code and invited you as a contributor

**Comment by gregveres** [comment]
and I changed the return back to being an object. 
I made sure the line endings were LF only.

**Comment by FRSgit** [comment]
@gregveres
Sorry I got carried away with other things and could handle it only now.

I've splitted your work into two branches - one for `useFocus` and second one for `useFocusInputElement`. I've finished up work, added tests and opened up PR for `useFocus` (#818).

Regarding `useFocusInputElement` - I think this one might be too narrow for the vueuse library itself. Not sure, but I propose to go in a bit different direction. My idea is to create `useQuerySelector` composable which would look for a child element and return it as a reactive value. The proposed solution would then look like this:

```ts
import { useQuerySelector, useFocus } from '@vueuse/core';

const target = ref<HTMLElement | undefined>();
const control = useQuerySelector('input,textarea,select', { target });
const { focused } = useFocused({ target: control });
```

I think that could be a way to go - `useQuerySelector` should be flexible enough to open up the door for other use cases.
I can already think of an extensible API for it - e.g. toggleable configuration option for tracking of DOM changes with mutation observers. Or possibility to define default value (when no element is found).

I'll probably open up a separate issue for it to track the idea.

**Comment by FRSgit** [comment]
Hey! Just to do an update on this one - [useFocus PR](https://github.com/vueuse/vueuse/pull/818) just got merged!

Now the question about `useQuerySelector` composable. Imo it could be an useful util for handling cases like this - you get a child input element as a ref and pass it to `useFocus` - voila, you have your input focused (as visible on the code example in my message right above).

What do you think @gregveres, @antfu - any comments on this one? If it's all good I can give it a try with an actual implementation
