### ISSUE TITLE
usePermission() 不支持 Safari 

### ISSUE THREAD

**Issue by ShineKidd** [vueuse/vueuse#782]
使用的你 safari 浏览器打开 👉https://vueuse.org/core/usePermission/

并没有获取到权限信息

**Comment by webfansplz** [comment]
[Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API) 暂未支持`Safari`, 也许你可以`isSupported`来判断支持情况做相应的处理.

**Comment by danrocha** [comment]
If anyone lands here and can't read Chinese:

> The [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API) does not support Safari yet, maybe you can use `isSupported` to judge the support and deal with it accordingly.
