### ISSUE TITLE
与composition-api冲突

### ISSUE THREAD

**Issue by kailong321200875** [vueuse/vueuse#784]
"@vue/composition-api": "^1.2.1",
"@vueuse/core": "^6.4.1",

![image](https://user-images.githubusercontent.com/32283845/134449028-636f6eb0-d08d-48d8-b94e-ceac67d437d6.png)

当使用了vueuse中的某个方法，如useTitle，就会报如上的错误

**Comment by yanzhangshuai** [comment]
请问这个问题解决了吗，我也出现了这个错误
