### ISSUE TITLE
不兼容IE

### ISSUE THREAD

**Issue by kailong321200875** [vueuse/vueuse#785]
"@vue/composition-api": "^1.2.1",
"@vueuse/core": "^6.4.1",
"vue": "^2.6.14",
"vue-demi": "^0.11.4"

使用了vueuse中的方法，在IE浏览器上会报错，不使用的话，是可以正常运行的

![image](https://user-images.githubusercontent.com/32283845/134473274-3065c32b-6d7d-4fa6-9fa2-a3a1aa1f2176.png)

![image](https://user-images.githubusercontent.com/32283845/134473175-7989bdea-a45d-46e6-814e-47bdc6ebf594.png)

**Comment by antfu** [comment]
Can't see anything particular from the screenshot.

**Comment by kailong321200875** [comment]
> Can't see anything particular from the screenshot. Please provide more info

IE浏览器给的信息就这么多了。。现在只能定位到使用了vueuse，就会这样。。

**Comment by kailong321200875** [comment]
@antfu https://github.com/vueuse/vueuse-vue2-example官方的在线demo也是没有办法在IE上运行的。

**Comment by icepole-jon** [comment]
I also encountered a browser compatibility problem, which was initially confirmed to be an `async` syntax problem.
chrome v53
vue@3.2.14
@vueuse/core@6.4.1
I add `@vueuse/core` and `@vueuse/shared` to `vue.config.js` config `transpileDependencies`
but babel not trans it to `yield`
```js
module.exports = {
  transpileDependencies: [
    // "@purge-icons/generated",
    "@vueuse/core",
    "@vueuse/shared",
    "vue-request",
  ]
}
```
![](https://files.catbox.moe/dk27ih.png)
![](https://files.catbox.moe/8oelcw.png)

**Comment by antfu** [comment]
So I guess that's the problem of your local babel config then?

**Comment by icepole-jon** [comment]
@antfu 确实是配置问题
我把vue-cli升级到v5 设置转换所有依赖就行了
```js
// vue.config.js
module.exports = {
  configureWebpack: {
  // no-need
   /* module: {
      rules: [
        {
          test: /\.mjs?$/,
          include: /node_modules/,
          type: "javascript/auto",
        },
        {
          test: /\.cjs?$/,
          include: /node_modules/,
          type: "javascript/auto",
        },
      ],
  },*/
  transpileDependencies: true // 转换所有依赖
}
```

```
// .browserslistrc
chrome >= 50
ie >= 10
```
@kailong321200875 可以试一下

**Comment by lsdsjy** [comment]
I think it's a problem with `.mjs` & `.cjs` files in vue-cli & webpack 4.

Webpack 4 resolves `import` statements in `.mjs` files differently, ignoring the imported package's 'module' field (https://github.com/webpack/webpack.js.org/issues/4482#issuecomment-374980347). Now, `@vueuse/core/index.mjs` imports `@vueuse/shared`, which resolves to `@vueuse/shared/index.cjs` unexpectedly. And vue-cli-plugin-babel doesn't  transpile `.cjs` files by default (https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-babel/index.js#L38). Thus some code from @vueuse/shared appears un-transpiled in the final output.

**Comment by coderBabao** [comment]
> @antfu 确实是配置问题 我把vue-cli升级到v5 设置转换所有依赖就行了
> 
> ```js
> // vue.config.js
> module.exports = {
>   configureWebpack: {
>    // no-need
>    /* module: {
>         rules: [
>           {
>             test: /\.mjs?$/,
>             include: /node_modules/,
>             type: "javascript/auto",
>           },
>           {
>             test: /\.cjs?$/,
>             include: /node_modules/,
>             type: "javascript/auto",
>           },
>         ],
>     }, */
>   },
>   transpileDependencies: true // 转换所有依赖
> }
> 
> // babel.config.js
> module.exports = {
>   presets: ["@vue/cli-plugin-babel/preset"]
> };
> ```
> 
> ```
> // .browserslistrc
> chrome >= 50
> ie >= 10
> ```
> 
> @kailong321200875 可以试一下

@icepole-jon 我项目的Vue CLI是5.0.8版本，但是会报错transpileDependencies必须是数组
![企业微信截图_20241010110129](https://github.com/user-attachments/assets/4e54f34b-c8c9-4b0b-a3fb-0cf0c1bfac6a)
