### ISSUE TITLE
docs: useWebWorker, import path is incorrect

### ISSUE THREAD

**Issue by phaust** [vueuse/vueuse#795]
Currently: `import { useWebWorker } from 'vue-use-web'`
Should be: `import { useWebWorker } from '@vueuse/core'`

**Comment by phaust** [comment]
I already fixed it and would like to open PR.

**Comment by wheatjs** [comment]
I noticed this the other day as well, feel free to open a PR 😄

**Comment by phaust** [comment]
I struggle pushing my branch to the repo. I'm getting 'Access denied' failures. Need to check this.

**Comment by wheatjs** [comment]
You will need to fork the repo and create a PR back to this repo

**Comment by phaust** [comment]
OK, thx. Never contributed to an open source public repo before. Will try :)

**Comment by phaust** [comment]
Alright, thx for the hint with the fork. PR created.
