### ISSUE TITLE
Cannot find name 'value' in @vueuse/shared/index.d.ts

### ISSUE THREAD

**Issue by dragomirweb** [vueuse/vueuse#802]
Does anyone have any ideea why i'm getting this error:
using: 
"@vue/composition-api": "1.2.2",
"@vueuse/core": "^6.5.3",
"@vueuse/rxjs": "^6.5.3",
 "vue": "^2.6.10",
 "typescript": "4.2.4",
 "@vue/cli-plugin-typescript": "^3.7.0",
 
 `ERROR in /home/daniel/Desktop/Workspace/EstateClient/node_modules/@vueuse/shared/index.d.ts
35:9 Cannot find name 'value'.
    33 |  */
    34 | declare type RemoveableRef<T> = Omit<Ref<T>, 'value'> & {
  > 35 |     get value(): T;
       |         ^
    36 |     set value(value: T | null | undefined);
    37 | };
    38 | /**
ERROR in /home/daniel/Desktop/Workspace/EstateClient/node_modules/@vueuse/shared/index.d.ts
35:18 Cannot find name 'T'.
    33 |  */
    34 | declare type RemoveableRef<T> = Omit<Ref<T>, 'value'> & {
  > 35 |     get value(): T;
       |                  ^
    36 |     set value(value: T | null | undefined);
    37 | };
    38 | /**
ERROR in /home/daniel/Desktop/Workspace/EstateClient/node_modules/@vueuse/shared/index.d.ts
36:9 Cannot find name 'value'.
    34 | declare type RemoveableRef<T> = Omit<Ref<T>, 'value'> & {
    35 |     get value(): T;
  > 36 |     set value(value: T | null | undefined);
       |         ^
    37 | };
    38 | /**
    39 |  * Make all the nested attributes of an object or array to MaybeRef<T>
ERROR in /home/daniel/Desktop/Workspace/EstateClient/node_modules/@vueuse/shared/index.d.ts
36:15 Cannot find name 'value'.
    34 | declare type RemoveableRef<T> = Omit<Ref<T>, 'value'> & {
    35 |     get value(): T;
  > 36 |     set value(value: T | null | undefined);
       |               ^
    37 | };
    38 | /**
    39 |  * Make all the nested attributes of an object or array to MaybeRef<T>
ERROR in /home/daniel/Desktop/Workspace/EstateClient/node_modules/@vueuse/shared/index.d.ts
36:22 Cannot find name 'T'.
    34 | declare type RemoveableRef<T> = Omit<Ref<T>, 'value'> & {
    35 |     get value(): T;
  > 36 |     set value(value: T | null | undefined);
       |                      ^
    37 | };
    38 | /**
    39 |  * Make all the nested attributes of an object or array to MaybeRef<T>
ERROR in /home/daniel/Desktop/Workspace/EstateClient/node_modules/@vueuse/shared/index.d.ts
36:26 Object is possibly 'null'.
    34 | declare type RemoveableRef<T> = Omit<Ref<T>, 'value'> & {
    35 |     get value(): T;
  > 36 |     set value(value: T | null | undefined);
       |                          ^
    37 | };
    38 | /**
    39 |  * Make all the nested attributes of an object or array to MaybeRef<T>
ERROR in /home/daniel/Desktop/Workspace/EstateClient/node_modules/@vueuse/shared/index.d.ts
36:33 Object is possibly 'undefined'.
    34 | declare type RemoveableRef<T> = Omit<Ref<T>, 'value'> & {
    35 |     get value(): T;
  > 36 |     set value(value: T | null | undefined);
       |                                 ^
    37 | };
    38 | /**
    39 |  * Make all the nested attributes of an object or array to MaybeRef<T>
`

**Comment by antfu** [comment]
Upgrade to TS 4.4

**Comment by dragomirweb** [comment]
> Upgrade to TS 4.4

I will try that and come back with an update, Thanks @antfu

**Comment by dragomirweb** [comment]
> Upgrade to TS 4.4

solved, thanks
