### ISSUE TITLE
feat: `defined` utility function (user-defined type guard)

### ISSUE THREAD

**Issue by glen-84** [vueuse/vueuse#803]
I needed to check that a ref's `value` is defined (not `undefined` or `null`), so I wrote this [UDTG](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards):

```ts
function defined<T>(ref: Ref<T>): ref is Ref<Exclude<T, null | undefined>> {
    return ref.value !== null && ref.value !== undefined;
}
```

Usage:

```ts
const example = ref(Math.random() ? "example" : undefined); // Ref<string | undefined>

if (defined(example)) {
    example; // Ref<string>
}
```

I couldn't find something like this in vueuse, would it be useful to others?

(open to suggestions regarding the name)

**Comment by DarrylNoakes** [comment]
Re naming: how about `isdef`, like the C and C++ preprocessor macro?
Just because I come from a C++ background ;).

While you're at this, why not make it accept normal variables as well as refs?
Probably using `MaybeRef` or something like that.

**Comment by antfu** [comment]
I would feel `if (unref(example) == null)` is more straightforward

**Comment by glen-84** [comment]
@DarrylNoakes
> While you're at this, why not make it accept normal variables as well as refs?
> Probably using `MaybeRef` or something like that.
> That functionality would make it a handy all-rounder.

We can consider this if the general idea is accepted.

@antfu
> I would feel `if (unref(example) != null)` is more straightforward

This won't narrow the type ...

```ts
const example = ref(Math.random() ? "example" : undefined); // Ref<string | undefined>

if (unref(example) != null) {
    example; // Ref<string | undefined>
    example.value; // string | undefined
}
```

**Comment by antfu** [comment]
Ok let's do this

```ts
export function isDefined<T>(v: Ref<T>): v is Ref<Exclude<T, null | undefined>>
export function isDefined<T>(v: ComputedRef<T>): v is ComputedRef<Exclude<T, null | undefined>>
export function isDefined<T>(v: T): v is Exclude<T, null | undefined>
export function isDefined<T>(v: Ref<T>): boolean {
    return unref(v) != null;
}
```

**Comment by glen-84** [comment]
@antfu Should this go in `core` or `shared`?
