### ISSUE TITLE
Bug: useStorage

### ISSUE THREAD

**Issue by jlzm** [vueuse/vueuse#808]
## useStorage bug(maybe?)
- open opening a new window will loop indefinitely.
- Crazy jitter!!! and 
- I think there are two instances created, but both are responsive, and both are constantly responding.
I can't send a gif
please try this=>

![image](https://user-images.githubusercontent.com/31950551/135245039-fea6decf-e91e-4950-b5af-4c2822e2a098.png)

**Comment by harmyderoman** [comment]
This is not a bug, this is how it is supposed to work. Because it is reactive local storage and all browser tabs share the same storage.

**Comment by antfu** [comment]
Yes, the reactiveness is expected but indeed there are some issues with the dedupe check that causes the infinitely tracing loop.

**Comment by holtwick** [comment]
+1 I experience the same issue. Frequent changes of the same value seem to cause race conditions.

**Comment by jlzm** [comment]
reducing the frequency reduces the chance of triggering the loop, but it's not stable.

**Comment by jlzm** [comment]
This problem still exists.
