### ISSUE TITLE
Bug: Error in data(): "TypeError: vueDemi.getCurrentScope is not a function"

### ISSUE THREAD

**Issue by Jay214** [vueuse/vueuse#809]
![image](https://user-images.githubusercontent.com/22128373/135257147-cc2aedd7-b4c6-417e-ab78-f192db682354.png)
 
I don't know why this is happening.

I use vueuse in vue2.6.11 with vue-composition-api

**Comment by Jay214** [comment]
![image](https://user-images.githubusercontent.com/22128373/135260139-5c2709ba-ee7c-44ff-ad71-ea1facfd1941.png)
The vue-composition-api version must be ^1.0.0-rc.1 ？

**Comment by antfu** [comment]
v6.0 requires `@vue/composition-api` v1.1
