### ISSUE TITLE
v6.0 requires `@vue/composition-api` v1.1

### ISSUE THREAD

**Issue by Jay214** [vueuse/vueuse#810]
v6.0 requires `@vue/composition-api` v1.1

_Originally posted by @antfu in https://github.com/vueuse/vueuse/issues/809#issuecomment-930490856_

**Comment by Jay214** [comment]
I try v1.1 and v1.22, but it still error

**Comment by antfu** [comment]
Make sure you have only one version of `vue-demi` and `@vue/composition-api` installed. Otherwise, please provide a minimal reproduction.

**Comment by Jay214** [comment]
> Make sure you have only one version of `vue-demi` and `@vue/composition-api` installed. Otherwise, please provide a minimal reproduction.

Thank you, big brother, according to the way you said, I solved
