### ISSUE TITLE
bug: `useFocusTrap` doesn't work on `v-if` node

### ISSUE THREAD

**Issue by harmyderoman** [vueuse/vueuse#816]
Maybe this is not a bug, but it significantly limits the usage of the function. It is not possible to bind the function to a modal that has not yet appeared, because `v-if` is set to `false`.
Interestingly, after the second call to the modal, the focus trap is triggered, but this cannot be deactivated.

**Comment by wheatjs** [comment]
Hmm, this might be able to be fixed, but perhaps until it is something like v-show would be a good alternative. PR welcome if you want to try to fix it

**Comment by harmyderoman** [comment]
`v-show` may be a solution. Also, I was thinking about component `<use-focus-trap />` that activates the trap on mounting and deactivate on unmounting.

**Comment by harmyderoman** [comment]
@wheatjs I wrote the `UseFocusTrap` component but can't create a pull because my previous one hasn't been accepted yet.

**Comment by harmyderoman** [comment]
https://github.com/vueuse/vueuse/pull/820
