### ISSUE TITLE
could not resolve vue-demi (Nuxt 3 deployment on netlify)

### ISSUE THREAD

**Issue by Joaojack** [vueuse/vueuse#847]
Hi team, 
got this error when trying to deploying (for testing) a Nuxt 3 app with vue-use
`4:25:43 PM:  > .netlify/functions-internal/server/node_modules/@vueuse/shared/index.mjs:636:14: error: Could not resolve "vue-demi" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
4:25:43 PM:     636 │       require("vue-demi").set(...args);
4:25:43 PM:         ╵               ~~~~~~~~~~
4:25:43 PM:    .netlify/functions-internal/server/node_modules/vue-demi/package.json:18:17: note: The module "./lib/index.cjs" was not found on the file system
4:25:43 PM:      18 │       "require": "./lib/index.cjs",
4:25:43 PM:         ╵                  ~~~~~~~~~~~~~~~~~
4:25:43 PM: `

**Comment by Joaojack** [comment]
of course, sorry i'm still a beginner. Here is my repo : https://github.com/Joaojack/Nuxt3-x-tailwindcss-app-example

**Comment by antfu** [comment]
I guess this is because Netlify functions do not run the `postinstall` hook that `vue-demi` relies on. Need some help if anyone knows better of how to fix this.
