### ISSUE TITLE
useSessionStorage在IE11下部分情况卡死

### ISSUE THREAD

**Issue by ailtariel** [vueuse/vueuse#848]
1:
useSessionStorage使用object在IE11会卡死；
ff/chrome正常
useStorage正常

2：
useSessionStorage初始化后马上修改值在IE11会卡死；
ff/chrome正常
useStorage正常

环境：
@vueuse/core 5.3.0
@vueuse/shared 5.3.0
vue 2.6.11
@vue/composition-api: 1.0.2
--------------------
问题太诡异，测试变量太多，并且测试”浏览器卡死“是件非常折磨的事情（反复测了一天）。所以可能测试结果不完全精确，勿怪。

**Comment by antfu** [comment]
Feel free to drop a PR if you find the fix. Don't have IE and can't test myself.
