### ISSUE TITLE
Document: [useElementVisibility] Target Element is misleading, or wrong target

### ISSUE THREAD

**Issue by hikariNTU** [vueuse/vueuse#852]
As title, the ref is actually binding on the whole demo block instead of the dashed-outline block:

![image](https://user-images.githubusercontent.com/18393696/137684835-575dbb4a-f9a8-4eec-a334-112647c2ba96.png)

Which is quite confusing without looking at the demo source code.

[Source](https://github.com/vueuse/vueuse/blob/d9f4d10e97655ad1e142f442ada1d88b8cfa9c48/packages/core/useElementVisibility/demo.vue):
```html
<div ref="el" style="height: 200px">
  <note class="mb-2">
    Info on the right bottom corner
  </note>
  <div class="area">
    Target Element (scroll down)
  </div>
</div>
```

Should be:
```html
<div style="height: 200px">
  <note class="mb-2">
    Info on the right bottom corner
  </note>
  <div ref="el" class="area">
    Target Element (scroll down)
  </div>
</div>
```

**Comment by antfu** [comment]
Yeah, that seems to be a mistake. PR welcome, thanks!
