### ISSUE TITLE
useMagicKeys example doesn't compile with Typescript

### ISSUE THREAD

**Issue by CapitaineToinon** [vueuse/vueuse#862]
[The documentation](https://vueuse.org/core/usemagickeys) shows a usage of useMagicKeys like this:

```js
const { shift, space, a /* keys you want to monitor */ } = useMagicKeys()

watch(space, (v) => {
  if (v)
    console.log('space has been pressed')
})
```

But this doesn't compile in Typescript because keys returned have a type of `ComputedRef<boolean> | undefined` and `watch` has no signature to watch an undefined value directly. I had to change my code to this, which I believe should be documented.

```js
const { shift, space, a /* keys you want to monitor */ } = useMagicKeys()

watch(() => space?.value, (v) => {
  if (v)
    console.log('space has been pressed')
})
```

**Comment by webfansplz** [comment]
In 7.6.2, I couldn't reproduce it.

Please tell me reopen issue if you still facing this problem.

**Comment by CapitaineToinon** [comment]
[I've made a reproduction in codepen using vue 3 + @vueuse v7.6.2](https://codepen.io/CapitaineToinon/pen/KKyXGpW?editors=1000) and the problem is still here.

I'm on macos 12.2 and tried
* Chrome 98.0.4758.80
* Firefox 97.0
* Safari 15.3.
