### ISSUE TITLE
Have a question about UseStorage/UseSessionStorage

### ISSUE THREAD

**Issue by loksoon** [vueuse/vueuse#863]
index.vue
![Screenshot 2021-10-21 at 16 13 03](https://user-images.githubusercontent.com/43371272/138239814-799bfc62-3637-48a1-b51b-cc97872bcc47.png)
![Screenshot 2021-10-21 at 16 12 43](https://user-images.githubusercontent.com/43371272/138239839-5916298a-750f-4f85-941f-4815f3940bc3.png)

state.js
![Screenshot 2021-10-21 at 16 13 27](https://user-images.githubusercontent.com/43371272/138239892-1d1ea4dc-6d84-42c7-afd5-db97d16896bf.png)

In Localhost
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43371272/138241426-15731649-8a77-43c9-af22-c5bcfd253a41.gif)

In Live Server Domain
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/43371272/138242411-bd0cc535-d33d-4d04-a404-06297346547b.gif)

I have using sidebarPanelState(useSessionStorage) to change then value,in localhost anything is okay can change it,but after production in a live server domain,that session storage is not working

**Comment by loksoon** [comment]
Em or i need to do some setup in live server?

**Comment by wheatjs** [comment]
Can you please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) of the issue. We will close this until then, thanks 😄
