### ISSUE TITLE
Assigning a ref to a reactive property - with type safety

### ISSUE THREAD

**Issue by joakimriedel** [vueuse/vueuse#866]
Vue 3 supports assigning a ref to a reactive property, which has the bonus of creating a "live link" between them. 

However, [the documentation does not tell how to do that in a type safe manner](https://v3.vuejs.org/api/basic-reactivity.html#reactive).

Tried searching for different solutions, but couldn't find any good candidates. Also looked in this repository under `utils` but did not find any.

Could the below code be a candidate for a util, or does anyone know a better solution to this? 

```ts
const obj = reactive({ count: 0 });
const count = ref(0);

// Type 'Ref<number>' is not assignable to type 'number'.(2322)
obj.count = count;

const safeLinkRef = 
  <RT,R extends Ref<RT>>(source: R, target: R) => {
    target.value = source as unknown as RT;
  }

// this works
safeLinkRef(count, toRef(obj, "count"));

count.value++;

console.log(count.value); // 1
console.log(obj.count); // 1
```

**Comment by JensDll** [comment]
The only real solution should be `obj.count = count` as this is just a TypeScript limitation and you shouldn't have to add an extra function for something that would work in JavaScript. The best bet is probably to typecast `Ref` as `any`:
```ts
obj.count = count as any;
```
That being said this is something that can be upstreamed to TypeScript and there is already a suggestion in https://github.com/microsoft/TypeScript/issues/43826. Might be good to leave a reaction there :yum:

**Comment by joakimriedel** [comment]
@JensDll for me the performance penalty would be worth it,  I do think this wrapper would be inlined however. 

The reason not to do `as any` is that you lose any compile time enforcement, a bad refactor or merge could easily break the code at runtime and not compile time, which is why I love using Typescript in the first place. 

Thanks for the link, that Typescript suggestion would be excellent and upvoted. Until then, I'll continue using my little helper wrapper 😄

**Comment by JensDll** [comment]
That is fair, for me `toRef` looks a bit out of place however as it seems unrelated to assigning a value to an object. Might as well pass the object key directly. Extending your function my suggestion:
```ts
function safeLinkRef<
  Target extends object,
  Source extends Ref<Target[KeyTarget]>,
  KeyTarget extends keyof Target
>(target: Target, source: Source, key: KeyTarget) {
  target[key] = source as any;
}

safeLinkRef(obj, count, "count");
```

**Comment by antfu** [comment]
I would say this operation itself is not type-safe and might even be an anti-pattern. You are basically swapping an internal `number` with a `Ref<number>` - even the auto unwrapping would work, I still do not recommend the usage. I think this is out-of-scope of VueUse. Thanks
