### ISSUE TITLE
Memoize results based on arguments in createSharedComposable 

### ISSUE THREAD

**Issue by matt-snider** [vueuse/vueuse#878]
Hi!

Firstly, thanks for maintaining such a great collection of utilities. It's always the first place I check before implementing a composable myself, and very often, I don't end up needing to because you guys already have :-) 

I'm wondering if it would make sense for `createSharedComposable` to memoize the result based on the arguments. This definitely makes sense in my use case, and I can't think of a situation where you wouldn't want this. The following, for example, seems incorrect to me, but that's the way it works currently:

```ts
// Loads product 42 and provides some methods on it
const { product42, updateProduct42, deleteProduct42 } = useProduct(42);
// Result is cached due to using createSharedComposable, so this will still be product 42
const { product43, updateProduct43, deleteProduct43 } = useProduct(43);
```

This is what I'm using right now to overcome this:

```ts
import { effectScope, EffectScope } from "vue-demi";
import { tryOnScopeDispose } from "@vueuse/core";
import { values } from "lodash/fp";


type AnyFn = (...args: any[]) => any;
type ResolverFn<Fn extends AnyFn> = (...args: Parameters<Fn>) => string;

const defaultArgumentResolver = (...args: any[]) => values(args).join("_");

/**
 * Make a composable function usable with multiple Vue instances.
 *
 * @see https://vueuse.org/createSharedComposable
 */
export default function createSharedComposable<Fn extends AnyFn>(
  composable: Fn,
  memoizeResolver: ResolverFn<Fn> = defaultArgumentResolver,
): Fn {
  let state: Record<string, { subscribers: number, scope: EffectScope, value: ReturnType<Fn> }> = {};

  return <Fn>((...args: Parameters<Fn>) => {
    const key = memoizeResolver(...args);
    if (!state[key]) {
      const scope = effectScope(true)
      const value = scope.run(() => composable(...args))
      state[key] = { subscribers: 1, scope, value};
    } else {
      state[key].subscribers += 1;
    }

    tryOnScopeDispose(() => {
      state[key].subscribers -= 1;

      const { scope, subscribers } = state[key];
      if (scope && subscribers <= 0) {
        scope.stop()
        delete state[key];
      }
    })

    return state[key].value;
  })
}
```

So in the example from above, we'd use it as follows:

```ts
export default createSharedComposable(function useProduct(id: number) {
  const product = ref<Product>();
  // Load product
  // Define methods, etc
  return { product, /* methods */ };
});
```

This would work fine with the default memoization resolver, but if we have more complicated arguments, like `MaybeRef<number>`, we'd need to specify the second parameter.

```ts
export default createSharedComposable(function useProduct(id: MaybeRef<number>, loadImmediately = true) {
   // Implementation
}, (id, loadImmediately = true) => `${unref(id)}_${loadImmediately}`);
``` 

Anyways, I'm just looking to get some feedback on this and could open a PR if you think the idea seems good, even if the implementation needs some work.

**Comment by spaceemotion** [comment]
Was about to open an issue around this and saw this was an older issue. I frequently come across this pit-fall since the current version of `createSharedComposable` allows arguments. It doesn't error out and say "beware that if you do this, all instances will be shared, and arguments get ignored". The docs also don't have a warning for this.

**Comment by matt-snider** [comment]
It's a good idea to include in the docs. You could also give the approach described above a try. I can't reopen this but maybe a maintainer could do that

**Comment by ilyaliao** [comment]
Hi, I just found this. Is there a minimal reproduction that can trigger an error? I just tried it but didn’t see any errors.

If it’s confirmed to be a bug, I’d be happy to reopen it and investigate :)

**Comment by matt-snider** [comment]
Hey @ilyaliao This isn't a bug. 

As @spaceemotion wrote:

> I frequently come across this pit-fall since the current version of createSharedComposable allows arguments. It doesn't error out and say "beware that if you do this, all instances will be shared, and arguments get ignored". The docs also don't have a warning for this.

The solution I've suggested above provides a version which considers the arguments

**Comment by spaceemotion** [comment]
Just wanted to post an update on this. We just experienced quite a breaking bug with this implementation:

When the passed argument changes (e.g. you passed a ref/computed that's referring to a prop etc..), the system breaks - the original return values are still referencing the prior instance.

**Comment by OrbisK** [comment]
@spaceemotion can you please open a new issue with a reproduction via https://playground.vueuse.org/?

**Comment by spaceemotion** [comment]
@OrbisK not sure if it's relevant tbh. My issue is with the custom composable shared above, and not with a utility that's already inside of VueUse.

Just wanted to mention it as this thread basically says that there's a workaround - with a provided solution - but said solution has quite a few caveats.

I'm not sure if @matt-snider has run into this one yet, and would love to hear about a potential fix if they have.
