### ISSUE TITLE
[question] What is best practice to run client side code in nuxt 3

### ISSUE THREAD

**Issue by jd-0001** [vueuse/vueuse#881]
Hello,

I am new to Nuxt3 but previously used vueuse. As this time I have to use nuxt I have some difficulties using client composable like `useWindowSize`.

I am trying to apply class-based on windowSize but it doesn't feel reactive because code first runs on a server in nuxt.

Here is sample codesandbox: https://codesandbox.io/s/infallible-glade-oiynv?file=/app.vue

In the demo, if I want to hide sidebar in `<1264px` then on reload it always stays visible.

As I just use windowSize to add class, it will be better if we don't have to do some complex things like watching multiple things etc.

Regards.

**Comment by namcodes** [comment]
i think it can't use window object in ssr mode

**Comment by antfu** [comment]
Yes, you can't get the window size on server side. You can use `initialWidth` and `initialHeight` to provide fallback in SSR.

**Comment by jd-0001** [comment]
If I set `initialWidth` to 0 it always stays the 0. Can't it be reactive?

**Comment by jd-0001** [comment]
After checking the source code I noticed that `useWindowSize` updates on `resize` event listener.

Can I trigger it manually when window is available so it can recalculate the width & height?
