### ISSUE TITLE
useIntervalFn not recognized by PHPStorm

### ISSUE THREAD

**Issue by frankykubo** [vueuse/vueuse#896]
**Version**: 6.7.5
**IDE**: PHPStorm 2021.2.3
**OS**: Win 10

**Problem**:
```
import { useIntervalFn } from "@vueuse/core";
```
as you can see, I am importing useIntervalFn from @vueuse/core. I didnt notice when it started to happen, but now, my IDE says "_cannot resolve symbol 'useIntervalFn'_" and it is red as on image below.
![image](https://user-images.githubusercontent.com/50501921/140277726-4c907dce-339b-4f75-b658-73f9e27f105e.png)

What is weird? When I CTRL+click on red function title, it would jump to function declaration in _index.d.ts_ located at _node_modules/@vueuse/core/node_modules/@vueuse/shared_ directory.

I tried to reload caches, reinstall packages, nothing helped. App still compiles without problems.

Does someone know any solution for this? Thank you.

**Comment by frankykubo** [comment]
Anybody facing this issue as well?

**Comment by linkurzweg** [comment]
Exact same issue here with current version of Webstorm when using `useDebounceFn`. Would be really nice if this could be fixed.

![image](https://user-images.githubusercontent.com/4902517/160847541-eec406e8-bf92-41ea-9f11-57f12c1a59c9.png)

**Comment by prokhn** [comment]
Same with watchDebounced

**Comment by webdesignberlin** [comment]
Seems like a Problem with shared package? If i try to import via [Playground](https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRAAEA3AV0XOUQHooB7AJ0IBoRymAbIgCwBd+YZGlr0AJtgB0yGAE9IsKeMSlaZStTqMWIdiuRQmASzD9jDbEQDCDLl0RRzlgAQMAZi5Q1s5iFxcANUoXWzwwBmRjZ2wXAFVzLmjjFD0QUkQmKMsiABkIfhR+NOQGTihCNBBZBWgYEABfAF12d2MHVDRQAEEwMCkKStBC8K4CypAAHnFjUgAdWJd4E3EAXjmQAD8Xdy4GAHcAWkYA+AgwQ4AWDYWXFzAxivWQRl9EX2P3wqYXaMQ8ZCfN5MG6LXjPQwsd6gu7uSz8Z54SwMGEuAB8txck1szBmuEKLjGACNEFxngANDYuNCkfyUZ4ADyptAxi2xDFxxnxiEJEBJZI2AE0qTS6YhnnJmazJrQZqQ0SUjKZilVjOFmPwXMAXFoALJlGisHU0AAiiCJZWwFQAYrEGjsmAw8C4AOQaKg0ejMRAugDcCzVESYmpxTDx4wdTtdUloofDhQGlD9CwWr2Qmu1DKNchc9tWxsQ+q0AAoAJQpq2WdM7DkufNaM0W8hWxC24tlutorWYu53BkDMV1lyXAAMY8uAEZ-Ys7g0jaOx6Xpz2awwy412HGueNE0MQCMHuMiNNZpi4b5EcjUUT4M8kvABIcAKxjlziCBMGBod+f59j1G7IgDLPNsJyooUDIIhsFTAqiYDPAATNeuKZM8jrNio4igqydyTMgkCxBBUEgJcDJcBsaLANqtJcCEDQNDK+EQNgOFYkxhFAcRyDOj+X73o+ACcr68WgDCKNEch-lSeDPPwhxISAaJFjQWrasSpK5gxtDsdKsqzAq7CQsqRCBhqWpvogbTYIgAAKjrCLmkbOi6gwuhWKhWbZ9nIMWwCYupXBoC4ADK-AmNg8CsJiNGUEFABy5B4CSTBRdgDSlo09FAA):   it also breaks with **SyntaxError: The requested module '/new/@vueuse/shared@v8.3.0/dist=es2019,mode=imports?from=@vueuse/shared' does not provide an export named 'bypassFilter'**

**Comment by jodyhoonstarr** [comment]
Workaround: find the vueuse shared directory in your intellij based editor, right click, and "Mark directory as" -> "Not Excluded".
E.g. in the project window right click `node_modules/@vueuse/core/node_modules/@vueuse/shared` then mark not excluded

More info: A [post from the intellij team](https://intellij-support.jetbrains.com/hc/en-us/community/posts/5165894723986/comments/5181174853906) indicates that non-direct dependencies are not indexed by the editor by default. In that same thread they indicate that this behavior isn't likely to change in the future.
