### ISSUE TITLE
new function useOnClient or something like watchWithFilter to run on client only

### ISSUE THREAD

**Issue by jd-0001** [vueuse/vueuse#912]
Hi,

I have used vueuse in my VueJS project a lot and recently I started working on Nuxt (SSR), the problem I am facing is I am having a hard time using some composable function that runs on a client like `useWindowSize`. You can check this conversation: https://github.com/nuxt/framework/discussions/1702

I asked about the same but didn't get much luck:
https://github.com/vueuse/vueuse/issues/881
https://github.com/nuxt/framework/discussions/1702

I think it will be great to provide a guide or something to quickly get started with SSR and vueuse.

**Comment by antfu** [comment]
You can do `import { isClient } from '@vueuse/core'`

**Comment by jd-0001** [comment]
Hi,

I really respect your time but I am not sure have I will implement this with `useWindowSize`, can you please provide me an example by editing this [codesandbox](https://codesandbox.io/s/nuxt-vueuse-windowsize-query-328mo).

Thanks.

**Comment by alokVishu** [comment]
I am also interested in example of how I can leverage isClient with client composable in nuxt.

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/141057828-7cc92097-35a3-4723-8f62-8d3279185bbd.png)
![image](https://user-images.githubusercontent.com/11247099/141057853-55aabed3-10d2-46fc-afb5-3b83bc5d05c1.png)

I have no problem using it in vitesse-nuxt3

**Comment by antfu** [comment]
And I think your CSB also works for me 
![image](https://user-images.githubusercontent.com/11247099/141058697-53ed4776-a373-48fd-a8bd-8220f177d63e.png)

(yes it's initially zero since it comes from the server-side, you will need to wait for client-side hydration to have it updated.

**Comment by jd-0001** [comment]
Thanks for taking the time to inspect the issue.

The problem is class added based on windowWidth is not updating. If you open the CSB in screen `> 1200` then `disabled` class still applies.

I added note below box for more info.

Regards.

**Comment by jd-0001** [comment]
Hi,

I tried the same with `vitesse-nuxt3` and still getting the same result.

You can find the repo here: https://github.com/jd-0001/vueuse-vitesse-nuxt.git

NOTE
---
* issue is **class is not applied based on windowSize**
* issue exists on reload. Works fine if we resize.

**Comment by jd-0001** [comment]
Does anyone have easy to use solution?

**Comment by alokVishu** [comment]
Facing same issue.

**Comment by vrushank** [comment]
@jd-0001 Did you find any way? I'm facing the same issue.

**Comment by jd-0001** [comment]
not yet

**Comment by okxiaoliang4** [comment]
@jd-0001 Try to use version >=7.0.2

I think the commit has solved the problem
https://github.com/vueuse/vueuse/commit/42ae437839b0e4d16d54bc1dab12b565dac5a43b

**Comment by jd-0001** [comment]
Hi @okxiaoliang4 

Yes, I guess. For completeness can you help me with the issue I am facing in this [codesandbox](https://codesandbox.io/s/nuxt-vueuse-windowsize-query-328mo)?

I am not sure how to make it work.

**Comment by kedniko** [comment]
In my specific case I solved it by using a [nuxt hook](https://nuxt.com/docs/api/advanced/hooks)

  ```ts
import { breakpointsTailwind, useBreakpoints } from '@vueuse/core'
const breakpoints = useBreakpoints(breakpointsTailwind)

  const mdAndUp = breakpoints.greaterOrEqual('md')
  const lgAndUp = breakpoints.greaterOrEqual('lg')
  const stylesProperties = ref({})

  const nuxtApp = useNuxtApp()
  nuxtApp.hook('app:suspense:resolve', () => {
    watch([mdAndUp, lgAndUp], () => {
      calcStyles()
    }, {
      immediate: true,
    })
  })
```

**Comment by awacode21** [comment]
The issue got closed but now we are in year 2023 and i am still experiencing the issue.

**Comment by the94air** [comment]
Had a similar issue, but pretty sure you can avoid all this if you put your logic inside `onMounted` as it runs in client only.

**Comment by soylomass** [comment]
This bug still happens. Sadly one can only try workarounds.

**Comment by TalkativeGuy** [comment]
The issue still persists. ClientSide component is not an option in my case because it's a crucial part for SEO on the page. Why if I simply go ahead and type this
```ts
const windowWidth = ref(0);
const setWindowWidth = () => {
  windowWidth.value = window.innerWidth;
}
onMounted(() => {
  setWindowWidth();
  window.addEventListener("resize", setWindowWidth);
});
onUnmounted(() => {
  window.removeEventListener("resize", setWindowWidth);
});
```
it works perfectly with SSR, but this
```ts
const { width: windowWidth } = useWindowSize({ initialWidth: 1, initialHeight: 1 });
```
doesn't work in SSR at all?
