### ISSUE TITLE
Questions about internationalization

### ISSUE THREAD

**Issue by lgd8981289** [vueuse/vueuse#917]
Vue has a large number of developers in China. As vue's function library, vue-use provides a large number of commonly used functions, which greatly facilitates our development, but many people will increase the cost of learning due to document language problems.

Request vue-use Is there any plan to internationalize documents?

**Comment by antfu** [comment]
Sorry it's not on our roadmap, but we are open for community translations.

**Comment by antfu** [comment]
Sorry it's not on our roadmap, but we are open for community translations.
