### ISSUE TITLE
Upgrading to TS 4.5 results in `PostMessageOptions` not found

### ISSUE THREAD

**Issue by Shinigami92** [vueuse/vueuse#932]
`typescript@4.5.2`, `@vueuse/core@6.9.1`

![image](https://user-images.githubusercontent.com/7195563/142388158-4785be24-5361-423b-bd04-8f80f7893bc8.png)

```node
node_modules/@vueuse/core/index.d.ts:2983:34 - error TS2304: Cannot find name 'PostMessageOptions'.

2983         (message: any, options?: PostMessageOptions | undefined): void;
                                      ~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by Shinigami92** [comment]
I locally tried to upgrade to typescript 4.5.2 in my vueuse fork and now there is this line:

```ts
// <vueuse fork>/packages/core/dist/index.d.ts line 2983
        (message: any, options?: StructuredSerializeOptions | undefined): void;
//                               ~~~~~~~~~~~~~~~~~~~~~~~~~~ Cannot find name 'StructuredSerializeOptions'.ts(2304)
```

So it's another interface but same problem 🤔

**Comment by rumaan** [comment]
Yes. Same issue here with `typescript@4.5.2` and `@vueuse/core@6.9.1`

![Screenshot 2021-11-19 at 14 53 49](https://user-images.githubusercontent.com/18492868/142598798-0f256e33-ae3a-4686-85ac-7b1b7d2d715f.png)

**Comment by Shinigami92** [comment]
Ah there is a new interface that differs between TS 4.4 and 4.5
I think we need to define the return type manually so it can pick it up correctly from the current installed TS version

I will try to create a PR
