### ISSUE TITLE
I don’t quite understand the usage of useTimeAgo

### ISSUE THREAD

**Issue by rogepi** [vueuse/vueuse#936]
![image](https://user-images.githubusercontent.com/56425392/142603448-bbf7dcd7-6747-4637-b53c-cd4887ce88ee.png)

I expect it should be **TimeAgo : last month**

**Comment by wheatjs** [comment]
This is because in Javascript the month starts at 0. So January would be 0 and December would be 11. Since you put 10 for the month, that would be November, which in this case the output of useTimeAgo is correct. Change 10 to 9 and you will get "last month" as the output
