### ISSUE TITLE
`useClipboard` `updateText` throws an error in Firefox 91

### ISSUE THREAD

**Issue by Shinigami92** [vueuse/vueuse#937]
We got an Sentry error in our application that a user encountered an error with `t.clipboard.readText is not a function`

I found out that this was coming from this:

https://github.com/vueuse/vueuse/blob/2e9dd3d6106cc690cb6ea2590d41089838f56367/packages/core/useClipboard/index.ts#L59-L64

There is already a typescript expect error annotation 🤔 
Maybe we should get rid of that and maybe there needs to be a fix

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/142738627-b7454c75-bd36-4859-9573-9275bf5dcce9.png)

I think we could add this check to `isSupportedFlag` and bypass the call if it's not supported

**Comment by Shinigami92** [comment]
Will close this for now due to #941 is merged.

I can test it hopefully tomorrow, if there is a problem in the future, I can reopen this issue anyways :)
