### ISSUE TITLE
'useDark' is not defined.eslintno-undef - nuxt 3

### ISSUE THREAD

**Issue by productdevbook** [vueuse/vueuse#942]
<img width="1024" alt="CleanShot 2021-11-21 at 09 58 31@2x" src="https://user-images.githubusercontent.com/38668796/142752896-fae8c906-15f7-4ab0-a779-b50b34ac5276.png">

**Comment by antfu** [comment]
You will need to disable this rule. ESLint does not understand `<script setup>` and this has already been covered by TypeScript. Meanwhile, please use the right repo to open the issue.
