### ISSUE TITLE
Failed to compile with useFocusTrap integration

### ISSUE THREAD

**Issue by rumaan** [vueuse/vueuse#944]
TS Version: `4.5.2`
Vueuse version: `7.0.0`

<img width="1411" alt="Screenshot 2021-11-22 at 10 19 13" src="https://user-images.githubusercontent.com/18492868/142802936-bc6502a0-9a1e-41a2-8275-8d4846b5acde.png">
<img width="1074" alt="Screenshot 2021-11-22 at 10 19 41" src="https://user-images.githubusercontent.com/18492868/142802942-ac29eadf-84a3-4354-930c-cf772d07e9ea.png">

**Comment by rumaan** [comment]
Changing the import statement in useFocusTrap/component.d.ts from 
`import { RenderableComponent } from '@vueuse/core/types'`
to:
`import { RenderableComponent } from '@vueuse/core'`

Fixes this issue though

**Comment by antfu** [comment]
Fixed in v7.0.1
