### ISSUE TITLE
feat: useTruncateString formatter

### ISSUE THREAD

**Issue by bradley-varol** [vueuse/vueuse#948]
Just a little method that I use often to truncate text. If it's considered useful, i'd like to contribute :)

```js
truncate(string, maxLength, append = '...') {
    maxLength = maxLength - append.length;
    return string.length > maxLength ? string.substring(0, maxLength) + append : string;
},
```

**Comment by wheatjs** [comment]
Hmm, not sure there is much in terms of reactivity to be provided here though. The function might fit better in a general util library,
