### ISSUE TITLE
UseVirtualList may show empty page

### ISSUE THREAD

**Issue by menghany** [vueuse/vueuse#954]
When the array content decreases，view may be empty,
I I checked the source code  find 'from' is more than "to"
After I added the check, there is no problem, but I think it is not elegant。
![A24D5EBE-4DDE-4ea1-903D-1CE5F9B67519](https://user-images.githubusercontent.com/13767186/142982279-b71c801e-7aef-445a-aa8b-29d11c7b5cfa.png)

**Comment by wheatjs** [comment]
Could you provide a reproduction

**Comment by menghany** [comment]
This is very accidental, I tried many times with codesanbox, only a few times appeared。
https://codesandbox.io/s/dazzling-chebyshev-deq5s?file=/src/components/HelloWorld.vue

**Comment by menghany** [comment]
> Could you provide a reproduction

hey,I have reproduced it。Please check for me
https://codesandbox.io/s/misty-http-y41cu?file=/src/components/HelloWorld.vue
Please Scroll list to middle, enter numbers to input eg:1 or 123....

**Comment by JessicaSachs** [comment]
Your filter function for `filteredList` is incorrect. If you print it out, you'll see that the `filteredList` has 0 items in it. Once you start typing in the input, the `val` you're using to filter the list becomes a string and then the filter works as expected.

https://codesandbox.io/s/gracious-raman-glhnw?file=/src/components/HelloWorld.vue

<img width="362" alt="Screen Shot 2021-12-23 at 12 39 10 PM" src="https://user-images.githubusercontent.com/2801156/147275073-f61a03b0-6054-4911-8abb-5103b4442995.png">

You can either say
```ts
const val = ref('') // this will allow the .includes check to work
```

or

```ts
const filteredList = computed(() =>  {
  return val.value ?  allItems.filter(i => i.includes(val.value)) : allItems
})
```
```

After I fix the `filteredList`, I can't reproduce the issue anymore. Can you send a different reproduction or let me know if this is fixed?

**Comment by menghany** [comment]
> Your filter function for `filteredList` is incorrect. If you print it out, you'll see that the `filteredList` has 0 items in it. Once you start typing in the input, the `val` you're using to filter the list becomes a string and then the filter works as expected.
> 
> https://codesandbox.io/s/gracious-raman-glhnw?file=/src/components/HelloWorld.vue
> 
> <img alt="Screen Shot 2021-12-23 at 12 39 10 PM" width="362" src="https://user-images.githubusercontent.com/2801156/147275073-f61a03b0-6054-4911-8abb-5103b4442995.png">
> 
> You can either say
> 
> ```ts
> const val = ref('') // this will allow the .includes check to work
> ```
> 
> or
> 
> ```ts
> const filteredList = computed(() =>  {
>   return val.value ?  allItems.filter(i => i.includes(val.value)) : allItems
> })
> ```
> 
> After I fix the `filteredList`, I can't reproduce the issue anymore. Can you send a different reproduction or let me know if this is fixed?

I tested your demo, scrolled the container to the middle part, and entered the filter content, but it is still invalid

**Comment by SilenceDN** [comment]
核心的问题是这里
```ts
const getOffset = (scrollTop: number) => {
    if (typeof itemHeight === 'number')
      return Math.floor(scrollTop / itemHeight) + 1
  ........
}
````
当过滤数组后 数组的长度没有直接算出来的多，而当你的 itemHeight 是函数时就会走下面的数组循环 此时的offset计算就不会有问题
解决办法是:
1.itemHeight的值使用函数返回
2.尝试修复这个bug

修复代码如下 大概是这么个意思
```ts
const getOffset = (scrollTop: number) => {
    if (typeof itemHeight === 'number'){
      if (source.value.length * itemHeight < scrollTop) return 1;
      return Math.floor(scrollTop / itemHeight) + 1
    }
  ........
}

```

**Comment by VIIGstar** [comment]
May be you can try:

```
useVirtualList(optionsFilter, {
  itemHeight: (index: number) => {
    if (optionsFilter.value.length <= index) {
      return 0
    }

    return 40
  },
})
```

**Comment by barzie01** [comment]
> Void to fixed your itemHeight. May be you can try:
> 
> ```
> useVirtualList(optionsFilter, {
>   itemHeight: (index: number) => {
>     if (optionsFilter.value.length <= index) {
>       return 0
>     }
> 
>     return 40
>   },
> })
> ```

I had the same issue and solution above fixed it.
@VIIGstar many thanks!
