### ISSUE TITLE
Access data from `useAxios` inside setup

### ISSUE THREAD

**Issue by kr-apps** [vueuse/vueuse#955]
Hello,

I'm trying to get some data from an API using the composable function  `useAxios`, my code is the next:

```vue
<script setup lang="ts">
import axiosService from '~/services/axiosService'

const { data: users } = useAxios('/users', axiosService)

console.log(users) // <--- this got undefined
console.log(users.value) // <--- this also got undefined

</script>

<template>
  <div>
      {{ users }} <!--- this works just fine -->
  </div>
</template>
```

In this way I can use the `users` variable in the template without problems, however if I want to use that variable inside the setup I got `undefined` and I can't access the data to make something with, it for example to loop the users using `.map` function. 

I'm getting used to the composition api and I think maybe the solution is related to the new reactivity system, but I don't know if I doing something wrong nor I missing something.

**Comment by wheatjs** [comment]
`data` is a reactive object and will not immediately have data. You should use watch instead to wait for the data to be there. Try something like this
```html
<script setup lang="ts">
import axiosService from '~/services/axiosService'

const { data: users } = useAxios('/users', axiosService)

watch(users, (users) => {
  console.log(users)
})
</script>

<template>
  <div>
      {{ users }} <!--- this works just fine -->
  </div>
</template>
```

**Comment by kr-apps** [comment]
Thank's @wheatjs that was the part I was missing.
