### ISSUE TITLE
什么时候出中文档

### ISSUE THREAD

**Issue by zjp693** [vueuse/vueuse#966]

**Comment by antfu** [comment]
I don't know either

**Comment by zjp693** [comment]
好好希望有一个中文文档呀 这里面的工具集很好用 可惜全是英文的

**Comment by antfu** [comment]
说实话每个文档也没几个字，Google 翻译一下应该还行吧？如果真的这么需要的话可以组织做个社区翻译，我们团队暂时不会把经历放在这个上面。
