### ISSUE TITLE
feat: usePopper integration

### ISSUE THREAD

**Issue by jd-0001** [vueuse/vueuse#971]
[PopperJS](https://popper.js.org/) is an awesome library for creating popover or tooltips if not using any UI framework.

It has an official react wrapper but nothing for vue.

Regards.

**Comment by wheatjs** [comment]
Well this library already exists for it https://github.com/Akryum/v-tooltip

**Comment by jd-0001** [comment]
Yes, but I fear it is not actively maintained like vueuse.

But if you think it will be fine then I will try using that library.

May I know shall I keep this open for future implementation or close it?

**Comment by wheatjs** [comment]
The author is part of the Vue core team and the library is being maintained. I don't think you'll run into many issues using it
