### ISSUE TITLE
How to use `useStorage` conditionally?

### ISSUE THREAD

**Issue by r-priyam** [vueuse/vueuse#974]
Hello there, I want to use `useStorage` conditionally, I mean, If something is `true` then only I want to use it else No. I have searched around for the possible solution but couldn't find any. Any help please? :)

**Comment by r-priyam** [comment]
To be specific, the main problem I am facing here is `RemovableRef`
```vue
<template>
    <div v-if="data !== null">
        {{ data.a }}
    </div>
</template>
<script setup lang="ts">
function getConditionalData() {
    if (...) {
    return useStorage('data-test', {
        a: '',
    });
   return null;
}}

const data = getConditionalData();
</script>
```
Errors at `{{ data.a }}` => `Property 'a' does not exist on type 'RemovableRef<{ a: string; }>'.ts(2339)`

How to get rid of this error please

**Comment by antfu** [comment]
```ts
function getConditionalData() {
    if (...) {
    return useStorage('data-test', {
        a: '',
    });
   return ref({ a: '' });
}}

const data = getConditionalData();
```
