### ISSUE TITLE
feat: useScroll, detect directions

### ISSUE THREAD

**Issue by pyncz** [vueuse/vueuse#976]
**Hey!**

I thought it would be cool to return the direction of the scroll as well (you know, all those ui things like navbar/back-to-top-button that pops up when scrolling up etc).

Is it ok if I create PR with this?

![Nov-26-2021 05-35-35](https://user-images.githubusercontent.com/32226573/143518183-076df9c7-c470-4641-a9c3-29f53df56c9a.gif)

**Comment by wheatjs** [comment]
Go for it!
