### ISSUE TITLE
Allow UseMouseInElement to listen to event listeners?

### ISSUE THREAD

**Issue by Fanna1119** [vueuse/vueuse#982]
I am wondering if it is possible to set up https://vueuse.org/core/useMouseInElement/
to listen to  https://vueuse.org/core/useMousePressed/ events.

So a use case would be to check if the mouse is moving in a element while being drag or right click drag etc

**Comment by wheatjs** [comment]
https://vueuse.org/core/usedraggable/ maybe this is what you are looking for?
