### ISSUE TITLE
Should the useSetup() test util be an exported ... ?

### ISSUE THREAD

**Issue by michealroberts** [vueuse/vueuse#984]
I've been writing some integration style composables on a project utilising the design patterns outline in this library, and using some of the composables.

For example, I have written a `useMount()` (not to be confused with the Vue 3 lifecycle hooks of a similar name) and wanted to utilise the useSetup() test composable from this library:

```ts
import {
  describe,
  expect,
  it
} from '@jest/globals'

import {
  useSetup
} from '@vueuse/core'

import {
  useMount
} from './'

describe('usePushNotification', () => {
  it('should be defined', () => {
    expect(useMount).toBeDefined()
  })

  it('should be defined', () => {
    it('', () => {
      useSetup(() => {
        // test something with useMount()
        useMount()
      })
    })
  })
})
```

Unfortunately, as you'll probably be aware - the "Module '"@vueuse/core"' has no exported member 'useSetup'.".

Is there any way that this could be sneaked out as a feature release in the next version please?

**Comment by antfu** [comment]
`useSetup` was written mainly for Vue 2's composition API caveat at the early stage, which is actually no longer needed. We should even remove it from our codebase at some point.

I am not sure what you are trying to achieve here if we could have come up with a set of more complete and systematic test utils, I am happy to introduce a new package like `@vueuse/test-utils`

**Comment by michael-observerly** [comment]
@antfu Ahh I see. Yeh it would be really beneficial to have a standardised way of testing composables that are dependent on being run inside of setup() ... I can't seem to reference anything in vue-test-utils@next or in @testing-library/vue ... or am I missing something ...

**Comment by michael-observerly** [comment]
> `useSetup` was written mainly for Vue 2's composition API caveat at the early stage, which is actually no longer needed. We should even remove it from our codebase at some point.
> 
> I am not sure what you are trying to achieve here if we could have come up with a set of more complete and systematic test utils, I am happy to introduce a new package like `@vueuse/test-utils`

@antfu Ahh I see. Yeh it would be really beneficial to have a standardised way of testing composables that are dependent on being run inside of setup() ... I can't seem to reference anything in vue-test-utils@next or in @testing-library/vue ... or is there already a way to test composables without the need for "setting up" ...

**Comment by prazdevs** [comment]
Curious if this is still considered. While I'm not a fan of unit testing components in a Vue3 environment, unit testing composables seems more important. As I've always yoinked this useSetup/useMount from vueuse, I'd also definitely like it to be exported as a util library somewhere. :)

**Comment by michael-observerly** [comment]
@antfu Will something like this be incorporated into your vitest package? I feel like it's really useful and like @prazdevs I always yoink it (steal it) when I need to test composables on other projects ... it's so much easier than having a test component for each composable ... is that perhaps a tad lazy?

**Comment by prazdevs** [comment]
Vitest is framework agnostic so I dont think it would include Vue-specific features like this. The great part with these utility functions is the TS integration that is clean.
