### ISSUE TITLE
`set` with 3 parameters

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [vueuse/vueuse#986]
Why is it that set with 3 parameters does not handle `ref` but with 2 it does?
For example
```js
const a = ref(0)
set(a, 1)
console.log(a.value) // 1
```
totally fine, but
```js
const a = ref({ foo: 0})

set(a, 'foo', 1) // Argument of type '"foo"' is not assignable to parameter of type 'keyof Ref<{ foo: number}>'
```
instead you have to do this
```js
const a = ref({ foo: 0})

set(get(a), 'foo', 1)

console.log(a.value.foo) // 1
```
For me this is unintuative

**Comment by wheatjs** [comment]
This is the intended behavior.

**Comment by sschneider-ihre-pvs** [comment]
But why? Why is there a difference in usage of the first argument just because I have a 3rd argument?
