### ISSUE TITLE
useMouse return pageX and not clientX like touch events

### ISSUE THREAD

**Issue by lavolpecheprogramma** [vueuse/vueuse#988]
Hi and thanks for this awesome project!
I want to ask why useMouse has different behaviour on touch and mouse events, in particular return pageX and pageY value on mouse event and clientX and clientY on touch.
Can be the returned value choosed by the user through an option (pageX or clientX)?
In case of a custom cursor, for example, we need the clientX/clientY value.

Thanks in advance

**Comment by antfu** [comment]
Sounds like a bug, PR welcome! Having a config to choice pageX and clientX is a good idea!

**Comment by okxiaoliang4** [comment]
I think it is possible to return clientX,clientY directly, no additional configuration is needed~
