### ISSUE TITLE
useStorage initialValue 都是必填的，无法获取storage中的值

### ISSUE THREAD

**Issue by EnoND** [vueuse/vueuse#991]
在官方的createGlobalState 示例代码中
`
export const useGlobalState = createGlobalState(
  () => useStorage('vue-use-local-storage'),
)
`
useStorage 也是 一个参数，而在core/index.d.ts中，useStorage参数类型定义，initialValue都是必填的

**Comment by okxiaoliang4** [comment]
halo，这个是文档问题，`useStorage`的初始值是需要传递的~
